### ISSUE TITLE
Could not open / parse mpdURL

### ISSUE THREAD

**Issue by RoyPh78** [peak3d/inputstream.adaptive#10]
My Internet Service Provider (ISP) provides an API to access the webtv streams ([WebTV API docs](https://webtv-api.xs4all.nl/2/doc/doc)). I'm writing a small plugin for Kodi to be able to watch these streams, using inputstream.adaptive.

My ISP provides one public channel (which plays without issues) and a number of channels which are only available for its clients (IP based, so for people which are not clients, these streams will not be accessible). These streams are DASH with Widevine (I do have libwidevinecdm.so installed in the .kodi/cdm folder). From the API I get a stream URL and a Licence URL, which I both pass to inputstream.adaptive.

The plugin I'm creating can be found here (note again that the protected streams are only visible for clients of my ISP which actually have a subscription for TV): [Kodi XS4All WebTV plugin](https://github.com/RoyPh78/plugin.video.xs4me)

When I try to play one of these streams protected with widevine, I see that an .mpd file is downloaded from the provided stream URL. After this download is finished, inputstream.adaptive reports the ERROR: "Could not open / parse mpdURL", see the Kodi.log file below.

I've analized the network traffic (using TCPdump / wireshark) and I saw that requests are made to the stream URL (I see http HEAD and http GET requests, both with status 200 (OK)). After these requests, no communication takes place anymore (I expected to see requests to "Historywv-$RepresentationID$.dash" and next to "Historywv-$RepresentationID$-$Number$.m4s", but that doesn't happen).

I'm using Kodi 17.1 RC1 (compiled with --enable-debug) on a Raspberry Pi2 (OS: Raspbian) with inputstream.adaptive 1.0.7.

The Kodi log can be found here: [Kodi.log](http://pastebin.com/mGNhfCHn)
The .mpd file which is downloaded from the specified stream URL (from the stream which corresponds with the above Kodi log file) can be found here: [manifest.mpd](http://pastebin.com/2zFaA9vK)

To verify that the streams from my ISP are OK, I created a small PHP web site, using the same webtv-api from my ISP, using [Bitmovin HTML5 Player](https://bitmovin.com/html5-player/) to play the streams. With this player, the streams play correct.
For anyone interested, the .PHP file can be found here: [Click here](http://pastebin.com/stKBntHV)

If you need any additional info, please let me know. I hope you can help.

**Comment by peak3d** [comment]
Hi, you need the libssd_wv.dll/so for the encryption.
You can find the sources in this git: https://liberty-developer/inputstream.adaptive.

Clone / go into folder wvdecrypter / mkdir build / cd build / cmake .. / make
The resulting [lib]ssdwv.[so/dll] must be copied to this place:
09:46:31.451 T:1488974832   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /home/pi/.kodi/cdm

**Comment by RoyPh78** [comment]
Thanks for your quick reply.

I now have libssd_wv.so installed (I assumed that only libwidevinecdm.so was enough). The "Could not open / parse mpdURL" error is gone now.

Now the next problem occurs: the license server returns an error (HTTP status 500).

The corresponding kodi log can be found here: [kodi.log](http://pastebin.com/60BQtE53)

**Comment by peak3d** [comment]
The inputstream.adaptive.license_url for com.widevine.alpha is a template wich has to be designed in a way that the request fits to the one expected by your provider. The challenge sent to the provider could be Base64 in GET string / B64 in post payload body or raw bytes in body (or somehow in a form or in JSON)

It contains of 4 parts: [URL]|Header|Post-Body|[How to find response in answer]

Easiest way would be if you send me what you have for the license call and I can build the correct template for this one. Pls. use a mail for this.

**Comment by RoyPh78** [comment]
I will send an email with the info I have tomorrow. Is the "programmer" address (as listed on your website) the correct address to use?

**Comment by peak3d** [comment]
Ah, sorry, I thougth that my mail is visible here in git.
You can use pfau@peak3d.de

**Comment by RoyPh78** [comment]
I've send you an email with the info I have.

Thanks.

**Comment by RoyPh78** [comment]
The problem is solved by using the correct template for the License URL in my plugin.

Thanks for the great support.
