### ISSUE TITLE
[20.2.0-Nexus and up] Different behavior of Base64 decoder

### ISSUE THREAD

**Issue by dobo90** [peak3d/inputstream.adaptive#1003]
After updating inputstream adaptive to 20.2.1-Nexus one of video addons has stopped working. Git bisect has shown that commit **1b9e2d01 [cleanup] Rework to new utils** breaks it. After some hours of digging it came out that stream provider sends a license which contains dummy backslash characters.

An example of received license:
```CAISrAIKOAoQy5fKYgG+uSStdsbS96gssBIQy5fKYgG+uSStdsbS96gssBoAIAEoADiAxgpAgMYKSLnA2ZQGEhAIARABIIDGCiiAxgowgMYKGmYSEOgHs3r6cR5fBR44b13GxesaUNWnUdImlZpVZ8g3SD7VKZERdRpb0SufKydBvd8dJns58+xHX+8mDlYftJtyFtHn7DBJIJRav1Plbr\/\/PTg5VEBo04qzS1\/FZyXrNmuuxgGfIAEaaAoQpR2Xqj0qj0eG7arhwWUnCBIQoQiM8xrzulnMMYMcamv7GhoghPTvWTucrRqk0u1SeVtwOvPUXbqo33a6H4K0W5Nu6+ogAigBMgQIABAqQhIKEGtjMTYAAqMAka\/H06AAAAhiAlNEILnA2ZQGOOPclZsGUAAaINECAjuYsVVAtXt+EQnjlEwUsUfdZ9vPjt4vOpKZRvlqIoABP7CJwOKM5aMH29LsHI+2epEj+OpsHgwqSjDoZVzvB04RAX4NCU0cXHYeNKXHrwR1Nq+\/Z0GpDyTob1rrlJIyUNPF8jW+Mi2J+ZWlttkATg9uo4U7s4ptps1tIcvvqgI7lRTc\/qYBPgLMV43KY8+44Cn+H8DsX203BGqx26YR9uE6MwoxMTYuNS4wIEJ1aWx0IG9uIERlYyAxNSAyMDIxIDEwOjI3OjE3ICgxNjM5NTkyODE1KUABSrABAAAAAgAAALAABQAQka\/H0\/y8qNYAAABQAAAAEAAAAGIAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAqMAAAAAAAACowAAAAAAAAAAAAAAAAEAAAC4AAAAEAAAAMoAAAAQAAAA3AAAABAAAAAAAAAAAAAAAQoAAAAQPZgOBKXN7hbLxQkrB0WWSYol4jlADACnFN0WF96N029YAQ==```

As you can see for each '/' character there is a '\\' before it. It's probably because of the wrong escaping implementation in the stream provider. Anyhow b64_decode function (which was present in the code before mentioned commit) was ignoring backslashes.

So, after refactoring commit decoded Base64 license length is 712, b64_decode is 706. I've checked Python implementation and by default it ignores non-alphabet characters (so the length is also 706). As license is wrongly encoded stream isn't started and in logs we can see **License update not successful (no keys)**.

I've seen that current Base64 is copied from Kodi sources. I don't expect to fix it, it can be fixed by HTTP proxy in the addon. I've just wanted to mention about this issue as it made me few hours to fix it. Anyway, it's some kid of regression...

**Comment by CastagnaIT** [comment]
thanks there is need to investigate if the previous was a custom implementation
or if this this a bug since the current base64 encoding is same of kodi core
if needed should be fixed in both places

**Comment by CastagnaIT** [comment]
i checked the python implementation their code is more safe then our in kodi/isa
then i can backport their code that have more checks for decoding
as soon as possible i will provide a test build so you can give me feedback

**Comment by CastagnaIT** [comment]
@dobo90 here you can find test builds https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1006/4/artifacts
let me know

**Comment by dobo90** [comment]
Sorry, I had a busy weekend. I've compiled latest Nexus branch and the issue is fixed. Thanks, closing this!
