### ISSUE TITLE
CMAF Support

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1007]
This is an issue to track CMAF support in Inputstream Adaptive / Kodi

CMAF is basically fMP4 (fragmented mp4) + M3U8/Dash manifest + optional encryption (usually AES-CBC)
It allows a single set of media segments for many benefits (better caching etc)

Current Issues

1) 
CBCS support
Added in Inputstream 20 with PR: https://github.com/xbmc/inputstream.adaptive/pull/887
Unable to backport to 19 due to Kodi core needing changes for Android support
Technically, Kodi 19 support for other platforms could be possible - but not great having a feature that doesn't work on a certain platform (especially a big one like Android)
    
2)
Support for ignoring unsupported EXT-X-KEY in M3U8
The below will error out with LOGERROR, "Unsupported encryption method: SAMPLE-AES"
Due to the first EXT-X-KEY being for apple streaming (actual sample-aes)
The 2nd Sample-aes is for CMAF CBCS (Widevine)
If I remove the first line - we support the 2nd line already due to looking for the KEYFORMAT.

So, we just need to change the code to not fail on SAMPLE-AES, but to just ignore it.
I think i've had a PR about that in the past.
```
#EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-VERSION:6
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-MEDIA-SEQUENCE:5
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-START:TIME-OFFSET=-15,PRECISE=YES
#EXT-X-PROGRAM-DATE-TIME:2022-06-14T10:42:30.211Z
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://03b47c8e-5bdf-41cb-bbef-29be6a18de9e:813A1D12BE0A6D2475F810BEE5AFC5E2",IV=0x813A1D12BE0A6D2475F810BEE5AFC5E2,KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAZnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEYSEAO0fI5b30HLu+8pvmoY3p4aBkF4aW5vbSIkMDNiNDdjOGUtNWJkZi00MWNiLWJiZWYtMjliZTZhMThkZTllSOPclZsG",KEYID="0x03B47C8E5BDF41CBBBEF29BE6A18DE9E",IV=0x813A1D12BE0A6D2475F810BEE5AFC5E2,KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1"
#EXT-X-MAP:URI="https://epllinearcdn-s-bla.l.optusnet.com.au/v5/OptusSport1/xbtss/drm/hevc/cmaf/scte/v5-OS1-XBTSS_audio_5_0_track_323026866_csid_6f482ccc67614227b43c42a0b4453b22_14_init.mp4"
#EXTINF:3.84,
https://epllinearcdn-s-bla.l.optusnet.com.au/v5/OptusSport1/xbtss/drm/hevc/cmaf/scte/v5-OS1-XBTSS_audio_5_0_4241391.mp4?m=1649136584
```

**Comment by CastagnaIT** [comment]
did you find anything in other players sources that might suggest how to implement it?
i tried search a lot but i didn't find how to do

**Comment by glennguy** [comment]
From what I've read CMAF is a subset of DASH/HLS/ISM. To me all it means is "Encoded video that is compatible across multiple playlist types, allowing providers to encode once and create multiple playlist types for the same files"
e.g HLS/TS is not CMAF as MPD/ISM doesn't support TS files.

**Comment by glennguy** [comment]
In this particular example though decryption is failing for some reason.

**Comment by glennguy** [comment]
Update on this: this looks to be a problem with Bento4 not liking this particular stream, some part of the `saiz` (I think) box aren't parsing correctly and then bad stuff happens shortly after. Will continue looking at over next several days.

**Comment by matthuisman** [comment]
Thanks @glennguy . Let me know if you need anything from me :)

**Comment by CastagnaIT** [comment]
if this is the cause maybe could solve the image problems with netfl@x AV1

**Comment by CastagnaIT** [comment]
@glennguy about subsamples time ago i found this on shaka
https://github.com/shaka-project/shaka-packager/blame/ce932f68a2e45e9a85a8e9c3d6f50675682c6fdf/packager/media/crypto/subsample_generator.cc
which i suspected was related to the problem but i have no certainty
i could not understand how it works

**Comment by glennguy** [comment]
One more piece of the puzzle to solve before this stream will play in full: https://github.com/axiomatic-systems/Bento4/issues/781

**Comment by CastagnaIT** [comment]
i tested current #1048 with netflix AV1 but no improvements still wrong images

**Comment by matthuisman** [comment]
Fixed with https://github.com/xbmc/inputstream.adaptive/commit/fa470beeda76a9384f785bd1f7f19297fdaa2a4e
