### ISSUE TITLE
DTS support

### ISSUE THREAD

**Issue by kenodai** [peak3d/inputstream.adaptive#101]
Hi peak3d,
i've been playing with DASH lately and noticed there is DTS support missing.

Spec:
https://resources.dts.com/bp/#/search/?q=9302j81100&filters=%257B%257D

Reference Tests can be found here:
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd05
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd20

Regards,
Kenodai

**Comment by peak3d** [comment]
thx for reporting / samples!

https://github.com/peak3d/inputstream.adaptive/commit/7cad17dabdbf4d8dd8eb770428e80d0684b5446b
