### ISSUE TITLE
#KODIPROP

### ISSUE THREAD

**Issue by Newbiect** [peak3d/inputstream.adaptive#1018]
Hello, i have an mpd and the key and the kid of the video, how can i make kodi play it using #KODIPROP?

--KID: edef8ba979d64acea3c827dcd51d21ed --KEY: 11cc7544ad746290115ecd1460ba19b9

**Comment by CastagnaIT** [comment]
you cant
you must have a valid MPD with content protection data

**Comment by Newbiect** [comment]
But if I have the valid MPD and these are the protection data, right? --KID: edef8ba979d64acea3c827dcd51d21ed --KEY: 11cc7544ad746290115ecd1460ba19b9

> you cant you must have a valid MPD with content protection data

**Comment by Newbiect** [comment]
#EXTINF:-1 tvg-logo="" group-title="" tvg-id="", NAME
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"o3XQhiQpqNJv/2ZV5IZc1Q", "kid":"EQg3dH7ihdTP0RRaEyiNNQ" } ], "type":"temporary" }
#EXTVLCOPT:http-user-agent=Chrome/61.0.3163.100
https://live2-ott.izzigo.tv/out/u/dash/TELEHIT-URBANO-SD/default.mpd

> you cant you must have a valid MPD with content protection data

**Comment by CastagnaIT** [comment]
clearkey DRM is not supported
but its planned in a future implementation

**Comment by glennguy** [comment]
@warlinct, like in #1020 I have a question:

Are you actually using Kodi to try and play videos?

Btw: `--KID: edef8ba979d64acea3c827dcd51d21ed`
This is not a KID, it is the UUID for Widevine.
