### ISSUE TITLE
HLS stream AES-128 encryption

### ISSUE THREAD

**Issue by Lantash77** [peak3d/inputstream.adaptive#1019]
## Bug report
Hi I was wondering if you could help me out or point me in right direction, as last couple days I'm kicking with the horse
### Describe the bug
`2022-07-13 01:12:53.039 T:8696    FATAL <general>: AddOnLog: inputstream.adaptive: AES decryption failed: -10`

Here is a clear and concise description of what the problem is:

Website which I'm cooperating started implementing new player, during tests performed there was no problem.
However during tests requests for key always returned 16bytes 0. `b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`
Recently thats changed and key request returning values (16 bytes). 
Different everytime
Best I've got is 3seconds playback  and spamming decryption failed in log.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Any advice - point appreciated

### To Reproduce

1. Script required some workaround to get hls playlist possible to run,  also there is proxy set up
   as server require specific ping to keep stream active. 
I can share it if required, not sure if it needed now.
2. Example link: [https://iframe.mediadelivery.net/embed/43012/7e5a66c8-7d0a-4f05-865b-2b76e549748a](url)
But as mention before it need workaround to get hls manifest and required headers.

Let me know - will provide more details when needed

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/letexegeje.kodi](url)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://video-420.mediadelivery.net/.drm/063cd965-66a8-4fe6-8509-681c6b748a4f/1280x720.drmkey?v=0",IV=0x3230386236373936636331332d346433
#EXTINF:5.005000,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video0.ts?v=0&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:3.753756,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video1.ts?v=0&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:3.753744,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video2.ts?v=0&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXT-X-KEY:METHOD=AES-128,URI="https://video-420.mediadelivery.net/.drm/063cd965-66a8-4fe6-8509-681c6b748a4f/1280x720.drmkey?v=1",IV=0x3230386236373936636331332d346433
#EXTINF:3.753756,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video3.ts?v=1&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:3.753744,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video4.ts?v=1&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:5.005000,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video5.ts?v=1&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXT-X-KEY:METHOD=AES-128,URI="https://video-420.mediadelivery.net/.drm/063cd965-66a8-4fe6-8509-681c6b748a4f/1280x720.drmkey?v=2",IV=0x3230386236373936636331332d346433
#EXTINF:3.753756,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video6.ts?v=2&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:3.753744,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video7.ts?v=2&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXTINF:3.753756,
https://vz-86fc79ca-5ba.b-cdn.net/7e5a66c8-7d0a-4f05-865b-2b76e549748a/1280x720/video8.ts?v=2&resolution=1280x720&server=420&contextId=063cd965-66a8-4fe6-8509-681c6b748a4f
#EXT-X-KEY:METHOD=AES-128,URI="https://video-420.mediadelivery.net/.drm/063cd965-66a8-4fe6-8509-681c6b748a4f/1280x720.drmkey?v=3",IV=0x3230386236373936636331332d346433
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3
 - inputstream.adaptive version: 19.0.7

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by L2501** [comment]
Looks similar issue to https://github.com/xbmc/inputstream.adaptive/pull/1010

**Comment by Lantash77** [comment]
Issue update
Did rollback to v19.0.5 and it is working without problems. 
Same problem found on K20 with ISA 20.2.3 - rollback to 20.2.1 solved it.

**Comment by L2501** [comment]
@Lantash77 you might also be able to bypass this by disabling http2, seems like kodi curlfile does not handle file length in http2 data-frame.

**Comment by Lantash77** [comment]
@L2501
Thank you for answer. 
Disabling HTTP2.
Can't recollect ISA having that option. 

Shall I pass all requests via proxy then?
or is there easier workaround.

**Comment by L2501** [comment]
@Lantash77 disablehttp2 is in advncedsettings.xml, or yes proxying everything should work also.

**Comment by glennguy** [comment]
@L2501 thanks for helping with this. I'm not very knowledgeable in http protocol area, do you have any suggestion to solve this without breaking anything? Would a `GetPropertyValue(ADDON_FILE_PROPERTY_RESPONSE_PROTOCOL)` and checking for http2, and if so never send 'end of file' to `write_data` work? Is it all http2 transfers that don't give us the correct length or right conditions to check properly?

**Comment by L2501** [comment]
@glennguy ideally the kodi curl vfs AtEnd/length methods should be fixed to reflect the correct value, but not sure how feasible that is. In the meantime checking if file length is 0 might work.

**Comment by glennguy** [comment]
Ok cool thanks. Looking at Kodi side of things, AtEnd() just checks if the position is gte the length, so length 0 gives us a potentially 'bad' true.

So you're thinking along the lines of `if (write_data(bufferData.data(), byteRead, lockfreeBuffer, (file.AtEnd() && file.GetLength() != 0)))`?

**Comment by L2501** [comment]
that would work for chunked as kodi explicitly sets length 0 https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L1153
it defaults to 0 https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L257
and updated only by the content length header https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L373
in http2 content-length header is SHOULD (optional) and is missing in this case.

**Comment by L2501** [comment]
@glennguy scratch that looks like that might not actually work, as the length is updated by the position
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L377

**Comment by Lantash77** [comment]
@glennguy 
#1022 
Curing the problem. Thank you.
