### ISSUE TITLE
Can't play this link for some reason. Can someone help me?

### ISSUE THREAD

**Issue by Decimus4000** [peak3d/inputstream.adaptive#102]
Hi,
I am trying to play a live stream. I cannot get it to work. I have made a STRM file and put the following in there:

> #KODIPROP:inputstreamaddon=inputstream.adaptive
> #KODIPROP:inputstream.adaptive.manifest_type=mpd
> https://h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|X-Requested-With=XMLHTTPRequest|authority=h5p2p.peer-stream.com|method=GET|path=/chunks/itv_sd.webm.mpd|scheme=https|accept=*/*|accept-encoding=gzip, deflate, br|accept-language=en-US,en;q=0.9|referer=https://h5p2p.peer-stream.com/index-video.html?mpd=//h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

It does not play in Kodi. This is my log file.

> 11:02:59.949 T:3868  NOTICE: special://profile/ is mapped to: special://masterprofile/
> 11:02:59.949 T:3868  NOTICE: -----------------------------------------------------------------------
> 11:02:59.949 T:3868  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Windows NT x86 32-bit
> 11:02:59.949 T:3868  NOTICE: Using Release Kodi x32 build
> 11:02:59.949 T:3868  NOTICE: Kodi compiled Dec 10 2017 by MSVC 190024215 for Windows NT x86 32-bit version 10.0 (0x0A000000)
> 11:02:59.949 T:3868  NOTICE: Running on Hewlett-Packard HP Pavilion g6 Notebook PC with Windows 10, kernel: Windows NT x86 64-bit version 10.0
> 11:02:59.950 T:3868  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
> 11:02:59.952 T:3868  NOTICE: Host CPU: Unknown, 2 cores available
> 11:02:59.952 T:3868  NOTICE: Desktop Resolution: 1366x768 32Bit at 60Hz
> 11:02:59.952 T:3868  NOTICE: Running with restricted rights
> 11:02:59.956 T:3868  NOTICE: Aero is enabled
> 11:02:59.956 T:3868  NOTICE: special://xbmc/ is mapped to: C:\Program Files (x86)\Kodi
> 11:02:59.956 T:3868  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files (x86)\Kodi
> 11:02:59.956 T:3868  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files (x86)\Kodi/addons
> 11:02:59.956 T:3868  NOTICE: special://masterprofile/ is mapped to: C:\Users\Tom\AppData\Roaming\Kodi\userdata
> 11:02:59.956 T:3868  NOTICE: special://home/ is mapped to: C:\Users\Tom\AppData\Roaming\Kodi\
> 11:02:59.956 T:3868  NOTICE: special://temp/ is mapped to: C:\Users\Tom\AppData\Roaming\Kodi\cache
> 11:02:59.956 T:3868  NOTICE: special://logpath/ is mapped to: C:\Users\Tom\AppData\Roaming\Kodi\
> 11:02:59.956 T:3868  NOTICE: The executable running is: C:\Program Files (x86)\Kodi\kodi.exe
> 11:02:59.967 T:3868  NOTICE: Local hostname: DESKTOP-9DQ8Q4F
> 11:02:59.967 T:3868  NOTICE: Log File is located: C:\Users\Tom\AppData\Roaming\Kodi\/kodi.log
> 11:02:59.967 T:3868  NOTICE: -----------------------------------------------------------------------
> 11:02:59.980 T:3868  NOTICE: load settings...
> 11:03:00.004 T:3868 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
> 11:03:00.004 T:3868 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
> 11:03:00.023 T:3868  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
> 11:03:00.024 T:3868  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
> 11:03:00.024 T:3868  NOTICE: Default Video Player: VideoPlayer
> 11:03:00.024 T:3868  NOTICE: Default Audio Player: paplayer
> 11:03:00.024 T:3868  NOTICE: Disabled debug logging due to GUI setting. Level 0.
> 11:03:00.024 T:3868  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
> 11:03:00.025 T:3868  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
> 11:03:00.027 T:3868  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
> 11:03:00.028 T:3868  NOTICE: Loaded playercorefactory configuration
> 11:03:00.029 T:3868  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
> 11:03:00.029 T:3868  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
> 11:03:00.093 T:3868  NOTICE: Running database version Addons27
> 11:03:00.412 T:3868  NOTICE: ADDONS: Using repository repository.xbmc.org
> 11:03:00.546 T:4048  NOTICE: Found 2 Lists of Devices
> 11:03:00.546 T:4048  NOTICE: Enumerated DIRECTSOUND devices:
> 11:03:00.546 T:4048  NOTICE:     Device 1
> 11:03:00.546 T:4048  NOTICE:         m_deviceName      : {0FB1C1D0-E403-455D-BC4D-ADC81448CAA5}
> 11:03:00.546 T:4048  NOTICE:         m_displayName     : Speakers - Speakers (High Definition Audio Device)
> 11:03:00.547 T:4048  NOTICE:         m_displayNameExtra: DIRECTSOUND: Speakers (High Definition Audio Device)
> 11:03:00.547 T:4048  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 11:03:00.547 T:4048  NOTICE:         m_channels        : FL,FR
> 11:03:00.547 T:4048  NOTICE:         m_sampleRates     : 44100
> 11:03:00.547 T:4048  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
> 11:03:00.547 T:4048  NOTICE:         m_streamTypes     : No passthrough capabilities
> 11:03:00.547 T:4048  NOTICE:     Device 2
> 11:03:00.547 T:4048  NOTICE:         m_deviceName      : default
> 11:03:00.547 T:4048  NOTICE:         m_displayName     : default
> 11:03:00.547 T:4048  NOTICE:         m_displayNameExtra:
> 11:03:00.547 T:4048  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 11:03:00.547 T:4048  NOTICE:         m_channels        : FL,FR
> 11:03:00.547 T:4048  NOTICE:         m_sampleRates     : 44100
> 11:03:00.547 T:4048  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
> 11:03:00.547 T:4048  NOTICE:         m_streamTypes     : No passthrough capabilities
> 11:03:00.547 T:4048  NOTICE: Enumerated WASAPI devices:
> 11:03:00.547 T:4048  NOTICE:     Device 1
> 11:03:00.548 T:4048  NOTICE:         m_deviceName      : {0FB1C1D0-E403-455D-BC4D-ADC81448CAA5}
> 11:03:00.548 T:4048  NOTICE:         m_displayName     : Speakers - Speakers (High Definition Audio Device)
> 11:03:00.548 T:4048  NOTICE:         m_displayNameExtra: WASAPI: Speakers (High Definition Audio Device)
> 11:03:00.548 T:4048  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 11:03:00.548 T:4048  NOTICE:         m_channels        : FL,FR
> 11:03:00.548 T:4048  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100
> 11:03:00.548 T:4048  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
> 11:03:00.548 T:4048  NOTICE:         m_streamTypes     : No passthrough capabilities
> 11:03:00.548 T:4048  NOTICE:     Device 2
> 11:03:00.548 T:4048  NOTICE:         m_deviceName      : default
> 11:03:00.548 T:4048  NOTICE:         m_displayName     : default
> 11:03:00.548 T:4048  NOTICE:         m_displayNameExtra:
> 11:03:00.548 T:4048  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 11:03:00.548 T:4048  NOTICE:         m_channels        : FL,FR
> 11:03:00.548 T:4048  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100
> 11:03:00.548 T:4048  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
> 11:03:00.548 T:4048  NOTICE:         m_streamTypes     : No passthrough capabilities
> 11:03:00.734 T:3868  NOTICE: Found screen: Generic PnP Monitor on AMD Radeon(TM) HD 6480G, adapter 0.
> 11:03:00.735 T:3868  NOTICE: Primary mode: 1366x768@ 60.00 - Full Screen
> 11:03:00.737 T:3868  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
> 11:03:00.739 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.739 T:3868  NOTICE: Additional mode: 800x480@ 60.00 - Full Screen
> 11:03:00.741 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.741 T:3868  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
> 11:03:00.742 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.742 T:3868  NOTICE: Additional mode: 1024x600@ 60.00 - Full Screen
> 11:03:00.743 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.743 T:3868  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
> 11:03:00.745 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.745 T:3868  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
> 11:03:00.746 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.746 T:3868  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
> 11:03:00.748 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.748 T:3868  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
> 11:03:00.749 T:3868  NOTICE: Previous line repeats 2 times.
> 11:03:00.749 T:3868  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
> 11:03:00.750 T:3868  NOTICE: Checking resolution 16
> 11:03:02.016 T:7120  NOTICE: Running database version Addons27
> 11:03:02.019 T:7120  NOTICE: Running database version ViewModes6
> 11:03:02.023 T:7120  NOTICE: Running database version Textures13
> 11:03:02.031 T:7120  NOTICE: Running database version MyMusic60
> 11:03:02.041 T:7120  NOTICE: Running database version MyVideos107
> 11:03:02.046 T:7120  NOTICE: Running database version TV29
> 11:03:02.051 T:7120  NOTICE: Running database version Epg11
> 11:03:02.455 T:3868 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
> 11:03:02.718 T:3868  NOTICE: initialize done
> 11:03:02.718 T:3868  NOTICE: Running the application...
> 11:03:02.719 T:3868  NOTICE: starting upnp client
> 11:03:03.023 T:6000  NOTICE: ES: Starting UDP Event server on port 9777
> 11:03:03.023 T:6000  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
> 11:03:04.138 T:6676  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.6), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
> 11:03:04.367 T:7120  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 18 channels.
> 11:03:07.293 T:7120  NOTICE: EPG::CEpgContainer::Start - EPG thread started
> 11:03:08.374 T:6716  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
> 11:03:10.530 T:6152   ERROR: XFILE::CDirectory::GetDirectory - Error getting
> 11:03:16.649 T:3868   ERROR: Previous line repeats 6 times.
> 11:03:16.649 T:3868  NOTICE: VideoPlayer: Opening: https://h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|X-Requested-With=XMLHTTPRequest|authority=h5p2p.peer-stream.com|method=GET|path=/chunks/itv_sd.webm.mpd|scheme=https|accept=*/*|accept-encoding=gzip, deflate, br|accept-language=en-US,en;q=0.9|referer=https://h5p2p.peer-stream.com/index-video.html?mpd=//h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
> 11:03:16.650 T:3868 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
> 11:03:16.990 T:3868   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
> 11:03:16.990 T:3868   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
> 11:03:16.996 T:7140  NOTICE: Creating InputStream
> 11:03:18.088 T:7140  NOTICE: Creating Demuxer
> 11:03:18.089 T:7140  NOTICE: Opening stream: 1 source: 256
> 11:03:18.369 T:7140   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
> 11:03:18.611 T:5472   ERROR: CCurlFile::Open failed with code 404 for https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._v_11.chk|Connection=keep-alive&acceptencoding=gzip&seekable=0
> 11:03:18.611 T:5472   ERROR: AddOnLog: InputStream Adaptive: Download https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._v_11.chk doesn't provide any data: invalid
> 11:03:18.612 T:7140  NOTICE: Creating video codec with codec id: 168
> 11:03:18.612 T:7140  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: Google VP9
> 11:03:18.612 T:7140  NOTICE: Creating video thread
> 11:03:18.613 T:7140  NOTICE: Opening stream: 2 source: 256
> 11:03:18.624 T:6812  NOTICE: running thread: video_thread
> 11:03:19.783 T:7140   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
> 11:03:20.019 T:2092   ERROR: CCurlFile::Open failed with code 404 for https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._a_11.chk|Connection=keep-alive&acceptencoding=gzip&seekable=0
> 11:03:20.019 T:2092   ERROR: AddOnLog: InputStream Adaptive: Download https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._a_11.chk doesn't provide any data: invalid
> 11:03:20.020 T:7140  NOTICE: Finding audio codec for: 86077
> 11:03:20.022 T:7140  NOTICE: Creating audio thread
> 11:03:20.023 T:7140  NOTICE: CVideoPlayer::OnExit()
> 11:03:20.023 T:7140  NOTICE: VideoPlayer: eof, waiting for queues to empty
> 11:03:20.023 T:7140  NOTICE: Closing stream player 1
> 11:03:20.024 T:7140  NOTICE: Waiting for audio thread to exit
> 11:03:20.026 T:6684  NOTICE: running thread: CVideoPlayerAudio::Process()
> 11:03:20.026 T:6684  NOTICE: thread end: CVideoPlayerAudio::OnExit()
> 11:03:20.026 T:7140  NOTICE: Closing audio device
> 11:03:20.026 T:7140  NOTICE: Deleting audio codec
> 11:03:20.026 T:7140  NOTICE: Closing stream player 2
> 11:03:20.026 T:7140  NOTICE: waiting for video thread to exit
> 11:03:20.026 T:6812   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
> 11:03:20.027 T:6812  NOTICE: thread end: video_thread
> 11:03:20.027 T:7140  NOTICE: deleting video codec
> 11:03:20.036 T:3868   ERROR: Playlist Player: skipping unplayable item: 0, path [https://h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|X-Requested-With=XMLHTTPRequest|authority=h5p2p.peer-stream.com|method=GET|path=/chunks/itv_sd.webm.mpd|scheme=https|accept=*/*|accept-encoding=gzip, deflate, br|accept-language=en-US,en;q=0.9|referer=https://h5p2p.peer-stream.com/index-video.html?mpd=//h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36]
> 11:03:20.052 T:3868  NOTICE: CVideoPlayer::CloseFile()
> 11:03:20.053 T:3868  NOTICE: VideoPlayer: waiting for threads to exit
> 11:03:20.053 T:3868  NOTICE: VideoPlayer: finished waiting
> 11:03:20.053 T:3868  NOTICE: CVideoPlayer::CloseFile()
> 11:03:20.053 T:3868  NOTICE: VideoPlayer: waiting for threads to exit
> 11:03:20.053 T:3868  NOTICE: VideoPlayer: finished waiting
> 11:08:10.298 T:6716  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
> 11:09:56.927 T:3868  NOTICE: VideoPlayer: Opening: https://h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|X-Requested-With=XMLHTTPRequest|authority=h5p2p.peer-stream.com|method=GET|path=/chunks/itv_sd.webm.mpd|scheme=https|accept=*/*|accept-encoding=gzip, deflate, br|accept-language=en-US,en;q=0.9|referer=https://h5p2p.peer-stream.com/index-video.html?mpd=//h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
> 11:09:56.927 T:3868 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
> 11:09:57.077 T:3868   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
> 11:09:57.077 T:3868   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
> 11:09:57.078 T:6408  NOTICE: Creating InputStream
> 11:09:57.845 T:6408  NOTICE: Creating Demuxer
> 11:09:57.846 T:6408  NOTICE: Opening stream: 1 source: 256
> 11:09:58.035 T:6408   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
> 11:09:58.203 T:6696   ERROR: CCurlFile::Open failed with code 404 for https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._v_11.chk|Connection=keep-alive&acceptencoding=gzip&seekable=0
> 11:09:58.204 T:6696   ERROR: AddOnLog: InputStream Adaptive: Download https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._v_11.chk doesn't provide any data: invalid
> 11:09:58.204 T:6408  NOTICE: Creating video codec with codec id: 168
> 11:09:58.205 T:6408  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: Google VP9
> 11:09:58.205 T:6408  NOTICE: Creating video thread
> 11:09:58.205 T:6408  NOTICE: Opening stream: 2 source: 256
> 11:09:58.212 T:2316  NOTICE: running thread: video_thread
> 11:09:58.918 T:6408   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
> 11:09:59.113 T:5492   ERROR: CCurlFile::Open failed with code 404 for https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._a_11.chk|Connection=keep-alive&acceptencoding=gzip&seekable=0
> 11:09:59.113 T:5492   ERROR: AddOnLog: InputStream Adaptive: Download https://h5p2p.peer-stream.com/chunks/itv_sd.webm_40jyNIYu67hgp6XV._a_11.chk doesn't provide any data: invalid
> 11:09:59.114 T:6408  NOTICE: Finding audio codec for: 86077
> 11:09:59.116 T:6408  NOTICE: Creating audio thread
> 11:09:59.118 T:6408  NOTICE: CVideoPlayer::OnExit()
> 11:09:59.118 T:6408  NOTICE: VideoPlayer: eof, waiting for queues to empty
> 11:09:59.119 T:6408  NOTICE: Closing stream player 1
> 11:09:59.119 T:6408  NOTICE: Waiting for audio thread to exit
> 11:09:59.120 T:6664  NOTICE: running thread: CVideoPlayerAudio::Process()
> 11:09:59.120 T:6664  NOTICE: thread end: CVideoPlayerAudio::OnExit()
> 11:09:59.120 T:6408  NOTICE: Closing audio device
> 11:09:59.120 T:6408  NOTICE: Deleting audio codec
> 11:09:59.121 T:6408  NOTICE: Closing stream player 2
> 11:09:59.121 T:6408  NOTICE: waiting for video thread to exit
> 11:09:59.121 T:2316   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
> 11:09:59.121 T:2316  NOTICE: thread end: video_thread
> 11:09:59.122 T:6408  NOTICE: deleting video codec
> 11:09:59.124 T:3868   ERROR: Playlist Player: skipping unplayable item: 0, path [https://h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|X-Requested-With=XMLHTTPRequest|authority=h5p2p.peer-stream.com|method=GET|path=/chunks/itv_sd.webm.mpd|scheme=https|accept=*/*|accept-encoding=gzip, deflate, br|accept-language=en-US,en;q=0.9|referer=https://h5p2p.peer-stream.com/index-video.html?mpd=//h5p2p.peer-stream.com/chunks/itv_sd.webm.mpd|user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36]
> 11:09:59.130 T:3868  NOTICE: CVideoPlayer::CloseFile()
> 11:09:59.130 T:3868  NOTICE: VideoPlayer: waiting for threads to exit
> 11:09:59.130 T:3868  NOTICE: VideoPlayer: finished waiting
> 11:09:59.130 T:3868  NOTICE: CVideoPlayer::CloseFile()
> 11:09:59.130 T:3868  NOTICE: VideoPlayer: waiting for threads to exit
> 11:09:59.130 T:3868  NOTICE: VideoPlayer: finished waiting

Any help would be appreciated!

**Comment by peak3d** [comment]
1.) You don't need all the headers you attached
2.) Multiple headers are separated by &, the header values should be URL encoed (but see 1)
3.) The mime type of the streams is webm, this is not yet supported

**Comment by micahg** [comment]
I'm running into the "No MOOV in stream!" as well? Can we reopen this? I can up my log or add a new issue.
