### ISSUE TITLE
 Issue with license URL in M3U File. Prioritize license in M3U

### ISSUE THREAD

**Issue by DCARTERCCP** [peak3d/inputstream.adaptive#1020]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have an M3U file which consists of a channel having MPD and License URL in the M3U File.

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-chno="" group-title="", Some Name
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=http://somedomain.com/custom/license/url
http://somedomain.com/custom/mpd/url
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In the above block provided the request for license should be made on the URL http://somedomain.com/custom/license/url
instead of the one which is in MPD i.e http://somedomain.com/custom/mpd/url

## Actual Behavior

Instead the request for license are being sent to http://somedomain.com/custom/mpd/url which shouldn't be the case when user himself has provided the license URL in M3U File. This doesn't happen in the case of `clearkey`. There it happens as desired the request is made to the URL provided in the M3U file not in the MPD.

### To Reproduce

1. I used a player named Tivimate which uses `inputstream.adaptive`.
2. Just copy the above provided channel block to a txt file and load it the Tivimate App.
3. In my opinion, The case should be same with Kodi as well.
4. You can then see the request being made to the URL provided in the MPD File.

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
http://somedomain.com/custom/mpd/url

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Where's the log?

**Comment by monichoza** [comment]
You said that with clearkey doesn't happen, how you reproduce a clearkey stream?

**Comment by DCARTERCCP** [comment]
> Where's the log?

Sorry what log? I don't think there could be anything like log for this. In case you need TVmate HTTP Requests which I intercepted I can share that.

**Comment by DCARTERCCP** [comment]
> You said that with clearkey doesn't happen, how you reproduce a clearkey stream?

Sure. Here it is. The below block represents a channel having Clear Key DRM,

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-chno="" group-title="", Some Name
#KODIPROP:inputstream.adaptive.license_type=clearkey
#KODIPROP:inputstream.adaptive.license_key=http://somedomain.com/custom/license/url
http://somedomain.com/custom/mpd/url
```

Now, the request for license will be sent to `http://somedomain.com/custom/license/url` which is desired to happen when the DRM System is `com.widevine.alpha`

**Comment by CastagnaIT** [comment]
clearkey its planned but not supported yet
available license_type's are specified in wiki: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivelicense_type

**Comment by DCARTERCCP** [comment]
> clearkey its planned but not supported yet available license_type's are specified in wiki: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivelicense_type

Sorry, but I just mentioned `clearkey` as that app was using it. But question is still on for `com.widevine.alpha`
Which is WV and supported by this.
That was does it uses license url from MANIFEST instead of the one provided separately.

**Comment by CastagnaIT** [comment]
ok take in account that both types have common things but are differents

if you want that we try investigate you have to provide
- the MPD manifest as file attached (not the link)
- full kodi debug log when you try play the video from the M3U

if you have problem with not accepted extensions zip them

**Comment by DCARTERCCP** [comment]
I think I'm unable to explain this issue properly. So will reopen or create a new one once I collect all the required things. Thanks for your time.

**Comment by glennguy** [comment]
@DCARTERCCP 

Clearly we're all confused here.

1. This is a repo for a *Kodi* add-on. "Tivimate" means absolutely nothing to us, I have no idea what this is.
2. The behavior you're asking for works already in Kodi.

To me, it appears that whatever app you're using is designed to be able to use Kodi playlists and parses the parameters as such. Despite 'inputstream.adaptive' being mentioned, it has nothing at all to do with what your player does with your playlist.

Suggestion:
Go and speak to the Tivimate devs about your issue, you're in the wrong place.
