### ISSUE TITLE
Add support for ORIGINAL language in HLS?

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1021]
99% sure its not in HLS spec, but would be nice if we could add it for kodi sake so addons could mark a track as original audio and get it passed along to kodi like we do for dash.

eg
`#EXT-X-MEDIA:TYPE="AUDIO",GROUP-ID="eac-3",NAME="Español (Latinoamericano)",LANGUAGE="es-419",ORIGINAL="YES",AUTOSELECT="YES",CHANNELS="6",`

One newline under:
https://github.com/xbmc/inputstream.adaptive/blob/33eea0081b6b2c57e461a89c4e12a64cc3e36587/src/parser/HLSTree.cpp#L251
`adp->original_ = map["ORIGINAL"] == "YES";`

**Comment by matthuisman** [comment]
currently I set DEFAULT=YES when the language is the original language. but this isnt that great as it overrides kodis language setting. If we can set the ORIGINAL audio - then that will be selected by Kodi better using its language setting

**Comment by matthuisman** [comment]
actually for impaired - it can already be set with HLS spec:
CHARACTERISTICS="public.accessibility.describes-video".

**Comment by matthuisman** [comment]
impaired covered here: https://github.com/xbmc/inputstream.adaptive/issues/690

**Comment by CastagnaIT** [comment]
i have planned to add other listitem properties to override audio/subtitle track flags without that each developer has to implement a proxy to edit the manifest just for this

so like the existing `inputstream.adaptive.original_audio_language`
this property do not fit your purpose?

however we can also add unofficial properties like done in DASH

**Comment by matthuisman** [comment]
oh, i forgot about that and are actually using it. I'm a big dumb dumb! sorry for the noise
