### ISSUE TITLE
[Question- Problem] Stream m3u8 file

### ISSUE THREAD

**Issue by johntaxmi** [peak3d/inputstream.adaptive#1024]
I coming here from phunkyfish and his IPTV Simple Player addon.
I have a problem while playing a m3u8 file using his addon and he told me to contact you.

I wanna find a way to refresh the m3u8 file before the first chunk of video ends so it can automatically continue playing the stream without closing the file.

The problem that i was facing is that beacuse of my m3u8 file playing low-duration(seconds) chunks of videos, phunkyfish's addon has a setting to auto refresh the file every 1 minute, but as i said  beacuse of the fact that my m3u8 file plays small videos there was no time to actually refresh the m3u8 to cache the next chunk of video.
So he told me to contact you here.

*Here is the issue at IPTV Simple Client. (https://github.com/kodi-pvr/pvr.iptvsimple/issues/618)

Thanks in advanced.

**Comment by glennguy** [comment]
Without seeing an example of this file it's hard to know exactly what you mean.

But let me have a guess.

m3u8 files can be many things (someone else jump in if I'm incorrect, I don't use IPTV stuff personally):
* A channel playlist - this is used to list a bunch of IPTV channels including small metadata such as channel name. Should be refreshed periodically e.g IPTV Merge does this. Contains urls of master (or even sub) m3u8 playlists
* a 'master' playlist. This is handled by inputstream.adaptive and contains links to variant or sub m3u8 playlists of differing bandwidths
* a 'sub/variant' playlist. This contains the urls to the actual chunks of video/audio/text. 

It's only the sub/variant m3u8 playlists that should be refreshed every 2 - 10 (depending on chunk length) seconds.

If you're indeed passing the sub m3u8 playlist directly to iptvsimple, you would need to wrap it in a channel m3u8 that points back to it.

**Comment by johntaxmi** [comment]
That actually makes so much sense!
Okey so, I am totally using a m3u8 file which is a sub/variant playlist and that is the reason which is playing low-duration videos.

Is there a possible fix for my issue with my current situation.
Beacuse like I said to phunkyfish if there was a way to refresh the file before the chunk ends(refresh it like every 15 seconds) then I will have no issues.

**Comment by glennguy** [comment]
Like I said, don't point iptv simple to the direct path of the variant playlist. It's meant to have a channel list m3u8.
Create a m3u8 file and put something like this inside:
```
#EXTM3U

#EXTINF:-1 channel-id="greekchannel"
https://yourcurrenturlgoeshere.....
```
And point iptv simple to this file

**Comment by johntaxmi** [comment]
After testing it for a bit, with the new format(Which is almost same with mine, the difference is that I have #EXTINF:0, instead of #EXTINF:-1), i am still getting the same issue.
Sometimes the stream continue normally and others it just stop after some seconds.
And that happens beacuse sometimes the refresh from the IPTV simple comes before the total duration of the first chunk and the other times the refresh from the IPTV simple never comes beacuse the chunk of the video ends before the IPTV simple actually refresh it.
And thats exactly the reason i asked phunkyfish to show me how I can lower the duration from minutes to seconds, so I can force it refresh my m3u8 every like 15 seconds.

**Comment by glennguy** [comment]
I'm not really sure what the problem is - I create an m3u8 file like suggested i.e:
```
#EXTM3U

#EXTINF:0 channel-id="greekchannel"
https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8
```

And point iptvsimple to it:
![image](https://user-images.githubusercontent.com/11909320/180782824-cfed0817-3c3d-4cee-a76a-5853dc47cabd.png)

iptvsimple hands over playback duties to Kodi's internal ffmpeg and playback happens without problem. Notice I have auto refresh disabled - doesn't matter. Auto refresh's job is not for refreshing a variant playlist, but for refreshing the channel playlist.

At this point inputstream.adaptive is not even used. There seems to be a setting in iptvsimple to force use of IA for this type of stream here (HLS), or it can be done for the individual channel in the channel m3u8 file:
```
#EXTM3U

#EXTINF:0 channel-id="greekchannel"
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8
```

Can you please try to replicate what I've done and post your results?

**Comment by johntaxmi** [comment]
It does actually work perfectly now, without even adding the
> #KODIPROP:inputstream=inputstream.adaptive
> #KODIPROP:inputstream.adaptive.manifest_type=hls

My only concern is about how I am able to find the master playlist each time?

**Comment by glennguy** [comment]
Have a look through dev tools in the browser. This one was pretty easy with a json file called 'livedetails':
![image](https://user-images.githubusercontent.com/11909320/181013724-1d785367-799a-4372-aead-225ee78aea08.png)

**Comment by johntaxmi** [comment]
Okey, thank you!
Appriciate both of you for your help!
