### ISSUE TITLE
FairPlay Support

### ISSUE THREAD

**Issue by Spider-netizen** [peak3d/inputstream.adaptive#1026]
Hi,

Is there any chance inputstream.adaptive will support Apple FairPlay on macOS anytime soon? How can I help to make this happen?

I'm trying to play an HLS stream that each of its m3u8 files has a line beginning with `EXT-X-KEY:METHOD=SAMPLE-AES` and has `KEYFORMAT="com.apple.streamingkeydelivery"`, which I believe is Apple FairPlay and inputstream.adaptive can't handle that type of DRM at the moment? inputstream.adaptive logs this line when I try to play it: 

> Unsupported encryption method: SAMPLE-AES

Thank you

### Environment
Used Operating system:

 - Operating system version/name: macOS 10.5.7
 - Kodi version: 19.4.0
 - inputstream.adaptive version: 19.0.7

**Comment by CastagnaIT** [comment]
fwik there is no plan to add fairplay DRM support

i have no apple products than i have no knowledge, from my part i can suppose that is needed to implement from scratch a kind of wrapper by using apple SDK, so in similar way as done with android on this file ([wvdecrypter_android.cpp](https://github.com/xbmc/inputstream.adaptive/blob/Nexus/wvdecrypter/wvdecrypter_android.cpp)) and relative jni sub folder

however if you are not aware open Wiki page to get all info of supported DRM's

**Comment by glennguy** [comment]
@Spider-netizen  - @CastagnaIT is correct, we would need to use (if even available) a Fairplay CDM - does there exist a `fairplaycdm.dylib` or similar for Safari?

Anyway in your m3u8 manifest is there also another key line adjacent to the fairplay one e.g 
```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://03b47c8e-5bdf-41cb-bbef-29be6a18de9e:E9124B8D9E2B6B9A6529A2360A3B241F",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1",IV=0xE9124B8D9E2B6B9A6529A2360A3B241F
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAZnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEYSEAO0fI5b30HLu+8pvmoY3p4aBkF4aW5vbSIkMDNiNDdjOGUtNWJkZi00MWNiLWJiZWYtMjliZTZhMThkZTllSOPclZsG",KEYID="0x03B47C8E5BDF41CBBBEF29BE6A18DE9E",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",IV=0xE9124B8D9E2B6B9A6529A2360A3B241F
```
with keyformat being the Widevine GUID?

If so you can attempt to try playing with Widevine.

As far as implementing FP in IA, I don't have a mac device either (except for a VM that barely works). If you have dev skills and want to have a go then I'm sure we can guide/support.

**Comment by Spider-netizen** [comment]
> @Spider-netizen - @CastagnaIT is correct, we would need to use (if even available) a Fairplay CDM - does there exist a `fairplaycdm.dylib` or similar for Safari?

Thank you for your reply. I appreciate it. I don't know how to find out if there is `fairplaycdm.dylib` or something similar for Safari. There is FairPlay Streaming Server SDK, that you can supposedly download [here](https://developer.apple.com/streaming/fps/), but it seems to me that you have to be a member of the Apple Developer Program to get it.

> Anyway in your m3u8 manifest is there also another key line adjacent to the fairplay one e.g
> 
> ```
> #EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://03b47c8e-5bdf-41cb-bbef-29be6a18de9e:E9124B8D9E2B6B9A6529A2360A3B241F",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1",IV=0xE9124B8D9E2B6B9A6529A2360A3B241F
> #EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAZnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEYSEAO0fI5b30HLu+8pvmoY3p4aBkF4aW5vbSIkMDNiNDdjOGUtNWJkZi00MWNiLWJiZWYtMjliZTZhMThkZTllSOPclZsG",KEYID="0x03B47C8E5BDF41CBBBEF29BE6A18DE9E",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",IV=0xE9124B8D9E2B6B9A6529A2360A3B241F
> ```
> 
> with keyformat being the Widevine GUID?
> 
> If so you can attempt to try playing with Widevine.
> 
> As far as implementing FP in IA, I don't have a mac device either (except for a VM that barely works). If you have dev skills and want to have a go then I'm sure we can guide/support.

If I try to play the stream through Safari I first get a manifest that looks like this:
https://pastebin.com/nGhkUayW
Password:  FkuLFu8p6T

And then it starts getting m3u8's from the first manifest and they look like this:
https://pastebin.com/VuJ9RQDW

I couldn't find a keyformat that's a Widevine GUID, I'd be really appreciative if you could have a look, and tell me if there's any way I could play those streams.

I can get a Widevine mpd of the content, but it doesn't allow me to stream anything above 720p. When I try to play anything with higher resolution the playback freezes, I assume it's because it requires Widevine level L2 or L1.


Unfortunately I don't have enough knowledge regarding DRM, to even know where to begin with development.

**Comment by CastagnaIT** [comment]
I am closing the issue as there is no planning to add fairplay support
for any other problem open a Issue by fullfill the appropriate template
