### ISSUE TITLE
Unable to find license in JSON string

### ISSUE THREAD

**Issue by kodi0687** [peak3d/inputstream.adaptive#1029]
I try to play [video](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiI1rKQ68b5AhW0kmoFHX1nCWwQFnoECAQQAQ&url=https%3A%2F%2Fvix.com%2Fes-es%2Fcanales&usg=AOvVaw2HuSNcpXNbIo3P8yMMABu0) from the site video

anvatoVideoJSONLoaded({"upload_id":"adstXmkEN9Kbdle6","mcp_id":"UNIVISON","owner_id":"66615243","def_title":"ZONA_TUDN_MEX","def_callsign":"Frequency-ZONA_TUDN_MEX","dvr":"","video_type":"2","src_image_url":"","src_logo_url":"","published_urls":[{"embed_url":"https://dcs-live.mp.lura.live/server/play/ADn3nqTORo32sXr7/manifest.m3u8?encp=XTy9XE7dZDXVx1O4CnZjKQ:v9BXP1yqzel2rN1XMwrggq0hqjMWd_AtIZDtciZFOuEvD_28uXBIRlSHCRLcKKNGnaHYdPUXW4sFbvTWffulrtCTuXkils8FMcwPYHoWRnMtIySW4OEc3gRihsIFnOXSuS01_-0VgmKsEn3wFYeAwXFFNT6tffHnATnEB-tX8qF1Bbyz01c1lk48F-w0eY-eYkJddE3vdalawLiDvS_202OVmmbvFCT8jYIeZoQdmU8G16P0rFvLKsTgSVZj0TBv1OG0EfMBSNt1QXmA-WCkZwtNoy49jqWNxVOm4985IFAYPRh58oYjY-tYCx5MtEBjFTtj6PgNC9GwdrplQFBbtJI9TSyBl4hDGa2dVjG1uaXvEB6kyUq1CycU9mrFOUQ8YA3WiLwyAmNQpovJw0Rmp-4F7lxEtSe1QNPtEWBZHe7eTxZRn9_XH62-tMdf0D9K7-0tjYTZ6FkuQceRUS7uvaprwAeMtg_C2lIneB5g2PpbNjo5ZsW9-GMrDgzLfeY4F25a9K3H9rs4ycOg5JqS4qlRXpm0EdN9Yu9j3JMKJ6PIP6ElvEj0PERr7FlyXHn4SwO9bJ32WZ1E6FFkmsYmA8Vy9GiRaBIpv0u2ytS3eZsQZ5Wd135HFE1VPN463CLXrh_3AuFSSdq7G7RTEqV91gqjF8JG9q_do8vg1Y-otIQ&anvtrid=97eceeb0b820c947381eeda4168af1c4&anvauth=tb=0~te=1660490455~sgn=5aba87a6dee747d4c5d9e2da7d59060bae57d3733becb76bcf86dcafafc29c89&t=1660490365","format":"m3u8-variant","kbps":0,"cdn_name":"","format_name":"m3u8-variant","width":0,"height":0,"cdn_id":-1,"protocol":"https","server_side_ad_tracking":"1","license_url":"https://drm.mp.lura.live/fp?eqp=bs0oadN3--NAIP9v5hxk4bm_-ZWx2ImoPpamXhBWrwmHcW9uFonadKPLvFcxmqcOgT5ScuiWt-kJACFRtty8gewAlRbGismks7k_A6IiXeiV3yU1DszZ5qO6fbZbRfBoX6wlfjUynEv-Hh2VlsSLDNxzzkIYLpCZJw675s0zlouSPkSswdX8r7mmpjRdTAhLI7fDdpRJwVjgoj4da72YoTKrTePmc-d4LGvFF7B_jw4BisVl5gGkiNvFhwjmwlbQk9UMdjFNTYQPZ5zBBPGWmF1N3MezaBYU9_c18pEZ0Fkv78T97SqtAbuuUiGv4UNf&anvauth=tb=0~te=1660501165~sgn=1d7e172fc2beabaa9e384ecc348ab4f7806d640b3f1e3e62827e32d55c0d90e4&t=1660490365","fp_cert":{"payload":"/Zbiyj7J9zZIZCxSvaPZ9Pc/qIwu/mbNV4LFLTlKCHy+IRh1vngy824cl8FktRKrNcQ1zDmg9owp4u/3FHvi60zkspvqASZrAtV6XRiGDYU9Gxbzbttz/I7K3Rms7mGU9mpZQHwRBiCFDVGXJYMp1MN9g5vlUXqC88maGqM6u/1nKkng404cU81torRbGmu8CPPCEm0MhkkLQU+5cWdHoV6wCm1iSLTR1FTK4mAVRfGTSBd5BOP8nEauDXBvCaIXjCfF2s4INtadOAIcGmyIJOmqVjlo7m2d6vxF939AVyn8lDjv13d3uHRhYLdupD2xUMcxVqpcdIaO8hzve8GJyP7g184VtDPz/gpUasrSAXQ2RfDDeRIBcHhUe5rkZ5Tk8UsJShAa+8j3gQaOr2lOr1cilrs948BAmA5wQJx3x0MWmxmSqku9KLzjnVReUrrmbfrQKwntqFu1aWJAlaZIeojwjqp6SbGjMfRg+17s9/gt9U4OdIlYDlojKKdSPaxqXpL/vLRioVZc1ETudhWUzX8MPLW8M0gl61h5MpC7t1E5vjp3k4/jWnI60wEE2N/rGbrpBq69XReo6tvYYqu8y2KScJRVqs7oQR7IV3pfoNvMyScpGesDOmtp4KtZYxGSFob0p8x9Ac6ZjuE9Ikx193RZfLhMVdf9kfjX8sNgl3ncvMc6aFIq/lce4KphFXN1ieBxQUV6mqROjSuC8oSoj0E0sBqMVrRa4ZtmcoexxatljsQ84x/DHKi6Gwnda8OYiwhqPjCuZt+QuuKia3oCIjFQdEeVmE46w190fnWd1cIlKFMN3DreGCC8o2OY3kicDCByaMzxvkGlUE5/5meJCmZEpHD3AQME6k4ltbHkez0MPD8GSBHyVuJWArt50ygzhYLKpBTZD0xrte/1h9NC2iO1B0vbU7tdZi5h2TW+IyNkdkfMbqCaY1ITnT52aSlRKqB1hLKN159SGAhwMs+0sY8WLLacl3M9Xhf+KdCE5nBS58eQtyukQ9ITplpRKt/0SaC1si70EX7nHxrvKTbAaKkzzqoQknPdZyyQXZHmELmSkcjbg/2DRPook8ZlNk4DtneAFhzxklYy0WtfixlKiO8brJyb0xXBmQM5GrtQeUUp8wIv3+txzttUH9I+gTNA/2jX4VSF4b5V0Md6/Tf4k9UhSn/zNVMtUnbwv34RqPopenlj6rlLFuEQcZfCHKHzqMiYMIR+c0a7Pw6EF6hE8AIg0+DdkMzYjXWwc92humU8Jtn/5z/l8fp2KKygBm9hMV9dYFhXGivv/0p7kogH3q4OHOtlzfuMaZ3bt0st2dPu+YNYwKqOYbshkb3c1FLFksFSkZi3Lb6y3CguH34w0fTveCfaWvplGBoF3l3Mnwvce/d4bZrIik8dUOv7otiJIidIDarMKnN65eC5LkZhAF/+uitajayVbLWcsdwlT/3TgN1/nEi0WFRLOo+dCF7U5pzPNrok8QspnqX1aAjq9S6ju68XS3mw5AljkMQMWFSavXvKikW2THeWbpLV06QRDGYWYFJIlXCiTzm71GdgNiiK2e8/9Br3O9bk3F+1wVQoqqd1h9Gf4qwgngA53pGbpV2a0K7cRm7habSqEeLPAU2dVisZBICQHSZ68uVhyKimhgSerLJ/s3JAZMcVTKsVLc//WX3YJGtCBJQARJYhlrBvoHoiG4hd4tAUJbe+IH/92k11/outgs1YI2tTkpvLEJVWbJ32RRMq/eCWYfyKePA4YcbdJ9TDQ1EZomQtUZ4AzXHXMYSOnufk8IMRGeLKBJ5ydyWB3dcq9cq9F1tV2D0jHVnCDxm6H9XgUx9qno4VSmt0NsLTT99RXa0uurfxc5FHRusZi443/tVJO4nGa9FCTCuVA8feSiY+PMAiPoKDjFP/X6d/S1BppMiHYorwZ56IfPgp8TZ+9DvYD3TSxCsV6DfbFlLU0YIgccUSCw39he5kts1g0FzN48mXz/bt23B0t2t+OXmQTb5H4KwlLd4PDFdor8N2KSaZIfPThGncY933lIbTvWqBtw7AWc+mqpcyRaZiDqL6C4DaYDhZAi7x2R3IbVjzCFJBVu3rA7Tmxl5/Fy33yQKEn13o4UICB2RZUHQtfXAcZn/xoGgLq1V1UUu3GfnwMWI0+MqyEdS/TQskwHLnrkfpxigxfeFBlI/iyBwWyft1uKDfpPEx3yn1VfgYdSinnnUajOHlxA0=","encrypted":true}},{"embed_url":"https://dcs-live.mp.lura.live/server/play/ADn3nqTORo32sXr7/manifest.mpd?encp=LNHiOOecPxEsOwsb16TXOg:HYE7JV3KQUtA7ARPClBGFx-8h5TZ4W0nOjwNZL1FADwyC2Xo4NJXSn9UQ9WACqeXvBMj5alsWBQNDIkXp9RMl4FxDwJxkokwPExowGQQQyAfToPKI2ir4OI3EGhXjrfZeexolIgyM16CHzlv97Y5Ud2p9WbTt-_7GmZS3BnbGTEKO8i8xktcpoAOJ9Zyd1TutkHktoXUsYcfoFLYnwqCe_ygFpIQdqInQWvWk1oSv-pKBzVZqI_ZbhswbeAEI174Aych-pnzv6tlltbhcsP2mkqRXRdYKVOpl9huwwjBSl31MPQcI6WyeeKuK1PLctWBDesNpFzfv2opB4CetzeLV9YYB_IAvo5Gbxpm5ENx6PjmdC4lNewUkhV6AsCo68usCLY0wYfLHfurGI1HI2X_Y8_jnckC75UOWikXfNWYeao3IGHuDttGD-NA2dg2NRgdDe9tv-Ck7ZqPlAKH_EalzEuSBcP_U7QkBVK8o7Qth3Ts2fghI1kcM6YSZsLakyTBUd2azI2rtK0wgJQDTluC9ONFaGE3iPO7xjIhfanOy2JtcybNKPwt3TYFXkKYCj-Ct72z1bb8cQ210JOI00XK3IJ2t4YV47czieXEJLLRlOTcApU1aJgP_uf1U4Pgmi77Mg70vnsCcSpxbH3GH5UBTQ&anvtrid=97eceeb0b820c947381eeda4168af1c4&anvauth=tb=0~te=1660490455~sgn=0a4f2050af20be08bb20425a765b50d34287e2bf8f6794664800576849920b1c&t=1660490365","format":"dash","kbps":0,"cdn_name":"","format_name":"dash","width":0,"height":0,"cdn_id":-1,"protocol":"https","license_url":"https://drm.mp.lura.live/cenc?eqp=MH7sIW5UJOvdIw_59puigNh4lalafWYgmWtyapJGKQrJiutg23sw6ITY9j4VOz88EXNOTe532K6FmJ0tGYRt6G8yO4MkKdh8r7cNTSbVkXl7di5qfYTOPDU37_0yabAsjRr7pudjR6nyc-lnLEbNJr_DxxtO4MSIcWy5Tj2c8QGdV4SA_zq-CstMVrQoMWJw8--j98SacChLjI87CxBpUQAGhhFl_Kgukw2d0s3780Jdl3CzBt8JiC7U0l6Wgt0NFwGKJGHQg1ayiDLk7hEBaygcYZV7QI3z4ASg5Lf-TuOazkbcA-xDjjh2qPZ2KM_s&anvauth=tb=0~te=1660501165~sgn=6bf17a1ccf934ab2b9a24eb022e5f051b633c9d78787fea5bb1dd5917590e92e&t=1660490365"}],"logo_settings":[],"source_channel_id":"556","derived_metadata":{"video_id":"adstXmkEN9Kbdle6","video_name":"ZONA_TUDN_MEX","video_genre":"","video_type":"2"},"requested_id":"adstXmkEN9Kbdle6","redirected_id":null,"primary_id":null,"access_rules":[],"generated":"at 1660490365 in 0.29762697219849 sec"})

        list_item = self.xbmcgui.ListItem(path=video_url + '|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0')
        list_item.setProperty('inputstream.adaptive.license_type', 'com.widevine.alpha')
        list_item.setProperty('inputstream', 'inputstream.adaptive')
        list_item.setProperty('inputstream.adaptive.license_key', license_url +'|Content-Type=|R{SSM}|Jlicense')
        list_item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
        list_item.setMimeType('application/dash+xml')

 -  x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - inputstream.adaptive version:19.0.7

**Comment by glennguy** [comment]
>I try to play [video](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiI1rKQ68b5AhW0kmoFHX1nCWwQFnoECAQQAQ&url=https%3A%2F%2Fvix.com%2Fes-es%2Fcanales&usg=AOvVaw2HuSNcpXNbIo3P8yMMABu0) from the site video 

Ok. Did it work?

**Comment by kodi0687** [comment]
> 

Dont work.
        video_url = re.findall('\,\{"embed_url"\:"(.*?)"', html)[0].replace("\\/", "/")
        s = requests.Session()
        r = s.get(video_url, headers=header)
        subject = (r.content)
        html = subject.decode('ISO-8859-1')
       video_url2 = re.findall('Location\>(.*?)\<', html)[0]

With this crash and close kodi.



    list_item = self.xbmcgui.ListItem(path=video_url2 + '|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0')
    list_item.setProperty('inputstream.adaptive.license_type', 'com.widevine.alpha')
    list_item.setProperty('inputstream', 'inputstream.adaptive')
    list_item.setProperty('inputstream.adaptive.license_key', license_url +'|Content-Type=|R{SSM}|')
    list_item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
    list_item.setMimeType('application/dash+xml')

**Comment by glennguy** [comment]
So what does the license response normally look like? Have you checked in a browser?

A log would be nice.

**Comment by kodi0687** [comment]
The first posdata is CAQ= decoded in base 64 and the response is in raw
 
 $posdata= base64_decode("CAQ=")
 $response= base64_decode("CAUSw4cFCsOBAggDEhAXBcK5F8OMEgTChsKLBjM6L3cqwowYwoLCtMKCwpIFIsKOAjDCggEKAsKCAQEAwpnDrVs7Mn3Cq14kw6/Dg8K2KsKVwrXCmFIKw5XCvMOLN1A+BkXCuBTDmHbCuMOfQFEEQcKtwozDo8KtwrEbwrjCjE5yWl5Kwp4HwpUpHVhYQCPCp8Ohwq8OOMKpEnk5MAhhC28VwozCh8KMfiHCv8O7w77DqnfDoQHCnh5XwoHDqMKkX0YmPRTDpg7CgFjCqGB6w5zDoE/CrMKEV8KxN8Kow5Z8w43DqzNwXcKYOiHDu07DrMK9ShDDikdJDMKkfsKqXUPCghjDncK6w7HDisOeM8KSw7E9b8O7ZELDvTHDocK/QMKww4YEw5HDhMK6TMKVIMKkwr/Cl8Ouwr1gwpLCmsO8w67DtVvCusO1ZMOiw5DDp2zDl8OFXHPCoMKCwrnClhILwoNZw63DjiRwcMKCaApvZ8OGw5gsSsOFw7MTRMKQwqdOw6w3wq9LLwEMWcOoKEPDolgvC2vCn13CsMO8Xm7Dn2TDu8OTCMK0cRvDjxJQAcKcwp9aCQIDAQABOhRsaWNlbnNlLndpZGV2aW5lLmNvbRLCgAPCrjRzFMK1wqg1KX8nE8KIw7t7wrjDi1J3w5JJwoI8w53DkcOaMMK5MzlRHsKzw4zCvcOqBMK5RMK5J8OBITRuw73CvcOqw4nDlBPCkX5uw4F2wqEEOEYKUDvDgcKVK8KbwqTDpMOOD8OEwr/DggrCmAjCqsKvS8O8w5HCnB3Dj8ONw7V0w4zCrCjDkcK0EEFsw7nDnsKIBDAcwr3CszTDisO8w5DDlAl4QjpkLlRhPcOwwq/Dj8KWw4pKwpJJw5hVw6QrOnA+w7F2f2rCm8OTbWvDuCvDp2vCvwzCuk/DnlnDksKrw4x2w77CtkJHwrhcQx/CvMKlImbCthnDvDbCl8KVQ8O8wqnDi8K9wrvDusO6DhpVw6dVwqPDh8K8w6ZVw7lkb1gqwrnDj3DCqgjCuXnDuGfDtjoLK3/DmzYsW8OEw6zDlVXDmFvDisKpw4XCk8ODwoPDiFfDlMKdwqrCt35AwrfChR3Dn8OSScKYwoDCjjXCsljDp114w6rDgMOKFsO3BHMEw4IKwpPDrcOkw6jDvxxvF8OmJD4/PcKow7wXCcKHDsOEX8K6woI6Jj8Mw6/CocO3CTsZCcKSwoMmMzcFBDopwr3CpsO5wrQ0LMOIw59UPMKxwqEYL3xfw78zw7EEwpDDusOKWyU2C3YBXsKcWgbCq8KOw6AvAMOSw6jDlcKYYQTCqsOMTcOUdcO9wpbDrsKcw6TDoybDshvCg8OHBcKFd8Kzwocyw43DmsK8amvDrRPDuwpJw5PCikXDq8KHwqXDtA==")
 
 
 
 Then it does a Posdata in raw
 $posdata2= base64_decode("CAESw4ErEiwKKgoUCAESEMOQwpDDksKtFGFEQm3CmcKdNTzDpcKFChABGhDDmiHCmgDDiMO3BjTDrsOHSwXCtMO+O8KYGAEgw7PDusKIwpgGMBU4wrXDh8OIwr0BQsKAKwoUbGljZW5zZS53aWRldmluZS5jb20SEBcFwrkXw4wSBMKGwosGMzovdyrCjBrDgCjCkk9lF8OsHUh8fcOww7rDkxxxwoAadMOSw6fDq8OAw4TDuFnCu8KlFcKkCsONw7XClzPCpT8bUsOXwqXCvT7DncKNc8KIEzcRR8Ozwo1Qw7nCgXAZwrrDv00Qw5EfV0HDtMO3wpnCmC5awqXClcKUwqxzwojCshpRcx1TMn3DnMOuw4c5ODnCjcOeGEHCiz7Ck8O1w5I7wprCjgwPw6QYWcKUIFrCmXh1w43Cj8OUw6A4KsOewoXCpk5IwovDtUBdF8KmwoRTFUPDiiVVwonCjjxmacKDw5XCszPCoBLCiDrDlsOkwotEw6jCjzLDr8K2w6zCn8OJwrHCuEo3wok8HsOzwpPCkSPDvcONF8O6M8KJTB5fByLDsHJzw43DrMKcH8KOw6bCpMOAw5zDs8O9w5McwovCnGcrw5vDqsKeD25AwpzCsMKew5A7wp87w5R1w4jDpcK4wqAXCmzCisKqQGBnw5fDnwDCiRrDuhhCYsOOw5xsQMK7ScKjWsKxJxNPwpcQw7LCvVk8wqjDnsOtecOjw75owr7Co8KXwqpCI8OEbsO4w73ClsKjwpfCkwcKOsKGTDvCp8Knw58RVG4cw4nDscKWJCIAw7bCpkjCmsK3w7J4w7wxaHMZHFPCpBMBw7s3TMKqfhvCjDfCnBTDpkZBPcKyEjBDw4hQfsKHw6lTGFNNE8OoworDh1PDo8KOGGLDmcOlaXTDq3TCsXLCtTvChSfCh8Ofw4syw6Mbw4PDlmR+w4I3MWLDn8O+wr3DscKKFsOcwpHCmTTChcOEwqYhOsOzDl/CgcKTCzM1wodGw6vCt28pw6DDgjwAS2DCmk0YL8OZQjltI2TCrFt+fMKew6tCw6DCtsOlSQJaT8K6IAvDksOpw67CnMO8w6kfw59GwqfCvsOaFcOPIzBGwrp3w57CsRTDjlhMWsKUwrzCt...")
 
 $responde2=base64_decode("CAISwqoCCjQKEMOaIcKaAMOIw7cGNMOuw4dLBcK0w747wpgSEMOaIcKaAMOIw7cGNMOuw4dLBcK0w747wpgaACABKAA4AEAASMOzw7rCiMKYBhIUCAEQABgAIAAoADAAOABIAFAAWAAaZhIQwqozw6bCsMKsdFnDisOewp0nLAcfw4bDrBpQw6UCMcOpw5nDu8OVwrECwqlmwollPDA6w6zChcKhfMOBwod7GsKGwq/DqBbCkVvCohA4wod8QMKxLGJrMMKFw75dw40RwonDuMKbc8ORSMOoBsKbcHMzVcOJTCfCvW/DgHk2wobCuB/CjsO8wqvDjsO3G3rCsh1RIAEaagoQw5DCkMOSwq0UYURCbcKZwp01PMOlwoUKEhDDslPDhwZewpXCrMKuCiLDhiRtw57CjCsaID3CgnMOB2HDrsODw4wAw6vDp0PCh8Olw58LPcKfelwawoJIw5vClBNBwoY4wr/CiyACKAEyCAgAECoYACAAQhIKEGtjMTYAAAAAF8KyI8K1wqAAAAhiACDDs8O6wojCmAY4AFACGiAEEsOGw63CkMOEGWXDsEbDg33CscKFRsKzw7rDmcOmacO0wqXCpMKGw5PDicOHwoDCvcOLJsOeIsKAAcOBwpTCv8K7bmvCgE0UGCNpwr7Dui9tFMKvwrPDsMKnw77CjijDt8Kow50VwrfDosKdw5U4WcO5YCNEMMOAw6zCl3pJwrnCosKPFcK5woVowpjDkMKKIGdvFA/DpMO9e2lMUBkeYFhgCMK7wrHCscOowqFxwrXDhzTCiUbDkzt8SUfDnz7CowzDpcKiZsKvw4DCpcKmw6sUIwbDp0TCg8O6wrFOwqctw4zCl8OFwrTCjMKaw4DDg8OEO8KMO8Olw5BMwqAHwqA6MgowMTcuMS4wIEJ1aWx0IG9uIEF1ZyA1IDIwMjIgMDU6NTI6MTEgKDE2NTk3MDM5MTIpQAFKwrABAAAAAgAAAMKwAAUAEBfCsiPCtcO5w5E6wr8AAABQAAAAEAAAAGIAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAADCuAAAABAAAADDigAAABAAAADDnAAAABAAAAAAAAAAAAAAAQ4AAAAQwqxkcyjCjsKGw4bDuMOzPMKvw4TDqSbCoF8rw4nCni48wqJHNcKTw4jCsU10SQQzWAE")
 
 and an equal response in raw, this same format works for me in tivimate but in kodi I can't get it to work. Sorry for my English.
 
2022-08-21 12:09:07.689 T:10460    INFO <general>: Creating InputStream
2022-08-21 12:09:08.293 T:10460    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1366 x 768)
2022-08-21 12:09:08.463 T:10460   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\

Thread 10460 (process 3288)

**Comment by glennguy** [comment]
Turn debug logging on, reproduce and put a link to the entire log file please.

**Comment by kodi0687** [comment]
https://www.dropbox.com/s/xvqtrkfke1repzy/kodi.log?dl=0

**Comment by glennguy** [comment]
Log snippets (i.e, partial log) are useless to us.

**Comment by CastagnaIT** [comment]
issue closed as no way to investigate
