### ISSUE TITLE
Subtitle stops showing after an empty vtt file

### ISSUE THREAD

**Issue by TermeHansen** [peak3d/inputstream.adaptive#1037]
### Describe the bug
Here is a clear and concise description of what the problem is:

Subtitles stops showing after it comes to an empty vtt fil, or so it seems right now at least.
It happens from the stream provided in the master_manifest.m3u further down (Episode 3 of Sherwood), but not in the other episodes of the show. When comparing on master and subtitle m3u8 files between episodes I don't see anything different other than urls...

Looking at actual vtt file segments I saw this empty one right when kodi stops showing subtitles (from segment 4).

VTT file: "segment_0.vtt"
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000

00:00:00.840 --> 00:00:03.200
Tidligere:

00:00:03.360 --> 00:00:07.240
Gary var med i NUM.
Folk her var med i UDM -

00:00:07.400 --> 00:00:11.120
- udbryder-fagforeningen,
der brød strejken.

00:00:12.360 --> 00:00:18.400
Der snakkes om, at nogen går efter
dem, der strejkede. Hvem er den næste?

00:00:18.560 --> 00:00:23.840
- Ville nogen ramme mig?
- Hvem kunne finde på at gøre det?

00:00:24.000 --> 00:00:25.480
Det var ...

00:00:27.960 --> 00:00:34.440
Mr. Rowley, vi må vide, hvad Scott
har i sinde, så vi kan hindre det.

00:00:35.480 --> 00:00:39.520
- Ved I, hvad politispioner er?
- Politiagenter fra 60'erne og 70'erne.

00:00:39.680 --> 00:00:45.200
- De fulgte ordrer og forsvandt igen.
- Denne forsvandt tilsyneladende ikke.

00:00:45.360 --> 00:00:49.440
Vedkommende tog en ny identitet,
flyttede hertil i 1980'erne -

00:00:49.600 --> 00:00:53.760
- udspionerede de lokale
og blev her helt til vore dage.

00:00:59.400 --> 00:01:07.640
Denne historie er inspireret af to mord,
der fandt sted i en mineby
i Nottinghamshire.
```

VTT file: "segment_1.vtt"
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000

00:01:07.800 --> 00:01:14.280
Hvad laver du, Ian?
Lille Ian St Clair klædt så fint ud.

00:01:14.440 --> 00:01:20.480
Tænk, hvor stolt din far ville være.
Tænk, hvor sjovt det ville være herovre.

00:01:24.640 --> 00:01:29.360
Gary ... Nej, Gary, nej.

00:01:29.520 --> 00:01:31.840
Hold nu op, drenge.

00:01:32.000 --> 00:01:37.400
Minearbejderne giver aldrig op!
Minearbejderne ...!

00:01:39.280 --> 00:01:42.480
Minearbejderne giver aldrig op!

00:01:45.600 --> 00:01:51.880
Minearbejderne giver aldrig op!
Minearbejderne giver aldrig op!

00:01:52.040 --> 00:01:55.880
Skjolde, ryk frem!
```

VTT file: "segment_2.vtt"
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000

00:02:05.520 --> 00:02:08.800
Skruebrækkere!
Skruebrækkere!

00:02:17.560 --> 00:02:19.600
Minearbejderne ...

00:02:22.720 --> 00:02:25.440
Slip mig!
```

VTT file: "segment_3.vtt"
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000
```

VTT file: "segment_4.vtt"
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000

00:04:00.240 --> 00:04:07.200
Den mand, vi gerne vil tale med,
er Scott Rowley, 24 år.

00:04:07.360 --> 00:04:12.080
Mr. Rowley opholder sig i skovene
omkring Annesley, Newstead og Hucknall.

```
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To just let the empty vtt file pass and continue on the next ones...

## Actual Behavior

No subtitles after segment 3

## Possible Fix

Don't know

### To Reproduce

Streams are geo blocked, but we can set up again with the zerotier "vpn" if needed...

### Debuglog

The debuglog can be found here:
I can post if needed

### MPD/M3U8s/ISM

[master_manifest_fail.m3u8](https://github.com/xbmc/inputstream.adaptive/files/9566938/master_manifest_fail.m3u8.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - inputstream.adaptive version: 19.0.7

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Thanks for the report @TermeHansen 
Out of interest is this issue present in Kodi 20?

**Comment by TermeHansen** [comment]
@glennguy no, it seems to only happen in Kodi 19.

**Comment by glennguy** [comment]
Sure thing, makes sense as the subtitle parsing is completely overhauled in Kodi 20 (and happens on Kodi's side now).
@CastagnaIT any ideas on why this might be happening and if a fix would be easy?

**Comment by CastagnaIT** [comment]
my theory is that ReadNextSample in SubtitleSampleReader method return false then set "eof" to true and then not load next subs segments, this can be WebVTT::Prepare for some reason return false

but this parser for kodi 19 is too chaothic and shitty so its needed a test stream and link the debugger to understand culprit
with kodi 20 on the horizon this has such low priority to me

**Comment by CastagnaIT** [comment]
Thanks for time for reporting the problem,
we dont have no plan to developing for Kodi 19 platform
so we suggest you go ahead with Kodi v20
