### ISSUE TITLE
v20.3.0-Nexus Abnormal behavior of FF and REW

### ISSUE THREAD

**Issue by ghost** [peak3d/inputstream.adaptive#1043]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I fastforwards a netflix video then back to play(press play key) sometimes an unexpected abnormal behavior happens such as rewind or video freezing. And sometimes during FF x4 if press REW key once, normaly it shoud be FF x2. But very fast rewind (maybe REW x8?) happening sometimes. It seems that these weird behaviors and frequent video freezing or crash after FF are more likely happening when video is resumed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. I fresh installed latest kodi nexus nightly (0917)  and netflix addon on shield tv.
2. Resume a video and test FF and REW, repeated test of FF and Play, FF and REW is needed, cause it happens sometimes.

### Debuglog

The debuglog can be found here:
https://drive.google.com/file/d/1-Bjk-tY4qoVLQTfTDkW5qf0naU36_Hyz/view?usp=drivesdk

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://drive.google.com/file/d/1-Sq7Kwl2mGQf3_He3j1mZ1EA3DCoGAjR/view?usp=drivesdk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android 11/shield TV
 - Kodi version: nexus latest nightly 20220917
 - inputstream.adaptive version: v20.3.0-Nexus

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
Confirmed this should be related on WIP changes related to subtitles
that i have add a partial patch #1035 to have the seek working
@glennguy is already working on it

**Comment by glennguy** [comment]
@monsoons sorry for the lengthy delay in looking into this. Would you be able to:
a) test with Kodi 20 nightly to see if the issue remains?
b) test with the appropriate IA build (android aarch64 most likely) from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1079/1/artifacts ?

**Comment by ghost** [comment]
> @monsoons sorry for the lengthy delay in looking into this. Would you be able to: a) test with Kodi 20 nightly to see if the issue remains? b) test with the appropriate IA build (android aarch64 most likely) from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1079/1/artifacts ?

Never mind. Take your time.
a) Regardless of kodi builds(alpha3 ~RC1 late nightlies), this issue persists with v20.3.1.
b) The build you attached works fine. No issue.
Thank you.

**Comment by glennguy** [comment]
Thanks @monsoons 
Could I ask you to run one more test with the builds from #1082 - https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1082/1/artifacts ?

**Comment by ghost** [comment]
> Thanks @monsoons Could I ask you to run one more test with the builds from #1082 - https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1082/1/artifacts ?

For me no issue as well with Netflix.

**Comment by matthuisman** [comment]
Getting lots of reports about "audio but not video" on Kodi 20.0 for my various addons.

Lots of my live channel addons use seek to force the end of the stream or to a certain bit back from end of the stream.

Note: manifest type was DASH (not hls) on at least one of the addons with the issue.
https://github.com/xbmc/inputstream.adaptive/pull/1082 fixes the issues for me

**Comment by Rimtef** [comment]
Votre réponse est du chinois pour moi...pourquoi avoir clot le topic ?
