### ISSUE TITLE
Nexus H265 issues on newer version of ISA

### ISSUE THREAD

**Issue by dev77-07** [peak3d/inputstream.adaptive#1047]
### Describe the bug
Here is a clear and concise description of what the problem is:
Playing H265 media from the Hulu addon doesn't work on ISA 20.2.0-Nexus and higher. Tested with 20.1.2-Nexus and it works. 20.2.0 crashes when trying to play H265, 20.3.0 just spins and never loads, Kodi freezes if I try and exit.
Moving issue from https://github.com/matthuisman/slyguy.addons/issues/267 to here

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play H265 media without crashing or not loading

## Actual Behavior

Kodi crashes or doesn't load media

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
ISA 20.3.0: https://paste.kodi.tv/rorejuveke.kodi
ISA 20.2.0: https://paste.kodi.tv/jiwicijuxa.kodi
ISA 20.1.2: https://paste.kodi.tv/uhivalinax.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.0-ALPHA3 (19.90.710) Git:20220927-b7332d015c
 - inputstream.adaptive version: 20.3.0, 20.2.0

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
MPD of ISA 20.1.2 log: [171249737.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/9681941/171249737.mpd.txt)

Your kodi version is one of last builds, so since there is the API breaking change with these kodi versions
all ISA versions below 20.3.0 will not works
or you have self changed/builded source code to make these works but this will make only confusion to understand the causes

the log of "ISA 20.1.2" it is also weird is missing ISA stream selection logging appears like another oldest version

i can see that on log ISA 20.3.0 ISA try to playback 4k stream that should be not possible on Windows when DRM encrypted
where on the first log of "ISA 20.1.2" seem that play the 720p stream

please install ISA 20.3.0 then try open ISA settings and set Stream selection to ASK
when you play a video will be asked the video quality please try
720p / 1080p / 4k
and let me know what happens for each one

**Comment by CastagnaIT** [comment]
sorry i misread the Issue title i was thinking for H264...

DRM H265/HEVC can be played on android device that support HEVC codec
usually DRM H265/HEVC cannot be played on Windows system (maybe thing are changed meantime? so it needed widevine add the codec support)
so you can play only unencrypted H265/HEVC on Windows

@glennguy DRM H265/HEVC was really working on Windows?!

**Comment by glennguy** [comment]
![image](https://user-images.githubusercontent.com/11909320/193272738-625a94aa-462a-441a-a66c-ea40d97c6249.png)
😄 

This stream in the screencap isn't using the secure pathway/video codec, so I think there must be something wrong with how hevc data is being handled. Maybe I screwed something else up with the refactor - if I force secure pathway it won't play.

**Comment by CastagnaIT** [comment]
from CDM there is no h265
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/wvdecrypter/cdm/media/cdm/api/content_decryption_module.h#L300-L306

or it use kCodecH264 / kUnknownVideoCodec?

**Comment by dev77-07** [comment]
All 3 versions I tried were using the 3840x2160 stream not 720p, stream_01831f83-16db-b00b-356f-00fa87d925c2_1000070772996_HEVC10_16000_1000070858078_video.mp4, which according to the mpd you linked is 3840x2160
```
<Representation id="018322ff-a6fa-85cf-3da6-0022a1461d62" codecs="hev1.2.4.L153.90" bandwidth="19812609"  startWithSAP="1"             width="3840" height="2160" frameRate="24000/1001">
            <hulu:ProfileBandwidth>16000</hulu:ProfileBandwidth>
            <hulu:Cdn>fa</hulu:Cdn>
            <BaseURL>https://http-fa-darwin.hulustream.com/737/171249737/stream_01831f83-16db-b00b-356f-00fa87d925c2_1000070772996_HEVC10_16000_1000070858078_video.mp4?expires=1664610757&amp;keyid=NzkwYmRlZWMzM2VlZDQK&amp;signature=ZUIcYcyZqqaZxpKBakC1xkGsdlfews_8jEfpVeTl7uE%3D</BaseURL>
            <SegmentBase indexRange="1593-11872" indexRangeExact="true">
                <Initialization range="0-1592"/>
            </SegmentBase>
        </Representation>
```
I did compile the 20.1.2 and 20.2.0 myself which is how I got them to work on a newer Nexus nightly.

Screenshot of 20.1.2 playing 3840x2160 HEVC file on Windows
![hevc](https://user-images.githubusercontent.com/58564160/193293156-b50b75bd-a19e-484e-af54-df4e7f341c1d.png)

It does appear to be an issue with the secure pathway/crypto sessions. Before the refactor it's not using crypto session but after the refactor it uses crypto sessions and fails to play.

**Comment by glennguy** [comment]
Ok, maybe something that has broken detection of decrypter capabilities.

I'm nearly done with a refactor that fixes some other issues, I'll try to PR tomorrow and get you to test. Thanks heaps for all the detail

**Comment by CastagnaIT** [comment]
so let me understand this stream so need only decrypt not decode?

**Comment by glennguy** [comment]
Correct. Theory is that something is causing `DecryptSampleData` to return false when called from `GetCapabilities`, setting the flag to decrypt and decode.

**Comment by dev77-07** [comment]
I tried the build you linked in https://github.com/xbmc/inputstream.adaptive/pull/1048 and had the same issue, just spins and Kodi freezes when I try to exit. Debug log still shows trying to use crypto sessions. I can pull a full debug log if you'd like.

**Comment by glennguy** [comment]
> from CDM there is no h265 https://github.com/xbmc/inputstream.adaptive/blob/Nexus/wvdecrypter/cdm/media/cdm/api/content_decryption_module.h#L300-L306
> 
> or it use kCodecH264 / kUnknownVideoCodec?

Yep you're right, CDM doesn't support decrypt/decode of h265 - maybe that's why NF uses VP9 then? One less problem to worry about :)

**Comment by glennguy** [comment]
Btw trying to decrypt/decode h265 is causing the crashing. The first `VIDEOCODEC_PICTURE` passed in by Kodi seems to be uninitialized or something like it.

**Comment by CastagnaIT** [comment]
yes i think is one of the reason why NF has jump directly to AV1
can you do a small recap? this issue has been solved from some PR or not yet?

**Comment by glennguy** [comment]
Yes this is fixed from the PR you approved a few hours ago.

Trying to decrypt/decode the h265 stream was just a symptom of the underlying issue
