### ISSUE TITLE
Inputstream Adaptive can not play some MP4 videos

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1050]
Inpustream Adaptive is unable to play this mp4 video
https://ngs14c.digiteka.net/941a073012c2b5278011e843bd053adc/c3BlZWQ9MTUwO3VzZXI9bmdzO2V4cGlyZT02MzQ4NGYzZQ,,/sdf1/49/30/4930d3b63328009a32c7adec364e2c998ae53989.mp4?mdtk=04999999

It is a non drmed video. This video works fine in mpv.
Thanks for any hint to fix this problem.
Here is the interesting parto f the log I think

[redacted - attach full debug file log]

**Comment by CastagnaIT** [comment]
New issues must be opened by using our "problem report" template
please edit and fullfill the template with all required info
https://github.com/xbmc/inputstream.adaptive/issues/new?assignees=&labels=&template=bug_report.md

The log must be attached in full as file or pastebin link and not partially pasted on description
