### ISSUE TITLE
[Android] Seeking issue: Dolby Digital Plus within Zattoo 

### ISSUE THREAD

**Issue by gsicilia82** [peak3d/inputstream.adaptive#1057]
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/9795384/kodi.log)
### Describe the bug
Here is a clear and concise description of what the problem is:

Seeking in Zattoo addon with widevine_dash (1080p) can cause freezer / jitter if audio stream Dolby Digital Plus is set. It does not matter which stream is selected, if 2.1 or 5.1. 

Zattoo broadcasts different audio streams. By choosing manually AAC 2.0 stream, everything works fine. Therefore, DD+ seems to cause this issue. 

Using dash instead of widevine_dash inside Zattoo addon works fine. In this case DD+ doesn't leads to freezer / jitter. However, in this case resolution is only at 480p.

Network issue can be excluded; original Zattoo app works well without any problems. 

### To Reproduce
1. Set widevine_dash in Zattoo addon 
2. Start live broadcast, where DD+ is available (usually all) 
3. Jump forward or backward
4. Freezer / Jitter, sometimes it gets smooth after some seconds. Sometimes it stucks for long time

### Debuglog
In attachment 

### Your Environment
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Fire TV Stick 4k, Fire OS 7.6.0.3
 - Kodi version: 19.4
 - inputstream.adaptive version: 19.0.7

### BTW
I tested same procedure with Pixel 6, same issue. On x86 Ubuntu server, this issue is not reproducible. Therefore, I think it depends from Android OS.

**Comment by CastagnaIT** [comment]
Are you able to test it on last Kodi 20 nightly?

**Comment by gsicilia82** [comment]
I installed Kodi 20 alpha 3. But pvr addons were missing. Is that usual? I don't know how to cross compile for Android ARMv8.

**Comment by CastagnaIT** [comment]
you have to install last nightly not the old alpha 3
from here: http://mirrors.kodi.tv/nightlies/android/

**Comment by gsicilia82** [comment]
I installed actual nightly and Zattoo was available. I tested replay, but still same behaviour. Freezer and jitter after seek.

**Comment by glennguy** [comment]
@CastagnaIT haven't had time to look into but my gut feeling is this might be to do with the `preceeding` variable...

**Comment by CastagnaIT** [comment]
@gsicilia82 we have stop development on Kodi 19,
since now Kodi 20 is officially released please test on Kodi 20
if the problem still occurs, please attach a new debug log

**Comment by gsicilia82** [comment]
Until now, everything works well. I will observe and give you an update this weekend.
