### ISSUE TITLE
Adobe Primetime Support

### ISSUE THREAD

**Issue by TheDiamondPicks** [peak3d/inputstream.adaptive#106]
Is [Adobe Primetime](http://www.adobe.com/nz/marketing-cloud/primetime/digital-rights-management.html) support over HLS supported? If not, is this feasible for it to be included into inputstream.adaptive at some point? (however I suspect that it isn't going to be widely used as it isn't a very common DRM)

Thanks,

**Comment by peak3d** [comment]
We had discussions about this but decided to not spend the time / research on it.
If a dev comes around with experience on it, I'm open for discussions.
