### ISSUE TITLE
Please help! Can't play drm content on kodi. Kodi logs attached.

### ISSUE THREAD

**Issue by auau237** [peak3d/inputstream.adaptive#1060]
Please help me! I can't play drm content on kodi. I am attaching kodi logs. Thank you.
[kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/9847246/kodi.txt)

**Comment by L2501** [comment]
think you might need update Shield TV OS

**Comment by auau237** [comment]
I had the same Shiield tv os, and drm content was working fine. I just did a factory data reset, and drm videos stopped working. Just to be sure, I installed the same OS again, and still the same.

**Comment by CastagnaIT** [comment]
When you open an Issue you have to use our problem report template
then fullfill all required details

please edit your Issue or close and create a new one correctly

**Comment by auau237** [comment]
sorry about that. I will do that, if I can find where these rules and templates are, or if anyone can be kind enough to point me to them.
how about solving my problem, anyone?

**Comment by CastagnaIT** [comment]
To open a Issue just press:
![immagine](https://user-images.githubusercontent.com/3257156/197586817-330a8ad5-9fc7-4566-8aff-9d6299f83d00.png)
then on the new opened page select Problem report template
![immagine](https://user-images.githubusercontent.com/3257156/197586934-57944943-89a0-4280-957b-1142ec5253ea.png)

**Comment by auau237** [comment]
Thank you, I will do that.
