### ISSUE TITLE
Can't play drm content on kodi. 

### ISSUE THREAD

**Issue by auau237** [peak3d/inputstream.adaptive#1061]
### Describe the bug
Here is a clear and concise description of what the problem is:

Can't play drm content on kodi. I have Nvidia Shield tv running Full Android Oreo, and it was playing drm videos fine. I did a factory reset, and after that drm videos did't play anymore. I get the error: "one or more items failed to play. Check the log for more information about this message". I am attaching kodi log to this post.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should play without any errors popping up.

## Actual Behavior

I get the error: "one or more items failed to play. Check the log for more information about this message".

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here: attached to this post.

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - inputstream.adaptive version: 19.0.7

[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/9855411/kodi.log.txt)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
the log is without kodi debug so no detailed info

addon used is `slyguy.paramount.plus`?
@matthuisman are you aware of this addon problem?

**Comment by matthuisman** [comment]
no known issues my end. 
what is interesting is _**script.module.slyguy - Widevine Level (fallback): 3**_
It should be Level 1 for a shield.
fallback means it failed to obtain the level from kodi.
So something isn't right with this users kodi / system

I'd suggest fully removing kodi and starting fresh and see if that helps.
Also, the user could try my "Video Tester" add-on with the Widevine option to remove the VOD service variable

**Comment by auau237** [comment]
CastagnaIT and matthuisman, thank you very much, I appreciate you!
Matthuisman, I have removed kodi and started fresh about 10 times now, still the same.
Could you, please help me with this "Video Tester" add-on, I did a google search how to install it, I got nothing. Where do I find "Video Tester" add-on on kodi, and how do I install it? 
Thank you.

**Comment by matthuisman** [comment]
its in the slyguy repo under video addons.
https://www.matthuisman.nz/2018/05/kodi-widevine-support.html
Scroll down to Video Test Streams addon

**Comment by auau237** [comment]
Matthuisman, I installed Video Test Streams addon. I select "InputStream Adaptive - Dash with Widevine", and I get the dreadful: "one or more items failed to play. Check the log for more information about this message". The video doesn't play. 
Under Video Test Streams addon, "HLS" - plays fine.
"InputStream Adaptive - HLS" - plays fine.
"InputStream Adaptive - DASH" - plays fine.

**Comment by auau237** [comment]
Here is kodi log for trying to play "InputStream Adaptive - Dash with Widevine" under Video Test Streams addon, and getting the error: "one or more items failed to play. Check the log for more information about this message".
[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/9864601/kodi.log.txt)

**Comment by matthuisman** [comment]
Something is wrong with your shield or Kodi. I'd try reset shield again.

**Comment by auau237** [comment]
I have reset shield 4 times now, including installing it from scratch. The same result.

**Comment by matthuisman** [comment]
why you running such an older version of Android? that is probably the cause.
have you tried any official apps on it and see if their widevine plays? eg. the paramount app?
I can't help further sorry.

**Comment by auau237** [comment]
I like to run full android on my shield tv, not android tv os, that is why I installed full android oreo. I don't know if it is against the forum rules to post the website where I got the instruction for that. If you tell me it is ok, I can post it. That project is discontinued, so, that is why I am stuck on oreo. But, as I said, I used to play drm content fine on the same android version, until I did a reset.
Yes, paramount plus app works fine, even 4k videos. 

Matthuisman, thank you very much for all your help, I appreciate you, and I understand not being able to help anymore. Something weird is going on.

**Comment by matthuisman** [comment]
Are you sideloading Kodi or installing it from playstore?

**Comment by auau237** [comment]
From playstore, kodi is on version 19.3. I installed that, and drm doesn't play. From their website - kodi.tv - I downloaded version 19.4, I installed it, and still drm doesn't play.

**Comment by matthuisman** [comment]
i have no more ideas sorry. Maybe @CastagnaIT has some input.
I dont think this is a bug in Inputstream or the add-on itself but rather something to do with your setup.

**Comment by auau237** [comment]
I like to play videos on kodi, because I can amplify the audio as much as I want, and zoom in as much as I want - the official app doesn't allow for those.
Thank you again.

**Comment by CastagnaIT** [comment]
what means exactly this? can you explain more

> I like to run full android on my shield tv, not android tv os that is why I installed full android oreo.

if you have replaced the ROM in some unofficial way you could have broken widevine

**Comment by auau237** [comment]
I have installed full android oreo rom, which, as far as I understand, is part Nvidia shield tv OS and part full android OS - like a tablet functionality. I can post the webpage url, if you want and if it is not against the forum rules.
But, as I said before, under this Rom, widevine was fine and I was playing drm videos fine.

**Comment by glennguy** [comment]
Hi guys, sorry for joining in late.

I think this one is fairly simple - the first log file posted shows http 400 errors when trying to provision the device for both L1 and L3.
This indicates that the device can't play Widevine protected content at all. @auau237 you should be able to confirm that installing the paramount app from the playstore will also fail to play content.

Solution: install a rom that supports Widevine in the current day. Hopefully unlocking bootloader/installing custom roms has not wiped the device's ability to get Widevine provisioning.

This is not a Kodi/inputstream.adaptive problem.

**Comment by auau237** [comment]
glennguy, thank you for your help, appreciate you. paramount+ app plays videos fine, even 4k. Even cheap android tv boxes from china can play widevine protected content, I understand they play in SD, 480p, but they do play netflix or prime video. I have watched many youtube videos on many such boxes. And I never heard of a tv box not playing at all netflix for example or prime video.

**Comment by auau237** [comment]
I think, and please correct me if I am wrong, that the ability of an android tv box to play widevine protected content, is a software issue. So, as long as you install the same rom correctly, the ability to get Widevine provisioning should be there. So, I don't believe that installing custom roms has wiped the device's ability to get Widevine provisioning, since, as I mentioned before, the same custom rom I have now was working fine, and was playing widevine content even in 4k.

**Comment by CastagnaIT** [comment]
i just installed `Video Test Streams` addon on my Nvidia shield that has the last official firmware
then tried to play "InputStream Adaptive - Dash with Widevine"
i can confirm that works without problems until 1080p stream

so provide a log when you play "InputStream Adaptive - Dash with Widevine" and remember to enable kodi debug
so we can check if there is the same error or different

**Comment by CastagnaIT** [comment]
I have now seen the log above, so its same error
the only difference is that i tested on Kodi 20
@auau237 can you try test with last Kodi 20 nightly?
from http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/

**Comment by auau237** [comment]
I installed kodi 20 days ago. I tried to play video, I get the error: inputstream adaptive is missing. I downloaded inputstream.adaptive.20.3.1-Nexus.zip, tried to install it on kodi, kodi doesn't install it, I get error message: failed to install the addon due to invalid structure.

**Comment by auau237** [comment]
ok, my bad... in kodi 20 nightly, Inputstream.adaptive installs fine under VideoPlayer Inputstream. 

I installed Video Test Streams from SlyGuy repo. I play "InputStream Adaptive - Dash with Widevine", and I get the error: "one or more items failed to play. Check the log for more information about this message".

**Comment by auau237** [comment]
I have the kodi log debug file ready to post after testing "InputStream Adaptive - Dash with Widevine". Many times I have asked, do these log files contain any personal info about my device and my internet connection? It may be too late now, since I already have posted many logs, but I want to know anyway because it is debug log and contains a lot of info, too large a file. If somebody can tell me, I would appreciate it, so I can delete anything that is personal before posting.

**Comment by CastagnaIT** [comment]
the Kodi log never contains personal information, but,
could contains something if some "bad/unofficial" installed addon print unwelcome information because it dont follow Kodi rules, in this case simply disable it temporarily

the log should be not of large mb, if so is because you have enabled "debug specifics component" that is not required

testing on Kodi 20 was more of a curiosity to rule out a possibility
but if the same error persists, as @glennguy said you have a problem with widevine of your current ROM
the DRM request being made (that fails) is a standard request that FWIK cannot be changed
i also suggest you to update your Shield to last official ROM

**Comment by auau237** [comment]
Thank you, CastagnaIT, and everyone that helped in this, I appreciate you.
I will post kodi debug log anyway. I understand you all have done a lot, but you never know if you or someone new to this post can come up with a solution. So, if you want to close this post, it's ok by me. If you want to leave it open for some 'miracle' to happen, that's ok too.
Thank you!

[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/9876597/kodi.log.txt)

**Comment by glennguy** [comment]
@auau237 thanks for the debug log, it becomes much clearer where the process is failing.

@CastagnaIT I'm noticing that we send the request signature as POST data, whereas for example ExoPlayer sends an empty POST request and adds the signed request as ulr param: https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/core/src/main/java/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.java#L119-L128

**Comment by CastagnaIT** [comment]
interesting we can give a try but not sure how decode utf8 data

we have to remember also that same method is on kodi side
https://github.com/xbmc/xbmc/blob/68bf07ee4fab9f844a9bef3ddeeb443be45d9453/xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp#L269-L298

**Comment by auau237** [comment]
[glennguy](https://github.com/glennguy), and [CastagnaIT](https://github.com/CastagnaIT), thank you very much for continuing to help on this. Obviously, you both understand that your last posts are alien to me, I don't understand a thing you are saying....lol. Hopefully you can solve this. Thank you.

**Comment by glennguy** [comment]
@CastagnaIT thanks for pointing out the Kodi side method. Looks like they do it the same way as in exoplayer. I'm not convinced this is the issue though.

@auau237 one more thing to look at would be Android logcat. If there's any way you can provide this for around the time the failure happens it may help

**Comment by auau237** [comment]
[glennguy](https://github.com/glennguy), thank you very much again. I will provide Android logcat, I just need to find out what it is and where can I find it searching on google of course.

**Comment by auau237** [comment]
is it the one under \system\bin\? I got the file logcat there, but I can't open it with notepad? How can I open and read through it? I need to know if there is some personal info there before posting it.

**Comment by CastagnaIT** [comment]
you have to read it by call the system app
if you have installed adb on your computer, you can get it by run on cmd shell
`adb connect 192.168.x.x` (replace with your shield IP)
`adb shell logcat -d > mylogcat.txt`

**Comment by auau237** [comment]
I installed adb and fastboot.
no matter what I do I get: "can't connect to 192.168.1.4"
I checked, my shield ip is correct. 
fastboot devices cmd shows my shield.
adb devices cmd shows nothing.

**Comment by CastagnaIT** [comment]
if you dont have enabled adb in the developer options on shield you cant connect it
you can find instructions on web

**Comment by auau237** [comment]
yes, developer option is enabled, and usb debugging is enabled.

**Comment by CastagnaIT** [comment]
ensure to have last adb version (v33) (https://developer.android.com/studio/releases/platform-tools)
when you connect on shield appears a message for the authorization that must be accepted
if "can't connect to" still appears so you have some other network problem or software like antivirus/firewall that block it
