### ISSUE TITLE
Question about "Invalid max HDCP"

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1063]
I'm trying to add support for a streaming platform. So far it works on PC and some android devices. But now I tested on a chromecast with google tv and I get this error when trying to get the license:
`{"status":"UNGRANTED_REQUEST","code":400,"errorCode":2104,"message":"Invalid request"}`

Apparently the error 2104 means "Invalid max HDCP version in the licence request."
How can I fix it?

**Comment by CastagnaIT** [comment]
to understand better the situation
you should provide a full kodi debug log
and also the manifest response data

it is possible that you have requested a manifest with incorrect HDCP

**Comment by Paco8** [comment]
The full log: https://paste.kodi.tv/godifibaja.kodi
The manifest: https://paste.kodi.tv/elotogihew

**Comment by CastagnaIT** [comment]
i dont see nothing relevant
usually if you have a wrong HDCP the problem happens on playback not when you request the license
imo could be possible you have some wrong or missing http header

**Comment by glennguy** [comment]
Yes I agree, can't see what would be wrong.

I would suggest having a look at logcat as well, and also comparing to logcat when you play through the official app.

**Comment by Paco8** [comment]
I finally was able to fix this problem by setting the certificate with the option `inputstream.adaptive.server_certificate`.
After that I found an additional problem, inputstream adaptive was making two license requests in a row, the second one failed because of a "reused token". I fixed it by writting a proxy so that I could change the token, isn't there an easier way?

**Comment by CastagnaIT** [comment]
closed as root problem has been solved
if you need other kind of solution for the last question
i suggest to open a new issue by providing logs/info that help us to investigate

**Comment by glennguy** [comment]
The 2 license requests issue is solved in the forthcoming version (both Nexus/Omega)
