### ISSUE TITLE
Playbacks stops after 1 minute (ism)

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1064]
### Describe the bug

I'm trying to add support for a streaming platform but I have a problem with live streams, they only play 1 minute and then stop.

## Expected Behavior
Playback shouldn't stop.

## Actual Behavior
Playback stops after 1 minute.

### Debuglog
The log: https://paste.kodi.tv/haxavuroxi.kodi

### MPD/M3U8s/ISM
The manifest: https://paste.kodi.tv/ihihudifoy

## Additional context or screenshots (if appropriate)

```
play_item.setProperty('inputstream.adaptive.license_type', 'com.widevine.alpha')
play_item.setProperty('inputstream.adaptive.license_key', '{}?token={}||R{{SSM}}|'.format(license_url, token))
play_item.setProperty('inputstream.adaptive.server_certificate', certificate);
play_item.setProperty('inputstream.adaptive.manifest_type', 'ism')
```

I try adding `play_item.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')` but it doesn't make any difference.
What am I doing wrong?

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3
 - inputstream.adaptive version: 19.0.7

**Comment by Paco8** [comment]
After comparing the manifest with another one from another channel which didn't have the problem, and testing with a proxy I think I found the problem. It's this in the manifest:
`IsLive="true"`

It seems inputstream.adaptive expects "true" to be un upper case. If I replace it with `IsLive="TRUE"` then it doesn't stop.

**Comment by CastagnaIT** [comment]
thanks you have found the culpit
i will backport the fix to matrix soon

**Comment by CastagnaIT** [comment]
if you can confirm the fix,
you can find android apk test builds here (kodi 19):
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1069/1/artifacts

**Comment by Paco8** [comment]
I've just tested on an Android TV, and yes, it works. Thank you very much for the fix.
