### ISSUE TITLE
Inputstream adaptive 20.3.1-Nexus  can not be installed in Kodi 20 Nexus alpha 3

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1065]
### Describe the bug
When I try to install Inpustream adaptive (as well as Inputstreamffmpegdirect) in Kodi 20 Nexus Alpha 3,
the install process fails with the message
"The dependency on kodi.binary.instance.inputstream version 3.2.0 could not be satisfied."

## Expected Behavior
Inpustream adaptive should install

## Actual Behavior
Kodi complains: ""The dependency on kodi.binary.instance.inputstream version 3.2.0 could not be satisfied.""

## Possible Fix
Don't know what to do with that. Sorry.

### To Reproduce
1.  install kodi (as well in Windows 11 (64 bits or 32 version) or Android
2.Try to install inputstream adaptive **20.3.1-Nexus** or inputstreamffmpegdirect

### Debuglog
The debuglog can be found here: [kodi.log](https://github.com/xbmc/inputstream.adaptive/files/9914620/kodi.log)

### MPD/M3U8s/ISM
Happens before I can load any MPD...

## Additional context or screenshots (if appropriate)
I was attempting to install inputstream adaptive **20.3.1-Nexus**

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nexus 20 alpha 3
 - inputstream.adaptive version: **20.3.1-Nexus**

**Comment by fuzzard** [comment]
You'll need to use newer nightlies. There was an API bump shortly after alpha 3.

**Comment by joaopa00** [comment]
Thanks you for the advice.
Indeed, that's fixed the problem.
I close this ticket then.
