### ISSUE TITLE
[BUG] No Picture for drm video, eg netflix

### ISSUE THREAD

**Issue by e-ru** [peak3d/inputstream.adaptive#1070]
## Bug report

Hello

This a bug report i posted some days ago in the libreelec [issue tracker](https://github.com/LibreELEC/LibreELEC.tv/issues/7088). All information, bug description, system, logs, etc are there.

### Describe the bug

Basically it's about this error i get when i try to play a drm encoded video:
```
2022-11-16 22:39:58.450 T:1243    error <general>: CEGLImage::CreateImage - failed to import buffer into EGL image: 0x3003
2022-11-16 22:39:58.467 T:1243    debug <general>: EGL Debugging:
                                                   Error: EGL_BAD_ALLOC
                                                   Command: eglCreateImageKHR
                                                   Type: EGL_DEBUG_MSG_CRITICAL_KHR
                                                   Message: dri2_create_image_khr_texture
2022-11-16 22:39:58.467 T:1243    debug <general>: CEGLImage::CreateImage - attributes:
                                                   EGL_WIDTH: 1280
                                                   EGL_HEIGHT: 720
                                                   EGL_LINUX_DRM_FOURCC_EXT: YU12
                                                   EGL_YUV_COLOR_SPACE_HINT_EXT: EGL_ITU_REC601_EXT
                                                   EGL_SAMPLE_RANGE_HINT_EXT: EGL_YUV_NARROW_RANGE_EXT
                                                   EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT: EGL_YUV_CHROMA_SITING_0_EXT
                                                   EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT: EGL_YUV_CHROMA_SITING_0_EXT
                                                   EGL_DMA_BUF_PLANE0_FD_EXT: 117
                                                   EGL_DMA_BUF_PLANE0_OFFSET_EXT: 0
                                                   EGL_DMA_BUF_PLANE0_PITCH_EXT: 1344
                                                   EGL_DMA_BUF_PLANE1_FD_EXT: 117
                                                   EGL_DMA_BUF_PLANE1_OFFSET_EXT: 967680
                                                   EGL_DMA_BUF_PLANE1_PITCH_EXT: 1344
                                                   EGL_DMA_BUF_PLANE2_FD_EXT: 117
                                                   EGL_DMA_BUF_PLANE2_OFFSET_EXT: 968352
                                                   EGL_DMA_BUF_PLANE2_PITCH_EXT: 1344

```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
video plays normally

## Actual Behavior
video playback starts but it's output is just the kodi interface, like a picture freeze.

## Possible Fix
absolutely no idea

### To Reproduce
1. use this [nightly version](https://test.libreelec.tv/11.0/Generic/Generic/LibreELEC-Generic.x86_64-11.0-nightly-20221104-534ecbc.img.gz)  of libreelec
2. install inputstream helper in version 0.5.10+matrix.1 and inputstream adaptive in version 20.3.1.1
3. install netflix addon from [this repo](https://github.com/castagnait/repository.castagnait/raw/kodi/repository.castagnait-2.0.0.zip)
4. play random video on netflix
5. see the logs for the error

### Debuglog
The debuglog can be found here:
[pastekodi details](http://ix.io/4eYJ)

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
```
[plugin.video.netflix (0)] Requesting manifest (version default) for
                                                   VIDEO ID: 80098733
                                                   ESN: NFCDCH-LX-JPC3T1550Y1N13D9A8X4E328K79Y57
                                                   HDCP: []
                                                   PROFILES:
                                                   [ 'heaac-2-dash',
                                                     'heaac-2hq-dash',
                                                     'BIF240',
                                                     'BIF320',
                                                     'playready-h264mpl30-dash',
                                                     'playready-h264mpl31-dash',
                                                     'playready-h264mpl40-dash',
                                                     'playready-h264hpl22-dash',
                                                     'playready-h264hpl30-dash',
                                                     'playready-h264hpl31-dash',
                                                     'playready-h264hpl40-dash',
                                                     'h264mpl30-dash-playready-prk-qc',
                                                     'h264mpl31-dash-playready-prk-qc',
                                                     'h264mpl40-dash-playready-prk-qc',
                                                     'webvtt-lssdh-ios8',
                                                     'vp9-profile0-L21-dash-cenc',
                                                     'vp9-profile0-L30-dash-cenc',
                                                     'vp9-profile0-L31-dash-cenc',
                                                     'vp9-profile0-L40-dash-cenc',
                                                     'ddplus-2.0-dash',
                                                     'ddplus-5.1-dash',
                                                     'ddplus-5.1hq-dash',

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
 - LE Version: LibreELEC-Generic.x86_64-11.0-nightly-20221104
 - Hardware Platform: CPU: 11th Gen Intel(R) Core(TM) i5-11400, GPU: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.3, DRM 3.48, 6.0.6)
 - linux version: 6.0.6

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC-Generic.x86_64-11.0-nightly-20221104
 - Kodi version: 20.0-BETA1
 - inputstream.adaptive version: 20.3.1.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i have answered on the libreelec issue linked,
if @glennguy has other suggest otherwise i suggest to try tranfer this issue to xbmc repo

**Comment by glennguy** [comment]
@CastagnaIT I agree with your suggestion. This is not a 'bug' according to the thread on libreelec

**Comment by e-ru** [comment]
thanks for clarification. will follow your suggestions asap.

best erik
