### ISSUE TITLE
Chromecast with Google TV and Dolby Vision not working properly

### ISSUE THREAD

**Issue by pggion** [peak3d/inputstream.adaptive#1073]
### Describe the bug
When I play streaming Dolby Vision in add-on (Disney Plus, for example), the video goes out of sync with the audio, and sometimes goes faster and other slowly.  This started to happen after the Android 12 update in the Chromecast with Google TV 4k. I am using Kodi Nexus Maven, but also happened in Kodi Nexus normal.

## Expected Behavior
A normal playback of Dolby Vision streaming video.

## Actual Behavior
When I play streaming Dolby Vision in add-on (Disney Plus, for example), the video goes out of sync with the audio, and sometimes goes faster and other slowly.

### To Reproduce
Here is the link with the Kodi log: https://paste.kodi.tv/sanebejahi

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: 20
 - inputstream.adaptive version: last one according to Kodi autoupdate
 - I am using Chromecast with Google TV 4K (Sabrina)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i read on the net that more users complains of hdr/dv/refresh problems on Chromecast with Android 12 firmware update that suggest a firmware bug,
here we dont handle changes for a specific device firmware,
This Issue [22072](https://github.com/xbmc/xbmc/issues/22072) is similar so i suggest you to follow that Issue

**Comment by pggion** [comment]
Grazie!
I will follow that thread then.
