### ISSUE TITLE
License response in json, base64 AND urlencoded

### ISSUE THREAD

**Issue by cache-sk** [peak3d/inputstream.adaptive#1074]
Hello, i am trying to play this widevine encrypted free music tv stream via kodi - https://loungetv.cz/ltv-play

License request looks like this:

`{"timestamp":1670414719,"offset":0,"version":"0.1","edges_id":1,"devices_identification":"LoungeTV Web","devices_hash":"LoungeTV Web","rawLicense":"EkgSPBo6CjQKEPzIbni1-5HtZJFySuL_xdoSEPzIbni1-5HtZJFySuL_xdoaACABKAA4AEAASIGDwpwGEDsYABgCIL2DwpwGMBUaILrmQsYxZ7wrzGsfUREga8q5NOvjNJcPc4SJWEBGwaui"}`

License response looks like this:

`{"isRenewal":false,"rawLicense":"CAISuwUKNAoQUJuj4D9vCfnmJlGkx\/oq+xIQUJuj4D9vCfnmJlGkx\/oq+xoAIAEoADgAQABIraDCnAYSEggBEAAYASCCATCCAThQSDxQChpmEhCeL6P7NB1nFWaBjGyINldEGlA\/6d5MmVdX4huLR7VlOYhsa2X2h7up04X2KR92FQpBC0FcYUgkDTK85CyJ8S9dmrI8gnNraWeRBHboEOzHKPO5mzLE3si1N5d5G8oqyFht+yABGmUKEBD8cgKtwrB5gF1EKIeAWjYSEHGrC6cicfxtR4P\/RWUJbugaIEiEftvGnARzw37xI+tGhTrSSq1q+hbuugDBAR41W8PyIAIoAUISChBrYzE2AAAAgoVGHnKAAAAIYgVBVURJTxpiChC7s5P3eAwombJ6DD0ghlFIEhAjmJmjLckTakpS5h3lKp5KGiCXdJWjHUrKCvwxkA6LYq2IHGrMpEm\/N8ZACzhizmcD\/iACKAFCEgoQa2MxNgAAAIKFRh5ygAAACGICSEQaYgoQslwdnHuTT71kEVGwWWf16xIQtCWKsDqJVoiYTTi7AoI0RhogEofzJs+z5xSCqNM7+0y3yngMrwFoSk4Oq\/bdCV\/ebYUgAigBQhIKEGtjMTYAAACChUYecoAAAAhiAlNEGmQKEOAqjgqKkN0N43tdWvX1U24SEDO3T3EI7rAFYGMTzIvsup8aIC9sJX3pHiwMUY+4roAfJHayaaqfYGtZn6zvfU8HAIvDIAIoAUISChBrYzE2AAAAgoVGHnKAAAAIYgRVSEQxGmQKEHNF\/f7hMjdgeGl1ZVplUxASEGlZ5Z6zNkx4VyNoRNOrQV0aIJsD\/VdmTFSomj2yOxC6glHGApRlKmw\/8K0oewbXXGOjIAIoAUISChBrYzE2AAAAgoVGHnKAAAAIYgRVSEQyIK2gwpwGOPPGiZsGUAUaIOx8FYlentF03xjus9EbdqXNZI4Vj5ydTR\/+6PFxxUhdIoABm013Q2CzPx2QZFhIaIG9ttmr9pb17ajEz2RGOBb2y8WR1OBIfODasPJ4fjvkMfeNgZLZRBIfnUrS0iEr4kEuqoSlXnnJ6ZD\/k1YdJX8YugLiXGO6pkGTgZFbK9VDACgp8NLyca9B66jzSIl0ww2cX4WXnnNR6EWTAKNq98B1nc06MgowMTcuMy4wIEJ1aWx0IG9uIE5vdiAxIDIwMjIgMTU6MTI6MzQgKDE2NjczNDA3MjUpQAFK0AIAAAACAAABUAAFABCFRh5yN7qvRgAAAE4AAAAQAAAAYAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAIIAAAAAAAAAAAAAAAAAAACMAAAABQAAALYAAAAQAAAAyAAAABAAAADaAAAAEAAAAAAAAAAAAAABAgAAABAAAAEdAAAAEAAAAS8AAAAQAAABQQAAABAAAAAAAAAAAAAAAQIAAAAQAAABgQAAABAAAAGTAAAAEAAAAaUAAAAQAAAAAAAAAAAAAAECAAAAEAAAAeUAAAAQAAAB9wAAABAAAAIJAAAAEAAAAAAAAAAAAAABAgAAABAAAAJLAAAAEAAAAl0AAAAQAAACbwAAABAAAAAAAAAAAAAAAQIAAAAQv6fIq5U3b67XIYJw3B0NGBRvMeis+PQ0RBBmiLau3NxYAQ=="}`

License key should be something like this (or with b{SSM}, tried both): 

`'URL|HEADERS|{"timestamp":1670414719,"offset":0,"version":"0.1","edges_id":1,"devices_identification":"LoungeTV Web","devices_hash":"LoungeTV Web","rawLicense":"B{SSM}"}|JBrawLicense'`

But video is "garbled" and in log is error `DecryptSampleData: Decrypt failed with error: 2 and key: ...`

Then i have noticed, that in response there are backslashes, so it seems that content of rawLicense is probably url encoded (or base64url alphabet).

For post data, there is b{ssm} for base64 and B{SSM} for base64 and url encoded.

For response there is no option to url decode content of json token.. Or am I missing something?

Thanks.

**Comment by mtr81** [comment]
Problem is that IS for Kodi 19 doesn't support DRM cbcs mode -> https://github.com/xbmc/inputstream.adaptive/issues/1056#issuecomment-1282228304 Could you try your addon on Kodi 20?

**Comment by cache-sk** [comment]
@mtr81 

Yes, it works in Nexus :) Same "loungetv" as in your issue :)

So it is solved then, closing issue.
