### ISSUE TITLE
inputstream Adaptive not compatible with newest python 3.11.1 on Libreelec nightly Raspberry Pi 

### ISSUE THREAD

**Issue by hbbernardo** [peak3d/inputstream.adaptive#1075]
I had an issue with my copy of Libreelec running Kodi 20 beta. I had to make a clean install 

The thing is. I have discovered that Inputstream Adaptive is not being offered as a dependency on today's version of Libreelec right from their nightly repositories.

https://test.libreelec.tv/11.0/RPi/RPi2/

I'm running a Raspberry Pi 3B+ and here's is what has changed from the previous working build (December, 5th) to today's (December 7th)

2022-12-07 (cfd7db5):#7173  Revert 32-bit Y2038 changes
2022-12-07 (a3499ee):#7211 Python3: update to buildroot 3.11.0 patches
2022-12-07 (675e9b2):#7216 Python3: update to 3.11.1
2022-12-07 (89f2e5d):#7209 cleanup addons
2022-12-06 (32d2d3a):#7212 Minor package updates
2022-12-06 (fedee34):#7215 scripts/build: update TRACE_BUILD_TIMING

PS; There was no build for December, 6th.

If you search for Inputstream on Kodi Addons you'll only find Inputstream Helper is available to be installed. 

I'm only reporting here the situation on Libreelec. But I suspect that something similar must be happening with other platforms. 

Can you please have a look on it?

Thanks

**Comment by Vikassm73** [comment]
Try the steps

https://wiki.libreelec.tv/how-to/force-add-on-update

After that check for 

Add-ons > Install from repository > Kodi Add-on repository > VideoPlayer InputStream

and install inputstream adaptive from there

**Comment by hbbernardo** [comment]
I've followed the steps suggested. To no avail 

There's no Inputstream Adaptive in my fresh copy of LibreElec. 

I even uninstalled the Netflix Addon. Rebooted. And that is what I got for its dependencies upon reinstallation (see images)

![screenshot00002.png](https://user-images.githubusercontent.com/24485236/206453230-01c9a41f-b772-45d8-8759-c2a249f0a16f.png)

![screenshot00000.png](https://user-images.githubusercontent.com/24485236/206452787-c1c1feac-af0b-483b-bfec-4197013855c3.png)

**Comment by hbbernardo** [comment]
For the sake of testing I downgraded LibreElec to the nightly version released in December, 5th 

Then I uninstalled Netflix for Kodi. Rebooted. Then installed again. And it was offered the option to install inputstream adaptive as it should.

Then I upgraded again to the latest nightly build of LibreElec which at the time of this writing is from December, 7th inputstream adaptive is still appearing as enabled.

But Inputstream FFMPEG Direct is failing to install

**Comment by hbbernardo** [comment]
Another update.

When I tried to play something on Netflix for Kodi LibreElec crashed. 

To normally play it. I had to downgrade LibreElec to the December, 5th build that is being offered:

I suspect that this issue is indeed related to the bump LibreElec made on their version of Python 3 to 3.11.1

You can see the daily changelog at the bottom of the nightly download page:

https://test.libreelec.tv/11.0/RPi/RPi2/

**Comment by vpeter4** [comment]
Maybe related to this?  https://forum.libreelec.tv/thread/26357-attention-le11-nightly-2022-12-08-will-cause-issues-with-binary-addons/

**Comment by glennguy** [comment]
@hbbernardo can we close this issue? It seems to be a) not something that we control from this end and b) nothing to do with python bumps in Kodi

**Comment by hbbernardo** [comment]
> @hbbernardo can we close this issue? It seems to be a) not something that we control from this end and b) nothing to do with python bumps in Kodi

Yes, you can. It was solved by the LibreElec devs.
