### ISSUE TITLE
How to give datas to license server?

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1077]
That is not a bug, but a help request. I have to give datas to license server. How can one achieve that?
Here is my python code that works well when calling the license server

`import requests

headers = {
    'authority': 'tf1.live.ott.irdeto.com',
    'accept': '*/*',
    'accept-language': 'fr,fr-FR;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
    'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNoYTI1NmVURjFfMSIsInR5cCI6IkpXVCJ9.eyJhaWQiOiJ0ZjEiLCJleHAiOjE2NzA5NDk1ODIsImlhdCI6MTY3MDk0OTU1MiwiaXNzIjoiZXRmMS1kZWxpdmVyeSIsImp0aSI6IjY3NWRjMzkwLTA0Y2MtNDc2NC1hMmExLTkzMmUyNGU5NmUzYSIsInN1YiI6ImdpZ3lhLTAzYTcwODRiLTIxYzctNDdmMS1hMDcwLTZiODI5ODQ2NGQ3YiJ9.1k9MiTRD6hCKqz_bzSr2hhF1ii5bTvMrk17enlrEVZs',
    'origin': 'https://prod-player.tf1.fr',
    'referer': 'https://prod-player.tf1.fr/',
    'sec-ch-ua': '"Not_A Brand";v="99", "Microsoft Edge";v="109", "Chromium";v="109"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': '"Android"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 Edg/109.0.1518.14',
    'content-type': 'application/x-www-form-urlencoded',
}

params = {
    'contentId': 'TMC',
    'keyId': 'df6a6a8b-5ba2-4d9c-ae00-1f9357fe7f3b',
}

data = '\b\x04'

resp = requests.post(
    'https://tf1.live.ott.irdeto.com/licenseServer/widevine/v1/tf1/license',
    params=params,
    headers=headers,
    data=data,
)
print(resp)
print(resp.text)

`

When using inpustream helper, I have that for now, but it does not work

`import inputstreamhelper
from codequick import Listitem

video_url = 'https://live-tmc-das-secure.cdn-0.diff.tf1.fr/out/v1/058058c2718948b994dbbcd22d960b0b/index.mpd'
license_url = 'https://tf1.live.ott.irdeto.com/licenseServer/widevine/v1/tf1/license?contentId=TMC&keyId=df6a6a8b-5ba2-4d9c-ae00-1f9357fe7f3b'
headers = {
    'User-Agent': web_utils.get_random_ua(),
    'referer': 'https://prod-player.tf1.fr',
    'content-type': 'application/x-www-form-urlencoded',
    'authority': 'tf1.live.ott.irdeto.com',
    'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNoYTI1NmVURjFfMSIsInR5cCI6IkpXVCJ9.eyJhaWQiOiJ0ZjEiLCJleHAiOjE2NzA5NDk1ODIsImlhdCI6MTY3MDk0OTU1MiwiaXNzIjoiZXRmMS1kZWxpdmVyeSIsImp0aSI6IjY3NWRjMzkwLTA0Y2MtNDc2NC1hMmExLTkzMmUyNGU5NmUzYSIsInN1YiI6ImdpZ3lhLTAzYTcwODRiLTIxYzctNDdmMS1hMDcwLTZiODI5ODQ2NGQ3YiJ9.1k9MiTRD6hCKqz_bzSr2hhF1ii5bTvMrk17enlrEVZs'
}

item = Listitem()
item.path = video_url
item.property[INPUTSTREAM_PROP] = "inputstream.adaptive"
item.property['inputstream.adaptive.license_type'] = 'com.widevine.alpha'
item.property["inputstream.adaptive.manifest_type"] = 'mpd'
item.property['inputstream.adaptive.stream_headers'] = urlencode(headers)
item.property['inputstream.adaptive.license_key'] = '%s|%s|R{SSM}|' % (license_url, urlencode(headers))`

My probelm is : how to give the '/b/x04' to the license_key?

**Comment by joaopa00** [comment]
Fixed by changing the license url
SOrry for the noise

**Comment by Vikassm73** [comment]
contentId= 'TMC'
keyId='df6a6a8b-5ba2-4d9c-ae00-1f9357fe7f3b'        
lic_url = 'https://tf1.live.ott.irdeto.com/licenseServer/widevine/v1/tf1/license'
lic_hdr = 'Content-Type=&contentId=%s&keyId=%s' % (contentId, keyId)
license_key = '%s|%s|R{SSM}|' % (lic_url, lic_hdr)
item.property['inputstream.adaptive.license_key'] = license_key

**Comment by CastagnaIT** [comment]
you are sending a post request with as data the DRM Challenge

from here:
> item.property['inputstream.adaptive.license_key'] = '%s|%s|R{SSM}|' % (license_url, urlencode(headers))`

the `R{SSM}`,
so it seems that from what you say you have to replace it with your data
maybe something like

```py
data = '\b\x04'
item.property['inputstream.adaptive.license_key'] = '%s|%s|%s|' % (license_url, urlencode(headers), data)`
```

**Comment by glennguy** [comment]
` /b/x04` is only normally happening on platforms that support VMP (not Kodi). This request won't get you keys in the response.
This 2 byte value is generated automatically by the CDM when it needs to. It doesn't in our case.

Wherever it is that you're capturing the traffic that normally goes to irdeto for the license, check the next POST request which will have a much larger payload than 2 bytes (sometimes ~4000 or ~6000) and that will have a response with keys in it.

What is the response you get from your existing code (which looks correct from first glance btw)? If it's 403 then the service provider may be enforcing VMP which is bad news. In that case it should normally mention in the response.

**Comment by joaopa00** [comment]
With my current code, I receive error 500

**Comment by glennguy** [comment]
My question above wasn't about your current code. Look in Chrome/Firefox/Whatever in dev tools and see what the traffic is there.

**Comment by joaopa00** [comment]
I managed to give a correct license. So my problem if somewhat fixed...
