### ISSUE TITLE
Kodi 19.4 (Matrix) crashes when playing H.265 (HEVC) streams

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1078]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi Matrix (19.4) crashes when playing H.265 (HEVC) streams with version 19.0.7 of InputStream Adaptive.
This happens with a new MagentaTV Megathek (Test) Addon
## Expected Behavior
Here is a clear and concise description of what was expected to happen:
No crashing, but playing the stream as it should. 
## Actual Behavior
When starting an H.265 stream with InputStream Adaptive, Kodi crashes back to the home screen of the Samsung Tab
### To Reproduce
1. Start Kodi
2. Open the MagentaTV Megathek Addon
3. Try to play a stream which is H.265 encoded (I used "Jumanji").
### Debuglog

The debuglog can be found here:
[kodi_HEVC.log](https://github.com/xbmc/inputstream.adaptive/files/10216943/kodi_HEVC.log)
## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Samsung Galaxy Tab A (2018, 10.5) SM-T590

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 10
 - Kodi version: 19.4 (Matrix)
 - inputstream.adaptive version: 19.0.7

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Hi there,

Do you happen to know if this affects other platforms?

Also is there a way we could get access to a stream from this service to test? It doesn't appear geolocked which is a good start :)

**Comment by werimail** [comment]
Unfortunately, I cannot answer whether other platforms are affected. At least on my Android TV environments (Magenta TV Stick and Nvidia Shield TV 2019 Pro) the HEVC streams run.
I was hoping that the streaming addresses from the log file could be used for test purposes...I think Amazon Prime also offers HEVC streams (at least this could be activated in the [addon](https://github.com/Sandmann79/xbmc) in the past).

**Comment by CastagnaIT** [comment]
@werimail since Kodi v19 is EOL we have stopped the development on that platform,

please try test if the problem still happens on Kodi v20
if so, provide a new debug log
