### ISSUE TITLE
YouTube DASH broken on Kodi

### ISSUE THREAD

**Issue by greenmr** [peak3d/inputstream.adaptive#108]
For about a week now YouTube videos on Kodi have been stuck at 720p, and as I suspected the official YouTube plugin forum says that YouTube changed their DASH API. At least I'm not forced down to SD resolution, but I don't see any mention here that peak3d is aware of the issue. Are there plans to remedy this via this plugin? Is it even possible?

Also, I believe the inputstream.adaptive is part of Kodi, and not a regular type of plugin. Now that Krypton is frozen at 17.6 will there be any way to install a fix if provided without having to jump to Kodi 18 (which I'd really rather not do right yet)?

**Comment by meoz** [comment]
Same issue for me, all 1080p videos play only at 720p max.

**Comment by anxdpanic** [comment]
This is an issue with the YouTube add-on and not inputstream.adaptive. The dash url is not currently available for vods.

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
