### ISSUE TITLE
HLS: .ec3 file extension for audio doesn't work (plays ok in ffmpeg)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1085]
more info to come....

![image](https://user-images.githubusercontent.com/6225961/208818138-28fcd11f-d686-4fe3-b3c2-ba8efccc9f97.png)

**Comment by glennguy** [comment]
Hey Matt

Any idea what the container is for these ec3 files? Could you zip/attach one of them for us here?

**Comment by matthuisman** [comment]
Sure.ill try over next few days. They are the new channel 9 streams. IPTV
Au addon > channel 9.

**Comment by glennguy** [comment]
Thanks Matt, I've got a segment now. Looks to be ADTS. Allowing this in HLSTree.cpp hasn't fixed the problem though :( so will have to look deeper.

**Comment by tmm1** [comment]
I recently added support for this into my software.

It looks like ADTS parser needs to be taught about EAC3:   https://github.com/xbmc/inputstream.adaptive/blob/Nexus/src/ADTSReader.cpp#L89

EDIT: Or maybe a new parser makes sense. Basically ADTS wrapped AAC will start with 0xFF (see https://wiki.multimedia.cx/index.php/ADTS), but AC3/EAC3 will start with 0x0B77

**Comment by CastagnaIT** [comment]
similar problem not sure its same, attach here to allow investigations:
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8
```
