### ISSUE TITLE
Is there any way to configure what is sent in challenge payload?

### ISSUE THREAD

**Issue by mkorganashvili** [peak3d/inputstream.adaptive#1086]
Challenge looks very different from what is sent from browser. What I can find with naked eye, browser does not include this part:

```
◄rchitecture_name↕♠x86-64→▬
♀company_name↕♠Google→↨

model_name↕     ChromeCDM→↑
platform_name↕Windows→#
¶widevine_cdm_version↕♂4.10.2557.02
```

Does not seem to be different encodings, they both contain some parts that looks same.

**Comment by glennguy** [comment]
I believe it's in the protobuf format. We don't control what is sent in the license request.
IA asks widevinecdm to create a license challenge, it gives that to us then we send it to the license server.

Btw browser will send additional requests compared to Kodi. Most browsers are signed with a certificate from Widevine, and therefore qualify as a 'verified media path'. To check this, the browser sends a request to the license server for a certificate. This is the two byte request `\x08\x04`.

So the short answer is no.
