### ISSUE TITLE
Unsupported encryption method for unencrypted stream

### ISSUE THREAD

**Issue by jairoxyz** [peak3d/inputstream.adaptive#109]
Some unencrypted stream manifest have this type of entry: #EXT-X-KEY:METHOD=NONE and I believe it causes inputstream to fail with message "Unsupported encryption method:".
I assume this needs to be addressed somewhere here:
https://github.com/peak3d/inputstream.adaptive/blob/c35bf3ccf0b6f9cd87a8fcb3f6e489afe938b193/src/parser/HLSTree.cpp#L378

**Comment by peak3d** [comment]
Is there an sample stream around?

**Comment by peak3d** [comment]
Thanx for reporting!

https://github.com/peak3d/inputstream.adaptive/commit/9089703f939a2db177363cfbde11a505fc6ecf8f

**Comment by Gujal00** [comment]
Any chance this fix will be available for Krypton? Thanks
