### ISSUE TITLE
Duplicate subtitles after seek action in some add-ons

### ISSUE THREAD

**Issue by MauriceW67** [peak3d/inputstream.adaptive#1090]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the Disney+ add-on (but also Pluto TV according to reports on the Kodi forum), subtitles will start to be shown twice after performing a seek action in the video. The duplication does not happen immediately, but only after letting the video play for about 1-2 minutes after the seek action was performed.

The issue can be fixed temporarily by performing another backward seek action, but the fix will only last for a couple of minutes.

Note: I have discussed this with the author of the Disney+ add-on (@matthuisman ) and he asked me to report this issue in the InputStream:Adaptive GitHub.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No duplication of subtitles should occur.

## Actual Behavior

Subtitles start to duplicate after performing a seek action.

### To Reproduce
1. Start playing a video. I used an episode from Star Wars Andor in the Disney+ add-on
2. Let the video play for about a minute.
3. Perform a seek backwards action of 30 seconds by pressing the "Left" button twice.
4. Let the video play for about 1-2 minutes.
5. Duplicate subtitles will start to show.

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/aniromovec.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.postimg.cc/HLcjHYvR/Kodi-20221230-114634.png

Note: The screenshot does not show the video, but it does show the subtitles. Apparently this is a limitation of the Nvidia Shield's screenshot feature (?).

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.1.1 (Android TV 11)
 - Kodi version: 20.0-RC2
 - inputstream.adaptive version: 20.3.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Thanks for the bug report @MauriceW67 
Can I confirm that this is the release 20.3.1 and not any of the builds here from pull requests or commits since 20.3.1?

**Comment by MauriceW67** [comment]
@glennguy No, I did not install any post 20.3.1 builds.

**Comment by Sholander** [comment]
I can confirm this exact behavior on my FireStick 4K, Kodi 20 (beta1,2-RC1,2) with inputstream.adaptive 20.3.1 BUT ONLY with  Disney+ addon running some old series, like  LOST (2004-2010). On new contemporary material subtitles work normally, i.e. no duplicate lines...

**Comment by glennguy** [comment]
Thanks guys, I'm looking into at the moment

**Comment by MauriceW67** [comment]
@Sholander That's weird. For me it happens with new shows as well, like I mentioned with Star Wars Andor.

I also had the issue with the show The Old Man a few weeks ago (also on Disney+).

**Comment by GG-76** [comment]
It definitely happens on the new series as well. It happens to me on practically all of them, when the skip intro function is turned on, which moves the video forward a bit and skips the intro. Subsequently, the subtitles will always start to be displayed in duplicate.

**Comment by glennguy** [comment]
Hey guys, we're still working through one last subtitle sync issue but I think I have the duplicate issue solved. If you could test this build here that would be great! https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1082/4/artifacts

**Comment by GG-76** [comment]
Hi, I installed the version from the link, tried to play a video from Disney plus, fast forwarded, but unfortunately after a while the subtitles started to appear in duplicate again. In addition, after turning off the playback and starting again from the point where it ended, the subtitles will no longer appear at all. This behavior did not happen before.

**Comment by glennguy** [comment]
@Kravatak76 thanks heaps for testing and the feedback. It seems there's still much to be done! I'll try to get some more time for this next week.

**Comment by Sholander** [comment]
Just to inform you, I also tried your test version and run into one "peculiarity" using English subtitles on Lost.S04E06 episode, on my Firestick 4K with Kodi Nexus RC2:
After skipping forward, duplicate English subtitles started to appear. Usually only one skip backwards sorts this behavior for a couple of minutes when it starts again. Since I was testing I did a lot of skipping back/forward and suddenly I lost the subtitle track completely. Restarting the episode from resuming point or starting from beginning I could not get them any more; as if the subtitle track was somehow blacklisted for that single episode, since subs worked on all other episodes I tried.
Restarting Kodi several times did not help. The only thing that helped was to "revert" to official stable version (although both are same version number) and then I got back the subtitle track to finish of the episode.
I am now sorry that I restarted Kodi several times and lost relevant "Kodi.log.old" to maybe see what was going on...

**Comment by MauriceW67** [comment]
@glennguy Any luck yet on finding the root cause of this? :)

**Comment by glennguy** [comment]
Sorry I need to do some more testing. I did some tonight but haven't been able to reproduce it yet. I'll try to get to on the weekend.

**Comment by Sholander** [comment]
??? It's just very easy to reproduce it on my Firestick 4K; I just hit "Seek" 1 or 2 times and after a couple of minutes double (English) subtitles appear.

**Comment by glennguy** [comment]
Thanks @Sholander I've been patient enough to watch until it happens :)

In my example on D+, I'm at the start of the program (during segment 0 of subs, which is the first 4 minutes). At this point Kodi has received this segment only. After seek it sends segment 1 straight away, followed shortly after by segment 0 again. Once we near the 4 minute mark, segment 1 is sent again which causes the double-up. I didn't keep watching but I'm confident once we enter segment 2 the doubling would not occur.

Give me some time and I can fix.

**Comment by Sholander** [comment]
There is no need to rush, we can live with it as is :) 
It's interesting that I notice it only on Disney+, but not on HBO-Max addon...

**Comment by GG-76** [comment]
> There is no need to rush, we can live with it as is :) It's interesting that I notice it only on Disney+, but not on HBO-Max addon...

true, it is strange that it is not an addon problem, but the problem occurs only on one specific Disney+ addon, not others on the same version of Kodi, not even on those that use inputstream adaptive (HBO Max, Netflix) and moreover from the same creator SluGuy(HBO Max) this issue does not appear.

**Comment by glennguy** [comment]
It's to do with the format in which the subtitles are delivered. They come just as text files with no container. Audio/video are containerised and also have their own internal presentation timestamps for each sample of audio/video but here the subs don't even have a true timestamp of their own, only a time relative to the audio/video, which itself needs to then relate to the start of a chapter.... It's a crap format but we've just figured out a way that works with that in various scenarios, now they last piece is making sure we're not sending the next pending segment when seeking.

**Comment by GG-76** [comment]
> It's to do with the format in which the subtitles are delivered. They come just as text files with no container. Audio/video are containerised and also have their own internal presentation timestamps for each sample of audio/video but here the subs don't even have a true timestamp of their own, only a time relative to the audio/video, which itself needs to then relate to the start of a chapter.... It's a crap format but we've just figured out a way that works with that in various scenarios, now they last piece is making sure we're not sending the next pending segment when seeking.

I understand that Disney+ has a specific subtitle format. The question is whether the solution for this format will not affect the other addons that are working at the moment... But I am not a programmer, I don't see the problem (I only understand a little about developing an application :D), so I'm just looking forward to the problem being solved and I won't have to restart the video playback on Disney+ because of duplicate subtitles with every skip intro :D

**Comment by Sholander** [comment]
> It's to do with the format in which the subtitles are delivered. They come just as text files with no container. Audio/video are containerised and also have their own internal presentation timestamps for each sample of audio/video but here the subs don't even have a true timestamp of their own, only a time relative to the audio/video, which itself needs to then relate to the start of a chapter.... It's a crap format but we've just figured out a way that works with that in various scenarios, now they last piece is making sure we're not sending the next pending segment when seeking.

Don't know if of any relevance to this problem, but when a similar problem appeared with old HBO_Go addon, then developer of that addon made changes so that the whole subtitle track was downloaded and used for playing the stream. After the stream finished this subtitle track was automatically deleted. 
That way the problem would be out of your courtyard :)

**Comment by matthuisman** [comment]
i have had reports its happening on PBS Live add-on as well.

I think this is HLS only. That is why add-ons using DASH are not affected.

**Comment by matthuisman** [comment]
Spotted this pr on kodi repo
https://github.com/xbmc/xbmc/pull/22567

Sounds related but maybe there are two different issues here?

**Comment by glennguy** [comment]
Ok found the culprit. Now trying to tidy up all of these changes so they can be reviewed properly

**Comment by glennguy** [comment]
More test builds up at https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1082/5/artifacts

Note that this build is relying on changes in Kodi which haven't been submitted yet, and this will affect alignment for e.g shows that have a separate chapter for the splash screen like Disney+, where they'll come 3 seconds early.
But the duplicate issue should be resolved, along with a bunch of others.

**Comment by MauriceW67** [comment]
@glennguy I'm slightly confused.. I thought the "3 second early" issue was fixed a long time ago? At least I haven't had that issue anymore for a long time already.

**Comment by glennguy** [comment]
Yes it was fixed however the solution only helped in the disney+ case and not all. The fix in motion now resolves for other use cases but if you were to install the zip from my PR now, the 3 second issue would return *until/unless* you install an updated Kodi with the corresponding changes included as well.

**Comment by glennguy** [comment]
Having said that, just thinking now it might be fairly trivial to have our cake and eat it too. Will look at later tonight.

**Comment by MauriceW67** [comment]
@glennguy Do we need a Kodi build with updates for this like you said? And how could we test your change in IS:A ?

**Comment by glennguy** [comment]
I'm about to make a new release, and after that the change in Kodi will be merged and in the nightly builds shortly after.

**Comment by MauriceW67** [comment]
@glennguy Thanks for the new release! Do you happen to know which Kodi PR is required to make it all work?

**Comment by glennguy** [comment]
Sure - https://github.com/xbmc/xbmc/pull/22709 or https://github.com/xbmc/xbmc/pull/22621

Most things should work with the current v20 release though

**Comment by MauriceW67** [comment]
@glennguy Thanks. I noticed it's working with V20. But I'm also testing a custom v21 build from @fritsch (https://forum.kodi.tv/showthread.php?tid=371292) and in that one the subs are still 3 seconds early in the Disney+ addon, even with the new IS:A 20.3.3 release.

**Comment by CastagnaIT** [comment]
for v21 you need to apply also PR #1095 otherwise packets may have wrong data,
suggest you to wait until all PR's are merged on xbmc master branch and then wait for next future nightlies

**Comment by MauriceW67** [comment]
@glennguy I just tried the latest v21 master. That PR xbmc/xbmc#22621 you mentioned was merged 4 days ago.

But the #1095 PR was closed as outdated by @CastagnaIT.

And now when I watch a show with the Disney+ addon, I need to delay the subs by 6 seconds instead of the previous 3 seconds.

Am I missing something here?

**Comment by CastagnaIT** [comment]
for v21 you need to build/install ISA from Omega branch

**Comment by MauriceW67** [comment]
I just tested with IS:A v21.0.0 from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/4/artifacts

But it will not play video at all.

I guess I need to be more patient lol 😁

**Comment by CastagnaIT** [comment]
take in account that on Nexus there are deprecated isa properties that still works,
but on Omega has been removed or changed,
then each addon must apply relative fixes otherwise may not works correctly

see properties summary on Wiki integration page, where are marked the properties deprecations

**Comment by MauriceW67** [comment]
@CastagnaIT Thanks for explaining. I guess that means we'll need to wait for the addons to catch up. But since Omega is still in early alpha stages that also means being even more patient 😀 

Shame though, because the audio fixes in Omega are working pretty well and are preventing video micro stuttering and audio dropouts on the Nvidia Shield with firmware 9.x.

But I believe those audio fixes are being backported to v20.1, so that would work too I suppose.

**Comment by GG-76** [comment]
Hi, I have a strange thing going on right now. The subtitles are no longer duplicated, which is great, but when I stop playing the video and then resume from where I left off, the subtitles don't show at all. Does this happen to you too? Is there any way to fix this by installing a different version? I have Disney+ addon 0.13.5 and Inputstream Adaptive 20.3.3 installed.Thank you.
