### ISSUE TITLE
The Query params passed to the main manifest are stripped off when downloading the child manifest

### ISSUE THREAD

**Issue by ganeshbn** [peak3d/inputstream.adaptive#1093]
### Describe the bug
Consider HLS livestream main manifest -> https://ip:port/manif.m3u8
Here is the structure of the manifest file:
* manif.m3u8
  - manif_1.m3u8
      - transport_1_1.ts
      - transport_1_2.ts
  - manif_2.m3u8
      - transport_2_1.ts
      - transport_2_2.ts

I need to pass token1 into header and token2 as a query params to be able to download any(main or the child) manifest from cdns.

[inputstream.adaptive](https://github.com/xbmc/inputstream.adaptive) is stripping off the query params from the url when downloading the child manifest (Ex: manif_1.m3u8).
The CDN Server would send back 403 or 405 errors as the url is missing the token2 query param. 

## Expected Behavior
The main manifest (Ex:  https://ip:port/manif.m3u8?token2param=token2) gets downloaded
The child manifest (Ex:  https://ip:port/manif_1.m3u8?token2param=token2) gets downloaded

## Actual Behavior
The main manifest (Ex:  https://ip:port/manif.m3u8?token2param=token2) gets downloaded
The child manifest (Ex:  https://ip:port/manif_1.m3u8) do not download(405E) as query param(token2param=token2) is stripped off.

## Possible Fix
Fix at InputStream.Adaptive :
1. Do not strip the query params passed to the main manifest URL, while downloading the subsequent child manifest. I mean you could add back the removed query param after all the base url processing is done.
2. There might already be a way to do this in InputStream.Adaptive. I might have missed it while reading the documentaition, please do suggest if this is the case :).
3. Give a new map property which can be set by the calling code. Ex: We have "inputstream.adaptive.stream_headers" to pass the headers. Similarly there could be a map property "inputstream.adaptive.stream_query_params" which we could pass from client code to populate into the child manifest and ts files.

Option 2 could be the best fix. (As I didnot get the exact reason why the query params are being removed [here](https://github.com/xbmc/inputstream.adaptive/blob/6a02e74d0845ebdc5b913d9fa95c9d2ced279ce2/src/parser/HLSTree.cpp#L478), but not added back later. Probably its important for the library)

Fix at client code:
1. Proxy Server: We could run an internal proxy server to attach query param and then forward the request to CDN server. This will add lag to the calls and delay downloads (though in milli seconds, it could have snow ball effect while live streaming)

### To Reproduce
I cannot give the exact tokens and urls(in log files) with which the issues are happening, but for testing purpose you can use the following url which I copied form (https://demos.jwplayer.com/live-streaming/) 
Test URL: https://wowzaec2demo.streamlock.net/live/bigbuckbunny/playlist.m3u8
You can see that it has a child manifest chunklist_w(some number).m3u8

If I use https://wowzaec2demo.streamlock.net/live/bigbuckbunny/playlist.m3u8?testParam=test as the callback url into InputStream.Adaptive then you will see that while downloading the chunklist_w(some number).m3u8 file it would have stripped off the 
?testParam=test query param.

### Debuglog

The debuglog can be found here:
[kodi_issue_1093.log](https://github.com/xbmc/inputstream.adaptive/files/10357797/kodi_issue_1093.log)

### MPD/M3U8s/ISM
Test URL: https://wowzaec2demo.streamlock.net/live/bigbuckbunny/playlist.m3u8?testParam=test

### Your Environment
Used Operating system:

 - [X] Android
 - [X] iOS
 - [X] tvOS
 - [X] Linux
 - [X] OSX
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.x
 - inputstream.adaptive version: [19.0.7](https://github.com/xbmc/inputstream.adaptive/releases/tag/19.0.7-Matrix)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i tried make a search, and HLS by default should not propagate parameters of master to all childs
look like a custom implementation required for some services

i think that add a new ISA property should be the best way

**Comment by CastagnaIT** [comment]
in your case is required to add params also to media files (.ts)? or you need it only for each manifests?

**Comment by ganeshbn** [comment]
> in your case is required to add params also to media files (.ts)? or you need it only for each manifests?

**Short Answer**: At this instant, transport(.ts) files do not need the params to be passed, but this could be added in the future for more security purposes.

**My proposition**:
For now adding them only to the main and child manifest should suffice.

**Long Answer**:
1. Transport files are already DRM encrypted so they are secure unless the actor can download the DRM key with auth.
2. Adding params to the .ts files and verifying them at CDN edge will have snowball affect and slowdown continuous streaming.
3. It will require enabling CDN edge computing and increases cost of running. 

Due to the above reasons .ts files might not need the param to be passed in the immediate future. Having said that, when they can bare those tradeoffs it will be enabled in the far (3y+) future.

**Comment by ganeshbn** [comment]
> i tried make a search, and HLS by default should not propagate parameters of master to all childs look like a custom implementation required for some services
> 
> i think that add a new ISA property should be the best way

Yes I agree, it's not typical and not part of the original Apples HLS specs. HLS specs are open enough for people/companies to adapt their own methods over it .

**Comment by CastagnaIT** [comment]
ok i asked to have a clearer situation
i have seen on the net that some other services require specify params also on .ts media files
in this case they appears to use same url parameters for manifests and media (similar as you said) however should be rare cases

i think i will try implement separate ways to add url properties to manifests and media
so you can separately set it for manifests, or if needed also for media

this seems to require some rework to implement a bit better the things
can be done for Kodi v20+

**Comment by ganeshbn** [comment]
That would be super cool and future proof aswell.
Thank you for your support.
Yeah we can start with Kodi V20. Post that if time permits, we can check if it's possible to cherry pick the solution into V19.7+

**Comment by CastagnaIT** [comment]
this will be treated as new feature, 
since kodi 20 is released, the team is focusing on future v21,
this means that backports to Kodi 19 are allowed for bug fixes only

backporting new features depends on the cases and is at the discretion of the team
also because codebase of Kodi 19 is different, then cherry-picking generally does not work

**Comment by ganeshbn** [comment]
Oh. Got it. I didn't see that Kodi 20 already moved out of release candidate.👍

**Comment by CastagnaIT** [comment]
so i have done the changes
you can find test builds here (kodi 20):
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1102/3/artifacts

please if you can test and give a feedback
remember to add the new ISA properties to your addon or playlist file
as described in PR #1102

**Comment by ganeshbn** [comment]
I tested the windowsX64 and android7a (Those are the only devices I have. Since the code changes are common it should work on other platforms too) artifacts with the required plugin changes and **it works great as expected**.

Note to everyone: After this new feature release, whoever was using stream_headers as a property to pass header tokens to download m3u8 files now should use manifest_headers as a property to download manifest files. Additionally you can use manifest_params property to pass query params to download main or its child manifests.
The stream_headers/params property can now be used to pass headers and query params download media(.ts/.mp4) files only.

**Comment by ganeshbn** [comment]
Here is an **issue** that I am facing only on my **Android7a**. (In WindowsX64 working fine, I dont see any issue).
For 2-4 secs it works fine and then I see a lot of green patches. If I revert back to old plugin code and repository version 20.3.2 then I dont see this issue on Android7a.

I looked at the code I dont see any device specific code(as, in Windows its working fine) which could have caused this.
**Was there any Android7a bug introduced over the repository release 20.3.2 version for HLS playback?**

Here is what I have already checked in regards to appearance Green patches:
1. I have checked if there is data loss in downloading .ts files. -> nope
2. I have checked if there is intermittent download failure while getting .ts files. -> nope
3. I have checked if there is failure in getting the license keys. -> nope

**Comment by CastagnaIT** [comment]
i will try to double-check again my code if i forgot something
but there are no changes android specific, then if a problem occurs should happens on all platforms
from the official version there are no particular differences that might suggest something

on android device after updated with test build, please try force close kodi and start it again, just to be sure to have cleaned kodi memory

if you can provide a kodi log with debug enabled it would be more useful

**Comment by CastagnaIT** [comment]
i have double-check my code changes but found nothing that could explain you green image problem on android

this is a new build with last my cleanups:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1102/6/artifacts
as said on my previous comment after updated isa try restart kodi

here you can also have a test build of current Nexus branch without my changes:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/198/artifacts
