### ISSUE TITLE
Feature Request: If only single quality - dont bother asking

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1096]
if mode is set to ask for quality and only a single quality available, dont bother showing dialog

**Comment by KingstonNdwambi** [comment]
My tv guide epg only shows when I open Slyguy Dstv addon from there doesn't update.  How do I get it to update ?

**Comment by matthuisman** [comment]
why are you posting that question on this ticket?
Its totally unrelated.
please check where you are posting questions.

best to ask DSTV questions here: https://mybroadband.co.za/forum/threads/release-dstv-now-kodi-add-on.977513/
