### ISSUE TITLE
Kodi 20 crashes when license key headers has a trailing ampersand

### ISSUE THREAD

**Issue by dimkroon** [peak3d/inputstream.adaptive#1098]
### Describe the bug
Here is a clear and concise description of what the problem is:

When the headers section in inputstream.adaptive.license_key has a trailing ampersand, kodi 20 crashes when the stream is played.
For example:
`list_item.setProperty('inputstream.adaptive.license_key', 'https://my.stream|Pragma=no-cache&|R{SSM}|')`

A trailing '&' is of course an error, but got silently ignored in IA 19. 
inputstream.adaptive.stream_headers in IA 20.3.1 also ignores an error like this.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Either just ignore the 'missing' header, or log an error and fail gracefully.

## Actual Behavior

Kodi 20 crashes

### To Reproduce

1. Install the little test addon [here](https://dimkroon.net/tests/plugin.video.test_streams_t2.zip)
2. Play last item in the menu.

### Debuglog

The debuglog can be found here: [https://paste.kodi.tv/ojutecabew.kodi](https://paste.kodi.tv/ojutecabew.kodi)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Zorin 15.3
 - Kodi version: 20.0-RC2 (19.90.905)
 - inputstream.adaptive version: 20.3.1

The same issue is reportedly also present on win10, win11, IA 20.3.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
thanks for the test addon, fixed

you will find test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1099/1/artifacts

**Comment by dimkroon** [comment]
Many thanks, that's quick!
I can confirm the fix btw
