### ISSUE TITLE
Not ignoring unsupported codecs

### ISSUE THREAD

**Issue by Schtek** [peak3d/inputstream.adaptive#110]
When DASH support was fixed on the YouTube Kodi plugin, jdf76/plugin.video.youtube#230, it was found that the provided manifest file would not function correctly when sent to Inputstream Adaptive if it contained streams that could not be played. In that case it was Opus and VP9 that failed if included.

I can see that VP9 is not supported, as stated in #91, but I would expect that non supported codecs would be completely ignored if there were other, supported, codecs included in the manifest.

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/242828c2460c56ee392223c7d8ed10dd0f9b8a9e
