### ISSUE TITLE
Android 32bit - Issue playing some widevine content 

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1101]
attached is a good (h264) and bad (h265) zip of manifest, log and media files for two streams from a single service.

device is 32bit Android Nvidia Shield Tube (L1)

The h265 just shows black / distorted screen and audio is OK
h264 works fine.

I fixed this by enabling "try not to use secure decoder".

I wonder if these files give us a clue to how we can correctly play these without the above setting?

Same content on 64bit Android Nvidia Shield + other 64bit devices are fine.
Even Kodi 32bit on the 64bit devices is fine.

Only broken on 32bit kodi on 32bit device.
[op1_h265_broken.zip](https://github.com/xbmc/inputstream.adaptive/files/10465167/op1_h265_broken.zip)
[op1_x264_ok.zip](https://github.com/xbmc/inputstream.adaptive/files/10465169/op1_x264_ok.zip)

Also, when I play this same service but using their dash manifest, the 1080 H265 streams work,
But I suspect they could be different files.

**Comment by glennguy** [comment]
Hey Matt
A couple of things.
Could you check if it fails the same when setting IA to video only?
Could you also provide a logcat for when it's failing?

No errors in the Kodi log... normally when we're feeding Kodi ffmpeg with incorrectly decrypted data it will show a bunch of ffmpeg errors in the log... none here. Makes me wonder if this is some sort of memory thing, or even a device issue. Hard to say!

**Comment by matthuisman** [comment]
Turns out the non-cmaf doesn't play either on the users system. I have another user with Google tv 32bit on android 20 and a different addon (stan) isn't working as well.

I'll try get logs etc. 
But yeh, not a cmaf issue. But a widevine license issue

**Comment by liam8888999** [comment]
are there any updates on this. I am having trouble with kayo on my firestick but its playing fine on my laptop

**Comment by CastagnaIT** [comment]
@liam8888999 no because we need more feedbacks and logs to try investigate
if you are able please provide logs as mentioned in comment above https://github.com/xbmc/inputstream.adaptive/issues/1101#issuecomment-1398253610

**Comment by CastagnaIT** [comment]
the h265 is hvc1 that should be dolbyvision
its possible that the problem is on device codec decoders, kodi has selected
`2023-01-20 22:29:49.326 T:21096    info <general>: CDVDVideoCodecAndroidMediaCodec:: Open Android MediaCodec OMX.Nvidia.h265.decode.secure`
but maybe should use `OMX.Nvidia.DOVI.decode`

on this purpose on Kodi 21 has been made various improvements
It is worthwhile to test and see what happens on debug log

**Comment by CastagnaIT** [comment]
closed for inactivity
