### ISSUE TITLE
Sky Sports Now Issue

### ISSUE THREAD

**Issue by Sportsmaniacuk** [peak3d/inputstream.adaptive#1105]
Hello,
When I try and play any stream the sound starts but there is no picture. I have to try the back button to get the video stream but it’s unreliable.

Edit: currently having spinning logo

**Comment by CastagnaIT** [comment]
when you open a new issue you have to use and fullfill our template

**Comment by Sportsmaniacuk** [comment]
> when you open a new issue you have to use and fullfill our template

How do I do that?

**Comment by CastagnaIT** [comment]
press _New Issue_ button and choose _Problem report template_ its the only available
