### ISSUE TITLE
[Question] Encryption AES-128 CBC (cbcs mode) on Android devices

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1112]
I have sample material encrypted in AES-128 CBC (cbcs mode) 
```
#EXTINF:-1,Test DRM CBCS
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_key=https://proxy.uat.widevine.com/proxy?provider=widevine_test||R{SSM}|
https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd
```
On devices with Windows 10 there's no problems with playback, but on Android (I tested on ver. 7 and 9) decryption failed with information in log "device API does not support CBCS decryption". The question is : Is this problem with device (version of Android) or IS don't support this ancryption mode on Android?

**Comment by kszaq** [comment]
It's probably your device, it plays fine on my Android device with Kodi 20 and latest ISA. 

However, I needed to apply a small correction:
```
 
#EXTINF:-1,Test DRM CBCS
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_key=https://proxy.uat.widevine.com/proxy?provider=widevine_test
https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd
```

**Comment by CastagnaIT** [comment]
CBCS is supported only on Kodi >= v20, and usually you need android >= v7.1

**Comment by mtr81** [comment]
About K20 I know (tested only on this ver. Kodi). You wrote 'usually'... Do you know what the conditions are?

**Comment by CastagnaIT** [comment]
because not all android v7 may be compatible with cbcs, depends on firmware bundled with the devide, on android v9 for sure works

but you havent provide any detailed debug log, so we cannot says what problems there are with your device and if are solvable,
cbcs has been tested with differents android devices, from my part on devices with android v8 v9 v10 and playback has worked

**Comment by glennguy** [comment]
Minimum API is technically Android 24 (7.0) however it's buggy and doesn't actually work at least on devices that I tested. 25 (7.1) does.

relevant code in Kodi: https://github.com/xbmc/xbmc/blob/64f9286f791d5ddf5c3236b3c11224e8bc7e4350/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L977-L982
