### ISSUE TITLE
Could not open / parse mpd for UK Channel5 live stream

### ISSUE THREAD

**Issue by nictjir** [peak3d/inputstream.adaptive#1114]
### Describe the bug
Here is a clear and concise description of what the problem is:

Cannot decode/play Channel 5 UK live stream.
The main errors/warnings from the log include :-
warning <general>: AddOnLog: inputstream.adaptive: No periods in the manifest
ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd)

## Possible Fix

The configuration below plays a Channel 5 catchup/on demand video with no issue.

### To Reproduce

I am trying to play a live stream from Channel 5 UK. The stream info is extracted from this JSON derived from the dat and iv after calling
https://cassie.channel5.com/api/v2/live_media/my5desktopng/C6.json?timestamp=1675315148

JSON decoded from iv and data extracted from above

{'id': 'C6', 'assets': [{'renditions': [{'renditionid': 0, 'format': 'SD', 'bitrates': [360, 480, 800, 1200, 1500], 'url': 'https://akahlslive-5star.akamaized.net/out/v1/50215a44e37c44049f1a3edb503fcc25/index.m3u8'}], 'profile': 'hlsfpslive1', 'drm': 'fairplay', 'keyserver': 'https://cassie.channel5.com/api/v2/licences/fairplay/364/C6?expiry=1675401549&tag=34623666373033613363323632633066373730383466363866656161356262343035343265316637', 'offset': 0}, {'renditions': [{'renditionid': 0, 'format': 'SD', 'bitrates': [360, 480, 800, 1200, 1500], 'url': 'https://akadashlive-5star.akamaized.net/out/v1/c7150fa2d717466cae6740c9b75e0973/index.mpd'}], 'profile': 'dashwvslive1', 'drm': 'widevine', 'keyserver': 'https://cassie.channel5.com/api/v2/licences/widevine/365/C6?expiry=1675325949&tag=61326563356230623164396231346337373863656135666262343233626331343232633335663034', 'offset': 0}, {'renditions': [{'renditionid': 0, 'format': 'SD', 'bitrates': [360, 480, 800, 1200, 1500], 'url': 'https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd'}], 'profile': 'dashplslive1', 'drm': 'playready', 'keyserver': 'https://playreadydrm.channel5.com/v2/rightsmanager.asmx?x=N2U1MDQ0ZjMtZjU3ZS00NTZlLTk2YmMtNDY2MjQ3MWVjOGZjOzAyLzAyLzIwMjMgMDU6MjQ6MDk7bFozUVliZnRFS3hWNjRSa1VnTDA0R3NpVEFLaS9uZVZXRmhSSVN3OStRdz07R2VuZXJhbExpdmU%3D', 'offset': 0}]}

Call to Kodi 20 to play stream
   stream = ''
   license_url = 'https://cassie.channel5.com/api/v2/licences/widevine/365/C6?expiry=1675325949&tag=61326563356230623164396231346337373863656135666262343233626331343232633335663034'

    lic_headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0',
        'Referer': 'https://www.channel5.com/',
        'Content-Type': '',
    }

    # get server certiticate data and b64 it
    resp = urlquick.get('https://c5apps.channel5.com/wv/c5-wv-app-cert-20170524.bin')
    content = resp.content
    cert_data = (base64.b64encode(content)).decode('ascii')

    stream_headers = urlencode(lic_headers)
    license_url = '%s|%s|R{SSM}|' % (drmurl, stream_headers)

    item = Listitem()
    item.path = stream
    item.label = get_selected_item_label()
    item.art.update(get_selected_item_art())
    item.info.update(get_selected_item_info())
    item.property[INPUTSTREAM_PROP] = 'inputstream.adaptive'
    item.property['inputstream.adaptive.manifest_type'] = 'mpd'
    item.property[ 'inputstream.adaptive.license_type'] = 'com.widevine.alpha'
    item.property[ 'inputstream.adaptive.server_certificate'] = cert_data
    item.property['inputstream.adaptive.license_key'] = license_url
    return item

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The live stream should play

## Actual Behavior

Kodi complains about a playback error

### Debuglog

log entries include
2023-02-02 06:09:50.639 T:4488     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/channel5/get_live_url/?_pickle_=8004953c000000000000007d94288c075f7469746c655f948c0f3520537461722066726f6d204d7935948c08786d6c74765f6964944e8c076974656d5f6964948c02433694752e
2023-02-02 06:09:52.489 T:4587     info <general>: Creating InputStream
2023-02-02 06:09:52.641 T:4587     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 701x588, max allowed: 1024x768, Adjust refresh rate: 0
2023-02-02 06:09:52.642 T:4587    error <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
2023-02-02 06:09:56.597 T:4587  warning <general>: AddOnLog: inputstream.adaptive: No periods in the manifest
2023-02-02 06:09:56.599 T:4587    error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd)
2023-02-02 06:09:56.604 T:4587    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/channel5/get_live_url/?_pickle_=8004953c000000000000007d94288c075f7469746c655f948c0f3520537461722066726f6d204d7935948c08786d6c74765f6964944e8c076974656d5f6964948c02433694752e]

### MPD/M3U8s/ISM

The mpd is attached
[index.txt](https://github.com/xbmc/inputstream.adaptive/files/10565670/index.txt)
this is obtained from
https://akadashlive-5star.akamaized.net/out/v1/c7150fa2d717466cae6740c9b75e0973/index.mpd

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/63444876/216247825-4a0d4e95-3f8e-4732-91cb-96b7a1ad722b.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-20.0-Nexus-armeabi-v7a.apk
 - inputstream.adaptive version: 20.3.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Hi @nictjir thanks for the detailed report.

The only thing missing is a full debug log file. You need to turn on debug logging in the settings, reproduce the issue, and attache the entire hodi.log here (rename to .txt to be able to attach easily)

**Comment by nictjir** [comment]
Thankyou. Here is the full debug from kodi, all 2.5M
[kodilog.txt](https://github.com/xbmc/inputstream.adaptive/files/10568532/kodilog.txt)

**Comment by glennguy** [comment]
Thanks for the log.

I can't reproduce here.

I've downloaded your attached mpd, hosted locally and attempt playback. Using anything for licence URL - does not matter as I just need to see it parse. And it does:
```
2023-02-07 22:49:09.563 T:29824   debug <general>: AddOnLog: inputstream.adaptive: Download finished: http://192.168.1.4:81/ch5.mpd (downloaded 12401 byte, speed 174762638.48 byte/s)
2023-02-07 22:49:09.564 T:29824    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 2, Type: live)
```

The mpd downloaded in your log looks to be a different size - is it the same one?
```
2023-02-02 11:43:39.996 T:4306    debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd (downloaded 28449 byte, speed 27772.58 byte/s)
2023-02-02 11:43:40.065 T:4306  warning <general>: AddOnLog: inputstream.adaptive: No periods in the manifest
```

**Comment by nictjir** [comment]
Thankyou for testing.

Each time i download the manifest, the size changes (different pssh etc in the file)

nic@nics-mbp ~$ wget https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd--2023-02-07 14:33:29--  https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpdResolving akadashlive-5star.akamaized.net (akadashlive-5star.akamaized.net)... 84.17.50.68Connecting to akadashlive-5star.akamaized.net (akadashlive-5star.akamaized.net)|84.17.50.68|:443... connected.HTTP request sent, awaiting response... 200 OKLength: unspecified [application/dash+xml]Saving to: ‘index.mpd’
index.mpd               [ <=>                ]  27.78K  --.-KB/s    in 0s
2023-02-07 14:33:31 (113 MB/s) - ‘index.mpd’ saved [28449]
nic@nics-mbp ~$ wget https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd--2023-02-07 14:34:16--  https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpdResolving akadashlive-5star.akamaized.net (akadashlive-5star.akamaized.net)... 84.17.50.68Connecting to akadashlive-5star.akamaized.net (akadashlive-5star.akamaized.net)|84.17.50.68|:443... connected.HTTP request sent, awaiting response... 200 OKLength: unspecified [application/dash+xml]Saving to: ‘index.mpd.1’
index.mpd.1             [ <=>                ]  27.56K  --.-KB/s    in 0s
2023-02-07 14:34:17 (146 MB/s) - ‘index.mpd.1’ saved [28224]


What is odd though, is that the mpd is now being processed by inputstream adapative and the live streams are playing on Kodi 20 Android - maybe C5 had an issue making manifests ?

So this can be closed
