### ISSUE TITLE
Please compile latest vesion for ubuntu fossa

### ISSUE THREAD

**Issue by enigma131** [peak3d/inputstream.adaptive#1115]
I'm using Kodi nexus and have problems with plug-in catchup tv and more here : 

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1061
Can you please compile latests one for focal, it is not updated : 

https://launchpad.net/%7Eteam-xbmc/+archive/ubuntu/ppa/+index?batch=75&memo=750&start=750
should be version 20.3.2 and I have : 

apt policy kodi-inputstream-adaptive
kodi-inputstream-adaptive:
  Installé : 6:20.3.1-2~focal
  Candidat : 6:20.3.1-2~focal
 Table de version :
 *** 6:20.3.1-2~focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

If @wsnipex can compile it please for focal and over

**Comment by wsnipex** [comment]
this should be automatic, dunno why it wasn't built,  uploaded now

**Comment by enigma131** [comment]
After update Channels are Ok on Ubuntu Focal  + Nexus base , many thanks @wsnipex
