### ISSUE TITLE
Playready Error on Android - inputstream.adaptive: WV_DRM: Unable to initialize MediaDrm

### ISSUE THREAD

**Issue by nictjir** [peak3d/inputstream.adaptive#1116]
### Describe the bug
Here is a clear and concise description of what the problem is:

Trying to play a playready live stream on Kodi 20 android results in an error
error <general>: AddOnLog: inputstream.adaptive: WV_DRM: Unable to initialize MediaDrm

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The live stream should play

## Actual Behavior

An error is generated and no stream is played
error <general>: AddOnLog: inputstream.adaptive: WV_DRM: Unable to initialize MediaDrm

## Possible Fix

Nothing I can find

### To Reproduce

This is the configuration invoked to try and play the media

  lic_headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0',
    'Referer': 'https://www.channel5.com/',
    'Content-Type': '',
}

# get server certiticate data and b64 it
     resp = urlquick.get('https://c5apps.channel5.com/wv/c5-wv-app-cert-20170524.bin')
     content = resp.content
     cert_data = (base64.b64encode(content)).decode('ascii')

    stream_headers = urlencode(lic_headers)
    drmurl = 'https://playreadydrm.channel5.com/v2/rightsmanager.asmx?x=N2U1MDQ0ZjMtZjU3ZS00NTZlLTk2YmMtNDY2MjQ3MWVjOGZjOzAyLzAyLzIwMjMgMTQ6MDA6MjQ7V2d2RmxxV1R3OTZQSWovak1PTFBLOFV3NmtJUElGcTNPNEZ0Y0N5NHg5Yz07R2VuZXJhbExpdmU%3D'

    license_url = '%s|%s|R{SSM}|' % (drmurl, stream_headers)

    stream = 'https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd'
    
    item = Listitem()
    item.path = stream
    item.label = get_selected_item_label()
    item.art.update(get_selected_item_art())
    item.info.update(get_selected_item_info())
    item.property[INPUTSTREAM_PROP] = 'inputstream.adaptive'
    item.property['inputstream.adaptive.manifest_type'] = 'mpd'
    item.property[ 'inputstream.adaptive.license_type'] = 'com.microsoft.playready'
    item.property[ 'inputstream.adaptive.server_certificate'] = cert_data
    item.property['inputstream.adaptive.license_key'] = license_url

### Debuglog

The debuglog can be found here:
[kodilog.txt](https://github.com/xbmc/inputstream.adaptive/files/10569792/kodilog.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://akadashlive-5star.akamaized.net/out/v1/f9ff5ec1d68b40dcb6e72c0f85031382/index.mpd
[index.txt](https://github.com/xbmc/inputstream.adaptive/files/10569734/index.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/63444876/216346703-1a916843-91f0-4680-ba58-0831ac556208.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-20.0-Nexus-armeabi-v7a.apk
 - inputstream.adaptive version: 20.3.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
its a virtual machine? if so you should use a real android device

**Comment by glennguy** [comment]
@nictjir you should test on your Android VM if the offical app works for playback. I doubt it would.

**Comment by nictjir** [comment]
Thankyou both. Indeed on a physical android device, Kodi 20, the playready  stream plays perfectly.
Thankyou!
