### ISSUE TITLE
Process MPD from local file 

### ISSUE THREAD

**Issue by nictjir** [peak3d/inputstream.adaptive#1118]
### Describe the bug
Here is a clear and concise description of what the problem is:

A feature request rather than a bug. I  would like to pre process the MPD before passing it inputstream adaptive. The reason for this is to try and remove some renditions that have properties/elements that might not compatible with inputstream adpative

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Read a MPD from a local file instead of a remote URL

## Actual Behavior

Cannot find an option to allow this

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[index.txt](https://github.com/xbmc/inputstream.adaptive/files/10577142/index.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-20.0-Nexus-armeabi-v7a.apk
 - inputstream.adaptive version: 20.3.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
to modify a manifest you have to implement a proxy in your addon where
ISA -> request manifest to -> Addon -> request to -> service
service -> response to -> Addon -> edit and response to -> ISA

something like explained in wiki:
https://github.com/xbmc/inputstream.adaptive/wiki/How-to-provide-custom-manifest-and-license

**Comment by nictjir** [comment]
Thankyou for the prompt reply and explantion
