### ISSUE TITLE
French live Tv

### ISSUE THREAD

**Issue by RasPsykk** [peak3d/inputstream.adaptive#112]
Hello,

thanks for your plugin, it's cool for DRM. I'm working on this website :

https://www.mycanal.fr/live/

there is three free channels and I could see something like :

https://hss-m006-live-aka-canalplus.akamaized.net/live/disk/cnews-clair-hd/hd-clair.isml/Manifest

For the key, I think it's something like that :
certificates
fairplay:
"https://secure-webtv-static.canal-plus.com/bourbon/cert/fps-mycanal-1-20161208.der"
widevine:
"https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin"

Someone can help me with Kodi 18, just to be able to watch the channels on my tv?

Regards

**Comment by RasPsykk** [comment]
Hi,

I run the free live Tv but now I need to login to try if the manifest's working, so if you want to try with me, you can join me here : https://discord.gg/qmH2xZX

Thanks

**Comment by peak3d** [comment]
Hi, the linked manifest is not content protected, so you can play it without having to care about fairplay / widevine.

For your addon you have to fill only the 2 listItem properties: 

inputstreamaddon=inputstream.adaptive
inputstream.adaptive.manifest_type=ism

and provide the Link to the manifest in listItem path

**Comment by RasPsykk** [comment]
I see that's closed, thanks for yout answer. I had a lot of work and I'm back to work on it.

I tried https://bitmovin.com/demos/drm but I can't load streams, peak3d can you try to explain to me how can I have the free channels first. I can give you the links in private.

And after why not loggin the user to see the scrambled channels he pays for.

Thanks again.
