### ISSUE TITLE
Release more often?

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1127]
Have you guys discussed the possibility of doing more rapid releases?

eg. after every PR?

be a lot easier to track down bugs if X new version caused a regression and there was only one PR as part of that?

smaller changes more often :)

**Comment by CastagnaIT** [comment]
every PR? 😆
filling the repository with release points is certainly not a good idea and i am sure that do not like to kodi team
sometimes we have very few changes that could be on hold without other new PR merged for a long time,
so maybe in this case we can think to plan a mini-release

but i think usually is better wait depends on the type of changes introduced
for example recent regressions that i made that has been fixed before release thanks to users that test nightlies
if it had been released immediately it would have broken many addons

but if you refer to the recent seek+subtitles problem that took many time, this also affected kodi core
i also had to wait for confirmation also from kodi core
it was not appropriate to make a release with partial / not complete solution

**Comment by matthuisman** [comment]
Fair enough :) your right. It would cause more traffic to Kodi servers
