### ISSUE TITLE
Fragmented webvtt subtitles out of sync in dash-mpd on Kodi 20 but work fine on Kodi 19

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1138]
### Describe the bug
Here is a clear and concise description of what the problem is:

The subtitles from live channels on Movistar+ are about 7 seconds ahead of time when using Kodi 20, but they are displayed correctly when using Kodi 19.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The subtitles should appear synchronized.

## Actual Behavior

The subtitles are out of sync.

### To Reproduce

It's difficult to provide a sample video where you can reproduce it since these channels require a subscription.
I attach several of the subtitle fragments, I hope this would be enough to figure out the problem.

[fragments.zip](https://github.com/xbmc/inputstream.adaptive/files/10737507/fragments.zip)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/poyagiyeco.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://hollywood-dash-movistarplus.emisiondof6.com/dash/hollywood.isml/manifest.mpd
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10740303/manifest.mpd.txt)

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: tested on Windows 7 and Fire TV Stick.
 - Kodi version: 20.0
 - inputstream.adaptive version: 20.3.3

**Comment by CastagnaIT** [comment]
is required an account?
maybe you can provide it in a strm?

**Comment by glennguy** [comment]
~~@Paco8 could you attach a copy of the mpd file linked above? I get a 403 response from where I am~~ nvm it's there now :)

**Comment by CastagnaIT** [comment]
its possible that this problem come from kodi
due to the offset not set for iso type

if you can test stream over this kodi omega test build:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230215-b52a54c4--x64.exe

and install this InputStreamAdaptive build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/3/artifacts

**Comment by Paco8** [comment]
Yes, the problem is fixed in that build. Thank you.

**Comment by CastagnaIT** [comment]
@Paco8 please i need also another feedback, please test on Kodi 20 by using these nightlies:
kodi build: http://mirrors.kodi.tv/nightlies/windows/win64/Nexus/KodiSetup-20230214-3a7a8b17-Nexus-x64.exe
isa: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/215/artifacts

and let me know whant happens

**Comment by Paco8** [comment]
It works as well.

**Comment by CastagnaIT** [comment]
I made you test the pure kodi 20 nightly
then there are no bugs, you will have to wait next kodi 20 release
