### ISSUE TITLE
inputstream.adaptive returned bad status "Permanent failure" during instance creation

### ISSUE THREAD

**Issue by mkuthan** [peak3d/inputstream.adaptive#1146]
After upgrading Kodi from 19.5 to 20.0, Kodi isn't able to load inputstream.adaptive plugin.

During Kodi startup the plugin is recognized:

```
CAddonMgr::FindAddons: inputstream.adaptive v20.3.3 installed
```

But when video player opens video the plugin can't be loaded, it happens for all video players using inputstream.adaptive.

```
VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=mhK0i-lkRHo
Creating InputStream
ADDON: Could not locate inputstream.adaptive.so.20.3.3
IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=mhK0i-lkRHo]
```

Kodi is compiled from sources (current Nexus branch) on Raspberry PI (CPU: armv7l, ARCH: arm) with the following configuration:

```
cmake ../kodi-nexus -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCORE_PLATFORM_NAME=gbm \
    -DAPP_RENDER_SYSTEM=gles \
    -DENABLE_VAAPI=OFF \
    -DENABLE_VDPAU=OFF \
    -DENABLE_OPENGL=OFF \
    -DENABLE_PULSEAUDIO=OFF \
    -DENABLE_INTERNAL_FMT=ON \
    -DENABLE_INTERNAL_SPDLOG=ON \
    -DCMAKE_CXX_STANDARD_LIBRARIES="-latomic" \
```

The plugin is compiled as binary addons from Kodi sources:

```
sudo make -j$(getconf _NPROCESSORS_ONLN) \
    -C tools/depends/target/binary-addons PREFIX=/usr/local/kodi \
    ADDONS="inputstream.adaptive"
``` 

I also compiled and installed inputstream.adaptive as describied here: https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build. No luck anyway, the errors are exactly the same.

It looks that all dynamically linked libraries are resolved for compiled library:

```
$ ldd inputstream.adaptive.so.20.3.3
linux-vdso.so.1 (0xbeb43000)
/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb6cdf000)
libstdc++.so.6 => /lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6b45000)
libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6ad6000)
libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6aa9000)
libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6955000)
/lib/ld-linux-armhf.so.3 (0xb6edd000)
```

I don't know why Kodi isn't able to load the plugin, error message doesn't tell what is a reason. Enabling debug for add-ons component (code 16777216) didn't help as well.

I am looking for tips to help me solve the problem.

**Comment by CastagnaIT** [comment]
usually `Permanent failure` happens when you update ISA addon without rebooting Kodi, in this case is a know problem and atm cannot be solved, you must reboot kodi after each ISA update

if `Permanent failure` happens at first ISA installation then i think you have builded ISA in a wrong way
our RPI wiki build instructions may be old, have been provided by other users, and has been not updated by years
from my side i could not help you

**Comment by glennguy** [comment]
Is it definitely loading from the correct path (and not trying the previous version)? No idea from your log snippet.

**Comment by mkuthan** [comment]
Thanks for quick respones :)

1. This happens every time, system/Kodi restarts didn't help. 
2. Everything is installed under standard location /usr/local, the plugin libraries are readable by Kodi process. Symlinks look fine, I see all plugin metadata, I can configure the plugin from Kodi interface.
3. When I installed version compiled for version 19.5 I got explicit error message about incompatible plugin version.
4. "inputstram.adaptive" is the only binary extension installed as in-tree binary addons.
5. There is no changes to the plugin configuration.
6. I didn't change compilation procedure between 19.5 and 20. The only visible difference is that for 19.5 Kodi uses distribution ffmpeg from Bullseye, Kodi 20 installs ffmpeg itself. I'm going to compile 19.5 again to verify that it's not a system configuration issue.

Do you know any method to debug Kodi fragment responsible for loading extensions?

**Comment by CastagnaIT** [comment]
if you tried use ISA binary for v19 to v20 (or reversed order) you cant, because they have different interface versions

i think the binary should be loaded from kodi core by this code:
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/binary-addons/AddonDll.cpp#L165-L170

**Comment by CastagnaIT** [comment]
closed as we have no other hints for your building way
