### ISSUE TITLE
non-root relative urls not handeled correctly

### ISSUE THREAD

**Issue by L2501** [peak3d/inputstream.adaptive#1148]
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/xbmc/inputstream.adaptive/blob/ba96563de6bce08ff97ec82f04b57dbc5328a7f6/src/utils/UrlUtils.cpp#L86-L89

only checks for relative urls with root path, but relative urls can be without root "foo/aes.key"

#
 - Operating system version/name:
 - Kodi version: 21
 - inputstream.adaptive version: git

**Comment by glennguy** [comment]
@L2501 could you elaborate please? An example of a url that is not handled correctly when attempting playback?

**Comment by L2501** [comment]
when HLS key url is relative without root like "foo/aes.key" the check in 
https://github.com/xbmc/inputstream.adaptive/blob/ba96563de6bce08ff97ec82f04b57dbc5328a7f6/src/parser/HLSTree.cpp#L125
will be false, resulting in invalid request to "foo/aes.key" instead on a joined url

**Comment by glennguy** [comment]
Fixed already in #1134 #1137

**Comment by glennguy** [comment]
My bad, I've been looking at the wrong history

**Comment by CastagnaIT** [comment]
yes seem there are also other relative things to be check
with the old refactor i tried preserve old way
but i forgot to check the reason why has been made in this way
basically IsUrlRelative ==/== IsUrlAbsolute should produce always reversed value
just for readability there are both methods

**Comment by CastagnaIT** [comment]
one example to be check is
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/parser/DASHTree.cpp#L1361-L1365

**Comment by CastagnaIT** [comment]
found that we are not following correctly RFC 3986 for url operations
i will try fix soon

**Comment by CastagnaIT** [comment]
@L2501 please install this test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1151/1/artifacts
an let me know

**Comment by L2501** [comment]
good for me

**Comment by kyl416** [comment]
> Fixed already in #1134 #1137

The backport for Nexus #1137 was merged into the Omega branch instead of the Nexus branch.
