### ISSUE TITLE
Kodi Kayo addon [Aus] time issue for live sport

### ISSUE THREAD

**Issue by bosustow** [peak3d/inputstream.adaptive#1152]
With the recent Kayo update for Kodi, when selecting a live sport you normally get the time of eg 0:00/1:23:53 meaning you are at start of live and it is 1:23 into live. As the game progresses say 30 mins and it is still live you get 30:00:00/1:53:53 so both clocks move.

Now what is happening is you see 30:00:00/1:23:53 so the end clock does not move even though the live sport is still on.

Then when you get to after this time you see for eg 1:30:00/1:23:53 instead of seeing 1:30:00/3:13:53.

Now when you skip say 10sec when the first clock is greater then the 2nd clock it goes back to the 1:23:53 time even when trying to skip forward. If you use the up button which is a 10min skip function forward this one works.

Was mentioned to me that it is potentially an inputstream.adaptive issue not Matt's excellent Kayo addon for Kodi.

Just wondering if anyone else is seeing this issue and can be rectified?

**Comment by matthuisman** [comment]
@glennguy suspect this is related to the shift from HLS to Dash

**Comment by glennguy** [comment]
> suspect this is related too the shift from HLS to Dash

Good point. 

@bosustow is this when playing from EPG/PVR, or from within the add-on? Does it behave the same way in the add-on?

**Comment by bosustow** [comment]
From the add on I just select live sport that is in progress
