### ISSUE TITLE
Get KEY and KID of Widevine stream

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [peak3d/inputstream.adaptive#1153]
Is it possible to get the KEY and KID of a Widevine-encrypted stream? There is [a plugin](https://github.com/cralin/plugin.video.TVOnline.ro) for playing IPTV that sends the DASH stream url and the drm license url to inputstream.adaptive. I want to record a TV show played by this plugin and the only way I could do that is by getting the key and the kid and decrypting the video with Bento4.

**Comment by glennguy** [comment]
No sorry, not with inputstream.adaptive. The CDM doesn't tell us the key, which is kind of the point of the system. It's a black box - we send content into it with a key ID, it does the decrypting and gives the data back to us for Kodi. In the case of L1 streams, CDM does decrypting and decoding, Kodi only get the decoded frame at the end.

**Comment by Andrei-Iosifescu123** [comment]
> No sorry, not with inputstream.adaptive. The CDM doesn't tell us the key, which is kind of the point of the system. It's a black box - we send content into it with a key ID, it does the decrypting and gives the data back to us for Kodi. In the case of L1 streams, CDM does decrypting and decoding, Kodi only get the decoded frame at the end.

So from my understanding, inputstream.adaptive just gives `widevinecdm.dll` the drm license url and the encrypted stream, then it gets the decrypted video and the magic is done by `widevinecdm.dll`? 
In this case, can the output (decoded frames) be piped to ffmpeg?

**Comment by Andrei-Iosifescu123** [comment]
> No sorry, not with inputstream.adaptive. The CDM doesn't tell us the key, which is kind of the point of the system. It's a black box - we send content into it with a key ID, it does the decrypting and gives the data back to us for Kodi. In the case of L1 streams, CDM does decrypting and decoding, Kodi only get the decoded frame at the end.

So from my understanding, inputstream.adaptive just gives widevinecdm.dll the drm license url and the encrypted stream, then it gets the decrypted video and the magic is done by widevinecdm.dll?
In this case, can the output (decoded frames) be piped to ffmpeg?

**Comment by CastagnaIT** [comment]
kodi does not allow the send decrypted stream outside would be illegal
usually stream services that allow download store encrypted data to disk
this is currently not supported and there is no plan to implement it

**Comment by Andrei-Iosifescu123** [comment]
> kodi does not allow the send decrypted stream outside would be illegal usually stream services that allow download store encrypted data to disk this is currently not supported and there is no plan to implement it

But there are plugins for recording, and I doubt it is illegal in my country.

**Comment by glennguy** [comment]
Yes - they are PVR add-ons, which can instruct a PVR backend to do the recording. This is not a PVR add-on so it can't.
I should also clarify - with L1 decoding the decoded frames are sent via a secure pathway. Android does the decoding and sends the data directly to the rendering surface - it doesn't pass through Kodi's hands.
