### ISSUE TITLE
Kodi 20 license_data regression (android 32bit only?)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1155]
Kodi 19.5 vs 20.0 Android 32bit and this content does not play
Windows 20 has no issues and have reports Android 20 64bit also no issues

Logs from 19 and 20 showing OK and not OK
[19.0.7.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10793029/19.0.7.log.txt)
[20.3.3.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10793031/20.3.3.log.txt)

note: - no cenc contentprotection in manifest
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10793005/manifest.mpd.txt)

i use the license_data property to set the below cenc data which is generated from the key their api gives:
A105F9D3-787A-49F9-994D-EDA9BFD11861
`AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEKEF+dN4ekn5mU3tqb/RGGE=`

It doesnt even get to making the license request on kodi 20
Here is the logcat snippet showing WVCdm error
```
02-21 22:58:15.978  3207  3257 E WVCdm   : [initialization_data.cpp(121):SelectWidevinePssh] Unable to parse concatenated PSSH boxes
02-21 22:58:15.978  3207  3257 E WVCdm   : [initialization_data.cpp(79):InitializationData] Unable to select a supported Widevine PSSH from the init data
02-21 22:58:15.978  3207  3257 I WVCdm   : [cdm_engine.cpp(237):GenerateKeyRequest] Generating key request: session_id = sid203
02-21 22:58:15.978  3207  3257 W WVCdm   : [cdm_session.cpp(532):GenerateKeyRequestInternal] Init data absent
02-21 22:58:15.978  3207  3257 E WVCdm   : [initialization_data.cpp(121):SelectWidevinePssh] Unable to parse concatenated PSSH boxes
02-21 22:58:15.978  3207  3257 E WVCdm   : [initialization_data.cpp(79):InitializationData] Unable to select a supported Widevine PSSH from the init data
02-21 22:58:15.978  3207  3257 I WVCdm   : [cdm_engine.cpp(237):GenerateKeyRequest] Generating key request: session_id = sid203
02-21 22:58:15.978  3207  3257 W WVCdm   : [cdm_session.cpp(532):GenerateKeyRequestInternal] Init data absent
```

I have found a workaround, if I proxy and edit the manifest and add the below to it
```
<ContentProtection xmlns:cenc="urn:mpeg:cenc:2013" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="A105F9D3-787A-49F9-994D-EDA9BFD11861"/>
<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
   <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEKEF+dN4ekn5mU3tqb/RGGE=</cenc:pssh>
</ContentProtection>
```

then it works fine on 19.5 and 20.0 so this is my workaround for now :)

This is the same data that im using with license_data so maybe its an IA regression parsing that?
Or, a default_kid issue?
Not sure

@glennguy FYI

**Comment by scottydulton** [comment]
@matthuisman im pretty sure Nvidia shields are 64 bit? from the logs that is a 64 bit processor with 32 bit kodi installed

info <general>: Host CPU: ARMv8 Processor rev 1 (v8l), 4 cores available

I have no trouble playin your addon Stan on my fire tv with both 19.5 or 20

**Comment by matthuisman** [comment]
This is a tube shield which is 32bit

**Comment by CastagnaIT** [comment]
i suspect the problem is that we set wrong size to data
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/Session.cpp#L566

i think should be changed as
`init_data.SetData(decLicDataUInt, decLicenseData.size());`

but also the condition above (`if (uuid)`) is strange
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/Session.cpp#L560-L562

but is strange also on Matrix branch:
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/main.cpp#L2509-L2511

memmove operation on same pointer!?
i tryed replicate on a debugger and that operation seem to corrupt always the memory
i do not understand what logic it should have

**Comment by DownRabbitHoles** [comment]
Looks like its buggy version of something like this:-

std::string kidDefault = "0123456789ABCDEF";
std::string decLicenseData="I am missing a 16 byte {KID} right here but using 5 bytes so need to expand by 11";
std::string kidPlaceHolder = "{KID}";

int pos = decLicenseData.find(kidPlaceHolder);
          
if (pos>=0)
  {
  decLicenseData.replace(pos,kidPlaceHolder.size(),kidDefault);
  }

**Comment by CastagnaIT** [comment]
thanks now i understand yes it is probably just a placeholder replacement well messed up

also was not documented in wiki, now added

**Comment by CastagnaIT** [comment]
i tried apply fixes, someone can test and let a feedback?
test builds (Kodi 21): https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1158/2/artifacts (link updated)
