### ISSUE TITLE
Problem with playback MPD manifest after ISA update to ver. 20.3.4

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1168]
Here is a MPD manifest: [manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/10827363/manifest.txt)
manifest url: https://r.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/vodido.livx
ISA try to load data from this url: https://n-22-3.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/?type=video&ft=0&id=0&bitrate=4800000
instead of https://n-22-3.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/vodido.livx/?type=video&ft=0&id=0&bitrate=4800000.
Back to ver. 20.3.3. resolve problem.
Tested on Kodi 20 (Windows 10)
ISA 20,3.4
```
2023-02-24 18:39:29.436 T:7700    error <general>: AddOnLog: inputstream.adaptive: Download failed with error 404: https://n-22-3.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/?type=video&ft=0&id=0&bitrate=4800000
```
ISA 20.3.3
```
2023-02-24 18:40:57.529 T:3800    debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://n-22-3.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/vodido.livx/?type=video&ft=0&id=0&bitrate=4800000 (downloaded 1434 byte, speed 13277.00 byte/s)
```

**Comment by DownRabbitHoles** [comment]
My guess is if you add a / to end of the baseURL in manifest it would work fine.

I think a fix would be adding URL::EnsureEndingBackslash(dash->strXMLText_); about
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/parser/DASHTree.cpp?plain=1#L1550
or the URL::Join function will do badly later.  But baseURL can be a file so don't know if that causes problems.

I would of thought this was best/normal combined result
https://n-22-3.dcs.redcdn.pl/livedash/o2/vowos/vodido/live/vodido.livx?type=video&ft=0&id=0&bitrate=4800000

So instead I would improve URL:Join by not removing base content after the last slash when only ?args are being added (eg /leave?replace) , but I don't know enough to say if that causes legacy problems.

    if(relativeUrl.front() == '?')
        {
        size_t argsPos = baseUrl.find('?');
        if (argsPos != std::string::npos)
            baseUrl.erase(argsPos);
        }
    else
        {// normal baseUrl changing    
        }

**Comment by CastagnaIT** [comment]
@DownRabbitHoles thanks for the hint, baseurl outside periods cannot be a file only a url that must end with backslash
in this case the provider provides a malformed url so we fix as done on other baseurl cases

`URL:Join` must never changed because its follow RFC3986 as well also the DASH specs use
if a bug is found on that method, it will be investigated for a fix,
but many test cases have already been added to try avoid these problems:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/test/TestUtils.cpp#L36-L138

**Comment by CastagnaIT** [comment]
@mtr81 if you can give a try on Kodi 21 with this ISA test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1171/1/artifacts

or if you prefeer Kodi 20:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1172/1/artifacts

**Comment by mtr81** [comment]
I confirm, on K20 it works fine.
