### ISSUE TITLE
Unhandled video formats by Kodi addon interface is cause of faulty images

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#1174]
### Describe the bug

Video formats not implemented by the Kodi interface cause faulty images on the screen, this is the results when we use DRM decoder
the problem has been hidden because we have always used the same basic video formats for years

im talking about these:
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/video_codec.h#L48-L63
from this formats list is missing all the new video formats used by the more advanced video codecs as VP9 and AV1,
and probabily can cause problems also with some HEVC

over the time i tried more times to understand what was the root of cause because DRM videos was displayed with wrong images,
in the past i always tested with N€tfix videos as AV1 or VP9 Profile 2
because i havent found another DRM test stream with that codecs
with the following result:
![immagine](https://user-images.githubusercontent.com/3257156/221596273-3b7ac8c7-0ee8-4d45-bdd9-6a106efe6c88.png)
and for VP9 Profile 2 see #525, same problem

thanks to the new rebases i noticed this new log error
`AddOnLog: inputstream.adaptive: media::ToSSDVideoFormat: Unknown video format 17`
i tried investigate again and i have found the problem

the error is because currently we are trying to pass to Kodi a video format that is missing to the InputStream interface
in this case `YUV420P10` but the list is more long:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/wvdecrypter/cdm/media/cdm/api/content_decryption_module.h#L273-L291
and currently InputStream interface support only `Yv12` and `I420`

but the problem is yes around here, but the root come from another point, so where we callback Kodi to get the framebuffer:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/KodiHost.cpp#L110-L111
this do a callback to kodi method here:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L351-L353
as you can see on link above, the method has hardcoded the video format to `AV_PIX_FMT_YUV420P`

now if i replacing the video format with the correct format required for my DRM stream, so `AV_PIX_FMT_YUV420P10`
the image is rendered correctly on screen, as follow:
![immagine](https://user-images.githubusercontent.com/3257156/221604118-0cbb71e4-64d7-434c-831e-2f6a84670892.png)

yeah 🎉 finally we can watch DRM AV1 / VP9 Profile 2 streams!

## Possible Fix

For sure is needed add to Kodi input stream interface all missing video formats,
so include all formats supported by the Widevine DRM

how achieve a good solution, atm i dont know is needed investigate better

maybe is possible integrate a video format change on the fly
in the `CAddonVideoCodec::GetPicture`
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L226-L272
but im not sure

for now i found the cause and documented here

### To Reproduce

1. install n€tflix addon
2. on addon expert settings enable AV1 and disable all other codecs
3. configure ISA to ask video quality, in order to make sure to play an AV1 stream
4. play a video recently added to the catalogue (the old movies/tvshow can not have AV1)

### Debuglog

The debuglog can be found here:
[kodi_AV1.log](https://github.com/xbmc/inputstream.adaptive/files/10840994/kodi_AV1.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21 nightly
 - inputstream.adaptive version: master branch Omega

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by camokarzi** [comment]
I see the same issue on Binge when I play the latest "Last of Us" episode the system is calling for a later version of Widevine. All previous episodes work fine.
