### ISSUE TITLE
Unable to load widevine shared library

### ISSUE THREAD

**Issue by bded** [peak3d/inputstream.adaptive#118]
II can"ŧ play HBOgo. If I try to open any file in HBO go, I get this log.

20:36:04.627 T:140697994770176  NOTICE: Creating InputStream
20:36:04.627 T:140697994770176   DEBUG: ADDON: Dll Initializing - InputStream Adaptive
20:36:04.627 T:140698003162880   DEBUG: Thread BackgroundLoader start, auto delete: false
20:36:04.627 T:140697994770176   DEBUG: SECTION:LoadDLL(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.1.13)
20:36:04.627 T:140697994770176   DEBUG: Loading: /usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.1.13
20:36:04.633 T:140699869964032   DEBUG: Loading settings for https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest
20:36:04.634 T:140698717058816   DEBUG: CGUIInfoManager::SetCurrentMovie(https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest)
20:36:04.636 T:140699912722176   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
20:36:04.636 T:140699912722176   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
20:36:04.641 T:140699912722176   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
20:36:04.641 T:140699912722176   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
20:36:04.654 T:140697994770176    INFO: AddOnLog: InputStream Adaptive: SetVideoResolution (1920 x 1200)
20:36:04.654 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Open()
20:36:04.654 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_data: [not shown]
20:36:04.654 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_key: [not shown]
20:36:04.654 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_type: com.widevine.alpha
20:36:04.654 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_type: ism
20:36:04.664 T:140699979835520   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
20:36:04.676 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Initial bandwidth: 0
20:36:04.677 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:04.677 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:04.677 T:140698003162880   DEBUG: Thread BackgroundLoader 140698003162880 terminating
20:36:04.701 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:04.701 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTION selected: 2
20:36:04.701 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:04.701 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:04.702 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTIONSECURE selected: 2
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:04.702 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: STREAMSELECTION selected: 0
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:04.702 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:04.703 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:04.703 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /usr/lib/kodi/addons/inputstream.adaptive/
20:36:04.724 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /usr/lib/kodi/addons/inputstream.adaptive/libssd_wv.so
20:36:04.724 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
20:36:04.725 T:140697994770176   DEBUG: CurlFile::Open(0x7ff6bc06b9f0) https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest
20:36:05.047 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest
20:36:05.970 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Download https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest finished
20:36:05.971 T:140697994770176    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 6 Download speed: 0.0000 Bytes/s
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:36:05.972 T:140697994770176   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
20:36:05.972 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
20:36:06.000 T:140697994770176   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
20:36:06.000 T:140697994770176   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
20:36:06.000 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
20:36:06.001 T:140697994770176   ERROR: CVideoPlayer::OpenInputStream - error opening [https://edgecastcdnsecure.hbogo.eu/415e51f6-4c62-30e0-d23a-c66c2d896333_hbo/COMP/19670489_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_2600000.ism/Manifest]
20:36:06.001 T:140697994770176  NOTICE: CVideoPlayer::OnExit()
20:36:06.001 T:140697994770176   DEBUG: AddOnLog: InputStream Adaptive: Close()

I don"t get it .  The widevinecdm.so is from the latest stable google-crhome .Thanks.

**Comment by lullius** [comment]
I think libwidevine got updated recently. It stopped working some days ago for me too with the exact same error (AddOnLog: InputStream Adaptive: Unable to load widevine shared library).

I'm running Arch and got it from the AUR:
https://aur.archlinux.org/packages/chromium-widevine/

I took a look at the recent changes to the PKGBUILD and saw that it was updated to get the latest version, but looking at the change history I found this link:
https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_63.0.3239.108-1_amd64.deb

As a temporary workaround I downloaded and extracted libwidevine.so from there and put it in my .kodi/cdm dir. Everything seems to work fine again now.

**Comment by bded** [comment]
I try this workaround, and it works for me too.
Thanks lullius.

**Comment by ervy1** [comment]
Hi, any idea if I have the same issue?
log file [here](http://ix.io/KMs)

ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)

Tnx.

**Comment by ervy1** [comment]
@lullius @bded 
i think google is quick to stop or block linking to older versions of the file like the one lullius posted,,
https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_63.0.3239.108-1_amd64.deb

any chance you can send me the older libwidevinecdm.so file? tnx.

**Comment by lullius** [comment]
@ervy1 
I'm not sure I'm allowed to send you the file, but I did find a mirror that is still up:
http://sagasl.uccuyosl.edu.ar/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/

MD5sums of my working files are:
cc36f3a115e3e213a2bedb8b8fbe08ba  google-chrome-stable_63.0.3239.108-1_amd64.deb
06fffe4c8849017ba42908b7505fb04b  libwidevinecdm.so

**Comment by ervy1** [comment]
tnx - ill give it a try tonight

**Comment by ervy1** [comment]
@lullius 
Thank you Thank you Thank you - it works now. :))
