### ISSUE TITLE
N€tflix videos VP9 Profile 2 or AV1 cause DecryptAndDecodeVideo error status 5 (kDecodeError)

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#1181]
### Describe the bug
Here is a clear and concise description of what the problem is:

im testing AV1 and VP9 Profile 2 on kodi 21

video with VP9 Profile 2 do not start, and raise a non ending errors of:
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status: 5`
status 5 == kDecodeError

video with AV1 codec video starts, for some minutes i think because firsts unencrypted segments, then raise
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::LogDecryptError: Decrypt failed with error: 2 and key: 0000000006E9C0010000000000000000`

video with AV1 codec video, if seek forward immediately to middle of video, then raise the same above
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status: 5`

Try to play the same VP9 Profile 2 stream **on Kodi 19 works** without problems
apparently a regression somewhere

i have not tested force trying AV1 on Kodi 19 since its not supported

sidenote:
we should limits CDM errors and stop playback without having a infinite loop

### To Reproduce

to test VP9 Profile 2:
1. Install N€tflix addon by using this mod: [plugin.video.netflix_1.20.8+matrix.1_20230302_VP9.2.zip](https://github.com/xbmc/inputstream.adaptive/files/10872186/plugin.video.netflix_1.20.8%2Bmatrix.1_20230302_VP9.2.zip)
2. Ensure that on nf addon expert settings there is VP9 enabled and all other video codecs disabled
3. i dont know if there are more videos with this codec but for sure this, find the movie: `Cosmos Laundromat: First Cycle`
4. play it

to test AV1:
1. Ensure that on nf addon expert settings there is AV1 enabled and all other video codecs disabled
2. Play "Dune" video title

On kodi 19 is played but wrong displayed is expected, ok Kodi 20/21 give error

### Debuglog

The debuglog can be found here:
VP9.2: [kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872500/kodi.log.txt)

AV1 from starts: [kodi - AV1fromStarts.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872629/kodi.-.AV1fromStarts.log.txt)
AV1 immediate seek forward: [kodi - AV1skipToMiddle.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872636/kodi.-.AV1skipToMiddle.log.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10872152/manifest.mpd.txt)
[manifestAV1.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10872666/manifestAV1.mpd.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i tried apply PR #1165 but has not fixed the problem

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21 master branch
 - inputstream.adaptive version: Omega branch 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i made a lot of reverts
and i found that on my old refactor is the cause [472fea3f9087e3be17ea88e51d2b3d0560161940](https://github.com/xbmc/inputstream.adaptive/commit/472fea3f9087e3be17ea88e51d2b3d0560161940)
i will try investigate whats wrong

**Comment by CastagnaIT** [comment]
found the problem is the encryption_scheme set in to the inputbuffer on DecryptAndDecodeVideo
for some reason have a wrong value

**Comment by CastagnaIT** [comment]
@glennguy i found the bug the old refactor is not the cause,
but a problem in the `CFragmentedSampleReader::ProcessMoof`
the `schemeType` for some reason return an unhandled value of `1885955686`

follow fix:
https://github.com/CastagnaIT/inputstream.adaptive/commit/1f512fd60f3a3e0a2feae095452b2a8da5b5741f#diff-ae3bbb4407d6625e36a1b5d2f70f0b6829e0ebe41103e0772ca960a5935827d0R430-R437

so if i add this value then the playback for AV1 and VP9.2 works correctly,
and now i can also confirm that the PR that add/fix new video formats display images correctly for both codec cases

now there is to understand the reason why return this value, that there is no in the protection scheme definitions:
https://github.com/axiomatic-systems/Bento4/blob/master/Source/C%2B%2B/Core/Ap4CommonEncryption.h#L55-L58

if you have some idea how investigate or if you can give help because now im stuck

the mp4 video data should be this
https://www.dropbox.com/s/94fpqyert4itgy2/UjNxE0-B.7z?dl=1

**Comment by CastagnaIT** [comment]
i tried reverse the atom
```
    int val = 1885955686;
    char ch = (val >> 24);
    char ch1 = (val >> 16);
    char ch2 = (val >> 8);
    char ch3 = (val);
    cout<<  ch<<ch1<<ch2<<ch3;
```

and 1885955686 value is "piff"
looking at https://github.com/gpac/gpac/wiki/Common-Encryption#gpacdrm-element-semantics
seem to be not a wrong value, just unhandled?

**Comment by glennguy** [comment]
Try this one https://github.com/axiomatic-systems/Bento4/blob/0735fe81819fd5f6501e6649b6e0d4b2b7874d8f/Source/C%2B%2B/Core/Ap4Piff.h#L57

**Comment by CastagnaIT** [comment]
yeah AP4_PROTECTION_SCHEME_TYPE_PIFF works!
i will make a PR
