### ISSUE TITLE
Kodi v20 crashes randomly when starting a netflix video over tvheadend

### ISSUE THREAD

**Issue by xhpohanka** [peak3d/inputstream.adaptive#1185]
My libreelec kodi instance is sometimes crashing when starting a netflix video. It happens in case when another stream is already playing (tvheadend).

Here is my crashlog...
https://pastebin.com/97xrRWXM

https://forum.libreelec.tv/thread/26729-random-crash-when-starting-a-netflix-video/?postID=177679#post177679

**Comment by CastagnaIT** [comment]
you forgot to enable Kodi debug setting, enable it and provide a new log

**Comment by xhpohanka** [comment]
> you forgot to enable Kodi debug setting, enable it and provide a new log

Indeed. _Fortunately_ it is easilly reproducible, here it is... http://ix.io/4qj7

[log.txt](https://github.com/xbmc/inputstream.adaptive/files/12130670/log.txt)

**Comment by CastagnaIT** [comment]
please check if LE provide ISAdaptive addon updated to 20.3.9
if so, please try to see if crash still happens

**Comment by xhpohanka** [comment]
I just got the crash with `20.3.9.1` 😟

**Comment by CastagnaIT** [comment]
i close it since has been fixed on Kodi 21
