### ISSUE TITLE
[Netflix] Formula 1: Drive to survive throws CDM status: 5

### ISSUE THREAD

**Issue by ErwinJunge** [peak3d/inputstream.adaptive#1188]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have the same symptoms as described in https://github.com/xbmc/inputstream.adaptive/issues/1181, but with the show "Formula 1: Drive to survive" instead of the example chosen there. I figured it's probably the same issue, so I first waited for that to be fixed and a new release to be cut. However I upgraded to 20.3.5 today and the problem still persists.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video plays.

## Actual Behavior

Video does not play. Instead, a spinner shows infinitely. When debug log is enabled the log is spammed full with this line on repeat:

```
debug <general>: AddOnLog: inputstream.adaptive: DecryptAndDecodeVideo: Returned CDM status: 5
```

## Possible Fix
Probably something similar to https://github.com/xbmc/inputstream.adaptive/issues/1181, but for a different value than "piff"? I'm not sure what "piff" even is tbh, this is not my area of expertise :shrug: 

### To Reproduce

1. Try to play episode 1 of season 5 of drive to survive on netflix.

### Debuglog

The debuglog can be found here:

[debug.log](https://github.com/xbmc/inputstream.adaptive/files/10952116/debug.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

I don't know how to get this, but if you can point me in the right direction I'll gladly upload it.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux Arm on a raspberry pi 4 (32 bit install, kernel 6.1.15)
 - Kodi version: 20.0
 - inputstream.adaptive version: 20.3.5

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
unfurnately the "piff" fix has not be backported yet due to lack of time
this means 20.3.5 dont have the fix

**Comment by CastagnaIT** [comment]
i cannot provide you a test build for RPI
but if you are able to build yourself the add-on for your RPI you can build by using PR #1189

**Comment by ErwinJunge** [comment]
Hey @CastagnaIT thanks for the quick reply! I'm sorry about testing the wrong thing, I thought this was already part of the release :)

Luckily, I can build this myself, so I just did. I tested it and it didn't work...

I noticed in the code that you added some additional logging as well and I don't see those lines either in the kodi log. Could it be that there's another different protection scheme going on that's not handled at all?

I'd love to help you out to fix this, but I'm not sure how to proceed from here. If you could give me some pointers on what to try, or what files to provide to you I'd be happy to help.

**Comment by CastagnaIT** [comment]
i tested mentioned tvshow episode under ubuntu
`Formula 1: Drive to survive - episode 1 of season 5`

on Kodi 20 i have same mentioned errors
on Kodi 19 is played correctly

~looks like a ISAdaptive regression but i dont know~

**Comment by CastagnaIT** [comment]
well i compiled PR #1189 for ubuntu and installed over v20
and i can confirm that playback now works correctly (so its the "piff" problem)
so i think you have compiled wrong branch or you installed the compiled binary in wrong way

now that PR has been merged on Nexus branch so you can build also by using the Nexus branch of this repo

**Comment by ErwinJunge** [comment]
Thanks for the double check. I tried again on a completely fresh copy and it worked now. I think I probably had some leftovers from a previous compile of a PR. In fact, it was another one of yours :grinning: https://github.com/xbmc/inputstream.adaptive/pull/1119

Thanks so much for the work you put in to this project. We can close this, since it's fixed in the nexus branch :+1:
