### ISSUE TITLE
No Sound in Kodi 20

### ISSUE THREAD

**Issue by Vikassm73** [peak3d/inputstream.adaptive#1192]
Stream is working perfectly in Kodi 19.5 but there is no sound in Kodi 20.

Manifest of MPD
https://paste.kodi.tv/ejawimezoc

Debug Log
https://paste.kodi.tv/lepucaqena.kodi

**Comment by CastagnaIT** [comment]
please provide also a log of the same video played on kodi 19

**Comment by Vikassm73** [comment]
Log file in Kodi 19

https://paste.kodi.tv/simugotero.kodi

**Comment by CastagnaIT** [comment]
if you are still interested on this please update broken links

**Comment by Vikassm73** [comment]
You can close this.  It was an issue with some episodes. Those are still giving a problem but latest episodes are working fine.
