### ISSUE TITLE
kodi 11 - subtitles for livestrams are 'accumulating'

### ISSUE THREAD

**Issue by joopdo** [peak3d/inputstream.adaptive#1193]
### Describe the bug
If I open a livestream in Kodi 20, subtitles start at the bottom of the screen, then each additional subtitle get's added, until the screen is full, then they stay there. (assuming they keep piling up outside the screen). On the previous kodi version, the subtitles disappeared as expected.

This seems only with live streams that make use of inputstream.adaptive, on demand works fine. 

### Screenshots 

![PXL_20230315_214642723](https://user-images.githubusercontent.com/1182449/225451405-a4081c55-9f90-4509-9d08-7c9ba21d4e84.jpg)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.0
- libreelec 11

**Comment by joopdo** [comment]
@CastagnaIT Sorry I'll follow the rules in an update to this issue.

**Comment by CastagnaIT** [comment]
this should be opened on xbmc repo not here
and you should test over kodi 20.1 because could be already fixed

edit: for this purpose you can install kodi 20.1 on another system just to test it (if LE is not available yet)

**Comment by joopdo** [comment]
Thanks, I'll do that. I'll close the issue then.
