### ISSUE TITLE
Headers set by Server aren't forwarded

### ISSUE THREAD

**Issue by completafurdc** [peak3d/inputstream.adaptive#1195]
### Describe the bug
Here is a clear and concise description of what the problem is:
When a channel is played, It redirects the URL to another location. The new URL is response sets some `cookie` header which are needed to load the children. As I can see **403 Error by debugging**, It looks like this is probably the cause as the server sent headers aren't set.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The headers set by server should have also been set and sent to children. Like `Cookie`

## Actual Behavior

The headers set by server aren't sent. Like `Cookie`

### To Reproduce

1. Played a channel where server is setting some sort of Header, `Cookie` in my case

### Debuglog

The debuglog can be found here:
NA

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
NA

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 20.1
 - inputstream.adaptive version: 20.3.5

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i assume that you are talking of HLS manifest (?) and that the cookie is provided by the master playlist for the children?
there is already opened issue for this #184

this is a custom requirement for some servers, its possible that we will implement this support in future with a property to enable it

as workaround, some users use a custom addon service that make requestwith right cookies by using the addon service and provide the manifests to ISA
https://github.com/xbmc/inputstream.adaptive/wiki/How-to-provide-custom-manifest-and-license
but i dont know if it is easily possible with HLS

**Comment by completafurdc** [comment]
Hi! Thanks for your response. I am taking about both HLS and DASH Manifest. Sorry didn't looked to so old issues.

Yes, actually a lot more providers these days require this as a part of basic authentication. Custom solution to implement a server won't be possible on scale and can bring in several unforseen edge cases. 

Is this something which can be done in a single commit or something which requires heavy brain storming? I really feel that this feature should be a must for such a great addon and request the team to please take this on high priority.

Thanks!

**Comment by CastagnaIT** [comment]
we are only two active maintainers of this addon so there is a slow developing
currently this is not seen by us as higher priority

usually new features are not backported to previous versions (atm kodi 20)
however will be evaluated when the task is taken over

im currently busy with a big rework of this project that has the priority over all
except for kind of bugs so i cannot provide you ETAs

however the workaroud do not require to implement a server, but instead an addon service as explained in the wiki link,
so the addon service will take care to download the manifest files and then handle the headers/cookies

**Comment by completafurdc** [comment]
Understandable, I really appreicate the teams effort and commitments on this. Thanks a lot!
Oh got it, misunderstood. Sure will take a look at those methods! All the best for rework, Wish you luck!

**Comment by CastagnaIT** [comment]
i have implemented a workaround for the session cookies problem,
if there is someone willing to test and give me a feedback would be useful

the cookies now are stored managed by ISAdaptive,
be aware that if you set manually cookies to the property `inputstream.adaptive.stream_headers`
they will replace/delete the session cookies

test builds (Kodi 21 only):
(link re-updated)
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1412/3/artifacts

otherwise you can build PR #1412
