### ISSUE TITLE
Unable to play DRM-Free Multibitrate HLS from WinterOlympics

### ISSUE THREAD

**Issue by Gujal00** [peak3d/inputstream.adaptive#120]
This is the multibitrate stream from Winter Olympics. Works fine on browser/vlc but not with inputstream.adaptive. This is the content of the STRM file that I am using
`#KODIPROP:inputstreamaddon=inputstream.adaptive`
`#KODIPROP:inputstream.adaptive.manifest_type=hls`
`https://live.olympicchannel.com/ocs/channel01b/master.m3u8`

I thin the issue is identical to the one described in #109 
Please help

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/9089703f939a2db177363cfbde11a505fc6ecf8f
