### ISSUE TITLE
Cannot play Netflix stream with IA binary addon on FireTV

### ISSUE THREAD

**Issue by quietvoid** [peak3d/inputstream.adaptive#1200]
### Describe the bug
Here is a clear and concise description of what the problem is:

There seems to be a problem with IA not being able to find a decrypter when Kodi 21 is built with IA as a binary addon.
When I try playing a Netflix stream through the Netflix addon, I get an error that the video can't be played.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should play.

## Actual Behavior

There's an error and playback fails.

The log contains these:
>2023-03-24 20:15:57.996 T:2980     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 3840x2160, Adjust refresh rate: 0
2023-03-24 20:15:57.996 T:2980    debug <general>: AddOnLog: inputstream.adaptive: Searching for decrypters in: /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
2023-03-24 20:15:57.997 T:2980    debug <general>: AddOnLog: inputstream.adaptive: Searching for decrypters in: /data/user/0/org.xbmc.kodi/cache/lib/inputstream.adaptive/
2023-03-24 20:15:57.997 T:2790    debug <general>: void CXBMCApp::OnPlayBackStarted()
2023-03-24 20:15:57.997 T:2980    error <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/lib/inputstream.adaptive/
2023-03-24 20:15:57.997 T:2980    debug <general>: AddOnLog: inputstream.adaptive: Searching for decrypters in: /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
...
2023-03-24 20:16:00.105 T:2980    debug <general>: AddOnLog: inputstream.adaptive: Entering encryption section
2023-03-24 20:16:00.105 T:2980    error <general>: AddOnLog: inputstream.adaptive: No decrypter found for encrypted stream
2023-03-24 20:16:00.105 T:2980    debug <general>: AddOnLog: inputstream.adaptive: CSession::~CSession()

## Possible Fix

Installing IA `20.3.5-Nexus` through the Kodi repository works if Kodi wasn't built with the binary addon.
For some reason it only does not work with the binary addon built-in.

### To Reproduce

1. Follow Kodi build instructions for Android
2. At the step to build binary addons (after depends), build the IA binary addon with: 
    `make -j$NUM_THREADS -C tools/depends/target/binary-addons ADDONS="inputstream.adaptive"`
3. Build the rest of Kodi
4. Install the built APK on the device
5. Install the Netflix addon through repository, do the setup
6. Try playing a Netflix video through the addon

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/azavadonad.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I looked quickly and it seems that none of the searched directories are readable when I try accessing them through `adb shell`.

Some more context but it has no additional info over the debug log: https://forum.kodi.tv/showthread.php?tid=371557&pid=3146334#pid3146334

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireOS 7, FireTV Stick 4K Max
 - Kodi version: 21 nightly, commit https://github.com/xbmc/xbmc/commit/6a8b23c59f01827ae8dab177485e9ab07a578b4a
 - inputstream.adaptive version: 21.0.3-Omega as a binary addon

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by quietvoid** [comment]
I've seen some users suggest to install the addon from Jenkins' runs: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/21/artifacts
But I don't understand why that's necessary.

I haven't tried it either.

**Comment by glennguy** [comment]
The built-in path was removed from being searched in 2021 when we stopped packaging inputstream.adaptive with Kodi. This was needed to allow proper updating of the add-on - code used to look like this: https://github.com/xbmc/inputstream.adaptive/blob/8887378b71cd12506679ff6d4b7e48f1a83b9949/src/main.cpp#L2139-L2148

and is now like this: https://github.com/xbmc/inputstream.adaptive/blob/1f2c66c38072e7a78cb3197388a8ae6bd9ff5ab9/src/Session.cpp#L123-L128

Installing from zip as has been suggested to you will place the decrypter library in one of the paths that are currently searched. In the future we plan to make the decrypter library part of the main library - no searching needed.

For now though it could be added back to allow for your case or alternatively you can build IA separately and install from zip.

**Comment by quietvoid** [comment]
Thanks. I tried installing the latest Omega release on a regular Kodi build and it works fine.

Unfortunately I couldn't figure out how to package the binary addon myself, so I have to rely on the CI.
There doesn't seem to be clear instructions on building for target platforms, and looking at the CI log didn't really help me.

It's mostly only an issue because the Kodi repository doesn't include nightly versions, and I wasn't aware the CI was packaging them.

**Comment by CastagnaIT** [comment]
another alternative to build yourself ISA
is to add my github action CI builder, by forking `Omega_CI` branch from
https://github.com/CastagnaIT/inputstream.adaptive/tree/Omega_CI
to your github

after that in your github repo, go to Actions page,
and on CI manual artifacts buildings section, click to Run workflow button, you can select platform/architecture
write the branch to be builded and other options

![immagine](https://user-images.githubusercontent.com/3257156/229081804-d9ea2c24-6405-4d7d-a431-18d9036d7a73.png)

ofc you need to keep in sync your repo branches to be builded
or you can hack my github action CI to point official repository

my action CI builder is not perfect but can save headaches to avoid setting up an ad hoc os to build ISA for each other system

(basically you keep Omega_CI as default branch and no need to update it, then select to build one of the other branches)

**Comment by quietvoid** [comment]
Thank you, it is really useful.

Reading the workflow, it just seems I was doing some things wrong.
I couldn't get the `package-*` target to work but I'll try copying some parts and see if I can do it in my environment too.
