### ISSUE TITLE
Inputstream-adaptive doesn't work (marked as incompatible) on the latest Kodi master (Omega)

### ISSUE THREAD

**Issue by hbbernardo** [peak3d/inputstream.adaptive#1205]
After upgrading LibreElec to the latest  test build version complied using the latest Kodi code inputstream-adaptive is disabled. Marked as incompatible.

You can find the latest LibreElec builds here:

https://test.libreelec.tv/12.0/RPi/RPi2/

This issue has started with the build from today (April, 02)

There's also in this link a changelog

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec

 - Kodi version: 21 (Omega)

 - inputstream.adaptive version:

inputstream-adaptive 21.0.3-Omega

**Comment by lrusak** [comment]
Likely LibreELEC needs to update the add-on version.
