### ISSUE TITLE
[DASH] Inform Kodi when advertisements are playing

### ISSUE THREAD

**Issue by dapharsyde** [peak3d/inputstream.adaptive#1207]
Logging this issue as a feature request for the team to consider adding the detection of advertisements via SCTE-35 markers or similar, and informing Kodi of this in the chapter/period.  If this feature is implemented, Kodi could add a new setting that automatically mutes the audio during advertisements detected using this method.

@matthuisman - please help add any additional context to this request, this is my first time creating a github issue - thanks!

**Comment by CastagnaIT** [comment]
@enen92 iirc you have worked for something related this?
are you aware if this is supported for binary addons?

**Comment by enen92** [comment]
Nop not really @CastagnaIT I fixed mute actions in EDL which were broken before, and also spent a bit of time understanding EDL implementation in general. My guess is that the way to go is to extend the EDL interface and allow addons to set new edits. I was thinking about doing this a bit more statically by allowing the addon to set a property with a list of edits. However, as far as I can understand the request here is a bit more dynamic...
Currently this is not possible at all

**Comment by CastagnaIT** [comment]
thanks so in near future its not possible do nothing about this
then i close it

**Comment by dapharsyde** [comment]
@enen92 - I see this issue has been closed, but is it because we need to first "extend the EDL interface and allow addons to set new edits" as part of a Kodi change?  If that's the case, is there a Kodi issue tracking this feature request, or can I create one for it, in hopes of eventually re-opening this issue on the inputstream.adaptive side?
