### ISSUE TITLE
[Hulu] Some live streams don't seem to redownload the manifest

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1213]
[manifest_1680918086.txt](https://github.com/xbmc/inputstream.adaptive/files/11182307/manifest_1680918086.txt)
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11182308/kodi.log)

I see
"AddOnLog: inputstream.adaptive: adaptive::DASHTree::RefreshLiveSegments: Full update without start number (repr. id: DSS_VIDEO_7_1800000 current start: 9)"

But only ever the initial 1st manifest in the IA's manifest folder and the time of the stream never gets updated
![screenshot00011](https://user-images.githubusercontent.com/6225961/230697893-4c996cfe-fbfb-44b9-abb4-2d1acd1dea7d.png)

**Comment by glennguy** [comment]
Does it work if you set the manifest update parameter to 'full'?

**Comment by CastagnaIT** [comment]
is this a modified/custom manifest?
fwik the location tag should have an absolute address not relative as is:

`<Location>/patch_dash_continue/EPLUS094-2-DSS.mpd?cdn=af&amp;cdn_auth=true&amp;cluster=blue&amp;duration=10800&amp;enabled_ec3_codecs=false&amp;fill_gap=1&amp;fragment_offset=3&amp;max_frame_rate=60&amp;max_h264_codec=avc1.64002a&amp;origin_location=ava&amp;repeat=1&amp;split_times=3&amp;stream_cdn=sfa&amp;use_events=1&amp;last_period=151282613707650&amp;next_segment_ts=151282626320251&amp;token=1681004481_4d177bd6ee15f14a55cc4b4cacdd5abd0216333093692406e7cb2248ddd7fc41</Location>`

**Comment by matthuisman** [comment]
Does IA use the location?
I thought it didn't?

**Comment by matthuisman** [comment]
closing this as ESPN seems to do something "weird" with their manifests

**Comment by CastagnaIT** [comment]
> Does IA use the location? I thought it didn't?

yes read it but check for absolute address
but i have not verified if parameter 'full' is set automatically
