### ISSUE TITLE
IA plugin does not work in kodi21 and affects other plugins

### ISSUE THREAD

**Issue by yanik2333** [peak3d/inputstream.adaptive#1217]
Adaptive cannot continue to use InputStream.Adaptive after updating **Kodi21 Omega** version, so the problem is that kodi21 is not compatible with this plugin version or is not available, and there is no official update!
In addition, only InputStream Adaptive **20.3.6** is available in the official plugin Bitter Library, and I understand that the technicians have updated to Omega compliant version **21.1.0**, but the problem can be closed if the official plugin library is updated as soon as possible!

**Comment by glennguy** [comment]
Kodi official repository only provides binary addons like inputstream.adaptive for Windows, Mac, and Android. Linux platforms are supported by separate package managers.

Please use the bug report issue template next time so we may know more about your platform and use case.

**Comment by yanik2333** [comment]
Thanks for the reply, **first I'll upload my bug report**[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11189953/kodi.log)and then I'll ask this project or a technician who knows this project to help me investigate the phenomenon of this bug report, thanks guys!

**Comment by yanik2333** [comment]
By the way, my system is Android TV 11.

**Comment by glennguy** [comment]
Hi @yanik2333 thanks for posting the log

I have found the issue is the current builds of Kodi 21 are still pointing to the Kodi 20 add-on repository - the Nexus version inputstream.adaptive is incompatible with Kodi Omega. 

I've made a pull request to get this updated/fixed which will hopefully make the forthcoming alpha release of Omega.
Until then you can download the add-on directly from here which will suit your Android TV: https://mirrors.kodi.tv/addons/omega/inputstream.adaptive+android-armv7/inputstream.adaptive-21.1.0.zip

**Comment by onlytanmoy** [comment]
Hi @glennguy can you please share the file for arm64-v8a so that I can install in Kodi Omega running on my Nvidia Shield 2019 device?

**Comment by glennguy** [comment]
Sure - all addons can be found here https://mirrors.kodi.tv/addons/omega

**Comment by onlytanmoy** [comment]
@glennguy I am getting this error :(
![image](https://user-images.githubusercontent.com/48493659/231457770-b7a01b5b-bd58-446e-9370-7ff26f5c697a.png)

**Comment by CastagnaIT** [comment]
you need add backslash
https://mirrors.kodi.tv/addons/omega/

**Comment by Nuklear92** [comment]
I've been trying to install these and they don't install, it prompts something like "unable to install due to invalid structure". Same goes for even the nexus version. 😩

**Comment by onlytanmoy** [comment]
@CastagnaIT thanks mate, I was able to install inputstream.adaptive-21.1.0.zip from there in my Shield TV and thereafter install the YouTube add-on.

**Comment by yanik2333** [comment]
> 你好@yanik2333感谢您发布日志
> 
> 我发现问题是 Kodi 21 的当前版本仍然指向 Kodi 20 附加存储库 - Nexus 版本 inputstream.adaptive 与 Kodi Omega 不兼容。
> 
> 我已经提出了一个拉取请求来更新/修复这个问题，这将有希望使即将到来的 Omega alpha 版本成为现实。 在此之前，您可以直接从此处下载适合您的 Android TV 的插件：https://mirrors.kodi.tv/addons/omega/inputstream.adaptive+android-armv7/inputstream.adaptive-21.1.0.zip

Thank you for your reply and for your help in such detail

**Comment by yanik2333** [comment]
Well, it's possible to install this plugin, thanks to the help of the technician, and I can use it to watch 4K video streams from Netflix!
