### ISSUE TITLE
Help with License parameters

### ISSUE THREAD

**Issue by diegofn** [peak3d/inputstream.adaptive#122]
Hello to all,

Can you help me with the correct parameters for this MPD file with widevine license
LIcense URL: https://widevine-vod.clarovideo.net/licenser/getlicense  
https://www.clarovideo.com/playerhtml5/colombia/tv/717022.php?playgroupfull&group_id=717022&is_live

I tried the following params but it does not work:
```
listitem.setProperty('inputstreamaddon','inputstream.adaptive')
            listitem.setProperty('inputstream.adaptive.manifest_type','mpd')
            listitem.setProperty('inputstream.adaptive.license_type','com.widevine.alpha')
            listitem.setProperty('inputstream.adaptive.llicense_key','https://widevine-vod.clarovideo.net/licenser/getlicense')
            self.xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)  
```

Thanks for your help

**Comment by peak3d** [comment]
Hi,
`https://widevine-vod.clarovideo.net/licenser/getlicense||{"token":"0a128898b223085e7da300c2276e0df8","device_id":"030481698d85c27166f7bb3a8121c110","widevineBody":"B{SSID}"|`

The correct token and device_id must be set in the string above from you, you'll get both of them somehow from the web page.

**Comment by diegofn** [comment]
Hello @peak3d 

I tried the following code:
```
listitem = self.xbmcgui.ListItem(path = stream_url)
            
listitem.setProperty('inputstreamaddon','inputstream.adaptive')
listitem.setProperty('inputstream.adaptive.manifest_type','mpd')
listitem.setProperty('inputstream.adaptive.license_type','com.widevine.alpha')
listitem.setProperty('inputstream.adaptive.license_key','https://widevine-vod.clarovideo.net/licenser/getlicense||{"token":"0a5cc2012010abf6901bb14177464c3a","device_id":"b7d30225cf0f0c458c9db09bdb633a04","widevineBody":"B{SSM}"|')

#listitem.setMimeType('application/dash+xml')
#listitem.setContentLookup(False)

self.xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)  
```

But it does not work I get the following log:
https://pastebin.com/UjBML4dk

Do you reach to view the streaming in kodi?
https://www.clarovideo.com/playerhtml5/colombia/tv/717024.php?playgroupfull&group_id=717024&is_live

Thanks for your help.

**Comment by peak3d** [comment]
Between the two || in license_key Headers can be set in format Name=value&name2=value2....
HTTP 415 sounds for me that you have to set / overwrite Content-Type HTTP Header.

Play around with headers (you'll find required headers in Browser log).

**Comment by peak3d** [comment]
There is a getCertificate call in log, you may have to copy the b64encoded string (or b64 encode by yourself) and pass it in inputstream.adaptive.server_certifictate listItem property.

I'm currently unable to play the video in kodi, not sure if its caused by an wrong widevine or whatever - have to investigate. Maybe you have luck with the server_certificate.

**Comment by peak3d** [comment]
@diegofn the token is only a few seconds valid, because of that .strm file is not working.
I wrote a small plugin to test: https://github.com/peak3d/plugin.video.simple

The server_certificate is hardcoded in my addon, you should retrieve it in the same way as done on web site.

**Comment by peak3d** [comment]
Pls. refer to plugin.video.simple in this git repo

**Comment by diegofn** [comment]
Thanks I will test it and give feedback to you.

**Comment by diegofn** [comment]
Thanks for all!! It works, I will review the retrieve getCertficate URL.

**Comment by kate395** [comment]
Can you adapt this plugin to this player : https://www.radiantmediaplayer.com/docs/latest/dash-drm-documentation.html
