### ISSUE TITLE
[Windows] DRM Error: no keys (working on ARM)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#123]
LibreELEC 8.2.3 RPI3 Log (working)
https://pastebin.com/c7LxccLq

Windows 10 Log (not working)
https://pastebin.com/Sg9PgskN

Windows 7 Log (not working)
http://ix.io/PG7

Here is the manifest mpd file
https://pastebin.com/UALdM4Lw

Both using Inputstream Adaptive 2.0.19

It has me stumped.
I have tried rolling back to older KODI versions and even latest nightlies.
Also tried older versions of Inpustream Adaptive.
Also tried different widevine dll's.
The same error occurs.

It was working fine recently (1 week ago maybe?)

The only real difference in the logs I see is that Windows can't verify the SSL certs.

I have another user using Windows 7 with I suspect the same issue.

**Comment by peak3d** [comment]
In kodi userspace (where kodi log rsides) in folder cdm is a .response file.
Pls. analyze the content there and / or provide the file here

**Comment by zlootec** [comment]
I have exactly the same issue.
Here is my response file: [https://pastebin.com/raw/E1JQECWp](url)

**Comment by peak3d** [comment]
@zlootec can you pls provide the kodi log (debug logging enabled / component debugging off) ?
Maybe I need the license_key parameter in addon too, not sure if I print it out,

**Comment by zlootec** [comment]
Kodi log: https://pastebin.com/raw/HWvGkHtR
`license_key = license_server + '|' + license_headers + '|R{SSM}|JBlicense'`

**Comment by peak3d** [comment]
Ok, license_key looks fine for the response.

Pls. Install EME logger in Chrome Browser, open it, and start a movie.
After that provide the log output. You can use my mail public here in github.

**Comment by peak3d** [comment]
Pls retry after the latest commit:

https://github.com/peak3d/inputstream.adaptive/commit/f63d5921b211297197f23434328f0c188f12c9f7

**Comment by zlootec** [comment]
Working both under Windows 7 and 10.
Could not test under linux because can't compile the latest wvdecrypter.

**Comment by peak3d** [comment]
wvdecrypter is compiled together with inputstream.adaptive.
you don't have to compile / install it separated.

**Comment by matthuisman** [comment]
Tested with KodiSetup-20180319-2c8eac2e-master-x64 (inputstream adaptive 2.2.5)
Works fine now :)
I'll close issue
