### ISSUE TITLE
Kodi crashes when starting a Netflix stream on arm64

### ISSUE THREAD

**Issue by Deadmansshoe** [peak3d/inputstream.adaptive#1245]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when trying to watch something on Netflix before the stream starts. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The stream should just start.

## Actual Behavior

Kodi restarts.

## Possible Fix

In the logs, kodi seems to be trying to open a undefined directory, where inputstream adaptive is trying to find a decrypter.

```
2023-04-29 23:14:13.515 T:798155   debug <general>: AddOnLog: inputstream.adaptive: Searching for decrypters in:
2023-04-29 23:14:13.515 T:798155   error <general>: GetDirectory - Error getting
```

### To Reproduce

1. Go a movie/series 
2. Start a stream

### Debuglog

The debuglog can be found here:

[kodi_crashlog-20230429_225555.log](https://github.com/xbmc/inputstream.adaptive/files/11360105/kodi_crashlog-20230429_225555.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Inputstream helper was at first not working with my system as arm64 support is not in the official release yet. Therefore, I installed a test build from github. After that, I could install the widevine libraries, however this problem occurred then.

I do not think that this problem is specific to the Netflix plugin, but as it is a fresh installation, I have not added any other plugin which uses IA. I will try this later and post the results here.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjora 6.1.24-1-MANJARO-ARM-RPI
 - Kodi version: 20.0.0
 - inputstream.adaptive version: 21.1.0.Omega.r54.gb6cdc64-1
 - inputsream.helper version: [0.5.10+matrix.1-arm64-3983f12](https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/533#issuecomment-1484131357)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Deadmansshoe** [comment]
So I have now also tried with a different addon (joyn) and there I encounter the same problem. 

By now, I have installed the new version of inputstream helper, which works fine with arm64 and I have reinstalled widevine through that. However, this did not improve anything. 

Does really nobody have any idea, what could be happening or how I could solve this? Is there any possibility to find out what kind of decrypter IA is trying to load and why it is empty?

**Comment by glennguy** [comment]
Hi @Deadmansshoe 

I'm fairly certain the issue is when the decrypter tries to load libwidevinecdm.so

Our add-on has changes for arm64 which work in libreelec/coreelec arm64 - these OSes have their own changes (in Kodi or otherwise) to allow the proper loading. Your OS/kodi build may not... - please see https://github.com/CoreELEC/CoreELEC/tree/coreelec-21/packages/devel/glibc/patches/widevine-arm for example

**Comment by CastagnaIT** [comment]
seem that manjaro provide some packages for widevine but i dont know if can help for kodi
https://forum.manjaro.org/t/package-wishlist-for-manjaro-arm/131100/12
you can try ask for help on manjaro forum
