### ISSUE TITLE
Inputstream adaptive can not play hls without video

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1259]
### Describe the bug
Inpustream Adaptive close when trying to play hls file that ocntain audio only (no video)

## Expected Behavior
Inputstream adaptive should play the audio even there is no video

## Actual Behavior

Inputstream adaptive closes without any error message

### To Reproduce
Try to
 play this free link: https://stream.rtl.lu/live/hls/radio/rtllx

### Debuglog
The debuglog can be found here:
[kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/11469136/kodi.txt)

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Available at  [hls stream](https://stream.rtl.lu/live/hls/radio/rtllx)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.1 Nexus
 - inputstream.adaptive version: 20.3.6-1~kinetic

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
currently HLS manifest with audio only is not supported on ISA, we assume video+audio
but i think we can investigate to implementing it

**Comment by joaopa00** [comment]
Thank you for the feedback. I will wait for you to implement that.

**Comment by CastagnaIT** [comment]
i have implemented it
you can test on Kodi 21 with one of these test builds
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1342/5/artifacts
cannot be backported to older kodi versions
