### ISSUE TITLE
Build error wvdecrypter

### ISSUE THREAD

**Issue by Dubbeldrank** [peak3d/inputstream.adaptive#126]
When i try to build wvdecrypter on Ubuntu 16.04 64-bit i get the following error:

> [ 74%] Building CXX object libbento4/CMakeFiles/bento4.dir/Core/Ap4LinearReader.cpp.o
/home/kodi/inputstream.adaptive/lib/libbento4/Core/Ap4LinearReader.cpp: In member function ‘AP4_Result AP4_LinearReader::Advance(bool)’:
/home/kodi/inputstream.adaptive/lib/libbento4/Core/Ap4LinearReader.cpp:479:36: error: ‘nullptr’ was not declared in this scope
                 buffer->m_Sample = nullptr;
                                    ^
libbento4/CMakeFiles/bento4.dir/build.make:2462: recipe for target 'libbento4/CMakeFiles/bento4.dir/Core/Ap4LinearReader.cpp.o' failed
make[2]: *** [libbento4/CMakeFiles/bento4.dir/Core/Ap4LinearReader.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'libbento4/CMakeFiles/bento4.dir/all' failed
make[1]: *** [libbento4/CMakeFiles/bento4.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by peak3d** [comment]
wvdecrypter is compiled together with inputstream.adaptive, there is no need to compile wvdecrypter standalone. In your case it seems that -std=c++11 compiler flag is missing.
