### ISSUE TITLE
Missing sound channel info when using inputstream.adaptive for m3u8 (HLS) streams with pvr.iptvsimple

### ISSUE THREAD

**Issue by ajbathe** [peak3d/inputstream.adaptive#1265]
When I use the pvr.iptvsimple setting Advanced -> Use inputstream.adaptive for m3u8 (HLS) streams, the information about the number of sound channels is missing under the Skin Confluence or Estuary, please see
https://github.com/kodi-pvr/pvr.iptvsimple/issues/764#issue-1718455205

phunkyfish: "That issue should be with inputstream.adaptive. Please post the problem there."

My system: LE nightly-20230522-794a8ad (Omega), RPi4.aarch64, inputstream.adaptive 21.1.0.1

**Comment by L2501** [comment]
Often HLS streams don't provide this kind of metadata and it would need to be probed (like with mp3). If known beforehand it can be added by proxy and it will show properly.

**Comment by CastagnaIT** [comment]
this is a know problem a complete solution require not easy code changes, currently not planned

however on Kodi Omega we have already implemeted a fallback to 2.0 channels when HLS dont provide channels metadata,
but due to amount of changes behind it, this "fallback" will not be backported to Nexus

**Comment by CastagnaIT** [comment]
oh i read now that you specified Omega build this is weird...

so please enable "save manifest" on ISAdaptive expert settings
and attach to the message the manifest file

where find the manifest file: https://github.com/xbmc/inputstream.adaptive/wiki/Dev.-FAQ#how-to-get-downloaded-manifests-files

**Comment by ajbathe** [comment]
http://mcdn.daserste.de/daserste/de/master.m3u8

[manifest_1685430584_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/11597214/manifest_1685430584_child-audio.txt)
[manifest_1685430584_child-audio_1.txt](https://github.com/xbmc/inputstream.adaptive/files/11597216/manifest_1685430584_child-audio_1.txt)
[manifest_1685430584_child-subtitle.txt](https://github.com/xbmc/inputstream.adaptive/files/11597220/manifest_1685430584_child-subtitle.txt)
[manifest_1685430584_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/11597223/manifest_1685430584_child-video.txt)
[manifest_1685430584_child-video_1.txt](https://github.com/xbmc/inputstream.adaptive/files/11597225/manifest_1685430584_child-video_1.txt)
[manifest_1685430584_master.txt](https://github.com/xbmc/inputstream.adaptive/files/11597229/manifest_1685430584_master.txt)

As I mentioned, the media audio flag of channels is only missing, when the option "Use inputstream.adaptive for m3u8 (HLS) streams" under "Settings - IPTV Simple Client" -> Advanced -> Streaming is used. Otherwise it is there. As I observed, it is with all my IPTV channels (around 120).

**Comment by CastagnaIT** [comment]
this bug is already fixed on last version 21.1.1
at least testing linked stream i can see the 2 channels info in the GUI
now i dont know if LE has already updated his ISAdaptive binary
otherwise you will need to wait that their publish the new update
