### ISSUE TITLE
Decryption failing? on some manifests but not others within one VOD service

### ISSUE THREAD

**Issue by glennguy** [peak3d/inputstream.adaptive#128]
Hi @peak3d 

The service I'm accessing has two manifest options for each program (playlist_med and playlist_high)
I can achieve playback with no issue for the playlist_med manifest, but playlist_high just has a black screen with a continual stream of ffmpeg/aac errors in the log, leading me to think that something is being decrypted incorrectly.

I saw your request in another issue for log output from EME logger. I have logs for both playlists and can email them if you need.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/1821567/kodi.log)
[playlist_high.txt](https://github.com/peak3d/inputstream.adaptive/files/1821562/playlist_high.txt)
[playlist_med.txt](https://github.com/peak3d/inputstream.adaptive/files/1821563/playlist_med.txt)

Running Kodi March 16 nightly for Win x64, widevinecdm is latest at v1.4.9.1070

Let me know if you need any other info

Thanks

Glenn

**Comment by peak3d** [comment]
Hi Glenn, audio requires secure path, but this is not yet implemented in Kodi.

In the next commit these audio streams will be removed from selection - for your case this means that you will have no audio instead ffmpeg errors (but maybe you'll have video).

If you have video or not depends on if the video is HDCP restricted, there is still some TODO on my side figuring out how it works for windows.

Right now you can simply restict to Video streamtype in inputstream addon settings and look what happens.

**Comment by glennguy** [comment]
Ok so I think it must be HDCP. Changing the setting to video doesn't help, but I've just loaded Kodi onto my Android phone and playback is fine.

Are there any platforms other than Android that play nicely with HDCP streams? Haven't had any luck with Ubuntu/Intel NUC or LibreELEC/RPi3...

**Comment by peak3d** [comment]
Oh, I expected that RBPi3 could work, NUC not because its x86_64, HDCP is afaik under devlopment there.
Does the stream runs with chrome on ubuntu / NUC?

**Comment by peak3d** [comment]
Can you pls provide a new log via mail? Token has expired, cannot check here.

**Comment by glennguy** [comment]
Sure thing, I'll get the log/stream url to you later today (looks like it would be 1am where you are right now) as the expiry seems to be 6 hours.

Definitely a HDCP issue, a message briefly flashed on screen about changing the quality setting to low when I tried to play on chrome/ubuntu. From some limited research it looks like HDCP support is implemented in kernel 4.17 for intel's driver, so one step closer in the future.
