### ISSUE TITLE
DAZN VOD freezing on Windows 10

### ISSUE THREAD

**Issue by Maven85** [peak3d/inputstream.adaptive#1283]
### Describe the bug

DAZN VOD streams freeze after few minutes on Windows.
The problem does not exist on Android devices.

### Debuglog
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11702494/kodi.log)

### MPD/M3U8s/ISM
[stream.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/11702493/stream.mpd.txt)

## Additional context or screenshots (if appropriate)
When I play the stream in the browser, the last segment number is 143, but IA keeps trying to download number 144.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21
 - inputstream.adaptive version: 21.1.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
should be fixed now, please update ISA with this test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1284/2/artifacts
(building is in progress, you will find builds soon)

**Comment by Maven85** [comment]
Thanks for the quick fix, it's working now 👍
