### ISSUE TITLE
HLS played by ffmpeg, not inputstream.adaptive

### ISSUE THREAD

**Issue by reinisb** [peak3d/inputstream.adaptive#129]
Hi,

I use Kodi on my macOS and raspberry pi for watching HLS live streams. I do that either via .strm file containing the HLS stream URL or via an add-on which effectively does the same thing. The experience is awful - it takes multiple seconds for a stream to load initially and then during the stream it will stutter/have hiccups once in a while. Very annoying. Hence I decided to investigate the issue.

The streams that I am watching are from the same provider - all of the stream URLs follow the same pattern as this one: https://str3e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=ArjqMFM%2BAdQPX3Tdd8zLofNcQXTftu4DFN9UAA1wam8RU1GmY9b15FU%2Ft4QQObRU31rS860Xqc6mj0qpQOthUOf0Tm3FCV6A (the content is geo-blocked). This playlist.m3u8 file contains a link to the chunklist.m3u8 file, which in turn contains the links to the next 10 .ts chunks of the live stream. As far as I can see in the kodi.log the chunklist.m3u8 file is loaded every second or so to get the next .ts chunks, which are then also downloaded and played by ffmpeg. See the playlist.m3u8 and chunklist.m3u8 file contents right below.

playlist.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3022288,CODECS="avc1.100.30,mp4a.40.2"
chunklist_w441777882.m3u8?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
```

chunklist.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:156580
#EXTINF:2.0,
media_w441777882_156580.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:3.04,
media_w441777882_156581.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:2.96,
media_w441777882_156582.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:2.92,
media_w441777882_156583.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:3.08,
media_w441777882_156584.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:4.0,
media_w441777882_156585.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:2.0,
media_w441777882_156586.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:4.0,
media_w441777882_156587.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:2.0,
media_w441777882_156588.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
#EXTINF:3.4,
media_w441777882_156589.ts?resource_id=c-ltv1&auth_token=JYmc5XmP0Ql1EL4LjJ%2FkIci2w6D25DRp9YU6kR2I%2FX8qjSrBOvJbsLTlRf8RpURChGOqjCJAj353ihVnKZCk0xSDnMtsw%2BBd
```

Now, while investigating I stumbled upon inputstream.adaptive - it shall be superior to ffmped with loading and playing HLS streams. Perfect - exactly what I am looking for! As I have the newest v18 Leia nightly with inputstream.adaptive v2.2.5 installed I simply created a .strm file with the following contents, but the experience has not changed - actually I can see in the kodi.log that ffmpeg is still being used for playback (not inputstream.adaptive)! Can someone please point to what I am doing wrong? I really want inputstream.adaptive to work! I hate HLS via ffmpeg on Kodi. Thank you!

test.strm
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://str3e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=ArjqMFM%2BAdQPX3Tdd8zLofNcQXTftu4DFN9UAA1wam8RU1GmY9b15FU%2Ft4QQObRU31rS860Xqc6mj0qpQOthUOf0Tm3FCV6A
```

**Comment by peak3d** [comment]
Most probably inputstream.adaptive is not enabled in addon settings.
If enabled, please provide a debug log.

**Comment by reinisb** [comment]
Thanks for the quick response. You are correct - the addon was not enabled. Just tried the stream and can confirm that inputstream.adaptive is working perfectly - the stream starts immediately and not stuttering later on. Amazing!

Is this coming as the default HLS handler for Kodi instead of ffmpeg?

**Comment by peak3d** [comment]
I don't think so, but for sure a point we can discuss internally in team kodi.

**Comment by reinisb** [comment]
Please - do discuss this internally. HLS via ffmpeg is really, really bad. This would be a major improvement!
