### ISSUE TITLE
DASH stream stalls - RefreshLiveSegments: Segment at position 0 not found from (update) representation id: EC3_1_CMAF_CENC_CTR_256K

### ISSUE THREAD

**Issue by dapharsyde** [peak3d/inputstream.adaptive#1290]
I have been experiencing freezing on some specific live DASH streams within < 30 seconds.  It does not matter if an advertisement is playing or broadcast content.

This is a very unique, specific problem that only occurs sporadically during some broadcasts on the ESPN channel via the Hulu plugin.  When the stream stalls on ESPN, other channels work without an issue.  I am very confident the issue is specific to the streams being broadcast by ESPN at certain times.  I've experienced the issue twice recently - 6/5/2023 @ 8:45PM PDT and 6/12/2023 @ 4:30PM PDT

I've attached an excerpt from my kodi.log when the stream dies - the most notable entries are probably these lines, as they do not appear on other channels, nor on ESPN when the stream is working fine:

`AddOnLog: inputstream.adaptive: RefreshLiveSegments: Segment at position 0 not found from (update) representation id: EC3_1_CMAF_CENC_CTR_256K`

I understand this issue is difficult to reproduce/test/fix because it only occurs when ESPN is broadcasting something different in their content that causes the stream to drop out, but please let me know if there is anything I can help with regards to debugging this the next time I notice ESPN broadcasting this unsupported content.

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11730041/kodi.log)

**Comment by CastagnaIT** [comment]
next time please use the appropriate "problem report" template to open an issue

the log attached is without debug and shrinked that its totally useless, the log must be complete and with debug info
also you have to attach also all saved manifests by enabling relative ISA expert setting (https://github.com/xbmc/inputstream.adaptive/wiki/Dev.-FAQ#how-to-get-downloaded-manifests-files)

**Comment by dapharsyde** [comment]
Sorry about that, I am new to this community.  Hopefully the information below is better:



## Bug report
### Describe the bug
Here is a clear and concise description of what the problem is:




When tuned into a specific channel, ESPN, via the Hulu plugin, some broadcasts stall within a minute of playback.  The stalls happen regardless of whether an advertisement is playing or if it is regular content.  Changing to a different channel works without issue, which suggests the problem is related to something specific in the broadcast content.  It also does not happen continuously on the channel, the problem only appears during some broadcasts (live as opposed to taped content?)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:



Video should continue playing without pauses, as it does on other channels.

## Actual Behavior



Video playback stalls, and a "buffering...." message pops up.

## Possible Fix



?

### To Reproduce
Steps to reproduce the behavior:



1. Begin playback on ESPN channel via Hulu plugin 
2. 
3.


### Debuglog



The debuglog can be found here:

Attached 2 files - 

log file exhibiting stall behavior - [kodi_espn_stall.log](https://github.com/xbmc/inputstream.adaptive/files/11861124/kodi_espn_stall.log)

log file from regular channel with no stall - 
[kodi_no_stall.log](https://github.com/xbmc/inputstream.adaptive/files/11861126/kodi_no_stall.log)

### MPD/M3U8s/ISM


An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Attached 2 files -

manifest from ESPN, experiencing stalls - 
[manifest_1687731713_espn_stall.txt](https://github.com/xbmc/inputstream.adaptive/files/11861128/manifest_1687731713_espn_stall.txt)

manifest from CSNBA, no stalls - 
[manifest_1687731587_no_stall.txt](https://github.com/xbmc/inputstream.adaptive/files/11861131/manifest_1687731587_no_stall.txt)


### Screenshots 
Here are some links or screenshots to help explain the problem:




## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:





### Your Environment
Used Operating system:


 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11.0.1
 - Kodi version: 20.1
 - inputstream.adaptive version: 20.3.9.1




*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by L2501** [comment]
BBC live DASH stream also stalls
```
https://vs-cmaf-push-uk.live.cf.md.bbci.co.uk/x=3/i=urn:bbc:pips:service:bbc_one_hd/iptv_hd_abr_v1.mpd
```

**Comment by dapharsyde** [comment]
> BBC live DASH stream also stalls
> 
> ```
> https://vs-cmaf-push-uk.live.cf.md.bbci.co.uk/x=3/i=urn:bbc:pips:service:bbc_one_hd/iptv_hd_abr_v1.mpd
> ```

Please do not hijack my thread with your issues.  Unless you are also seeing stalling caused by an error related to "representation id: EC3_1_CMAF_CENC_CTR_256K", you should create your own issue because is it probably unrelated to this bug report.

**Comment by CastagnaIT** [comment]
can you test under Windows operative system or android?
because on LE i cant provide you a test binary

if so, install this ISAdaptive test build for Kodi 20:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1313/1/artifacts

then run the problematic stream, after video buffering problem you should find at least 2 manifests saved on ISA "manifests" folder

@L2501 your stream could have similar problem but i dont know without a full log and better dont confuse this thread with two problems then open a separate Issue, also because i tried use VPN with your manifest link but still protected i cant test it

**Comment by L2501** [comment]
Latest build live working again :+1:

**Comment by dapharsyde** [comment]
> can you test under Windows operative system or android? because on LE i cant provide you a test binary
> 
> if so, install this ISAdaptive test build for Kodi 20: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1313/1/artifacts
> 
> then run the problematic stream, after video buffering problem you should find at least 2 manifests saved on ISA "manifests" folder

Thanks for the test build.  I installed Kodi 20.2 on a Windows system with your test IA build and will provide the log file and manifests the next time I see this error occur on this channel.  In the meantime I've noticed the Hulu plugin regularly failing after ~5 minutes with [HTTP 410 errors](https://github.com/matthuisman/slyguy.addons/issues/488).  The RefreshLiveSegments errors usually happen in < 1 minute, so hopefully I will still be able to capture it the next time ESPN broadcasts this unsupported content.

**Comment by dapharsyde** [comment]
I think I was able to reproduce the RefreshLiveSegments error on Omega with the nightly build of IA.

Attached are the log file and manifest files.

[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/11956652/manifests.zip)

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11956650/kodi.log)

Update:  Actually I just noticed this is a different RefreshLiveSegments error - "Full update without start number".  I encountered it a few times on multiple channels, not just ESPN.  It seems to happen whenever switching between content and advertisements.  In case it's useful, here is another log file with manifests:

[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/11957084/manifests.zip)

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/11957087/kodi.log)

**Comment by CastagnaIT** [comment]
from the first log there is just a "Download failed, HTTP error 410" error
the "Full update without start number" are not errors are debug info

from the manifest i see that on `SegmentTemplate` there is `presentationTimeOffset` attribute that is currently not implemented on ISA maybe this could influence on this problem

**Comment by dapharsyde** [comment]
Thank you, the missing implementation of presentationTimeOffset must be the issue.  I tested it again now and when the issue occurs, the ad will start playing, but soon after playback jumps backwards and then it all falls apart.  Inspecting the manifests' timestamps, the stream works fine until presentationTimeOffset appears in them.  Is it necessary to create a separate issue for this or should we keep tracking it here?

**Comment by CastagnaIT** [comment]
yes if you can please open another Issue (you can also attach same relevant log/manifests)
so the problem its better understandable by other devs
because the discussion here is become a bit confusionary
when done you can close this one

**Comment by dapharsyde** [comment]
Thanks, I opened a different [issue ](https://github.com/xbmc/inputstream.adaptive/issues/1317)to track the missing implementation for presentationTimeOffset.  I'll close this issue for now, at least until I'm able to reproduce it again with the latest Omega build.
