### ISSUE TITLE
Video freezes

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1298]
### Describe the bug
The episode of Mentalist "le tueur le plus fort" from MYTF1 used in Catchuptvandmore plays for a few stops and then freezes.

## Expected Behavior
smooth streaming. No freeze

## Actual Behavior
Freeze of the video.

### To Reproduce

1.  With Catchuptvandmore plugin, -> replay->france->Mytf1->TMC->series>Mentalist->"le tueur le plus fort"
2. launch the video

Be careful. Link is geoblocked.

### Debuglog
[kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/11782376/kodi.txt)

### MPD/M3U8s/ISM
[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/11782377/manifest.txt)

### Your Environment
Used Operating system:
- [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.1 Nexus
 - inputstream.adaptive version: 20.3.6

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
please before try update ISA to last version 20.3.9 and give a feedback if problem still persist

**Comment by joaopa00** [comment]
Unfortunately, the lauchpad of Kodi is not updated anymore. Is there an easy way to install the latest IA in Ubuntu?

**Comment by CastagnaIT** [comment]
you need to use kodi official ~development~ ppa
https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

then
```
sudo apt-get update
sudo apt-get install kodi-inputstream-adaptive
```

**Comment by joaopa00** [comment]
Thank you. Indeed, that fixed the problem.
I close this bug report.
