### ISSUE TITLE
Only audio, no video

### ISSUE THREAD

**Issue by kevlare** [peak3d/inputstream.adaptive#1299]
### Describe the bug
Here is a clear and concise description of what the problem is:
When playing replay via catchuptvandmore from mytf1 there is a thumbnail and audio plays but no video playback.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Video is visible while audio plays.

## Actual Behavior
Audio plays but no video

### To Reproduce
1. With Catchuptvandmore plugin, -> catchuptv->france->Mytf1->TMC->infos,mag&sport>quotidien->extrait->any video
2. launch the video
Be careful. Link is geoblocked to France.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/esesominir.kodi

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://paste.kodi.tv/lexewivibo

### Screenshots 
Here are some links or screenshots to help explain the problem:
![16874181211987208350776229160871](https://github.com/xbmc/inputstream.adaptive/assets/99365449/20a91543-49ff-4ad2-a8a2-73202a1d714f)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android Version 11. Shield Android tv SW Version: 9.1.1(33.2.0.157)
 - Kodi version: 20.1
 - inputstream.adaptive version: 20.3.9

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
attached log has no debug, please attach a log with debug info

**Comment by kevlare** [comment]
Thank you, I updated the link.

**Comment by CastagnaIT** [comment]
can you test on Kodi 21?
and if the problem persist provide a debug log from kodi 21? thanks

**Comment by CastagnaIT** [comment]
closed as cleanup operation

**Comment by kevlare** [comment]
This is closed, which is ok.
If someone encounters the same problem, I solved it by uninstalling and reinstalling kodi and the add-on.
All settings were lost, but now it works.
