### ISSUE TITLE
HLS stream will play back fine from .strm file, but wont play from plugin addon

### ISSUE THREAD

**Issue by reinisb** [peak3d/inputstream.adaptive#131]
Hi,

I am running the latest Leia v18 nightly containing inputstream.adaptive v2.2.6. Moreover, as the title states, when I attempt to play back a HLS stream via a .strm file, then inputstream.adaptive successfully plays back the stream. However, when I attempt to play back the same stream via a simple kodi plugin, it fails to start playing the stream. More specifically, in the kodi.log the failure seems to be the following line:
`WARNING: OpenStream - Unsupported stream 1. Stream disabled.`

Here is how I attempt to play the video in the plugin:
```
def play_channel():
    utils.log("Attempting to play a channel!")

    try:
        params_str = sys.argv[2]
        params = utils.get_url(params_str)
        data_url = params['data_url']

        hls_url = api.get_stream_url(data_url)
        utils.log("Got channel HLS stream URL:"+hls_url)
        utils.log("Now attempting to play the HLS stream URL...")

        playitem = xbmcgui.ListItem(path=hls_url)
        playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
        playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
        playitem.setMimeType('application/dash+xml')
        playitem.setContentLookup(False)
        xbmcplugin.setResolvedUrl(_handle, True, playitem)

    except:
        d = xbmcgui.Dialog()
        msg = utils.dialog_error("Unable to fetch listing")
        d.ok(*msg)
        utils.log_error()
```

Finally, here are the logs. You can see that the attempts to play the hls stream have almost identical steps in both cases, except that plugin case fails.
(1) Attempt to play stream from .strm file - success
[log_with_strm_file.log](https://github.com/peak3d/inputstream.adaptive/files/1832547/log_with_strm_file.log)

(2) Attempt to play stream from kodi plugin - failure
[log_with_plugin.log](https://github.com/peak3d/inputstream.adaptive/files/1832546/log_with_plugin.log)

**Comment by enen92** [comment]
@reinisb when you set the mimetype directly in the listitem Kodi will not lookup for it. In hls streams the mimetype is usually `application/vnd.apple.mpegurl` and not `dash+xml`.

You can easily find this in the log for the strm playback:

`DEBUG: CCurlFile::GetMimeType - https://str7t2e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=iq4TCIJiHWuF3Urz3Yk%2FddqPcJEfnp6Fjr4FWH28zFKCayTihmIahCyxUu4uXZ71m%2BZxfYIeLrcBPLzGppsuNgIZ3WIj4iGT -> application/vnd.apple.mpegurl` 

Try setting the correct mimetype or remove the instruction that forces the mimetype

**Comment by reinisb** [comment]
@enen92 Thanks for the tip. I tried both, but it still will not play the stream.

Here are the new logs (it seems that they are identical):
[without_mimetype_line.log](https://github.com/peak3d/inputstream.adaptive/files/1834810/without_mimetype_line.log)
[with_mimetype_applempegvid.log](https://github.com/peak3d/inputstream.adaptive/files/1834811/with_mimetype_applempegvid.log)

And just in case - here is the main python file of the kodi plugin:
```
import xbmc
import xbmcaddon
import xbmcgui
import xbmcplugin
import os
import sys
import json

# Add our resources/lib to the python path
try:
    current_dir = os.path.dirname(os.path.abspath(__file__))
except:
    current_dir = os.getcwd()

sys.path.append(os.path.join(current_dir, 'resources', 'lib'))

#import utils, categories, series, programs, play
import utils
import api


# Capture the addon's handle - need this to provide this in calls to xbmc so that xbmc would know who's calling!
_handle = int(sys.argv[1])


utils.log('Plugin initialised!')


def make_channel_list():

    utils.log("Attempting to create the channel list. First will attempt to login and retrieve channel info...")

    try:
        # channels tiek saglabata visa informacija par lattelecom kanaliem un taalaak kanaali pa vienam tiek ievietoti listee,
        # kas tiek atgriezta make_channel_list funkcijas beigaas! get_channels ielogojas lattelecomaa un savaac visu info
        # par kanaaliem!
        channels = api.get_channels()
        utils.log("Here is the full channels dictionary:")
        utils.log(json.dumps(channels, indent = 10))

        utils.log("Login as well as channel info retrieveal is successful! Now creating the channel list...")

        ok = True
        for c in channels:

            listitem = xbmcgui.ListItem(label=c['name'])
            listitem.setInfo('video', { 'title': c['name'] })
            listitem.setIconImage('https://manstv.lattelecom.tv/'+c['logo'])
            listitem.setThumbnailImage('https://manstv.lattelecom.tv/'+c['thumb'])
            listitem.setProperty('IsPlayable', 'true')

            ## Build the internal URL for the program, including the list_info
            url = "%s?play=true&data_url=%s" % (sys.argv[0], c['id'])
            utils.log("Adding the following channel internal URL to the channel list: "+url)

            # Add the program item to the list
            ok = xbmcplugin.addDirectoryItem(handle=_handle, url=url, listitem=listitem, isFolder=False, totalItems=len(channels))

        # tell kodi as what type of content the items need to be displayed like! It can be files, videos, movies, episodes, tvshows, etc.
        xbmcplugin.setContent(handle=_handle, content='videos')

        # tell kodi that I am done here with creating the list!
        xbmcplugin.endOfDirectory(handle=_handle, succeeded=ok)
        utils.log("Finished creating the channel list!")


    except:
        d = xbmcgui.Dialog()
        msg = utils.dialog_error("Something went wrong with creating the channel list! Check the log!")
        d.ok(*msg)
        utils.log_error()


def play_channel():

    utils.log("Attempting to play a channel! First getting channel HLS stream URL...")

    try:
        # sheit no sys.argv[2] tiek nolasiti parametri, ar kuriem tika ieladets plugins (atceries, ka katrs Enter laizh pluginu no jauna -
        # ja enter nospieda uz kaada no kanaaliem, tad tika atverts ieksheejais kanaala kodiURL, kuram beigaas ir shie divi parametri, kas
        # ir saglabaati ieksh sys.argv[2]).
        params_str = sys.argv[2]

        # taalaak nakamas divas rindas attira params_str, lai tajaa paliktu tikai data_url vertiba
        params = utils.get_url(params_str)
        data_url = params['data_url']

        # visbeizot balstoties uz data_url vertibu (piemeram, LTV1 taa ir "101"), tiek atgriezts stream URL un pieglabaats kaa hls_url.
        hls_url = api.get_stream_url(data_url)
        # izprinteeju stream URL
        utils.log("Successfuly got the following channel HLS stream URL:"+hls_url)
        utils.log("Now attempting to play that HLS stream URL...")

        # taalaak to stream url ir vienkarshi jaatskanjo!

# Orginaalais veids (ffmpeg)
#        listitem=xbmcgui.ListItem(label="video")
#        xbmc.Player().play(rtmp_url, listitem)


#Jaunais veids (ar inputstream.adaptive)
        playitem = xbmcgui.ListItem(path=hls_url)
        playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
        playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
#        playitem.setMimeType('application/vnd.apple.mpegurl')
        playitem.setContentLookup(False)
        xbmcplugin.setResolvedUrl(_handle, True, playitem)

    except:
        d = xbmcgui.Dialog()
        msg = utils.dialog_error("Unable to fetch listing")
        d.ok(*msg)
        utils.log_error()



if __name__ == '__main__':
    # About Kodi plugins. When a user clicks on a folder, kodi will run the plugin again to retrieve another listing.
    # If a file is clicked, kodi will either play the file directly or call the addon to retrieve a playable url.
    # Manaa gadijumaa, nospiezhot enter uz kaada no sarakstaa uzgenereetajiem kanaaliem, tiek atveerts kanaala ieksheejais
    # kodi URL ar parametriem (piemeram, plugin://lattelecomtv/?play=true&data_url=101). Tas nozime, ka
    # plugins laizhas velreiz un tieshi zemak esoshajaa skripta sadaljaa tiek konstatets ka ieksheejaa koduURL
    # ir parametrs ar nosaukumu(key) play, tapec aiziet funkcija play_channel, kas taalaak peec kanaala id
    # dabuu patiesu striima URL un saak taa atskanoshanu! Simple - galvenais ir saprast logjiku kaa straadaa kodi plugini.

    utils.log("Plugin handle (line below):")
    utils.log(_handle)

    params_str = sys.argv[2]
    utils.log("Here is the parameters string (line below):")
    utils.log(params_str)

    # uztaisa dictionary params no params_str.
    params = utils.get_url(params_str)
    utils.log("Here is the parameters dictionary (line below):")
    utils.log(json.dumps(params, indent = 10))

    # Pirmajaa reizee startejot pluginu params dictionary bus tukshs, tapec ari nostradas nakamais if un palaidis
    # funkciju make_channel_list, kas uzgenerees kanaalu sarakstu!
    if (len(params) == 0):
        make_channel_list()
    elif params.has_key("play"):
        play_channel()

    else:
        utils.log("Unknown url: " + sys.argv[0])
```

**Comment by enen92** [comment]
Well by downloading the playlist you can check it is a single playlist and not a multi-birate one. According to https://github.com/peak3d/inputstream.adaptive/issues/64#event-1514739058 only multi-bitrate playlists were supported. Since the issue was closed a few days ago I've no idea what the current state is.
Cheers

**Comment by reinisb** [comment]
@enen92 Yes - the playlist.m3u8 file contains only a single bitrate and chunklist URL. I also read that only multi-bitrate hls ir supported, but how come the same playlist.m3u8 works fine via a .strm file and doensn’t work via plugin. Are these use cases handled differently by inpitstream.adaptive?

Thanks

**Comment by enen92** [comment]
Just tried it from a strm file on last nightly build and it does not play (same behaviour as the through a python script):

```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
http://str4e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=app_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MTg1OTQxODQsImV4cCI6MTUyMTcwNDY0NCwidXNlcl9pZCI6MTY4MjAxLCJyaWdodHMiOnsid2VidHYiOnRydWUsInZvZCI6ZmFsc2UsIm1hamFzX3ZpZGUiOnRydWV9LCJ1aWQiOiJkNDRhODk4MGE1ZGMyZTViIn0.IDRL6RJ0u4eaH5OyK8CN_DnNgPOUKCs5cJhBQ9KVRrQ
```

The strm only plays when not using inputstream, i.e using ffmpeg directly

**Comment by reinisb** [comment]
@enen92 For me the stream plays perfectly fine through inputstream.adaptive from the .strm file (I can see it in the logs - no ffmpeg, only inputstream.adaptive).

Also, that stream URL should not work for you as it is geoblocked to Latvia. Does it really work for you or was it an assumption?

@peak3d - any comments on the original topic would be appreciatedz

**Comment by peak3d** [comment]
For what country is the geolock?

**Comment by reinisb** [comment]
I think that the authtoken had expired. I got a new token. Here is the new HLS stream URL:
https://str12e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=rPOCIfoXYPBDv9F1qQEgTCTv4hDEBDTlfnSfkVv24jX7vtNrxpNAQdsE0GPuIW%2BAumXAEDphCYzZl4uKWyj6OBg3OaEezamk

In case it is not possible to download that playlist.m3u8 given your location, here are its contents:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3153700,CODECS="avc1.100.30,mp4a.40.2"
chunklist_w1541902963.m3u8?resource_id=c-ltv1&auth_token=rPOCIfoXYPBDv9F1qQEgTCTv4hDEBDTlfnSfkVv24jX7vtNrxpNAQdsE0GPuIW%2BAumXAEDphCYzZl4uKWyj6OBg3OaEezamk
```

**Comment by enen92** [comment]
@reinisb it worked for me in VLC and kodi (without input stream). Sorry I can’t help more.

**Comment by reinisb** [comment]
@enen92 , @peak3d - alright, I think I figured out the cause of the problem. I still do not know the solution, though. So, here's  the deal - I think that the problem lies within inpustream.adaptive interpreting the token part of an URL.

In my case the same content provider provides two slightly different URLs - one is for its web player, and the other is for its iOS app. Previously I was using them interchangeably, but now I realised that it was a mistake. Sorry about that.

The first URL plays back perfectly fine everywhere (!) - Safari, VLC, kodi-ffmpeg AND kodi-inputstream.adaptive (both via .strm file and kodi plugin):
https://str4e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=RIUb2GsdMe5%2BPNlhHcgdoW%2B%2B3nZZSuhm2jT87tn5joJjldFiiHg1CKhxuRqDSl9xcQVeI8gtbpLrj1l%2BPXN0eV34Gqu4pyfu


However, the second URL (which I want to use in the kodi plugin with inputstream.adaptive) plays back fine in Safari, VLC, kodi-ffmpeg, BUT fails to play back via kodi-inputstream.adaptive (both via .strm file and plugin):
https://str7t2e.lattelecom.tv/live/mp4:ltv1_lv_hq.stream/playlist.m3u8?resource_id=c-ltv1&auth_token=app_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjE3MjU2OTUsImV4cCI6MTUyNDgzNjE1NSwidXNlcl9pZCI6MTY4MjAxLCJyaWdodHMiOnsid2VidHYiOnRydWUsInZvZCI6ZmFsc2UsIm1hamFzX3ZpZGUiOnRydWV9LCJ1aWQiOiIyODlkMzEzMDgwODMzNWQ1In0.XzEYYfG84RivMg1IUVHv4qaoj8hta8uNOjXUZpWnv00

It seems that the only notable difference between these two URLs is the token! It seems that every player (incl. ffmpeg) knows how to deal with the token part of the second URL, but inputstream.adaptive does not. Could it be that the dots "." in the token are causing the issue? Or perhaps the length of the token?

Looking forward to your input - thanks!

**Comment by peak3d** [comment]
@reinisb https://github.com/peak3d/inputstream.adaptive/commit/b2965bd3a67445983ef4d06b2288c7bb5e6d8004

fixes the issue. Thx for reporting / providing all the samples and logs.

**Comment by reinisb** [comment]
Thanks for the quick fix! Will try again tomorrow once it is released with the new kodi nightly.

**Comment by reinisb** [comment]
PS Perhaps a silly question - how can I manually install the newest version of the inputstream.adaptive binary addon? I found this but I'm not sure how to use it in this case: https://github.com/xbmc/repo-binary-addons

**Comment by peak3d** [comment]
You have to git clone kodi, git clone this repo and build the addon (using cmake)
It's a pain, so if binary addon compiling is not your daily business, wait until tomorrow for the nightly

**Comment by reinisb** [comment]
It's definitely not my daily business so I will wait for tomorrow's nightly for my macOS. However, my main streaming device is Raspberry Pi 3 B+ running OSMC Kodi 17.6 and inputstream.adaptive v2.0.19. I guess I would need to do the compiling to get the latest inputstream.adaptive on my Kodi 17.6, right?

Thanks once more!

**Comment by reinisb** [comment]
I just now installed the latest kodi v18 nightly containing inputstream.adaptive v2.2.8 and I can confirm that now my URLs work perfectly fine! Thanks a lot for the fix!

Moreover, it would be absolutely fantastic in you could backport the minor inputstream.adaptive fixes to Krypton when you have the time! Thanks

**Comment by reinisb** [comment]
I am closing this now as the issue has been fixed. Moreover, @peak3d - it would be great if you could backport those minor fixes to Krypton branch. Thanks!

**Comment by reinisb** [comment]
@peak3d thanks! I removed v18 from my macOS (incl settings files) and installed a fresh copy of v17.6 (which includes inputstream.adaptive v2.0.19), but it seems that the backported changes are not there as it is still v2.0.19 and my special token URLs won'y play. I guess I need to do some extra steps, right? "You have to git clone kodi, git clone this repo and build the addon (using cmake)"? 

Thanks!
