### ISSUE TITLE
IA 21 regression - No audio

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1319]
Slyguy -> 9now -> featured > the ashes test cricket > select any
issue: no audio

Works ok in Kodi 20

Addon is a Australia addon so @glennguy should be able to test easily :)

[manifest_1688892723_master.txt](https://github.com/matthuisman/slyguy.addons/files/11994792/manifest_1688892723_master.txt)
[manifest_1688892724_child-audio.txt](https://github.com/matthuisman/slyguy.addons/files/11994793/manifest_1688892724_child-audio.txt)
[manifest_1688892724_child-video.txt](https://github.com/matthuisman/slyguy.addons/files/11994794/manifest_1688892724_child-video.txt)
[kodi.log.txt](https://github.com/matthuisman/slyguy.addons/files/11994795/kodi.log.txt)

**Comment by glennguy** [comment]
Thanks Matt!
Looks like file container detection is not happening correctly here

**Comment by CastagnaIT** [comment]
yeah good catch forced forced TS to #1308 audio now works
therefore its same problem on both issues

**Comment by CastagnaIT** [comment]
please test #1321

**Comment by matthuisman** [comment]
@CastagnaIT yes, that PR fixes the audio. thank you
