### ISSUE TITLE
Live ism streams are broken since version 21.1.1

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1324]
### Describe the bug
Here is a clear and concise description of what the problem is:

The live streams which use ism manifests in the [plugin.video.orange.spain](https://github.com/Paco8/plugin.video.orange.spain) addon are not working since inputstream adaptive 21.1.1.

With some tv channels there's only audio, no video. With other channels there's audio only for some seconds, then there's video for some seconds (no audio) and then playback stops.

It works correctly with inputstream adaptive 21.1.0.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The tv channels should play correctly, with video and audio.

## Actual Behavior

Only audio or audio for some seconds, then video for some seconds, then stops.

### To Reproduce

I can't provide a strm to test, because the token expires after 2 minutes.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/erivezazej.kodi

In that log I play two tv channels, the first one plays audio only, the second one plays audio for some seconds, then video for some seconds, then stops.

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/12015066/manifests.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: 21.0-ALPHA2
 - inputstream.adaptive version: 21.1.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
have you tested current nightly?
if not, you can try use these builds
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1323/2/artifacts

**Comment by Paco8** [comment]
I'm afraid the problem is still present in that build.

**Comment by CastagnaIT** [comment]
~there can be more problems
first try this test build
[inputstream.adaptive-android-armv7-omega-30cd8ec_1.zip](https://github.com/xbmc/inputstream.adaptive/files/12025532/inputstream.adaptive-android-armv7-omega-30cd8ec_1.zip)~

if you dont see improvements, provide a log of same video played with last working isa build and the nightly build

EDIT: i think i made a wrong change in the test build here, dont try it, but if you can please provide log comparison

**Comment by Paco8** [comment]
This is the log using inputstream.adaptive 21.1.0 (working):
https://paste.kodi.tv/qexajojale.kodi

This streaming platform also have VOD videos using ism manifests, those videos are not affected by the problem. I attach one of those manifests, maybe you can find something different.

[tvshow_manifest.zip](https://github.com/xbmc/inputstream.adaptive/files/12028103/tvshow_manifest.zip)

**Comment by CastagnaIT** [comment]
can you test this build and let me know if there are differences? [inputstream.adaptive-android-armv7-omega-f2e0f85_1.zip](https://github.com/xbmc/inputstream.adaptive/files/12035958/inputstream.adaptive-android-armv7-omega-f2e0f85_1.zip)
its not a fix but help me understand from what point of code is broken

request aside, which has nothing to do with the problem
i see that `QualityLevel` tag have `FrameRate` attribute value in this case "25"
do you know if there is videos with "23,976"?

**Comment by Paco8** [comment]
I can't see any difference. This is the log:
https://paste.kodi.tv/ewopetamej.kodi

I realized that with some channels playback doesn't even start, you can see this in the log:

```
2023-07-13 09:20:03.588 T:10790   debug <general>: AddOnLog: inputstream.adaptive: Download finished: http://live-mss-ntc.cdns.cdn.orangetv.orange.es/l9s2QW0MJsX401BQibOUmA/1689319203/64842925/113311744/2032/ss/r1_paramount/mss_high.isml/manifest (downloaded 4732 byte, speed 7710091.58 byte/s)
2023-07-13 09:20:03.588 T:10790   error <general>: AddOnLog: inputstream.adaptive: ParseManifest: Protection header with a SystemID not supported or not implemented.
2023-07-13 09:20:03.588 T:10790    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 3, Type: live)
2023-07-13 09:20:03.588 T:10790   error <general>: AddOnLog: inputstream.adaptive: InitializePeriod: Unhandled encrypted stream.
```

However that channel plays fine with version 21.1.0, see the log:
https://paste.kodi.tv/uhetapizam.kodi

[paramount_manifest.zip](https://github.com/xbmc/inputstream.adaptive/files/12037701/paramount_manifest.zip)


> request aside, which has nothing to do with the problem i see that `QualityLevel` tag have `FrameRate` attribute value in this case "25" do you know if there is videos with "23,976"?

I think all streams in this platform play at 25 fps.

**Comment by CastagnaIT** [comment]
thanks, i found this free stream that have video broken
suspect same problem of one of your stream
should help to investigate to find the regression
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=ism
https://gstv-tnz-gsmediastreaming.preview-jpea.channel.media.azure.net/dfd06b62-e9d1-4a7f-bcbb-89d2ecbc82ee/preview.ism/manifest
```

> Protection header with a SystemID not supported or not implemented

for this one i found the cause

**Comment by CastagnaIT** [comment]
i dont know if fixes all your cases
anyway this is the new test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1325/1/artifacts

if you will find some other videos broken, please add log+manifest as usual
so to avoid confusion with previous problems

**Comment by Paco8** [comment]
It's a progress, now there's audio and video, but in many channels playback freezes after some seconds.

This channels freezes but also the audio is out of sync:
https://paste.kodi.tv/cirikibozo.kodi

Working:
https://paste.kodi.tv/uviqazupuh.kodi

[la2_manifest.zip](https://github.com/xbmc/inputstream.adaptive/files/12040030/la2_manifest.zip)

**Comment by CastagnaIT** [comment]
new test build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1325/3/artifacts
let me know

**Comment by Paco8** [comment]
So far all live channels I tested work fine with this build.

However I noticed that catchup videos won't play. I'll send the logs and the manifest later.

**Comment by Paco8** [comment]
This manifest won't play:
[catchup_manifest.zip](https://github.com/xbmc/inputstream.adaptive/files/12053530/catchup_manifest.zip)

Log:
https://paste.kodi.tv/ayupipivij.kodi

Working with 21.1.0:
https://paste.kodi.tv/vafisiqeja.kodi

**Comment by CastagnaIT** [comment]
this is a drm playready VOD stream not live
i tried compare manifest parsing between the two isa versions, but i havent found nothing
the only different thing i can see its on the log that there is a different base url more likely due to a different cdn server

maybe @glennguy can have some idea why HTTP error 403 happen?

**Comment by CastagnaIT** [comment]
@Paco8 can you provide new logs of same vod stream, but this time by enabing in the kodi logging settings, the specifics component CURL? maybe we can see something useful in the http request data

**Comment by Paco8** [comment]
Working:
https://paste.kodi.tv/yoluhivaju.kodi

Not working:
https://paste.kodi.tv/fipiwarotu.kodi

Notice that there's a missing "$" in the fragment urls:

Correct:
`http://cdvr-mss.cdns.cdn.orangetv.orange.es/Ft0bcroYWLIWZ8nm0eYQig/1689508816/64842925/113311744/777058438/shss/LIVE$1010/2.ism/S!d2EIbXNzX2hpZ2gSAkN4hWPJRAC0Y8kWBGoHFmG0IL4EPJ8_/QualityLevels(5452595)/Fragments(video=0)`

Incorrect:
`http://cdvr-mss.cdns.cdn.orangetv.orange.es/GHFXMjQk2hmB3aOuvjyllw/1689508568/64842925/113311744/777058438/shss/LIVE1010/2.ism/S!d2EIbXNzX2hpZ2gSAkN4hWPJRAC0Y8kWBGoHFmG0IL4EPJ8_/QualityLevels(5452595)/Fragments(video=0)`

**Comment by CastagnaIT** [comment]
i think i have found the cause i will let you know soon

**Comment by CastagnaIT** [comment]
now should be all fine
new test build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1325/7/artifacts

**Comment by Paco8** [comment]
Yes, the problem seems fixed.
