### ISSUE TITLE
Fail to build with GCC-13

### ISSUE THREAD

**Issue by marillat** [peak3d/inputstream.adaptive#1332]
Fail to build with gcc-13, debian unstable, amd64, gcc version 13.1.0

I still don't know how to do a pr when several files are modified.
```
--- a/src/SSD_dll.h
+++ b/src/SSD_dll.h
@@ -10,6 +10,7 @@
 
 #include <stdarg.h> // va_list, va_start, va_arg, va_end
 #include <string_view>
+#include <cstdint>
 
 //Functionality wich is supported by the Decrypter
 class Adaptive_CencSingleSampleDecrypter;
--- a/src/Iaes_decrypter.h
+++ b/src/Iaes_decrypter.h
@@ -11,6 +11,7 @@
 #include <bento4/Ap4Types.h>
 
 #include <string>
+#include <cstdint>
 
 class IAESDecrypter
 {
@@ -31,4 +32,4 @@ public:
 
 private:
   std::string m_licenseKey;
-};
\ No newline at end of file
+};
--- a/src/common/ChooserDefault.cpp
+++ b/src/common/ChooserDefault.cpp
@@ -16,6 +16,7 @@
 #include <cmath>
 #include <numeric>
 #include <string_view>
+#include <cstdint>
 
 using namespace adaptive;
 using namespace CHOOSER;
--- a/src/utils/PropertiesUtils.h
+++ b/src/utils/PropertiesUtils.h
@@ -11,6 +11,7 @@
 #include <map>
 #include <string>
 #include <utility>
+#include <cstdint>
 
 namespace UTILS
 {
--- a/src/utils/FileUtils.h
+++ b/src/utils/FileUtils.h
@@ -10,6 +10,7 @@
 
 #include <string>
 #include <string_view>
+#include <cstdint>
 
 namespace UTILS
 {
--- a/src/utils/StringUtils.h
+++ b/src/utils/StringUtils.h
@@ -11,6 +11,7 @@
 #include <string>
 #include <string_view>
 #include <vector>
+#include <cstdint>
 
 namespace UTILS
 {
--- a/src/test/KodiStubs.h
+++ b/src/test/KodiStubs.h
@@ -12,6 +12,7 @@
 
 #include <string>
 #include <vector>
+#include <cstdint>
 
 #ifdef _WIN32 // windows
 #if !defined(_SSIZE_T_DEFINED) && !defined(HAVE_SSIZE_T)
--- a/src/utils/Utils.h
+++ b/src/utils/Utils.h
@@ -12,6 +12,7 @@
 #include <string>
 #include <string_view>
 #include <vector>
+#include <cstdint>
 
 namespace UTILS
 {
```

**Comment by bkuhls** [comment]
Please try https://github.com/xbmc/inputstream.adaptive/pull/1336, I am using it with buildroot for several weeks now: https://patchwork.ozlabs.org/project/buildroot/patch/20230507214317.409305-3-bernd.kuhls@t-online.de/

**Comment by marillat** [comment]
My patch add the same fixes for two more files, needed if build with -DBUILD_TESTING=ON
```src/common/ChooserDefault.cpp```
```test/KodiStubs.h```

**Comment by CastagnaIT** [comment]
@bkuhls are you willing to build ISA with @marillat request and make a new PR for required chages? i dont have a platform to test with GCC13

**Comment by glennguy** [comment]
Maybe also a good idea to add building with GCC 13 to GitHub actions? Haven't tried myself but from what I understand Ubuntu 23.04 should support this

**Comment by marillat** [comment]
As GCC 13 is the default compiler version for Debian, Ubuntu will do the same soon.

**Comment by CastagnaIT** [comment]
Some time ago i asked on slack they said that worth waiting for when it becomes official with existing CI's,
seem that ubuntu 23 its not available on github actions

**Comment by bkuhls** [comment]
> My patch add the same fixes for two more files, needed if build with -DBUILD_TESTING=ON `src/common/ChooserDefault.cpp` `test/KodiStubs.h`

Cross-compiling with
```
-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
```
creates
```
ChooserDefault.cpp.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```
without any further patches. Does this file really need to be patched?
And since I am only cross-compiling I cannot test a test build:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/CMakeLists.txt#L201

**Comment by CastagnaIT** [comment]
I assume it is sufficient
when we will have GCC13 on CI we will can take care better
