### ISSUE TITLE
Flickering and artifacts with PVR

### ISSUE THREAD

**Issue by numbernumero** [peak3d/inputstream.adaptive#1334]
### Describe the bug
Here is a clear and concise description of what the problem is:

- When change the channels in Simple PVR Client flickering and artifact at the start for few seconds.
- If you change the channels repeatedly with an interval of a few seconds after a while kodi (LibreELEC) freezes and starts again by itself

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

must be fluid without artifact and flickering and not crash while change channels 

## Actual Behavior

When you change the channels repeatedly from the list in the first few seconds there are various flickers and artifact.
Also if you change the channels repeatedly after a while  it freezes and restarts by itself

## Possible Fix

a new release of inputstream

### To Reproduce

1.  Load a list of m3u channel in Libreelec 11.0.3 with PVR Simple Client
2 . Change the channels repeatedly  in PVR Simple Client it will crash and restart by it self
3. You can reproduce the issues also with Zattoo PVR Client

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/mofaqomowe.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux LibreELEC 11.0.3 on Intel NUC 7i3
 - Kodi version: LibreELEC 11.0.3 (NEXUS)
 - inputstream.adaptive version: 20.3.9.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by numbernumero** [comment]
In all versions of LibreELEC 11 even in the latest 11.0.3, All addons related to inputstream seem to have flickering, crash problems and artifacts. Example: When you start a channel from the list in the first few seconds there are various flickers. This happens especially as soon as the PVR is opened. I also tried with Zatto Pvr Client and the problem is the same, in the first seconds when you start a channel freezes and flickers. It will also crash if you change the channels repeatedly with an interval of a few seconds and restarts again by itself
I did other tests in Kodi 20.2 in both Windows 11 and Android and on these operating systems everything works normally.
I also tried Libreelec 12 Nightly (20230716) and in this case there continue to flicker but much less than in Libreelec 11
All tests were carried out on an Intel NUC i3 generation 7 & 8 with 4GB of memory and SSD and with Skin Estuary (Default).

**Comment by numbernumero** [comment]
I just do an other test with with Libreelec 12 Nightly (20230716) and confirm that flickering or artifact appear but much less than Libreelec 11. If you change the channels repeatedly with an interval of a few seconds after a while even LibreELEC 12 freezes and starts again by itself

**Comment by codingPF** [comment]
I do not see any flickering but do experience random crash on channel switch for LibreELEC 11 / RP3 / Zattoo IPTV

**Comment by numbernumero** [comment]
I solved the problem of flickering thanks to a meticulous setting in Libreelec but the problem of the crash unfortunately remains

**Comment by numbernumero** [comment]
The problem of crashing is always present when you change channels in succession after a while crashes and starts again by itself.

**Comment by CastagnaIT** [comment]
since has been opened a new Issue for crash case #1362
please add on that issue thread the debug log
also because the log provided here has debug logging disabled

i close this issue since flickering is a external problem
