### ISSUE TITLE
Issue viewing BBC UHD iPlayer channels 

### ISSUE THREAD

**Issue by L162LZ** [peak3d/inputstream.adaptive#1337]
### Describe the bug
Here is a clear and concise description of what the problem is:

 I'm trying to setup the 5 BBC UHD channels (Not 24/7) to work through Kodi simple IPTV Client. The M3U file works perfectly using VLC player but doesn't work properly via Kodi. Is this a restriction of BBC/iPlayer that only supports VLC as a player or is there some trick/tweak to get them to work in Kodi?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I should select a channel that is currently transmitting (BBC UHD 5 at moment) from my channel list and it should play continuously

## Actual Behavior

I select the channel, it will always initially play, although sometimes it does not get the correct 4k resolution initially and I have to stop/start again. The stream will work for 14 to 15 seconds and then freezes. The kodi menu appears at the bottom but will stay like this until I stop/start the stream again. It always starts again but will just last 14 to 15 seconds before the picture freezes again and I have to stop/start again....

### To Reproduce

1.  Add line up in M3U file listed below. This is geolocked to UK I believe
2. Test M3U file in VLC player to make sure it works in your location and see which BBC UHD channels are currently tranmitting 
3. Select a working channel in Kodi and try to play it

### Debuglog

The debuglog can be found here: 

https://paste.kodi.tv/uzojiqamug.kodi

### MPD/M3U8s/ISM

#EXTM3U
#EXTINF:0,BBC UHD 1
https://ve-uhd-push-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:uhd_stream_01/iptv_uhd_v1.mpd
#EXTINF:0,BBC UHD 2
https://ve-uhd-push-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:uhd_stream_02/iptv_uhd_v1.mpd
#EXTINF:0,BBC UHD 3
https://ve-uhd-push-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:uhd_stream_03/iptv_uhd_v1.mpd
#EXTINF:0,BBC UHD 4
https://ve-uhd-push-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:uhd_stream_04/iptv_uhd_v1.mpd
#EXTINF:0,BBC UHD 5
https://ve-uhd-push-uk-live.akamaized.net/x=3/i=urn:bbc:pips:service:uhd_stream_05/iptv_uhd_v1.mpd

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows 11 22h2 ver 22621.1992 (fully updated/patched)
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2
 - inputstream.adaptive version: 20.3.11

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i have no way to test your case from my country, VPN also dont helps
i see that its downloads dont works, this could be a dash live update problem that could be already solved on Kodi 21

first thing suggest you to test on Kodi 21 with last ISAdaptive 21.1.3 and give a feedback
if still dont works on Kodi 21, please attach kodi 21 debug log and the manifest files:
https://github.com/xbmc/inputstream.adaptive/wiki/Dev.-FAQ#how-to-get-downloaded-manifests-files

**Comment by L162LZ** [comment]
Thanks I've tried with latest nightly of Kodi v21 as suggested and v21.1.3 of ISAdaptive, That works perfectly. Do you know if whatever has changed in Kodi V21 will be imlemented in V20. I dont normally switch to a new Kodi version on the main TV until its at least at Beta release? 
Cheers Dave

**Comment by CastagnaIT** [comment]
on v21 there are many big changes that cannot be backported
even thinking about doing a partial backport takes too much time
more likely no one will make this commitment
now we are focused to improve on v21 only

**Comment by glennguy** [comment]
same here with VPN - the response is slightly different but it won't allow to download.

Do you get the same result in Kodi 20 if you change the IA settings to ask for quality and then choose the 4k one when you play?

**Comment by L162LZ** [comment]
> same here with VPN - the response is slightly different but it won't allow to download.
> 
> Do you get the same result in Kodi 20 if you change the IA settings to ask for quality and then choose the 4k one when you play?

I updated the main PC/display to Kodi v21 to get round the problem. Just tested on one of my other clients that are still on v20 and yes I get the same issue if I set IA to "ask for quality" and choose 4k from the list

**Comment by CastagnaIT** [comment]
closed no more backports, developments are starting for Kodi 22
