### ISSUE TITLE
HLS stream crashes master - Inputstream 2.2.8

### ISSUE THREAD

**Issue by sarbes** [peak3d/inputstream.adaptive#134]
The following streams will crash the current master:
https://mdrevent1hls-lh.akamaihd.net/i/livetvmdrevent1_ww@513989/master.m3u8
https://mdrevent2hls-lh.akamaihd.net/i/livetvmdrevent2_ww@513991/master.m3u8
https://mdrevent3hls-lh.akamaihd.net/i/livetvmdrevent3_ww@513991/master.m3u8

**Comment by peak3d** [comment]
@sarbes can we close this?
