### ISSUE TITLE
Many subtitle fragments in ism manifests are skipped

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1341]
### Describe the bug
Here is a clear and concise description of what the problem is:

The VOD videos from [plugin.video.orange.spain](https://github.com/Paco8/plugin.video.orange.spain) use ism manifests with fragmented ttml subtitles. There's one fragment for every 2 seconds.

From time to time but very often Kodi skips one of those fragments (it's downloaded but from some reason it's not displayed).
If I rewind some seconds just after this happened maybe then the fragment is displayed.

This happens in all versions of Kodi, from 18 to 21, and all operating systems.

I think it has to do with the timestamps. If (using a proxy) I modify the last digit of the timestamps with a random number then the fragments are not skipped.

There's a easy way to test the problem. If I replace the original texts in the fragments with this:
```
<p begin="00:00:00.000" end="00:00:02.000">Hello World</p>
```

it should display "Hello World" during all video, right? But it doesn't. It displays the text for 2 seconds, then it displays nothing for 2 seconds, the it displays the text for 2 seconds, then it displays nothing...

For some reason in this case it displays the even fragments but not the odd ones.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Some fragments are not displayed on screen.

## Actual Behavior

All fragments should be displayed.

### To Reproduce

I couldn't find a free stream to reproduce the issue, and I'm afraid I can't provide either a strm to test because the token expires after 2 minutes. However, if you need to play a video to see the problem, I think I can provide you with a cookie file for the addon. Write me to mitvbox.spain at gmail dot com

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kifuretato.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifest.zip](https://github.com/xbmc/inputstream.adaptive/files/12173654/manifest.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I attach all subtitle fragments from an episode.

[fragments.zip](https://github.com/xbmc/inputstream.adaptive/files/12173660/fragments.zip)

During the first 11 minutes (I didn't test any further) the following fragments are not shown:
```
49:
    <div>
      <p begin="00:00:00.000" end="00:00:02.000" region="bottomCenter">Si me matas, cerrarás el portal.</p>
    </div>

88:
    <div>
      <p begin="00:00:00.000" end="00:00:01.000" region="bottomCenter">No lo entiendo.</p>
    </div>

91:
    <div>
      <p begin="00:00:00.000" end="00:00:01.280" region="bottomCenter">a mi familia.</p>
      <p begin="00:00:01.600" end="00:00:02.000" region="bottomCenter">No estoy orgulloso de aquello,</p>
    </div>

93:
      <p begin="00:00:00.000" end="00:00:01.880" region="bottomCenter">
        pero no me arrepiento
        <br/>
        de lo que hice.
      </p>

123:
      <p begin="00:00:00.000" end="00:00:01.360" region="bottomCenter">
        Prométeme
        <br/>
        que cumplirás la profecía.
      </p>

176:
      <p begin="00:00:00.000" end="00:00:01.120" region="bottomCenter">Eres Karric Unger,</p>
      <p begin="00:00:01.560" end="00:00:02.000" region="bottomCenter">
        Acólito del Santuario
        <br/>
        en el Paso de Cadrian.
      </p>
    </div>

208:
      <p begin="00:00:00.000" end="00:00:02.000" region="bottomCenter">
        Te atreves a mentir, incluso
        <br/>
        cuando tienes tanto que perder.
      </p>

242:
      <p begin="00:00:00.000" end="00:00:00.560" region="bottomCenter">Esta vez, será tu tragedia.</p>
      <p begin="00:00:00.720" end="00:00:01.800" region="bottomCenter">No, por favor!</p>
      <p begin="00:00:01.960" end="00:00:02.000" region="bottomCenter">No han hecho nada!</p>

306:
      <p begin="00:00:00.000" end="00:00:00.160" region="bottomCenter">
        Cuando apareces
        <br/>
        de la nada sin avisar,
      </p>
      <p begin="00:00:00.320" end="00:00:01.480" region="bottomCenter">lo que haces es asustar.</p>

328:
      <p begin="00:00:00.000" end="00:00:00.120" region="bottomCenter">
        Está escrito
        <br/>
        en un idioma extraño.
      </p>
      <p begin="00:00:00.280" end="00:00:01.160" region="bottomCenter">Es yindrio.</p>
      <p begin="00:00:01.680" end="00:00:02.000" region="bottomCenter">
        Pues claro que sí.
        <br/>
        -Sí.
      </p>

332:
      <p begin="00:00:00.000" end="00:00:01.520" region="bottomCenter">pero solo sé hablar tres.</p>
      <p begin="00:00:01.680" end="00:00:02.000" region="bottomCenter">Eres asombroso.</p>

337:
      <p begin="00:00:00.000" end="00:00:02.000" region="bottomCenter">
        Mi yindrio está algo oxidado,
        <br/>
        ya que nadie lo habla,
      </p>  
```

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18, 19, 20, 21 alpha
 - inputstream.adaptive version: last tested with 21.1.3

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
`<p begin="00:00:00.000" end="00:00:02.000">Hello World</p>`

this is right but for normal xml ttml case, that show only for first two seconds Hello world
but your ttml is ISOBMFF format that is different

this use case seem not implemented the time seem relative to something else
atm i have only a dash manifest with ttml as ISOBMFF but this works correctly
will be needed more deeper investigations

**Comment by werimail** [comment]
Hi @CastagnaIT 
Is there now a possible solution or at least an approach to the problem presented?
Greetings Weri

**Comment by CastagnaIT** [comment]
i had tried investigate time ago but since i did not found a helpful documentation on this type of ttml isobmff
so i don't know how/what to do
since i dont have any similar sample stream that can be used to make local tests i am at a standstill

**Comment by werimail** [comment]
Ok @CastagnaIT maybe I can help: Here I have a log file with subtitle streams which are also skipped. These may help??

[kodi_sub_debug.log](https://github.com/xbmc/inputstream.adaptive/files/13989706/kodi_sub_debug.log)

Greetings Weri

**Comment by CastagnaIT** [comment]
after a lot of searchs i found something, looks like a microsoft customization
https://github.com/Dash-Industry-Forum/dash.js/blob/124920530d8503bd7581e1ffed300823b54c2512/src/streaming/text/TextSourceBuffer.js#L329-L330
thanks MS for your crap... i hope one day it will start to follow the standards

**Comment by CastagnaIT** [comment]
looks like we are already add the offset despite its always applied for all cases that can be wrong...

can you give me a feedback?
these are test builds for Kodi 21:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1497/1/artifacts

**Comment by Paco8** [comment]
After a quick test this problem seems fixed.

However I noticed that there are still problems with the subtitles in live streams. I'll try to send some fragments, since it seems live streams use a slightly different format.

**Comment by CastagnaIT** [comment]
this new test build should solve:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1497/3/artifacts
let me know

**Comment by Paco8** [comment]
Now it seems that it no longer skips fragments on live streams. 
However there's still a remaining problem, which only happens on live streams. When there are two lines, they are displayed in the wrong order.

For example:
![Captura desde 2024-02-29 16-09-43](https://github.com/xbmc/inputstream.adaptive/assets/5084042/81fada44-069d-4e7e-a432-12786b129947)

It should say:
```
Su tercera pareja
fue la periodista checa,
```

I attach some subtitle fragments from this live stream:
[live_tv.zip](https://github.com/xbmc/inputstream.adaptive/files/14449990/live_tv.zip)

**Comment by CastagnaIT** [comment]
thanks for fragments, the mentioned subs are relative to this xml
```xml
  <body>
    <div>
      <p begin="00:00:00.000" end="00:00:00.359" region="speaker">de GermÃ¡n Kafka, su padre. </p>
      <p begin="00:00:00.599" end="00:00:02.000" region="speaker">Su tercera pareja </p>
      <p begin="00:00:00.599" end="00:00:02.000" region="speaker">fue la periodista checa, </p>
    </div>
  </body>
```

this is a know problem of the subtitle renderer used by kodi so Libass (external) library,
here we are converting TTML to SRT and feed kodi sub renderer by single packet (in this case single text line) at time (3 lines of above example == 3 packets) so its managed somehow always such as a live video, this can cause libass to show messy lines,
as mentioned on comment https://github.com/libass/libass/issues/534#issuecomment-899024461 where the guy say:

>I would expect subtitles to be in order oldest at top (that is the top one should be no 1 in the example above). New ones should always be added at the bottom, never in the middle.

the dev maintainer answered, works as it is...
so we are at the mercy of workarounds or keep as is

the only solution that come to my mind is to try convert TTML to ASS format, this would result in one less step in Kodi core and so will provide to the libass renderer pure ASS data, maybe, in this way in theory, you can preserve the order of the lines of text
ofc require some rework in ISA, its possible to do an attempt, in future
if you want you can open a separate Issue to keep track

**Comment by Uukrull** [comment]
As a workaround, could it be possible to check if both lines have the same time and add 1 millisec to the second line?

      <p begin="00:00:00.599" end="00:00:02.000" region="speaker">Su tercera pareja </p>
      <p begin="00:00:00.600" end="00:00:02.000" region="speaker">fue la periodista checa, </p>

**Comment by CastagnaIT** [comment]
yes in theory, a become a bit more complex to works with segments,
you need to store/compare also the last begin time between segments

**Comment by Uukrull** [comment]
What about this:

```
@@ -344,6 +360,14 @@ void TTML2SRT::StackSubtitle(std::string_view id,
   newSub.end = GetTime(endTime);
   newSub.text = text;
 
+  if (m_subtitlesList.size() > 0 && ((m_subtitlesList.end()-1)->start == newSub.start))
+  {
+    (m_subtitlesList.end()-1)->text += '\n' + std::string(text);
+    return;
+  }
+
```

**Comment by CastagnaIT** [comment]
> What about this:

this example code dont take in account of segmented subtitles, end time between cue's may be different,
forcing the joining of text between different cue's is wrong, to avoid it when possible

**Comment by CastagnaIT** [comment]
i made a test PR #1498
test builds here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1498/1/artifacts

i have no streams to test ttml overlapping locally, so idk the results

**Comment by CastagnaIT** [comment]
my test PR dont work,
its the same as you try the overlapped test from here: https://ale5000.altervista.org/subtitles.htm
(and you edit first cue's timings)

however overlapped test SRT file is shown correctly as happens on VLC/MPV

i agree that libass multi-lines sort order is strange nowadays (also srt),
where instead the new added text lines should be displayed always from bottom, not on top

the best way is that the libass renderer itself provide a setting for multiple-lines sort order,
last resort is try the solution i mentioned above, so convert TTML to ASS format instead of "SRT"

**Comment by CastagnaIT** [comment]
@Uukrull thinking again on your proposal, i think its better than nothing, since a real solution for now its not possible
i have reworked your code on PR #1499
ofc this workaround its not perfect and can fails on more situations
but by see fragments provided above should improve much better at least on this use case

please give feedback
test builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1499/1/artifacts

**Comment by Paco8** [comment]
With the latest build, now the subtitle lines are displayed in the correct order.

**Comment by Uukrull** [comment]
It works for me but only if I remove the region check. For example:

```
<?xml version="1.0" encoding="utf-8"?>
<tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" >
<head>
  <styling>
   <style xml:id="s0" tts:backgroundColor="rgba(0,0,0,192)" tts:color="rgba(255,255,255,255)" tts:fontSize="1c" tts:fontFamily="proportionalSansSerif" />
  </styling>
  <layout>
   <region xml:id="b24fdd_r0" tts:textAlign="center" tts:origin="0.00% 79.07%" tts:extent="100.00% 8.43%" />
   <region xml:id="b24fdd_r1" tts:textAlign="center" tts:origin="0.00% 87.40%" tts:extent="100.00% 8.43%" />
  </layout>
</head>
<body timeContainer="par">
  <div xml:lang="und">
   <p xml:id="cb24fdd_00" xml:space="preserve" begin="10167:08:52.429" end="10167:08:54.429" region="b24fdd_r0" ><span style="s0">Now that I've met you two, we can</span></p>
   <p xml:id="cb24fdd_01" xml:space="preserve" begin="10167:08:52.429" end="10167:08:54.429" region="b24fdd_r1" ><span style="s0">make lots of different greens.</span></p>
  </div>
</body>
</tt>
```

**Comment by CastagnaIT** [comment]
ok removed region check
in any case it is a conversion that does not follow any of TTML rules
