### ISSUE TITLE
update .mpd when playing live

### ISSUE THREAD

**Issue by mkorganashvili** [peak3d/inputstream.adaptive#135]
I'm trying to play nba live but it playes only for about 1 minute. The thing is that web player reloads .mpd file in every three seconds to get new segments. Is there any chance to do the same with kodi?

**Comment by emilsvennesson** [comment]
@mkorganashvili See https://github.com/emilsvennesson/kodi-viaplay/issues/16 and https://github.com/emilsvennesson/kodi-viaplay/commit/dfe9fc1d7f7df0dff34c02aa567ef848f4debf13 (Kodi Leia only).

**Comment by peak3d** [comment]
@mkorganashvili you managed it? Some providers use partitial manifest update instead updating the full manifest, you should lookk in the web traffic log how updating is performed (ETag / some parameters like startpos / whatever).

If you can provide the information how they do updating, I can most probably tell you the way how to implement.

**Comment by mkorganashvili** [comment]
@peak3d it is working now. Thank you ;)
