### ISSUE TITLE
DAZN live stream problems

### ISSUE THREAD

**Issue by Maven85** [peak3d/inputstream.adaptive#1350]
### Describe the bug
When I start a live stream from the live position, the stream jumps to the beginning of the stream after a few seconds. The stream then freezes or jumps back and forth between the live position and the beginning.

### Debuglog
[debug.log](https://github.com/xbmc/inputstream.adaptive/files/12318641/debug.log)

### MPD/M3U8s/ISM
[stream.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/12261646/stream.mpd.txt)

## Additional context or screenshots (if appropriate)
Works with version 21.1.2 but not with 21.1.3.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11/Android 9
 - Kodi version: 21
 - inputstream.adaptive version: 21.1.3

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
can you provide a debug log by playing on the last working isa?

also try to see if you see some improvement with this test:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1352/1/artifacts

**Comment by Maven85** [comment]
Here a debug log with ISA v21.1.2:
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/12266864/kodi.log)

The test version didn't improve anything.

**Comment by CastagnaIT** [comment]
Try test this
[inputstream.adaptive-windows-x86_64-omega-f52201f_1.zip](https://github.com/xbmc/inputstream.adaptive/files/12282047/inputstream.adaptive-windows-x86_64-omega-f52201f_1.zip)

**Comment by Maven85** [comment]
do you also have a version for armv7?

**Comment by CastagnaIT** [comment]
here [inputstream.adaptive-android-armv7-omega-f52201f_1.zip](https://github.com/xbmc/inputstream.adaptive/files/12287685/inputstream.adaptive-android-armv7-omega-f52201f_1.zip)

**Comment by werimail** [comment]
do you also have a version for arm64 (v8a)?

**Comment by Maven85** [comment]
unfortunately no improvement.

**Comment by CastagnaIT** [comment]
can you show me a log for that test build?

**Comment by Maven85** [comment]
I will, but there will be live streams again tomorrow.

**Comment by Maven85** [comment]
the log for the test build:
[debug.log](https://github.com/xbmc/inputstream.adaptive/files/12318634/debug.log)

**Comment by CastagnaIT** [comment]
the log is not what i expected has not printed custom log text,
or you have not installed correctly the zip or the manifest is different caused different behaviour

please install following test: 
[inputstream.adaptive-android-armv7-omega-0465aaf_1.zip](https://github.com/xbmc/inputstream.adaptive/files/12318933/inputstream.adaptive-android-armv7-omega-0465aaf_1.zip)

for other platforms are on following link, but are double zipped, if downloaded you have unzip it before install it:
https://github.com/CastagnaIT/inputstream.adaptive/actions/runs/5829358225

if playback fails
provide log and manifests, please note that you should find more than a single manifest file

**Comment by Maven85** [comment]
With your test build it works again. thanks for your work!

**Comment by werimail** [comment]
I can also confirm that. I no longer experience any crashes, which was the case with the current version 21.1.3.
