### ISSUE TITLE
Feat add fps

### ISSUE THREAD

**Issue by s0rau** [peak3d/inputstream.adaptive#1359]
I've got and old RPI and the 60fps is too much for it, i'd like to set max fps in order to play on 30 fps all videos.

**Comment by CastagnaIT** [comment]
this is not a thing that will be considered to implement

low end devices like old RPIs has different downsides and playback cannot be fluent in different situations that lead to bad performance, like playing some DRM streaming, higher bitrate, middle or higher resolutions, CPU too much loaded, limited memory

the number of downsides variables is high and not acceptable, so your request is a workaround

solutions for devices like old RPI's are:
- limit max stream resolution for unencrypted and/or DRM content
- limit max bitrate
- try set more memory dedicated for GPU
- ensure there are no background operations that load CPU/HDD while in playback, e.g. limit addons background services
- try set fixed refresh rate to display and use kodi setting "sync playback to display", from kodi player->video settings, passthrough will not work, but idk if will be performant on oldest RPIs

for the first two options, you can use ISAdaptive addon settings

**Comment by s0rau** [comment]
Thanks for answer but does not fix the 60fps but only set max resolution and bandwidth bitrate, I'll find another solution.
