### ISSUE TITLE
Set license key on Playready DRM SmoothStreaming

### ISSUE THREAD

**Issue by datrix88** [peak3d/inputstream.adaptive#1365]
### Describe the bug

I tried to play a stream with Playready DRM SmoothStreaming with his license url but i can't stream anything.
I used this code: 

#EXTM3U
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=ism
#KODIPROP:inputstream.adaptive.license_type=com.microsoft.playready
#KODIPROP:inputstream.adaptive.license_key=https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(contentkey:KEY,kid:header)
https://hss-live-hd-nowtv.skycdn.it/21519/FHD/tg24.isml/Manifest

How can i set the DRM key in right way?

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: last official release
 - inputstream.adaptive version: last official release

**Comment by CastagnaIT** [comment]
your video service use really microsoft test server? its weird
fwik usually the license url is contained on the PlayReady header that is already provided with the manifest
set the inputstream.adaptive.license_key should not be needed
thats what wiki said: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivelicense_key

**Comment by datrix88** [comment]
Thanks @CastagnaIT 
So how can i pass the Key to decrypt the stream if i can't use license_key parameter?

**Comment by CastagnaIT** [comment]
what key? the kid is part of the PlayReady header

**Comment by datrix88** [comment]
In the license URL there Is Key:

https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(contentkey:KEY,kid:header)

In the example i use the word KEY, it's a base64 key

**Comment by CastagnaIT** [comment]
as i can see the playready header of the manifest (downloaded from provided link)
[Manifest.xml.txt](https://github.com/xbmc/inputstream.adaptive/files/12462766/Manifest.xml.txt)
already have the license url and also the kid as follow:
```
<WRMHEADER xmlns="http://schemas.microsoft.com/DRM/2007/03/PlayReadyHeader" version="4.0.0.0">
  <DATA>
    <PROTECTINFO>
      <KEYLEN>16</KEYLEN>
      <ALGID>AESCTR</ALGID>
    </PROTECTINFO>
    <KID>PhaHxz3GkEG2AcYSCFONfA==</KID>
    <LA_URL>http://profe.any.sky.it/PlayReadyLicenser/rightsmanager.asmx</LA_URL>
    <DS_ID>7/RYM5/9ok6TRIaf7Montg==</DS_ID>
    <CUSTOMATTRIBUTES xmlns="">
      <TXTGUARD_EID>RouterPlayreadyProvider</TXTGUARD_EID>
    </CUSTOMATTRIBUTES>
    <CHECKSUM>DHOekTDZdIs=</CHECKSUM>
  </DATA>
</WRMHEADER>
```
so its not clear to me why you want overwrite the playready header data with other data
if dont works you need to provide a debug log (better on Kodi 21 that has many improvements)
