### ISSUE TITLE
[Disney+] Default subtitle not displayed

### ISSUE THREAD

**Issue by MauriceW67** [peak3d/inputstream.adaptive#1366]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing an episode in the Disney+ addon, my default subtitle language (Dutch) is being selected by the addon and subtitles are also enabled according to the Kodi OSD. However, the subtitles are not displayed on screen. Manually switching to another subtitle language makes the subtitles appear in that language. Switching back to Dutch makes the subtitles disappear again.

@matthuisman I've created a separate issue to prevent clutter in the issue about sound not being played.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles should be displayed in my language (Dutch) when selected and enabled automatically by the Disney+ addon.
Note: For the purposes of testing, I disabled the SlyProxy option in the Slyguy Common services addon.

## Actual Behavior

Subtitles are not displayed in my language (Dutch) when selected and enabled automatically by the Disney+ addon.

### To Reproduce

1. Ensure Dutch is selected as the default subtitle language in Kodi's settings
2. Start the Disney+ addon.
3. Start playing an episode (f.e. Secret Invasion, episode 1).
4. Note that no subtitles are being displayed.
5. Check the Kodi OSD and note that Dutch subtitles are selected and enabled there.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/12445233/kodi.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifests.zip](https://github.com/xbmc/inputstream.adaptive/files/12445255/manifests.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.1.1 (Android TV 11)
 - Kodi version: 21.0-ALPHA2 (20.90.201) Git:20230824-b049c37178
 - inputstream.adaptive version: inputstream.adaptive-android-aarch64-omega-decc930_1

Note: The issue also occurs with IS:A version 21.2.0 (released yesterday). However, it does not occur with Kodi 20.2 and IS:A 20.3.11.

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
the problem is the same of the other issue
ISA try download from a wrong url address

**Comment by MauriceW67** [comment]
I created this issue to avoid clutter with the sound issue like @matthuisman suggested.

But after I posted the issue it hit me that the behavior is basically the same as with the audio tracks :-)

It's weird though, why does ISA only use the wrong url address for the initially chosen track (audio or subtitle), but all the other tracks that are manually chosen work ok?
