### ISSUE TITLE
No Audio while playing HLS stream

### ISSUE THREAD

**Issue by Vikassm73** [peak3d/inputstream.adaptive#1367]
While playing below stream in Kodi 20, I am getting no audio output. Below stream play perfectly without inputstream. (Using ffmpeg in Kodi or VLC player). Please note that stream may not work outside India.

Stream Url : https://jc-ak-hlsstreaming.jiocinema.com/vod/_definst_/smil:vod/6/31/9a6676b0feb711ed966e4f6edd74efff.smil/playlist_voot_web_premium.m3u8?hdnts=st=1693288083~exp=1693288683~acl=/vod/_definst_/smil:vod/6/31/9a6676b0feb711ed966e4f6edd74efff.smil/*~id=bf5b38d8-5f39-4ffa-b8b1-a4960ad00168~hmac=509176fcbcdbebce0c132f235ea1f4143912fcc1d49a5ac6d1065774c813fecb

Manifest:
https://paste.kodi.tv/odujabisuq

Debug Log:
https://paste.kodi.tv/wokipacifa.kodi

**Comment by CastagnaIT** [comment]
i cannot test the stream linked, its geolocked
however there is no audio because has not be able to download the audio manifest

```
2023-08-29 11:18:40.580 T:53480   error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x1e95f941a10) Failed: HTTP returned code 403
2023-08-29 11:18:40.580 T:53480   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://jc-ak-hlsstreaming.jiocinema.com/vod/_definst_/smil:vod/6/31/9a6676b0feb711ed966e4f6edd74efff.smil/chunklist_b64000_ao_t64YWFj.m3u8> Failed with code 403:
                                                   
2023-08-29 11:18:40.580 T:53480   error <general>: AddOnLog: inputstream.adaptive: CURLOpen returned an error, download failed: https://jc-ak-hlsstreaming.jiocinema.com/vod/_definst_/smil:vod/6/31/9a6676b0feb711ed966e4f6edd74efff.smil/chunklist_b64000_ao_t64YWFj.m3u8
```

i have no idea of the reasons, a possibility to try understand something
is that you play it with ffmpeg with enabled kodi Curl component specific logging
so i can try compare urls with both logs

**Comment by Vikassm73** [comment]
Inputstream with enabled kodi Curl component specific logging

https://paste.kodi.tv/axuzifeyoh.kodi

ffmpeg with enabled kodi Curl component specific logging

https://paste.kodi.tv/epujitawuj.kodi

**Comment by CastagnaIT** [comment]
thanks unfurnately i was not aware that with ffmpeg curl logging dont works
however this confirm that we are downloading from the right url
the only thing i could think is that maybe there are some cookies obtained from master manifest request, that are sent to the request of all others child manifests

but the only way to check if cookies are used, at this point is analyze the network flow when you play same video with the webbrowser on the original website, and check if in the request for
`https://jc-ak-hlsstreaming.jiocinema.com/vod/_definst_/smil:vod/6/31/9a6676b0feb711ed966e4f6edd74efff.smil/chunklist_b64000_ao_t64YWFj.m3u8`
are sent some custom cookies

if this is confirmed, we already know that ISAdaptive dont support sending cookies

**Comment by Vikassm73** [comment]
Unfortunate that is not possible. API return 2 urls. One Dash and another hls link. Webbrowser use dash link. which is working fine. hls link has a problem which is not used while playing in browser. 

Please note that this issue is with some hls play back while others are working fine.

Working hls link

https://paste.kodi.tv/akecedomey.kodi

(In Kodi 21 - Non working hls goes into infinity loop. Plays nothing.)

**Comment by Vikassm73** [comment]
Main issue is in Manifest of an url. Please find below.

https://paste.kodi.tv/osolakiloc

Kodi 21 Error is
2023-09-08 16:10:26.943 T:86184 warning <general>: AddOnLog: inputstream.adaptive: adaptive::CHLSTree::ParseMultivariantPlaylist: Cannot add EXT-X-STREAM-INF variant due to unhandled data
2023-09-08 16:10:26.943 T:86184   error <general>: AddOnLog: inputstream.adaptive: adaptive::CHLSTree::ParseMultivariantPlaylist: The EXT-X-STREAM-INF variant does not have enough info to determine the stream type

**Comment by CastagnaIT** [comment]
yes that manifest dont have much info to determine the stream type
i forced fallback as video, following test build should be ok:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1376/2/artifacts

**Comment by Vikassm73** [comment]
Need windows-x86_64 zip

**Comment by CastagnaIT** [comment]
you have to wait green status of builds

**Comment by Vikassm73** [comment]
Working now, Thanks
