### ISSUE TITLE
Failed to download manifest and playback not starting

### ISSUE THREAD

**Issue by swinder0161** [peak3d/inputstream.adaptive#1370]
### Describe the bug
installed add-on: https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/plugin.video.hotstar/plugin.video.hotstar-1.2.2.zip
Try to play Cricket Asia cup stream: Sports -> Asia Cup -> India vs Pakistan match
There is error from input.adaptive
Not Working: kodi: 21.0-ALPHA2 & input.adaptive : 21.1.3
Working: Same plugin working well on Kodi:Nexus in Windows and Android Phone: input.adaptive : 20.3.12

## Expected Behavior
Playback should work

## Actual Behavior
Playback shows error

### To Reproduce
installed add-on: https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/plugin.video.hotstar/plugin.video.hotstar-1.2.2.zip
Try to play Cricket Asia cup stream: Sports -> Asia Cup -> India vs Pakistan match

1. 
2.
3.

### Debuglog
2023-09-02 15:00:38.206 T:4200505   error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 403: https://live12p.hotstar.com/hls/live/2024726/inallow-asiacup-2023/hin/1540024251/15mindvrm01041c55e31355409c98d85f4627ad910402september2023/master_apmf.m3u8?a=ns&hdnea=st=1693646937~exp=1693647537~data=ip%3dd58JPvHp1pKClTi1VRsdxe-userid%3dMYfwPgDplhWnuXHFbpTfcrUcln5VqHu92cZfUYxoTKZY-did%3dfEPhZ5UygwveUJ2GzTvp8QabIBIXpw6ER1LNBNBl3er3GHCGAbn4VUj-cc%3din-~hmac=03095a00fa09f4a2c2670be0d239b991701ec0a04ca030d743d16e841578fed0&ttl=86400&type=free&acl=/hls/live/2024726/inallow-asiacup-2023/hin/1540024251/15mindvrm01041c55e31355409c98d85f4627ad910402september2023/master_apmf

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/12503712/kodi.log)

### MPD/M3U8s/ISM

Manifest not available in the userdata folder

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
<img width="1680" alt="image" src="https://github.com/xbmc/inputstream.adaptive/assets/397543/98fce378-152c-4473-adf2-e7f32e2e9a77">

### Your Environment
Used Operating system: MAC OS 13.5

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0-Alpha2 nightly build ARM64 version
 - inputstream.adaptive version: 21.1.3

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
this is more likely an addon "hotstar" bug that has not updated the inputstream configuration for kodi 21,
please check deprecation note and new configurations:
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemanifest_headers-
these are also printed as warning on Kodi 20 log

if you are not the developer of "hotstar" you have to report this problem to "hotstar" addon repository
flagged as external resolution until we get a feedback addon author

**Comment by swinder0161** [comment]
Hi @CastagnaIT 

Thanks for prompt feedback.
I am not the developer but I can try out suggestions in addon python files if you have any.

I see addon has below code, please suggest changes so that I can try and give you feedback

```
"properties": {
    "IsPlayable": True,
    "inputstream": is_helper.inputstream_addon,
    "inputstream.adaptive.manifest_type": playbackProto,
    "inputstream.adaptive.license_type": drm,
    "inputstream.adaptive.stream_headers": urlencode(stream_headers),
    "inputstream.adaptive.license_key": licenceUrl and licenceUrl + '|%s&Content-Type=application/octet-stream|R{SSM}|' % urlencode(stream_headers)
},
```

**Comment by CastagnaIT** [comment]
contact the developer, he know the requirements for the video service

**Comment by swinder0161** [comment]
Hi @CastagnaIT 

I tried [Kodi 21 Omega pre-release apk](https://ftp2.nluug.nl/mediaplayer/xbmc/snapshots/android/arm64-v8a/kodi-21.0-Omega_alpha2-arm64-v8a.apk) on Android and it seems to have no inputstream.adaptive.
Earlier I tried on Macbook ARM64 nightly build.

Not sure if developer of hotstar will have macbook to try out. Can you please help to fix problem with Kodi omega apk so that I can provide steps to hotstar developer for android instead of macbook?

**Comment by CastagnaIT** [comment]
the pre-release that are you using its old, you cant use binary addons with that version
you have to use the nightly builds http://mirrors.kodi.tv/nightlies/ ("master" folder=kodi 21)

its not needed a macos,
you can test over any operative system supported by "hotstar" addon

i have already provided you the links of the two inputstream properties required to be check, that you can check by yourself
based on your comment https://github.com/xbmc/inputstream.adaptive/issues/1370#issuecomment-1704028140
seem missing this one: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers
so you can try add it
i cant help you more than this i dont know how works that service,
the right step is open an issue on the "hotstar" addon

**Comment by Vikassm73** [comment]
![image](https://github.com/xbmc/inputstream.adaptive/assets/41675437/9255d0b0-16e6-4076-9e8a-5794aa582970)

**Comment by Vikassm73** [comment]
The header details from browser are listed above. This website does not need a license key. We only need to pass "Stream Header" to parse the main url. The steps in Kodi 20 and Kodi 21 are the same. In the second level, we may required "manifest_headers" . If I'm wrong, kindly correct me.
In Kodi 20 it works flawlessly, but not in Kodi 21.

**Comment by CastagnaIT** [comment]
> We only need to pass "Stream Header" to parse the main url. The steps in Kodi 20 and Kodi 21 are the same.

its well explained on wiki and dont say that

`stream_headers`:
- until kodi <=20 its used to set headers to **manifests** and **streams**, but from kodi 20 its deprecated
- from kodi 21 its used to set headers to **streams** _only_

just read your Kodi 20 log to see that there is a WARNING where explain that in your addon more likely miss to set a property.

your addon still dont set `manifest_headers`, then headers are not set for the manifest request,
the `manifest_headers` should be already added to your addon from Kodi 20, and not 21 only

every time there is a deprecation, addons must act with correction code changes and dont still use deprecated things

**Comment by Vikassm73** [comment]
Now, I have tried 
1) both stream_headers as well as manifest_headers.
2) Only manifest_headers.

 but result is the same.

**Comment by swinder0161** [comment]
@Vikassm73 I even tried with python3.10.12 script and it doesnot work on shell also. Same 403 error is thrown.

```
import requests

url = '' # add url here

#this header I get in my inconginito browser window b ut the m3u8 get downloaded
#seems cookie is not needed at all
hdrs = { 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'en-IN,en;q=0.9',
'Connection': 'keep-alive',
'Host': 'live15p.hotstar.com',
'Sec-Fetch-Dest': 'document',
'Sec-Fetch-Mode': 'navigate',
'Sec-Fetch-Site': 'none',
'Sec-Fetch-User': '?1',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54',
'sec-ch-ua': '"Chromium";v="116", "Not)A;Brand";v="24", "Microsoft Edge";v="116"',
'sec-ch-ua-mobile': '?0',
'sec-ch-ua-platform': '"macOS"'
}

r=requests.get(url, headers=hdrs)
print("r:", r) #getting error 403 here
```

**Comment by swinder0161** [comment]
<img width="1356" alt="image" src="https://github.com/xbmc/inputstream.adaptive/assets/397543/d005ed54-bbe5-4009-917c-72263efbd453">

**Comment by Vikassm73** [comment]
After updating to latest Development Builds and latest version of inputstream, it start working. But same stream failed first time and start playing If I played it again. Also, not all streams are working.

https://paste.kodi.tv/ahawureges.kodi

**Comment by CastagnaIT** [comment]
from the last log i can see that headers are set correctly
the http error 403 response there is `x-cache: Error from cloudfront`
but i have no idea the reasons behind this so i don't even know what should be done

there is only a uncommon thing on a header that is set as:
content-type=application/json

where here there is no json contents, usually should be set as:
content-type=application/octet-stream

**Comment by CastagnaIT** [comment]
if content-type change above dont works,
and if on kodi 20 still works correctly, a thing that you can do is to use a proxy software to inspect network traffic
then compare ISA requests when you play same video on Kodi 20 and 21
in this way you can try to see if you find some data/parameters difference between the requests made by the two kodi versions

**Comment by Vikassm73** [comment]
content type change does not work. Please find below working kodi 20 log
https://paste.kodi.tv/ruferafoto.kodi

In working module parameter like hotstarauth, x-hs-usertoken appears in Curl::Debug - HEADER_OUT while those are missing from non working stream in Kodi 21.

**Comment by Vikassm73** [comment]
content type change does not work. Please find below working kodi 20 log
https://paste.kodi.tv/apemejabez.kodi

Kodi 21 log of same stream
https://paste.kodi.tv/opehijapir.kodi

In working module header parameters  shown in Curl::Debug - HEADER_OUT while those are missing from non working stream in Kodi 21.

**Comment by CastagnaIT** [comment]
thanks i try investigate

**Comment by Vikassm73** [comment]
Used mtmproxy to check a network traffic. Required main headers are Cookies and User-Agent only

![image](https://github.com/xbmc/inputstream.adaptive/assets/41675437/df9f8b79-df84-4b79-9443-7b96dc2f97f1)

**Comment by CastagnaIT** [comment]
i have found an oversight in the code i didn't see it before

test builds will be available soon here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1376/1/artifacts

**Comment by Vikassm73** [comment]
Thanks, start working now.

**Comment by swinder0161** [comment]
Not sure, but still doesnot work for me
Operating system - MAC OSX 13.5 on Apple Silicon(arm64)
Kodi v21 arm64 - [kodi-20230908-4d639b82-master-1570-arm64.dmg](https://mirror.yandex.ru/mirrors/xbmc/nightlies/osx/arm64/master/kodi-20230908-4d639b82-master-1570-arm64.dmg)
inputstream.adaptive - [inputstream.adaptive-21.2.1.zip](https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-1376/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-arm64/inputstream.adaptive-21.2.1.zip)
Error log - [kodi.log](https://github.com/xbmc/inputstream.adaptive/files/12559131/kodi.log)

**Comment by CastagnaIT** [comment]
@swinder0161 dont work for you because its missing the ISA `manifest_headers` property as discussed above

**Comment by swinder0161** [comment]
@Vikassm73 is there a new version of hotstar plugin which I can try?

**Comment by swinder0161** [comment]
@CastagnaIT @Vikassm73 seems below is working
```
diff --git a/resources/lib/builder.py b/resources/lib/builder.py
index b1a4633..409073a 100644
--- a/resources/lib/builder.py
+++ b/resources/lib/builder.py
@@ -109,6 +109,7 @@ class Builder:
                     "inputstream.adaptive.manifest_type": playbackProto,
                     "inputstream.adaptive.license_type": drm,
                     "inputstream.adaptive.stream_headers": urlencode(stream_headers),
+                    "inputstream.adaptive.manifest_headers": urlencode(stream_headers),
                     "inputstream.adaptive.license_key": licenceUrl and licenceUrl + '|%s&Content-Type=application/octet-stream|R{SSM}|' % urlencode(stream_headers)
                 },
                 "subtitles": [subtitleUrl]
```

**Comment by swinder0161** [comment]
ISA patch even solved my long term problem with tsneh playlist on Kodi v21 which had same error of 403.
