### ISSUE TITLE
Custums headers are not used in IA 

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1371]
### Describe the bug
Here is a clear and concise description of what the problem is:
In Nexus, IA seems to overwrite  the customs declared headers with its own header. **That does not occur with Leia. Did not test with Matrix**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Custom header is used all over the stream process

## Actual Behavior
IA uses its own headers (user-agent: Kodi/21.0-ALPHA1 (X11; Linux x86_64) Ubuntu/23.04 App_Bitness/64 Version/21.0-ALPHA1-(20.90.101)-Git:20230413-53001491bc)

### To Reproduce
1.  Install the latest beta of Catchup-tv-and-more (0.2.39 beta 34)
2.  **With a french IP** live->France->France Info

### Debuglog

The debuglog can be found here: [kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/12504990/kodi.txt)

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/12504989/manifest.txt)

## Additional context 
Here is some additional context or explanation that might help:
Here is my IA configuration for this stream:

`
headers ={'User-Agent': 'toto (X11; Linux x86_64) Ubuntu/23.04 App_Bitness/64 Version/21.0-ALPHA1-(20.90.101)-Git:20230413-53001491bc', 'Accept-Encoding': 'gzip, deflate, br'}
stream_headers = urlencode(headers)
item.property[INPUTSTREAM_PROP] = "inputstream.adaptive"
item.path = ' https://simulcast-p.ftven.fr/ZXhwPTE2OTM3MjI4Njh+YWNsPSUyZip+aG1hYz1jZjFmODFiMTIxOGM1ODA1NWQwOGM4NDZjOTk0M2U3OWRiM2MyNjM5NmEyZmZmNDNmMDYwZjlhNmJmOTA3YTcx/simulcast/France_5/hls_fr5/index.m3u8?hdnea=exp=1693701868~acl=%2f*~hmac=b50da77333552a62bc54dde1f917a3f48e631deabb7c93cc0521c21dbe5d2eb2'

item.property["inputstream.adaptive.manifest_type"]  = 'hls'
item.property['inputstream.adaptive.license_type'] = 'com.widevine.alpha'
item.property['inputstream.adaptive.manifest_headers'] = stream_headers
item.property['inputstream.adaptive.license_key'] = 'https://simulcast-b.ftven.fr/keys/hls.key|%s|R{SSM}|' % stream_headers

`

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 20.2 Nexus
 - inputstream.adaptive version: 21.1.3

**Comment by CastagnaIT** [comment]
> In Nexus, IA seems to overwrite the customs declared headers with its own header.

its not clear if you are talking about 20 or 21,
your attached log is Omega (v21), not Nexus (v20)
and in the log there are no InputStream adaptive uses to verify,
however if was so we will have much more complaning, sound weird

suggest you to check your addon sources and read wiki page to fix related ISA header properties for the appropriate kodi version used:
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemanifest_headers-
since there are deprecations and new properties between kodi versions

**Comment by CastagnaIT** [comment]
also its not clear if you want set headers to manifest or streams or both

if your snipped example code above is referred to v21
then you have not set the headers to the streams

**Comment by joaopa00** [comment]
Sorry. I have just seen that Ubuntu Lunar uses Omega when Kodi repo is enabled. I removed it and installed the Nexus version (20.0 in Ubuntu) to have a bug report with Nexus. Here is the new debug log. The problem is still there.
[kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/12505965/kodi.txt)

However, If I add the config item  i
`item.property['inputstream.adaptive.stream_headers']= stream_headers` 
all is fine  although this item is deprecated in Nexus.

**Comment by CastagnaIT** [comment]
that property its not deprecated, just read whats deprecated _behaviour_ is for it on wiki
