### ISSUE TITLE
With Twitch streaming, crash at commercial break

### ISSUE THREAD

**Issue by thomasb22** [peak3d/inputstream.adaptive#1374]
### Describe the bug
Here is a clear and concise description of what the problem is:

When a commercial break start, Kodi crash and restart.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash.

## Actual Behavior

Crash.

### To Reproduce

1. Install [Twitch on Kodi](https://github.com/anxdpanic/plugin.video.twitch)
2. Launch a stream with ads in middle of stream
3. Wait the ads

### Debuglog

The debuglog can be found here:

Journalctl at crash moment:
```
Sep 06 13:36:47 Pi4 connmand[515]: ntp: adjust (slew): -0.010984 sec
Sep 06 13:53:51 Pi4 connmand[515]: ntp: adjust (slew): -0.010105 sec
Sep 06 14:10:04 Pi4 kodi.sh[788]: Segmentation fault (core dumped)
Sep 06 14:10:08 Pi4 kodi.sh[788]: Crash report available at /storage/.kodi/temp/kodi_crashlog_20230906141004.log
Sep 06 14:10:08 Pi4 systemd[1]: kodi.service: Main process exited, code=exited, status=139/n/a
Sep 06 14:10:08 Pi4 systemd[1]: kodi.service: Failed with result 'exit-code'.
Sep 06 14:10:08 Pi4 systemd[1]: kodi.service: Consumed 13min 33.705s CPU time.
Sep 06 14:10:10 Pi4 systemd[1]: kodi.service: Scheduled restart job, restart counter is at 1.
Sep 06 14:10:10 Pi4 systemd[1]: Stopped kodi.service.
Sep 06 14:10:10 Pi4 systemd[1]: kodi.service: Consumed 13min 33.705s CPU time.
Sep 06 14:10:10 Pi4 systemd[1]: Starting kodi.service...
Sep 06 14:10:10 Pi4 systemd[1]: Started kodi.service.
Sep 06 14:10:45 Pi4 systemd[1]: Starting sshd.service...
Sep 06 14:10:50 Pi4 ssh-keygen[24699]: ssh-keygen: generating new host keys: RSA ECDSA ED25519
Sep 06 14:10:50 Pi4 systemd[1]: Started sshd.service.
Sep 06 14:10:50 Pi4 sshd[24700]: Server listening on 0.0.0.0 port 22.
Sep 06 14:10:50 Pi4 sshd[24700]: Server listening on :: port 22.
Sep 06 14:10:55 Pi4 connmand[515]: ntp: adjust (slew): -0.004431 sec
```

And Kodi's log:
[kodi_crashlog_20230906141004.log](https://github.com/xbmc/inputstream.adaptive/files/12537687/kodi_crashlog_20230906141004.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: v20.2
 - inputstream.adaptive version: 20.3.12

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i trying test play videos on twitch but despite in "general" addon settings
i have set video quality to adaptive, and turn on "use input stream adaptive"
the addon still use ffmpeg instead of ISAdaptive

there is something else to do? or what else?

looks like that twitch addon has a bug
despite i have changed video quality still print "source" in the log:
`2023-10-25 13:26:49.844 T:9596    debug <general>: Twitch: Attempting playback using quality |Source| @ |https://video-weaver`

**Comment by CastagnaIT** [comment]
ok i solved by reinstalling twitch addon maybe a cache problem

for now i tried on Kodi 21 and when the ads starts just when playback start there are no crashes,
but to take in account that on Kodi 21 there are many improvements

do you mean ads at the beginning of live or only during live?
if during live, how much time is needed to have and ads in the middle of stream (after 15m no ads...)?

**Comment by thomasb22** [comment]
Issue is only with ads in the middle of stream.

**Comment by neo1973** [comment]
I'm also not able to reproduce the issue with aed0903e84cfe115c59f87acfddc2734004c1831 and https://github.com/xbmc/xbmc/commit/9d0ccaddf6a2556ba6621a2141f6fa4c8452d545. Watched streams with adds in the middle without problems.

**Comment by CastagnaIT** [comment]
finally i have catch ads in the middle of a live video
so i also confirm that on Kodi 21 no crashes

the problem looks like limited on Kodi 20 only,
personally i will dont try spend time to fix it on Kodi 20 due to too much missing code improvements
i leave opened the issue for a while if someonelse want try do it

**Comment by CastagnaIT** [comment]
closed no more backports, developments are starting for Kodi 22
