### ISSUE TITLE
IA can no download key file described in m3u8 file

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1375]
### Describe the bug
Here is a clear and concise description of what the problem is:
dailymotion C8 live stream has a URI to download key file in its m3u8 manifest. IA can not play this kind of file

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
IA can play stream with key file in m3u8

## Actual Behavior
Stream is not played.

### To Reproduce
1. CATCHUPTVANDMORE 
2. LIVE->FRANCE->C8->Dailymotion
3.

### Debuglog
The debuglog can be found here:
[kodi.txt](https://github.com/xbmc/inputstream.adaptive/files/12548592/kodi.txt)

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[maniifest.m3u8.txt](https://github.com/xbmc/inputstream.adaptive/files/12548524/maniifest.m3u8.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu
 - Kodi version: 20.0
 - inputstream.adaptive version: 20.3.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joaopa00** [comment]
Tested in windows and android: the problem does not occur. Happens only on Linux based Kodi: Libreelec, Ubuntu...
Happens on Ubntu with Leai 18.9 too.

**Comment by glennguy** [comment]
From the log: `Property found "inputstream.adaptive.license_type" value: com.widevine.alpha`
This isn't right. The manifest shows it's AES-128.

Other than that, the log shows that the download doesn't seem to be adding in the base URL: `AddOnLog: inputstream.adaptive: CURLOpen returned an error, download failed: /sec(3uHXKsK7_-J9YIYIiNPgOLrUENQgNjYWfcPOF0OGwm350gmt5QkcBOaQ_nebGYhv)/p/dm/3/x5gv5v0/d/live-2.key`

**Comment by CastagnaIT** [comment]
can you attach also the master manifest file?

**Comment by CastagnaIT** [comment]
you are using a quite old version
`inputstream.adaptive v20.3.2 installed`
please update to last one and test again,
from that old version to last one has been made different fixes about urls

> Tested in windows and android: the problem does not occur.

this could also explain the difference between os's

PS: i forgot,
currently Kodi distributions on linux platforms are stopped, and are not updated anymore (at least on PPA)
and also on flatpack so you will find only component versions of when has been compiled,
so you will have to build last version for your platform by yourself
