### ISSUE TITLE
Inputstream.adaptive updating

### ISSUE THREAD

**Issue by furkyto** [peak3d/inputstream.adaptive#138]
Is it possible to download with ffmpeg the url that are created by inputstream.adaptive from Kodi add-on

**Comment by furkyto** [comment]
How to get in the new version 2.2.14 into kodi ? With zip file or with downloading kodi install from mirrors.kodi.tv 
@peak3d  help :)

**Comment by tuxedo0801** [comment]
I'm searching as well for a way to update. 
I have RB Addon Repo, but it only contains v2.1.8.10

Where can I get zip file (S905 box) or addon repo to update this addon?

**Comment by JinRonin** [comment]
Just update your kodi / rb build

**Comment by peak3d** [comment]
can we close this one?

**Comment by tuxedo0801** [comment]
Using new coreelec. solved for me.
