### ISSUE TITLE
Flusonic Server HLS

### ISSUE THREAD

**Issue by quthla** [peak3d/inputstream.adaptive#139]
Adaptive Inputstream seems to be unable to play HLS generated by Flusonic Server.

http://demo-watcher.flussonic.com this doesn't play at all probably because there is no audio

Unfortunately the service I am using is not publicly accessible but I found another service using Flusonic which doesn't need login and also doesn't play.

tata . to -> TV

**Comment by peak3d** [comment]
tata.to looks like that it is a pirate site -> not my intention to support here.
