### ISSUE TITLE
Issue with playing a stream using Widevine and Kodi 21 Omega Beta 1 through PVR

### ISSUE THREAD

**Issue by ghost** [peak3d/inputstream.adaptive#1406]
I am running the latest Arch Linux Aarch64 on a Raspberry PI 3+. I'm trying to play m3u stream that requires Widevine. I have compiled and installed all requirements (64 bit) that pvr simple iptv needs: glibc-widevine, widevine, inputstream.ffmpegdirect, rtmp, adaptive, and helper.

I have disabled catchup and timeshift in the PVR Simple IPTV Client. When I select a stream through the EPG, the stream starts playing but it only plays for 15 seconds and then stops and I get a stream stalled. I am able to rewind the length of the current show so say I click on to play and the show is 30 minutes the show plays for 15 seconds and then stops then I can rewind 30 minutes and watch until the point where I started play. I don't have any issues with streams that don't need widevine.

I thought it was a PVR Simple IPTV client problem so I posted on their Github but after looking at my logs they said that it could be adaptive problem.

1) I consider this a bug since it stops playing after 15 seconds.
2) Desired behavior is that when I click play it continues to play without the stream stalling.
3) How to repeat. Use a 64 install, running Kodi Omega 21.0 beta 1, install PVR simple client and use a m3u that needs widevine. Click on play and you will see that the stream stalls.

https://privatebin.net/?8fa4e77c6ed9799a#7e1eswXrKsnvndSXF3tB1GuUXGTGHWtYnVdefWHKrddR

**Comment by CastagnaIT** [comment]
please attach the mpd manifest file

**Comment by ghost** [comment]
Here is the manifest fie.

https://pastes.io/fehyd3tpby

**Comment by CastagnaIT** [comment]
you have attached a wrong link

**Comment by ghost** [comment]
I edited the comment and added the proper link

**Comment by ghost** [comment]
I complied older versions until I found one that complied properly. 21.1.3 works and doesn't cause a stalled buffer stream.

**Comment by Uukrull** [comment]
> I complied older versions until I found one that complied properly. 21.1.3 works and doesn't cause a stalled buffer stream.

Probably because of this: https://github.com/xbmc/inputstream.adaptive/pull/1353 After reverting that code, a lot of live channels stuck at the timeShiftBufferDepth mark play without problems past that time.

**Comment by CastagnaIT** [comment]
all links are expired
can you post the m3u playlist if not geolocked, so i can try test the stream locally?

**Comment by CastagnaIT** [comment]
im working on a fix
you can find some test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1492/4/artifacts
i cannot provide build for RPI or LE/CE, but if you are able you can try build by using the branch of PR #1492

if you can please give feedback

**Comment by stuckinthe** [comment]
This fix has resolved the problem I was seeing. Live TV keeps playing instead of stopping after 30 seconds.

**Comment by ghost** [comment]
Unfortunately, I am seeing a stream stalled issue as the stream starts and then says stalled in the log files after 30 seconds.

**Comment by CastagnaIT** [comment]
use ISA expert setting to save all manifests and get also kodi log, so attach here all files

**Comment by CastagnaIT** [comment]
you can try test the updated PR #1492 branch
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1492/6/artifacts
if still doesnt work, ofc i need manifests+full log as said before

**Comment by ghost** [comment]
I am having a hard time figuring out how to pull these changes. I am running arch so I used makepkg. I was able to edit the PKGBUILD file and I added gh pr checkout 1492 but this now gives me a merge error and I can't figure out how to fix.

**Comment by CastagnaIT** [comment]
there are some instructions on wiki https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build but not for all systems

all PR's have they CI builds, just open "all checks passed" section
and click on "details" link of the "continuous integration" action
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/a407dbd7-9778-4a05-a323-f23e5de1bd7a)
after opened the new page goto "artifact" page to get the test builds, link on top menu

**Comment by ghost** [comment]
I'm using a different architecture so I need to build from source. The page you are referring to looks builds. How to I get the raw code so I can build?

**Comment by stuckinthe** [comment]
I ended up checking out each commit. I wasn't sure if I had did it correctly but I must have since I no longer have the problem as your fix has solved my issue.

**Comment by ghost** [comment]
I tried again and it doesn't seem to be working properly. I tried before when my internet was slow and it worked. I don't know what to think.

**Comment by CastagnaIT** [comment]
> I tried before when my internet was slow and it worked.

this sound more a provider problem
but i cannot say nothing more without having log+manifest

**Comment by ghost** [comment]
I just compiled the latest git and I am no longer seeing the issue.
