### ISSUE TITLE
Dash update Manifest Location tag not followed for relative urls

### ISSUE THREAD

**Issue by kcook98765** [peak3d/inputstream.adaptive#1407]
Running latest Omega versions. Had an issue where Live TV via Hulu was only lasting 5 minutes, then stalling.

Added to issue at https://github.com/matthuisman/slyguy.addons/issues/584

I have turned off Matt's proxy to test having just IA in the loop.

The first Manifest in such a test is attached. It contains a Location tag that is a relative url :  
`<Location>/v1/live/dash/continue/531124fc-2566-4206-b155-1b4f216e9ec8/manifest.mpd?cdns=sf&amp;cluster=blue&amp;origin=us-west-2&amp;duration=10800s&amp;manifest_cdn=ak&amp;repeat=true&amp;patch=true&amp;hpbsid_enabled=false&amp;uas_enabled=false&amp;segment_type_enabled=false&amp;query_params_v2=false&amp;unencrypted=false&amp;cver=0&amp;acquired_source_name=ABC_KOMO_SEA_MMA_CLT2-USW2&amp;stream_filter=fhd_high_stereo&amp;prev_start=1698533614322&amp;prev_boundary_start=1697130402514&amp;prev_pts_values=AAC_1_CMAF_CENC_CTR%3D68325770240%7CH264_1_CMAF_CENC_CTR%3D85407211890&amp;authToken=1698534232_cf0ec596424db8ccae76227b5f0f506210b14e605f7c02bb59aec3cbfa912859</Location>`

But monitoring the Manifest copies stored by IA when run never shows the Location being followed, instead every Manifest request is to the original Manifest, which only has 5 minutes of streaming.

Shouldn't IA follow the Location for the next update Manifest (and in turn if it has a Location to then follow it)?

I have tested from an Rpi 3b and a firestick, same issue.

[manifest_1698533632.txt](https://github.com/xbmc/inputstream.adaptive/files/13196875/manifest_1698533632.txt)

When I did test with Matt's proxy, I had modified to make the Location absolute which in turn at least had IA follow it, thought something else is going on as it did not get past the first 5 minutes, like processing of the partial update did not work (or maybe something else going on), but I want to first start here.

Also, if following these update manifests, and one call should have an issue, should IA fall back to "lasl" followed Location Manifest, instead of falling back to the very first one which it does now should any of the Location url's fail?

Thank You for your time and effort on this project.

**Comment by CastagnaIT** [comment]
> I have turned off Matt's proxy to test having just IA in the loop.
> The first Manifest in such a test is attached. It contains a Location tag that is a relative url :
> But monitoring the Manifest copies stored by IA when run never shows the Location being followed, instead every Manifest request is to the original Manifest, which only has 5 minutes of streaming.

hmm have sense,
a relative url on `Location` tag is not supported yet on ISAdaptive, then the value is ignored, but could be an easy fix

reading the dash spec i havent found a clear explanation of `Location` tag with relative url
but imo could have sense merge the `Location` relative url with the base domain url from the downloaded manifest url
from your attached manifest an example become as follow:

first manifest url (your downloaded mpd):
https://livem-akc-na.media.hulustream.com/v1/live/dash/initial/531124fc-2566-4206-b155-1b4f216e9ec8/manifest.mpd?acquired_source_name=ABC_KOMO_SEA_MMA_CLT2-USW2&cdns=sf&cluster=blue&cver=0&duration=10800s&manifest_cdn=ak&origin=us-west-2&patch=true&query_params_v2=false&repeat=true&segment_type_enabled=false&stream_filter=fhd_high_stereo&uas_enabled=false&authToken=1698533927_86b00f91d453bf82a5677d3a437f87f55602c402c47e371595e17a151340dd57

nexy update manifest url (base domain taken from above + location tag):
https://livem-akc-na.media.hulustream.com/v1/live/dash/continue/531124fc-2566-4206-b155-1b4f216e9ec8/manifest.mpd?cdns=sf&amp;cluster=blue&amp;origin=us-west-2&amp;duration=10800s&amp;manifest_cdn=ak&amp;repeat=true&amp;patch=true&amp;hpbsid_enabled=false&amp;uas_enabled=false&amp;segment_type_enabled=false&amp;query_params_v2=false&amp;unencrypted=false&amp;cver=0&amp;acquired_source_name=ABC_KOMO_SEA_MMA_CLT2-USW2&amp;stream_filter=fhd_high_stereo&amp;prev_start=1698533614322&amp;prev_boundary_start=1697130402514&amp;prev_pts_values=AAC_1_CMAF_CENC_CTR%3D68325770240%7CH264_1_CMAF_CENC_CTR%3D85407211890&amp;authToken=1698534232_cf0ec596424db8ccae76227b5f0f506210b14e605f7c02bb59aec3cbfa912859

**Comment by CastagnaIT** [comment]
hoping its not the only problem for your stream i made a fix
you can find some test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1409/1/artifacts

**Comment by kcook98765** [comment]
That did work, in that it followed the relative Location URL's !

There is something else going on though with partial update Manifests.

The initial Manifest loads and playback begins.

But, something is wrong with the update manifests.

After the first Update manifest is downloaded, I get:

`2023-10-30 11:52:32.504 T:3580    debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://livem-akc-na.media.hulustream.com/v1/live/dash/continue/531124fc-2566-4206-b155-1b4f216e9ec8/manifest.mpd?cdns=sf&cluster=blue&origin=us-west-2&duration=10800s&manifest_cdn=ak&repeat=true&patch=true&hpbsid_enabled=false&uas_enabled=false&segment_type_enabled=false&query_params_v2=false&unencrypted=false&cver=0&acquired_source_name=ABC_KOMO_SEA_MMA_CLT2-USW2&stream_filter=fhd_high_surround&prev_start=1698691927479&prev_boundary_start=1697130402514&prev_pts_values=AAC_1_CMAF_CENC_CTR%3D75924801536%7CEC3_1_CMAF_CENC_CTR%3D75924801575%7CH264_1_CMAF_CENC_CTR%3D94906001190&authToken=1698692545_851ff4108edb841b7c164a9f5335a64970bf810c13b9196511c2afd40f16bd25 (downloaded 2460 byte, speed 3322.00 byte/s)
2023-10-30 11:52:32.505 T:3580    debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: C:\Users\kcook\AppData\Roaming\Kodi\userdata\addon_data\inputstream.adaptive\manifests\manifest_1698691952.txt
2023-10-30 11:52:32.505 T:3580  warning <general>: AddOnLog: inputstream.adaptive: adaptive::CDashTree::ParseTagAdaptationSet: Skipped AdaptationSet with id: "4289974598", has no representations.
2023-10-30 11:52:32.505 T:3580  warning <general>: AddOnLog: inputstream.adaptive: adaptive::CDashTree::ParseTagAdaptationSet: Skipped AdaptationSet with id: "2008774996", has no representations.
2023-10-30 11:52:32.505 T:3580  warning <general>: AddOnLog: inputstream.adaptive: adaptive::CDashTree::ParseTagAdaptationSet: Skipped AdaptationSet with id: "901119627", has no representations.
2023-10-30 11:52:32.505 T:3580  warning <general>: AddOnLog: inputstream.adaptive: No periods in the manifest`

I am including the Initial Manifest as well as the first Update Manifest here.

[manifest_1698691946.txt](https://github.com/xbmc/inputstream.adaptive/files/13208895/manifest_1698691946.txt)
[manifest_1698691952.txt](https://github.com/xbmc/inputstream.adaptive/files/13208896/manifest_1698691952.txt)

The update Manifest indeed contains no representations , but the Period, AdaptationSet, SegmentTemplate and SegmentTimeline sections do appear.

Should this be enough information for the update Manifest to function?
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/13208912/kodi.log)

**Comment by CastagnaIT** [comment]
thanks for new provided info helped a lot,
by looking at your attached manifest i think this is a new use case, that isnt currently supported

IIRC the current implementation assume to have a full live update manifest data and not a partial one with only segments, therefore as we can see the update fails

this will require some changes in to
CDashTree::RefreshLiveSegments to handle manifest with only segments
and some little adjustments in how we parse the manifest data to prevent that the parsing stop the manifest update due to missing data

so a fix will be possible

PS. Note that this type of improvement will be able to be made for Kodi 21 and not on Kodi 20 due to many non-backportable changes

**Comment by kcook98765** [comment]
Thank You!

I will be available to test changes for this when you have some ready.

**Comment by kcook98765** [comment]
Any possibility of getting example initial manifest and an update manifest that "work" for IA currently. They don't need to be able to be played, I just want to review the XML and experiment with a proxy for Hulu Partial updates to see if I can work out a way to convert the Hulu partial updates into a form IA currently understands to patch this issue until IA can handle partial updates?

I have been testing many variations to try and do this, but an example set would help me greatly , and then I might be able to make this work.

Thank you!

**Comment by CastagnaIT** [comment]
not all live manifests are the same, so comparing with others services may cause confusion
you already have your manifests above

its possible that just coping the relative `Representation` tags from the first manifest to future update manifests, ofc by respecting the parent AdaptationSet id's, could temporary solve the problem until a real fix is implemented

but i think you will need also find a solution for the relative urls, since with a proxy more likely they will be broken

**Comment by kcook98765** [comment]
Thank you for the feedback. I had tried adding just the missing Representation elements (in the correct Adaption ID areas) from a copy of the original manifest when it gets to the proxy where I check matching period and adaptation id to determine which representation elements to insert , but then the stream halts within 10 seconds (even while additional update manifests continue to be downloaded via the "Location" tag which has the proper proxy adjustment.

That is why I wanted examples, as I was going to examine which elements/attributes were used in both Initial and update manifests to see if there were other pieces of information I need to modify in the partial update manifests.

Some other things I had tried were to force MPD to have attribute type="dynamic" (as it is in intial, but not partial manifests). I also tried many other adjustments like this, but can't seem to find the magic combination of changes to get it to work.

The proxy is solid and doing it's job, requests are coming back with 200 status, saved debug manifests are looking as expected with each change, so I think it is some other key piece(s) of data that I need to account for.

Also wondering if maybe partial update in IA is not triggered without a "start_number" as mentioned in IA code:

// YouTube needs segment start number as parameter
  bool urlHaveStartNumber = manifestParams.find("$START_NUMBER$") != std::string::npos;

and

if (urlHaveStartNumber) // Partitial update

I have not tried this yet, was thinking of adding in this to the url (and stripping it when proxy contacts service).

**Comment by kcook98765** [comment]
Been trying all kinds of adjustments based on initial manifest. MPD "type" attribute added. Representation elements added. BaseURL added. SegmentTemplate attributes added (plus calculating a statrNumber to insert) .

Still not quite working as it cuts out quickly, but logs at least show :

2023-11-09 17:01:10.388 T:943     debug <general>: AddOnLog: inputstream.adaptive: RefreshLiveSegments: Full update with start number (repr. id: AAC_1_CMAF_CENC_CTR_128K current start:1685)
2023-11-09 17:01:10.388 T:943     debug <general>: AddOnLog: inputstream.adaptive: RefreshLiveSegments: Full update with start number (repr. id: AAC_1_CMAF_CENC_CTR_64K current start:1685)
2023-11-09 17:01:10.388 T:943     debug <general>: AddOnLog: inputstream.adaptive: RefreshLiveSegments: Full update with start number (repr. id: H264_1_CMAF_CENC_CTR_192K current start:2)

still plugging away, but running out of things to try.

Please do give me an example initial and partial update manifest I can study, even if it is another service as it might shed a light on some of the attributes, etc that may help me.

Thanks!

**Comment by matthuisman** [comment]
have you tried just removing Location tag?
Or having your partial update just return the latest full manifest?

**Comment by kcook98765** [comment]
It is a live feed, so fairly sure it must use Location, as initial manifest never updates after first call.

Also, I forked and am testing changes in your proxy code to do this (bit hacky as I test things), you can see current changes at:

https://github.com/matthuisman/slyguy.addons/compare/master...kcook98765:slyguy.addons:master

I collect various data from initial manifest, then re-route update manifests (currently triggered on "continue" in the url to a new section of code where I make adjustments to the update manifest before returning it to IA

I'll be out until tomorrow now, but any hints would be helpful if you spot something, thanks!

**Comment by matthuisman** [comment]
the master manifest must change for new clients playing right?

If the params in the manifest url control what it returns, then have the proxy call wherever to get the latest url and fetch that and return that?

My proxy used to just remove Location and it did work for some services

**Comment by CastagnaIT** [comment]
> Some other things I had tried were to force MPD to have attribute type="dynamic" (as it is in intial, but not partial manifests). I also tried many other adjustments like this, but can't seem to find the magic combination of changes to get it to work.

yes `type="dynamic"` is always mandatory for live streams, must be specified also on all manifest updates
but seem that your service dont follow exactly DASH specs, since its missing
then i dont know the real service intention

alternatively it could mean that the live manifest it is turned into VOD content from the next manifest update (where this usually should be specified as `type="static"`) hovewer the conversion from "live to VOD" is not supported on ISA, if it works is by luck,
so adding `type="dynamic"` might be ok

> Please do give me an example initial and partial update manifest I can study, even if it is another service as it might shed a light on some of the attributes, etc that may help me.

take note that there are many different manifest use cases for live content, and many DASH features for live content are not supported yet on ISA,
if could help this is a sample stream that could be similar but without Location tag
https://livesim.dashif.org/livesim/segtimeline_1/testpic_2s/Manifest.mpd
i dont have nothing else similar

> Also wondering if maybe partial update in IA is not triggered without a "start_number" as mentioned in IA code:

this is a specific youtube case, it should be out-of-spec

**Comment by kcook98765** [comment]
Thank you both for the input. This information helps, and after reviewing the new example manifest and more of the code in the proxy, I have spotted a few more things to try and adjust. If I can get this working I will report back the details so that you can see how to handle this service partial updates in the future.

**Comment by kcook98765** [comment]
Success! First time I have gotten a hulu stream to last over 5 minutes! Currently past 10 minutes and allowing to run to see if anything stops working.

I can try and check each change to see if anything is not needed, but current working changes to proxy are at :

https://github.com/matthuisman/slyguy.addons/compare/master...kcook98765:slyguy.addons:master

I can write up the exact details of how the partial update manifests are modified to get them to work if it would help.

@matthuisman , I'm sure additional tweak would be needed like the trigger of the modification routine I added (currently just looks for "continue" in url, proabably better to also verify it is a Hulu domain, etc so as not to affect other services.

**Comment by kcook98765** [comment]
Here is the initial manifest (unchanged other than original proxy adjustments) and the first partial update manifest (which originally looked very sparse, like the one I uploaded earlier in this issue), now modified by the code changes to be much more detailed based mostly on the original manifest details, though I did have to add to Period start="PT0S".

[manifest_1699648630.txt](https://github.com/xbmc/inputstream.adaptive/files/13323111/manifest_1699648630.txt)

[manifest_1699648635.txt](https://github.com/xbmc/inputstream.adaptive/files/13323112/manifest_1699648635.txt)

**Comment by kcook98765** [comment]
Ran just over an hour and I stopped it. I see no major issues in kodi log, but there were a lot of 

"Received status code 204 which is in the retry list. Retrying" noted 
(code I modified in proxy where it retries failed look ups, I specifically had added 204 to also re-request after a short sleep.)

I'm thinking this is due to requesting the next partial update too soon, so server responds with no-content/204 , maybe need to adjust something to help avoid this?

In this 1 hour test, 723 Manifests including the initial one were processed and stream was solid!

**Comment by kcook98765** [comment]
fyi, some other channels seem to not even start based on initial manifest, but it looks like other issues, like :

2023-11-10 14:02:16.235 T:949     debug <general>: AddOnLog: inputstream.adaptive: Download finished: http://127.0.0.1:52103/https://livem-akc-na.media.hulustream.com/v1/live/dash/initial/22e65e4b-5d12-4bbc-a8c3-3085a9d1d27b/manifest.mpd?acquired_source_name=DSC_ANIMAL_WEST_MMA_CLT2-USW2&cdns=sf&cluster=green&cver=0&duration=10800s&manifest_cdn=ak&origin=us-west-2&patch=true&query_params_v2=false&repeat=true&segment_type_enabled=false&stream_filter=fhd_high_stereo&uas_enabled=false&authToken=1699654030_5efc22f78018804e8f6e52f147c3be1ee70f6815efee8c4600ed11f6cf17bea2|User-Agent=Mozilla/5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome/94.0.4606.81%20Safari/537.36 (downloaded 250881 byte, speed 60269.00 byte/s)
2023-11-10 14:02:16.246 T:949     debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: /storage/.kodi/userdata/addon_data/inputstream.adaptive/manifests/manifest_1699653736.txt
2023-11-10 14:02:16.276 T:949     debug <general>: Thread Terminating with Exception: std::bad_alloc
2023-11-10 14:02:27.620 T:913     debug <general>: slyguy.hulu - SIGNAL: after_dispatch
2023-11-10 14:02:27.623 T:913     debug <general>: slyguy.hulu - SIGNAL: on_close

but his doesn't appear to be related to changes I made which mainly involve the partial update files which did not even get a chance to be called in this test. I am running RPI3b so it maybe also an issue.

And maybe too early to celebrate, as after a reboot I tried same channel again, but no audio, and auto ended after a minute or so.

**Comment by kcook98765** [comment]
looks like part of the audio issue was that channel program had switched to audio EC3 , so I disabled that one via settings, still not quite working, will continue to work on this though.

**Comment by kcook98765** [comment]
I have redone the logic.

Now it basically takes all the attributes and missing elements (except the segment &lt;S&gt; ones) from the initial manifest and applies to the update manifest.

Also testing on Windows now.

Now it works, though The kodi timeline shows starting at 2:59:30 and plays until 2:59:45, but if I rewind it seems to play normally... so maybe there is a small tweak to get Kodi to start at the beginning rather than near the end (maybe something I am copying over from the initial manifest or other adjustment needed)?

The now working change in my fork of the proxy is at:

https://github.com/kcook98765/slyguy.addons/commit/acdd843e94f7078c8313d499f74b90aac77de0ba

I have also tested other channels, including ones that have multiple periods and adaptation sets , and so far they all play, and play past the hard 5 minute limit that was being encountered before!

Just the starting timeline in Kodi is "odd"

**Comment by CastagnaIT** [comment]
now that i see there is also `presentationTimeOffset` tag currently not supported
that could make problem with stream syncs that could be the cause of audio problems
(for `presentationTimeOffset` tag there are already opened another 2 issues)

i you have copied all things from initial manifest, more likely you have to pay attention to Period "start" value

**Comment by kcook98765** [comment]
Thank you. What I copied was the manifest after manipulations that include stripping out presentationTimeOffset. I thinkmy only issue is in now supplying or calculating the Period "start" value...  Since they do not supply a start value in the partial updates, I am trying to calculate ones and getting close.

**Comment by kcook98765** [comment]
https://github.com/kcook98765/slyguy.addons/commit/acdd843e94f7078c8313d499f74b90aac77de0ba is where I am at end of today.

IA saved manifests mostly work, but occasional buffering and sometimes halting.

initial manifest:

[manifest_1700016598.txt](https://github.com/xbmc/inputstream.adaptive/files/13359469/manifest_1700016598.txt)

first partial manifest:

[manifest_1700016602.txt](https://github.com/xbmc/inputstream.adaptive/files/13359477/manifest_1700016602.txt)

**Comment by kcook98765** [comment]
Running into a wall here. I copy the (modified already, like removing presentationTimeOffset, etc) the initial manifest (attached below) .

The next partial update manifest is scanned and all elements are compared to initial manifest and any missing attributes are set (like MPD attribute "type" set to initial type which is "dynamic").

Also any missing elements like representation, etc are inserted from the initial manifest.

When start stream, the initial manifest is read and playback begins.

And then the first partial update manifest is downloaded, the above changes applied, then sent to IA.

But then:

`2023-11-15 17:03:32.060 T:26816   debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: C:\Users\kcook\AppData\Roaming\Kodi\userdata\addon_data\inputstream.adaptive\manifests\manifest_1700096612.txt

2023-11-15 17:03:32.060 T:26816   debug <general>: AddOnLog: inputstream.adaptive: adaptive::CDashTree::RefreshLiveSegments: Full update without start number (repr. id: H264_1_CMAF_CENC_CTR_192K current start: 2156)

2023-11-15 17:03:32.060 T:26816   debug <general>: AddOnLog: inputstream.adaptive: adaptive::CDashTree::RefreshLiveSegments: Full update without start number (repr. id: AAC_1_CMAF_CENC_CTR_64K current start: 2156)

2023-11-15 17:03:32.859 T:3844    debug <general>: ------ Window Init (VideoOSD.xml) ------

2023-11-15 17:03:32.859 T:3844     info <general>: Loading skin file: VideoOSD.xml, load type: KEEP_IN_MEMORY

2023-11-15 17:03:32.880 T:3844    debug <general>: ------ Window Init (DialogSeekBar.xml) ------

2023-11-15 17:03:32.881 T:3844    debug <general>: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------

2023-11-15 17:03:33.603 T:3160    debug <general>: AddOnLog: inputstream.adaptive: adaptive::AdaptiveStream::ensureSegment: [AS-2] Begin WaitForSegment stream H264_1_CMAF_CENC_CTR_192K

2023-11-15 17:03:33.704 T:38864   debug <general>: CurlFile::XFILE::CCurlFile::Open - <http://127.0.0.1:52103/https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___>

2023-11-15 17:03:33.716 T:29268   debug <general>: script.module.slyguy - REQUEST IN: https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___ (GET)

2023-11-15 17:03:33.716 T:29268   debug <general>: script.module.slyguy - REQUEST OUT: https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___ (GET)

2023-11-15 17:03:33.881 T:29268   debug <general>: script.module.slyguy - RESPONSE IN: https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___ (200)

2023-11-15 17:03:33.881 T:29268   debug <general>: script.module.slyguy - RESPONSE OUT: https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___ (200)

2023-11-15 17:03:33.999 T:38864   debug <general>: AddOnLog: inputstream.adaptive: [AS-2] Download finished: http://127.0.0.1:52103/https://live-f.hulustream.com/v2/__REMOVED AS NOT NEEDED___ (downloaded 201583 byte, speed 685656.00 byte/s)

2023-11-15 17:03:33.999 T:1972    error <general>: AddOnLog: inputstream.adaptive: CFragmentedSampleReader::GetFragmentInfo: Can't get FragmentSampleTable from track 1
`
Note the error is right after a good download of the first segment in the partial update manifest

The redacted urls above were :

https://live-f.hulustream.com/v2/531124fc-2566-4206-b155-1b4f216e9ec8/199fbb1d-6ccb-3c61-b0e5-d9fac9c70e69/H264_1_CMAF_CENC_CTR_192K/pts_70380430120.m4s?token=1700139808_608ba82a0fc81293a1c7b9b39f8239f20b300731
which is the first segment in the first partial update manifest.

I have tried setting Period start to same as initial manifest and also not setting a start at all (as it comes) in the partial update manifest.

Perhaps there are other attributes/elements that are causing this, or something else I need to look into.

What does this error mean, is there some other attribute to add or remove or modify to get further here?

Initial Manifest:
[manifest_1700096608.txt](https://github.com/xbmc/inputstream.adaptive/files/13371269/manifest_1700096608.txt)

first partial update manifest (after processing to make it "complete" :

[manifest_1700096612.txt](https://github.com/xbmc/inputstream.adaptive/files/13371275/manifest_1700096612.txt)

Thank You!

**Comment by kcook98765** [comment]
one additional line after the above logs :

2023-11-15 17:03:35.897 T:24632   debug <general>: CPtsTracker: detected pattern of length 1: 33366.67, frameduration: 33366.666667

And then it goes on to get the next partial updates but I never see this error again, though do see "Full update without start number ..." for the rest of the partial update manifests.

**Comment by kcook98765** [comment]
I don't think I need any more help here.

Thank you for all you have shared.

I believe I have this worked out via Proxy to translate sparse update manifests into form IA can process.

Sorry to lead this issue off topic slightly. I can start a new one specific to enhancement of sparse partial update manifests if you like to close this one.

I will continue notes on my fix for this over at Slyguy :

https://github.com/matthuisman/slyguy.addons/issues/584#issuecomment-1817352884

Thanks again and have a great weekend!

**Comment by kcook98765** [comment]
Closing this, as the relative url issue was solved.
