### ISSUE TITLE
CCurlFile: Open failed with code 0

### ISSUE THREAD

**Issue by JBeyens** [peak3d/inputstream.adaptive#1413]
## Description
From user perspective: I am using an addon (tv vlaanderen) and I select a channel in it (VTM 2, Nickelodeon, ...) and for that channel I select anything (watch live, Restart, TV guide or replay), then KODI crashes. It seems that for example VTM 2 does work via another add-on (VTM Go) but I need the TV Vlaanderen app to work for other channels.

Technical part: Looking at the kodi.log (full log in attachment), I can see several errors appearing just before the crash:
 - error <general>: AddOnLog: inputstream.adaptive: The parameter "full" is no longer supported.
 - error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x15fa8272120) Failed: Stream error in the HTTP/2 framing layer(92)
 - error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://tvvvideolive3.solocoo.tv/blueskytvvlive7dash/bluevtm3hd/Manifest.mpd> Failed with code 0
 - error <general>: AddOnLog: inputstream.adaptive: UTILS::CURL::CUrl::Open: CURLOpen failed
 - error <general>: AddOnLog: inputstream.adaptive: Download failed, internal error: https://tvvvideolive3.solocoo.tv/blueskytvvlive7dash/bluevtm3hd/Manifest.mpd

## Expected Behavior
I expected the add-on to play/stream the selected stream.

## Possible Fix
Workaround or local fix can also help me out a lot. Please tell me what I can do.

### MPD/M3U8s/ISM
The Kodi.log indicates that the MPD file can be found here: https://tvvvideolive3.solocoo.tv/blueskytvvlive7dash/bluevtm2hd/Manifest.mpd
I went through it, but don't understand enough to know what I should be looking for.

### Your Environment
 - Operating system version/name: Windows 11 Pro X64
 - Kodi version: kodi-21.0-Omega_beta1-x64 (I updated to get the latest inputstream.adaptive version which solves some other issues for me)
 - inputstream.adaptive version: 21.3.0

**Comment by CastagnaIT** [comment]
the crash has been already solved on main branch and the fix ~has not been released yet~

UPDATE: fix released

> Stream error in the HTTP/2 framing layer(92)

im not aware of specifics solutions for this error
it could be a network problem, could be solved for example by resetting your router (turn off/on)
or a server side problem

> error : AddOnLog: inputstream.adaptive: The parameter "full" is no longer supported.

for this one, it should not be a big problem, but the dev of that addon must fix/update his addon to avoid this error on log
by reading changes done on ISA for Kodi 21 on Wiki integration page

**Comment by CastagnaIT** [comment]
closed as no one know what suggest you to solve the HTTP error
