### ISSUE TITLE
Netflix error playback on kodi 18 armv7

### ISSUE THREAD

**Issue by meeuuh92** [peak3d/inputstream.adaptive#1418]
### Describe the bug
Here is a clear and concise description of what the problem is:
Since some days, i'm not able to play video on netflix on kodi leia... I try several things (logout..., reinstall last lib drm..), so i think it's inputstream adaptative which has got'problem on leia? 

Regards,

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
there is no more support to n€tflix addon for Kodi 18 Leia,
the development on that old ~platform~ kodi version has been full stopped on last years
