### ISSUE TITLE
InputStream Adaptive: No MOOV in stream!

### ISSUE THREAD

**Issue by FIoannides** [peak3d/inputstream.adaptive#142]
I know there is already an open issue related to the NBA League Pass add-on, but the issue I am facing seems a bit different. Video doesn't start at all and seems that the reason is that the MOOV atom is not found. If it helps I am using Rpi2 with Libreelec v9 alpha (Kodi 18, Leia). Full log below.

>21:14:44.831 T:1796850560   DEBUG: ##### NBA League Pass: the url of video 0041700122 is https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250
21:14:44.910 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: Platform information: ('Linux', 'LibreELEC', '4.14.32', '#1 SMP Sat Apr 7 21:27:36 BST 2018', 'armv7l', '')
21:14:44.911 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
21:14:44.914 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","type":"kodi.inputstream"}}}
21:14:44.916 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive is installed.
21:14:44.916 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'properties': ['enabled'], 'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
21:14:44.918 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","enabled":true,"type":"kodi.inputstream"}}}
21:14:44.919 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 999.2.2.14 is enabled.
21:14:44.920 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 999.2.2.14 is installed and enabled.
21:14:45.008 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.009 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.014 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.014 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.020 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.021 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.024 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.025 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.027 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: Found Widevine binary at /storage/.kodi/cdm/libwidevinecdm.so
21:14:45.336 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.336 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.343 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.343 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.347 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.347 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.351 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:45.351 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:45.455 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd executed successfully.
21:14:45.455 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd output:
                                                linux-vdso.so.1 (0x7eb65000)
                                                /usr/lib/libarmmem-v7l.so (0x76736000)
                                                libpthread.so.0 => /usr/lib/libpthread.so.0 (0x7670d000)
                                                libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x765bf000)
                                                libdl.so.2 => /usr/lib/libdl.so.2 (0x765ac000)
                                                librt.so.1 => /usr/lib/librt.so.1 (0x76595000)
                                                libnss3.so => /usr/lib/libnss3.so (0x764a2000)
                                                libnssutil3.so => /usr/lib/libnssutil3.so (0x76471000)
                                                libnspr4.so => /usr/lib/libnspr4.so (0x7643d000)
                                                libm.so.6 => /usr/lib/libm.so.6 (0x763ba000)
                                                libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7638a000)
                                                libc.so.6 => /usr/lib/libc.so.6 (0x7624e000)
                                                /lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0x76ed2000)
                                                libplc4.so => /usr/lib/libplc4.so (0x76ef9000)
                                                libplds4.so => /usr/lib/libplds4.so (0x76ef5000)
21:14:45.456 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: There are no missing Widevine libraries! :-)
21:14:45.457 T:1796850560   DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting definitions
21:14:45.457 T:1796850560   DEBUG: CAddonSettings[script.module.inputstreamhelper]: trying to load setting definitions from old format...
21:14:45.458 T:1796850560   DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting values
21:14:45.459 T:1796850560   DEBUG: [script.module.inputstreamhelper-0.3.3]: Widevine update check was made on 2018-04-18T17:49:38
21:14:45.567 T:1796850560    INFO: CPythonInvoker(16, /storage/.kodi/addons/plugin.video.nba/main.py): script successfully run
21:14:45.593 T:1805243264   DEBUG: Thread scriptobs 1805243264 terminating
21:14:45.594 T:1941629536    INFO: easy_acquire - Created session to https://neunlds348.akamaized.net
21:14:45.773 T:1796850560    INFO: Python script stopped
21:14:45.773 T:1796850560   DEBUG: Thread LanguageInvoker 1796850560 terminating
21:14:45.945 T:1941629536   DEBUG: CCurlFile::GetMimeType - https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250 -> application/dash+xml
21:14:45.971 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers(https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250)
21:14:45.971 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
21:14:45.972 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
21:14:45.972 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
21:14:45.972 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
21:14:45.972 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
21:14:45.972 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
21:14:45.973 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
21:14:45.973 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
21:14:45.973 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
21:14:45.973 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
21:14:45.974 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
21:14:45.974 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
21:14:45.974 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
21:14:45.974 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
21:14:45.974 T:1941629536   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
21:14:45.975 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
21:14:45.975 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
21:14:45.975 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
21:14:45.975 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
21:14:45.975 T:1941629536   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
21:14:45.975 T:1941629536  NOTICE: VideoPlayer::OpenFile: https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250
21:14:45.975 T:1941629536   DEBUG: OnPlayBackStarted: CApplication::OnPlayBackStarted
21:14:45.976 T:1796850560   DEBUG: Thread VideoPlayer start, auto delete: false
21:14:45.976 T:1796850560  NOTICE: Creating InputStream
21:14:45.978 T:1796850560   DEBUG: ADDON: Dll Initializing - InputStream Adaptive
21:14:45.978 T:1796850560   DEBUG: SECTION:LoadDLL(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.2.14)
21:14:45.979 T:1796850560   DEBUG: Loading: /usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.2.14
21:14:45.993 T:1587364736   DEBUG: Loading settings for https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250
21:14:46.002 T:1941629536   DEBUG: CGUIInfoManager::SetCurrentMovie(https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250)
21:14:46.024 T:1796850560    INFO: AddOnLog: InputStream Adaptive: SetVideoResolution (1920 x 1080)
21:14:46.024 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Open()
21:14:46.024 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_key: [not shown]
21:14:46.024 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_type: com.widevine.alpha
21:14:46.024 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_type: mpd
21:14:46.024 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_update_parameter: full
21:14:46.026 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Initial bandwidth: 4000000
21:14:46.027 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.027 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.028 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTION selected: 0
21:14:46.030 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.030 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.031 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTIONSECURE selected: 3
21:14:46.032 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.032 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.034 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: STREAMSELECTION selected: 0
21:14:46.035 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.035 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.038 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.038 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.040 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /usr/lib/kodi/addons/inputstream.adaptive/
21:14:46.064 T:1874506624   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
21:14:46.064 T:1874506624   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
21:14:46.078 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /usr/lib/kodi/addons/inputstream.adaptive/libssd_wv.so
21:14:46.078 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
21:14:46.080 T:1796850560   DEBUG: CurlFile::Open(0x7156df78) https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250
21:14:46.086 T:1874506624   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
21:14:46.086 T:1874506624   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
21:14:46.164 T:1941629536   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:14:46.394 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250
21:14:46.490 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Download https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250 finished
21:14:46.491 T:1796850560    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Download speed: 0.0000 Bytes/s
21:14:46.492 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.492 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.494 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:14:46.494 T:1796850560   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
21:14:46.496 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
21:14:46.503 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Searching PSSH data in FILE
21:14:46.505 T:1796850560   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
21:14:46.505 T:1796850560   DEBUG: CurlFile::Open(0x7156df78) https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/3_41700122_mia_phi_2017_b_whole_1_3000_video/Time=init.m4s
21:14:46.544 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Download https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/3_41700122_mia_phi_2017_b_whole_1_3000_video/Time=init.m4s finished, average download speed: 269264.4835
21:14:46.544 T:1796850560   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
21:14:46.545 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
21:14:46.548 T:1796850560   ERROR: CVideoPlayer::OpenInputStream - error opening [https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/04/16/nlncp/41700122/41f9bbe0-0204-3de3-f896-7a63d05c25c8/v1/stream/3_41700122_mia_phi_2017_b_whole_1_ceddash.mp4.mpd?h=7d63c25a214d90204c0c63c5f3b5f50b.1524086084772&hdnea=exp=1524086144~acl=/*~hmac=DC4ECD8CFC0EF223563EDE1830D7160AC3DFE98F1664D87A7AC1AD8E16DEA9DD&nltid=nba&nltdt=137&uid=2466250]
21:14:46.548 T:1796850560  NOTICE: CVideoPlayer::OnExit()
21:14:46.549 T:1796850560   DEBUG: AddOnLog: InputStream Adaptive: Close()
21:14:46.549 T:1796850560   DEBUG: SECTION:UnloadDll(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.2.14)
21:14:46.549 T:1587364736   DEBUG: DoWork - Saving file state for video item plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%2876ers%29&url=&start_time=1523923255000&video_id=0041700122&video_type=archive&mode=playgame&duration=10400000&video_ishomefeed=1
21:14:46.550 T:1796850560    INFO: ADDON: Dll Destroyed - InputStream Adaptive
21:14:46.550 T:1796850560   DEBUG: Thread VideoPlayer 1796850560 terminating

**Comment by JinRonin** [comment]
@peak3d 
effective url forward slash issue

@FIoannides 
if you currently need a working build it should work with #0404 and before

**Comment by FIoannides** [comment]
Thank you @JinRonin, I can confirm build #0404 works great.

**Comment by JinRonin** [comment]
fixed with https://github.com/peak3d/inputstream.adaptive/commit/cd6d9c9884ae97fa6d31071ca4dff0b6004e51d6

**Comment by dvaai** [comment]
Good day, 

I am having an issue with my DSTV Now addon

I have attached a log file:

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/10404398/kodi.log)

Please can some one explain what is going on?

Regards

**Comment by glennguy** [comment]
@dvaai please open a new issue, commenting on years old closed issues is not good.

We will also need a log with debug logging enabled to help
