### ISSUE TITLE
widevine video not playing in kodi only, other apps playing just fine

### ISSUE THREAD

**Issue by aicynide** [peak3d/inputstream.adaptive#1421]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm trying to play from .strm file

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiIzMjk1ZTdkZS1hM2U1LTRiNmEtODEwNC1mNmZiNzVhNGFjM2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNjk2OTI1LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjEwNTI1LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.Sl6HFcO4DSF-QcqQMjCWqcchd4grCLTbrY4uqMyUsnA
https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_405/output/manifest.mpd
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play without any error like OTT Navigator/Tivimate app

## Actual Behavior

Unknown error

## Possible Fix

Check .strm file
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiIzMjk1ZTdkZS1hM2U1LTRiNmEtODEwNC1mNmZiNzVhNGFjM2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNjk2OTI1LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjEwNTI1LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.Sl6HFcO4DSF-QcqQMjCWqcchd4grCLTbrY4uqMyUsnA
https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_405/output/manifest.mpd
```

### To Reproduce

1. Create a .strm file
2. .strm file content
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiIzMjk1ZTdkZS1hM2U1LTRiNmEtODEwNC1mNmZiNzVhNGFjM2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNjk2OTI1LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjEwNTI1LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.Sl6HFcO4DSF-QcqQMjCWqcchd4grCLTbrY4uqMyUsnA
https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_405/output/manifest.mpd
```

3. Use India vpn
4. Try to play it

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/13438708/kodi.log)

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiIzMjk1ZTdkZS1hM2U1LTRiNmEtODEwNC1mNmZiNzVhNGFjM2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNjk2OTI1LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjEwNTI1LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.Sl6HFcO4DSF-QcqQMjCWqcchd4grCLTbrY4uqMyUsnA
https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_405/output/manifest.mpd
```

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiIzMjk1ZTdkZS1hM2U1LTRiNmEtODEwNC1mNmZiNzVhNGFjM2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNjk2OTI1LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjEwNTI1LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.Sl6HFcO4DSF-QcqQMjCWqcchd4grCLTbrY4uqMyUsnA
https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_405/output/manifest.mpd

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10
 - Kodi version: 20.2 (latest)
 - inputstream.adaptive version: latest from kodi repo

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by aicynide** [comment]
@CastagnaIT 
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/13438714/kodi.log)
New license key `https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000252&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiI0NjkwY2Y1Yy1lNzhjLTRjZWEtYWM4My00ODA3MjNhYTg5ZDciLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNzM5MTI3LCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjUyNzI3LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.S3JqggBFvFWXCqf0tWhC2-H8N1WOCzuOdi57s-0LXZo`

**Comment by aicynide** [comment]
mpd - https://bpprod3linear.akamaized.net/bpk-tv/irdeto_com_Channel_166/output/manifest.mpd 


License server - https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000119&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiI5NjFlOTk3MS1hNGFjLTRlZDMtODk2Mi1mNmMzOTEwNGNmNGYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAwNzQwMjAwLCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwNjUzODAwLCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.jQ-T9Nuky6gEArHOolp48au3R-fIMRBrtj4e6GyACFc

I tested this in https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html
Playing just fine but error in kodi 
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/13438947/kodi.log)

**Comment by CastagnaIT** [comment]
from the log there is no specified any details about the "error"
apparently stops before downloading the manifest
maybe its required specify the user agent by using `inputstream.adaptive.manifest_headers` that is missing

however the log is of kodi 20,
huge improvements has been done on Kodi 21 that cannot be backported
then we have to start investigate for problems on Kodi 21

please test on Kodi 21,
if problem still occurs provide a log of Kodi 21 and also attach the manifest files

i tried download the manifest but looks geolocked and my VPN dont support India
i tried also https://reference.dashif.org player without success give me errors

**Comment by aicynide** [comment]
Yes its geolocked

**Comment by aicynide** [comment]
Exact same error in Omega, can't play it

**Comment by aicynide** [comment]
Sorry license_key was expired.
Tried in Omega, playing fine. Hurray!! Nexus has issue

**Comment by aicynide** [comment]
![19_Kodi](https://github.com/xbmc/inputstream.adaptive/assets/97217381/de844a38-6691-402d-8a85-909d03568f99)

**Comment by aicynide** [comment]
![-_Kodi](https://github.com/xbmc/inputstream.adaptive/assets/97217381/f536b578-6cfd-4cf7-9ef6-3f1ea58dd6eb)
While there is Multiple audio track, why only 1 video Quality?
It has 4 video quality but kodi auto selecting any random Video Quality, how do i change video quality?

**Comment by CastagnaIT** [comment]
> While there is Multiple audio track, why only 1 video Quality?

to use Kodi player GUI video stream list, you have to set on ISA settings, "Manual OSD" stream selection
but for that is better set "Ask quality" stream selection

if after changed that setting the quality still be 1
i don't know without being able to see the manifest

but if on Omega works means that is one of the things that has been improved and that cannot be backported

**Comment by aicynide** [comment]
Manifest- https://deltatesttatasky.akamaized.net/out/i/968284.m3u8
 License url https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001074&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiI4OTJlZThmOS1kNGJjLTRkYzQtYTE3ZC1hMjE2MDEwZjlhNmQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAxMDM0MzQwLCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAwOTQ3OTQwLCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.DvkizqOJrn43ZGc_sNdTRuNubtxiKEcIVIP4_AQRzb4

**Comment by aicynide** [comment]
Another fix needed for Omega is PVR 1024 characters limit. 
IPTV providers aren't aware about `inputstream.adaptive.license_url` and `inputstream.adaptive.license_url_append` so they can't provide Playlist with `inputstream.adaptive.license_url_append`
Will we have to wait for Kodi 22 for the PVR 1024 characters limit fix?

**Comment by glennguy** [comment]
> IPTV providers aren't aware about inputstream.adaptive.license_url and inputstream.adaptive.license_url_append so they can't provide Playlist with inputstream.adaptive.license_url_append
Will we have to wait for Kodi 22 for the PVR 1024 characters limit fix?

IPTV providers will have to adapt eventually. They need to follow us, we can't be beholden to them.
Yes it seems Kodi 22 will have the fix but it's too late for Kodi 21.
My suggestion:
Write a simple proxy service to point m3u8 refreshes to. This proxy should fetch the m3u8 from tata service, and rewrite the kodiprops to use the new url_append way where appropriate.

**Comment by CastagnaIT** [comment]
> so they can't provide Playlist with

there is a big difference from not being able to, and _not wanting to_

from our side, we have already done enough to find a possible solution, _since a proper fix cannot be made_

if someone want to suggest some kind of improvement to the PR workaround adopted let us know

if you think that the new properties workaround are useless, let us know in the PR,
and we can talk to pause or cancel the merging of the PR

but better to give notice ASAP on the PR (NOT in this Issue that is OT),
because there is already an intention to merge

> Will we have to wait for Kodi 22 for the PVR 1024 characters limit fix?

Kodi API interface fix its more complex to do,
and require more development steps that touch all binary addons,
it could be done from Kodi 22 maybe near end next year

but here we make no promises
to tell the truth currently there is not much interest in to fix this problem at kodi level because this is a borderline case
so i have no idea who will want to take on this task or when

the only thing that i can suggest is to find a way to use the new properties
for example make a small python script that modify automatically the playlists by using the new properties

@glennguy you anticipated me while i was writing hehe, anyway i written different aspects

**Comment by aicynide** [comment]
No audio in this video (Kodi 21 Omega)

License url - https://tataplay.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001074&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjkyMjk1MDk4NjMxIn0.eyJzdWIiOiIxMzI3NDU1ODY5IiwiaXNlIjp0cnVlLCJqdGkiOiI5MjA3MmEyMy1mYjI0LTQ1ZDgtOTE0NS0yNGY0Y2YzZTU0MGMiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNzAxMjAwMDIwLCJuYW1lIjoidW5kZWZpbmVkIiwiaWF0IjoxNzAxMTEzNjIwLCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxNTIzIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzOCJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMzMifSx7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAwMDAyIn0seyJlcGlkIjoiU3Vic2NyaXB0aW9uX0Jyb3dzZXJfU3RyZWFtaW5nIiwiYmlkIjoiMTAwMDAwMTAzNSJ9LHsiZXBpZCI6IlN1YnNjcmlwdGlvbl9Ccm93c2VyX1N0cmVhbWluZyIsImJpZCI6IjEwMDAwMDAwMDEifV0sImNzbW8iOnsibWFzIjoiNiIsImR0IjoidHBtYSIsIm1hc2QiOiIyIn0sImlzcyI6InRwbWFfd2ViIn0.ZVlVqM7ZsgUelGqYL1RaEqdZpMnNbdzjVKARKr5U4Os

Manifest url  - https://deltatesttatasky.akamaized.net/out/i/968284.m3u8

Also i observed that `#KODIPROP:inputstream=inputstream.adaptive` is must. Without this property `#KODIPROP:inputstream=inputstream.adaptive` video doesn't play in Kodi 21 Omega. The playlist i generated from a script didn't had this parameter so i added it manually. 
Maybe it wasn't playing Nexus Kodi 20 due to this property `#KODIPROP:inputstream=inputstream.adaptive` missing but as far as i remember even after adding `#KODIPROP:inputstream=inputstream.adaptive` it was not able to play in Kodi 20 Nexus

**Comment by CastagnaIT** [comment]
closed no more backports, developments are starting for Kodi 22
