### ISSUE TITLE
Cannot change Initial Bandwidth to low values

### ISSUE THREAD

**Issue by sdbbs** [peak3d/inputstream.adaptive#1429]
## Bug report

Cannot change Initial Bandwidth to low values.

### Describe the bug
Here is a clear and concise description of what the problem is:

I'm trying to set InputStream Adaptive bandwidth settings to low values, so I get served max 480p videos (anything more than that, and my playback hardware chokes)

Earlier I had used 250000 bps as max, and it seemed to work for me:

> ![image](https://user-images.githubusercontent.com/26737749/194774935-2de7b841-daee-4ce4-b72e-f30e38e8ce17.png)

Now, there is something called "initial bandwidth", and at first, I couldn't get it below the default 4000 kbps - whatever number I entered there below 4000 kpbs, simply was ignored, and 4000 came up in the field again.

Then I turned off "Auto determines initial bandwidth", and realizing that 0 disables "minimum bandwidth", entered 50 for "minimum bandwidth" - and so I could get to set Initial bandwidth to 1000 kbps - but NOT below that (again, if I enter 900 here, it is ignored, and 1000 is reinstated after I click "done". 

![image](https://github.com/xbmc/inputstream.adaptive/assets/48317456/7362ba17-3976-4cf4-8e54-fdddeb7cebc1)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

At least as the "Initial bandwidth" naming implies, I'd expect to be able to set "Initial badnwidth" to any number between the ones set in Minimum bandwidth and Maximum bandwidth.

## Actual Behavior

Described in "Describe the bug"

## Possible Fix

Cannot think of anything

### To Reproduce

1. Open Settings - InputStream Adaptive
2. Disable "Auto determines initial bandwidth"
3. Set Minimum bandwidth to 50 kbps
4. Set Maximum bandwidth to 250 kbps
5. Try to change initial bandwidth from the default 4000 (kbps) to 200
6. Observe how the 200 you just entered is ignored, and the 4000 comes back as the value for Initial bandwidth

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/equhanewem.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Not applicable

### Screenshots 
Here are some links or screenshots to help explain the problem:

See "Describe the bug"

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not applicable

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2
 - inputstream.adaptive version: v20.3.14

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
what streaming has 50 to 250 kbps of adaptive video stream? if so please attach the manifest

~and also the stream switching will result almost impossible to do~
edit: new codecs compressions may have lower values so ok, my bad affermation

but however its not clear why you affirm that default 4000 cannot be changed, the minumum value is 500

use values >= 500 kbps for initial bw, or you have to use "Fixed resolution" stream selection type

UPDATE: FYI i opened PR to allow initial bw from 50kbps
