### ISSUE TITLE
 Could not find protocol inside url - invalid

### ISSUE THREAD

**Issue by Gaet81** [peak3d/inputstream.adaptive#143]
Hello,

Thanks for the plugin, it's really helpful!

I'm trying to read a mpd file but I'm getting the following error:
01:29:19.401 T:1439691600   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
01:29:19.402 T:1439691600   ERROR: AddOnLog: InputStream Adaptive: Could not find protocol inside url - invalid
01:29:19.402 T:1439691600   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
01:29:19.402 T:1439691600   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()

here is a more complete log:
https://framabin.org/?9ede8def1be4a267#ovV/Y9L5loGyq52Jq4OIbdlTQPI3/8K4id2+wrRMut4=

I'm not sure what I'm doing wrong...here is the code called by the addon:
liz = xbmcgui.ListItem(path=media_url)
liz.setProperty('inputstreamaddon', 'inputstream.adaptive')
liz.setProperty('inputstream.adaptive.license_type', 'com.widevine.alpha')
if is_live:
    liz.setProperty('inputstream.adaptive.manifest_type', 'mpd')
    licence_url = 'http://wv-keyos.licensekeyserver.com|customData=' + auth + '|R{SSM}|'
liz.setProperty('inputstream.adaptive.license_key', licence_url)
liz.setMimeType('application/dash+xml')
liz.setContentLookup(False)

In the license_url I've tried with R{SSM} and B{SSM} without luck. Any idea what is the url that doesn't have protocol?

Thanks

**Comment by Gaet81** [comment]
Can't anyone help me to find out why it's bugging?

**Comment by opscc** [comment]
You may need to create a 'proxy' [I did].  Look at the addon referenced at the bottom of this issue
https://github.com/peak3d/inputstream.adaptive/issues/97

**Comment by peak3d** [comment]
You need at least one slash after the domain (I dont know why it is like that)
Can you add a / after the .com?

**Comment by Gaet81** [comment]
Hi @peak3d 

Thanks it was indeed the issue!
