### ISSUE TITLE
Maximum Length of URL checked by isUrl too small

### ISSUE THREAD

**Issue by nictjir** [peak3d/inputstream.adaptive#1440]
### Describe the bug
In inputstream.adaptive-Nexus the URL is verified with isUrl in src/utils/UrlUtils.cpp. A maximum length of 2083 is allowed else the URL is declared invalid "URL not valid". I require a longer URL as the site requires multiple parameters to be passed as well as a very long authorization Bearer string

## Expected Behavior
A longer URL should be allowed.

## Actual Behavior
If the URL length is greate than 2083, the URL is declared invalid "URL not valid"

## Possible Fix
Change
if (validateLenght && url.size() >= 2083)
to
if (validateLenght && url.size() >= 4003)

### To Reproduce

Call with a URL of
 

### Debuglog
Pass the following 
https://cfd-v4-service-stitcher-dash-use1-1.prd.pluto.tv/stitch/dash/episode/6369123841c0980014a1ff2d/main.mpd?appName=web&appVersion=unknown&deviceVersion=unknown&deviceModel=web&deviceMake=unknown&deviceId=unknown&deviceType=web&clientID=unknown&clientModelNumber=1.0&drmCapabilities=widevine%3AL3&deviceDNT=false&sid=f638d8ff-a601-11ee-a74e-baf1ab572eb4&jwt=eyJhbGciOiJIUzI1NiIsImtpZCI6ImJkOTYzOGNhLTVlYzMtNGZjOS1hZmQzLWUxYWJhNTJmMGQ2NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiJmNjM4ZDhmZi1hNjAxLTExZWUtYTc0ZS1iYWYxYWI1NzJlYjQiLCJjbGllbnRJUCI6IjE4NC4xODkuNC4yNSIsImNpdHkiOiJGYWlyZmF4IiwicG9zdGFsQ29kZSI6IjIyMDMwIiwiY291bnRyeSI6IlVTIiwiZG1hIjo1MTEsImFjdGl2ZVJlZ2lvbiI6IlVTIiwiZGV2aWNlTGF0IjozOC44MzAwMDE4MzEwNTQ2OSwiZGV2aWNlTG9uIjotNzcuMzM5OTk2MzM3ODkwNjIsInByZWZlcnJlZExhbmd1YWdlIjoiZW4iLCJkZXZpY2VUeXBlIjoid2ViIiwiZGV2aWNlVmVyc2lvbiI6InVua25vd24iLCJkZXZpY2VNYWtlIjoidW5rbm93biIsImRldmljZU1vZGVsIjoid2ViIiwiYXBwTmFtZSI6IndlYiIsImFwcFZlcnNpb24iOiJ1bmtub3duIiwiY2xpZW50SUQiOiJ1bmtub3duIiwiY21BdWRpZW5jZUlEIjoiIiwiaXNDbGllbnRETlQiOmZhbHNlLCJ1c2VySUQiOiIiLCJsb2dMZXZlbCI6IkRFRkFVTFQiLCJ0aW1lWm9uZSI6IkFtZXJpY2EvTmV3X1lvcmsiLCJzZXJ2ZXJTaWRlQWRzIjpmYWxzZSwiZTJlQmVhY29ucyI6ZmFsc2UsImZlYXR1cmVzIjp7ImlzU3RpdGNoZXJFa3MiOnRydWUsInNlYXJjaEFQSSI6eyJtYXRjaEV4YWN0SW5QaHJhc2VFbmFibGVkIjp0cnVlLCJtYXRjaEluQWN0b3JzRW5hYmxlZCI6dHJ1ZSwibWF0Y2hJbkRpcmVjdG9yc0VuYWJsZWQiOnRydWUsInF1ZXJ5U3lub255bXNFbmFibGVkIjp0cnVlLCJxdWVyeVZlcnNpb24iOiJ2MSJ9fSwiZm1zUGFyYW1zIjp7ImZ3VmNJRDIiOiJ1bmtub3duIiwiZndWY0lEMkNvcHBhIjoidW5rbm93biIsImN1c3RvbVBhcmFtcyI6eyJmbXNfbGl2ZXJhbXBfaWRsIjoiIiwiZm1zX2VtYWlsaGFzaCI6IiIsImZtc19zdWJzY3JpYmVyaWQiOiIiLCJmbXNfaWZhIjoiIiwiZm1zX2lkZnYiOiIiLCJmbXNfdXNlcmlkIjoidW5rbm93biIsImZtc192Y2lkMnR5cGUiOiJ1c2VyaWQiLCJmbXNfcmFtcF9pZCI6IiIsImZtc19oaF9yYW1wX2lkIjoiIiwiZm1zX2JpZGlkdHlwZSI6IiIsIl9md18zUF9VSUQiOiIiLCJmbXNfcnVsZWlkIjoiMTAwMDksMTAwMDAifX0sImRybSI6eyJuYW1lIjoid2lkZXZpbmUiLCJsZXZlbCI6IkwzIn0sImlzcyI6ImJvb3QucGx1dG8udHYiLCJzdWIiOiJwcmk6djE6cGx1dG86ZGV2aWNlczpVUzpkVzVyYm05M2JnPT0iLCJhdWQiOiIqLnBsdXRvLnR2IiwiZXhwIjoxNzAzOTEwMTg1LCJpYXQiOjE3MDM4MjM3ODUsImp0aSI6IjU4ZTkyNDM3LWMxZTctNDBmNC1hZGNiLWRhZjVlZjgyNjUxNSJ9.G3B9QvlGRtUXhj6Ooo0eg2rp6AEpOB-hQGyhBT-JGUE&

### MPD/M3U8s/ISM
https://cfd-v4-service-stitcher-dash-use1-1.prd.pluto.tv/stitch/dash/episode/6369123841c0980014a1ff2d/main.mpd

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [X ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi (20.2 (20.2.0)
 - inputstream.adaptive version: 20.3.15

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
look like the HTTP standard has raised the minimum limit to 8000 so we can try raise the value to 8000,
but need to be tested since other kodi components may not works correctly and make this change not possible
i will prepare a test build

**Comment by nictjir** [comment]
Thankyou, appreciate your quick response and test build - happy to test the new  build 
My system is Android with Kodi Nexus

**Comment by CastagnaIT** [comment]
you can download test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1441/1/artifacts
let me know

**Comment by nictjir** [comment]
Thankyou - this solves my issue of long URLs and everything else still works as expected.
Really appreciate quick fix and updated releases

**Comment by CastagnaIT** [comment]
change merged, but as now i cannot give you an ETA for the new release
