### ISSUE TITLE
Problem with playback HLS manifest [QUESTION]

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1443]
I have such a HLS manifest:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="mp4a.40.2-128000-48000-2",NAME="POL",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="pl",CHANNELS="2",URI="v4-221.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=829048,AVERAGE-BANDWIDTH=663517,RESOLUTION=512x288,CODECS="avc3.4D4015,mp4a.40.2",FRAME-RATE=25.000,AUDIO="mp4a.40.2-128000-48000-2",CLOSED-CAPTIONS=NONE
v4-121.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1829048,AVERAGE-BANDWIDTH=1463517,RESOLUTION=768x432,CODECS="avc3.4D401E,mp4a.40.2",FRAME-RATE=25.000,AUDIO="mp4a.40.2-128000-48000-2",CLOSED-CAPTIONS=NONE
v1-121.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1829048,AVERAGE-BANDWIDTH=1463517,RESOLUTION=768x432,CODECS="avc3.4D401E,mp4a.40.2",FRAME-RATE=25.000,AUDIO="mp4a.40.2-128000-48000-2",CLOSED-CAPTIONS=NONE
v3-121.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3079048,AVERAGE-BANDWIDTH=2463517,RESOLUTION=1024x576,CODECS="avc3.4D401F,mp4a.40.2",FRAME-RATE=25.000,AUDIO="mp4a.40.2-128000-48000-2",CLOSED-CAPTIONS=NONE
v2-121.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=7704088,AVERAGE-BANDWIDTH=6163549,RESOLUTION=1920x1080,CODECS="avc3.4D4028,mp4a.40.2",FRAME-RATE=25.000,AUDIO="mp4a.40.2-128000-48000-2",CLOSED-CAPTIONS=NONE
v0-121.m3u8
```
IS player playback only audio without video (there is no option to select a stream once playback starts). Questions:
1. Is this expected behavior for an IS player?
2. What have I do in such HLS manifest? Is the only way to edit it before send to IS (proxy/HTTP server) ?

**Comment by CastagnaIT** [comment]
> Is this expected behavior for an IS player?

depends on settings/addon factor and / or if there could be bugs,
with default ISA settings no streams are selectable, because use adaptive stream feature

> IS player playback only audio without video (there is no option to select a stream once playback starts).

like a music song? if so, seem to be some other problem behind, there is opened another similar Issue (#1299) but no way to investigate because geoblocked

> (there is no option to select a stream once playback starts)

check if have you set the ISA "Stream selector" setting to "ask quality" this should show the streams,
and make sure that the addon used to play the stream DONT override that setting by using `inputstream.adaptive.stream_selection_type`

**Comment by mtr81** [comment]
> like a music song? if so, seem to be some other problem behind, there is opened another similar Issue (#1299) but no way to investigate because geoblocked

Exactly. Even if I select video stream, IS open it like a music song.
![K1](https://github.com/xbmc/inputstream.adaptive/assets/86961563/c8416dcd-4be9-4248-87b5-901cf5f89c45)
![K2](https://github.com/xbmc/inputstream.adaptive/assets/86961563/f39ecf83-0582-49fe-b7b1-5c0eabae4865)

Here is stream url : `https://cdndai.pl/tvp1hd/index.m3u8`

**Comment by CastagnaIT** [comment]
thanks for the test stream its works good on Kodi 21
so looks like not the same issue of https://github.com/xbmc/inputstream.adaptive/issues/1299

luckily there are very small fixes to backport to kodi v20
you can test fixes by using test builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1445/1/artifacts

**Comment by mtr81** [comment]
Works fine! Thank you.
