### ISSUE TITLE
[K20/K21] Issue with playing MPD manifest

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1446]
I have problem with playing belowed MPD manifest (I changed IP number in urls to 00.00.00.00)
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/13806568/manifest.mpd.txt)
The IS appears to have obtained the VW license without any problems, but there was a problem when parsing the init m4a/m4s segment
[media-b2490000-init.zip](https://github.com/xbmc/inputstream.adaptive/files/13806577/media-b2490000-init.zip)
Debuglog -> [debug_log.txt](https://github.com/xbmc/inputstream.adaptive/files/13806593/debug_log.txt)

I tested it on Kodi ver. 20.2 and K21 (BETA-2 20.90.821 ) on Windows 10 and Android device

**Comment by glennguy** [comment]
Yeah seems to not like the init segments for some reason

`2024-01-02 01:39:48.162 T:9120    error <general>: AddOnLog: inputstream.adaptive: ADP::CreateStreamReader: No MOOV atom in stream` 

Apparently there *is* a MOOV atom in the init segment provided though:

![image](https://github.com/xbmc/inputstream.adaptive/assets/11909320/5d20509c-883c-4b32-b078-c81e8a1b0e27)

**Comment by CastagnaIT** [comment]
its possible that the cause is not the moov itself
there is another problem above:
`AddOnLog: inputstream.adaptive: adaptive::CDashTree::ParseTagRepresentation: Cannot generate segments timeline, the segment count exceeds SIDX atom limit.`

this does not allow to create the timeline and then try to build segments from SIDX atom, this could cause the MOOV problem

**Comment by CastagnaIT** [comment]
i tried remove the segment limit hoping is the only problem,
if you have a chance to test it please give a feedback with test build
kodi21: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1478/1/artifacts

**Comment by mtr81** [comment]
Thanks. Playback started but after 14 sec. stopped. On the counter I see ```167:49:46/168:00:00``` So it looks only one segment is playing.

**Comment by CastagnaIT** [comment]
then for now i will remove the segment limit
there are too many live streams cases that dont works due to code that need to be improved
if the manifest is same as attached above the segments should be of 4 secs each one, so more likely there are other problems

**Comment by mtr81** [comment]
I noticed that in manifest suggestedPresentationDelay is set on 12 sec. If I set in ISA property `inputstream.adaptive.live_delay` with different value I can extended palyback time... So maybe problem is in that property?
