### ISSUE TITLE
Version 20.3.16 won't play anything in my firestick

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1452]
### Describe the bug
Here is a clear and concise description of what the problem is:

I was using inputstream.adaptive 20.3.11 in my firestick (old model) with kodi 20. It worked fine. But after updating to version 20.3.16 it seems playback doesn't work with any addon.

There's no error but playback never starts (circle spinning or maybe the controls appear but the movie never starts).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback should work.

## Actual Behavior

Spinning circle. Playback never starts.

### To Reproduce

1. Try to play anything with an addon that uses inputstream.adaptive, for example with the prime video addon on a (old?) firestick.

### Debuglog

The debuglog can be found here:

This is the log with 20.3.16 (not working):
https://paste.kodi.tv/dosemiyedi.kodi

This is the log with 20.3.11 (working):
https://paste.kodi.tv/evucowufow.kodi

### MPD/M3U8s/ISM

I think a manifest is not relevant since the problem seems to happen with all addons.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Amazon AFTT with Android TV 5.1.1 
 - Kodi version: 20.2 
 - inputstream.adaptive version: 20.3.16 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joaopa00** [comment]
I have also the problem in my Ubuntu box. In Android no problem.

**Comment by glennguy** [comment]
Thanks guys

Just from looking at the log it seems that in the 'non working' version this might be what is happening (educated guess):
* Video/Audio/Sub 'streams' are all started by IA
* Kodi asks for samples to feed VideoPlayer (calls DemuxRead() )
* IA determines that the video stream is next in line to give a sample (current timestamp of the video reader is the furthest behind, but in reality they're most likely all the same at start of playback - we haven't read anything yet according to logs). So IA downloads a video segment and feeds a sample to Kodi.
Here's where it might go wrong:
* IA's function that checks which 'sample reader' is next in line keeps choosing the video one. We can see in this log that it keeps downloading more video segments. It isn't clear in the log if playback was asked to be stopped or not but seems like it was left to keep running at the point the log was uploaded.
* Only guessing here but I think VideoPlayer knows that we have an audio stream and is waiting/expecting audio samples so it can sync and start playback. This never happens so we're stuck stalled.

@CastagnaIT does this resonate with you, and if so can you think of any recent changes that may affect this (samplereader/PTS)?

**Comment by CastagnaIT** [comment]
> Only guessing here but I think VideoPlayer knows that we have an audio stream and is waiting/expecting audio samples so it can sync and start playback. This never happens so we're stuck stalled.

i also see that no audio processed
but here we are talking of Kodi 20 and there are very few changes between versions

@Paco8 can you test with ISA versions after 20.3.11? such as 20.3.12, etc...?
so its possible narrow it down better

**Comment by Paco8** [comment]
> @Paco8 can you test with ISA versions after 20.3.11? such as 20.3.12, etc...? so its possible narrow it down better

Where can I find old versions?

I found [here](https://mirrors.kodi.tv/addons/nexus/inputstream.adaptive+android-armv7/) version 20.3.14 and 15. They don't work, same problem.

I can't find versions 12 and 13.

**Comment by Paco8** [comment]
I found version 20.3.12. Playback doesn't work with this version either. So it seems the last working version in this device is 20.3.11.

Log from 20.3.12:
https://paste.kodi.tv/mebikefazo.kodi

**Comment by CastagnaIT** [comment]
thanks then this should means
that somewhat a there is again a memory heap corruption somewhere
https://github.com/xbmc/inputstream.adaptive/pull/1348

could be similar to the problem with amazon vod on this issue:
https://github.com/xbmc/inputstream.adaptive/issues/1394
on that issue happens on libreelec, maybe its possible verify if happens also on ubuntu that is more easy make tests

**Comment by CastagnaIT** [comment]
i made a fix but for now testing on Kodi 21 only
if you are able to give a feedback, here there are test builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1464/2/artifacts

**Comment by Paco8** [comment]
This is what I did: I installed Kodi 21 beta, a clean install. I try to play videos with my addons and they played fine with the version of inputstream adaptive supplied by Kodi 21. But then I closed Kodi, opened it again, and now it doesn't play anything, spinning circle. For some reason it worked fine just after the installation but not afterwards.

Then I installed the version of inputstream adaptive you told me and now it plays again. However one of the addons has some problems like image corruption, freezes... which weren't present in the previous version of inputstream adaptive (the one which only worked once).

**Comment by CastagnaIT** [comment]
> This is what I did: I installed Kodi 21 beta, a clean install. I try to play videos with my addons and they played fine with the version of inputstream adaptive supplied by Kodi 21. But then I closed Kodi, opened it again, and now it doesn't play anything

the memory allocation problem happens randomly so if you play a video could starts the first time, dont play the second time, and be played correctly the third time etc... without logic

> However one of the addons has some problems like image corruption, freezes...

the fix its a test, its possible due to bad code change or also not related at all
try to see if this "corrupted" video is played corrupted every time you play it or not
if you can i would like to see the manifest+log of this one

**Comment by CastagnaIT** [comment]
i think to have found a oversight in my code
please test this new test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1464/4/artifacts

**Comment by CastagnaIT** [comment]
i think to have found a oversight in my code

sorry previous was a wrong link, new test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1464/5/artifacts

**Comment by Paco8** [comment]
This new build seems to work fine, no image corruption.
