### ISSUE TITLE
Problem with playback VOD content after IS update (ver. 20.3.17)

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1468]
Yesterday's IS update (ver. 20.3.17) caused problems with VOD content playback on Android devices (only sound segments are playing).
Manifest MPD
[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/14157749/manifest.txt)
Log
[Untitled.txt](https://github.com/xbmc/inputstream.adaptive/files/14157733/Untitled.txt)

**Comment by CastagnaIT** [comment]
its possible thats related to commit https://github.com/xbmc/inputstream.adaptive/commit/0566e1267c93b85efd09881645983cd913d48e2d
but to be sure you need a test build with the commit reverted,
i cannot see the target platform since the log is incomplete, you need arm or arm64?

its needed an accout to test the stream? you can provide a stream that i can use to test?

**Comment by mtr81** [comment]
ARM. Thanks for reply!

**Comment by CastagnaIT** [comment]
i have tested more times the sample stream you sent to my email:

on android:
kodi 20 + 20.3.16
kodi 20 + 20.3.17
kodi 21 + 21.4.0
kodi 21 + 21.4.1
kodi 21 + 21.4.2
no video, all them same playback errors as shown in your log, the problem is on every ISA version, not only in the last 20.3.17

instead on Windows with:
kodi 21 + 21.4.0
kodi 21 + 21.4.2
the video somewhat works but results in a corrupted/pixellated images

i dont see this as a recent regression

**Comment by CastagnaIT** [comment]
from your email:

> As for playback this stream on devices in Windows - works fine afrer switching off hardware acceleration in video settings...

you have forgotten to specify that "try avoiding secure decoder" ISA setting needs to be enabled to play the stream on android

please next time follow _our Issue template to provide complete information_ and avoid wasting our time for nothing

**Comment by mtr81** [comment]
I didn't ask about playback in Windows. I only note that playback this stream is correct after switch off hardware acceleration in video settings. 
As for Android after switch on "try avoiding secure decoder" there are artefacts, so **ISA still work not properly**. Other thing - playback in ISA v. 20.3.16 is correct without enabled this setting.

> please next time follow _our Issue template to provide complete information_ and avoid wasting our time for nothing

You got all necessary informations to solve problem. Form is less important.

**Comment by CastagnaIT** [comment]
> Other thing - playback in ISA v. 20.3.16 is correct without enabled this setting

on my android with 20.3.16 if i keep "try avoiding secure decoder" disabled dont play the video
i think here there is more than one problem

**Comment by CastagnaIT** [comment]
> Device unique ID size: 32, System ID: 4445, Security level: L3

ah your device is "L3" so this can explain the different situation

looks like that on our ISA for android is lack of this check:
https://developer.android.com/about/versions/12/features?hl=it#mediadrm
refer to `MediaCrypto.requiresSecureDecoderComponent(mimeType)` / `requiresSecureDecoder(@NonNull String mime)`

secure is set by looking at L1 and nothing else
https://github.com/xbmc/inputstream.adaptive/blob/2c58dee6b685660ddeeb1156ea19e3210b4f1d15/src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp#L193-L197

**Comment by CastagnaIT** [comment]
i made a test fix, please give feedback, choose the preferred build:
test build for Kodi 20: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1476/1/artifacts
test build for Kodi 21: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1475/2/artifacts

**Comment by erikatremblay** [comment]
> i made a test fix, please give feedback, choose the preferred build: test build for Kodi 20: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1476/1/artifacts test build for Kodi 21: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1475/2/artifacts

Works for me👌 Kodi 20.3 on android tv (homatics box r 4k plus)

**Comment by KodiTopQuebec** [comment]
il y a eu une patch de sortie , pour moi fonctionne num 1 , télécharger le .zip et installer le a partir de kodi , voici le lien pour la patch , merci a ce généreux pour avoir travaillé la dessus
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1476/1/artifacts/

**Comment by KodiTopQuebec** [comment]
@CastagnaIT  merci beaucoup pour ton temps a corriger ce bug , fonctionne A1
