### ISSUE TITLE
"inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" corrupted

### ISSUE THREAD

**Issue by tingjhenjiang** [peak3d/inputstream.adaptive#1469]
### Describe the bug

Hello, I'm developing a KODI addon for retrieving streamings and playing streaming videos with the help of inputstream.adaptive.
But I found out that options
"inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" does not work as expected and get corrupted.

My url parameter for retrieving streaming is something like this:

`URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xMy8&Expires=1707329257&KeyName=private-web-cdn-key&Signature=p165n9-rL3qGvv_Sqw4zr8SDchU`

## Expected Behavior

The URL parameters in target streaming url should be as same as what is provided in the "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" options. 
Target streaming url should be like `hls.m3u8?URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xMy8&Expires=1707329257&KeyName=private-web-cdn-key&Signature=p165n9-rL3qGvv_Sqw4zr8SDchU` in the given example.

## Actual Behavior

When the parameters are passed to "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" options,
the actual request does not work as expected, as it becomes something like this:

`hls.m3u8?URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xMy8&Expires=1&KeyName=private-web-cdn-key&Signatu&Signature=p165n9-rL3qGvv_Sqw4zr8SDchU`

Please notice that **the "Expires" argument got changed, and junk parameter "Signatu&" is added**.

## Possible Fix

I mannually change the value of "Expires" url parameter and get the following results.
|  Expires   | result of url parameter  |
|  ----  | ----  |
| str(9)  | corrupted |
| str(99)  | corrupted |
| str(999)  | corrupted |
| str(9999)  | corrupted |
| str(99999)  | corrupted |
| str(100000)  | corrupted |
| str(1000000)  | corrupted |
| str(10000000)  | corrupted |
| str(100000000)  | corrupted |
| str(abc)  | corrupted |
| str('')  | corrupted |

Check and fix codes on concerning parts.

### To Reproduce
1. create a listitem
2. set the "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" attributes of the listitem with the URL parameter provided as above.
3. play the item

OR
4. 
save the following texts as a .strm and open it with KODI:
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
#KODIPROP:inputstream.adaptive.manifest_params=URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xNi8&Expires=1707388067&KeyName=private-web-cdn-key&Signature=vn-rvCSZdcGld3TTXw4eItt3LK0
#KODIPROP:inputstream.adaptive.stream_params=URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xNi8&Expires=1707388067&KeyName=private-web-cdn-key&Signature=vn-rvCSZdcGld3TTXw4eItt3LK0
https://prod-cdn.ptsplus.tv/video/migration/3-2023629-1-16/hls.m3u8
```

### Debuglog
The debuglog can be found here: (Kodi debug log as follows)
situation 1: [both "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" are set](https://pastebin.com/Ys1L9xQw).
situation 2: [only "inputstream.adaptive.manifest_params" is set](https://pastebin.com/TAdfLs5a).
situation 3: [only "inputstream.adaptive.stream_params" is set](https://pastebin.com/VVBYeWSY).

### MPD/M3U8s/ISM

[An example or copy of a manifest (or manifests for HLS - master and variants) can be found here: a link](https://prod-cdn.ptsplus.tv/video/migration/3-2023629-1-16/hls.m3u8)
url parameter for the manifest and streaming should be added:
`URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0xNi8&Expires=1707385731&KeyName=private-web-cdn-key&Signature=yh1lLu0HamnNm0ABd7rZgK7QhLo`

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
I develop the addon with xbmcswift2. Listitem is set as 
```
[{
	'label': "play{}".format( "" ),
	'label2': '',
	'path': streamingurl,
	'info': {},
	'thumbnail': None,
	'icon': None,
	'properties': {
		'inputstream': 'inputstream.adaptive',
		'inputstream.adaptive.manifest_type': 'hls',
		'inputstream.adaptive.stream_headers': reqheaders_strs,
		'inputstream.adaptive.manifest_headers': reqheaders_strs,
		'inputstream.adaptive.manifest_params': urlparameters,
		'inputstream.adaptive.stream_params': urlparameters,
	},
	'is_playable': True,
}]
```

### Your Environment
Used Operating system:

 - Operating system version/name: Windows 11 Pro 23H2 build 22631.3007
 - Kodi version: 20.3 (Git 20240110-6fb2bfc7ff)
 - inputstream.adaptive version: v20.3.17

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
you can test the fix by using one of these test builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1471/1/artifacts (are ready in ~15minuts)

**Comment by tingjhenjiang** [comment]
> you can test the fix by using one of these test builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1471/1/artifacts (are ready in ~15minuts)

hello,
I tested another v21.4.2 Omega version [using CI pipeline built package here](https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/21.4.2-Omega/2/pipeline) because the [CI pipeline did not successfully build a windows x64 v20 version](https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1471/1/artifacts), and I found out another problem.

This time "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" still does not work as expected. Given the same example, the actually request become something like this:

> 2024-02-10 09:16:39.727 T:7596    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.manifest_params" value: URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0yMy8&Expires=1707538591&KeyName=private-web-cdn-key&Signature=6VrG_FKwqwx1X2pb9CubMWoYE5Y
> AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_params" value: URLPrefix=aHR0cHM6Ly9wcm9kLWNkbi5wdHNwbHVzLnR2L3ZpZGVvL21pZ3JhdGlvbi8zLTIwMjM2MjktMS0yMy8&Expires=1707538591&KeyName=private-web-cdn-key&Signature=6VrG_FKwqwx1X2pb9CubMWoYE5Y
> 2024-02-10 09:16:39.795 T:7596    error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 403: <u>https://prod-cdn.ptsplus.tv/video/migration/3-2023629-1-23/hls.m3u8</u>
> 2024-02-10 09:16:39.795 T:7596    debug <general>: AddOnLog: inputstream.adaptive: CSession::~CSession()
> 2024-02-10 09:16:39.795 T:7596    error <general>: CVideoPlayer::OpenInputStream - error opening [https://prod-cdn.ptsplus.tv/video/migration/3-2023629-1-23/hls.m3u8]

which means the "inputstream.adaptive.manifest_params" and "inputstream.adaptive.stream_params" options are not functional at all and all the parameters are not passed to the actual request URL.

**Comment by CastagnaIT** [comment]
thanks you have found a regression on omega, now fixed

in hope CI dont fails again (is a know CI problem) new builds:
Nexus: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1471/2/artifacts
Omega: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1470/2/artifacts

**Comment by tingjhenjiang** [comment]
> thanks you have found a regression on omega, now fixed
> 
> in hope CI dont fails again (is a know CI problem) new builds: Nexus: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1471/2/artifacts Omega: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1470/2/artifacts

Hello,

I've tested the both Nexus and Omega version with the two links you provided and both work as expected now. But [this CI pipeline built version](https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/346/pipeline) fail to work. Thanks!
