### ISSUE TITLE
Missing languages when I use inputstream.adaptive in add on Amazon VOD

### ISSUE THREAD

**Issue by peterman65** [peak3d/inputstream.adaptive#147]
Hi all,

first, thanks for your great work.

I have installed the add on amazon vod and I cannot select the Spanish from Spain language when I play a video from amazon, it provides six languages: German,French,Portuguese,Italian, Spanish and English and the Spanish language corresponds to the Latin version. When I play it in the firefox browser or in a little tv box based on android I have 8 or 9 languages including Latino Spanish and Spain Spanish.

I have asked the authors of the "kodi add-on Amazon VOD'' about my problem and they have answered that it is not a problem of the  "Amazon VODadd-on" . They have said me that possibly the problems is in the inputstream.adaptive add on, so I'm here asking you.

Could you tell me if it could be a inputstream.adaptive problem and  how to do in order to have the Spanish Spain language??

Thanks in advance

Pedro

PD. I have read this sentence" 
Automatic / fixed video stream selection depending on max. visible display rect (some work has to be done at the inputstream interface)."

does It mean that the interface shows as many streams as it can show in the visible display rect?

**Comment by peak3d** [comment]
There is no restriction about (audio) streams in inputstream.adaptive.
What you read is only that Video resolution is limited to max of the Monitor / TV size, e.g. 4K videos are not chosen automatically on 1080p TV's.

What's the title of the video you are playing? Could be that grouping of streams lead to this issue.

**Comment by peterman65** [comment]
Thanks for your answer,

some videos for which I have problems are the episodes of the first season of "the man in the castle" series.

Thanks again

**Comment by peak3d** [comment]
If you get it archieved to download the manifest file, I can look what's going on.

Either copy the manifest from browser developer options (F12 / search for the manifest request in network tab and provide the response), or copy the URL from kodi.log and download the manifest manually.

After that pls. provide the manifest file here

**Comment by peterman65** [comment]
Dear peak3d,
I have found two more series with the same problem, they are 'electric dreams' and 'fleabg'.
About the manifest, I enter in my account of amazon prime video, I select the series then F12 I search for something related with manifest in network tab. Then I find two entries:

https://fls-eu.amazon.com/1/action-impressions/1/OE/aiv-web-player/action/HTML5Player:.LanguageDownload.Time.es-ES@v=44:u=ms/HTML5Player:.LanguageDownloadCacheHit@v=1/HTML5Player:.GetPlaybackResourcesTime@v=180:u=ms/HTML5Player:.GetPlaybackResourcesTime@v=242:u=ms/HTML5Player:.ManifestDownloadTime@v=211:u=ms?instance=f22dbddb-ef2c-48c5-8876-bed0d47594fd&marketplace=roe_eu&marketplaceId=A3K6Y4MI8GDYMT&requestId=1&service=AIVWebPlayer&session=704b71d9-6337-4aa2-9d72-d801427af7a7&client=Firefox

and 

https://fls-eu.amazon.com/1/action-impressions/1/OE/aiv-web-player/action/HTML5Player:.LanguageDownload.Time.es-ES@v=44:u=ms/HTML5Player:.LanguageDownloadCacheHit@v=1/HTML5Player:.GetPlaybackResourcesTime@v=180:u=ms/HTML5Player:.GetPlaybackResourcesTime@v=242:u=ms/HTML5Player:.ManifestDownloadTime@v=211:u=ms?instance=f22dbddb-ef2c-48c5-8876-bed0d47594fd&marketplace=roe_eu&marketplaceId=A3K6Y4MI8GDYMT&requestId=1&service=AIVWebPlayer&session=704b71d9-6337-4aa2-9d72-d801427af7a7

And for these entries the response headers  and request headers are the following:

For the first, the  request headers: 

Host: fls-eu.amazon.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: es,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://www.primevideo.com/detail/0JP0XMEGW4LOPLMRSLPS0UJW6K/ref=atv_hm_hom_c_8pZiqd_2_1
Origin: https://www.primevideo.com
Connection: keep-alive

For the first, the  response headers: 
HTTP/2.0 204 No Content
date: Wed, 23 May 2018 09:58:02 GMT
x-amzn-requestid: c8511e06-5e6f-11e8-ac69-a1deacbed3f0
access-control-allow-origin: *
access-control-expose-headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
X-Firefox-Spdy: h2

For the second, the  request headers:

Host: fls-eu.amazon.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: es,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://www.primevideo.com/detail/0JP0XMEGW4LOPLMRSLPS0UJW6K/ref=atv_hm_hom_c_8pZiqd_2_1
Origin: https://www.primevideo.com
Connection: keep-alive

For the second , response headers:

HTTP/2.0 204 No Content
date: Wed, 23 May 2018 09:58:02 GMT
x-amzn-requestid: c84de9d1-5e6f-11e8-9d46-2f04f8afba85
access-control-allow-origin: *
access-control-expose-headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
X-Firefox-Spdy: h2

Is this the information that you are asking me??? I am not sure if I have understood your instructions.

thanks

This evening at home I will try to get the information from kodi.log and I will send it to you

**Comment by peterman65** [comment]
Sorry for my clumsiness,

I have filter by "GetPlaybackResources" in the network tab, there is a line in the list status=200, method=POST, .., etc with type=json, (not xml), there are two xml type files after filtering but the size is 0.
After selecting the line of this json file on the right I select the tab Response and I have a lot of information, but it is not xml style. I paste here a part of the only very long line

{"catalogMetadata":{"catalog":{"entityType":"TV Show","episodeNumber":2,"id":"a.....


I have attached:.

[response.txt](https://github.com/peak3d/inputstream.adaptive/files/2030777/response.txt)

Is this the file that you want???

**Comment by peak3d** [comment]
Then try filtering your network list by "mpd"
There should be exactly one element (a GET request with corrected.mpd in URL).

The response of that is what we're searching for

**Comment by peterman65** [comment]
Hi peak3d, 

I attach the kodi.log file, it contains two lines where appear a file named ....corrected.mpd, do yo need these files? I have downloaded them.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/2031974/kodi.log)

**Comment by peterman65** [comment]
These are both mpd files:
[930832f8-24cc-4962-9da6-8c73cf401470_corrected_mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/2031998/930832f8-24cc-4962-9da6-8c73cf401470_corrected_mpd.txt)
[930832f8-24cc-4962-9da6-8c73cf401470_correctedSecondFile_mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/2031999/930832f8-24cc-4962-9da6-8c73cf401470_correctedSecondFile_mpd.txt)

**Comment by peak3d** [comment]
Fine, ok, I'll investigate now what happens with the languages, thx

**Comment by peak3d** [comment]
I pushed a commit which solves the merge issue.

But for the correct display in Audio selection dialog there are some channges in kodi required.
Until this change has happened you'll have 4 spanish streams but you don't know what is what.

**Comment by peterman65** [comment]
First of all, thank you for your time. 

You say that I have 4 Spanish streams, where? I can only see one Spanish language option, If I had 4 options I would test all of them to find the correct one, and it could be an appropriate solution until the next fixed version of kodi.

**Comment by peak3d** [comment]
If you play the stream from yesterday (amazon) and go into audio-settings ([key] m, audiosettings , audiostreams) you should see all streams provided in mpd manifest file.

**Comment by peterman65** [comment]
As I have said before, sorry for my clumsiness, but how get the 2.2.19 version, can I download from some place? can I install a repository to do it?

**Comment by peterman65** [comment]
Now I have a version 2.1.13 (it is included in the libreelec 9.0 installation I have done).

**Comment by JinRonin** [comment]
Just update to the latest milhouse build. 
Looks like you have downgraded from 2.1.18 to 2.1.13

**Comment by peterman65** [comment]
I have just installed again libreelec 2.8.5 and then milhouse build/testing (08-feb) the last I have found and the inputstream.adaptive is 2.1.13. 
What am I doing wrong?

**Comment by peak3d** [comment]
https://forum.kodi.tv/showthread.php?tid=298461

**Comment by peterman65** [comment]
Finally I have Spanish-Spain language available. Thank you very very much peak3d.

**Comment by peak3d** [comment]
thx for support!
