### ISSUE TITLE
add ability to include custom HTTP headers

### ISSUE THREAD

**Issue by opscc** [peak3d/inputstream.adaptive#148]
Add ability to include custom HTTP headers to play stream
Custom HTTP headers can currently be specified for the license request, but not the playing stream

E.g. I would like to specify the playing URL to be http://someplace.com/file.mpd|user-agent=myprogram,   
which allows CURL to add user-agent=myprogram to the  .m4s requests .... but Inpustream is using | for other purposes

**Comment by JinRonin** [comment]
You can add headers via
listitem.setProperty('inputstream.adaptive.stream_headers', 'user-agent=myprogram')

**Comment by opscc** [comment]
That works.  Thanks
