### ISSUE TITLE
How to use without kodi? Standalone

### ISSUE THREAD

**Issue by FloridaStream** [peak3d/inputstream.adaptive#149]
Can you provide a sample code for using it without the kodi? Same as standalone for exemple.

I have a raw encrypted input, and I'm trying to download decrypted by cleaning it on disk, but I'm having difficulty modifying/integrating because I do not know how to get output like kodi does.

For example:
Get Licence
Open file from Disk or URL
Decrypt
Save on Disk

**Comment by peak3d** [comment]
It's not intended to store decrypted streams on disk.
If allowed, you can store the decytion key (if license allows) and decrypt on playback.

So, sorry, no support in standalone, maybe there will be support for offline in the near future (see description above)
