### ISSUE TITLE
How to install on Linux?

### ISSUE THREAD

**Issue by Mart-Bogdan** [peak3d/inputstream.adaptive#1494]
There are no Install instructions in Readme.

https://kodi.tv/addons/nexus/inputstream.adaptive/

I can't find it from linux on Kodi 20.4 in built in addon explorer.

And on kodi web site 
![image](https://github.com/xbmc/inputstream.adaptive/assets/775038/912c67c2-a3e9-4401-af4a-80083e628c28)

it has only zip download for windows/mac/android.

I'm trying to watch amazaone prime and that addon told me that inputstream.adaptive is not installed.

**Comment by Mart-Bogdan** [comment]
Turns out I have to use my distro's repository and install package [`kodi-addon-inputstream-adaptive`](https://archlinux.org/packages/extra/x86_64/kodi-addon-inputstream-adaptive/)

**Comment by figure002** [comment]
Package `kodi-inputstream-adaptive` on Debian/Ubuntu.
