### ISSUE TITLE
[K21][MPD] [live stream] playback stopped after 16 sec.

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1495]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playback started and stopped after 16 sec.  Continuation issue https://github.com/xbmc/inputstream.adaptive/issues/1446
In Kodi 20 playback didn't start (no fix "[Dash] Removed segment limit based on SIDX refs" for this Kodi version) https://github.com/xbmc/inputstream.adaptive/pull/1478 )

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback live stream correctly.

## Actual Behavior

Playback stopped after 16 sec.

## Possible Fix

---

### To Reproduce

1.  Start playback manifest MPD

### Debuglog

The debuglog can be found here:

[log.txt](https://github.com/xbmc/inputstream.adaptive/files/14395096/log.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Manifest MPD
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/14395099/manifest.mpd.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![megogo_2024-02-25](https://github.com/xbmc/inputstream.adaptive/assets/86961563/0d1ecd1a-00b0-4bf0-a3ea-e3d89da97a77)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

---

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21.0-BETA3 (20.90.830) Git:20240221-480476cb59
 - inputstream.adaptive version: 21.4.3 (from https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1492/4/artifacts)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
here lack of MPD manifest updates
by reading the manifest you have a unusual MPD data where its missing `minimumUpdatePeriod` attribute
and since there is no `mediaPresentationDuration` means that it's not even a transition from live to VOD

in general common rules requirements are:
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/a431b313-24f7-4a50-9e52-7c41061d07a6)

**but seem exists another way:**
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/6b592b2b-dbed-4d54-9309-04088d0294ac)
(the first way is already implemented not mentioned here) this is the second:
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/02d679cc-f345-47e8-9340-06fc0048e711)
and other details
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/14400b7f-c1ff-4289-a6e5-70ae7e57ef02)

at the moment this is not supported, atm i don't have enough information about how it should be done

**Comment by CastagnaIT** [comment]
can you attach here a ".m4s" file (that dont cointain "init" word) downloaded from ISA before that stop playback? (you can download from log links)

**Comment by mtr81** [comment]
[media-b4000000-init.zip](https://github.com/xbmc/inputstream.adaptive/files/14893921/media-b4000000-init.zip)
In ver. from PR #1518 playback doesn't stop but player periodically returns to older segments.

**Comment by CastagnaIT** [comment]
nope i need segment .m4s not the "init" file, its different things

**Comment by mtr81** [comment]
Sorry. 
[media-b4000000-428103712.zip](https://github.com/xbmc/inputstream.adaptive/files/14894025/media-b4000000-428103712.zip)

**Comment by CastagnaIT** [comment]
nice 
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/868911f1-13f4-4914-b125-a994129a93e2)
the uuid d4807ef2ca3946958e5426cb9e46a79f seem to be the TFRF UUID that currently we use for smoothstreaming
in theory no big changes should be needed to make it work
i will take a look at it later

**Comment by CastagnaIT** [comment]
i have tried implement it,
but i have no way to test if changes works
test build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1525/1/artifacts

in case of problems provide new log+manifest

**Comment by mtr81** [comment]
Playback stops after several seconds.
*log:* 
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/14925298/log.txt)
*manifest:*
[manifest_1712706280.txt](https://github.com/xbmc/inputstream.adaptive/files/14925300/manifest_1712706280.txt)

**Comment by CastagnaIT** [comment]
ok fragments seem to be read with success but there is somenthing wrong with pts values
i need more info
please provide a new log with this build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1525/2/artifacts

**Comment by mtr81** [comment]
**LOG:**
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/14934723/log.txt)
**MANIFEST:**
[manifest_1712764602.txt](https://github.com/xbmc/inputstream.adaptive/files/14934730/manifest_1712764602.txt)

**Comment by CastagnaIT** [comment]
i think to have found the problem,
timescale conversions was generating such a high number that it was going out of data type limit...
new build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1525/3/artifacts

**Comment by mtr81** [comment]
Thanks for your effort. Now it works properly.
