### ISSUE TITLE
Some streams play with audio only and incorrect duration

### ISSUE THREAD

**Issue by CaptainTK** [peak3d/inputstream.adaptive#15]
While inputstream.adaptive is able to play back [this stream](http://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/f6b92e-b08h7jr4/vf_b08h7jr4_d5d56eed-c2c6-4ca8-8612-33ef74cd850c.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?__gda__=1488421772_a16418e531f480127a06f3b9d45fd6a3) correctly, [this stream](http://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/f6b92e-b08h7jr4/vf_b08h7jr4_d5d56eed-c2c6-4ca8-8612-33ef74cd850c.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1488422158_c0b6f7f1786e048e66d346d532ab6d36) does not work correctly. The latter gives me audio with no video and a totally wrong duration (about 500 minutes instead of the expected 30 minutes).

Note that these streams will only be available for a few weeks and will only work from within the UK.

**Comment by mac1202** [comment]
I have similar issue for example all the video for the gcndex channel suffer the same problem 
https://www.youtube.com/channel/UCUUfmVXMFLgsP0nCca_sE7w

**Comment by peak3d** [comment]
@CaptainTK I'm unable to retrieve the manifest files.
Can you pls download such an mpd file and attach it here?

Thanks

**Comment by CaptainTK** [comment]
I can't test right now if the problem is the same for these two, but please see two mpds attached to see the difference between a good and bad one.

[mpds.zip](https://github.com/peak3d/inputstream.adaptive/files/837056/mpds.zip)

**Comment by peak3d** [comment]
not reproducable
