### ISSUE TITLE
Add-on 'inputstream.adaptive' is not compatible with Kodi 18.0 ALPHA2

### ISSUE THREAD

**Issue by ryanfantus** [peak3d/inputstream.adaptive#150]
Hello,

I've recently installed a nightly Kodi 18 Leia and can't get the inputstream.adaptive package to work. When I try to enable it, I get an error that it isn't compatible with my version of Kodi.

Kodi (according to kodi -v) is:
18.0-ALPHA2 Git:20121104-c313e69 Media Center Kodi
According to apt-cache policy kodi:
2:118.0+git20180528.0201-c313e69-0bionic

inputstream.adaptive (according to apt-cache policy kodi-libinputstream-adaptive) is:
2.2.19-1~bionic

Let me know if there are any logs or anything meaningful that I can provide. Thanks.

**Comment by FloridaStream** [comment]
Same here, i'm downloading kodi from master release, and trying to compile inputstream.adaptive on windows, i can compile it, but i cant use him with kodi downloaded from site, same as u problem.
@peak3d can u help us?

**Comment by liberty-developer** [comment]
I have bumped the version to force a new repo update,
2.2.20 build should be working again.

**Comment by peak3d** [comment]
I have bumped the version to force a new repo update,
2.2.20 build should be working again.

**Comment by ryanfantus** [comment]
@peak3d can confirm the version bump unblocked us here. I'll close this out, thanks!
