### ISSUE TITLE
DFXP subtitles not supported

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1503]
### Describe the bug
Here is a clear and concise description of what the problem is:

I saw several TV streams in the Orange addon with this line in the manifest:
`<QualityLevel Bitrate="20000" Index="0" FourCC="DFXP" />`

Kodi doesn't recognize this kind of subtitles, the option to select a subtitle is empty.
It happens in all versions of Kodi I tested, including the beta of Kodi 21.

If I replace DFXP with TTML then the subtitles are recognized and I can select them but they aren't displayed properly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be possible to select the subtitles.

## Actual Behavior

The subtitles aren't shown in the subtitle selection menu. It seems Kodi doesn't recognize this kind of subtitles.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

I attach a manifest file and some subtitle fragments.
[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/14496770/manifest.txt)
[fragments.zip](https://github.com/xbmc/inputstream.adaptive/files/14496777/fragments.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: All operating systems
 - Kodi version: 19, 20, 21
 - inputstream.adaptive version: all

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> If I replace DFXP with TTML then the subtitles are recognized and I can select them but they aren't displayed properly.

can you try explain what happens on screen?

im not so expert about TTML profiles like DFXP
but by looking at fragment data seem to be much similar to regular TTML
with the difference about the time format
`begin="0.720000s" end="2.000000s"`
that its different from usual and could be wrongly parsed, first thing to be verified

**Comment by Paco8** [comment]
> > If I replace DFXP with TTML then the subtitles are recognized and I can select them but they aren't displayed properly.
> 
> can you try explain what happens on screen?

When two lines should appear, only the first one is shown. Also it stays on the screen longer that it should, it only goes away when the next subtitle is shown.

**Comment by CastagnaIT** [comment]
please try kodi 21 test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1504/1/artifacts

**Comment by Paco8** [comment]
Sometimes the subtitles don't disappear and new ones appear on top of the old ones:

![Captura de pantalla 2024-03-06 154944](https://github.com/xbmc/inputstream.adaptive/assets/5084042/e7cddf0f-fd1d-43c0-a3b4-66ac1db759ae)

**Comment by CastagnaIT** [comment]
i forgot double types, this new build should works:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1504/3/artifacts

**Comment by Paco8** [comment]
It seems to work fine now :+1:
