### ISSUE TITLE
Unexpected EoF problem

### ISSUE THREAD

**Issue by tartiflemme** [peak3d/inputstream.adaptive#151]
Hi ! I’m confronted to a « end of file » problem when I’m watching certain livestreams over 480p. Others livestreams I watch don’t make me face to this problem. For now I only experienced this problem on only one particular youtube channel, fact that found weird.

Is it a configuration problem of me or is it a inputstream problem ?

Have a nice day ~

Btw, there’s the log from Kodi’s logs file:

01:21:25.417 T:1925405184  NOTICE: VideoPlayer: Opening: https://manifest.googlevideo.com/api/manifest/dash/requiressl/yes/signature/94A80A612AA4180705453AA619B4D9EADF38B408.45FFE6FF055551CE3E6C06CADEDC5E131D31B97E/id/1tKvHDKQPqo.1/source/yt_live_broadcast/sparams/as%2Cei%2Cgcr%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cplaylist_type%2Crequiressl%2Csource%2Cexpire/ei/dOANW7W8DcelW5TFkIgF/hfr/all/key/yt6/ip/2.10.41.222/playlist_type/LIVE/itag/0/ipbits/0/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/gcr/fr/expire/1527657684&start_seq=$START_NUMBER$
01:21:25.417 T:1925405184 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
01:21:25.418 T:1190130432  NOTICE: Creating InputStream
01:21:25.742 T:1190130432  NOTICE: Creating Demuxer
01:21:25.745 T:1190130432  NOTICE: Opening stream: 1 source: 256
01:21:26.188 T:1190130432  NOTICE: Creating video thread
01:21:26.188 T:1190130432  NOTICE: Opening stream: 2 source: 256
01:21:26.339 T:1190130432  NOTICE: Creating audio thread
01:21:26.341 T:1190130432  NOTICE: Opening stream: 1 source: 256
01:21:26.378 T:1190130432  NOTICE: Opening stream: 2 source: 256
01:21:26.547 T:1190130432  NOTICE: OMXClock using audio as reference
01:21:32.742 T:1190130432  NOTICE: CVideoPlayer::OnExit()
01:21:32.742 T:1190130432  NOTICE: VideoPlayer: eof, waiting for queues to empty
01:21:32.742 T:1190130432  NOTICE: Closing stream player 1
01:21:32.743 T:1190130432  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
01:21:32.755 T:1289745152  NOTICE: thread end: OMXPlayerAudio::OnExit()
01:21:32.832 T:1190130432  NOTICE: Closing stream player 2
01:21:32.833 T:1190130432  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
01:21:32.833 T:1474294528   ERROR: OMXPlayerVideo: Got MSGQ_IS_ERROR(-1) Aborting
01:21:32.833 T:1474294528  NOTICE: thread end: video_thread
01:21:32.915 T:1925405184   ERROR: Control 510 in window 10025 has been asked to focus, but it can't
01:21:32.930 T:1925405184  NOTICE: CVideoPlayer::CloseFile()
01:21:32.930 T:1925405184  NOTICE: VideoPlayer: waiting for threads to exit
01:21:32.930 T:1925405184  NOTICE: VideoPlayer: finished waiting
01:21:32.931 T:1925405184  NOTICE: CVideoPlayer::CloseFile()
01:21:32.931 T:1925405184  NOTICE: VideoPlayer: waiting for threads to exit
01:21:32.931 T:1925405184  NOTICE: VideoPlayer: finished waiting

**Comment by peak3d** [comment]
1.) For me it reads that inputstream.adaptive is not enabled (addon settings)
2.) beside this OMX Player is not capable of playing DRM streams which require software decoding (libwidevine)
