### ISSUE TITLE
Stream playing under Linux and Windows but not AndroidTV

### ISSUE THREAD

**Issue by nirvana-7777** [peak3d/inputstream.adaptive#1511]
### Describe the bug
Here is a clear and concise description of what the problem is:

The leading German Streaming Provider is putting more customers on their 2.0 platform. Unfortunately one video addon and a PVR addon have been programmed but both show the same behaviour with inputstream.adaptive. Streams are being played under Windows and Linux but not under AndroidTV. Kodi seems to do something but the screen remains black - no audio as well.
As said under Linux and Windows the streams do not show any issues at all.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Streams should also work under AndroidTV. Android itself is untested

## Actual Behavior

Once a stream is selected Kodi tries to play it - there is no error message - but the screen remains black.

## Possible Fix

No idea

### To Reproduce

1. Start a stream of the German Streaming Provider under AndroidTV
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ecidudaxoc.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://svc45.main.sl.t-online.de/bpk-tv/das_erste_hd/DASH/index.mpd

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 RC
 - inputstream.adaptive version: 21.4.3

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sunsettrack4** [comment]
`error <general>: OpenStream: Codec id 27 require extradata.
warning <general>: OpenStream - Unsupported stream 1001. Stream disabled.
`
The video stream always gets disabled - @CastagnaIT Do you know why that stream requires extra data on Android OS?

**Comment by CastagnaIT** [comment]
i tried download the init video file
the mp4 box show SPS/PPS fields empty, in theory this should be the cause of no extradata
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/fd40dba2-2330-4ce6-b8b7-5e50b5902a4d)

but you affirm that this stream works on Windows and Linux, so this confuses me
so i dont know exactly what to think

**Comment by nirvana-7777** [comment]
Yes, personally I can speak for Linux. The respective debug.log of inputstream.adaptive while playing the stream under Linux:

[Debug Log](https://paste.kodi.tv/runoduxawo.kodi)

**Comment by CastagnaIT** [comment]
has been cutoff all kodi core debug log from that log

**Comment by nirvana-7777** [comment]
True. Now included:

[Log](https://paste.kodi.tv/uqageqineg.kodi)

**Comment by CastagnaIT** [comment]
hmm i have not clear idea on how kodi core VP works
also comparing logs apparently seem that VP use different code paths between linux/android

its clear that stuck here
https://github.com/xbmc/xbmc/blob/e70f0d83f3ae5e5026cf6b6402c8d7e05662bc8a/xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp#L112-L123

i found this explanation on the web

>Amendment 2 of ISO/IEC 14496-15 (AVC file format) is defining a new structure for fragmented MP4 called "avc3". The principal difference between AVC1 and AVC3 is the location of the codec initialisation data (e.g. SPS, PPS). In AVC1 this data is placed in the initial MOOV box (moov.trak.mdia.minf.stbl.stsd.avc1) but in AVC3 this data goes in the first sample of every fragment (i.e. the first sample in each mdat box). The principal reason for avc3 is to make it easier for client implementations, because it removes the requirement to insert the SPS+PPS in to the decoder pipeline every time there is a representation change

that can explain why there is no SPS PPS on the init data
and so my MP4 init data screenshot above show right things

one possibility to test should be try change on Kodi core VP (linked above), the line:
`hint.codec == AV_CODEC_ID_H264 ||`
with
`(hint.codec == AV_CODEC_ID_H264 && hint.codec_tag != MKTAG('a','v','c','3')) ||`

and on ISA side

https://github.com/xbmc/inputstream.adaptive/blob/31dc91e870313c9145d881d17abcb372997a274f/src/Session.cpp#L793-L795

on H264 condition add the missing fourcc 
`stream.m_info.SetCodecFourCC(CODEC::MakeFourCC(...));`

OFC is needed build Kodi and also ISA with mentioned changes in order to test

PS: or try remove only the line on kodi VP just to do a fast test to see what happens

**Comment by CastagnaIT** [comment]
i builded kodi apk by removing forced extradata requirement
let me know what happens

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20240328-56ded866-extradata_avc3-armeabi-v7a.apk
http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20240328-56ded866-extradata_avc3-arm64-v8a.apk

**Comment by nirvana-7777** [comment]
Wow! Thank you. Yes, I can confirm that this Kodi Version plays the streams.

**Comment by CastagnaIT** [comment]
i found a sample stream avc3 but since its without DRM play without problems on android so i still cant test by myself

i will prepare the changes for kodi and ISA
when i will have both done, i will prepare a new test for you to have a confirmation that changes works

**Comment by CastagnaIT** [comment]
ok i have prepared the complete test fix
install both first kodi and after ISA
let me know

Kodi builds:
https://jenkins.kodi.tv/job/android-arm-docker/5956/artifact/kodi-20240329-7b232a41-PR24911-armeabi-v7a.apk
https://jenkins.kodi.tv/job/android-arm64-docker/5759/artifact/kodi-20240329-7b232a41-PR24911-arm64-v8a.apk

ISA builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1515/1/artifacts

**Comment by nirvana-7777** [comment]
Tested and confirmed working.

First did only the Kodi update. Does not work. Also not expected to work.
Then installed ISA from above. Works.

From my side green light. Please go ahead.
Thank you very much again for your efforts!
