### ISSUE TITLE
Compilation error in arm7h

### ISSUE THREAD

**Issue by boina** [peak3d/inputstream.adaptive#1516]
### Describe the bug

The compilation of inputstream.adative (Omega) in a raspberry pi 4 (armv7) stops with an error at the beginning of  build.
The error seems to be related to one of the flags used. The cc compiler exits with this message:

`cc: error: unrecognized command-line option ‘-mno-omit-leaf-frame-pointer’; did you mean ‘-fno-omit-frame-pointer’?`

I'm trying to compile adaptive inputstream in a arm archlinux installation. I'm using a PKGBUILD from the AUR (https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive-git)

## Expected Behavior

Compilation should continue until completion and generation of an installation file.

## Actual Behavior

Compilation stops with an error at the beginning of build.

## Possible Fix

I have tried to add these flags to the PKGBUILD but I keep having the same error.  Is there any other file/s I should add these flags?

```
 -DCMAKE_C_FLAGS="${CFLAGS} -fno-omit-leaf-frame-pointer" \
 -DCMAKE_CXX_FLAGS="${CXXFLAGS} -fno-omit-leaf-frame-pointer" \
```

### To Reproduce

1. Compile in raspberry pi with an archlinux install.
2.
3.

### Debuglog

The debuglog can be found here:
[adaptive.inputstream.bug.txt](https://github.com/xbmc/inputstream.adaptive/files/14817048/adaptive.inputstream.bug.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

It's an archlinux installation on a raspberry pi 4 (armv7h).

 - Operating system version/name:
 - Kodi version: 20.5
 - inputstream.adaptive version: Omega

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
I have no knowledge of building outside of the default kodi build system
i will try point out to other devs

**Comment by phunkyfish** [comment]
With arch builds generally someone contributes the package build file and then the community uses it, correct?

it’s possible this never got updated for RPI4. Can you contacts the maintainer of that file?

**Comment by boina** [comment]
Solved. It was a [faulty default configuration](https://archlinuxarm.org/forum/viewtopic.php?f=57&t=16830&p=72344&hilit=no+omit+leaf+frame+pointer#p72344) for the armv7 platform.
After removing the wrong flag, compilation and installation work.
Thanks!!
