### ISSUE TITLE
[K21, DASH, live stream with time shifting buffer] playback start from first period not last (like VOD content)

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1517]
### Describe the bug
Here is a clear and concise description of what the problem is:

From ver. 21.4.4 ISA play live stream with time shifting buffer like VOD content.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback live stream with time shifting buffer from last (current) period with the ability to change the period during playback.

## Actual Behavior

playback live stream from wrong period.

### To Reproduce

1.  Playback live stream (with time shifting buffer)
2.
3.

### Debuglog

The debuglog can be found here:
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/14818927/log.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[manifest_1711939990.txt](https://github.com/xbmc/inputstream.adaptive/files/14818929/manifest_1711939990.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Current behavior:
![TVN nieprawidłowo](https://github.com/xbmc/inputstream.adaptive/assets/86961563/a7428050-d29f-4292-aea1-be877dc67ce2)
Expecting behavior:
![tvn_prawidłowo](https://github.com/xbmc/inputstream.adaptive/assets/86961563/cd4d0fea-9b68-4504-9950-904959ac9bf1)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2, kernel: Windows NT x86 64-bit version
 - Kodi version: 22.0-ALPHA1 (21.90.700) Git:20240326-e70f0d83f3
 - inputstream.adaptive version: 21.4.4

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
hmm should happens because i have removed generation of segments for the timeshiftbuffer
now that the code is more cleanedup i hope to restore the situation more easily way

**Comment by CastagnaIT** [comment]
let me know if now is all ok
test builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1518/7/artifacts

**Comment by mtr81** [comment]
Ver. from PR #1518 solves the problem.

**Comment by Jusix** [comment]
@CastagnaIT Looks like I suffer from this issue with the current Linux Flatpak. How can I get a test build of the new version?

**Comment by CastagnaIT** [comment]
dont exists official releases for linux distributions,
some are maintained by external users but could be that are not always updated
i think you will need to build by yourself the binary add-on, on wiki there are some generic instructions
