### ISSUE TITLE
Compilation error under aarch64 (Raspberry Pi Slackware aarch64)

### ISSUE THREAD

**Issue by Johpin1** [peak3d/inputstream.adaptive#1520]
### Describe the bug
Here is a clear and concise description of what the problem is:

I tried to compile inputstream.adaptive (master and 21.4.4) for Kodi Omega 21.0rc2 on latest Slackware aarch64, but it gives an error .

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected no errors.

## Actual Behavior

Compilation stopped.

## Possible Fix

No idea.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
I don't have a kodi.log file, only stdout:

[ 30%] Building CXX object CMakeFiles/inputstream.adaptive.dir/src/Session.cpp.o
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp: In member function ‘bool SESSION::CSession::ExtractStreamProtectionData(PLAYLIST::CPeriod::PSSHSet&, std::vector<unsigned char>&, std::string)’:
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp:1427:40: error: ‘class AP4_Movie’ has no member named ‘GetPsshAtoms’
 1427 |   AP4_Array<AP4_PsshAtom>& pssh{movie->GetPsshAtoms()};
      |                                        ^~~~~~~~~~~~
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp:1427:54: error: invalid initialization of non-const reference of type ‘AP4_Array<AP4_PsshAtom>&’ from an rvalue of type ‘<brace-enclosed initializer list>’
 1427 |   AP4_Array<AP4_PsshAtom>& pssh{movie->GetPsshAtoms()};
      |                                                      ^
make[2]: *** [CMakeFiles/inputstream.adaptive.dir/build.make:118: CMakeFiles/inputstream.adaptive.dir/src/Session.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: CMakeFiles/inputstream.adaptive.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Slackware aarch64, version "current", installed on a Raspberry Pi 5
 - Kodi version: 21.0rc2
 - inputstream.adaptive version: 21.4.4 and master

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
I have limited knowledge about linux builds
suggest to take a look at https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build

from what i can see seem that you are building ISA with a wrong version of Bento4 library,
more likely with an upstream version instead of kodi bento4

**Comment by Johpin1** [comment]
Thanks. You're right. I had used the upstream version.

Now the compilation stops even earlier due to an issue with the audiocodec, see for the erros:
[https://paste.kodi.tv/usocezijuk.kodi](url)

I don't know if it is a Linux distribution problem, otherwise I can better wait for an update of the Slackbuild package.

**Comment by CastagnaIT** [comment]
i think you are compiling ISA in wrong way
these errors suggest that you are compiling ISA without kodi sources or with some wrong cmake configuration

kodi team currently does not maintain any linux distribution packages, so linux packages are managed by third party
you should ask the maintainer of that package
otherwise i suggest making the build taking a cue from the wiki link provided

**Comment by Johpin1** [comment]
Finally I succeeded in building it correctly. I was focusing on Bento4, but I should have compiled it in the way I did for inputstream.ffmpegdirect, inputstream.rtmp and pvr.simple.

In the README I overlooked the line with the reference to the wiki: I only searched for the section "Build instructions", like the forementioned addons have. I recommend to add Build instructions to the README, like the way it has been done for for example
inputstream.ffmpegdirect, see
[https://github.com/xbmc/inputstream.ffmpegdirect/blob/Omega/README.md](url).

Thanks for your patience. This issue can be closed.

Off topic: I have compiled Kodi with CEC support, but the CEC adapter does not exist despite of libcec has been found during configuring. I can switch of my television using cec-ctrl. I made a thread on the Kodi forum [https://forum.kodi.tv/showthread.php?tid=376807](url), but no response.
Should I have post it under another theme? Do you have any suggestion to debug this?

**Comment by CastagnaIT** [comment]
happy that you solved,
on this repo we dont use readme for any kind of instructions its a our choice,
the reason is that there are too many topics which are often updated
and more importantly Readme file require a direct git branch change, that become inconvenient because there are more active branches, so for us Wiki is the appropriate place to be updated frequently without touch the git branches

> Should I have post it under another theme? Do you have any suggestion to debug this?

unfurnately i cant help on this, i know that Kodi LIbreElec have it, maybe someone can give you some hint
