### ISSUE TITLE
[K21, DASH, VOD content] problem with playback MPD manifest

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1521]
Seems ISA has problem with playback below MPD manifest:
[manifest_1712439054.txt](https://github.com/xbmc/inputstream.adaptive/files/14895083/manifest_1712439054.txt)
For some reason the audio and video segments are completely ignored.
**Log**:
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/14895082/log.txt)
**System**:
Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.4170
**Kodi version**:
21.0 (21.0.0) Git:20240406-60c4500054
**ISA version**:
21.4.4 from PR #1518

The problem does not occur on Kodi 20.

**Comment by CastagnaIT** [comment]
please let me know
build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1523/1/artifacts

**Comment by mtr81** [comment]
Still doesn't work.
Partial log:
[log2.txt](https://github.com/xbmc/inputstream.adaptive/files/14897194/log2.txt)
Manifest:
[manifest_1712492907.txt](https://github.com/xbmc/inputstream.adaptive/files/14897195/manifest_1712492907.txt)

**Comment by CastagnaIT** [comment]
this should work
new build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1523/2/artifacts

**Comment by mtr81** [comment]
Thanks! Now works fine ;-)
