### ISSUE TITLE
[MPD K21] Some .mpd Streams doesn't start with iOS

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1527]
### Describe the bug
Here is a clear and concise description of what the problem is:

When testing various DASH streams in iOS, I found that this one: http://mdrtvsndash.akamaized.net/dash/live/2094117/mdrtvsn/dash.mpd does not start (loading circuit) and Kodi returns to the selection.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The stream should start in iOS with Kodi 21.0 and ISA 21.4.4.

## Actual Behavior

The stream does not start (loading circuit) and Kodi returns to the selection

## Possible Fix

see https://github.com/xbmc/inputstream.adaptive/issues/1507#issuecomment-2049318089

### To Reproduce

1. Start Kodi
2. Play Stream: http://mdrtvsndash.akamaized.net/dash/live/2094117/mdrtvsn/dash.mpd with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debuglog

The debuglog can be found here:
https://github.com/xbmc/inputstream.adaptive/files/14944291/kodidebug_iOS.log.zip

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
http://mdrtvsndash.akamaized.net/dash/live/2094117/mdrtvsn/dash.mpd

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: iOS 14.4.2 (Darwin 20.3.0)
 - Kodi version: 21.0
 - inputstream.adaptive version: inputstream.adaptive v21.4.4 incl. Fix #1526 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i attach here the mpd since the provided link is geolock
[dash.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/14949964/dash.mpd.txt)

seem that change this 
https://github.com/xbmc/inputstream.adaptive/blob/109c0e7abb29719a519860f2fcf152aea1b6b31b/src/parser/DASHTree.cpp#L1109
to
`segNumber += tsbStart / segDurMs;`
solve the problem that should be as was in origin the old code
but i will need to re-test the other live stream samples
this code easily can make one stream to work and break the others...

**Comment by CastagnaIT** [comment]
@werimail if you want test your live streams with this
EDIT-UPD: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1529/3/artifacts
let me know if you will find others broken live streams

**Comment by werimail** [comment]
> @werimail if you want test your live streams with this EDIT-UPD: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1529/3/artifacts let me know if you will find others broken live streams

It works now @CastagnaIT  So far I haven't been able to find a .mpd/DASH stream that didn't work with fix #1529 yet.

Thanks and greetings Weri
