### ISSUE TITLE
AES 128 key and IV via code

### ISSUE THREAD

**Issue by GladistonXD** [peak3d/inputstream.adaptive#1535]
I made a continuous hls server, where I only get the .ts files, but it runs without decryption, is it possible to quickly customize the outputs?

```python
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
def decrypt_file(input_file, output_file, key, iv):
    cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
    decryptor = cipher.decryptor()
    with open(input_file, 'rb') as f:
        encrypted_data = f.read()
    decrypted_data = decryptor.update(encrypted_data) + decryptor.finalize()

    with open(output_file, 'wb') as f:
        f.write(decrypted_data)

input_file = 'video_encrypted.mp4'
output_file = 'video_decrypted.ts'
key = b'\xda\xde"\rZ\xa3+t\x11\xd9\xcf\x1a\x88\r\xfc\xdd'
iv = b'\xf4>\x06#\xc1>\x98X\x01\n\xea\x1dg 6\x14'

decrypt_file(input_file, output_file, key, iv)
```
[video_encrypted.mp4](https://github.com/xbmc/inputstream.adaptive/assets/50533550/0aed31d2-5158-47bd-be7c-59b583f0b673
)
It would be something like this, but directly in input.adaptive or another faster decryption method in Kodi.
`#EXT-X-KEY:METHOD=AES-128,URI="/key/...",IV=...`
Would something like this be possible?
```python
listem.setProperty('inputstream', 'inputstream.adaptive')
listem.setProperty('inputstream.adaptive.license_key', 'key=', 'iv=')
```
Or do something directly in the player via advancedsettings.xml
If possible, someone can help.

**Comment by CastagnaIT** [comment]
fwik you cant
seem you want to simulate a live stream
it is best to manage everything inside your HLS server by building the appropriate master/child playlists with the appropriate HLS tags

**Comment by GladistonXD** [comment]
I understood the concept, in this case, instead of launching the videos directly on the server, I would put them in the form of links with HLS tags along with the Keys in a traditional way, I thought there could be a group of this kind:
```python 
listem.setProperty('inputstream.adaptive.license_key', 'key=', 'iv=')
```
thanks.
