### ISSUE TITLE
MPD with new period gets stuck during playback

### ISSUE THREAD

**Issue by tmm1** [peak3d/inputstream.adaptive#1540]
## Bug report
Regression of #1175 

### Describe the bug
Previously would show "Switching to new Period"

Now playback gets stuck and the logs show mpd refresh over and over without switching over to the next period

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

```
[AS-0] Download finished: 1711567398226item-06item_Segment-664560.mp4 (downloaded 2285902 byte, speed 57610955.24 byte/s)
[AS-1] Download finished: 1711567398226item-07item_Segment-664560.mp4 (downloaded 108040 byte, speed 3620498.81 byte/s)
ensureSegment: [AS-0] Begin WaitForSegment stream rep. id "1711567398226item-06item" period id "5760"
Download finished: master.mpd (downloaded 21646 byte, speed 322131.44 byte/s)
RefreshLiveSegments: MPD update - Done (repr. id "1711567398226item-06item", period id "5760")
RefreshLiveSegments: MPD update - Done (repr. id "1711567398226item-07item", period id "5760")
RefreshLiveSegments: Inserting new Period (id=5761, start=2593986796)
Download finished: master.mpd (downloaded 21826 byte, speed 146706.51 byte/s)
RefreshLiveSegments: MPD update - Done (repr. id "1711567398226item-06item", period id "5760")
RefreshLiveSegments: MPD update - Done (repr. id "1711567398226item-07item", period id "5760")
Download finished: master.mpd (downloaded 21844 byte, speed 713352.29 byte/s)
```

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
how do you think we can investigate if you dont attach the full debug log and all the manifests?

**Comment by tmm1** [comment]
Don't worry I'll fix it.

**Comment by CastagnaIT** [comment]
closed since you havent provided any way to test it
