### ISSUE TITLE
[HLS, live stream] problem with synchronization audio and video

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1544]
### Describe the bug
Here is a clear and concise description of what the problem is:

HLS live stream is playing without audio and video synchronization. Playback in Kodi 20 and 19 without problems.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback with audio and video synchronization.

## Actual Behavior

Playing without audio and video synchronization.

## Possible Fix

Unknown.

### To Reproduce

1.  Start playback live stream (HLS protocol)
2.  Stream is playing without audio-video synchronization.
3.

### Debuglog

The debuglog can be found here:

[log.txt](https://github.com/xbmc/inputstream.adaptive/files/15171111/log.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifest_1714509295_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15171112/manifest_1714509295_master.txt)
[manifest_1714509296_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171113/manifest_1714509296_child-video.txt)
[manifest_1714509297_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171114/manifest_1714509297_child-audio.txt)
[manifest_1714509297_child-subtitle.txt](https://github.com/xbmc/inputstream.adaptive/files/15171115/manifest_1714509297_child-subtitle.txt)
[manifest_1714509300_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171116/manifest_1714509300_child-video.txt)
[manifest_1714509301_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171117/manifest_1714509301_child-audio.txt)
[manifest_1714509309_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171118/manifest_1714509309_child-audio.txt)
[manifest_1714509309_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171119/manifest_1714509309_child-video.txt)
[manifest_1714509313_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171120/manifest_1714509313_child-audio.txt)
[manifest_1714509313_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171121/manifest_1714509313_child-video.txt)
[manifest_1714509317_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171122/manifest_1714509317_child-audio.txt)
[manifest_1714509317_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171123/manifest_1714509317_child-video.txt)
[manifest_1714509326_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171124/manifest_1714509326_child-audio.txt)
[manifest_1714509326_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171125/manifest_1714509326_child-video.txt)
[manifest_1714509330_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171126/manifest_1714509330_child-audio.txt)
[manifest_1714509330_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171127/manifest_1714509330_child-video.txt)
[manifest_1714509334_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171128/manifest_1714509334_child-audio.txt)
[manifest_1714509334_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171129/manifest_1714509334_child-video.txt)
[manifest_1714509342_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171130/manifest_1714509342_child-audio.txt)
[manifest_1714509342_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171131/manifest_1714509342_child-video.txt)
[manifest_1714509350_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15171132/manifest_1714509350_child-video.txt)
[manifest_1714509351_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15171133/manifest_1714509351_child-audio.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2, kernel: Windows NT x86 64-bit version
 - Kodi version: 21.0
 - inputstream.adaptive version: 21.4.5

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mtr81** [comment]
Similar issue with stream ```https://hugh.cdn.rumble.cloud/live/3fms19g4/slot-129/fpd5-jyun/chunklist_DVR.m3u8```
In this case playback stops periodically.
**LOG**: 
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/15189050/log.txt)
**Manifests:**
[manifest_1714655542_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15189053/manifest_1714655542_master.txt)
[manifest_1714655543_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189054/manifest_1714655543_child-video.txt)
[manifest_1714655547_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189055/manifest_1714655547_child-video.txt)
[manifest_1714655556_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189056/manifest_1714655556_child-video.txt)
[manifest_1714655560_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189058/manifest_1714655560_child-video.txt)
[manifest_1714655566_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189060/manifest_1714655566_child-video.txt)
[manifest_1714655571_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189061/manifest_1714655571_child-video.txt)
[manifest_1714655575_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189062/manifest_1714655575_child-video.txt)
[manifest_1714655580_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189063/manifest_1714655580_child-video.txt)
[manifest_1714655589_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189064/manifest_1714655589_child-video.txt)
[manifest_1714655597_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15189065/manifest_1714655597_child-video.txt)

**Comment by CastagnaIT** [comment]
im not sure that both cases have the same problem,
i was not able to figure out the problem on issue log above

but for
https://hugh.cdn.rumble.cloud/live/3fms19g4/slot-129/fpd5-jyun/chunklist_DVR.m3u8
its possible this use case has been broken with recent fixes
where `AdaptiveStream::ensureSegment` now make use of `GetSegmentByPts` to find the segment
so i suspect that after a manifest update, segments lost their pts and then `GetSegmentByPts` select a wrong segment

**Comment by mtr81** [comment]
> i was not able to figure out the problem on issue log above

But I see problem on screen - freezing, double playback the same audio segment etc. 
I try to play the same stream in ffmpeg direct player and there's no problem with playback. Also in ISA for K19 and K20...

**LOG - playback via ffmpeg direct player**
[log_ffmpeg_direct.txt](https://github.com/xbmc/inputstream.adaptive/files/15190532/log_ffmpeg_direct.txt)

**LOG - playback via ISA**
[log_ISA.txt](https://github.com/xbmc/inputstream.adaptive/files/15190534/log_ISA.txt)

**MANIFESTS (ISA)**
[manifest_1714662812_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15190581/manifest_1714662812_master.txt)
[manifest_1714662814_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190582/manifest_1714662814_child-audio.txt)
[manifest_1714662814_child-subtitle.txt](https://github.com/xbmc/inputstream.adaptive/files/15190583/manifest_1714662814_child-subtitle.txt)
[manifest_1714662814_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190584/manifest_1714662814_child-video.txt)
[manifest_1714662822_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190585/manifest_1714662822_child-audio.txt)
[manifest_1714662822_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190586/manifest_1714662822_child-video.txt)
[manifest_1714662826_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190587/manifest_1714662826_child-audio.txt)
[manifest_1714662826_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190589/manifest_1714662826_child-video.txt)
[manifest_1714662834_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190590/manifest_1714662834_child-audio.txt)
[manifest_1714662834_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190591/manifest_1714662834_child-video.txt)
[manifest_1714662838_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190592/manifest_1714662838_child-audio.txt)
[manifest_1714662838_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190593/manifest_1714662838_child-video.txt)
[manifest_1714662847_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190594/manifest_1714662847_child-audio.txt)
[manifest_1714662847_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190595/manifest_1714662847_child-video.txt)
[manifest_1714662851_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190596/manifest_1714662851_child-audio.txt)
[manifest_1714662851_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190598/manifest_1714662851_child-video.txt)
[manifest_1714662855_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15190600/manifest_1714662855_child-audio.txt)
[manifest_1714662855_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15190601/manifest_1714662855_child-video.txt)

**Comment by mtr81** [comment]
Another case - look at the counter:
Screen from Kodi 20:
![K20_hls_static](https://github.com/xbmc/inputstream.adaptive/assets/86961563/b5ce6fb9-f73a-424c-a040-a990457da2ba)
Screen from Kodi 21:
![K21_hls_static](https://github.com/xbmc/inputstream.adaptive/assets/86961563/9dd5db0f-57fb-48e6-8a2c-1d56d387ceec)

The same content was playback...

Manifests:
[manifest_1715135428_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15243188/manifest_1715135428_master.txt)
[manifest_1715135429_child-audio.txt](https://github.com/xbmc/inputstream.adaptive/files/15243189/manifest_1715135429_child-audio.txt)
[manifest_1715135429_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15243190/manifest_1715135429_child-video.txt)

**Comment by mtr81** [comment]
Similar (this time live stream):

Kodi 20
![K20_hls_live_counter](https://github.com/xbmc/inputstream.adaptive/assets/86961563/c20c8701-93da-4ab8-9448-5263d6b28d1d)

Kodi 21
![K21_hls_live_counter](https://github.com/xbmc/inputstream.adaptive/assets/86961563/a8fbbc52-c0a2-44a5-8168-9c64e2545830)

Manifests:

[manifest_1715136532_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15243307/manifest_1715136532_master.txt)
[manifest_1715136534_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15243308/manifest_1715136534_child-video.txt)

**Comment by CastagnaIT** [comment]
here you are collecting different cases on same issue
despite can be similar at screen, could be not so on source code and its needed investigate on each case
so it's starting to make it hard for me to follow this issue
please do not add other cases here otherwise it becomes a mess

now, i found a problem, the datetime was incorrectly parsed and it could, maybe, cause some problems on some posted streams
`#EXT-X-PROGRAM-DATE-TIME:2024-04-30T20:19:53.145433Z`

try test PR #1552 test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1552/2/artifacts
let me know if you find some difference

**Comment by mtr81** [comment]
Without changes - same situation as https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099627994

**Comment by CastagnaIT** [comment]
there is a website where get an updated url of
https://hugh.cdn.rumble.cloud/live/3fms19g4/slot-129/fpd5-jyun/chunklist_DVR.m3u8
or to get another similar? because looks like expired

**Comment by CastagnaIT** [comment]
ok for the "DVR" live,
the cause is that this service provide an inaccurate EXT-X-PROGRAM-DATE-TIME value
that cause to calculate a misaligned pts on segments after a manifest update
with the possible side effect to select wrong segment

as following example on `master_a1_20240514T061725_1245157.aac` segment
should have 1715667445174 but on next manifest update the datetime has been increased to 1715667445180

**previous aac child manifest**
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1245154
#EXT-X-PROGRAM-DATE-TIME:2024-05-14T06:17:19.180Z // 1715667439180
#EXTINF:2.00533,
master_a1_20240514T061719_1245154.aac // 1715667439180
#EXTINF:1.98400,
master_a1_20240514T061721_1245155.aac // 1715667441185
#EXTINF:2.00533,
master_a1_20240514T061723_1245156.aac // 1715667443169
#EXTINF:2.00533,
master_a1_20240514T061725_1245157.aac // 1715667445174
#EXTINF:2.00533,
master_a1_20240514T061727_1245158.aac
#EXTINF:1.98400,


**next aac child manifest**
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1245157
#EXT-X-PROGRAM-DATE-TIME:2024-05-14T06:17:25.180Z  // 1715667445180
#EXTINF:2.00533,
master_a1_20240514T061725_1245157.aac
#EXTINF:2.00533,
master_a1_20240514T061727_1245158.aac
#EXTINF:1.98400,
master_a1_20240514T061729_1245159.aac
#EXTINF:2.00533,
master_a1_20240514T061731_1245160.aac
#EXTINF:2.00533,
master_a1_20240514T061733_1245161.aac
#EXTINF:2.00533,


i will make a test to restore the parser to have seconds instead ms, this should in theory hidden the problem
so even in the case of value rounding it should cause fewer problems

**Comment by CastagnaIT** [comment]
i found that "DVR" live service has inaccurare EXT-X-PROGRAM-DATE-TIME values between manifest updates
so its possible that this is the cause of the wrong selected segments
i will try investigate better

previous aac child manifest

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1245154
#EXT-X-PROGRAM-DATE-TIME:2024-05-14T06:17:19.180Z // 1715667439180
#EXTINF:2.00533,
master_a1_20240514T061719_1245154.aac // 1715667439180
#EXTINF:1.98400,
master_a1_20240514T061721_1245155.aac // 1715667441185
#EXTINF:2.00533,
master_a1_20240514T061723_1245156.aac // 1715667443169
#EXTINF:2.00533,
master_a1_20240514T061725_1245157.aac // 1715667445174
#EXTINF:2.00533,
master_a1_20240514T061727_1245158.aac
#EXTINF:1.98400,


next aac child manifest
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1245157
#EXT-X-PROGRAM-DATE-TIME:2024-05-14T06:17:25.180Z  // 1715667445180
#EXTINF:2.00533,
master_a1_20240514T061725_1245157.aac // 1715667445180
#EXTINF:2.00533,
master_a1_20240514T061727_1245158.aac
#EXTINF:1.98400,
master_a1_20240514T061729_1245159.aac
#EXTINF:2.00533,
master_a1_20240514T061731_1245160.aac
#EXTINF:2.00533,
master_a1_20240514T061733_1245161.aac
#EXTINF:2.00533,

**Comment by mtr81** [comment]
I see that the default player skips these tags and that's why it works fine
```info <general>: ffmpeg[0x16d29b218c0]: [hls] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-14T15:26:36.000+0200')```

**Comment by CastagnaIT** [comment]
i made a fix, at least HLS "PVR" live now seem to works correctly
but i will need more time to test it to check for regressions for others use cases hoping my old test streams still works

EDIT:
builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1555/2/artifacts

**Comment by mtr81** [comment]
Issue https://github.com/xbmc/inputstream.adaptive/issues/1544#issue-2272463886 seems fixed but https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099627994 not at all. Also https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099650763 still without changes.
In all the above cases ISA for Kodi 20 works without problems...

**Comment by CastagnaIT** [comment]
> Issue https://github.com/xbmc/inputstream.adaptive/issues/1544#issue-2272463886 seems fixed but https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099627994 not at all. Also https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099650763 still without changes.
In all the above cases ISA for Kodi 20 works without problems...

because these cases "works" on kodi 20 dont means that was working because correctly implemented,
on Kodi 20 ISA have tons of bugs, hacks, workaround.. these mentioned are two examples so

for https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099650763
is a live with multiple periods, and the last period has no defined duration, so no total time (GUI right time) will be shown
on Omega is intended as is for now, no changes are intended to do.

for the https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099627994
is another story, this a weird case at least on my eyes
looks as a VOD stream, but have EXT-X-PROGRAM-DATE-TIME that should be used with live streams
some services may assume this like a "live to VOD" transition, but nothing of this is declared on official docs,
and i dont think this case has been really tested on ISA from our part.
The weird GUI time on Omega more likely is shown due to new EXT-X-PROGRAM-DATE-TIME implementation,
i dont see this like a real bug seem to be more a provider customization, that cause this side effect, would better if you open a separate issue for this case

**Comment by mtr81** [comment]
> for the [#1544 (comment)](https://github.com/xbmc/inputstream.adaptive/issues/1544#issuecomment-2099627994)
> is another story, this a weird case at least on my eyes
> looks as a VOD stream, but have EXT-X-PROGRAM-DATE-TIME that should be used with live streams
> some services may assume this like a "live to VOD" transition, but nothing of this is declared on official docs,
> and i dont think this case has been really tested on ISA from our part.
> The weird GUI time on Omega more likely is shown due to new EXT-X-PROGRAM-DATE-TIME implementation,
> i dont see this like a real bug seem to be more a provider customization, that cause this side effect, would better if you open a separate issue for this case

I won't waste any more time. I will solve the problem using a HTTP server...
