### ISSUE TITLE
Disney+ and new ISA v21.4.6 - KODI crash

### ISSUE THREAD

**Issue by zuzia-dev** [peak3d/inputstream.adaptive#1545]
### Describe the bug
When trying to play any video KODI crashes. In KODI 19 and 20 it plays without problems. The problem was also reported to the add-on's author: https://github.com/matthuisman/slyguy.addons/issues/731

## Expected Behavior
Stream should be played with inputstream.adaptive v21.4.6.

## Actual Behavior
Any stream from the Disney+ add-on cannot be played. 

## Possible Fix
Unknown

### To Reproduce

1. Start the stream.
2.
3.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/isiyaviheh.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here: [manifest.txt](https://raw.githubusercontent.com/hosting-GH/Logs/main/manifest.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 12 (bookworm), kernel: Linux x86 64-bit version 6.1.0-20-amd64
 - Kodi version: Kodi (21.0 (21.0.0) Git:20240414-nogitfound)
 - inputstream.adaptive version: 21.4.6

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
ouch broken with last change 
should be add a new test case
too much things to remember

**Comment by Ronny-nerd** [comment]
I have the same problem, for example, with the Nvidia Shield TV (Android 11) and on the PC with Windows 10 Pro.

After PR 1532 we already had this problem.
After PR 1543 everything was still OK.

**Comment by zuzia-dev** [comment]
Thank you for your quick response. The [patch](https://github.com/xbmc/inputstream.adaptive/pull/1547) fixes the problem with Linux as well, now the stream plays correctly.
