### ISSUE TITLE
Request headers set by user are used only in the initial request, and not in subsequent requests

### ISSUE THREAD

**Issue by kashaCode** [peak3d/inputstream.adaptive#1546]
### Describe the bug
My streaming service does not have a Kodi client, so I maintain my own. For authentication, certain HTTP request headers are required to be set. I am setting those via this line in my add-on:

```
"inputstream.adaptive.manifest_headers": urlencode(ISHeaders)
```
ISA is using the headers correctly in the initial request for manifest. Using Fiddler, I intercepted HTTP(S) traffic. See highlighted in red rectangle in screenshot:

![mpd-req](https://github.com/xbmc/inputstream.adaptive/assets/150218448/3fd29308-d09c-43ab-9a44-2171440fe292)

But in the subsequent request to actually get the individual video segment files mentioned in the mpd manifest, these headers are not used. See "User-Agent" in screenshot:

![dash-req](https://github.com/xbmc/inputstream.adaptive/assets/150218448/10332868-213e-42d4-86c6-208505a60878)

## Expected Behavior
Headers (those that are relevant) set by user should be used in all subsequent requests.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:Nightly build KodiSetup-20240429-625be876-Omega-x64
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
as the name of the property says
`inputstream.adaptive.manifest_headers`
its for manifest only

read integration page
https://github.com/xbmc/inputstream.adaptive/wiki/Integration
