### ISSUE TITLE
Does Kodi 21 limit buffer length to 4 hours?

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1549]
I have a manifest that has 24H buffer length but Kodi 21 seems to always show 4hours no matter what.
[in.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/15218999/in.mpd.txt)

Kodi 20 shows full 24 hours

**Comment by Uukrull** [comment]
https://github.com/xbmc/inputstream.adaptive/blob/0e0820d5a91936a7ca5d953c0f7ad2bd0dce8c0f/src/parser/DASHTree.cpp#L320-L325

https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemanifest_config-

**Comment by matthuisman** [comment]
thanks
"The maximum timeshift buffer depth in seconds, the default value is 4 hours (14400000 secs). This is limited to avoid excessive memory consumption with very large TSB values."

I think the wiki should be saying "mililseconds" not seconds

**Comment by CastagnaIT** [comment]
its seconds, there is a wrong example value
