### ISSUE TITLE
Setting a header for a HLS AES-128 License Key URL

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#155]
Just thought I would put this here for reference if anyone is trying to do the same.

I had a HLS stream using AES-128 that required a specific header to be passed to the AES license key URL.

I thought I may need to download the playlist, pull out the license url and then use that, but you can do this:

**#KODIPROP:inputstream.adaptive.license_key=|header=value**

eg.
#KODIPROP:inputstream.adaptive.license_key=|authorization=dfyJraWQtrreMzIx

You can leave out the url and it will still use the URL found in the playlist.
The first PIPE is required as this separates the URL from headers.

**Comment by vaselinetv** [comment]
Any idea on adding cookies to the stream url using #KODIPROP ? thanks in advance.

**Comment by fernandoalonzo** [comment]
I just want to mention that this has a limitation in the string length after the pipe, which seems to be ~1KB. I have some streams that require a pretty long authorization token (almost 2KB), which always gets truncated and passed to the server, thus making impossible to play the stream. I'm not sure how to workaround this problem, might open a new issue to see if anybody knows.

**Comment by matthuisman** [comment]
you'd need to use your own proxy and add the header to the call yourself

**Comment by fernandoalonzo** [comment]
Hey thanks for the quick response! I thought about writing my own proxy but the license key URI is in the m3u8 playlist itself, which doesn't seem possible to overwrite (with custom KODIPROP), unless I download the playlist and replace it everywhere.

**Comment by glennguy** [comment]
Does the same limitation exist if you play via a python add-on? 
I don't think the hard limit is happening in the code in inputstream.adaptive....

**Comment by matthuisman** [comment]
maybe same issue as this:
https://github.com/xbmc/xbmc/issues/20001
