### ISSUE TITLE
[HLS, Livestream] Plays in Nexus, but not in Omega

### ISSUE THREAD

**Issue by MetalChris** [peak3d/inputstream.adaptive#1553]
### Describe the bug
Here is a clear and concise description of what the problem is:

Stream manifest is downloaded and parsed, but stream does not play.  Other HLS streams from same source will play through ISA in Omega without issue.  Stream plays without issue using FFmpeg, though stream loading is much slower so use of ISA is preferred.

The stream plays as expected in Nexus with ISA version 20.3.18.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Stream should play as expected without issue.

## Actual Behavior

Stream manifest is downloaded and parsed, but stream does not play.  Warnings and error from log:

warning <general>: AddOnLog: inputstream.adaptive: OnSegmentChanged: Cannot get the stream sample reader
error <general>: OpenStream: Codec id 27 require extradata.
warning <general>: OpenStream - Unsupported stream 1004. Stream disabled.

### To Reproduce

1. Try to play the stream
2.
3.

### Debuglog

The debuglog can be found here:

[ISA debug.log](https://github.com/xbmc/inputstream.adaptive/files/15284054/ISA.debug.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

[manifest_1715453777_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15284055/manifest_1715453777_master.txt)
[manifest_1715453777_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15284059/manifest_1715453777_child-video.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux x86 64-bit version 5.18.7 (332295)
 - Kodi version: 21.0 (21.0.0) Git:20240406-60c4500-dirty
 - inputstream.adaptive version: 21.4.7

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
the Omega parser assume that EXT-X-KEY is placed before the EXTINF tag
and your manifest have EXT-X-KEY after EXTINF
this seem to be the problem

from hls specs seem there are no rules about the right sequence of tags
i will try restore it

**Comment by MetalChris** [comment]
Ok, thanks for looking at it.  I thought perhaps I was missing a new property tag in Omega version, but I guess that wasn't the case.  Please let me know if you need any additional information or if you need me to test something.

**Comment by CastagnaIT** [comment]
i made the fix but would be better to have a confirmation
i cant provide you a linux test build, if you are able to build the binary by yourself the PR is #1556

otherwise you can test on other OS's by downloading builds from
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1556/1/artifacts

**Comment by MetalChris** [comment]
Happy to confirm this now works in Linux.  Thanks!
