### ISSUE TITLE
Stop playback again in the event of commercial breaks or X-discontinuity with the inputstream.adaptive addon

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1563]
### Describe the bug
Here is a clear and concise description of what the problem is:
Hi @CastagnaIT I noticed that the stream from DAZN Darts x PlutoTV simply stops in the event of commercial breaks and you end up back in the Kodi main menu again. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The stream should run through without stopping in the event of commercial breaks.

## Actual Behavior

The stream from DAZN Darts x PlutoTV simply stops in the event of commercial breaks and ends up back in the Kodi main menu.

### To Reproduce

1. Start Kodi
2. Play Stream: https://r.mjh.nz/PlutoTV/64b67f0424ade50008a3be17-alt.m3u8 with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debuglog

The debuglog can be found here:

[kodi_dazn_darts_debug.log](https://github.com/xbmc/inputstream.adaptive/files/15415715/kodi_dazn_darts_debug.log)
[manifest_1716460844_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15415717/manifest_1716460844_master.txt)
[manifest_1716460846_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415718/manifest_1716460846_child-video.txt)
[manifest_1716460848_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415719/manifest_1716460848_child-video.txt)
[manifest_1716460854_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415720/manifest_1716460854_child-video.txt)
[manifest_1716460859_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415721/manifest_1716460859_child-video.txt)
[manifest_1716460864_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415722/manifest_1716460864_child-video.txt)
[manifest_1716460869_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415723/manifest_1716460869_child-video.txt)
[manifest_1716460875_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415724/manifest_1716460875_child-video.txt)
[manifest_1716460880_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415725/manifest_1716460880_child-video.txt)
[manifest_1716460886_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415726/manifest_1716460886_child-video.txt)
[manifest_1716460891_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415727/manifest_1716460891_child-video.txt)
[manifest_1716460897_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415728/manifest_1716460897_child-video.txt)
[manifest_1716460903_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415729/manifest_1716460903_child-video.txt)
[manifest_1716460908_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415730/manifest_1716460908_child-video.txt)
[manifest_1716460915_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415731/manifest_1716460915_child-video.txt)
[manifest_1716460921_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415732/manifest_1716460921_child-video.txt)
[manifest_1716460926_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415733/manifest_1716460926_child-video.txt)
[manifest_1716460931_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415734/manifest_1716460931_child-video.txt)
[manifest_1716460936_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415735/manifest_1716460936_child-video.txt)
[manifest_1716460940_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415736/manifest_1716460940_child-video.txt)
[manifest_1716460945_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415737/manifest_1716460945_child-video.txt)
[manifest_1716460950_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415738/manifest_1716460950_child-video.txt)
[manifest_1716460955_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415739/manifest_1716460955_child-video.txt)
[manifest_1716460960_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415740/manifest_1716460960_child-video.txt)
[manifest_1716460966_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415741/manifest_1716460966_child-video.txt)
[manifest_1716460971_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415742/manifest_1716460971_child-video.txt)
[manifest_1716460976_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415743/manifest_1716460976_child-video.txt)
[manifest_1716460983_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415744/manifest_1716460983_child-video.txt)
[manifest_1716460989_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415745/manifest_1716460989_child-video.txt)
[manifest_1716460994_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415746/manifest_1716460994_child-video.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://r.mjh.nz/PlutoTV/64b67f0424ade50008a3be17-alt.m3u8

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 10 / Windows 10
 - Kodi version: 21.0
 - inputstream.adaptive version: inputstream.adaptive v21.4.8

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by werimail** [comment]
Hi @CastagnaIT  unfortunately the problem described above occurs again for me with the current ISA version 21.4.8. Can you understand this?

Greetings Weri

**Comment by CastagnaIT** [comment]
this should be fixed by PR #1562
builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1562/2/artifacts

**Comment by werimail** [comment]
> this should be fixed by PR #1562 builds: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1562/2/artifacts

Thanks @CastagnaIT so far the new version with this fix is working quite well for me.

Greetings Weri
