### ISSUE TITLE
Constant buffering when playing the stream

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1568]
### Describe the bug
Here is a clear and concise description of what the problem is:
In my test, playback of the stream only works a few seconds until the buffer needs to be reloaded. This repeats itself several times.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I can play the stream without constant buffering.

### To Reproduce

1. Start Kodi
2. Play Stream https://live.teleradiocom.tj/8/3m.m3u8 with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debuglog

The debuglog can be found here:
[kodi_stream.log](https://github.com/xbmc/inputstream.adaptive/files/15496729/kodi_stream.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[manifest_1717059560_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496621/manifest_1717059560_child-video.txt)
[manifest_1717059549_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496622/manifest_1717059549_child-video.txt)
[manifest_1717059539_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496623/manifest_1717059539_child-video.txt)
[manifest_1717059529_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496624/manifest_1717059529_child-video.txt)
[manifest_1717059518_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496625/manifest_1717059518_child-video.txt)
[manifest_1717059508_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496626/manifest_1717059508_child-video.txt)
[manifest_1717059498_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15496627/manifest_1717059498_child-video.txt)
[manifest_1717059498_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15496628/manifest_1717059498_master.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LineageOS 20 based on Android 13 for Raspberry Pi 400
 - Kodi version: 21
 - inputstream.adaptive version: 21.4.9

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i attach here the hls stream:
https://live.teleradiocom.tj/8/3m.m3u8

the problem happen also on Kodi 20,
at least on Windows i don't see buffering problems, instead there are freezing images as if missing frames,
the segments seem to be correctly fed to Kodi and also the updates looks correct, also using a higher live_delay segments seems ok,
it could be a TS demuxer problem but im not sure since i have no so in-depth knowledge of that demuxer
atm i have no idea what could be done

**Comment by werimail** [comment]
> ... on Windows i don't see buffering problems, instead there are freezing images as if missing frames, the segments seem to be correctly fed to Kodi..

Funny... the stream doesn't even start for me under Windows. I also created a debug.log.
[kodi.log](https://github.com/user-attachments/files/15509821/kodi.log)

EDIT: The stream can no longer be started via the browser, apparently the problem is currently on the provider side.

Greetings Weri

**Comment by CastagnaIT** [comment]
unfurnately the live stream is ended

**Comment by CastagnaIT** [comment]
IPTV Simple Client itself dont provide playlists
provide the m3u8 playlist with the problematic channel

**Comment by werimail** [comment]
> IPTV Simple Client itself dont provide playlists
> provide the m3u8 playlist with the problematic channel

Unfortunately I don't understand exactly what you mean by that? I added the stream link above. Greetings Weri

**Comment by CastagnaIT** [comment]
the https://live.teleradiocom.tj/8/3m.m3u8 live is ended
so or the website provide an updated link for a new live stream
or this issue can be closed since that stream is not available anymore

**Comment by werimail** [comment]
> the https://live.teleradiocom.tj/8/3m.m3u8 live is ended
> so or the website provide an updated link for a new live stream
> or this issue can be closed since that stream is not available anymore 

Ok @CastagnaIT I understood. However, it was obviously a temporary problem with the provider as the stream worked again. I was able to play it easily in the browser! 

Edit: Hi @CastagnaIT  after an adjustment by the stream provider, it is now played correctly again via Kodi. Therefore I am closing the issue.

Thanks and greetings Weri
