### ISSUE TITLE
[HLS] .ts download is wiping cookie resulting in 403 when downloading key

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#157]
I have a stream that sends back a Set-Cookie: ; path=/; when downloading the .ts files.
This then leads to failing to download the key as that requires the access cookie to be set.

Would it be possible to do the download in the below order?
master.m3u8 -> sub.m3u8 -> key -> ts files

My current solution is to do a head request on the master.m3u8 before sending to KODI.
Getting the cookies, and then passing them as header arguments to inpustream with:
li.setProperty('inputstream.adaptive.license_key', '|' + headers)

This is not ideal as it adds an extra request before playing the stream.

Here is a debug log (using latest KODI nightly 
https://pastebin.com/a8zEJwFc

Line 1039 is where the cookie is wiped after the .ts download.
Line 1168 shows no cookie being sent with the key request.

I can't see a "re-use connection" before calling the key url either.
Maybe that's the issue? It's using a new connection without the cookies etc.

**Comment by matthuisman** [comment]
I think there is something else to this.

At the start of every hour, the key file is changed.
Inpustream and ffmpeg in KODI 17 both 403 on the new key file.
But, KODI 18 ffmpeg works.

It has to be something to do with the cookies.
The video files are behind a subscription wall, so I will try make some test url you can use.

**Comment by matthuisman** [comment]
Closing as duplicate of https://github.com/peak3d/inputstream.adaptive/issues/184

**Comment by vaselinetv** [comment]
Any idea on how to add Cookies to the #KODIPROP ?
