### ISSUE TITLE
[Bug]  Subtitles not shown when using manifests with ads

### ISSUE THREAD

**Issue by Paco8** [peak3d/inputstream.adaptive#1572]
### Describe the problem

When streaming content from SkyShowtime on Kodi, a trailer for one of their TV shows sometimes plays before the main content. When this trailer appears, subtitles are not displayed for the content. The logs indicate that the WebVTT subtitle files are downloaded, but they do not appear on screen. If the content starts without the initial trailer, subtitles are displayed.

### Steps to reproduce

You can reproduce it with the latest version of the [plugin.video.skyott](https://github.com/Paco8/plugin.video.skyott) addon (notice that this addon only works on android devices) and a SkyShowtime account. 

In the addon settings turn on the option "commercial breaks". Turn off the options to modify the manifest and improved subtitles.

Play any content.

### Debug log

https://paste.kodi.tv/qucisahowi.kodi

### Stream manifest file(s)

[manifest.txt](https://github.com/user-attachments/files/15525447/manifest.txt)

### Operating system(s)

Android

### Operating system version(s)

Any android

### InputStream Adaptive version(s)

21.4.9

### Kodi version(s)

21.0

**Comment by CastagnaIT** [comment]
the first thing to check is to verify if you are affected by the Kodi core bug that disable subtitles after a period/chapter change (like ads, etc...)

to do it: after that an ads/trailer is ended and the main video content start to be played (after period/chapter change),
try check on the kodi GUI settings if the subtitles has been disabled
i mean here:
![immagine](https://github.com/xbmc/inputstream.adaptive/assets/3257156/190ef80a-3b18-4940-9909-e6ea4a7354d4)

**Comment by Paco8** [comment]
I'm afraid that's not the problem. The subtitles are enabled but they're not shown.

**Comment by CastagnaIT** [comment]
ok then excluded
i also see that there is a pts "rewind" of 15secs after the period switching
that are duration of first period

```
2024-06-02 00:43:00.023 T:6568    debug <general>: CurlFile::Open - <https://g002-vod-eu-cmaf-prd-cf.pcdn01.cssott.com/pub/global/Tji/kZx/GMO_00000000132512_02/SST_1709187348885_198c_01/mpeg_cenc/r0/video/sdr/avc/7830k_1080_cmaf/seg_0.mp4>
2024-06-02 00:43:00.391 T:6569    debug <general>: CurlFile::Open - <https://g002-vod-eu-cmaf-prd-cf.pcdn01.cssott.com/pub/global/Tji/kZx/GMO_00000000132512_02/SST_1709187348885_198c_01/mpeg_cenc/r0/audio/stereo-eac3/en-GB/seg-5_0.mp4>
2024-06-02 00:43:01.190 T:5691    debug <general>: CVideoPlayer::CheckContinuity - resync backward :2, prev:14960000.000000, curr:0.000000, diff:-14960000.000000
2024-06-02 00:43:01.191 T:5691    debug <general>: CVideoPlayer::CheckContinuity - update correction: -15000000.000000
2024-06-02 00:43:01.192 T:5691    debug <general>: CVideoPlayer::CheckContinuity - wrapback :1, prev:15008000.000000, curr:15000000.000000, diff:-8000.000000
```

it could be caused due to segment package pts, and i think this could cause a shift in the subtitles timestamps, since CheckContinuity is cause of a pts offset correction

ISA already have several unsolved problems regarding PTS comparison on packages and demuxers pts offsets,
this could be a similar case related to that
from my side i wouldn't even know what to do atm there are several things to look into

**Comment by Paco8** [comment]
Testing with a TV show, I noticed that if I seek to minute 7, the subtitles appear. If I go back to minute 6, they disappear. If I play from minute 6 to 7, the subtitles don't appear on their own; I have to seek forward at least 10 seconds for them to appear.
Maybe this could provide a clue about the problem?

https://paste.kodi.tv/idegujidom.kodi
[manifest2.txt](https://github.com/user-attachments/files/15586858/manifest2.txt)

**Comment by Paco8** [comment]
I tested with other TV shows and movies and I think the problem is that kodi skips the content of the first webvtt file.

**Comment by Paco8** [comment]
It seems that removing `presentationTimeOffset="0"` from the subtitle entries in the manifests fixes the problem.

**Comment by CastagnaIT** [comment]
> It seems ...

you have to be sure without assumptions, please do better tests with same video stream
by comparing the regular ISA release, with following test build (that remove the only code used with `presentationTimeOffset`)

test builds https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1575/1/artifacts
pr #1575

so you can confirm or not the difference

**Comment by Paco8** [comment]
It's difficult to test this problem because once I watched an ad, they won't show another one for hours.
So it takes me a lot of time just to test a few videos.

I'm pretty sure the problem is that the content of the fragment #0 is not displayed. For example,
in one movie there were no subtitles for the first hour. I downloaded the [fragment #0](https://g002-vod-eu-cmaf-prd-cf.pcdn01.cssott.com/pub/global/kU9/dzX/GMO_00000000203175_02/SST_1708829692171_bc48_01/mpeg_cenc/r0/text/subs/es-ES/_116722596.subtitles.7.split.0.webvtt) and the timestamps are from 00:00:40 to 00:59:47.832. The first subtitle
in [fragment #1](https://g002-vod-eu-cmaf-prd-cf.pcdn01.cssott.com/pub/global/kU9/dzX/GMO_00000000203175_02/SST_1708829692171_bc48_01/mpeg_cenc/r0/text/subs/es-ES/_116722596.subtitles.7.split.1.webvtt) is at 01:00:53 which is exactly the first subtitle displayed by kodi.

My tests:
- **Original inputstream adaptive 21.4.9 with the original manifest**: the contents of the first fragment are not displayed.
- **Original inputstream adaptive 21.4.9 with a modified manifest (where the proxy deletes all references to "presentationTimeOffset=0")**: Subtitles are displayed correctly from the beginning of the video.
- **Your modified version of inputstream adaptive with the original manifest**: the contents of the first fragment are not displayed.
- **Your modified version of inputstream adaptive with a modified manifest (presentationTimeOffset="0" deleted)**: The first fragment is still not displayed.

**Comment by CastagnaIT** [comment]
try test with this new one
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1575/2/artifacts
but without deletes all references to "presentationTimeOffset, so original manifest

**Comment by Paco8** [comment]
Yes, this build works. Now the subtitles are displayed correctly in all videos I have tested so far. With the original manifests.

**Comment by CastagnaIT** [comment]
good to know so i understand,
its a side effect of the workaround that i reintroduced time ago with PR #1522 due to a more complex problem

fwik, in theory, the workaround could be limited to HLS since TS segments packages should be the only (i hope) to have PTS values that dont match the manifest segments PTS
yeah unfortunately it's all a bit speculative as i don't have enough info and there are many variables

i could make an attempt to try limit it to HLS,
since for now i have no plan to fix the root of the problem in a short time
