### ISSUE TITLE
Disney+ audio out of sync with video

### ISSUE THREAD

**Issue by Vitocorl** [peak3d/inputstream.adaptive#1579]
### Describe the problem

I seem to have an audio problem with Disney+, whenever i am trying to watch, audio is out of sync with video, usually comes too quick ahead of video.
The problem is Dolby Digital Plus (EC-3) on SlyGuy Common Playback settings. Disabling this i have no Audio sync problems, but it only outputs 2-channel audio, instead of 5.1.
he audio sync problem did not occur a month ago, with the exact same setup, so i guess this was caused by some upgrade somewhere.

### Steps to reproduce

1. Open Kodi Disney+ addon
2. Try to play a series, e.g. i played "Shogun:
3. Audio comes a lot quicker than video, i have to add delay and experiment to lip-sync

### Debug log

https://paste.kodi.tv/utiyowelun.kodi

### Additional info

Debug log has also logged the audio component. Setup consists of a Xiaomi MiBox S 2nd Gen, HDMI to TV (LG OLED G3), TV optical output to amplifier. I do not have any problem with movies or TV shows when played from network or hard drive, the only problem is with the Disney+ add-on

### Operating system(s)

Android

### Operating system version(s)

11

### InputStream Adaptive version(s)

21.4.9-Omega

### Kodi version(s)

21.0 (21.0.1) Git:20240603-eb4ce30216

**Comment by matthuisman** [comment]
maybe related to https://github.com/xbmc/inputstream.adaptive/issues/757

**Comment by matthuisman** [comment]
but, if its a regression and only started a within the last month, you may want to try older versions of inputstream.adaptive to see if the issue goes away

Here are some older versions:
21.4.8 - https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/Omega/189/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-21.4.8.zip
21.4.7 - 
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/21.4.7-Omega/1/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-21.4.7.zip

Please try and report if they have same issue

**Comment by Vitocorl** [comment]
Ok, i will try the older versions and report back

**Comment by Vitocorl** [comment]
So, i did test the previous versions:
21.4.7: more or less, the same audio problem as with 21.4.9, but, after 2-3 minutes Kodi is crashing to desktop.

21.4.8: the audio problem is less visible,  i think it is less than a second, but Kodi also crashes to desktop.

21.4.9: Audio problem is visible, about 3 or 4 seconds ahead of video, Kodi does not crash at all. If during watching a video, i change the audio track from 5.1 to 2ch, audio is fixed, if i change back, audio is again at fault...

**Comment by CastagnaIT** [comment]
imo it is unlikely that this problem originates from ISA
changes on last versions there is nothing that could affect audio delays

If you really have to test old versions i would suggest v21.4.4, v21.4.5 of a couple of months ago

but did you have automatic addon updates disabled? if so, what was your addon previous version?
if instead you had automatic ISA add-on updates enabled, you were already using the latest ISA versions, and more likely if you test old versions you wont see differences

**Comment by matthuisman** [comment]
it could even be a Nexus vs Omega. Omega on Android was about 1.5 months ago
The ISA version on Nexus is quite different

**Comment by CastagnaIT** [comment]
some months ago i used D+ (with a my account) on Shield android tv with Kodi 21 nightly
i have a 7.1 amplifier and i can confirm (at least at that time) that dolby was working correctly
so at least i can exclude "Nexus vs Omega"

**Comment by CastagnaIT** [comment]
i can restore my old D+ account from the end of next week so i can play some tvshow

**Comment by matthuisman** [comment]
It may be a Mi box issue. I recall quite some time that using secure
decoder for audio caused issues on some hardware

**Comment by Vitocorl** [comment]
> imo it is unlikely that this problem originates from ISA changes on last versions there is nothing that could affect audio delays
> 
> If you really have to test old versions i would suggest v21.4.4, v21.4.5 of a couple of months ago
> 
> but did you have automatic addon updates disabled? if so, what was your addon previous version? if instead you had automatic ISA add-on updates enabled, you were already using the latest ISA versions, and more likely if you test old versions you wont see differences

Ι uninstalled version 21.4.9,  and disabled updates after installing the older versions, 21.4.7 & 21.4.8 which both caused Kodi to crash to desktop. Can you provide a link to download older versions like v21.4.4, v21.4.5 you mention, i cannot find them.

@matthuisman I have just seen your comment on the forums about disabling the secure decoder, i will also try that and report back.

**Comment by Vitocorl** [comment]
Disabling the secure decoder, i have no video at all, i can only hear audio and the screen is black, enabling it again the video comes back...

**Comment by Vitocorl** [comment]
Update, i have downloaded and tried all Omega versions, from v21.4.1 to v21.4.9, all having the same results more or less, most versions also cause Kodi to crash. Also, i tried disabling Dolby Vision and HDR, enabling and disabling every option that has to do with video and audio, with no result. I do not know what else to try, if you have any ideas, or if you can make anything out of the debug log, please let me know...

**Comment by CastagnaIT** [comment]
i have tested D+
with android Shield and audio DD5.1 / H264 and h265 (not tested DV or HDR since i dont have the hardware)
my cable configuration is Shield HDMI -> ampifier HDMI -> TV
tried also change language
tested Shogun and some other tvshows
but i have not found audio out of sync problem
looks like a problem related to your MIBox device

**Comment by CastagnaIT** [comment]
>  I do not have any problem with movies or TV shows when played from network or hard drive, the only problem is with the Disney+ add-on

however to be able to make a kind of comparation you should play another DRM content with DD5.1
not by using network or HDD storage, since DRM contents its different

**Comment by Vitocorl** [comment]
I only have a Netflix subscription i could test with this, but i think the plugin for Kodi does not work, unless there has been a fix for this i do not know. I do not have any other subscription with DRM content unfortunately.

**Comment by CastagnaIT** [comment]
on my android device ntfx addon still works, just disable ESN generation (540p workaround) from expert settings
it may not works on all devices models but you can try

**Comment by Vitocorl** [comment]
Ok, i will try that and report back, thank you.

**Comment by Vitocorl** [comment]
So, it seems i was chasing a ghost with the audio delay problem. I found an audio setting on my TV (LG G3 Oled), enabling an audio delay on the optical output.
I have set this to 2 and everything works perfect! Disney+ audio is fixed, the peculiar thing is that movies or shows playing from the network are not affected at all, i was expecting that this would fix Disney delay but ruin all other audio, files playing without the intervention of ISA, but no, everything is fine. 
Moreover, Netflix Android app and Disney+ Android app are not affected at all, they also play with perfectly synchronized audio.  I cannot come to a conclusion as to how this setting is only affecting the specific audio sync problem, but i am happy it is solved now and i am sorry for taking your time and troubling you with what seems to completely irrelevant with ISA or Disney+ Kodi plugin.
Please mark this as solved for reference in case someone else faces this or similar problem...

**Comment by CastagnaIT** [comment]
glad you solved and thanks for the feedback
