### ISSUE TITLE
[HLS] Redirected master.m3u8 causes playback failure

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#158]
I have an IPTV service that gives me constant URLS that then redirect to the actual media urls.

eg. iptv.matthuisman.nz/tvnz-1.m3u8 -> tvnz.co.nz/master.m3u8

When trying to playback the first URL, inpustream will follow the redirect, open the master.m3u8 file and get the substreams.

However, when it goes to get the substreams, it uses the first URL as the base - not the 2nd url.
iptv.matthuisman.nz/tvnz-1-1500.m3u8 instead of tvnz.co.nz/master-1500.m3u8

Here is a debug log showing it happening.
https://pastebin.com/TCFsDbLG

Line 960 is where it get's the redirect location
Line 1104 has found the actual effective url
Line 1124 tries to get the master_5.m3u8 from the first url and not effective url

My current work-around is to do a head request to find out the destination URL ('location' header), and pass this to KODI. This is not ideal as it will fail for non-redirected streams and takes an extra request.

**Comment by matthuisman** [comment]
Here is a URL you can test with:
http://iptv.matthuisman.nz/nz/tv.redbull.tv/m.m3u8

That redirects to the Redbull TV master playlist.

**Comment by peak3d** [comment]
@matthuisman https://github.com/peak3d/inputstream.adaptive/commit/71260edf14aa81fe1bcf266b94f388fe1231aad6
