### ISSUE TITLE
[Bug] Disney+ Addon not playing properly the stream when VAAPI is enabled

### ISSUE THREAD

**Issue by adam-aph** [peak3d/inputstream.adaptive#1588]
### Describe the problem

This was tested with Omega, when playing the content as Disney stream this is happening:

- with VAAPI enabled, it doesn't refresh video and Kodi logs shows errors: `ffmpeg[0x1c3b8a30]: [hevc] hardware accelerator failed to decode picture`
- with VAAPI disabled everything works fine
- if that Disney stream will be downloaded as local mp4 file then Kodi plays it fine, for both configurations when VAAPI is enabled and disabled

Full log file is [here](https://x0.at/IkO2.txt).
[IkO2.txt](https://github.com/user-attachments/files/16145884/IkO2.txt)

Screenshot from played stream:
![nuc10-stream](https://github.com/xbmc/inputstream.adaptive/assets/1830625/5b335892-45ad-4391-9b98-4a725fc6f8c1)

Screenshot from played file:
![nuc10-file](https://github.com/xbmc/inputstream.adaptive/assets/1830625/0e400457-91c3-47c8-86e1-fb73b610539e)

<details>
<summary>Stream details (click it)</summary>

```
General
Complete name                            : Machine Gun Kelly’s Life in Pink.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/dby1/iso2/mp41)
File size                                : 2.29 GiB
Duration                                 : 1 h 41 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 219 kb/s
Frame rate                               : 23.976 FPS
Movie name                               : Machine Gun Kelly’s Life in Pink
Description                              : 'Machine Gun Kelly’s Life in Pink'
Recorded date                            : 2022
Writing application                      : Lavf60.3.100
Cover                                    : Yes

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L3.1@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 1 h 41 min
Bit rate                                 : 2 958 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.134
Stream size                              : 2.10 GiB (92%)
Title                                    : BAMTech video
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : hvcC

Audio
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : ec-3
Duration                                 : 1 h 41 min
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 186 MiB (8%)
Title                                    : BAMTech audio / English
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Dialog Normalization                     : -29 dB
compr                                    : -0.28 dB
mixlevel                                 : 105 dB
roomtyp                                  : Small
dialnorm_Average                         : -29 dB
dialnorm_Minimum                         : -29 dB
dialnorm_Maximum                         : -29 dB
```
</details>

### Possible fix

The workaround is to disable VAAPI support in Kodi Player.

### Steps to reproduce

See the problem description.

### Debug log

https://x0.at/IkO2.txt

### Stream manifest file(s)

See the stream details from problem description.

### Operating system(s)

Linux

### Operating system version(s)

LibreELEC Linux x86 64-bit version 6.9.5

### InputStream Adaptive version(s)

inputstream.adaptive v21.4.9.1

### Kodi version(s)

Kodi (21.0 (21.0.0) Git:21.0-Omega

**Comment by dljones8053** [comment]
I'm running kodi on Windows with inputstreamadaptive version 21.4.10 update yesterday not only Disney+ crashes Kodi so does Paramount+ and Prime Video have the same issue as well. I enjoy having all my streaming video's in one location, 
Just saying as I cannot find the previous version to do a roll back as this is something I wished Kodi offer.

**Comment by CastagnaIT** [comment]
VAAPI its hardware acceleration and i could be wrong but fwik you cant use it with DRM contents
since your platform support only DRM software decoding
this is on kodi core ISA has no control over it
maybe open an issue on kodi repo to see if someone is able to help you

**Comment by adam-aph** [comment]
Well, all that Disney+ content is DRM protected and most of streaming content plays fine with VAAPI enabled, but that particular stream doesn't. This would imply that there is something specific with that stream that either ISA cannot handle it properly or there is some bug on Kodi level. 
The chain of commands is: [Disney+ Addon] -> [ISA + Widevine] -> [Kodi Player + VAAPI]
As explained in the initial description, when I decode and download that stream contents to mp4 file, Kodi can play it without issues with VAAPI enabled.

Is there any specific ISA debug option to get some more detailed logs for this?

**Comment by adam-aph** [comment]
Anyways, opened also [Kodi issue](https://github.com/xbmc/xbmc/issues/25383) for this.

**Comment by CastagnaIT** [comment]
> Is there any specific ISA debug option to get some more detailed logs for this?

no but you can enable some kodi debugging components settings
anyway i have no idea on how works VAAPI on kodi
it need someone that know it

**Comment by CastagnaIT** [comment]
closed as no way to investigate from our part
i tried to write to the CoreElec devs if there is an answer, it will be on xbmc Issue
