### ISSUE TITLE
[Bug][Windows] ISA v21.4.10 crashes Kodi

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1589]
### Describe the problem

After starting playback using ISA, Kodi (installed on Windows 10) crashes. I tested it on many addons with the same result. 
ISA v. 21.4.9 works without problems.

### Steps to reproduce

1. starting playback
2. kodi crashes

### Debug log

[log.txt](https://github.com/user-attachments/files/15988875/log.txt)

### Operating system(s)

Windows

### Operating system version(s)

Windows 10

### InputStream Adaptive version(s)

21.4.10

### Kodi version(s)

21.0

**Comment by CrAcK75** [comment]
Even in Windows 11 and not on all machines, on some machines it doesn't happen

**Comment by mtr81** [comment]
Unfortunately, it's not first time when a new version is released without thorough testing. IMO it's time to change the style of working on this plugin, because many add-ons are based on it.

**Comment by CastagnaIT** [comment]
The complexity of this addon is quite high, and lack of official DRM docs, high amount of features of streaming protocols (like dash), lack of developers, it is impossible for 2 developers (of which only I am currently active) to follow and test every single use case, not only a single use case per streaming protocol type, but also on different operative systems/architectures.

Furthermore video services are often geolocked and/or at payment, what should we do? the only way is to wait for someone that can test, if you know other ways you are free to propose and/or provide some solutions

Fixing one thing, and breaking another: this is the fruit of a project that was designed badly at its birth
What solutions? Rewrite all the code from scratch, or improve small pieces at a time,
we can't do miracles with our less time and the work required behind this is huge

any dev can help as an external collaborator or also join the team to follow the project
if there are people who skilled or have better ideas to develop the project they are welcome
but in recent years i don't see anyone else who has offered to help, but only complain

**Comment by CrAcK75** [comment]
I agree with @CastagnaIT, I understand it perfectly. It is probably the Kodi team that should take charge of this addon which is the heart of all existing streaming, or at least use the resources to support it. In short, there are no alternatives to this addon and if it stops working I think that at least 70% of users will not be able to use Kodi.
I would add that unfortunately I am a C# developer with some knowledge of Python (with which I develop my addon a bit) but if I could I would gladly give my contribution. Unfortunately C++ is not my world.

ITA:
Sono d'accordo con @CastagnaIT, lo capisco perfettamente. Probabilmente è il team di Kodi che dovrebbe farsi carico di questo addon che è il cuore di tutto lo streaming esistente, o almeno utilizzare le risorse per supportarlo. Insomma non ci sono alternative a questo addon e se smettesse di funzionare penso che almeno il 70% degli utenti non potrebbe più usare Kodi.
Aggiungo che purtroppo sono uno sviluppatore C# con poca conoscenza di Python (con cui sviluppo un po' il mio addon) ma se potessi darei volentieri il mio contributo. Sfortunatamente C++ non è il mio mondo.

**Comment by mtr81** [comment]
I suppose the problem lies in PR #1576 . There's no ISA build for Windows x86 64-bit ->https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/195/pipeline

> The complexity of this addon is quite high, and lack of official DRM docs, high amount of features of streaming protocols (like dash), lack of developers, it is impossible for 2 developers (of which only I am currently active) to follow and test every single use case, not only a single use case per streaming protocol type, but also on different operative systems/architectures.
> 
> Furthermore video services are often geolocked and/or at payment, what should we do? the only way is to wait for someone that can test, if you know other ways you are free to propose and/or provide some solutions
> 
> Fixing one thing, and breaking another: this is the fruit of a project that was designed badly at its birth What solutions? Rewrite all the code from scratch, or improve small pieces at a time, we can't do miracles with our less time and the work required behind this is huge
> 
> any dev can help as an external collaborator or also join the team to follow the project if there are people who skilled or have better ideas to develop the project they are welcome but in recent years i don't see anyone else who has offered to help, but only complain

I understand and appreciate your efforts.


> It is probably the Kodi team that should take charge of this addon which is the heart of all existing streaming, or at least use the resources to support it

I totally agree.

**Comment by redtrash007** [comment]
Happened to me too, few days ago, tested on W10 and W11, same issue.
Works fine on Android.

Actually a friend of mine said that Kodi stopped working on his computer with W11, after some checks and without resolution, I've tried to install Kodi on my machine with W10, after the first run everything was fine, so I though the issue was W11, but after 1 hour I've restarted Kodi and meanwhile something got an update and the streaming stopped working, making Kodi to crash.
My installation was a first time instalaltion, so clean installation of Kodi.
**Maybe the temporary solution can be to uninstall Kodi, delete all the remaining files, reinstall kodi, disable the automatic update of the guilty plugin and use as it is?**

**Comment by CrAcK75** [comment]
For the moment the solution is to reinstall the previous version of IA, namely 21.4.9

**Comment by redtrash007** [comment]
I did and it works!
I have no idea how do it properly, I just replaced the files from: C:\Users\USERNAME\AppData\Roaming\Kodi\addons\inputstream.adaptive

**Comment by emveepee** [comment]
The Kodi current Windows nightlies are at MSVC 194033811 which map to the compile runtime used for this maybe jenkins needs to use the older MSVC 193431937

**Comment by jeff2900** [comment]
Same issue solved with latest version 14.40.33810.0 of Microsoft Visual C++ Redistributable
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by CastagnaIT** [comment]
seem that old VC runtime library cause problems

as said by @jeff2900 above, please ensure that you have installed last VC runtime:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

also i suggest to update/install last kodi 21 nightly, that can be downloaded from:
http://mirrors.kodi.tv/nightlies/windows/win64/Omega/
waiting for the next new release of kodi 21
