### ISSUE TITLE
Stream cannot be played in Kodi 21 Omega [Bug] 

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1592]
### Describe the problem

The live stream cannot be played within Kodi 21 via the ISA addon. An error message appears.

### Steps to reproduce

1. Start Kodi
2. Play Stream http://88.212.7.10/live/test_ctsport_25p/playlist.m3u8 with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debug log

[kodi.log](https://github.com/user-attachments/files/16027195/kodi.log)

### Operating system(s)

Windows

### Operating system version(s)

Windows 11

### InputStream Adaptive version(s)

21.4.10

### Kodi version(s)

Kodi 21

**Comment by mtr81** [comment]
Works, but server verifies 'User-Agent' header, so:
```
#EXTINF:0, Stream test
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.stream_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
#KODIPROP:inputstream.adaptive.manifest_headers=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
http://88.212.7.10/live/test_ctsport_25p/playlist.m3u8|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
```

**Comment by CastagnaIT** [comment]
do not use pipe along the manifest url its not supported by isa
instead add
#KODIPROP:mimetype=application/dash+xml
or for HLS
#KODIPROP:mimetype=application/vnd.apple.mpegurl
to avoid the kodi core HEAD request

**Comment by mtr81** [comment]
I know that, but the log shows that ISA called by IPTV Simple Klient opens the base Stream URL (without string after '|').

**Comment by CastagnaIT** [comment]
@werimail you need to open an issue to IPTV Simple Client addon
and ask maintainer to add required headers to ISA properties:
inputstream.adaptive.manifest_headers
inputstream.adaptive.stream_headers

such as the example above
and maybe could be also an idea to have a PVR setting that allow to set or enable/disable user agents

**Comment by werimail** [comment]
Thanks @cast I opened an issue here https://github.com/kodi-pvr/pvr.iptvsimple/issues/871#issue-2383276845

Greetings Weri

**Comment by werimail** [comment]
Hi @CastagnaIT  I received the following answer from the maintainer of the IPTV Simple Client Addon: 

> There is a setting for iptvsimple to set a user agent for all streams.
The props you are setting are ISA specific so no built in support for those in  iptvsimple.

Apparently there is already an option in the addon? 
What else can I do? 

Greetings Weri

**Comment by CastagnaIT** [comment]
i answered on PVR issue,
unfurnately if the PVR dont set these properties nothing can be done
we specifically provide these properties "explicitly" and not as general setting, as it use case can differ for each provider
