### ISSUE TITLE
Max resolution is always 1080p even though 2160p stream is available

### ISSUE THREAD

**Issue by amtuannguyen** [peak3d/inputstream.adaptive#16]
LibreELEC with kodi YouTube addon on a 100Mbps download network, the max resolution is maxed out at 1080p

inputstream.adaptive is configured with default values 

min bandwidth: 0
max bandwidth: 0
stream selection: auto

**Comment by peak3d** [comment]
Can you provide the manifest file for this stream?
The URL can be found in the kodi log file, in general you can download the URL after that.

A complete log file would be help as well.

**Comment by amtuannguyen** [comment]
Hi peak3d, been busy so I haven't been able to get back on testing this stuff. 
Here is the log when I play the YouTube video with stream selection auto: http://sprunge.us/DUfT
And here is when stream selection is manual: http://sprunge.us/aMGQ

Note that when I choose manual, the 4k stream is selected automatically :).

Thanks for your awesome work.

**Comment by peak3d** [comment]
log files outdated

**Comment by maniacgit** [comment]
Here you can find a manifest with 4k [Manifest](https://manifest.googlevideo.com/api/manifest/dash/sparams/as%2Cei%2Chfr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/mv/m/playback_host/r11---sn-4g57knld.googlevideo.com/ms/au/key/yt6/signature/65B44A31A3672CE893DFECA3D441B61EC319D82D.081F7F5CA3B8916555DA9AE04CF213B7641D2C9F/requiressl/yes/mt/1501094405/ip/80.144.22.66/initcwndbps/1027500/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear/expire/1501116142/source/youtube/itag/0/ei/juJ4WbmbG5LSWJOSgIgL/mn/sn-4g57knld/hfr/1/mm/31/ipbits/0/pl/16/id/8ea3b1df60aff972)

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
