### ISSUE TITLE
Missing audio track if "Stream Selection: Auto" is chosen

### ISSUE THREAD

**Issue by dapharsyde** [peak3d/inputstream.adaptive#160]
With MLB.tv streams, there are 4 audio tracks - English from TV, English from radio, Spanish, and No Linguistic Content.

If I set Stream Selection to "Manual", all 4 audio tracks are available to choose from.  Unfortunately the video defaults to the lowest resolution available, and I always have to manually select the 720p stream I want.

On the other hand, if I set Stream Selection to "Auto", the video resolution is what I want, but the English from TV audio track is no longer available.  The other 3 tracks are available - English from radio, Spanish, and No Linguistic Content.

I assume that "Auto" stream selection is automatically selecting only one audio track for each language.  Is there any way to override this behavior, so I can still choose the English audio track I prefer?

**Comment by gsjv2** [comment]
I have the same issue.  However, I compiled the latest version and now I have no audio streams and hdmi crashes after the video ends.

**Comment by peak3d** [comment]
Audio streams, get merged in Auto mode if they don't differ in attributes we can pass kodi.
How is the difference displayed in kodi audio selection (english for TV / english for Radio) ?

**Comment by peak3d** [comment]
@gsjv2 what should I do with your post?

**Comment by dapharsyde** [comment]
Hi peak3d - thanks for your response.  You are right, it looks like both english audio streams look the same in the audio selection screen - they are both listed as "English - AAC - 0 channels".  Older versions of the mlb.tv plugin before June 2018 did not use inputstream.adaptive, and those streams showed audio as "English from Radio" or "English from TV".

Just curious, what is the advantage of eliminating the "duplicate" audio stream?  I would prefer the flexibility of choosing the alternate audio stream, especially in cases like this when it really is a different stream.

**Comment by peak3d** [comment]
Sure, that is where we all want to go to, but we should find a proper solution and this is identifying the differences and displaying them in kodi selection menu.

Can you provide the stream URL for this sample?

**Comment by dapharsyde** [comment]
These streams are available through the mlb.tv plugin.  Here is a URL to a game that is "free", but still requires one to create a mlb.com login.

https://www.mlb.com/tv/g530515/v4d76537d-123b-4590-b3b4-4a04845eb9ed

Let me know if you are able to access it.

**Comment by peak3d** [comment]
Can you pls. pull one master playlist (wget / curl / chrome browser) file and attach it here?

**Comment by gsjv2** [comment]
@peak3d i see it adds no benefit, however, I have no audio streams with mlb.tv or netflix

**Comment by peak3d** [comment]
@gsjv2 sry, don't understand your question. What adds no benefit?

**Comment by dapharsyde** [comment]
Sorry, I'm not sure how to fetch the master playlist.  I created a dummy mlb.com login for you, if you are able to try out the link above.

Username: dabjsa+cgfvqjs4l3qh8@sharklasers.com
Password: Peak3d123

If not, please help provide guidance on how to extract the master playlist and I will be happy to help!

**Comment by peak3d** [comment]
@dapharsyde thx for login, got what I needed, will add a solution for this.
Should I cancel the submission? Or doesn't it matter (I changed the pw)

**Comment by dapharsyde** [comment]
No need to do anything with the login.  It's a free account with a throwaway email.

**Comment by peak3d** [comment]
@dapharsyde pls. try the current nightly, I committed a change yesterday for this issue.

**Comment by dapharsyde** [comment]
fixed - I can now choose between both english audio streams - thank you for your efforts!
