### ISSUE TITLE
Kodi 22 Piers?

### ISSUE THREAD

**Issue by Ronny-nerd** [peak3d/inputstream.adaptive#1608]
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/activity

Hello CastagnaIT...are there any new inputstream.adaptive-22.0.0.zip for android-armv7 and android-aarch64 versions after the PRs for Kodi 22 Piers?

**Comment by CastagnaIT** [comment]
no CI jenkins is broken, kodi team will fix it i think in a week

**Comment by Ronny-nerd** [comment]
OK...thanks for the info.
