### ISSUE TITLE
[K21] Playing DASH (.mpd) Stream stops after some seconds

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1614]
### Describe the problem

Here is a clear and concise description of what the problem is:
I played the stream http://daserstedash.akamaized.net/dash/live/2103597/daserste/dvbt2/manifest.mpd during my test. Playback only worked for a few seconds and then stopped.

Playing on Kodi 21 with ISA 21.4.10 works fine.

### Debug log

[kodi.log](https://github.com/user-attachments/files/16439189/kodi.log)

### Stream manifest file(s)

[manifest_1722417400.txt](https://github.com/user-attachments/files/16439193/manifest_1722417400.txt)
[manifest_1722417394.txt](https://github.com/user-attachments/files/16439194/manifest_1722417394.txt)
[manifest_1722417382.txt](https://github.com/user-attachments/files/16439195/manifest_1722417382.txt)

### Operating system(s)

Windows

### Operating system version(s)

Windows 11

### InputStream Adaptive version(s)

ISA 21.5.0

### Kodi version(s)

Kodi 21

**Comment by walterheisenberg** [comment]
Same problem under AndroidTV, Kodi21
with free German streams from here:
https://github.com/jnk22/kodinerds-iptv/tree/master/iptv/dash

The previous versio2.4.10 worked.

**Comment by matthuisman** [comment]
Looks like 21.5.0 may have also broke Disney+ (HLS Widevine)
https://github.com/matthuisman/slyguy.addons/issues/827
"Since two Days i have the Issue i can't configure something in the addon and the Videos load very long and are stucking and without sound"

**Comment by CastagnaIT** [comment]
the dash problem above should be affected by #1586 but that pr change only dash case

@matthuisman have you possibility to send me again D+ login to test? my account is expired

**Comment by matthuisman** [comment]
@CastagnaIT unfortunately that was the one i was using too so i also dont have one.
I'll ask around to see if anyone can provide

**Comment by matthuisman** [comment]
having other reports of 21.5.0 causing HLS issues
"i note Channel 9 changed things up a bit recently. For me it plays for about 10 seconds then it freezes and the audio goes nuts"
reverting to previous version fixed

Channel 9 is a free to air Australia channel
HLS (no widevine)
@CastagnaIT do you have way to VPN to australia to test?

**Comment by CastagnaIT** [comment]
> having other reports of 21.5.0 causing HLS issues "i note Channel 9 changed things up a bit recently. For me it plays for about 10 seconds then it freezes and the audio goes nuts" reverting to previous version fixed
> 
> Channel 9 is a free to air Australia channel HLS (no widevine) @CastagnaIT do you have way to VPN to australia to test?

yes hoping works
where i can find channel 9?

**Comment by matthuisman** [comment]
wait. getting conflicting information. He said he went to 21.5.0 and now its fine.
Trying to find out what was the version that wasnt working.

Its in my "IPTV AU" plugin. "Channel 9"

**Comment by matthuisman** [comment]
FYI for anyone looking for 21.4.10 to test with:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Omega/208/artifacts

**Comment by matthuisman** [comment]
@CastagnaIT  ok sorry.
My user was on v21.4.9 and then went to 21.5.0 and fixed for them.
So Channel 9 streams are actually ok.
I suspect the fix for those was actually in 21.4.10

**Comment by jordandalley** [comment]
Apologies. That was my bad - I fat fingered the non-working version number to @matthuisman
