### ISSUE TITLE
Recent versions seem to have reduced buffer time

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1619]
### Describe the problem

not sure what version it started on, but i've noticed live streaming is just a lot more unreliable on newer versions of Inputstream Adaptive.

It seems to always hit the end of the timeline and run out of buffer.

Has there been some change to how much time / segments it calculates lately?
Testing with 21.5.0 and 21.4.10, 21.4.9 and both have same issue
This is using a single forced quality (no adaptive)
And also selecting a low quality that my internet should easily handle

Example manifest
`<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:mspr="urn:microsoft:playready" xmlns:scte35="urn:scte:scte35:2013:xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" availabilityStartTime="2023-05-11T21:40:32.455000+00:00" id="201" minBufferTime="PT12S" minimumUpdatePeriod="PT12S" profiles="urn:mpeg:dash:profile:isoff-live:2011" publishTime="2024-08-02T08:42:45+00:00" suggestedPresentationDelay="PT19.000S" timeShiftBufferDepth="PT298.000S" type="dynamic" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd">`

Notice same with HLS as well to the point where I turn off IA and use kodi ffmpeg

### Possible fix

increase buffered segment count?

### Debug log

tba

### Operating system(s)

Windows

### InputStream Adaptive version(s)

21

### Kodi version(s)

21

**Comment by matthuisman** [comment]
testing with slyguy proxy off

Kodi 20 + IA 20.3.18 plays at best quality 1280x720 without any issues

Kodi 21 + IA 21.5.0 - stops playback after about 10seconds (it shows a chapter dash on timeline in same spot every time)
             + IA 21.4.10 / 4.9 - timeline correct but hits the end lots and buffers at even lower qualities

**Comment by matthuisman** [comment]
i suspect the crash in 21.5.0 would be fixed with https://github.com/xbmc/inputstream.adaptive/pull/1616
UPDATE: confirmed above does fix crashing

However, it still has the issue of "flying too close to the sun"
It probably runs about 10s closer to the end and hits it constantly

The buffer segment settings are no longer available in 21 so cant try changing them

**Comment by matthuisman** [comment]
oh i see, there is a live_delay property now

**Comment by CastagnaIT** [comment]
it is not possible to make a comparison with kodi 20 because the old source code have too much hacks,
a total crap where we cant go back to it, and therefore the old code is of no help

the "buffer segment setting" was a killer setting, has been removed because was limited to specifics dash cases with specific templates, an incorrect setting of it can cause crashes on devices with limited memory or when playing 4k streams

In my tests live streams works are sufficiently stable
but there are too many live stream cases, and you are talking in general

there are still many things to be improved on ISA for live streaming e.g.:
-for dash its missing implementation for proper server timing sync for dash updates
-for HLS case, depends, there are live cases that dont works so well, a correct live delay is currently not automatically set...missing cleanups/implementation
-some time ago i also suspected a buffering loss bug that should come from old code
seems when the buffer finishes, then the buffer size (live delay) is no longer respected, no time ti investigate on this

this is a long term improvements...

> oh i see, there is a live_delay property now

yes you can override it to improve the situation

**Comment by matthuisman** [comment]
i did that, which makes it start further back - great...
But then it doesnt start trying to refresh until its right back at the end again :(
So it simply delays the issue

Does the refresh logic not kick-in until its close to head?

**Comment by CastagnaIT** [comment]
it could be related to the point 3 i written above

**Comment by matthuisman** [comment]
on kodi 20, if i set it to be 60s behind live and the buffer is 5mins
it will start at 4:00 and refresh and stay around 4:00/5:00

In Kodi 21, if i set live_delay to 60s
It will start at 4:00 and then play all the way to 5:00 and then buffer / pause


This is dash live manifest :)

**Comment by matthuisman** [comment]
do you think there is something i could proxy change in my manifests to force a longer buffer?

**Comment by CastagnaIT** [comment]
idk... needed a deeper investigation with a stream that can be tested

**Comment by matthuisman** [comment]
can you access NZ streams? I got a free to air one :)
My "TVNZ+" -> Live TV -> TVNZ 1

I also tried proxying and setting suggestedPresentationDelay to larger value.
Get the same behaviour as live_delay.
It makes is start further back but the refresh / get new manifest behaviour just never seems to kick in.

**Comment by CastagnaIT** [comment]
> can you access NZ streams? I got a free to air one :)

i will try idk
but not this weekend

**Comment by matthuisman** [comment]
ok, if i proxy the minimumUpdatePeriod down to 4s seems to help quite a bit.

I also notice now that i need to update refreshed manifests as well.
I used to just set the 1st and not modify the refreshes.
But it seems if i do that, IA now updates all the settings from the refresh (losing my lower update period etc)

Maybe we could have a new property to override the minimum update period?

**Comment by matthuisman** [comment]
@CastagnaIT  - just want to say appreciate your big effort on trying to get this add-on cleaned up and less "hacky" :)
Once all the niggles are worked out, its going to be amazing!
Bit of short term pain for long term gain

**Comment by MajinLugia** [comment]
In my case, I have channels from the Stremium plugin and when I start a channel, they start from the beginning of the timeline each time no matter what making the channel not live and since fast forward and rewind controls never properly worked, I can’t even fast forward to the current time of the programming. Downgrading to an earlier version of inputstream.adaptive isn’t helping either oddly.

**Comment by matthuisman** [comment]
@MajinLugia  that sounds quite unrelated to my issue here.
If your having issues with my Stremium plugin, I'd suggest opening an issue on my repo here: 
https://github.com/matthuisman/slyguy.addons/issues

They may just need my "Force playback from head" hack that some other multi-period dash need.
But it seems after https://github.com/xbmc/inputstream.adaptive/issues/574 that shouldnt be needed?
What version Kodi / Inputstream adaptive are you using?

I would need a stremium plugin to test with temporarilly though

**Comment by MajinLugia** [comment]
> @MajinLugia that sounds quite unrelated to my issue here. If your having issues with my Stremium plugin, I'd suggest opening an issue on my repo here: https://github.com/matthuisman/slyguy.addons/issues
> 
> They may just need my "Force playback from head" hack that some other multi-period dash need. But it seems after #574 that shouldnt be needed? What version Kodi / Inputstream adaptive are you using?
> 
> I would need a stremium plugin to test with temporarilly though

I am using Kodi 21.0 and I am using inputstream adaptive 21.5.1-Omega as I updated back to the latest version due to no difference in downgrading. I have emailed you my login for stremium!

**Comment by matthuisman** [comment]
thank you :) Got your email.
Can you advise a service / channel I can test with?

Its currently 1pm here in NZ. I hope to start having a look around 8pm (after work and after watching finale of House of dragon)

**Comment by MajinLugia** [comment]
> thank you :) Got your email. Can you advise a service / channel I can test with?
> 
> Its currently 1pm here in NZ. I hope to start having a look around 8pm (after work and after watching finale of House of dragon)

I’d say tune into USA Network, CNBC, TNT or really just about any channel that has 3 blue dots or 1 orange dot under the channel icons as those are sling channels that are giving that issue! Thank you so much and enjoy your night!
EDIT: I can’t save any settings on IPTV Merge on both android tv and pc.

**Comment by CastagnaIT** [comment]
> can you access NZ streams? I got a free to air one :) My "TVNZ+" -> Live TV -> TVNZ 1
> 
> I also tried proxying and setting suggestedPresentationDelay to larger value. Get the same behaviour as live_delay. It makes is start further back but the refresh / get new manifest behaviour just never seems to kick in.

i tried install that addon but also using vpn dont works error 403

**Comment by matthuisman** [comment]
oh right. tvnz are pretty good at blocking the major vpns.

I might close this issue.
I fixed a lot of the niggles by adjusting the suggested presentation delay and also doing some manual UTCTiming "fixes"
