### ISSUE TITLE
Could not open / parse mpdURL

### ISSUE THREAD

**Issue by quthla** [peak3d/inputstream.adaptive#162]
Error

`17:16:46.870 T:948790128   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://ors-uhd.cdn.ors.at/out/u/orfuhd-abr-hdr10_3.m3u8)`

M3U8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:101285
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101285.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101286.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101287.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101288.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101289.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101290.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101291.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101292.ts?m=1528901102&f=3
#EXTINF:6.000,
orfuhd-abr-hdr10_3_101293.ts?m=1528901102&f=3
```

Strm
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
http://ors-uhd.cdn.ors.at/out/u/orfuhd-abr-hdr10_3.m3u8
```

Only accessible with Austrian IP but if you need more information, let me know.

**Comment by JinRonin** [comment]
manifests without quality levels are not supported (yet).
But for your orf stream you can try:
`http://orfdev.cdn.ors.at/out/u/orfdev01cmaf-abr.m3u8`

**Comment by vlmaksime** [comment]
I have the same error in my plugin.

I have a link for the certificate 
https://w.ivi.ru/certificate/
and for the manifest
https://ivi-storage35.cdnvideo.ru/dash-mdrm-shq/DhVgz_oqwkFsjjn57tOiFQ,1529646775/storage35/contents/4/8/cd0b60effad29dd83526edce584041/manifest.mpd
file example: https://pastebin.com/vVMqUqDC

For playing I use this code:
```
li = xbmcgui.ListItem(path='https://ivi-storage35.cdnvideo.ru/dash-mdrm-shq/DhVgz_oqwkFsjjn57tOiFQ,1529646775/storage35/contents/4/8/cd0b60effad29dd83526edce584041/manifest.mpd')
li.setProperty('inputstream.adaptive.server_certificate', 'https://w.ivi.ru/certificate/')
li.setProperty('inputstream.adaptive.manifest_type', 'mpd')
li.setProperty('inputstreamaddon', 'inputstream.adaptive')
xbmcplugin.setResolvedUrl(_handle, True, li)
```
Log file: https://pastebin.com/3hhxLtZZ

**Comment by peak3d** [comment]
@vlmaksime 
> I have the same error in my plugin.
What same error do you have? Your case has really nothing to do with the initial post, pls. try to not hijack foreign posts.

For your issue pls open a new issue thread. before you do this, pls. provide the service certificate not as URL, but as b64 encoded binary data (call the URL above, b64encode the resulting payload, and use this as parameter value for server_certificate)

**Comment by peak3d** [comment]
@quthla issue solved? (thx @JinRonin )
