### ISSUE TITLE
Not compatible with newest kodi commit?

### ISSUE THREAD

**Issue by mrfixit2001** [peak3d/inputstream.adaptive#163]
Compiled the current commit from the xbmc repo (2ab16beeeaf67e3b8dca703d96615bd80aca7c35) and it says your newest commit (4db421d679b371a9ec6519548cc395a33da2a6e5) is not compatible when I attempt to enable the addon.

https://pastebin.com/Qmx7KrZZ

**Comment by peak3d** [comment]
@Rechi any ideas?

**Comment by Rechi** [comment]
@mrfixit2001 please post `inputstream.adaptive/addon.xml`. From reading Kodi only a wrong addon.xml could produce `Add-on 'inputstream.adaptive' is not compatible with Kodi` log lines.

**Comment by mrfixit2001** [comment]
I saw this previous issue with a similar problem, not sure if it helps:
https://github.com/peak3d/inputstream.adaptive/issues/150

Attached is the addon.xml that results after compile.

[addon.xml.zip](https://github.com/peak3d/inputstream.adaptive/files/2133126/addon.xml.zip)

**Comment by Rechi** [comment]
You haven't compiled against the inputstream binary interface you use (or maybe just not updated the addon.xml). Your addon,xml tells `<import addon="kodi.binary.instance.inputstream" version="2.0.6"/>`, but the Kodi version requires that the addon is compiled agains 2.0.7.

**Comment by mrfixit2001** [comment]
Ah, that helps a lot! Looks like I compiled the new inputstream first, then compiled the updated kodi after that. Needed to do it the other way around, as it looks like that version number changed fairly recently in the kodi source. Should be good now. Thanks!
