### ISSUE TITLE
[Bug] Since InputStream Adaptive Version that is working with Slyguys Addons HDR/4k Content do not work with castagnaIT Netflix

### ISSUE THREAD

**Issue by xMisterW** [peak3d/inputstream.adaptive#1635]
### Describe the problem

Hello,

im Using Kodi on a Fire TV Cube 3rd gen in the Android armeabi v7a Version

Since i geht Slyguys Addons Working with InputStream Adaptive. It is configured on adaptive. I cant play videos in your Netflix and they load infenite.

Kodi Version: 22.0-ALPHA1 (21.90.700) Git:20240729-80f4ac87d3

Inputstream Adaptive 22.1.0, 22.1.1 and 22.1.2

### Steps to reproduce

Navigate to Addons
Navigate to Video Addons
Navigate to Netflix
Choose Content you want to play with HDR/4k
It loads infinite

### Debug log

https://paste.kodi.tv/pequjaxeho

### Operating system(s)

Other (specify below)

### Operating system version(s)

FireTV OS 7.6.7.9

### InputStream Adaptive version(s)

22.1.0 - 22.1.2

### Kodi version(s)

22.0-ALPHA1 (21.90.700) Git:20240729-80f4ac87d3

**Comment by CastagnaIT** [comment]
that addon has development suspended also its not officially tested under kodi 22
also in the log i dont see addon directory accesses, nor initilaized playback
