### ISSUE TITLE
Inputstream PVR integration

### ISSUE THREAD

**Issue by snoopyjoe** [peak3d/inputstream.adaptive#165]
Is it possible to use inputstream to parse IPTV m3u8 streams played from within the Kodi PVR? Recent updates (6/6/18 and later) to the Kodi demuxer in the nightly builds prevent it from reading the m3u8 files from the PSvue EPG service. I recoded the service addon to use Inputstream to parse the streams from within the PVR but then the streams are only played as a listitem and not a pvr channel. This causes Kodi to crash when trying to change a channel. 

Here's a link to the inputstream section of the addon [Here](https://github.com/snoopyjoe/service.psvue.epg/blob/9fe23a3872ebda966b5311e9ecbc2ab633b7625e/resources/lib/webservice.py#L87)

**Comment by enen92** [comment]
Resolving playable paths must be accomplish from plugins and not from scripts/services. If your plugin sets the resolved url on the listitem you should be able to play it from pvr using their `plugin://` path.

**Comment by snoopyjoe** [comment]
The service creates a m3u playlist in which the urls are resolved as a listitem. This plays fine in the PVR, but Kodi plays them as standard video file from within the PVR. If you don't use Inputstream, then Kodi plays it as PVR channel.

**Comment by peak3d** [comment]
@snoopyjoe search for the pvr.zattoo addon and look how they do it.
If you search for "inputstreamaddon" you'll find the place.

Its not more than simply setting the already known listitem properties.

**Comment by snoopyjoe** [comment]
Thanks! I figured it out how to use the "plugin://" in the m3u playlist from what @enen92 was talking about. Addon works a lot better and was able to delete a lot of code.
