### ISSUE TITLE
twitch.tv not working with 2.2.24

### ISSUE THREAD

**Issue by L2501** [peak3d/inputstream.adaptive#167]
upgraded to latest git and now twitch streams are giving 403 error

**Comment by mac1202** [comment]
I had the same issue.

**Comment by JinRonin** [comment]
params are getting added from master to substreams that are actually not needed and yields in 403

log: https://www.dropbox.com/s/10m12kwade78mou/kodi.log?dl=0

**Comment by anxdpanic** [comment]
@peak3d is there any way to disable the behavior introduced with 298366ee57317898f8720bb1494342f45e5c96d6 ?

**Comment by peak3d** [comment]
@anxdpanic sorry for the delay, yes, I will change it so it that parameters are only attached, if base_url of master and sub matches. This should solve your issues.

**Comment by peak3d** [comment]
f1f16f37aadd49b79a1d69ffb4f24ef0701a0355

**Comment by anxdpanic** [comment]
That doesn't seem to have resolved the issue. The parameters are being past to the child playlists(different base url) still causing a 403, doesn't make it to the segments.
https://pastebin.com/raw/XpqjPCgg (ctrl-F #EXTM3U) to see the master playlist contents, and playback follows that. Apologies is that was outside the mentioned commit.

**Comment by peak3d** [comment]
And you are really sure, that you buid with this last commit?

**Comment by anxdpanic** [comment]
Yea, I just cleaned up and rebuilt to be sure. 
Looks like correct commit was used, 
```inputstream.adaptive-f1f16f37aadd49b79a1d69ffb4f24ef0701a0355.tar.gz```
Thanks for looking into it 👍

**Comment by peak3d** [comment]
can you log base_url_.c_str() and rep->source_url_.c_str()( here:

https://github.com/peak3d/inputstream.adaptive/blob/f1f16f37aadd49b79a1d69ffb4f24ef0701a0355/src/parser/HLSTree.cpp#L154

**Comment by mac1202** [comment]
I confirm build revision r364.f1f16f3 and issue still present.

**Comment by peak3d** [comment]
@mac1202 @anxdpanic as written above, pls. add a log line and provide the information what the vars tell

**Comment by peak3d** [comment]
pushed new commit, forgot one place

**Comment by anxdpanic** [comment]
I added the logging, but it doesn't make it too the log. I don't know any C++ so it may be that I added the log lines incorrectly. Can see what I added here: https://github.com/anxdpanic/inputstream.adaptive/commit/0f23fbbc098b1c39f62b78a48fab0172948b66d1

Building the latest commit fails with;
```
[ 88%] Building CXX object CMakeFiles/inputstream.adaptive.dir/src/parser/HLSTree.cpp.obj
HLSTree.cpp
E:\Workspace\GitHub\xbmc\cmake\addons\build\inputstream.adaptive\src\parser\HLSTree.cpp(216): error C2065: 'rep': undeclared identifier
E:\Workspace\GitHub\xbmc\cmake\addons\build\inputstream.adaptive\src\parser\HLSTree.cpp(216): error C2227: left of '->source_url_' must point to class/struct/union/generic type
E:\Workspace\GitHub\xbmc\cmake\addons\build\inputstream.adaptive\src\parser\HLSTree.cpp(216): note: type is 'unknown-type'
E:\Workspace\GitHub\xbmc\cmake\addons\build\inputstream.adaptive\src\parser\HLSTree.cpp(216): error C2228: left of '.compare' must have class/struct/union
```

**Comment by peak3d** [comment]
@anxdpanic ooops, sry, compile issue fixed

**Comment by anxdpanic** [comment]
That did it, everything looks to be working like before. 
Thanks again 👍
