### ISSUE TITLE
No module named 'distutils'  Libreelec Piers Nightly Build Rpi5



### ISSUE THREAD

**Issue by hbbernardo** [peak3d/inputstream.adaptive#1673]
Trying to play a Netflix title give me this error:

No Module named 'distutils'

Here's the log:

https://www.logpasta.com/paste/819c4662-68f1-4a00-b203-4a8a2ea32e09

Please let me know how I can  further help to clear this issue 

Thanks

**Comment by CastagnaIT** [comment]
inputstreamhelper has nothing to do with this addon,
open an issue on their repository

**Comment by hbbernardo** [comment]
> inputstreamhelper has nothing to do with this addon,
> open an issue on their repository

Sorry. The reason that I came here to post it was a message from Inputstream Helper asking me specifically to do it so.

 I will open a ticket at the Netflix addon GitHub page informing of this issue occurring with the latest builds of Libreelec Nightly Piers.

Thank You.

**Comment by CastagnaIT** [comment]
> I will open a ticket at the Netflix addon GitHub page informing of this issue occurring with the latest builds of Libreelec Nightly Piers.

you won't get help from n€tflix add-on
because if you look at stacktrace error on log
its clear that the error come from Inputstream Helper source code...

**Comment by hbbernardo** [comment]
Thanks for replying. 

Where should I ask for help? 

It was working perfectly just last week.

Please, let me know.

**Comment by hbbernardo** [comment]
> > I will open a ticket at the Netflix addon GitHub page informing of this issue occurring with the latest builds of Libreelec Nightly Piers.
> 
> you won't get help from n€tflix add-on
> because if you look at stacktrace error on log
> its clear that the error come from Inputstream Helper source code...
> 

Thanks for replying.

Where should I ask for help then?

It was working perfectly just last week.

Please, let me know.
