### ISSUE TITLE
[Bug] Space chars in the new adaptive DRM property cause the playback to fail

### ISSUE THREAD

**Issue by lavish440** [peak3d/inputstream.adaptive#1679]
### Describe the problem

I was testing the new adaptive.drm property with some Clearkey test streams. 
I obtained the json using json.dumps from Python but the logs were consistently saying "malformed JSON". 
Then I removed the space chars after the ':' and it worked. 
So there is some issue with escaping space chars. 

Note: I was using IPTV Simple Client. 

### Steps to reproduce

1. Try playing a DASH manifest with clearkeys by using the new adaptive.drm property. 

### Debug log

Not required. 

### Operating system(s)

Linux

### Operating system version(s)

Arch Linux 

### InputStream Adaptive version(s)

21.1.4

### Kodi version(s)

22.0-APLHA1 (21.90.700)

**Comment by CastagnaIT** [comment]
where is the log?

isa version `21.1.4` ? mistake ? because v21 of isa binary must not be used with kodi 22

also the space problem sound like the old IPTV Simple bug, not ISA bug,
that should be already fixed on last IPTV Simple release
so make sure to have installed, or builded, last IPTV Simple version 22.1.2

**Comment by lavish440** [comment]
Sorry, it was 22.1.4. 
I am on IPTV 22.1.0
Will try the new one

**Comment by lavish440** [comment]
Fixed on the latest IPTV client. Closing for now
Btw, how do I specify the Licence URL for Clearkeys DRM?

**Comment by CastagnaIT** [comment]
its explained on wiki with also examples
https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM

**Comment by lavish440** [comment]
Oh sorry didn't see the example for licence URL.
Another question, are multi keyIDs and Base64 supported through KodiProps?
 
Also the binary build from GitHub actions still has the old version and the old changelog.
