### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by drt420** [peak3d/inputstream.adaptive#168]
Hello Peak3d
I need your little help, I have modified your code as per my need and i am passing encrypted file, mpd and license key as an argument. Now, I am able to get "CDMMessage: 1 arrived!" but I am not able to receive challenge response from amazon server.
While same is working fine when I am using through kodi plugin. I am totally puzzled and not able to resolve this issue.

**Comment by daw134** [comment]
Are you trying to download from Amazon Video?

**Comment by drt420** [comment]
No I am not I am creating app for my use

**Comment by daw134** [comment]
I can see your progress on another forum lol

**Comment by peak3d** [comment]
Sorry, no support for things which go into the wrong direction.
