### ISSUE TITLE
[Feature request] Pass mpd URL custom headers to actual video files? [clearkey DRM]

### ISSUE THREAD

**Issue by enerdude** [peak3d/inputstream.adaptive#1684]
### Describe the feature

Hi I have a similar request to https://github.com/xbmc/inputstream.adaptive/issues/20

My case is not widevine drm but clearkey drm instead.  My m3u entry is e.g.

#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
https://example.com/manifest.mpd|Origin=https://example.com

The issue is that the custom 'Origin' header is applied to downloading the manifest but not to the following segments which leads to a http 403 forbidden in my case

### Motivation

I can see this as someting other people can also use.

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

**Comment by CastagnaIT** [comment]
this is not a feature request
you are using a malformed manifest request url by using pipe `|` char

pipe char is not allowed on this addon

there are explicit header properties to be used, read wiki
https://github.com/xbmc/inputstream.adaptive/wiki/Integration

**Comment by enerdude** [comment]
Thanks for your quick reply.
Excuse my ignorance when it comes to programming in general as well as doing add-ons.
If I understand it correct I must set a property e.g.
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers

Assuming I'm not writing a plugin / just creating a .strm / .m3u file, how would I specify these properties or is there an example skeleton add-on I can modify to enable me to use 'plugin://' in my playlist to play just one encrypted item?

Edit: or is there a way to use '#KODIPROP:' to set these headers and therefore not needing to create an addon?

**Comment by CastagnaIT** [comment]
> Assuming I'm not writing a plugin / just creating a .strm / .m3u file, how would I specify these properties

if you look at example on top of wiki page, there is the example
just add new KODIPROP: lines with your properties having the appropriate value after "=" char

> or is there an example skeleton add-on I can modify

not skeleton, but you can take ispiration from #1678 and modify it,
anyway exists many kodi addons that integrate ISAdaptive just make some searchs on the web

**Comment by enerdude** [comment]
Ok thanks

One last question if I need to set:
listitem.setProperty('inputstream.adaptive.stream_headers', 'headername=value')

do I do:
#KODIPROP:inputstream.adaptive.stream_headers=headername=value ?

**Comment by CastagnaIT** [comment]
yep exactly

**Comment by enerdude** [comment]
Does not work.

I also tried
#KODIPROP:inputstream.adaptive.stream_headers=['Origin=https://example.com']

When I sniff the traffic, the origin headers is not added

Surely
#KODIPROP:inputstream.adaptive.stream_headers=headername=value

cannot work cause there is 2 '=' signs on one line?

**Comment by CastagnaIT** [comment]
> #KODIPROP:inputstream.adaptive.stream_headers=['Origin=https://example.com']

must be
`#KODIPROP:inputstream.adaptive.stream_headers=Origin=https://example.com`
for correctness the header should be url encoded
`#KODIPROP:inputstream.adaptive.stream_headers=Origin=https%3A%2F%2Fexample.com`

if you read in full the wiki, the stream_headers is applied to streams requests only,
if you want to apply to manifest or license are separate properties

**Comment by enerdude** [comment]
Thanks so much for your help!  Did not mean to waste your time but as I said I don't know much about programming in general.

Just for future reference for people with the same "problem", my final solution was:


#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|xxxx:xxxx
#KODIPROP:inputstream.adaptive.manifest_headers=Origin=https%3A%2F%2Fexample.com
#KODIPROP:inputstream.adaptive.stream_headers=Origin=https%3A%2F%2Fexample.com
https://example.com/manifest.mpd|Origin=https://example.com


Note I still had to put the |Origin=https://example.com after the manifest otherwise the first HEAD and GET got 403 errors even though after that it still worked.  I am a perfectionist so I rather put it this way.

I have another question for you even though unrelated to this add-on.  I have asked on kodi forums and other places but could never get an answer.  When I want to play an url in a strm / m3u file, is there any way to specify a proxy (http / socks) via the '|' or even a #KODIPROP - or must I create an add-on that use requests library to specify proxy?
e.g. http://example.com/live/aaaa/bbbb/file.ts|socks5://1.1.1.1:8080

Please delete this post (or last part thereof if necessary)

**Comment by enerdude** [comment]
[QUOTE=2nHxWW6GkN1l916N3ayz8HQoi;2748746]No idea. I've seen a few users capable of obtaining keys just from a mpd, either from a cache keys DB, or through other tricks. Wait until your comment is seen by one of them.

Edit: actually try these ones

[CODE]
- Sky Sports Action --key 000397ec797bffa6a7d2f5f14bf3f90b:644bb73f541fb127d218ddfc0fccb38f
- Sky Sports Arena --key 000516903d55e9706d1661c489ee94da:acf37edb85d8a99a8cfb8ed5e3e9acf2
- Sky Sports F1 --key 0005c0635a06a943911f666abcef3923:749cae7fc7f350be6ba7400f11150ea9
- Sky Sports Football --key 0005c37ab85893a379c1e1e5ed60fcf0:b60a9aa6c55026adfc3f47136ce64924
- Sky Sports Main Event --key 000546476256963bd054ded3b6ae5800:1e497068bcc078fdb2f4296bc400ca2b
- Sky Sports Mix --key ???
- Sky Sports PL --key 00058832b1c058c3de8b5d118cc775d4:721345f25729d236d6bb317fce797b77
[/CODE][/QUOTE]
 
Thanks for your input on the keys.  I actually came to this forum to figure out how to play the clearkey DRM inside Kodi.

I eventually figured it out, example to do Sky Sports Action:
[code]
#EXTINF:-1,Sky Action via UK ip address
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|000397ec797bffa6a7d2f5f14bf3f90b:644bb73f541fb127d218ddfc0fccb38f
https://linear001-gb-dash1-prd-ak.cdn.skycdp.com/Content/DASH_003_720_120/Live/channel(skysportsaction)/manifest_720-120.mpd
[/code]

I have read a few threads but still unsure how to get the key pairs.  I have downloaded the manifests, tried sites like
[code]https://emarsden.github.io/pssh-box-wasm/decode/[/code]
to decode the PSSH in the manifest, but still don't get enough info to get to the keys.
I know here is also a noob python script to get these things for you, but I would like to know the manual method if anybody can explain, LOL

**Comment by CastagnaIT** [comment]
> Note I still had to put the |Origin=https://example.com/ after the manifest otherwise the first HEAD and GET got 403 errors even though after that it still worked. I am a perfectionist so I rather put it this way.

this is also explained on the wiki, in fact you have not set the mimetype on the strm

> Just for future reference for people with the same "problem", my final solution was:

for a lack of understanding of how works things,
suggest to do wrong things to users is not so appropriate...

for your last question idk
