### ISSUE TITLE
[Bug] AES-128 encrypted HLS stream failed to play on Android devices

### ISSUE THREAD

**Issue by vargalex** [peak3d/inputstream.adaptive#1686]
### Describe the problem

AES-128 encrypted HLS streams cannot be played on Android devices, because the ISA receive HTTP 404 on downloading encryption.key. I have tested on Kodi 20.5, 21.0 and 21.1. On Linux and Windows devices working fine.
Without ISA (with Kodi embedded method), the ffmpeg download the encryption.key without problem and the stream is playing.

### Steps to reproduce

1. My original URL: https://filemoon.in/e/r3lij9c74xw4$$https://dmda.media
2. Resolve URL with ResolveURL. My resolved URL is: [https://be2719.rcr22.ams01.cdn112.com/hls2/02/06885/r3lij9c74xw4_h/master.m3u8?t=CfwBNZqGI4zoYu3Y6e7m97fOBPRojKUzNkiUhhcEKkQ&s=1727196001&e=10800&f=34429012&srv=27&asn=47159&sp=4000|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Ffilemoon.in%2Fe%2Fr3lij9c74xw4&Origin=https%3A%2F%2Ffilemoon.in&verifypeer=false](https://be2719.rcr22.ams01.cdn112.com/hls2/02/06885/r3lij9c74xw4_h/master.m3u8?t=CfwBNZqGI4zoYu3Y6e7m97fOBPRojKUzNkiUhhcEKkQ&s=1727196001&e=10800&f=34429012&srv=27&asn=47159&sp=4000|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Ffilemoon.in%2Fe%2Fr3lij9c74xw4&Origin=https%3A%2F%2Ffilemoon.in&verifypeer=false)
3. Play it with Kodi

### Debug log

[https://paste.kodi.tv/pureyujixo.kodi](https://paste.kodi.tv/pureyujixo.kodi)

### Stream manifest file(s)
(Not the original, but similar. Unfortunately the encryption.key URL is source IP locked)
#EXTM3U
#EXT-X-TARGETDURATION:20
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://be7713.rcr82.waw05.cdn112.com/hls2/01/04421/z5fidp3hyi8e_h/encryption.key?t=E-lk8_KMfKbtrsfwji1ILOO5wgVF_kljTeZR9VK2Ss8&s=1728029973&e=10800&f=22105461&srv=39&asn=21334&sp=4000"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:12.095,
https://be7713.rcr82.waw05.cdn112.com/hls2/01/04421/z5fidp3hyi8e_h/seg-1-v1-a1.ts?t=E-lk8_KMfKbtrsfwji1ILOO5wgVF_kljTeZR9VK2Ss8&s=1728029973&e=10800&f=22105461&srv=39&asn=21334&sp=4000
#EXTINF:14.932,
https://be7713.rcr82.waw05.cdn112.com/hls2/01/04421/z5fidp3hyi8e_h/seg-2-v1-a1.ts?t=E-lk8_KMfKbtrsfwji1ILOO5wgVF_kljTeZR9VK2Ss8&s=1728029973&e=10800&f=22105461&srv=39&asn=21334&sp=4000
#EXTINF:10.010,
https://be7713.rcr82.waw05.cdn112.com/hls2/01/04421/z5fidp3hyi8e_h/seg-3-v1-a1.ts?t=E-lk8_KMfKbtrsfwji1ILOO5wgVF_kljTeZR9VK2Ss8&s=1728029973&e=10800&f=22105461&srv=39&asn=21334&sp=4000
#EXTINF:10.010,
...

### Operating system(s)

Android

### Operating system version(s)

Android 11, Android 12, etc.

### InputStream Adaptive version(s)

21.5.4

### Kodi version(s)

Kodi 20.5, Kodi 21.0, Kodi 21.1

**Comment by lavish440** [comment]
I can confirm that HLS stream with AES-128 keys work fine on Kodi for Android and Linux. 

Edit: Looks like the issue might be the Kodi user agent. Try changing it for the licence URL.

**Comment by CastagnaIT** [comment]
first: on manifest url, you must remove headers injection with pipe use: `|User-Agent=...`
this only lead to problems because not supported by ISAdaptive, its a Kodi core thing only

second: i also suspect that the server reject the request due to wrong user agent
the .key its license request, and so you have to add the user agent on [inputstream.adaptive.license_key](https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM-%28old%29#inputstreamadaptivelicense_key)

e.g.
`prop["inputstream.adaptive.license_key"] = "|User-Agent=xy"`

**Comment by vargalex** [comment]
My first idea was the User agent too, but I can download without problem the encryption.key with curl without user-agent modification.
But, than my question: how can I change the User agent for the licence URL? As you can see, I give the m3u8 URL to the inputstream adaptive with user-agent. The ISA use the user agent for m3u8 request, but not for license URL request.

**Comment by vargalex** [comment]
> first: on manifest url, you must remove headers injection with pipe use: `|User-Agent=...` this only lead to problems because not supported by ISAdaptive, its a Kodi core thing only
> 
> second: i also suspect that the server reject the request due to wrong user agent the .key its license request, and so you have to add the user agent on [inputstream.adaptive.license_key](https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM-%28old%29#inputstreamadaptivelicense_key)
> 
> e.g. `prop["inputstream.adaptive.license_key"] = "|User-Agent=xy"`

Than I must download the m3u, parse it, and set the full URL with User-Agent to the license_key property? But I don't uderstand, why don't have I the same problem under Linux and Windows?

**Comment by lavish440** [comment]
> My first idea was the User agent too, but I can download without problem the encryption.key with curl without user-agent modification.


Maybe the Kodi Android User-Agent is blacklisted by the service that you are using. 

> But, than my question: how can I change the User agent for the licence URL? As you can see, I give the m3u8 URL to the inputstream adaptive with user-agent. The ISA use the user agent for m3u8 request, but not for license URL request.

If you are using a .m3u playlist, then just do

```
#KODIPROP:inputstream.adaptive.license_key=|User-Agent=foo_bar||
```

**Comment by vargalex** [comment]
> first: on manifest url, you must remove headers injection with pipe use: `|User-Agent=...` this only lead to problems because not supported by ISAdaptive, its a Kodi core thing only
> 
> second: i also suspect that the server reject the request due to wrong user agent the .key its license request, and so you have to add the user agent on [inputstream.adaptive.license_key](https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM-%28old%29#inputstreamadaptivelicense_key)
> 
> e.g. `prop["inputstream.adaptive.license_key"] = "|User-Agent=xy"`

Thanks, that was the solution.

**Comment by vargalex** [comment]
> first: on manifest url, you must remove headers injection with pipe use: `|User-Agent=...` this only lead to problems because not supported by ISAdaptive, its a Kodi core thing only
> 
> second: i also suspect that the server reject the request due to wrong user agent the .key its license request, and so you have to add the user agent on [inputstream.adaptive.license_key](https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM-%28old%29#inputstreamadaptivelicense_key)
> 
> e.g. `prop["inputstream.adaptive.license_key"] = "|User-Agent=xy"`

Thanks, that was the solution.

**Comment by CastagnaIT** [comment]
i think in future should be introduced a new property that allow to set a global headers
that will make easier setups

**Comment by vargalex** [comment]
> i think in future should be introduced a new property that allow to set a global headers that will make easier setups

I have set the `stream_headers` and `manifest_headers`, but ISA doesn't use it for license_key. The [inputstream.adaptive.license_key](https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM-%28old%29#inputstreamadaptivelicense_key) documentation a bit misleading, because writes that this parameter is for DRM streams. AES encrypted HLS streams are only a note on the page...

**Comment by lavish440** [comment]
> i think in future should be introduced a new property that allow to set a global headers
> that will make easier setups

Yes, sometimes I need to do manifest, stream and licence. A global property would be better.

**Comment by CastagnaIT** [comment]
yes a bit of a misleading but AES encryptions (and others similars) are corner cases,
if it wasn't for the headers it wouldn't have been particularly useful
i will try to think how to improve the page

i will consider to add global headers on kodi 22
since more users encountered similar problems/misunderstandings
