### ISSUE TITLE
[Bug] Latest ISA build from Github Actions carshes ISA

### ISSUE THREAD

**Issue by lavish440** [peak3d/inputstream.adaptive#1690]
### Describe the problem

I downloaded the latest builds from Github actions to test the new `inputstream.adaptive.common_headers` property.
It was successfully installed. But when I tried to play any content with ISA (no matter the property used), it crashes Kodi.

### Steps to reproduce

1. Download and install the latest build of ISA from Github Actions.
2. Try playing any content with ISA.

### Debug log

```log
2024-10-11 19:36:46.807 T:8196     info <general>: Creating InputStream
2024-10-11 19:36:46.807 T:8196    debug <general>: ADDON: Dll Initializing - InputStream Adaptive
2024-10-11 19:36:46.807 T:8196    debug <general>: SECTION:LoadDLL(/home/lavish/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.22.1.5)
2024-10-11 19:36:46.807 T:8196    debug <general>: Loading: /home/lavish/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.22.1.5
2024-10-11 19:36:46.810 T:8130    debug <general>: Loading settings for pvr://channels/tv/All%20channels@-1/93@pvr.iptvsimple_1625116856.pvr
```

### Operating system(s)

Linux

### Operating system version(s)

Arch Linux

### InputStream Adaptive version(s)

22.1.5

### Kodi version(s)

Kodi (22.0-ALPHA1 (21.90.700) Git:20240924-20ad993b8e1-dirty)

**Comment by CastagnaIT** [comment]
are you able to try cherry-pick the commit from PR #1683 and rebuild it?
i assume its same problem

**Comment by lavish440** [comment]
do a checkout at 1683 and then build?

**Comment by CastagnaIT** [comment]
maybe more easy for you manually edit the files
see the changes
https://github.com/CastagnaIT/inputstream.adaptive/commit/14c708a57144a0aaf99af0852e7f1260ad3169f6

**Comment by lavish440** [comment]
It worked. 
Also, the new property works good.

**Comment by CastagnaIT** [comment]
thanks for the feedback

**Comment by lavish440** [comment]
@CastagnaIT 
Also before opening another issue, I want to ask something. 
I tried the new DRM property. It works great. 
I used the `use_http_get_request`, it only worked for Widevine DRM but not for Clearkey. 
Is that how it's supposed to work?

**Comment by CastagnaIT** [comment]
clear key license request fwik is mandatory use POST request,
because you need to inform the license server of the KID's to be requested

**Comment by lavish440** [comment]
> clear key license request fwik is mandatory use POST request,
> because you need to inform the license server of the KID's to be requested

What if the server already knows the current keyID which would be requested?
In that case forcing a get request could be helpful.

**Comment by CastagnaIT** [comment]
what you are saying sound a bit weird to me
how can a license server know what stream you are decoding if you dont provide the kids?

looks like a out-of-spec thing, exists some test stream that can prove this?
as you can read on the specs there is a license request format to be used
https://www.w3.org/TR/encrypted-media/#clear-key-request-format

**Comment by lavish440** [comment]
I am currently using this because ISA can't extract the Default KID from the media segments. 
I manually inject the KID and PSSH in the manifest.
Because of that I already know the KeyID that would be requested.

Edit: My use case is described in https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/159#issue-272030686

> Use the same initialization segment throughout. The initialization segment, including default_KID stays the same even if key rotates. cenc:default_KID should not present in the manifest. Use sbgp sgpd with seig in media segments to indicate the key id (See DASH-IF-IOP v4.1 7.4.1). There is no need to use separate periods when key rotates as neither initialization segment nor cenc:default_KID changes.

**Comment by CastagnaIT** [comment]
yes what you are describing is the DRM key rotation behaviour, is not supported in ISA
there are some issues already opened, and its also specified on wiki WIP page

but your request is a workaround an attempt to mitigate this unsupported feature
does not seem to me to be the case to implement vague customizations due to unsupported features

**Comment by lavish440** [comment]
currently ISA can successfully extract default KID from initial segments but not from media

**Comment by CastagnaIT** [comment]
> currently ISA can successfully extract default KID from initial segments but not from media

initial segment is similar but different thing,
you need to implement correctly the key rotations management between segments and decryption pool

**Comment by lavish440** [comment]
> > currently ISA can successfully extract default KID from initial segments but not from media
> 
> initial segment is similar but different thing,
> you need to implement correctly the key rotations management between segments and decryption pool

See my above comment. I quoted something from the DASH IF. 
That could also partially solve the Widevine playback issue that I reported.
