### ISSUE TITLE
clearkey intergration

### ISSUE THREAD

**Issue by frankyarch** [peak3d/inputstream.adaptive#1696]
hello

can you do me a favor
how to re-edit the key like this into real clearkey so make it Playable ?

#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey 
#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"5KI1mwVWM5nx2a385kFySg", "kid":"aWRrdV8xMDAwMDAwMDAwMA" } ], "type":"temporary" }

i tested this key formatting on my v22 kodi. but it's not playable
thank you

**Comment by CastagnaIT** [comment]
the `license_key` property dont support clearkey,
moreover this data

> { "keys":[ { "kty":"oct", "k":"5KI1mwVWM5nx2a385kFySg", "kid":"aWRrdV8xMDAwMDAwMDAwMA" } ], "type":"temporary" }

its in the clearkey server license response format that use a custom base64 https://www.w3.org/TR/encrypted-media/#using-base64url
as is cant be used,
first you need to convert/obtain the keys and kids in to hex format, maybe there is some utility on the web idk...

after that
for the ISA configuration, suggest you to read wiki page where all is explained,
the `drm_legacy` property is more easy to use
https://github.com/xbmc/inputstream.adaptive/wiki/Integration-DRM

**Comment by lavish440** [comment]
@frankyarch Convert both keyID and key into Hex (Base16) from Base64.
then use this format: `#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|keyid_in_hex:key_in_hex`

**Comment by lavish440** [comment]
@CastagnaIT I have a related question. Will CBCS clearkeys be supported in the future?

**Comment by CastagnaIT** [comment]
> @CastagnaIT I have a related question. Will CBCS clearkeys be supported in the future?

atm there is no plan

> then use this format: `#KODIPROP:inputstream.adaptive.drm_legacy=keyid_in_hex:key_in_hex`

also this one is wrong, miss the key system and the pipe

**Comment by lavish440** [comment]
> > @CastagnaIT I have a related question. Will CBCS clearkeys be supported in the future?
> 
> atm there is no plan

Will that be just as hard as key rotation to implement?

> 
> > then use this format: `#KODIPROP:inputstream.adaptive.drm_legacy=keyid_in_hex:key_in_hex`
> 
> also this one is wrong, miss the key system and the pipe

Yeah I have corrected it now.

**Comment by CastagnaIT** [comment]
> Will that be just as hard as key rotation to implement?

in theory, more easy than key rotation, since similar thing is already implemented on widevine decrypter
some time ago i had already asked the other maintainer that implemented cbcs it in the past, who told me that it is possible to do
anyway he has too little time, and i'm already busy with all others changes that im working from last year

is not a priority so it stays there like all the other new features that will be evaluated in the future
ofc unless some other volunteer dev offers to implement them

**Comment by frankyarch** [comment]
> them

ok thx to your advise. it's working

**Comment by aseanic** [comment]
> > them
> 
> ok thx to your advise. it's working

Hi i couldnt get this working can u help? 
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|3f726fd5cbbf5944437a4dbfab431b10:376b009796e4ad50ea8f68d796676692
https://ht7mvvlb8c.execute-api.ap-southeast-1.amazonaws.com/ria.mpd
```
