### ISSUE TITLE
RPI5: Netflix Addon fails to resume any title on Nightly Libreelec Piers

### ISSUE THREAD

**Issue by hbbernardo** [peak3d/inputstream.adaptive#1703]
### Describe the problem

While using Netflix Addon on the latest nightly builds of Libreelec/Kodi Piers it falls to resume any video.

No error message is given. No vídeo appears. Only a loading icon. 

I have to reboot RPi5 using SSH because Kodi becomes unresponsive

### Steps to reproduce

Using the latest nightly build of Libreelec/Piers open Netflix Addon. 

Try to resume any title. 

No vídeo playback. Kodi becomes unresponsive

### Debug log

Here's the debug log

https://paste.kodi.tv/vitucilulu.kodi

### Operating system(s)

Other (specify below)

### Operating system version(s)

Libreelec

### InputStream Adaptive version(s)

22.1.7-Piers

### Kodi version(s)

V22

**Comment by CastagnaIT** [comment]
there are more underlying problem with that addon, where there are already opened issues on his repo
