### ISSUE TITLE
[Bug] Playback fails when switching playback from one DRM type to another

### ISSUE THREAD

**Issue by lavish440** [peak3d/inputstream.adaptive#1704]
### Describe the problem

The playback fails when I switch from one DRM type let's say Widevine DASH to CK DASH or HLS.

### Possible fix

Maybe it is caused due to the rework in Session property.

### Steps to reproduce

1. Play a DASH WDV stream
2. Switch to a DASH CK stream while the previous one is still playing in the background 

### Debug log

```
2024-10-20 17:47:52.282 T:87615    info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 3, Type: live)
2024-10-20 17:47:52.282 T:87615   error <general>: AddOnLog: inputstream.adaptive: InitializePeriod: Unhandled encrypted stream.
```

### Additional info

I am not able to play any other type of stream than the one I started with unless I restart Kodi.

### Operating system(s)

Linux

### Operating system version(s)

Arch Linux

### InputStream Adaptive version(s)

22.1.7 (Git Piers branch)

### Kodi version(s)

22.0-ALPHA1 (21.90.700) Git:20241006-fcdd657039f-dirty

**Comment by CastagnaIT** [comment]
tested and to me works correctly
binary addons like this one works with single instance, two playbacks cant reuse same instance, so cant be in conflict

> InitializePeriod: Unhandled encrypted stream.

more likely a bad configuration in DRM config or something unsupported in the manifest

**Comment by lavish440** [comment]
> tested and to me works correctly
> binary addons like this one works with single instance, two playbacks cant reuse same instance, so cant be in conflict

Let me try with a new build from Kodi master

> > InitializePeriod: Unhandled encrypted stream.
> 
> more likely a bad configuration in DRM config or something unsupported in the manifest

The same config and manifest works after restarting Kodi.

**Comment by CastagnaIT** [comment]
> Let me try with a new build from Kodi master

If you are doing the build yourself, also make sure to dont mix debug and release builds between kodi / ISA
mixing buld types can produce side effects

**Comment by lavish440** [comment]
> > Let me try with a new build from Kodi master
> 
> If you are doing the build yourself, also make sure to dont mix debug and release builds between kodi / ISA
> mixing buld types can produce side effects

Ohh, I will make sure of that.

**Comment by lavish440** [comment]
Not able to reproduce it on Android. 
I can't test out the Kodi master on Arch Linux as it fails on some Groovy error for me. 
I tried a lot of things but still it fails.

**Comment by CastagnaIT** [comment]
i never used arch linux so idk,
if you attach the manifest and drm property config used (also censored) for the clearkey i can try understand the situation
also the full log with debug enabled, two lines of logs say little

**Comment by lavish440** [comment]
> i never used arch linux so idk,
> if you attach the manifest and drm property config used (also censored) for the clearkey i can try understand the situation
> also the full log with debug enabled, two lines of logs say little

I think this would be a very good usecase for the ISA Tester Python addon that you have developed. 
I will try to use it.

**Comment by lavish440** [comment]
I tested with your Py addon.

https://github.com/user-attachments/assets/8e941ad1-947d-44e3-bffe-f779c2c9f07a

Wasn't able to get debug logs but one of the WDV License Server said:
`403 License denied. The license request contains a key ID that is not present in the entitlement message: eb676abb-cb34-5e96-bbcf-616630f1a3da.`

**Comment by CastagnaIT** [comment]
ok tested under ubuntu and i was able to replicate this situation
thats weird thing under windows dont happens
i will need to to some more tests

**Comment by lavish440** [comment]
> ok tested under ubuntu and i was able to replicate this situation
> thats weird thing under windows dont happens
> i will need to to some more tests

Looks like a Linux only issue then. 
I will also try to reproduce it on Android if I can.

**Comment by CastagnaIT** [comment]
i opened a fix PR #1706
a test under ubuntu seem to works
try build ISA with it and let me know

**Comment by lavish440** [comment]
Tested and looks like it has been fixed with the changes that you made.

**Comment by lavish440** [comment]
@CastagnaIT Can you merge it please?

**Comment by CastagnaIT** [comment]
i was waiting review form someone of team but seem no one has time
i will merge anyway

**Comment by lavish440** [comment]
I have tested it if it counts 😛

**Comment by CastagnaIT** [comment]
was not only for test it, but to know about correctness of the code change

**Comment by lavish440** [comment]
Ohh got it.
