### ISSUE TITLE
[Bug] Kodi crashes when playing streams from D+

### ISSUE THREAD

**Issue by Maven85** [peak3d/inputstream.adaptive#1707]
### Describe the problem

When playing a stream from D+, Kodi crashes after 60 seconds.

### Steps to reproduce

1. Start a stream from D+
2. Wait 60 seconds

### Debug log

*deleted*

### Stream manifest file(s)

*deleted*

### Operating system(s)

Android

### Operating system version(s)

Android 9 / 12

### InputStream Adaptive version(s)

22.1.7

### Kodi version(s)

Kodi v22 nightly

**Comment by Maven85** [comment]
The problem seems to occur when switching resolution from one segment to the next.

If you choose a fixed resolution, there are no problems.

**Comment by CastagnaIT** [comment]
logcat show something useful about the crash?

**Comment by Maven85** [comment]
here is a logcat: 
*deleted*

**Comment by Ronny-nerd** [comment]
I have the same problem as Maven85.

**Comment by CastagnaIT** [comment]
im not able to reproduce the crash without having D+
but testing another HLS with multiple periods i found that chapters was badly updated for VOD content

i made a test fix hoping its the same problem of D+ (k22)
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1713/1/artifacts

**Comment by Maven85** [comment]
I found that the issue has existed since #1670

**Comment by Maven85** [comment]
The crash still exists

**Comment by CastagnaIT** [comment]
i think the only fast way is that someone provide me a D+ access so that i can reproduce it locally
if someone is willing just copy settings.xml from folder
`userdata\addon_data\slyguy.disney.plus`
and send to my email

**Comment by Maven85** [comment]
I can do it. To which email address?

**Comment by CastagnaIT** [comment]
use that one provided here http://beacons.ai/castagnait

**Comment by CastagnaIT** [comment]
received, works
i catch the crash, i will investigate for a solution

**Comment by CastagnaIT** [comment]
this should works let me know
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1713/2/artifacts

**Comment by Maven85** [comment]
I can confirm. Thanks.

**Comment by Ronny-nerd** [comment]
It also works for me again under Kodi Piers and Kodi Omega and I would like to thank CastagnaIT and Maven85. 

https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1713/3/artifacts

https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1716/2/artifacts
