### ISSUE TITLE
[Bug] [ism] problems with playback from v21.5.5/22.1.6

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1708]
### Describe the problem

Since ISA v21.5.5 / v22.1.6 there are problems with playback DRM protected Microsoft Smooth Streaming Media manifests.  Result you can see in the screenshot below: 
![screen](https://github.com/user-attachments/assets/c681e519-2239-4215-9910-6ce7666854d8)

### Steps to reproduce

1. start to playback ism manifest (DRM protected)

### Debug log

[log_K22_ISAv22.1.7.txt](https://github.com/user-attachments/files/17534379/log_K22_ISAv22.1.7.txt)

### Stream manifest file(s)

[manifest_1730039657.txt](https://github.com/user-attachments/files/17534380/manifest_1730039657.txt)

### Operating system(s)

Windows

### Operating system version(s)

Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.5011

### InputStream Adaptive version(s)

v21.5.5 / v22.1.6 / v22.1.7

### Kodi version(s)

21.1 / 22.0-ALPHA1 (21.90.700) Git:20241026-60a52e2caf

**Comment by CastagnaIT** [comment]
try install this test build
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1709/1/artifacts
let me know

**Comment by mtr81** [comment]
Unfortunately, the problem still exists.
[log.txt](https://github.com/user-attachments/files/17551286/log.txt)
[manifest_1730172436.txt](https://github.com/user-attachments/files/17551287/manifest_1730172436.txt)

**Comment by CastagnaIT** [comment]
another attempt
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1710/1/artifacts

**Comment by mtr81** [comment]
Works fine. Thanks!

**Comment by CastagnaIT** [comment]
Issues thread are closed automatically by PR when merged, no need to be closed manually,
the build i done is not a full fix only a test to understand the problem
i tried revert a code, but do this will introduce another bug, so its not a solution

**Comment by CastagnaIT** [comment]
let me know if playback with this test build still work
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1710/2/artifacts

**Comment by mtr81** [comment]
I confirm, it works as it should.
