### ISSUE TITLE
[Feature request] Setting in inputstream adaptive to ignore invalid ssl certificates in website of video source

### ISSUE THREAD

**Issue by enerdude** [peak3d/inputstream.adaptive#1714]
### Describe the feature

On a system with inputstream.adaptive and without inputstream.ffmpegdirect:

I have a video source coming from a website without a proper SSL certificate and if I force playback through adaptive via #KODIPROP it won't play it.
When I remove the #KODIPROP it works, I assume it uses the default kodi player. (btw can you explain what the default player uses when it is a fresh installation of kodi with no addons, is it similar to ffmpeg?)

### Motivation

Maybe sometimes one is forced to playback from an insecure site / site without proper SSL Certificate, then this is handy.  I guess it is not all that secure but it will be nice to have a setting that can be set to 'ignore SSL certificate'

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

**Comment by enerdude** [comment]
BTW, I also tried adding |verifypeer=false after url as specified here: https://kodi.wiki/view/SSL_certificates
but it has no effect

**Comment by MoojMidge** [comment]
You can use this: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptiveconfig-

**Comment by CastagnaIT** [comment]
the only way is try to use and disable the ssl_verify_peer of inputstream.adaptive.config as linked above

**Comment by enerdude** [comment]
ok thanks a lot, can you please confirm the syntax for kodiprop, is it like this:
#KODIPROP:inputstream.adaptive.config={"ssl_verify_peer":false}

Also for interest sake, on a clean Kodi installation without adaptive or ffmpegdirect, what is the default kodi player based on?  ffmpeg?

**Comment by CastagnaIT** [comment]
correct

yes kodi is based on ffmpeg library

**Comment by enerdude** [comment]
> ok thanks a lot, can you please confirm the syntax for kodiprop, is it like this:
> #KODIPROP:inputstream.adaptive.config={"ssl_verify_peer":false}

Can you please confirm the syntax for future use, I cannot test it as the site I had a problem with now has a valid ssl certificate

**Comment by enerdude** [comment]
I have tried the kodiprop syntax as follow:
`#KODIPROP:inputstream.adaptive.config={"ssl_verify_peer":false}`

It does not seem to work, can you please advise the correct syntax

**Comment by CastagnaIT** [comment]
yes, i have already confirmed on my previous comment

make ensure that you are using ISA v.21.4.11 or higher
if dont works its not an addon problem
