### ISSUE TITLE
[Feature request] [HLS] manifests with #EXT-X-PROGRAM-DATE-TIME tags

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#1719]
### Describe the feature

Adding a ISA property to disable the inclusion of `#EXT-X-PROGRAM-DATE-TIME` tags in the playback process.

### Motivation

I noticed that ISA has a problem with playback HLS manifests containing `#EXT-X-PROGRAM-DATE-TIME` tags. 
Currently, the only solution is to edit manifests using a proxy. Also inpustream ffmpegdirect player correctly plays manifests with these tags...

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

**Comment by CastagnaIT** [comment]
you havent described nor provided files that explains the underlying reasons why the #EXT-X-PROGRAM-DATE-TIME must be deleted/ignored, as far as i know this could also be an unresolved bug that you are trying to hide instead of solve it
i cannot accept this request as is

**Comment by mtr81** [comment]
**Case no. 1** [incorrect data on counter and thus a problem with video scrolling]:
[manifest_1730949530_master.txt](https://github.com/user-attachments/files/17655599/manifest_1730949530_master.txt)
[manifest_1730949532_child-video.txt](https://github.com/user-attachments/files/17655600/manifest_1730949532_child-video.txt)
You can see on counter:
- start time: 11:16:21
- end time: 11:31:16

After removing tags `#EXT-X-PROGRAM-DATE-TIME` (by proxy) Kodi gives correct data:
00:00:00 / 00:14:55

**Case no. 2** [LIVE STREAM - playbacks stops after 13 sec. and then Kodi crashes]
[log.txt](https://github.com/user-attachments/files/17655783/log.txt)
[manifest_1730951188_child-video.txt](https://github.com/user-attachments/files/17655784/manifest_1730951188_child-video.txt)
[manifest_1730951188_master.txt](https://github.com/user-attachments/files/17655785/manifest_1730951188_master.txt)
[manifest_1730951193_child-video.txt](https://github.com/user-attachments/files/17655786/manifest_1730951193_child-video.txt)
[manifest_1730951198_child-video.txt](https://github.com/user-attachments/files/17655787/manifest_1730951198_child-video.txt)
[manifest_1730951203_child-video.txt](https://github.com/user-attachments/files/17655789/manifest_1730951203_child-video.txt)
[manifest_1730951208_child-video.txt](https://github.com/user-attachments/files/17655790/manifest_1730951208_child-video.txt)
[manifest_1730951213_child-video.txt](https://github.com/user-attachments/files/17655792/manifest_1730951213_child-video.txt)

Also in this case, removing the tags solves the problem...

**Comment by CastagnaIT** [comment]
these cases require more investigations

case 1: its missing VOD tag so assumed as LIVE, but there is a EXT-X-ENDLIST tag, its the first time that i see an HLS live video that end, i think has been never full tested, "live to vod" transitions has been always problematic case and could be cause of problems

case 2: crashes need to be investigated clearly something is not working correctly

i could provide a way to force disable parsing EXT-X-PROGRAM-DATE-TIME
but its not a solution, it just hide problems,
other users can open new issues about same problems

these are videos that i can play by myself if you provide a link/addon or other way also in PVT?
would make it much easier for me to debug and try to find a better solution, if im able, so to try avoid implementing a workaround to manually set a property to ignore EXT-X-PROGRAM-DATE-TIME

if not possible,
at least shoud be solved the crash, if so, i can provide some instructions to try get a debug dump crash log

**Comment by mtr81** [comment]
Thanks for the clarification!
