### ISSUE TITLE
[Bug] KODI 22 - PlutoTV Stream doesn't start anymore

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1723]
### Describe the problem

Hi @CastagnaIT  I discovered that the stream from DAZN Darts x PlutoTV cannot be started with the current Kodi 22. The error message immediately appears with an http 403 error. However, it can be started easily under Kodi 21. I use the IPTV Simple Client with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced"
My .m3u8 has the following structure:

`#EXTINF:-1 tvg-id="64b67f0424ade50008a3be17" group-title="Darts Live" tvg-logo="https://images.pluto.tv/channels/64b67f0424ade50008a3be17/colorLogoPNG.png",DAZN Darts x Pluto TV
#KODIPROP:inputstream.adaptive.manifest_config={"hls_ignore_endlist":true,"hls_fix_mediasequence":true,"hls_fix_discsequence":true}`
`https://jmp2.uk/plu-64b67f0424ade50008a3be17.m3u8`

### Steps to reproduce

1. Start Kodi 22
2. Play Stream: https://jmp2.uk/plu-64b67f0424ade50008a3be17.m3u8 with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debug log

[kodi_pluto_debug_K22.log](https://github.com/user-attachments/files/17678522/kodi_pluto_debug_K22.log)

### Operating system(s)

Android

### Operating system version(s)

LineageOS 21 based on Android 14 for Raspberry Pi 400

### InputStream Adaptive version(s)

ISA 22.1.9

### Kodi version(s)

22 ALPHA1

**Comment by CastagnaIT** [comment]
set a correct user-agent on iptvsimple settings

**Comment by werimail** [comment]
> set a correct user-agent on iptvsimple settings

Thanks @CastagnaIT  I knew there was something else... with the correct user agent in the settings it also works under Kodi22

Thanks and greetings Weri
