### ISSUE TITLE
Not play enigma2 player.

### ISSUE THREAD

**Issue by 68foxboris** [peak3d/inputstream.adaptive#173]
I collect kodi 17.6-krypton for arm v7. I added your plugin. It assembles and installs without errors. In the youtube plugin, when selecting a source, the MPD link appears. If I reproduce via the kodi video player, then playback is performed, but only 1080P.  If there is no playback through the internal player enigma2.
Do not tell me what you can do?
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/2210186/kodi.log)

**Comment by peak3d** [comment]
Not me, I have no clue what enigma2 player is, sry.

**Comment by dagwieers** [comment]
@peak3d No feedback, probably no longer relevant. Close it?
