### ISSUE TITLE
wvdecrypter_android.cpp error

### ISSUE THREAD

**Issue by drt420** [peak3d/inputstream.adaptive#174]
Hello
I am trying to build wvdecrypter_android.cpp and getting following error. Pls help me out how to resolve it/

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmediandk
collect2.exe: error: ld returned 1 exit status
```

**Comment by FloridaStream** [comment]
U need android ndk for compile android version.
@drt420 peak3d does not apology the decryption and download, I think it would not be nice you ask this here.
