### ISSUE TITLE
[Feature request] MPEG-DASH, periodic license requests

### ISSUE THREAD

**Issue by Frasknas** [peak3d/inputstream.adaptive#1741]
### Describe the feature

Hello.

This is related to the feature request #1736. That ticket was closed before I posted additional information. I thought maybe the ticket would be reopened but it appears it won't be so I am opening this one instead.

I am writing a plugin for kodi to play streams from a play site that uses https://www.maginepro.com/ as their backend.

The streams are mpeg-dash. I have not worked with those before and I can't get inputstream.adaptive to play them correctly.
The stream will start to play but after about a minute it crashes.

I notice that the web app I am trying to emulate is sending multiple license requests. The first one is sent when the stream is started. Then a new one is sent somewhere between a few seconds and up to two minutes after the initial request. After that it sends a new license request every 2 minutes as long as the stream is playing.

Since the life time of my stream is in the same ball park as the time until the web app sends the second license request my theory is that it dies because I am not sending these additional requests.

I had a look at the source code. I found that CSession::OnSegmentChanged is a suitable place to inject code to test my theory. But I failed to find a way to send a new license POST without also recreating the stream. Is it possible?

Thanks in advance.

### Motivation

I can't get the streams to work without it

### Are you willing to contribute in development?

Yes

### Should a possible backport be considered?

No

**Comment by CastagnaIT** [comment]
> I notice that the web app I am trying to emulate is sending multiple license requests. The first one is sent when the stream is started. Then a new one is sent somewhere between a few seconds and up to two minutes after the initial request. After that it sends a new license request every 2 minutes as long as the stream is playing.

this is a common behaviour of DRM Key Rotation method
where based on segments the pssh/kid change while in playback and if not available a new license may be required to continue decrypting data, its currently not supported on ISA and no ETA, there is already a feature request opened #1602

**Comment by CastagnaIT** [comment]
> I had a look at the source code. I found that CSession::OnSegmentChanged is a suitable place to inject code to test my theory.

could be not the right place, this should be done between FragmentedSampleReader and the decrypter(s) classes

**Comment by Frasknas** [comment]
OK. Thanks for your feedback. I will keep an eye out for updates to #1602 then.
