### ISSUE TITLE
inputstream.adaptive Krypton update

### ISSUE THREAD

**Issue by kodiultimate** [peak3d/inputstream.adaptive#177]
Guys,

maybe a silly question.
I'm currently on version 2.0.19
How do I updated to 2.0.20 please?
Thanks

**Comment by kodiultimate** [comment]
Just to mention

Installed freshly downloaded kodi 17.6 version still comes with 2.0.19
No updated from official kodi repo

**Comment by dagwieers** [comment]
@kodiultimate Is this issue still relevant? If not, please close it.
