### ISSUE TITLE
[MPD] Relative Base URLs Failing

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#178]
Using this MPD:
https://pastebin.com/J5tXMH83

The urls are being calculated as:
http://foxteldashlive01.akamaized.net/live/channel001/channel001_mcs.isml//live/channel001/channel001_mta.isml/dash/channel001_mta-textstream_eng=20000.dash

instead of
http://foxteldashlive01.akamaized.net/live/channel001/channel001_mta.isml/dash/channel001_mta-textstream_eng=20000.dash

Using latest nightly Windows x64 build.

Log is here:
https://pastebin.com/ymkffSiX

Note: In KODI 18 Beta & latest nightlies, this MPD caused KODI to crash

**Comment by nazofm** [comment]
any update on this one guys?

**Comment by matthuisman** [comment]
Note: In KODI 18 & nightlies, this MPD caused KODI to crash

**Comment by adamo331** [comment]
no chance with drm, it was also implemented on NBA league pass

**Comment by matthuisman** [comment]
@adamo331
What are you talking about?
Widevine protected streams can play fine using Inputstream

**Comment by adamo331** [comment]
> @adamo331
> What are you talking about?
> Widevine protected streams can play fine using Inputstream
> 
> This is an issue with baseurl and the urls being calculated in-correctly

But NBA games it is not working they use widevine and as i see many peoples they can't play it through kodi with paid nba league pass

**Comment by matthuisman** [comment]
@adamo331

That could be unrelated issue to this.
I have another add-on that play live streams (and ondemand) that use Widevine encryption just fine.

**Comment by adamo331** [comment]
> @adamo331
> 
> That could be unrelated issue to this.
> I have another add-on that play live streams (and ondemand) that use Widevine encryption just fine.

Hi
May i have your skype or email , want to discuss with direct

Thanks

**Comment by matthuisman** [comment]
@adamo331
No sorry.

You need to talk to the NBA add-on creator etc.
I can't help with add-ons that I don't make.

**Comment by glennguy** [comment]
I think I've identified the cause of this. In the mpd the BaseURL starts with a forward slash.
At https://github.com/peak3d/inputstream.adaptive/blob/master/src/parser/DASHTree.cpp#L1214 we have this: 
```c++
else if (dash->currentNode_ & MPDNODE_BASEURL) // Inside Period
      {
        if (strcmp(el, "BaseURL") == 0)
        {
          while (dash->strXMLText_.size() && (dash->strXMLText_[0] == '\n' || dash->strXMLText_[0] == '\r'))
            dash->strXMLText_.erase(dash->strXMLText_.begin());
          if (dash->strXMLText_.compare(0, 7, "http://") == 0
            || dash->strXMLText_.compare(0, 8, "https://") == 0)
            dash->current_period_->base_url_ = dash->strXMLText_;
          else
            dash->current_period_->base_url_ += dash->strXMLText_;
          dash->currentNode_ &= ~MPDNODE_BASEURL;
        }
}
```

`base_url_` is calculated in [PreparePaths](https://github.com/peak3d/inputstream.adaptive/blob/master/src/common/AdaptiveTree.cpp#L211) from the manifest url as `http://foxteldashlive01.akamaized.net/live/channel001/channel001_mcs.isml/` and as the BaseURL tag does not contain http or https the text gets appended, giving us ` http://foxteldashlive01.akamaized.net/live/channel001/channel001_mcs.isml//live/channel001` as the complete base url.

@matthuisman you have my email - if you're able to loan me some credentials I can test a fix and prepare a PR?

**Comment by matthuisman** [comment]
@glennguy 

They aren't my credentials (sent to me so I could build the add-on).
So, I have wipped up a quick webpage that will generate a test strm file for you on-the-fly.

I'll send you the link :)

**Comment by matthuisman** [comment]
@glennguy 

They aren't my credentials (sent to me so I could build the add-on).
So, I have wipped up a quick webpage that will generate a test strm file for you on-the-fly.

I've PM'd you the link on the KODI forums

**Comment by peak3d** [comment]
sorry, was not aware about this ticket....
https://github.com/peak3d/inputstream.adaptive/commit/5a7d53a5996510d2bf9adc3ffa6b40fa6f114bb7
should solve it

**Comment by matthuisman** [comment]
@peak3d 
Thanks for that :)
I'll test when next nightly comes out.

As for your question on the other issue about crashing..
That was in relation to this issue.
This MPD on Windows causes a hard crash ever since Beta 1.
In the Alphas it would attempt to play and I would see the wrong urls in the log.

**Comment by glennguy** [comment]
@peak3d using this mpd causes Kodi to crash.
[kodi_stacktrace-18.0-BETA5 Git_20181101-8f12995cac-20181102-110327.txt](https://github.com/peak3d/inputstream.adaptive/files/2540550/kodi_stacktrace-18.0-BETA5.Git_20181101-8f12995cac-20181102-110327.txt)
[kodi_crashlog-18.0-BETA5 Git_20181101-8f12995cac-20181102-110327.zip](https://github.com/peak3d/inputstream.adaptive/files/2540552/kodi_crashlog-18.0-BETA5.Git_20181101-8f12995cac-20181102-110327.zip)
@peak3d - @matthuisman could email you the link to the strm file? Australian IP address possibly needed to test.

**Comment by matthuisman** [comment]
@peak3d @glennguy 

Thank you both :)
I basically originally gave up when I struck the wrong urls being used.
Once I get a latest nightly with this fix in, I can investigate further :)
