### ISSUE TITLE
would it be possible to include some build/install instructions?

### ISSUE THREAD

**Issue by lozbrown** [peak3d/inputstream.adaptive#18]
With widespread coverage of the netflix plugin (of which this or at least its fork is a dependancy) and no clarity on when merges back to the kodi trunk are expected (and therefore apear in nightly builds), you'll likely find a lot of people like myself who see that as a feature just too good to wait until kodi 18 for so are trying to compile kodi-agile and the various dependencies. 

Would it be possible to include some build / install instructions for this in the readme, similar to 
https://github.com/FernetMenta/kodi-agile/tree/master/docs

**Comment by peak3d** [comment]
For netflix you should use github.com/liberty.developer/inputstream.adaptive.git

Compiling binary addons is different from os to os, and kodi team members already print lot of posts regarding this topic.

I know that it is not the simplest task, but if you google you'll lead e.g. at this post:
http://forum.kodi.tv/showthread.php?tid=219166

**Comment by rgainza** [comment]
Plz make a guide for this! No matter what I do this won't build on windows...

Tried this:

set ROOT=%CD%
git clone https://github.com/FernetMenta/kodi-agile
git clone https://github.com/liberty-developer/inputstream.adaptive -b agile
cd inputstream.adaptive
mkdir build
cd build
cmake -G "Visual Studio 14" -DADDONS_TO_BUILD=inputstream.adaptive -DCMAKE_BUILD_TYPE=Debug -DADDON_SRC_PREFIX=%ROOT% -DCMAKE_INSTALL_PREFIX=%ROOT%\kodi-agile\addons -DCMAKE_USER_MAKE_RULES_OVERRIDE=%ROOT%\kodi-agile\cmake\scripts\windows\CFlagOverrides.cmake -DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX=%ROOT%\kodi-agile\cmake\scripts\windows\CXXFlagOverrides.cmake -DPACKAGE_ZIP=1 %ROOT%\kodi-agile\cmake\addons
cmake --build . --config Debug

Tried this:

cd \kodi-agile\tools\buildsteps\windows\x64
bootstrap-addons.bat
Went to \kodi-agile\cmake\addons\addons\inputstream.adaptive
Edited the text so correct bransch would download:
inputstream.adaptive https://github.com/liberty-developer/inputstream.adaptive/ agile
back to \kodi-agile\tools\buildsteps\windows\x64
make-addons.bat addon (and yes I tried install as well) inputstream.adaptive

It always fails as soon as it starts building the addon itself! I really want to use this and build addons using this....

**Comment by peak3d** [comment]
@rgainza all necessary things are already mered into kodi mainline master.
There is no need to use any agile branch currently.

-> http://github.com/xbmc/xbmc -bmaster
-> http://github.com/peak3d/inputstream.adaptive -bmaster

build instructions for kodi and binary addons can be found everywhere.
I use folder "build" for kodi, and an "build-addons" for addons.
Maybe it would be a good idea to make in build the kodi cmake step : cmake -G "Visual Studio 14" ..

**Comment by rgainza** [comment]
Okay so the master branches can now be used for decrypting the MPEG-DASH streams such as Viaplay etc? I saw recently that Netflix upgraded their security as expected sadly... 

I'll try just building Kodi according to ur instructions itself then... I do not have such high hopes thou...

Plz believe me. I've tried so many things. The instructions that are everywhere must be insufficient and they're always done more for Linux which is way easier.

**Comment by rgainza** [comment]
Kodi master built fine. Noticed that it isn't possible to build your binary in x64 hence it isn't in the nightlies I presume?

I'm not happy with the end product. I was looking to decrypt Widevine DRM streams in Smoothstream and MPEG-DASH and it doesn't seem to work. The bransch u suggested doesn't even have the wvdecrypter included? I tried to compile it anyway and placed it on the correct folders (I think).

C:\Users\User\AppData\Roaming\Kodi\cdm
C:\Program Files (x86)\Kodi\addons\inputstream.adaptive\decrypter

And I copied the widevinecdm.dll to these folders as well. Are u sure I don't need Kodi Agile and your https://github.com/liberty-developer/inputstream.adaptive/ agile bransch?

**Comment by peak3d** [comment]
@rgainza you haven't told in your initial post that you're looking for decryption.
for decryption / libwidevine thing you have to use liberty-developer tree, correct.

After the 2 steps you already manged, go into wvdecrypter folder, mkdir build && cd build && cmake -G blabla ...
Then open sln, compile ssdwv.dll, and copy it maually to the desired place.

**Comment by rgainza** [comment]
I thought it was obvious seeing I wanted to build the agile bransch, my bad i guess..!

So just to be completely clear!

These are the steps:

- Build Kodi (xbmc master bransch) along with inputstream.adaptive (peak3d master bransch)
- Then git clone liberty-developer tree agile bransch and go into wvdecrypter folder and build ssdwv.dll
- Copy the dll to appdata/roaming/kodi/cdm and program/kodi/addons/inputstream.adaptive/decrypter
- Then I have to get the widevinecdm.dll (Google Chrome) and copy it as well to the folders above?
- Then the decryption should work just fine?

**Comment by peak3d** [comment]
For step 1: you dont need the peak3d inputstream.adaptive git, use both (inputstream.adaptive / wvdecrypter) from liberty-developer

The other points sound fine, pls. don't forget to activate inputstream.adaptive in kodi.

**Comment by rgainza** [comment]
Alright I'll try the liberty-developer master tree branch since the agile one wont compile.  Thanks for the answers!

**Comment by rgainza** [comment]
Building all done. No problem at all with the ssd_wv.dll. Copied all the dlls to the cdm folder and to decrypter folder to where the binary addon is placed. No luck!

Took the files from C:\Program Files (x86)\Google\Chrome\Application\59.0.3071.115\WidevineCdm\_platform_specific\win_x64

19:56:54.983 T:11056  NOTICE: Creating InputStream
19:56:55.213 T:11056   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\User\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
19:56:55.213 T:11056   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
19:56:55.214 T:11056   ERROR: CVideoPlayer::OpenInputStream - error opening ["randommpdurl"]
19:56:55.214 T:11056  NOTICE: CVideoPlayer::OnExit()

Just for trying the build out I used this addon https://github.com/emilsvennesson/kodi-cmore and it works fine in Linux... Any ideas why it cant open the shared library? Bad build?

**Comment by rgainza** [comment]
Never mind! It was all due to the Widevine being in 64-bit... Found 32-bit version. I guess this is because your binary addon cannot be built as 64-bit hence it cannot handle the dll yet. Thanks for the help!

**Comment by peak3d** [comment]
Close this because build instructions are inside kodi/docs/README.xxx files
