### ISSUE TITLE
Dazn Buffering

### ISSUE THREAD

**Issue by AlleSchonWeg** [peak3d/inputstream.adaptive#180]
Hi @peak3d 
i have an issue with dazn. It would be nice, if you can take a look. Logfile and description you can find at kodinerds: https://www.kodinerds.net/index.php/Thread/59078-DAZN-basierend-auf-Eurosport-Player/?postID=479922#post479922
Thank you!

**Comment by JinRonin** [comment]
Try with max speed 5 000 000 in inputstream adaptive. 
The pi3 might not be capable of playing 720p@6,5mbit

**Comment by AlleSchonWeg** [comment]
Hi @JinRonin 
Yesterday i was watching IndyCar with no buffering. Then i read you post and i looked at the kodi video info: 1280x720 25fps. I changed the max bandwith to 5 000 000 and play indycar again. Kodi video info: 1280x720 50fps and i had buffering. So i switched to wta tennis which had 1280x720 50fps and buffering too.
I changed max bandwith to 4 000 000 which this results:
Indycar: 1280x720 25fps no buffering
Tennis: 1280x720 25fps buffering

I restartet the tennis stream two or three times then i had no buffering (1280x720 25fps). Then i switched back to indycar (1280x720 25fps) with no problems to the end of the race. Almost 3 hours.

Are you sure that the rpi3 might not be capable of playing 720p@6,5 dazn stream? I have the problems since a week or so. Before this i'm pretty sure that i watched streams 1280x720 50fps.

**Comment by JinRonin** [comment]
Look at the cpu usage while streaming. If its too high you will have to lower the max bandwidth or even lower the max resolution to 480p.

**Comment by AlleSchonWeg** [comment]
If i turn debug on the kodi osd varies between 60-70% cpu (1280x720 50fps).
Today i reset max bandwidth and start a stream. Voila no buffering and 1280x720 50fps. So i created another logfile (see kodinerds) and the difference is, that inpustream used another host. I don't know if this is the culprit.

**Comment by JinRonin** [comment]
Yes it is. I will see if i add an option to manually select the cdn.

You can close this issue as its dazn related.

**Comment by AlleSchonWeg** [comment]
ok. thx @JinRonin 👍
