### ISSUE TITLE
fire tv crashes playing video

### ISSUE THREAD

**Issue by dontknowcris** [peak3d/inputstream.adaptive#182]
when I try to watch a football match on demand, the match starts without any problem, but after some minutes there's a buffering and the video freezes. if I try to stop the playback and going back to football matches list, then kodi crashes and goes back to the home of fire tv. and if I try to play again the same vod, the video always freezes at the same point then the previous one
same issue with live events (obviously in this case, the crash moment is different, depending on when I try to play a match)

here are the error logs
[kodilog1.txt](https://github.com/peak3d/inputstream.adaptive/files/2346292/kodilog1.txt)
[kodilog2.txt](https://github.com/peak3d/inputstream.adaptive/files/2346293/kodilog2.txt)

**Comment by dontknowcris** [comment]
hey peak3d, can you help us please?
there's the same error with 2.2.26

[kodilog3.txt](https://github.com/peak3d/inputstream.adaptive/files/2347997/kodilog3.txt)

**Comment by peak3d** [comment]
1.) Navigate to the video
2.) adb logcat -c
3.) let the video play until the errors occur
4.) adb logcat -d | pastebinit

**Comment by peak3d** [comment]
From what I read in the logs, there seem to be an audio issue.
To verify, pls. set Media to "Video" in inputstream.adaptive settings and play again.

**Comment by dontknowcris** [comment]
with that setting, video freezes the same, but this time kodi doesn't crash and remains open
[DebugNoAudio.txt](https://github.com/peak3d/inputstream.adaptive/files/2348900/DebugNoAudio.txt)

**Comment by peak3d** [comment]
The error shown is an error in android NDK. Many things have been fixed until 5.1, so unfortunately I cannot help further.

Simply use the oficial app from dazn, or upgrade your device.
