### ISSUE TITLE
Error in KODI 17.6

### ISSUE THREAD

**Issue by hitam4450** [peak3d/inputstream.adaptive#189]
Cannot install in Kodi 17.6 (ANDROID)

regards, hitam4450

**Comment by basrieter** [comment]
You only need to enable it in the add-on configuration. It should already be there in 17.6

**Comment by hitam4450** [comment]
We, thanks for your answer. However, "How-To-Enable" in the add-on configuration ???

Please advise!

Thank you in advance

**Comment by basrieter** [comment]
Go to the add-on browser within Kodi. Go to "my add-ons" and find the adaptive stream add-on in the VideoPlayer Input Stream folder.

**Comment by hitam4450** [comment]
THanks for your advice! I reay appreciate your help. I ony found versi 2.2.20.

However SkY Go asks for a version update 2.2.27.

I downloaded the master from this website, however it could not be installed . 
KODI on UBUNTU 18.04,  KODI on ANDROID and KODI on UBUNTU 16.04  all trials were unsuccessful!

**Comment by basrieter** [comment]
It won't work with Krypton. You will need Leia beta.

**Comment by htot** [comment]
For some reason in Add-ons/My add-ons I don't have a Videoplayer Input Stream folder. Closest match is Video add-ons. Where do I find it exactly?

**Comment by htot** [comment]
Ah, those packages are not built by Ubuntu. Resolved this by installing Kodi from the ppa.

**Comment by dagwieers** [comment]
@peak3d Can you please close this issue?
