### ISSUE TITLE
[NOT AN ISSUE] Version Progress Request

### ISSUE THREAD

**Issue by dontknowcris** [peak3d/inputstream.adaptive#190]
Hey @peak3d. 
Can you please change version number in 2.2.27-2 or 2.2.28 in order to force the upgrade on kodi nightly ppa by its maintainer? in that ppa inputstream is "2.2.27-1~bionic" dated 2018-09-09 and Wolfgang Schupp is not updating to the latest commits, so some addons, like netflix, do not work properly on linux. instead on windows they work correctly
Schupp did not realize that the addon needs to be recompiled

**Comment by JinRonin** [comment]
Can confirm that the latest changes are not included.
Did you address this to wnipex, dontknowcris?

**Comment by dontknowcris** [comment]
No, I did not

**Comment by dontknowcris** [comment]
Thank you @JinRonin

**Comment by peak3d** [comment]
Version bump is required because we discussed this internally.
Version is bumped now (2.2.28)

**Comment by dagwieers** [comment]
Is this still an issue ? I think we can close this one.

**Comment by dagwieers** [comment]
@peak3d Can you please close this issue?
