### ISSUE TITLE
[Feature Request] Pass mpd URL custom headers to actual video files?

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#20]
I have a .strm file like this:

```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://wvlic.brightcove.com/proxy/5375730767001|Content-Type=application%2Fx-www-form-urlencoded&X-Forwarded-For=202.89.4.222|A{SSM}|
http://dashtvnz-a.akamaihd.net/963482467001/963482467001_5375755467001_5375730767001.mpd?pubId=963482467001&videoId=5375730767001|X-Forwarded-For=202.89.4.222
```

For a GEO blocked service.

Here's the log:
https://pastebin.com/raw/T8jsHLXV

You can see it get's the license all OK etc.
However, it fails to open http://dashtvnz-a.akamaihd.net/963482467001/5375755266001/video/1/init.mp4

This will be due to CURL not setting the X-Forwarded-For (it only sets keep alive)

Would it be possible to update the code to pass on any custom stream headers to the actual video files?

I guess somewhere around here it would happen:
https://github.com/peak3d/inputstream.adaptive/blob/master/src/main.cpp#L217

**Comment by matthuisman** [comment]
Possibly it could be an extra Addon Setting if that's easier to implement?
"Extra Headers" or something like that?
Then that download function just appends |{headers} to the end of the initial URL string?
`
xbmc->CURLCreate(url +  "|" + xbmc->GetSetting("EXTRAHEADERS", (char*)&buf));`

Pretty sure the CurlCreate takes care of splitting the string on | and parsing the headers?

**Comment by matthuisman** [comment]
The downside to above is that add-ons like the one I write won't be able to set the extra headers.

**Comment by glennguy** [comment]
It seems to be able to do this already, I think you need to URL encode the string properly - '&' should be '%2F'.  i.e 
```
#KODIPROP:inputstream.adaptive.license_key=https://wvlic.brightcove.com/proxy/5375730767001|Content-Type=application%2Fx-www-form-urlencoded%2FX-Forwarded-For=202.89.4.222|A{SSM}|
```

**Comment by matthuisman** [comment]
That's not quite the issue (the license key actually works fine)

The issue is that the X-Forwarded-For at the end of the MPD URL is not passed onto the actual video (mp4) files.

1) The code fetches the MPD file correctly using the X-Forward
2) The code get's the actual video files from the MPD file (eg. init.mp4)
3) The code does not add X-Forward when requesting these video files

**Comment by glennguy** [comment]
@matthuisman my bad, I did a pretty bad job of reading your first post.

I've made a fix that pretty much follows your suggestion of storing the headers in a variable and append them to segment downloads. It works for your strm file. It's an easy but probably not ideal implementation. I'll make a PR.

**Comment by matthuisman** [comment]
@glennguy 
You are a LEGEND!

You could also append the X-Forward headers in your Aussie add-ons so us Kiwis can use them :)

**Comment by matthuisman** [comment]
Going to close this issue and continue convo on pull request :)
