### ISSUE TITLE
DASH Stream not working License update not successful (no keys)

### ISSUE THREAD

**Issue by GianniDPC** [peak3d/inputstream.adaptive#200]
I'm trying to create a Kodi app from a Belgium live TV app called Yelo Play.

I did some digging with Fiddler and tried to recreate the requests in Python to acquire the required keys, but I am stuck feeding the license key to the plugin.

I have a long key 10936 characters long I have to POST to this address https://lwvdrm.yelo.prd.telenet-ops.be/WvLicenseProxy, this key is static for the moment as I still don't know how this key is generated, but atleast it keeps working for some time.

This request returns the following:
`{"license": "CAISigIKKgoQj/Y9IpQ/JSP7b46vmiHUVBIQj/Y9IpQ/JSP7b46vmiHUVBoAIAEoABIKCAEQARgBMICjBRpmEhAY3H9hD3TZ1XVq6FeBQ9+lGlC9Lbn1Ahed9+YkWPEYVsMRiHkZrHdiQ9KP2TkgaFLfh7QQyLN2cRL5GA3MWnbrv6+2nJRui/D/bnXQFNbgyfdWYRJGtmgkB1/dQVv4AfVfvSABGkwKEFjBHyA5lE0VlQs584t+OiMSEF9Doi45j9zswOQVYL27fX4aINUVJcyAYiVoiDruFaD2pTe8RTnhZPCfQQC8sgphBJpgIAIoAWIAIKjz3N4FMhDkLMoFeHJJNrHMkpoCUAvTOABQAhogZTcWcLUGo8fhVgxrVn5IoKJWF4MQmWPeCfzfBcxeRSsigAKFzIU2UAS2kc0rzvN+xA77updIoHJpsr5zi5SrLIxuXxOB02FNCMAooZ8sdlIV0IlI1xWWqG5gc4FV/WVWUxGYzX7yL73s0snlLwJbCwff6WJMUr7kfoaRIrEBKf4VE21E4pfmcQ3y/j4NcS9pzefDdkjZCj5oTaQUYnQtuFxxYtYHSLAh/r8ZrYsEM7MaZuhwwlYm2uhjjdZ6ck5sjq0YkOKWEUiTbgysEKN3v4ywAEIIEhP+Zd+0r9srrJGVEPHfYmENsiKAGZnzBLrqBh0KcmTh0BfPjO+hzbzIxYT94A4Tzh5hsCKbAvfZwCd9Gi2hZ6TWxen6jnROEQl9iOyE"}`

Now I have two problems, I don't know how I can append the long key to the body to do the post request, as kodi will then see my .strm file as a folder with multiple files.

Anyway I tried recreating my own license server by using Flask and made it possible to do POST requests to it, if I do a POST request it returns me the JSON string as you can see in the above code block.

But the stream doesn't play, and if I look into the Kodi log it tells me: "License update not successful (no keys)" I don't know why it would say that as I can definitely see the JSON string in the RESPONSE file located in Kodi/cdm.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/2526842/kodi.log)
[stream_file.txt](https://github.com/peak3d/inputstream.adaptive/files/2526846/stream_file.txt)

**Comment by GianniDPC** [comment]
Nobody?

I did some further investigation and I understand that 'b{SSM}' is the base64NonURLencoded widevine payload.

My current problem is that the request to the server is fully base64encoded.

I decoded the string send to the server and it looks something like this.
`{
        "LatensRegistration": {
            "CustomerName": [removed],
            "AccountName": "PlayReadyAccount",
            "PortalId": [removed],",
            "FriendlyName": "THEOPlayer",
            "DeviceInfo": {
                "FormatVersion": "1",
                "DeviceType": "PC",
                "OSType": "Win32",
                "OSVersion": "Windows NT 10.0; Win64; x64",
                "DRMProvider": "Google",
                "DRMVersion": "1.4.8.86",
                "DRMType": "Widevine",
                "DeviceVendor": "",
                "DeviceModel": ""
            }
        },
        "Payload": [widevine challenge here],
        "alg": "HS256"
    }`

So I need to insert the challenge is this dictionary and then base64encode it again to send it to the server. But when I create a function for ex. base64.b64encode(create_packet(customerName, portalId, vw_Challenge)) and insert 'b{SSM}' as the 3rd argument it evaluates as 'b{SSM}' when I decode it again instead of the widevine challenge.

How can I solve this? any help is appreciated!

**Comment by FloridaStream** [comment]
@GianniDPC Did you close the issue because you solved the problem? What is the cause of the problem? Could you share?

**Comment by GianniDPC** [comment]
> @GianniDPC Did you close the issue because you solved the problem? What is the cause of the problem? Could you share?

The request was base64encoded with a base64encoded widevine challenge inside the payload field. 

So @peak3d introduced the possibility of wrapping the request with b{} or B{} difference between the two is, is that the second one does urlencoding and the first one doesn't so it depends on what you need.

Here is an example:
`'b{' + widevine_payload_package(device_Id, customer_Id, "b{SSM}") + '}'`

Ofcourse the above is going to be different depending on the request you need to send to the license server.

Also you'll see some new commits were pushed today, some have to do with the problem I was having. The KID was not being reused for audio so I was having a weird second request to the license server but by reusing the KID (if I'm not mistaken) I was able to get the stream to play.

**Comment by GianniDPC** [comment]
> @peak3d Thks for this possibility ;-)
> @GianniDPC Thanks for all your explanations. It's now 2 years that I'm trying (when I have some time, the big problem :-) ) to have something working for yelo in kodi without any success.
> Could you please share me by any way your current setup/implementation? It would be very appreciated 👍

Will release a beta version soon, it works but I'd like to add some features and I have limited time to do so atm.
