### ISSUE TITLE
h264 Hardware decoding?

### ISSUE THREAD

**Issue by satmandu** [peak3d/inputstream.adaptive#207]
I'm using this through caphm's netflix plugin version from here: https://github.com/asciidisco/plugin.video.netflix/pull/519

I'm able to play video but decoding appears to be software using inputstream.adaptive when other local h264 videos play using ff-h264-vaapi.

Is there a way to change this?

Debug log:
http://paste.ubuntu.com/p/ZxQbWqcY7V/

**Comment by satmandu** [comment]
Ah, so I think I found the answer for this from here:
https://github.com/truedread/netflix-1080p/issues/15#issuecomment-398256248

> Netflix uses Widevine DRM on Chrome, and with the license policy they have set (SW_SECURE_DECODE), the Widevine library decodes the frames rather than the CPU/GPU decoding the frames. As such, the frames are decoded without any sort of hardware acceleration, meaning on lower end computers, there will be frame drops. This is actually the reason Netflix only lets ChromeOS play 1080p with Chrome, because ChromeOS has hardware Widevine DRM, meaning Widevine can actually decode the frames through hardware acceleration, and as such there would be no frame drops.

So we would need the ChromeOS Widevine to work to get hardware decoding it seems. :/

**Comment by bam80** [comment]
It's interesting how it's done in ChromeOS. Can we borrow some blobs maybe for make it possible on normal linux?
