### ISSUE TITLE
[Bug] License related custom (non-standard) headers ignored by kodi

### ISSUE THREAD

**Issue by libqtc** [peak3d/inputstream.adaptive#21]
Hello,

I am currently trying to reproduce using the Kodi, inpustream.adaptive, widevine lib and a file.strm the following video:

-Big Buck Bunny (3rd video - mpd format) from the page https://demo.castlabs.com

This video is a demo of a DRM company so I think we can use it here.

Using Burp Proxy I checked that it use a base64 encoded header with some parameters.
Probably that's the reason that the license aquisition is failing in kodi.log (with an http error status code)

Is this video (that needs that parameters) compatible with the currently version of inputstream.adaptive? If yes, can you show me an exemple of a .strm file for this video?

Best regards,
libqtc

**Comment by libqtc** [comment]
I think I found the problem. It looks like kodi ignores non-standard headers like `dt-custom-data` header.

https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L860

For this reason, license acquisition fails.

Below is an excerpt from a log:

> DEBUG: ------ Window Init (DialogBusy.xml) ------
> DEBUG: AddOnLog: InputStream Adaptive: CDMMessage: 1 arrived!
> DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Expect: '
> DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Origin: https://demo.castlabs.com'
> DEBUG: CurlFile::ParseAndCorrectUrl() ignoring header option 'dt-custom-data: [DATA HIDDEN]'
> DEBUG: CurlFile::Open(0D705F60) https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/
> INFO: XCURL::DllLibCurlGlobal::easy_aquire - Created session to https://lic.staging.drmtoday.com
> ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 412

**Headers to whitelist:**
DRMtoday by castLabs: `dt-custom-data`
BuyDRM/KeyOS: `customdata`
Note: Possibly there are other providers using different headers.

Can this problem be solved with a new version of inputstream.adaptive or a new kodi build will be needed?

**Comment by peak3d** [comment]
Hi, this is an issue inside kodi I'll try to remove the restiction again.
In the kodi-agile working fork its already removed / changed, there are chances to get it into kodi

**Comment by peak3d** [comment]
kodi issue
