### ISSUE TITLE
Error regarding missing dependency kodi.binary.instance.inputstream, when upgrading from 2.2.25 to 2.3.11

### ISSUE THREAD

**Issue by sorin-pop** [peak3d/inputstream.adaptive#211]
Hi,

I am running Kodi 18 beta LibreELEC-RPi2.arm-9.0-Milhouse-20181123210219-#1123-gcf48bb0.tar on a Raspberry Pi 3.

I have InputStream Adaptive add-on version 2.2.5 installed. I would like to update it to the latest version, because I am facing https://github.com/asciidisco/plugin.video.netflix/issues/542, and upgrading this addon is one of the tips there.

So I click Update, and in the popup with the two versions (2.3.11.0 or 2.3.6.0) I choose 2.3.11.0. The installation fails with 

> The dependency on kodi.binary.instance.inputstream version 2.0.8 could not be satisfied.

Here is the full debug log: https://paste.kodi.tv/iwetabupuj

I guess the relevant part is:

14:02:14.197 T:1939288864   DEBUG: CAddonInstaller: installing 'inputstream.adaptive' version '2.3.11.0' from repository 'repository.libreelec.tv'
14:02:14.216 T:1809818480   DEBUG: CAddonInstallJob[inputstream.adaptive]: requires kodi.binary.instance.inputstream version 2.0.8 which is not available
14:02:14.218 T:1809818480   ERROR: CAddonInstallJob[inputstream.adaptive]: The dependency on kodi.binary.instance.inputstream version 2.0.8 could not be satisfied.

But I don't really understand it, I don't know what this kodi.binary.instance.inputstream is, and what I could do to solve this.

Any help would be much appreciated.

Thanks.

**Comment by Scoub0** [comment]
Hi,
Exactly the same issue for me.
Any help will be much appreciated :)

**Comment by Scoub0** [comment]
I solved the issue with a manual update of the last LibreELEC version (v8.90.009). After that, the update of InputStream Adaptive works well (2.3.11.0) and i have subtitles available again in Netflix addon.

**Comment by sorin-pop** [comment]
Hi @Scoub0 , thanks for sharing that, I will try it out.

By manual update, do you mean the method below? (taken from https://libreelec.tv/2018/12/libreelec-leia-v8-90-009-alpha/)

> LibreELEC 9.0 Alpha 009 (Kodi 18 RC2)

> To update an existing installation from within the Kodi GUI select manual update in the LibreELEC settings add-on and then check for updates; select the LibreELEC 9.0 channel and then the 8.90.009 release.

**Comment by Scoub0** [comment]
Hi @sorin-pop yes, exactly.

**Comment by sorin-pop** [comment]
It looks like this worked for me as well. Thanks again!

**Comment by bvujica** [comment]
hi
i'm trying to update inputstream adaptive from 2.2x to 2.3.11 and every time i get the same error
21:27:43.985 T:1790964592 ERROR: Requested path http://addons.libreelec.tv/9.0/RPi2/arm/inputstream.adaptive/inputstream.adaptive-2.3.11.0.zip not found in known repository directories

When try to install from from zip i get this
21:20:19.321 T:1937518608 ERROR: Failed to read 'zip://%2fstorage%2finputstream.adaptive-2.3.11.zip/inputstream.adaptive-2.3.11/addon.xml'
21:20:37.286 T:1937518608 ERROR: Failed to read

any solution?

Kodi 18rc2

thanks

**Comment by basrieter** [comment]
I think this a repository problem for libreelec?
