### ISSUE TITLE
Widevine autoinstall hangs without error

### ISSUE THREAD

**Issue by mivalsten** [peak3d/inputstream.adaptive#216]
Hi,
I try to launch netflix addon on RPi3, but it fails on widevine installation. I accept eula, get notified about size and need of parted/fdisk (present), then loading icon shows and nothing happens. I left system running overnight. There is no information in log, I don't know what else can I provide.
Kodi 18 RC1
inputstream.adaptive v 2.3.11

Best Regards

**Comment by basrieter** [comment]
This is not related to the InputStream Adaptive add-on itself but to the Netflix add-on or the InputStream Adaptive Helper add-on. So you are at the wrong place.

**Comment by mivalsten** [comment]
Thank you @basrieter 
In case anyone stumbles upon this issue, I found the answer here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/26 My issue was with json config file missing.
