### ISSUE TITLE
Failed to install from zip

### ISSUE THREAD

**Issue by darrenclimienewman** [peak3d/inputstream.adaptive#22]
hi

im struggling to get the inputstream addon to install from the zip file, i assume its because i dont have some dependencies installed. ive downloaded the kodinerds repository, but i cant seem to find the addon in the repo either?

please help, i need this to run Amazon VOD through Kodi and not a browser!

thanks

**Comment by darrenclimienewman** [comment]
You can close this, now sorted!

**Comment by KodiNewbie** [comment]
+1 Unbale to install. JSONJPP error plus
`CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindKodi.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Kodi", but
  CMake did not find one.

  Could not find a package configuration file provided by "Kodi" with any of
  the following names:

    KodiConfig.cmake
    kodi-config.cmake

  Add the installation prefix of "Kodi" to CMAKE_PREFIX_PATH or set
  "Kodi_DIR" to a directory containing one of the above files.  If "Kodi"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!`

**Comment by rasmussjoberg89** [comment]
can't install inputstream.adaptive from zip file on kodi 17.6 at ASUSTOR NAS , some help plz
