### ISSUE TITLE
[HLS] Redirected master.m3u8 causes playback failure (due to key uri)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#222]
Similar to issue: https://github.com/peak3d/inputstream.adaptive/issues/158

http://i.mjh.nz/au/Sydney/tv.101204200424/m.m3u8 
redirects to
https://9now-live.akamaized.net/hls/live/708945/life-syd/master.m3u8

IA gets the relative sub-stream OK: 
https://9now-live.akamaized.net/hls/live/708945/life-syd/master2.m3u8

However, this substream has AES-128 and a relative key URL.
#EXT-X-KEY:METHOD=AES-128,URI="K836400.key",IV=0x0000000000000000000000000007550F

Inputstream then trys to fetch the key from:
http://i.mjh.nz/au/Sydney/tv.101204200424/K836400.key
instead of the correct
https://9now-live.akamaized.net/hls/live/708945/life-syd/K836400.key

Debug log:
https://pastebin.com/RJ0vb6fi

[master.txt](https://github.com/peak3d/inputstream.adaptive/files/2862251/master.txt)
[master2.txt](https://github.com/peak3d/inputstream.adaptive/files/2862252/master2.txt)

**Comment by matthuisman** [comment]
@peak3d 
Are you able to take a quick peak at this?

**Comment by peak3d** [comment]
Sure, but could be weekend....

**Comment by peak3d** [comment]
@matthuisman can you pls. verify: https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/effective/1/artifacts

**Comment by matthuisman** [comment]
@peak3d 
Works perfectly :)

Here is debug log of the above stream now working:
https://pastebin.com/raw/NRrF4FJE

Also tested many other streams and confirmed none of them have been broken.

**Comment by matthuisman** [comment]
Fixed with https://github.com/peak3d/inputstream.adaptive/commit/b76c81fc4c2d7fd02e73c1d0091ae190351fc2fa#diff-b1c1970c522912d9e60f050dc96ae695
