### ISSUE TITLE
Inputstream fails to parse KID from MPD

### ISSUE THREAD

**Issue by fayer3** [peak3d/inputstream.adaptive#223]
given the following mpd (https://gist.github.com/fayer3/b3d9b12ef0ae852346edfa201cdadb35),  the inputstream addon fails to parse the KID from the following
`<ContentProtection xmlns:cenc="urn:mpeg:cenc:2013" schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" cenc:default_KID="8cf125e7-7bf7-8057-60c4-e13c482e8bcb">`

**Comment by peak3d** [comment]
Fixed with https://github.com/peak3d/inputstream.adaptive/commit/1367f3b278c769fa980a161704a796eb900068d5

Will be merged / released soon into Leia branch
