### ISSUE TITLE
WebVTT subtitle does not decode HTML entities

### ISSUE THREAD

**Issue by dagwieers** [peak3d/inputstream.adaptive#224]
When watching an episode with subtitles I noticed that the subtitles contained HTML entities like **&amp;amp;** or **&amp;quot;**. I opened a ticket with the Netflix addon, and one for Kodi to realise that the issue is in fact in inputstream.adaptive.

References:
- https://github.com/asciidisco/plugin.video.netflix/issues/621
- https://github.com/xbmc/xbmc/issues/15365
- https://bitbucket.org/basrieter/xbmc-online-tv/issues/1011/npo-ondertitels-decode

**Comment by dagwieers** [comment]
From the WebVTT standard it is clear that HTML entities are allowed (and a common way to display or escape certain characters). See https://www.w3.org/TR/webvtt1/#example-4a66a3ef especially where `&lrm;` is mentioned, but the document is littered with more specific examples.

So we have to support this correctly in our WebVTT implementation.

**Comment by dagwieers** [comment]
@peak3d It appears this is now fixed with #366. Please review and close if appropriate.

**Comment by Essam311** [comment]
@dagwieers Your issue not fixed with https://github.com/peak3d/inputstream.adaptive/pull/366, your issue fixed with https://github.com/xbmc/xbmc/pull/17085 but it needs to be merged in Kodi.
