### ISSUE TITLE
No Audio on particular stream (Windows & Linux)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#225]
I have found that I get no audio on Windows KODI 18 on that same troublesome stream.
Also, no audio in latest  LibreElec on Pi3.

KODI 18 Android works fine though.

![52031118-cf452400-257f-11e9-8c09-4ae319a0e428](https://user-images.githubusercontent.com/6225961/52080170-0b1dcf00-25fc-11e9-89e8-190ed3ef1f94.png)

To get a better debug log, I switched Inputstream to Audio only.
Played one of the good streams and then played the stream that fails.

I will email @peak3d the needed files to debug :)

**Comment by matthuisman** [comment]
Hi @peak3d 

Are we able to have a look into this?
I emailed you the files a while back but can easily email again if need-be.

Appears to be an issue on Windows & Linux now

**Comment by peak3d** [comment]
@matthuisman can you pls. provide mpd, init of video AND init of audio of one not working stream? Thx!

**Comment by peak3d** [comment]
@matthuisman nvm, found the issue

**Comment by peak3d** [comment]
@matthuisman pls. try this one: https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/56/artifacts

**Comment by matthuisman** [comment]
@peak3d 

Perfect!
Tested working in Windows.
Also tried a bunch of other Widevine content and all still working.

Your the best!

**Comment by matthuisman** [comment]
@peak3d 
What was the commit to fix this?
Was it latest in master? 5c9c7f2b74e0b3df0f24f51eab669b42ed6a05ed ?
Or not in master yet?

**Comment by matthuisman** [comment]
I just tried 2.3.17 and it's fixed.
So assume 5c9c7f2b74e0b3df0f24f51eab669b42ed6a05ed was the issue that is now fixed :)
Closing
