### ISSUE TITLE
Initiate inputstream.adaptive stram playback via JSON-RPC

### ISSUE THREAD

**Issue by reinisb** [peak3d/inputstream.adaptive#227]
Hey!

I've been using inputstream.adaptive both via .strm file and via a custom addon. It works perfectly fine in both ways so thanks a lot for the work - I really appreciate it! That being said, I also often like to play streams by sending a GET request to Kodi's JSON-RPC. Below is an example request query param value, which starts playback of the provided stream URL without using inputstream.adaptive Is there any way I could extend the request with instructions so that Kodi would use inputstream.adaptive for the playback?

Thanks!

`{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"Player.Open",
  "params":{
        "item":{
              "file":"https://www.example.com/stream.m3u8"
                }
            }
}`

**Comment by peak3d** [comment]
Pls. report this feature request in forum.kodi tv, thx!
