### ISSUE TITLE
Android TV Widevine CryptoSession getKeyRequest failed!

### ISSUE THREAD

**Issue by Vitocorl** [peak3d/inputstream.adaptive#228]
I have and Android tv device, Kodi 18 final and Netflix addon is not starting, giving me "Widevine CryptoSession getKeyRequest failed!"

My full debug log is here: https://hastebin.com/agoyixoduh.sql

**Comment by peak3d** [comment]
Could be that your device is not yet provisioned.
Has your device played any widevine drm protected content before?

**Comment by Vitocorl** [comment]
I am installing this also to Xiaomi Mibox S, which is certified for Netflix and i get the same error... The common thing of these 2 boxes is Android TV 8.1. I have installed the plugin to another box, Android 7 (no Android TV) and Netflix works normally, no Widevine errors. If it helps, i will also upload a log from Xiaomi MiBox S...

**Comment by rkkoszewski** [comment]
I have the same issue, also on a Xiaomi Mi Box S (Android 8.1 with Widevine Support with Security Level L1). Native Netflix app works without any issues. Is there any way to debug this somehow to get to the root cause of this?

**Comment by Vitocorl** [comment]
I did a fresh Kodi install in Xiaomi Mibox S, however, inputstream.adaptive cannot upgrade to 2.3.15, it stays to 2.3.14 and reports no other update is available... I also installed Netflix 0.14.0 beta20 and i have the same Widevine errors, here is my latest log: https://hastebin.com/cowahodanu.sql

**Comment by sebnutt** [comment]
Same issue here on Xiaomi Mi Box S. Netflix 0.14.0 beta20 installed with same exception thrown.

**Comment by peak3d** [comment]
Try setting https://github.com/caphm/plugin.video.netflix/blob/release/0.14.0/resources/lib/services/msl/request_builder.py#L19 to 100 instead 18, this disables widevine key xchange

**Comment by Vitocorl** [comment]
Ok, i will try it when i'm home later in the evening and report back, thanks again for the help.

**Comment by sebnutt** [comment]
@peak3d I'll give it a try tonight as well. Thx

**Comment by Vitocorl** [comment]
I modified the request_builder.py line 19 to 100 instead of 18, the result was a different error, my new Kodi log is: https://hastebin.com/ayexunewix.sql

**Comment by peak3d** [comment]
@Vitocorl how does your original netflix ESN starts with (from netflix app) ?

**Comment by Vitocorl** [comment]
No i havent logged out, i did not know about msl-data.json, i will delete it now and report

**Comment by peak3d** [comment]
/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/msl_data.json

**Comment by Vitocorl** [comment]
It is very odd, there is no such file in .kodi/userdata/addon_data/plugin.video.netflix/
Where can i upload a picture for you to see which file are in this folder?

**Comment by peak3d** [comment]
@Vitocorl :
`adb shell rm /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/msl_data.json`

**Comment by Vitocorl** [comment]
Ok, trying asap

**Comment by Vitocorl** [comment]
No such file or directory...

**Comment by peak3d** [comment]
Ok, thx, then, how does your ESN looks like (from original netfix app)

**Comment by Vitocorl** [comment]
NFANDROID2-PRV-XIAOMMIBOX4-8340-{AND A VERY LARGE STRING OF NUMBERS}

**Comment by peak3d** [comment]
Can you pls  insert this esn (at least this part: NFANDROID2-PRV-XIAOMMIBOX4-8340) into the netflix esn edit field?

**Comment by Vitocorl** [comment]
I have already done that, all the trials i have made was with the ESN from the original app, just yesterday i uninstalled netflix and tried with the auto-found ESN. I will copy it again into settings.xml and let you know in a minute.

**Comment by Vitocorl** [comment]
It throws the same error... https://hastebin.com/onamiqadak.sql

**Comment by peak3d** [comment]
seems that your 18 -> 100 change has gone

**Comment by Vitocorl** [comment]
Ops, sorry, i changed it back, here is the log: https://hastebin.com/sipeqaxako.sql

**Comment by peak3d** [comment]
Ok, seems that we have to focus on MediaDRM CryptoSession
You can revert all the changes, I'll try to provide a version with more logging, but not tonight.

**Comment by Vitocorl** [comment]
Ok, thanks again, i will try to help any way that i can.

**Comment by Vitocorl** [comment]
Ok, thanks again, i will try to help any way that i can.

**Comment by peak3d** [comment]
@Vitocorl  can you pls save this content in a .strm file and play in kodi?

```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://proxy.uat.widevine.com/proxy?video_id=48fcc369939ac96c&provider=widevine_test||R{SSM}|
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd
```
And send me a debug kodi log afterwards?

**Comment by Vitocorl** [comment]
Sorry, just seen your message, stream plays fine, here's the log: https://hastebin.com/xobegirori.sql

**Comment by peak3d** [comment]
Are you now able to play netfilx (after kodi restart) ?

**Comment by Vitocorl** [comment]
Yes! that did it! Netflix plays fine no errors no nothing! You fixed it with this provisioning stream!

**Comment by peak3d** [comment]
@sebnutt pls don't play the strm file and wait for me to provide a fix. Thx

**Comment by sebnutt** [comment]
I unfortunately already did it. With no further success. I will fait for the fix. 
Should i then reinstall the whole stuff ?

**Comment by peak3d** [comment]
@sebnutt then you most lkely have an other issue, pls. provide debug log.

**Comment by sebnutt** [comment]
Strange bzhavior : i can't play purchased movies on youtbe addon either. No error mess, vidéo ont strating

**Comment by peak3d** [comment]
@sebnutt pls. don't provide more off-topic issues here. I have no cristal ball and already asked for the dubug log to focus on initial issue.

**Comment by sebnutt** [comment]
Sure i'll focus on this bug n'y provising the début log

**Comment by peak3d** [comment]
@Vitocorl is your device quite new and you would consider making a factory reset if my fix is implemented?

**Comment by Vitocorl** [comment]
@peak3d 
Of course, i do not mind resetting it, it is very easy for me to set it up again...

**Comment by peak3d** [comment]
@Vitocorl cool, the build is currently running here: https://github.com/xbmc/xbmc/pull/15553
If it is successfully build, you'll find apk's when clicking on the jenkins build details.

**Comment by Vitocorl** [comment]
Ok, but we will have to wait 5-6 hours until i get home from work... 
You lost me with the instructions there... 
1. The Kodi build i have to download and try is thishttps://github.com/xbmc/xbmc ? or is it not build yet and i have to wait? 
2. Stock Kodi, you mean just the above build, with Netflix so we can recreate the widevine error?

Sorry for all these questions, but i have to be sure for what to install in order to help...

**Comment by peak3d** [comment]
- factory reset the device
- install kodi version you used yesterday (release? nightly?)
- enable debug log, install netflix addon, insert credentials
- make sure that netflix fails to play (CryptoSession error)
- install the kodi apk from PR (I'll post the link later)
- launch the new kodi version, and provide the debug log.

**Comment by Vitocorl** [comment]
Ok, thanks for the clarifications, i will follow your instructions and provide the log later on in the evening.

**Comment by sebnutt** [comment]
@peak3d I'll perform the same sequence when I'm home, hoping this will help.

Wouldn't it be worth first launching native Netflix app to initialize DRM provisioning as you [previously](https://github.com/peak3d/inputstream.adaptive/issues/228#issuecomment-461794880) mentioned ?

**Comment by peak3d** [comment]
@Vitocorl please don't, because then the new verification workflow can not be verified.

**Comment by Vitocorl** [comment]
Ok, i would not anyway, since we did not say i needed to do this.

**Comment by Vitocorl** [comment]
The link does not work for me, it reports not found

**Comment by peak3d** [comment]
Ok, I'll rebuild, sry

**Comment by peak3d** [comment]
@Vitocorl  https://jenkins.kodi.tv/job/Android-ARM/12987/artifact/kodi-20190219-dd4e434d-PR15553-merge-armeabi-v7a.apk

**Comment by Vitocorl** [comment]
Ok, do i install this on top of existing Kodi, or uninstall? I have installed Kodi 18.1 and Netflix addon and have come to the point where i get the Widevine errors...

**Comment by peak3d** [comment]
1.) does the cryptoSession issue appeared after fectory reset?
2.) Yes. pls update over existing, it is important then I get the debug log of the first start of the new apk.

**Comment by Vitocorl** [comment]
1. Yes, the cryptoSession issue appeared after the factory reset
2. I will do it asap and post the log

**Comment by Vitocorl** [comment]
Unfortunately, i get the error again... https://hastebin.com/omiwokuhuk.sql

**Comment by peak3d** [comment]
Ok, but we're on the right way, can you pls. enable libCURL component debugging, and after that start kodi again -> log pls.

**Comment by Vitocorl** [comment]
libCURL component enabled log: https://hastebin.com/enosuwitat.sql

**Comment by peak3d** [comment]
Next build is running: https://jenkins.kodi.tv/job/Android-ARM/12988/

**Comment by Vitocorl** [comment]
Ok, keep it coming!

**Comment by Vitocorl** [comment]
I downloaded it, going to try it out

**Comment by Vitocorl** [comment]
Same error, maybe i should uninstall and reinstall Netflix addon, because i did not even have the chance to login.... https://hastebin.com/kaselazubi.coffeescript

**Comment by peak3d** [comment]
Sems that provisioning was successful, does a new kodi start is Ok now ?

**Comment by Vitocorl** [comment]
Hey, i shutdown Kodi, restarted and Netflix was functioning! It is fixed with the second apk build, it just needs to open once (shows widevine errors) close Kodi and when it opens again no errors!!!!

**Comment by peak3d** [comment]
Yes, right, I'll make one final fix for it, would be great if you can after that make a last try

**Comment by Vitocorl** [comment]
Of course i can

**Comment by peak3d** [comment]
busy with familiy, will be later tonight, I'll post de download link later.

**Comment by Vitocorl** [comment]
Ok, i understand, i too have to revise my daughter's homework, so when i have the time and check back i will try it and report here, have a good evening.

**Comment by peak3d** [comment]
https://jenkins.kodi.tv/job/Android-ARM/12991/

**Comment by Vitocorl** [comment]
Just logged in, downloading the final now, i will report back in 5-6 minutes...

**Comment by peak3d** [comment]
For a real test you unfortunately have to factory reset again :-( But you don't need to install stock kodi before.

**Comment by Vitocorl** [comment]
Oh god, i also thought so, i will do it, but first, let me take a backup of my Kodi userdata and addons, reporting back when i have finished.

**Comment by peak3d** [comment]
Thx, it's the last test, promised :-)

**Comment by Vitocorl** [comment]
hahahaha, i should not complain at all, after all i started that....
Do you think that this will also do for my other Android box, which is also Android Tv 8.1, but it does not have L1 certification, it is only L3?

**Comment by peak3d** [comment]
I'm not 100% sure if L3 devices must be provisioned, too. If so, it affects every new device where no widevine DRM content was played before.

**Comment by Vitocorl** [comment]
I have a third box, Android 7.1, where Netflix played fine from the start and it also is L3, but it is not Android TV...

I am resetting the box now, reporting back when finished....

**Comment by Vitocorl** [comment]
You nailed it, Netflix plays from the start, i think we can close this issue for L1 Android TV! 
Tomorow i will check the L3 device and let you know, but i am not sure if  that device is supposed to play Netflix, it is not certified by Netflix and the Android TV app cannot even start on it...

Thanks again for all your efforts and hard work, i wish you a good night!

**Comment by peak3d** [comment]
Thank you!

**Comment by Vitocorl** [comment]
@peak3d 
Marcus, i am not sure if you would like to speak to me again after yesterday's marathon :-), but can you check the log from my other Android TV Device? It also L1 (not L3 as i told you yesterday) but in the log i can see it fails to open the provisioning urls... https://hastebin.com/ocamazuxin.sql
I have installed the final apk kodi-20190219-800c54f0-PR15553-merge-armeabi-v7a.apk that worked perfectly in Xiaomi yesterday...

I am also uploading some DRM Info pictures, in case you find something helpful
https://imgur.com/a/XQCWBva
https://imgur.com/a/Tzrc9sY
https://imgur.com/a/t4NbaVf
https://imgur.com/a/NZCkJ4o

**Comment by peak3d** [comment]
@Vitocorl  sorry I cannot really help with that, I get URL and data from widevine API and simply send the data to the URL. If you send the command via CURL (data can be found in log), the error returned is:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid Value"
   }
  ],
  "code": 400,
  "message": "Invalid Value"
 }
}
```
But it says nothing to me, sry.

**Comment by Vitocorl** [comment]
Ok, i guess there is something odd with the ROM of this device, thanks anyway for your time.

**Comment by peak3d** [comment]
Maybe try a factory reset or unroot the device

**Comment by Vitocorl** [comment]
Yes, i thought of that, but i am thinking to try another ROM i found on freaktab on it and see.
