### ISSUE TITLE
Problems wrong subtitle positions on webvtt-lssdh-ios8 when multi-line showed

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#229]
Several users have reported this problem, as shown in the screenshot the location of the subtitles seems wrong.
This is an example taken from "American Crime Story", series "The People v. O.J. Simpson" ep.1
The text "you have 90 seconds." should go under.

The format used is: webvtt-lssdh-ios8
Using the Netflix addon 14.0 beta 20 (in my repo)

![image](https://user-images.githubusercontent.com/3257156/52535554-0ff72700-2d50-11e9-887e-becd066e7914.png)

This is the subtitle code:
`
WEBVTT

NOTE Netflix
NOTE Profile: webvtt-lssdh-ios8
NOTE Date: 2017/02/23 01:32:47

NOTE SegmentIndex
NOTE Segment=591.466 32794@419 202
NOTE Segment=587.420 52446@33213 323
NOTE Segment=593.051 64699@85659 396
NOTE Segment=591.674 62117@150358 382
NOTE Segment=596.096 48916@212475 300
NOTE Segment=517.475 37083@261391 227
NOTE /SegmentIndex

........

217
00:11:04.747 --> 00:11:06.082  position:38.57%,start  align:start size:30.95%  line:10.00% 
<c.white><c.mono_sans>Please eat.</c.mono_sans></c.white>

218
00:11:04.747 --> 00:11:06.082  position:30.95%,start  align:start size:48.10%  line:15.33% 
<c.white><c.mono_sans>You have 90 seconds.</c.mono_sans></c.white>
`

On netflix browser same subtitle text lines are positioned at the top, but are correctly oriented
![image](https://user-images.githubusercontent.com/3257156/52535682-ae37bc80-2d51-11e9-822e-482eafbfbb87.png)

**IMPORTANT UPDATE:**
the problem occurs only in this case:
-screen resolutions set below 1080P
-kodi in windowed mode

unfortunately I can not test if the problem there is also in 4k

**Comment by Essam315** [comment]
This problem could be fixed by merging the lines with the same time codes when converting the subtitles from WebVTT to SRT format, in the same way "Subtitle Edit" merges the lines with the same time codes from "Tools" menu then "Merge lines with the same time codes".

**Comment by CastagnaIT** [comment]
**IMPORTANT UPDATE:**
the problem occurs only in this case:
-resolutions below 1080P
-kodi in windowed mode

unfortunately I can not test if the problem there is also in 4k

**Comment by dl16** [comment]
I had the problem in both fullscreen and windowed at 720p

**Comment by peak3d** [comment]
sorry @CastagnaIT but this seems to be a kodi isue, too. inputstream.adaptive passes the values simply to kodi.

**Comment by CastagnaIT** [comment]
thanks anyway
