### ISSUE TITLE
Compilation error: m_strGlobalApiVersion is not a member of kodi::addon::CAddonBase

### ISSUE THREAD

**Issue by Whisprin** [peak3d/inputstream.adaptive#230]
When compiling the latest version I'm getting an error during compilation:

```
kodi-addon-inputstream-adaptive-18-git/src/main.cpp: In member function ‘virtual bool WebmSampleReader::GetInformation(INPUTSTREAM_INFO&)’:
kodi-addon-inputstream-adaptive-18-git/src/main.cpp:1836:84: error: ‘m_strGlobalApiVersion’ is not a member of ‘kodi::addon::CAddonBase’
     if (!info.m_ExtraSize && info.m_codecName == "vp9" && kodi::addon::CAddonBase::m_strGlobalApiVersion.empty())
                                                                                    ^~~~~~~~~~~~~~~~~~~~~
```
https://github.com/peak3d/inputstream.adaptive/blob/master/src/main.cpp#L1836

**Comment by nitro322** [comment]
I'm also running into this.  I'm trying to build 2.3.15 on gentoo.  I have libplatform 2.1.0.1 and kodi-platform 18.0 (commit date 20180301) installed.  Happy to provide any additional information that may help troubleshoot this.

Thanks.

**Comment by peak3d** [comment]
your kodi addon dev kit is not up-to-date. Remove [src]/tools/depends/binary-addons/[platform] folder and recompile.
