### ISSUE TITLE
[Request] Customizing audio codec in the descriptions

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#236]
I don't know if it will be possible 
Currently there are no distinctions in the descriptions between dolby and dolby trueHD tracks or atmos etc..

it is possible in the future to have the possibility of change the words DD+ to 
DAtmos
DTrueHD
etc...

Example: this image show two english track at 6 channels but one is atmos
no distinctions between descriptions and users never understand if there are atmos tracks
![image](https://user-images.githubusercontent.com/3257156/53196790-22f3dc00-3619-11e9-8b3f-994ad9802262.png)

**Comment by peak3d** [comment]
Pls. report this to forum.kodi.tv / or kodi github issues, thx!
