### ISSUE TITLE
DRM/Inputstream.adaptive - Record stream

### ISSUE THREAD

**Issue by wwark** [peak3d/inputstream.adaptive#238]
Hi,

Is it possible to record DRM content with the inputstream.adaptive or it is not the case?
If it is not the case, do you think it will be possible in the future?

Thanks for your return,
Wwark

**Comment by FloridaStream** [comment]
You are going the wrong way, this is never going to be supported here, this goes against all DRM policies, and would only bring problems and lawsuits from all sides, I recommend you close your issue, and search for similar requests that were denied here . This addon is an alternative for viewing these contents in KODI, it only acts as an intermediary, without saving anything, nor recording, just for you to watch. I hope you have understood the purpose of this project. @wwark

**Comment by wwark** [comment]
HI @FloridaStream,

Thank you for your return, I understand. I will close this issue.
Wwark
