### ISSUE TITLE
inputstream.adaptive not available in official kodi repo anymore!

### ISSUE THREAD

**Issue by momo42** [peak3d/inputstream.adaptive#253]
Today I installed Kodi 18.0 on a new Android device (version from f-droid) and unlike before I wasn't able to install "InputStream Adaptive" from official kodi repository. Only "RTMP Input" is available under "Video InputStream Addons".

Then I checked my old Android device and saw that InputStream Adaptive (2.3.13) is still installed but on its info screen the source repository is remarked as "unknown".

I have absolutely no idea if the problem is on your or kodis side but I didn't find a dedicated bug tracker for the official kodi repo. So I think here is the best place for reporting this.

Please get this issue fixed! :-)
Thanks for your time!

**Comment by momo42** [comment]
just guessing: might have something to do with https://github.com/peak3d/inputstream.adaptive/issues/241

**Comment by momo42** [comment]
and perhaps https://github.com/xbmc/repo-binary-addons/commit/7d748237dd5c0d1fcac2e4ec24c3373070bea96e
but I have really no idea of those things.

**Comment by momo42** [comment]
also see: https://github.com/xbmc/xbmc/issues/15965

**Comment by peak3d** [comment]
can we close this issue?

**Comment by momo42** [comment]
Yes. Seems to be a packaging issue at F-Droid. Sorry to have bothered you. :-)
