### ISSUE TITLE
mpd with .4ms is not working on kodi but works in vlc

### ISSUE THREAD

**Issue by emadmahdi** [peak3d/inputstream.adaptive#263]
I tried to play this mpd file but it doesn't work in kodi 17.6 and works in vlc 3.0.6
https://videodelivery.net/e741fa99d45349a05a8e997595a424d5/manifest/video.mpd

i added to my script these lines but it still not working
play_item.setProperty('inputstreamaddon', 'inputstream.adaptive')
play_item.setProperty('inputstream.adaptive.manifest_type', 'mpd')

some other mpd files are working on kodi 17.6 perfectly, such as this one
https://videodelivery.net/25bdbb4bbfa9ab31e2544c3ebad62089/manifest/video.mpd

thanks

**Comment by emadmahdi** [comment]
it is working on kodi 18.2 android 7.1.1 inputstream.adaptive 2.3.17
but not working on kodi 17.6 windows 10 x64 inputstream.adaptive 2.0.19

where can i find an updated version of inputstream.adaptive for kodi 17.6 windows 10 x64 ??

**Comment by peak3d** [comment]
Sorry, there will be no backporting from my side because of the API changes between V17 / v18.
