### ISSUE TITLE
Unsupported stream on KODI 18

### ISSUE THREAD

**Issue by s0faking** [peak3d/inputstream.adaptive#266]
inputstream.adaptive stopped working for my addon on kodi 18.2. i've attached my logfiles for kodi 17.6(works here, inputstream.adaptive 2.0.19) and kodi 18.2(inputstream.adaptive 2.3.17). On Leia i only get `CVideoPlayer::OpenStream - Unsupported stream 1. Stream disabled.`.

[kodi17_6.log](https://github.com/peak3d/inputstream.adaptive/files/3197584/kodi17_6.log)
[kodi18_2.log](https://github.com/peak3d/inputstream.adaptive/files/3197585/kodi18_2.log)

**Comment by peak3d** [comment]
The content is geolocked and therefore not accessible for me for reproduction.
If possible download one .ts stream segment (you'll find the download URL in kodi log) and attach it / dropbox it. If there are legal issues, pls. provide segment (link) via mail.

**Comment by s0faking** [comment]
I've sent you a mail. better safe than sorry ;)

**Comment by peak3d** [comment]
Fixed with https://github.com/peak3d/inputstream.adaptive/commit/50ff9d2308c8b089c05dcd5408a4954b29029a9c

Will be merged / released soon
