### ISSUE TITLE
PSSH not found

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#268]
Hi @peak3d,

Working on my next add-on and struck this error when trying to playback content.

Could not extract license from video stream (PSSH not found)

I think in this case, the PSSH is returned in the license request json response.
But, this fails before every trying to get the license.

Attached is the debug log, mpd file, init.mp4
 
[master_h264-8adc3a0a.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3210235/master_h264-8adc3a0a.mpd.txt)
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3210237/kodi.log)
[init.mp4.txt](https://github.com/peak3d/inputstream.adaptive/files/3210239/init.mp4.txt)

Here is a screenshot of the android app raw payload to the license server
**https://lic.drmtoday.com/license-proxy-widevine/cenc/**
![image](https://user-images.githubusercontent.com/6225961/58225815-04b48e00-7d78-11e9-81f7-67fd97ac617a.png)

And here is the json response:
![image](https://user-images.githubusercontent.com/6225961/58225952-7a205e80-7d78-11e9-9d51-5edade423160.png)

**Comment by matthuisman** [comment]
Here are the exact files the above Android app requests are for
[master_h264-5327795.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3210264/master_h264-5327795.mpd.txt)
[init.mp4.txt](https://github.com/peak3d/inputstream.adaptive/files/3210265/init.mp4.txt)
[seg-1.m4f.txt](https://github.com/peak3d/inputstream.adaptive/files/3210266/seg-1.m4f.txt)

**Comment by peak3d** [comment]
@matthuisman 
1.) the manifest does not support widevine DRM, I wonder that inputstream.adaptive doesn't stop earlier.
2.) pssh is necessary to get the license request, install the eme logger (chrome plugin) and look what pssh data is sent. I assume its a combination from key_id and content_id. You can pass this with inputstream.adaptive.license_data property.

**Comment by matthuisman** [comment]
Is KID that same as PSSH?
https://bitmovin.com/docs/encoding/tutorials/how-to-create-widevine-drm-protected-content

I found the json response that returns the license server has a keyId: ad8debca0f7b4d57aa520ce6007d39ec as well as the url and custom-data.
The same key is also called 'protectionKey' elsewhere.

Would that maybe be the KID?

I would then do license_data=ad8debca0f7b4d57aa520ce6007d39ec  ?
Or maybe base64 encode it = YWQ4ZGViY2EwZjdiNGQ1N2FhNTIwY2U2MDA3ZDM5ZWMgIA==
How do I also send the PSSH?

https://forum.kodi.tv/showthread.php?tid=320774
This guy was using the same license server.

**Comment by peak3d** [comment]
@matthuisman pssh contains in general the KID, but can contain more information, this depends on what the license server expects. In your case it seems that KID could be sufficient, just try it with the base64 decoded convention: license_data=ad8debca0f7b4d57aa520ce6007d39ec

This should already work with older versions, with the latest mater you can simply make licence_data={KID}.

**Comment by peak3d** [comment]
One more thing: normally audio has different KID than video, sometimes F/UHD have different KID's than SD video streams, in that cases you will not be able to pass the KID from addon to inputstream.adaptive, but you can work with license_data={KID} concept.
