### ISSUE TITLE
Unable to update inputstream.adaptive

### ISSUE THREAD

**Issue by buddy9507** [peak3d/inputstream.adaptive#269]
I been trying to upgrade inputstream.adaptive to 2.3.18 I can’t even download 2.3.17 is there a fix for this? thanks.

**Comment by peak3d** [comment]
what OS ?

**Comment by dagwieers** [comment]
The last available inputstream.adaptive on LibreElec Kodi 18.2 on Raspberry Pi is 2.3.17.1 :-/

**Comment by dagwieers** [comment]
On Android in Google Play you have Kodi 18.2 available with inputstream.adaptive 2.3.17.

**Comment by dagwieers** [comment]
@buddy9507 Is this still an issue?

**Comment by dagwieers** [comment]
@peak3d No recent feedback. Please close this issue.
