### ISSUE TITLE
Bug with licence key "BJB" parsing response payload on Android

### ISSUE THREAD

**Issue by stanislav-m** [peak3d/inputstream.adaptive#272]
I have BJB working on Windows and Linux, but kodi crashes on Android.

The license server returns base64 encoded data: 
eyJ3dmxpYyI6IkNBSVN0d0lLS2dvUWVpc1VkNHMxeFU0SVJ0VlVNakVNbVJJUWVpc1VkNHM ...
after decoding I get a json with the license key {"wvlic":"CAIStwIKKgoQeisUd4s1xU4IRtVUMjEMmRIQeisUd....
For this reason, I set up my license URL in my addon to be:
licURL = play_param['license_url'] + '||R{SSM}|BJBwvlic'

I found the issue in wvdecrypter_android_jni.cpp - line 831 on master.
it reads:
"if (blocks[3][1] == 'B')", but should be:
"if (blocks[3][dataPos - 1] == 'B')" - as in wvdecrypter.cpp line 856.
So I believe to be an easy fix.

I will try to fix this locally, but I am not sure where and how and where to install the inputstream.adaptive binary add-on on Android.

edit:
Just a bit more info...
As I already mentioned everything is looking good on Windows and Linux.
On Android, Kodi manages to download the response from license key server as I gave example above - in base64 encrypted form.
All this make me think that the issue is with the parsing of the received response, so I started looking at the wvdecrypter code and found the difference I mentioned above.
The check should be either: if (blocks[3][2] == 'B') or
if (blocks[3][dataPos - 1] == 'B') as dataPos is already 3 in that moment.

Also if you give me some references where to drop built binaries on Android (inpustream.adaptive) and some guide to compile against Android, you'll be very much appreciated.

Thanks

**Comment by stanislav-m** [comment]
Just a bit more info...
As I already mentioned everything is looking good on Windows and Linux.
On Android, Kodi manages to download the response from license key server as I gave example above - in base64 encrypted form. 
All this make me think that the issue is with the parsing of the received response, so I started looking at the wvdecrypter code and found the difference I mentioned above.
The check should be either: if (blocks[3][**2**] == 'B') or
if (blocks[3][dataPos - 1] == 'B') as dataPos is already 3 in that moment.

Also if you give me some references where to drop built binaries on Android (inpustream.adaptive) and some guide to compile against Android, you'll be very much appreciated.

Thanks

**Comment by peak3d** [comment]
@stanislav-m the parsing part should always be in sync between the two files, seems that I missed it last time I changed

**Comment by stanislav-m** [comment]
Thank you very much!

**Comment by peak3d** [comment]
@stanislav-m pls. verify this build: https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/79/artifacts

Thx!

**Comment by stanislav-m** [comment]
@peak3d  Thanks. I checked this morning and it does not work.
I installed the addon through normal way installing addons - "install from zip" option in kodi. I even changed the version to be sure I am using correct version - so don't be surprised when looking in the logs. 
I've uploaded my logs including license server communication from cdm folder at:
https://github.com/stanislav-m/storage_place.

On the other note: thanks for the docs links - I did find this myself but wasn't reading carefully.

**Comment by peak3d** [comment]
Sorry, install from zip is not working for android. You'll have to wait until it is bundled into the apk.

**Comment by stanislav-m** [comment]
I made another attempt with a rooted device.
I check the kodi.log what is the full path when inputstram.adaptive is loaded to find the location.
After that, I replaced the two .so libs, even restarted the device.
However, the result is the same - Kodi crashes after downloading the key response from the license server.
Unless I am missing something, this small change is not enough to fix the issue.
Thanks

**Comment by stanislav-m** [comment]
@peak3d Update.
I've been trying to build kodi targeting Android unsuccessfully for some time... until I realized that I can test the nightly on Android... (silly me).

I can confirm the fix did the trick: the "BJB" bug I was facing is not existent with the nightly.
You can close the issue!

Thank you very much!

**Comment by stanislav-m** [comment]
Fixed
