### ISSUE TITLE
2.3.19 inputstream adaptive issue

### ISSUE THREAD

**Issue by buddy9507** [peak3d/inputstream.adaptive#276]
Unable to update inputstream adaptive to 2.3.19 says update failed no check the log just fails I’m using a android box is there a fix or a work around for this to update?

**Comment by icpryde** [comment]
Same issue and now it’s up to version 2.3.23 and I keep getting update failed

**Comment by dagwieers** [comment]
Is this issue still relevant? If not, please close. cc @peak3d
