### ISSUE TITLE
Not start adaptive stream

### ISSUE THREAD

**Issue by atirage21** [peak3d/inputstream.adaptive#277]
This stream not start in kodi with inputstream.adaptive. In exoplayer in android and with fluendo codecs in linux is working.

**Comment by kyl416** [comment]
That streaming server has user-agent protection to block Kodi and Libavf from playing it.

**Comment by atirage21** [comment]
It is possible to solve ?

**Comment by atirage21** [comment]
This command me generate many new information, but i dont know, what me help from this:
curl https://sec-stream1.stream.satro.sk/live/smil:barrandov.smil/playlist.m3u8 -avc1.77.31,mp4a.40.2

**Comment by mbebe** [comment]
You have answer in your posts -

> That streaming server has user-agent protection to block user-agents that have "Kodi" or "Lavf" in the name from playing it:

So you should add exoplayer headers in 'inputstream.adaptive.stream_headers'

**Comment by atirage21** [comment]
Where ? in which file ?

**Comment by atirage21** [comment]
thx, it helped
