### ISSUE TITLE
Wrong url calculated (2x base urls in mpd)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#283]
It has 2x base-urls in the mpd (attached), not sure if that is what is causing the issue.
One appears to be a back-up.

```
  <BaseURL>https://spark.akamaized.net/dash/live/2003222-b/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/startover/5982918e8f79bdb74efcd16275d0653ada1b9302/</BaseURL>

  <BaseURL>https:/spark.akamaized.net/dash/live/2003222/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/startover/5982918e8f79bdb74efcd16275d0653ada1b9302/</BaseURL>
.....
media="../../462c5cc3-fc84-4d0f-aec8-b68dda344331/$RepresentationID$-$Number$.mp4" initialization="../../462c5cc3-fc84-4d0f-aec8-b68dda344331/$RepresentationID$-init.mp4"
```
The url is calculates is:
`https://spark.akamaized.net/dash/live/2003222-b/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/startover/5982918e8f79bdb74efcd16275d0653ada1b9302/https:/spark.akamaized.net/dash/live/2003222/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/startover/5982918e8f79bdb74efcd16275d0653ada1b9302/../../462c5cc3-fc84-4d0f-aec8-b68dda344331/1080p-30fps-6000kbps-init.mp4`

The correct url should be:
`https://spark.akamaized.net/dash/live/2003222-b/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/462c5cc3-fc84-4d0f-aec8-b68dda344331/1080p-30fps-6000kbps-init.mp4`

The url to mpd is:
https://spark.akamaized.net/dash/live/2003222-b/spark/d2150a9c-6747-46f3-92bb-75cc6f062723/startover/5982918e8f79bdb74efcd16275d0653ada1b9302/master.mpd

Debug log and mpd attached

[master.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3343348/master.mpd.txt)
[kodi.log.txt](https://github.com/peak3d/inputstream.adaptive/files/3343360/kodi.log.txt)

Appears maybe Inputstream just needs to select the first base url and use that?

**Comment by matthuisman** [comment]
@peak3d 
'Pinging' as I know sometimes you miss my issues :)

**Comment by glennguy** [comment]
Looks like the second BaseURL is malformed - only one forward slash so maybe it should reject it based on that?

**Comment by peak3d** [comment]
@matthuisman I'm really unsure if I want to spend time on implementing logic to detect such malformed stuff. If it is important for you, you still could route the mpd fetch through your plugin and repair the mpd file by yourself.

**Comment by matthuisman** [comment]
Sorry, I was unaware it was malformed.

Your saying a mpd file should never have 2x base URLs? Its against the
specification?

I assumed it was just a feature we hadn't seen yet. Eg. A fallback if the
first is down or players pick one at random to reduce loads.

It plays via their android app (probably shaka) and via website.

In the inputstream code, it appears its just appending both base URLs
together.

I was thinking when its looping the tags that it could just skip the
baseurl tag if it already had a base URL set.

**Comment by matthuisman** [comment]
Oh, just spotted glens comment and the missing slash!

Ill fix the slash and see if IA can then handle it (with 2x valid base URLs)

Hopefully the provider will fix it their end too

**Comment by matthuisman** [comment]
Ok, looks like two base URLs is valid.

https://github.com/google/ExoPlayer/issues/771

Yes in this case the 2nd is malformed but ideally IA would be ignoring it
anyway as it has already selected the first?

Obviously the failover logic is a big ask, but maybe for now just selecting
the first one?

I think something like this could be used by providers to try to kill kodi
addons.

Putting rubbish 2nd base URLs that other players will ignore but breaks
kodi playback.

What do you think?

**Comment by matthuisman** [comment]
@peak3d 

OK, the provider seems to have fixed the bad base urls.
The new .mpd file is attached.
And new log is attached.

IA plays this fine, but it seems to use the 2nd base-url for segments
_https://spark.akamaized.net/dash/live/2003225-b/_

I assume as it's looping elements, it just overrides the first base-url it had found.

Is this desired behaviour?
Or would it be better to stick with the first base-url?
I assume most providers will use the 2nd as a back-up so the first should be used?

[master.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3370656/master.mpd.txt)
[kodi.log.txt](https://github.com/peak3d/inputstream.adaptive/files/3370658/kodi.log.txt)

**Comment by matthuisman** [comment]
Further to this, this provider sometimes needs to use the 2nd base-url (-b).

**Comment by matthuisman** [comment]
I'll be closing this issue and starting a new issue to implement multiple base urls

**Comment by matthuisman** [comment]
New issue:
https://github.com/peak3d/inputstream.adaptive/issues/326
