### ISSUE TITLE
Add support for Periods

### ISSUE THREAD

**Issue by michaelarnauts** [peak3d/inputstream.adaptive#287]
I have a DASH manifest with multiple Periods, but currently, only the last Period is played (not the first as documented in the README.md).

Is there any progress being made to support this? Is this something that has to be parsed in this codebase, or does a lot has to change for this? I'm thinking about the total stream duration that should be the sum of all periods, seeking outside a period...

**Comment by dagwieers** [comment]
@mediaminister Maybe you have some knowledge of this?

**Comment by mediaminister** [comment]
Take a look at my test branch: https://github.com/mediaminister/inputstream.adaptive/tree/test
I can play the first period, but I have no clue how to add the second period to the stream.

Maybe @peak3d can gives us some tips where to start in the codebase to implement this?

**Comment by michaelarnauts** [comment]
@peak3d can you take a look at how we solve this best?

**Comment by michaelarnauts** [comment]
I've thought a bit about this, and talked with @dagwieers about this, I guess the only correct implementation is some kind of playlist that contains all the Periods and plays them one by one.

Please correct me when I'm mistaken with some of my assumptions.

* I want to play all periods one by one. They should not be skipped.
* The periods are different streams, with different codecs, resolutions or encapsulation. Some periods aren't encrypted with widevine others are. This makes me think that we can't use one stream for all periods since the player needs to be reinitialised for the next stream.
* Chapters will not work, since they work in one stream (think like DVD chapters) and just jump to timecodes.
* I think for the subtitles, there is chance that it will just work. If the period after an advertisement break sets the right timecodes (so they don't start at 0, but continue where it left off), the subtitles will just use the right timecode and will work fine.
* What would be cool, but I don't see how this can work is that all the periods are on one timeline, so you can seek in the whole program, and not just in your current period. This is not how playlists work however.

**Comment by peak3d** [comment]
thx @michaelarnauts, this helps to get an idea about the topic and makes sense.

**Comment by matthuisman** [comment]
I've just struck a multiple period stream as well.
All the main content is in the first period which IA skips unfortunately.

Maybe a good start is first just updating the code to use the 1st period found.
I assume it's just parsing line by line and not check if it already has a period.
The same check could also be done for multiple base_urls as well (use 1st found).
(as per my issue here: https://github.com/peak3d/inputstream.adaptive/issues/283)

**Comment by mediaminister** [comment]
With other streams the first period may be a commercial...
But I have a commit which always uses the first period: https://github.com/mediaminister/inputstream.adaptive/commit/35d91601387f8a46620f7c7c90c45fe516e3b4ee

**Comment by matthuisman** [comment]
I'm thinking if there is anyway I can proxy the mpd file to merge the periods myself.
I don't think it's possible...
Unless IA could handle 2x SegmentTemplates in a single representation?

**Comment by dagwieers** [comment]
Yeah, so choosing the first or last period will most likely make one part happy, and breaks another part. At least it may break things that were working flawlessly today (e.g. VTM GO children shows).

Another option coined by @peak3d was to play the largest segment, which would be the better option for the cases where there is only one real segment. But it would fail for the reporter of the issue. So personally I would not look at quick fixes as they are a distraction for doing what is needed.

PS I was honestly surprised that Kodi (or inputstream.adaptive) is having its own implementation for handling manifests etc. Surely other Open Source media players have the same needs and possibly a better/more complete implementation? Possibly something we can collaborate on?

**Comment by peak3d** [comment]
Anyone can point me to a free resource / .strm file where protected content is inside a multi period manifest?

**Comment by mediaminister** [comment]
https://github.com/Axinom/public-test-vectors#v7-multidrm-multikey-multiperiod

**Comment by dagwieers** [comment]
Everything in the VTM GO addon seems to be available (in Europe) and does not need credentials AFAICT. So testing with https://github.com/michaelarnauts/plugin.video.vtm.go is probably easiest.

**Comment by dagwieers** [comment]
IMO we don't want to skip the ads per se. If the business model of the content provider is advertisements, I think we need to respect that. If that is technically not possible, then that is how it is and up to the add-on developer to either make the user aware of the terms of use or disclaim any rights. If it would be possible to also avoid forwarding ads then I would keep such an option open for the add-on. That's my opinion.

**Comment by peak3d** [comment]
VTM Go works fine here, thx @dagwieers . Prevent forwarding is currently not supported by kodi, we can think later about it.

**Comment by peak3d** [comment]
thx @mediaminister, too, good to have different sources

**Comment by matthuisman** [comment]
Wow peak3d moves fast:
https://github.com/peak3d/inputstream.adaptive/commit/efa4a863b06f9ea77c6cbee9d1fcd798cdd07b47

**Comment by mediaminister** [comment]
Nice improvement, but when I try to watch VTM Go live tv Kodi crashes with a ` Floating point exception`.

**Comment by peak3d** [comment]
@mediaminister pls. make an issue report including kodi log and maybe stack traces

**Comment by mediaminister** [comment]
Here is a issue with the logs: https://github.com/peak3d/inputstream.adaptive/issues/322

**Comment by michaelarnauts** [comment]
@peak3d thanks for you work! Can you elaborate on how your implementation from https://github.com/peak3d/inputstream.adaptive/commit/a5b1fabaf6f52ec33520cadd4b38f0ecb2440ddb works?
* Do you get one big stream?
* What happens when the end of the period is reached?
* What happens when you seek to a timestamp in a different period?

**Comment by peak3d** [comment]
- In Kodi you'll see a timeline with dots, each dot is the start of a new chapter.
- At the end of a period the next period is played
- seeking / chapter skip works, but not heavily tested -> you can time-seek over multiple chapters

**Comment by dagwieers** [comment]
@peak3d It appears to work and on VTM GO it tends to start with a commercial (everytime a different one). The subtitles for the show however starts immediately. So somehow the subtitles ought to track the *show periods* only, and not the commercials to work correctly.

During a period-transition the video stalls for a few seconds, and then the audio goes silent when video restarts, and then after a few seconds everything is fine again. Maybe this is related to peak3d/inputstream.adaptive#133 (which also still affects me).

I am using the latest master build (1f109197)

@michaelarnauts Normally you can use **Up** and **Down** to skip forward and backward through chapters, but this does not appear to work here.

**Comment by peak3d** [comment]
@dagwieers I pushed a new commit for VTM Go VOD stream types which should at least make seeking better.

For your idea with external dash library: parsing the files is easy and currently there is no need to care about an external lib. The implementation, in special aligning it to kodi capabilities, takes the most time, this is completely independend from having all data read.

**Comment by peak3d** [comment]
@dagwieers chapter skip (up / down) only works if you have kodi installed with the IChapter PR merged

**Comment by dagwieers** [comment]
> I pushed a new commit for VTM Go VOD stream types which should at least make seeking better.

Seeking works correctly now. Also restarting from previous offset now works correctly too. (I hadn't noticed this was broken, but now it is fixed !)

**Comment by dagwieers** [comment]
@peak3d Oh right :roll_eyes:

**Comment by mediaminister** [comment]
@dagwieers The subtitles are not part of the MPEG-DASH manifest that InputStream Adaptive opens, VTM Go uses separate WEBVTT files and cues for commercials are available in the non-standard json file that contains the MPEG-DASH manifest url. Fixing the subtitle timings should be done in the VTM GO add-on.

**Comment by dagwieers** [comment]
@mediaminister Let's discuss this in a separate ticket. My concern is that it means the VTM GO add-on needs to reimplement a lot of the Period logic in order to fix the offsets. I was hoping there was a better solution for this (i.e. get playback offset for non-commercial periods, if that is at all feasible).

**Comment by mediaminister** [comment]
I'll create an issue in the VTM GO repository.

**Comment by peak3d** [comment]
@mediaminister but therew are subs in the manifest. why provide external?

**Comment by michaelarnauts** [comment]
@mediaminister created this issue: https://github.com/michaelarnauts/plugin.video.vtm.go/issues/51

I also remember seeing subtitles in the manifest, but maybe we should continue discussion regarding the subtitles in the above issue.

**Comment by matthuisman** [comment]
@peak3d 
Will multi-period only work with your chapter PR?

Using your latest master build, I can't play past the first period.
It just exits back to menu.

**Comment by peak3d** [comment]
@matthuisman they should play as a single stream, pls. make sure that you really have inputstream.adaptive 2.4.0 installed, master version is smaller than current Matrix. And disable auto updates of inputstream.adaptive.

If this doesn't help, provide information pls. log / url / strm / mpd. whatever.

**Comment by matthuisman** [comment]
Windows 64 Kodi 18.4
Using IA from below:
https://jenkins.kodi.tv/job/peak3d/job/inputstream.adaptive/job/master/110/artifact/cmake/addons/build/zips/inputstream.adaptive+windows-x86_64/inputstream.adaptive-2.4.0.zip

Video shows as 03:32:29 in length (correct)

It stops playback at 00:37:38.
I assume this is the end of the first period as it shows "Stream has ended" card.
It then should move onto post-race interviews etc.

If I then try to resume from that time, it fails to play.
The log has me playing, seeking, and then trying to resume.

Log & MPD attached
Log is pretty big as I left it playing the last minute to catch it ticking over to next period.
I then try to resume

It's behind a paywall and region locked unfortunately so hopefully having a look at the mpd may help. Via their webplayer, it uses same mpd and the same total time and seeking through is ok.

[kodi.log.txt](https://github.com/peak3d/inputstream.adaptive/files/3592806/kodi.log.txt)
[master.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3592807/master.mpd.txt)

**Comment by matthuisman** [comment]
Oh wait, it appears it is actually the fullstream by the timeline is out.
In kodi, 00:37:38 is actually the same as the end of the actual stream 03:32:29

**Comment by peak3d** [comment]
@matthuisman I have pushed some changes today (inputstream.adaptive), but all the things will only work well if my avsync PR goes into kodi. Without this PR the chapter change is not working correctly.

**Comment by matthuisman** [comment]
@peak3d
Just tested (windows x64) and now works perfectly

Uses latest commit (b796ea4) build from here
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/119/artifacts

and latest kodi nightly (KodiSetup-20190924-7a9ced55-master-x64.)
(It wouldn't install in current 18.4 due to dependency error on binary addon)

Can now seek around on 1st and 2nd segment without issue.
And chapters appear to work as well!
Maybe your PR was put in to latest nightly?

**Comment by piejanssens** [comment]
> 
> 
> @matthuisman I have pushed some changes today (inputstream.adaptive), but all the things will only work well if my avsync PR goes into kodi. Without this PR the chapter change is not working correctly.

@peak3d With the avsync PR being reverted, how will this continue? 
https://github.com/xbmc/xbmc/pull/16706

**Comment by peak3d** [comment]
@piejanssens I'll have to spend more time on it for a different solution.

**Comment by michaelarnauts** [comment]
@peak3d 

It seems that the recent commits (I think the one related to seeking), broke seeking with periods. I can't seek beyond a period. When a new period is started, the current time position is that one of the period playing, not of the total.

I've tested this with the vtm go addon.

**Comment by peak3d** [comment]
Thank you. And yes, you are completely right. I pushed the fix commit in master branch

**Comment by dagwieers** [comment]
Since Periods supports is now in the Matrix branch, and soon backported in the Leia branch I would close this issue.

Please open new issues for any problems encountered with the existing implementation. This makes it easier to track in isolation. Thanks everyone! cc @peak3d

**Comment by michaelarnauts** [comment]
I've opened a tracking issue at https://github.com/michaelarnauts/plugin.video.vtm.go/issues/139 to keep track of the avsync issue after playing a short period.

The relevant issue in inputstream.adaptive is https://github.com/peak3d/inputstream.adaptive/issues/332

I think this issue can indeed be closed since the implemantation of Periods is done.
