### ISSUE TITLE
No Video on my NVidia Shield TV

### ISSUE THREAD

**Issue by wintuxx** [peak3d/inputstream.adaptive#293]
Hello,

after the Update to Android Pie (Shield TV Version 8.0.0) i am not to start any video with netflix addon.

In the following log i did three tests.

First test: i deactivated all hardware accerlation.
I start a movie on netflix addon
I got sound, but no video (a fanart is showing)

Second test: i activated all hardware accerlation
I start a movie on netflix addon
i got no sound and video. The movie seem to start, but without sound and video.
But the progressionwheels turns and turns

third test: i activated one hardware accerlation
the same as the second test

i have done 2 times a factoryreset with no sucess.

Hope someone can help.

[Kodi debug log](https://paste.ubuntu.com/p/wGcCtXKPtq/)

[fresh Kodi install without any changes in settings](https://paste.ubuntu.com/p/NpNxd9CmPD/)

**Comment by beardie79** [comment]
I had the same behavior.

**Comment by Dnkhatri** [comment]
Does the netflix app work for you

**Comment by wintuxx** [comment]
The native Netflix app works without problems.

**Comment by chrmat** [comment]
I have the same problem. The netflix kodi addon that uses inputstream does no longer  work on Nvidia Shield TV running Android Pie . I have managed to start the video by manually selecting the lowest quality videostream. As soon as i select a higher quality stream the problems  stated by others above happens.

**Comment by Smeulf** [comment]
@peak3d regarding the tests we've made https://github.com/CastagnaIT/plugin.video.netflix/issues/152 it seems we're facing a decrypting issue.

So either we're sending bad data to InputStream, or it's not compatible with Android Pie.

Can you help us to understand the root cause of the issue? Is it on you side or on our (Netflix Add-on)?

Thank you!

**Comment by CastagnaIT** [comment]
lines 3330 and so:
2019-08-04 13:39:49.113 T:19914   DEBUG: AddOnLog: InputStream Adaptive: Download http://45.57.79.161/?o=AQPFAWeD_OU9X8HpvZKI531NDiHJ3FlhB9PF4YwyifMYM7KzRKaHgbzn1ovYriFL92d7eGTTeAOCVUKj_nbkuFY60EDg-z3AHyLLVHVCXaaasGJvJa8MLoofjVczm3R_tuw96xofpwQpy5I4YbOROyM&v=5&e=1564961989&t=GGHN895gVXLzicCSx98rDgFi5uw finished, avg speed: 12093017.35byte/s, current speed: 89913.00byte/s
2019-08-04 13:39:49.113 T:19914   DEBUG: AddOnLog: InputStream Adaptive: UpdateSampleDescription: codec 1635148593
2019-08-04 13:39:49.113 T:19914   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1)
2019-08-04 13:39:49.113 T:19914   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1): initalizing crypto session
2019-08-04 13:39:49.113 T:19914   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1 with codec_id 27
2019-08-04 13:39:49.162 T:19914   ERROR: CDVDVideoCodecFFmpeg::Open() CryptoSessions unsuppoted!
2019-08-04 13:39:49.162 T:19914   ERROR: CVideoPlayerVideo::OpenStream - could not open video codec
2019-08-04 13:39:49.162 T:19914 WARNING: OpenStream - Unsupported stream 1. Stream disabled.

**Comment by CastagnaIT** [comment]
an old caphm reponse say:
The ffmpeg video-decoder used by Kodi does not support cryptosessions,
Switch to a different decoder/player backend to enable encrypted video streams
https://github.com/asciidisco/plugin.video.netflix/issues/424

maybe updating ffmpeg?
https://github.com/xbmc/xbmc/pull/16461
better wait and try again after update

**Comment by Smeulf** [comment]
@CastagnaIT ffmpeg is not involved with Android. It's pure API calls to the OS (Source Kodi IRC chat with @lrusak)

**Comment by peak3d** [comment]
I send a request to NVIDIA to support investigating the issue. Unfortunately I'm out of ideas why the returned playback widevine license does not lead to the expected DRM licensing workflow.

**Comment by Dnkhatri** [comment]
Nvidia has just released a hotfix for shield. Could someone try it and check if it fixes the inputstream plugin. As they have mentioned the fixing of streaming apps.

https://www.nvidia.com/en-us/geforce/forums/feed/305747/shield-experience-upgrade-80-hotfix-image/

From the changelog
" For the first issue with Streaming apps failing to play, please:
1. Install the ota.
2. Start anyone of the streaming apps that failed to play for you.
3. Restart SHIELD.
4. Start the streaming app again.

#2 should fail and then schedule a cleanup of the corrupt secure storage files at the next reboot (#3) and then #4 should work. "

**Comment by Uukrull** [comment]
Still the same.

**Comment by peak3d** [comment]
@Uukrull have you manually fixed the ESN? should be NFANDROID2-PRV-ANDROIDSHIELDTV-NVIDIANDROID=SHIELD=TV. The esn emitter in the current addons does not build the correct ESN, how ESN are build correctly is under investigation.

**Comment by Uukrull** [comment]
That ESN doesn't work. The correct one (from the Netflix app) is NFANDROID2-PRV-SHIELDANDROIDTV-NVIDISHIELD=ANDROID=TV
but the problem is still there: only works if the Max. Resolution secure decoder is set to 480p.

**Comment by peak3d** [comment]
Oops, your ESN is correct, I mixed things from memory. I'm still waiting for feedback from official side.

**Comment by gjm1128** [comment]
Any updates? 
I hope this would be solved soon.

**Comment by peak3d** [comment]
Still waiting for a development android OS...

**Comment by superduper99** [comment]
Quick question:  what is everyone's "Decrypter path" in their Kodi Inputstream Adative general settings?

I've tried changing it, with no difference (same 480p and/or no video/sound errors as above either way). I've actually forgotten what the default one was now, so I'd be interested if someone could share.  My nVidia Shield is also 8.0

**Comment by Dnkhatri** [comment]
> Still waiting for a development android OS...

Nvidia have just released dev images for shield 8.0.0

**Comment by peak3d** [comment]
Thx

**Comment by Dnkhatri** [comment]
@peak3d  do you think code from this project would help fixing the problem of no hd playback in the netflix addon or is it just spoofing the app restrictions

https://github.com/longseespace/netflix_patch

**Comment by beardie79** [comment]
......and fixed. The shield update has fixed the problem. Netflix working fine now.

**Comment by Skaronator** [comment]
Cool thanks for the info!

**Comment by SpliNTSweden** [comment]
Nothing has changed for me even after the Nivida Shield update. 
Everything above hevc,720x480,1792000 bps is still black..

**Comment by wintuxx** [comment]
After the last update videos are playing again.
I did not test which resolution

**Comment by betuelrov** [comment]
Nothing has changed for me also. Above 720p streams>>black screen

**Comment by herbalizer404** [comment]
Same issue here even after 8.0.1shield upgrade

**Comment by xnappo** [comment]
For me, after one additional restart after the 8.0.1 update the Netflix Addon now plays video on both my Shields.

HOWEVER .strm files extracted from it that work fine on my PC do not work on my Shields.

**Comment by dagwieers** [comment]
Yes, updating **inputstream.adaptive** may require a restart of Kodi to make Widevine playback work (again). (Even if it was working just before the update). This may be problematic if **inputstream.adaptive** was updated in the background and the user was not aware that this happened (e.g. overnight).

**Comment by betuelrov** [comment]
But your shields are able to play 1080 or 4 streams?

**Comment by xnappo** [comment]
I can only verify 1080p is working again.

**Comment by betuelrov** [comment]
I tried to replicate your way and nothing, still black screen on 1080p streams. From where u update netflix plugin from official repo?

**Comment by xnappo** [comment]
I am using this version on the Netflix plugin:
https://github.com/CastagnaIT/plugin.video.netflix

The one on the repo is very old..

**Comment by betuelrov** [comment]
This exactly my installed version(0.15.3) and inputstream v2.3.22 on Kodi 18.4. No luck! 😔

**Comment by Dnkhatri** [comment]
> I can only verify 1080p is working again.

Have you reset the shield after installing shield experience 8.0.0 or 8.0.1

**Comment by herbalizer404** [comment]
Hi,
I have shield experience 8.0.1
inputstream 2.3.22
input stream helper 0.4.2
Netflix plugin 0.15.3
But ish don't find widevine, have you an idea?
Thanks

**Comment by HATEIOS** [comment]
> I am using the latest version from this Git of the Netflix plugin:
> https://github.com/CastagnaIT/plugin.video.netflix
> 
> The one on the Asciidisco repo is very old.. The Git above is the active development and they are getting prepared to submit to the official Kodi repo (though really not sure that is a good idea myself...)

I downloaded the zip file.. But still no luck.. I do see the resolution set to 780P.. However, in the Input stream settings, I set the resolution to Manual, then during a video, under Vido options, I do soo the other resolutions upto 1080P listed.. When I select the 1080p, I get a spinning wheel icon but no picture.. Please help me here, I set the minimum bandwidth under adpative stream settings to 8000000.. But still no luck

**Comment by Dnkhatri** [comment]
What version of Kodi are you using

**Comment by peak3d** [comment]
@HATEOS pls. Attach a kodi log, only kodi startup is required in there.

**Comment by HATEIOS** [comment]
> @HATEIOS pls. Attach a kodi log, only kodi startup is required in there.

Here you go.. 
[kodi netflix addon.txt](https://github.com/peak3d/inputstream.adaptive/files/3709613/kodi.netflix.addon.txt)

**Comment by HATEIOS** [comment]
Kodi version - 18.4- is what am using..

**Comment by HATEIOS** [comment]
I just figured it out.. its the KODI Leia version is the culprit.. Diwnloaded KODI 19 Alpha.. I can stream 1080P HDR videos with Dolby ATMOS.. with which I can leave on till we get an official build of 19.

**Comment by Dnkhatri** [comment]
> I just figured it out.. its the KODI Leia version is the culprit.. Diwnloaded KODI 19 Alpha.. I can stream 1080P HDR videos with Dolby ATMOS.. with which I can leave on till we get an official build of 19.

The next kodi 18 nightly should also work if you want to go back to 18.5

**Comment by herbalizer404** [comment]
Tried last nightly build 19 but I've a green screen with content over 720p, with esn set. Without, only 720p content is possible.

**Comment by peak3d** [comment]
@herbalizer404 kodi log pls.

**Comment by peak3d** [comment]
solved by this commits:

https://github.com/xbmc/xbmc/pull/16729
https://github.com/xbmc/xbmc/pull/16733
