### ISSUE TITLE
Cannot install inputstream.adaptive on RPI4

### ISSUE THREAD

**Issue by miky-boy** [peak3d/inputstream.adaptive#295]
Hi my friend,

I bought a new Raspberry Pi 4 with Raspbian and Kodi 17.6, but i cannot install any of your inputstream.adaptive versions in this Raspberry.

Exists any incompatibility or i need to do something?

Thanks and regards

**Comment by dagwieers** [comment]
I can confirm it does work on Raspberry Pi 4 using LibreELEC 9.1.002 ALPHA and Kodi 18.3.

**Comment by miky-boy** [comment]
Hi my friend,

Thanks to your response, but in my case the LibreELEC doesn't fit because i can't access the SD Card folders and have to change all my scripts and things to make it work.

I love the OSMC OS, but until now it doesn't support the RPI4, so i use now the Raspbian but in this OS i can't put the inputstream.adaptive working. It always says "cannot load shared library".

Let's see if something change.
Thanks and regards

**Comment by matthuisman** [comment]
@miky-boy 

try install inpustream.adaptive via terminal

**sudo apt-get install kodi-inputstream-adaptive**

**Comment by miky-boy** [comment]
Hi my friend,

I already tried, but i got the error: "E: Unable to locate package kodi-inputstream-adaptive".

I thought that was normal with RPI4 version, or do not?

Thanks and regards

**Comment by matthuisman** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=192499&start=200#p1506904
"so no RPi 4 support yet."

You need to go use LibreELEC.
/storage directory is writable.

**Comment by miky-boy** [comment]
Yes, it was my feelings. 

Thanks and regards

**Comment by matthuisman** [comment]
I just tested a Pi4 using libreelec and widevine worked fine
so maybe they are using 32bit userland

**Comment by peak3d** [comment]
cannot be solved
