### ISSUE TITLE
Support local file paths?

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#296]
I need to pre-process some mpd files before passing them to inputstream.
I add a <BaseUrl> to the mpd file so it points to the actual urls.
However, if I try to point IA to a local file - I get the below error:

ERROR: AddOnLog: InputStream Adaptive: Invalid mpdURL: / expected ()
ERROR: AddOnLog: InputStream Adaptive: Cannot download
ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (D:\temp_play_file)

UPDATE:
For anyone else, I just discovered if I use a / in the path 
D:/temp_play_file  instead of D:\temp_play_file it works.
Remember, you need a full url in the local mpd file as <baseurl>

The above error was caused here:
https://github.com/peak3d/inputstream.adaptive/blob/4b83ba39c62f15f843ecc1317640976bbd27bb43/src/common/AdaptiveTree.cpp#L218

which lead me to find the fix

**Comment by matthuisman** [comment]
UPDATE:
For anyone else, I just discovered if I use a / in the path 
D:/temp_play_file  instead of D:\temp_play_file it works.
Remember, you need a full url in the local mpd file as <baseurl>

The above error was caused here:
https://github.com/peak3d/inputstream.adaptive/blob/4b83ba39c62f15f843ecc1317640976bbd27bb43/src/common/AdaptiveTree.cpp#L218

which lead me to find the fix

**Comment by envinur** [comment]
> UPDATE:
> For anyone else, I just discovered if I use a / in the path - then it works.
> D:/temp_play_file instead of D:\temp_play_file it works.
> Remember, you need a full url in the local mpd file as
> 
> The above error was caused here:
> https://github.com/peak3d/inputstream.adaptive/blob/4b83ba39c62f15f843ecc1317640976bbd27bb43/src/common/AdaptiveTree.cpp#L218
> 
> which lead me to find the fix
> 
> Only issue with local file is that headers can't be passed along

Hi matthuisman,

Are you able to share the code you used to change the format of the local file?

I am struggling to get this to work..

**Comment by Vikassm73** [comment]
Downloaded and modified MPD manifest as below
`<MPD 
 <BaseURL>https://streaming.sonyliv.com/</BaseURL>
  <Period `


Try to execute using strm file as below (If I change d:/torrent/ with https://streaming.sonyliv.com/, it works)

#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
d:/torrent/show_sab_taarakmehtakaooltahchashmah_ep2897.mpd

Getting Error Message as below

2020-09-16 21:17:29.440 T:14820  NOTICE: VideoPlayer::OpenFile: D:\Torrent\test.strm
2020-09-16 21:17:29.441 T:12984  NOTICE: Creating InputStream
2020-09-16 21:17:29.451 T:12984  NOTICE: Creating Demuxer
2020-09-16 21:17:29.457 T:12984   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, d:\torrent\show_sab_taarakmehtakaooltahchashmah_ep2897.mpd
2020-09-16 21:17:29.463 T:12984   ERROR: Previous line repeats 1 times.
2020-09-16 21:17:29.464 T:12984   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
2020-09-16 21:17:29.464 T:12984  NOTICE: CVideoPlayer::OnExit()
2020-09-16 21:17:29.685 T:14820  NOTICE: CVideoPlayer::CloseFile()
2020-09-16 21:17:29.685 T:14820  NOTICE: VideoPlayer: waiting for threads to exit
2020-09-16 21:17:29.685 T:14820  NOTICE: VideoPlayer: finished waiting
