### ISSUE TITLE
Inputstream not showing in the official repo

### ISSUE THREAD

**Issue by danilo-jlle** [peak3d/inputstream.adaptive#300]
Hi.
I'm running Android 7.1 on a Pine64 board.
First, I installed a APK directly because Play Store version was outdated.
Until a month ago everything was fine, but then Netflix Kodi plugin stopped working after an update of Kodi (via Play Store).
So I downloaded the stable version on the official site, then the Leia unstable, and then the nightly Matrix (19). Every version has the same issue: inputstream.adaptive is NOT on the repos.
The only one there is RTMP.
The thing is: Netflix plugin needs it.
Then I downloaded every version of inputstream.adaptive zip files released here (for Leia releases) but it fails to install.
Any tip?

**Comment by wintuxx** [comment]
Activate it in user addons inputstream. There can u find it.

gesendet mobil

danilo-jlle <notifications@github.com> schrieb am Di., 13. Aug. 2019, 17:17:

**Comment by danilo-jlle** [comment]
It isn't there.
There is only RTMP.
I also unchecked "Hide not compatible".

**Comment by skydrome** [comment]
doesnt look like its been built for v19 yet

**Comment by danilo-jlle** [comment]
> doesnt look like its been built for android for v19 yet

I just reinstalled 18.3.

Thanks.
