### ISSUE TITLE
Segfault at InputStreamAddon.cpp:373 playingYoutube videos

### ISSUE THREAD

**Issue by candrews** [peak3d/inputstream.adaptive#313]
I'm experiencing a segfault whenever I attempt to play a Youtube video.

From the crash log:
```
Core was generated by `/usr/lib64/kodi/kodi-x11 -fs --debug'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f63b1b7fa6 in CInputStreamAddon::GetStream (this=0x7f8f50003920, streamId=0x1) at /usr/src/debug/media-tv/kodi-9999/kodi-9999/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp:373
373             videoStream->masteringMetaData->display_primaries[0][0] = av_d2q(stream.m_masteringMetadata->primary_r_chromaticity_x, INT_MAX);
```

Here's the full crash log: 
[kodi_crashlog-20190827_195515.log](https://github.com/peak3d/inputstream.adaptive/files/3548549/kodi_crashlog-20190827_195515.log)

I'm using:
Kodi Matrix commit https://github.com/xbmc/xbmc/commit/3a7e2f2b6bb05eb8f181c607a554cf60c60fb695
Inputstream Adaptive commit https://github.com/peak3d/inputstream.adaptive/commit/3df8a84db327d9417f43d455001486452eea51f9
I'm happy to provide any other information and perform any testing. Thank you in advance!

**Comment by peak3d** [comment]
Try recompiling inputstream.adaptive (master or Matrix branch) with the latest kodi addon dev-kit (current kodi master checked out). I'll talk to addon specialists why version check fails.

**Comment by candrews** [comment]
Fixed by https://github.com/xbmc/xbmc/issues/16535

Thank you!
