### ISSUE TITLE
Cannot match resolution in Kodi that is available via web player, same API

### ISSUE THREAD

**Issue by piejanssens** [peak3d/inputstream.adaptive#314]
Addon: https://github.com/shycoderX/repo-plugins/tree/leia/plugin.video.yelo

The quality via the provider's streaming web application is noticably better than what I see in the Kodi addon. 

I checked out the manifest in the stream on the website and can see that there is a stream provided in 720p (50Hz).

```
<Representation id="dzFmZgaf" bandwidth="419430" codecs="avc1.42801f" width="400" height="224" frameRate="25" sar="224:225"/>
<Representation id="dzHMzAyf" bandwidth="838860" codecs="avc1.42801f" width="640" height="360" frameRate="25" sar="1:1"/>
<Representation id="dzEzMxOf" bandwidth="1258291" codecs="avc1.42801f" width="768" height="432" frameRate="25" sar="1:1"/>
<Representation id="dzGZmRmf" bandwidth="1677721" codecs="avc1.42801f" width="960" height="540" frameRate="25" sar="1:1"/>
<Representation id="dzEAAEif" bandwidth="4718592" codecs="avc1.4d001f" width="1280" height="720" frameRate="50" sar="1:1"/>
```

The max resolution that I see in Kodi is 960x544 at 25fps. The max bitrate that is passed on to play the stream in the addon is set to '0' to be unlimited.

What can I check / test to see where the difference comes from?

Ping @shycoderX

Update: **found a workaround** -> Activate "Ignore Display Resolution"
FYI I'm using a MacBook Pro Touchbar (retina) and menu is set to 1920x1200p

**Comment by piejanssens** [comment]
Ping @shycoderx @GianniDPC

**Comment by shycoderX** [comment]
You can also set "Stream selection" to Manual when you have issues. Then when playing a stream you can select: "Video settings" -> "Video Stream" and choose the quality you want.

Normally it will remember your selection next time you select the stream.

**Comment by dagwieers** [comment]
Still I think it is strange in this case that on a display with resolution 1920x1200 the selection did not pick 1280x720 by default.

This may still be a bug.

**Comment by piejanssens** [comment]
I just retested this with VTM Go and I no longer see this issue.
