### ISSUE TITLE
Watching Anvato livestream crashes Kodi with a floating point exception

### ISSUE THREAD

**Issue by mediaminister** [peak3d/inputstream.adaptive#322]
While testing my own compiled Inputstream Adaptive version of the master branch with multiple periods support https://github.com/peak3d/inputstream.adaptive/commit/efa4a863b06f9ea77c6cbee9d1fcd798cdd07b47 Kodi crashes when I try to watch a livestream with VTM Go add-on

Test on LibreELEC in VMWare Workstation 15:
[kodi_vtmgolive.log](https://github.com/peak3d/inputstream.adaptive/files/3587410/kodi_vtmgolive.log)
[kodi_crashlog_20190908080832_vtmgolive.log](https://github.com/peak3d/inputstream.adaptive/files/3587411/kodi_crashlog_20190908080832_vtmgolive.log)

Test on Linux Mint 19:
[kodi_crashlog-20190908_101940_vtmgolive.log](https://github.com/peak3d/inputstream.adaptive/files/3587412/kodi_crashlog-20190908_101940_vtmgolive.log)

**Comment by peak3d** [comment]
thx, should be fixed with the latest force-push

**Comment by mediaminister** [comment]
Thanks, I can confirm this is fixed.
