### ISSUE TITLE
Add support for multiple base-urls

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#326]
I have a provider who uses mpd files with multiple base-urls.
[master.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3623539/master.mpd.txt)

https://spark.akamaized.net/dash/live/2003227/spark/a9bb8a4c-dd05-4a1b-85a1-8412fb0c6cfb/257395ff-a6a4-41cc-8638-ebc09ae86789-1567944923052/324p-30fps-950kbps-525.mp4  not found

https://spark.akamaized.net/dash/live/2003227-b/spark/a9bb8a4c-dd05-4a1b-85a1-8412fb0c6cfb/257395ff-a6a4-41cc-8638-ebc09ae86789-1567944923052/324p-30fps-950kbps-525.mp4   is found

Sometimes the segment files are on the 2nd base-url only and sometimes on the first, and sometimes on both. 

Currently IA just uses the last base-url it finds.
This can cause content not to play.

The desired behaviour would be that it checks for init.mp4 on each base-url and then uses the first base-url that works (not 404). Often the first base-url should be fine.

Or, it could store all the base-urls in a list. pop the first and carry on as normal.
If it get's a 404 on a segment etc, it pops the next base-url and retries.
If no more base-urls - then it fails.

I can't imagine that some segments would be stored on one base-url and some on the other.

Worst case, cause maybe IA just choose the first base-url instead of the last?
That should fix quite a bit in the meantime until checking behaviour added

**Comment by matthuisman** [comment]
Another way is possibly that it just stores all base-urls in a list.
Then it tries each on in order. If all fail, then stream fails.
Maybe if one succeeds, it's moved to the start of the list so it's used first next time.

[baseulr1, baseurl2, baseurl3]

try baseurl1 - fails
try baseurl2 - fails
try baseurl3 - ok
(move baseurl3 to start)

[baseurl3, baseurl1, baseurl2]

**Comment by matthuisman** [comment]
@glennguy next mission after HLS Widevine playback?? :D :D

**Comment by glennguy** [comment]
Ah I know that feel... gets better soon!

Yes definitely, I'll have a crack at it soon!
