### ISSUE TITLE
Max. Resolution secure decoder seems to be ignored

### ISSUE THREAD

**Issue by cache-sk** [peak3d/inputstream.adaptive#328]
CoreELEC 9.2.0 (Amlogic S905W), inputstream.adaptive 2.4.2.1.

Widevine content in 720p, 720x404 and some lower resolutions.
Non encrypted content in 1080p, 480p, 360p.

Due latest widevine issues with slower cpus, i tried to limit secure content to 640p, then 480p, but inputstream.adaptive still auto choose 720p.
On non encrypted content works max general decoder as expected.

On older version before update (CoreELEC 9.0.3 with inputstream.adaptive 2.3.22.1), when was both limit set to same 640p, then auto choose smaller resolution for both, widevine and non encrypted content. When was set only secure decoder limit, it was ignored too.

**Comment by peak3d** [comment]
Secure decoder only jumps in if libwidevine is used to decode the stream. If secure decoder settings have no effect, most likely ffmpeg or h/w decoder is used. can you provide a kodi debug log pls?

**Comment by cache-sk** [comment]
To clarify - when i set secure limit to 640p or 480p and play that mentioned widevine protected stream, it still chooses 720p.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3654734/kodi.log)
![settings](https://user-images.githubusercontent.com/48527944/65638911-623b3e80-dfe7-11e9-9f32-a864daa1b1bc.jpg)
![played_stream](https://user-images.githubusercontent.com/48527944/65638918-66fff280-dfe7-11e9-9629-a99f30178645.jpg)

**Comment by peak3d** [comment]
You stream plays using the unsecure decoder (AMLCodec / H/W).
inputstream.adaptive / widevine does only decrypt, but not decode.

If your licene forbid using the H/w secoder, and decoding takes place in libwidevine (AddonVideoCodec decoder is used then), the secure limit is taken.

Try to play a netflix stream with the netflix addon, then you know what I mean.

**Comment by cache-sk** [comment]
Oh, thanks, got it. Closing this now, sice it is not a bug and will open new issue with feature request.
