### ISSUE TITLE
Support ARMv6 RPI v1?

### ISSUE THREAD

**Issue by cverwey** [peak3d/inputstream.adaptive#329]
Is the Raspberry PI v1 (ARMv6) significantly different and therefore it was not feasible to support it? Is it in the pipeline at all?

I tried LibreELEC and the PI1 seems great, except that adaptive doesn't work and renders half my use case unavailable due to plugins relying on inputstream-adaptive.

**Comment by glennguy** [comment]
No, there is no available libwidevinecdm.so module compiled for armv6. Google is the only one who can provide this, and they likely never will unfortunately.

**Comment by yoshimo** [comment]
Not every stream needs widevine or playready as a drm module. So low resolutions without drm might be possible

**Comment by peak3d** [comment]
I don't see any reason why it should not be compiled for rbpi 1. What is the issue?

**Comment by glennguy** [comment]
Sorry I should have been clearer - I assumed @cverwey was referring to widevine protected content in which case there is no known available cdm from google/chrome for armv6. Of course they are free to view non drm protected DASH and HLS streams on armv6.

**Comment by dagwieers** [comment]
@cverwey If **inputstream.adaptive** is not available on LibreELEC for Raspberry Pi 1, I think you need to report it on their forums/bugtracker. If there's a technical reason why it cannot be compiled, that can be discussed here.
