### ISSUE TITLE
Error DAZN Playback

### ISSUE THREAD

**Issue by AlleSchonWeg** [peak3d/inputstream.adaptive#339]
Hi,
starting with rpi2 milhouse build #1007 (https://forum.kodi.tv/showthread.php?tid=343068&pid=2891094#pid2891094) DAZN playback don't work.
If i switch to earlier versions <#1007 everthing work as expected.
Log snippet:

> 2019-10-16 18:41:56.278 T:365  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.dazn/?id=1cv88829f5lc8196rgyph1qf1i&verify_age=False&params=a2wohbhrzyoya6plq2ipxt9a0&mode=play&title=%5BCOLOR+red%5D12%3A00%5B%2FCOLOR%5D+%5BCOLOR+dimgray%5DTennis%5B%2FCOLOR%5D+WTA+Luxemburg%3A+Tag+3+%5BCOLOR+dimgray%5DLuxembourg+Open%5B%2FCOLOR%5D
2019-10-16 18:41:56.280 T:464  NOTICE: Creating InputStream
2019-10-16 18:41:57.478 T:464   ERROR: AddOnLog: InputStream Adaptive: Download https://dcb-cf-live-m2a-dazn-cf.m2amedia.services/u0zw291dd5xk13scqjpmjxgav/tv/../all/dash/avc_dash_global-stream_audio_eng_128000=128000-0.dash?outlet=dazn-dach failed with error: 410
2019-10-16 18:41:57.479 T:464   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
2019-10-16 18:41:57.505 T:467   ERROR: AddOnLog: InputStream Adaptive: Download https://dcb-cf-live-m2a-dazn-cf.m2amedia.services/u0zw291dd5xk13scqjpmjxgav/tv/../all/dash/avc_dash_global-stream_audio_eng_128000=128000-0.dash?outlet=dazn-dach failed with error: 410
2019-10-16 18:41:57.509 T:464   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.dazn/?id=1cv88829f5lc8196rgyph1qf1i&verify_age=False&params=a2wohbhrzyoya6plq2ipxt9a0&mode=play&title=%5BCOLOR+red%5D12%3A00%5B%2FCOLOR%5D+%5BCOLOR+dimgray%5DTennis%5B%2FCOLOR%5D+WTA+Luxemburg%3A+Tag+3+%5BCOLOR+dimgray%5DLuxembourg+Open%5B%2FCOLOR%5D]
2019-10-16 18:41:57.510 T:464  NOTICE: CVideoPlayer::OnExit()
2019-10-16 18:41:57.610 T:365  NOTICE: CVideoPlayer::CloseFile()
2019-10-16 18:41:57.610 T:365  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-16 18:41:57.610 T:365  NOTICE: VideoPlayer: finished waiting
2019-10-16 18:41:59.179 T:365 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (2.88s)

**Comment by debutanker** [comment]
Can confirm here on my x86 Milhouse infrastructure.
Till build #1006 every channel works as expected - since build #1007 some channels dont work anymore.
Full debug log -> http://ix.io/1YYQ

**Comment by AlleSchonWeg** [comment]
The problem is the **/../** in the url. The baseUrl Node in the mpd File contains a relative path 
`<baseUrl>../all</baseUrl>`

**Comment by Goommer** [comment]
Hi, I have the same problem.

This is the difference between inputstream v2.5.0 vs v2.5.1 opening the same stream:

inputstream v2.5.0:

```
CurlFile::Open(0x7f2cd000dd20) https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es
Curl::Debug - HEADER_IN: HTTP/1.1 200 OK
AddOnLog: InputStream Adaptive: Effective URL https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es
AddOnLog: InputStream Adaptive: Download https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es finished
AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 3 Type: live, Download speed: 0.0000 Bytes/s
AddOnLog: InputStream Adaptive: Entering encryption section
AddOnLog: InputStream Adaptive: CDM version: 4.10.1440.18
AddOnLog: InputStream Adaptive: cdm::OnInitialized: true
AddOnLog: InputStream Adaptive: Searching PSSH data in FILE
CurlFile::Open(0x7f2cd000dd20) https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/../all/dash/avc_dash_global-stream_audio_eng_128000=128000.dash?outlet=dazn-spain
Curl::Debug - HEADER_IN: HTTP/1.1 200 OK
AddOnLog: InputStream Adaptive: Download https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/../all/dash/avc_dash_global-stream_audio_eng_128000=128000.dash?outlet=dazn-spain finished, avg speed: 130.13byte/s, current speed: 165200.00byte/s
AddOnLog: InputStream Adaptive: Initializing stream with KID: 1CD160F708F35D86A733EFB921AD1526
```



inputstream v2.5.0:

```
CurlFile::Open(0x7f52440c32c0) https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es
Curl::Debug - HEADER_IN: HTTP/1.1 200 OK
AddOnLog: InputStream Adaptive: Effective URL https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es
AddOnLog: InputStream Adaptive: Download https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/stream.mpd?outlet=dazn-spain&channel=1212&h=c447ed1739dedc0d627a8545cbf8f9cc&plang=es finished
AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Periods: 1, #Streams in first period: 3, Type: live, Download speed: 0.0000 Bytes/s
AddOnLog: InputStream Adaptive: Entering encryption section
AddOnLog: InputStream Adaptive: CDM version: 4.10.1440.18
AddOnLog: InputStream Adaptive: cdm::OnInitialized: true
AddOnLog: InputStream Adaptive: Searching PSSH data in FILE
CurlFile::Open(0x7f52440c32c0) https://dcblivedazn.akamaized.net/mrs8jo7ky9mj1886sqajlxljl/tv/../all/dash/avc_dash_global-stream_audio_eng_128000=128000-0.dash?outlet=dazn-spain
Curl::Debug - HEADER_IN: HTTP/1.1 410 Gone
```

this is the SegmentTemplate:
`<SegmentTemplate timescale="600" initialization="avc_dash_global-$RepresentationID$.dash?outlet=dazn-spain" media="avc_dash_global-$RepresentationID$-$Time$.dash?outlet=dazn-spain">`

I guess, is being used media instead of initialization?

**Comment by peak3d** [comment]
Can someone pls. provide a full .ism file here? Thx!

**Comment by AlleSchonWeg** [comment]
It's an .mpd file.
[stream.txt](https://github.com/peak3d/inputstream.adaptive/files/3837366/stream.txt)

**Comment by peak3d** [comment]
Thx @AlleSchonWeg, I'll come back.

**Comment by peak3d** [comment]
@AlleSchonWeg depending your kodi device OS you can test one of the artifacts from here:

https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/122/artifacts

**Comment by AlleSchonWeg** [comment]
@peak3d 
I have an rpi3 with libreelec. 
There are two arm versions. Could you tell me what is the correct zip for my device? I will test it this evening.

**Comment by peak3d** [comment]
sorry, there is no artifact for linux arm in our automated build system.
Let me ask in kodinerds forum, there is at least one who could verify the solution.

**Comment by Goommer** [comment]
I have compiled and tested:
0473ea8 [DASH] Fix full update for timelined manifests  **but don't work**
d0c23bd [DASH] Fix SegmentTemplate streams without range (issue 339)  **but don't work**

54ef24e (2.5.0-Matrix) work fine and a5b1fab don't work that means that behavior change is here: https://github.com/peak3d/inputstream.adaptive/compare/2.5.0-Matrix...a5b1fab

Only live streams fail, this prevents testing at any time, only when there are live events and time to do so.

my test environment is linux amd64 and I have no problems compiling it, if any specific log is needed add it, I will compile it and test it.

I'm sorry I didn't upload the full mpd file, excuse me

this is the latest mpd file that i tested tonigt: [livestream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3844094/livestream.mpd.txt)

**Comment by peak3d** [comment]
@Goomer can you pls. add the kodi debug log file? As said, I have no dazn accound and do the changes nearly blindly. log helps much here.

**Comment by Goommer** [comment]
Well, tonight when I get home I'll try to reproduce it, I hope there are live events, maybe darts.

Do you want the complete log or filtered with 'InputStream Adaptive'?

Do you want from a specific tag or commit?

Maybe one of 54ef24e (2.5.0-Matrix) and another of a5b1fab?

**Comment by peak3d** [comment]
If your current issue is the one from the initial post, libCURL component logging could help.
Complete log pls. (always)

**Comment by Goommer** [comment]
I hope I have not made a mistake, I have taken master (41892ae4).
There is a change in behavior, there is no 410 Gone but it still doesn't work, it seems that the audio goes down first. The same livestream

with 41892ae4: [kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3849217/kodi.log) and [stream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3849218/stream.mpd.txt)

with 2.5.0 working: [kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3849222/kodi.log) and [stream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3849226/stream.mpd.txt)

I hope you find it useful.
Thank a lot for your work.

**Comment by Goommer** [comment]
One more

with 41892ae: [kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3853547/kodi.log), [stream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3853548/stream.mpd.txt), [avc_dash_global-stream_audio_eng_128000=128000.dash?outlet=dazn-spain_-_base64.txt](https://github.com/peak3d/inputstream.adaptive/files/3853549/avc_dash_global-stream_audio_eng_128000.128000.dash.outlet.dazn-spain_-_base64.txt)

with 2.5.1: 
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3853554/kodi.log), [stream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3853555/stream.mpd.txt), [avc_dash_global-stream_audio_eng_128000=128000-0.dash?outlet=dazn-spain_-_base64.txt](https://github.com/peak3d/inputstream.adaptive/files/3853556/avc_dash_global-stream_audio_eng_128000.128000-0.dash.outlet.dazn-spain_-_base64.txt)

with 2.5.0: 
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3853557/kodi.log), [stream.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/3853558/stream.mpd.txt), [avc_dash_global-stream_audio_eng_128000=128000.dash?outlet=dazn-spain_-_base64.txt](https://github.com/peak3d/inputstream.adaptive/files/3853559/avc_dash_global-stream_audio_eng_128000.128000.dash.outlet.dazn-spain_-_base64.txt)


Thanks a lot

**Comment by peak3d** [comment]
Sorry @Goommer , lost this out of my focus, I pushed a new commit in master branch for this.
Pls. be so nice and test again.

**Comment by Goommer** [comment]
Tested and results:

 - master 5e182f9d works fine

 - 2.5.2-Matrix 490d4ff1 doesn't works

 - patching a5b1fab with 5e182f9d works fine

If you want logs I can upload them


Here is the problem https://github.com/peak3d/inputstream.adaptive/commit/a5b1fabaf6f52ec33520cadd4b38f0ecb2440ddb#diff-fc4abc2b8c72e480ba9689e8d056c8efL1174 and this is the solution https://github.com/peak3d/inputstream.adaptive/commit/5e182f9d5b3ee171277d4b1751d1671d5be2bb36
I think it shouldn't have been easy to find the problem, besides not being able to prove it directly.

Thanks a lot for your great work

**Comment by peak3d** [comment]
Thx for testing, next Matrix release will include the commit from master.
