### ISSUE TITLE
DASH: YouTube playback does not work anymore

### ISSUE THREAD

**Issue by Maven85** [peak3d/inputstream.adaptive#350]
Since https://github.com/peak3d/inputstream.adaptive/commit/41892ae497fd1326b03d2c9d0686330a359e25a2, playback in the YouTube add-on no longer works when 'Use MPEG-DASH' is enabled in the settings.

Debug-Log:
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/3863163/kodi.log)

**Comment by Maven85** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/8e6154d508714212a7d946b1d61b922b4d8c88cd works fine again

**Comment by DarkfireHellspawn** [comment]
How did you get the new version?

**Comment by Maven85** [comment]
depending your kodi device OS you can get it from here:

https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/134/artifacts
