### ISSUE TITLE
wvdecrypter docs / API reference

### ISSUE THREAD

**Issue by Anan5a** [peak3d/inputstream.adaptive#352]
Hi,
I'm trying to update a project named video_decrypter (it is a fork and original repo is gone)
But problem is original code base is unable to work with latest libwidevinecdm.so (Linux x86_64)
So if i try to copy relative files from inputstream.adaptive the build fails with errors. It would be nice if you can help with the docs of wvdecrypter

**Comment by nickcartery** [comment]
:D I want to use wvdecrypter in PHP script, dont know it can be? Wish had any documents... I got license from server, but dont know how to decrypt content with it :(
