### ISSUE TITLE
Kodi crash and resets if i enable "Media -> ALL", but work only with Audio streaming

### ISSUE THREAD

**Issue by robustini** [peak3d/inputstream.adaptive#371]
I'm going crazy because even from the log I can't understand what's going on.
Amazon VOD, everything installed correctly (I think) with the relative dependencies, when I send a video to PLAY the cursor starts to rotate and shortly after it stops, at that moment Kodi starts from scratch.
In the log you can clearly see that if I use only audio there are no problems (i think).
I also don't understand the "GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/" error, i need your help! :-)

[kodi_crashlog_20200108000444.log](https://github.com/peak3d/inputstream.adaptive/files/4032903/kodi_crashlog_20200108000444.log)

**Comment by glennguy** [comment]
`GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/` - nothing to worry about
`NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.15` - Latest version for Leia is 2.4.2, should be available from the libreelec repo.
Start there and see how you go.

**Comment by robustini** [comment]
@glennguy thanks for reply!
Unfortunately the distribution I'm using of LibreELEC cannot connect to its repo and I don't know why, so I can't install it, I'm trying to download the sources and compile it, but it's not trivial for me.
Why aren't "add-on from zip" installable versions released?

**Comment by glennguy** [comment]
I can see you're asking in the right thread on the libreelec forums. You're on the right track - you've got a S802 which is not officially supported so there won't be anything in the LibreELEC repo as you've found.

You'll need to ask the maintainer of your build nicely to compile the package for you, or you can compile it from the source which would seem to be [here](https://github.com/libretro/Lakka-LibreELEC)

I'm guessing your current version of inputstream.adaptive was copied from a previous installation, that would probably explain the segfault. You should close this issue as it's not to do with inputstream.adaptive itself.

**Comment by CastagnaIT** [comment]
if can help you can download compiled versions from jenkins
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/Leia/23/artifacts

**Comment by robustini** [comment]
Thanks for your help!

**Comment by robustini** [comment]
I can view the contents of VMTV.GO without any problem, they are also protected with Widewine, I can't understand where the problem it came from, 
Here the log with VMTV.GO that works, and Amazon VOD that resets Kodi instead, maybe you can understand where the problem lies:

[kodi_crashlog_20200108105603.log](https://github.com/peak3d/inputstream.adaptive/files/4035539/kodi_crashlog_20200108105603.log)

**Comment by robustini** [comment]
@CastagnaIT purtroppo Stefano nessuno di quei file è compatibile, o almeno quelli Arm7.
Questo è quello che sto usando, la 2.4.0.

[inputstream.adaptive_2.4.0.zip](https://github.com/peak3d/inputstream.adaptive/files/4035604/inputstream.adaptive_2.4.0.zip)

**Comment by CastagnaIT** [comment]
ciao scriverò in inglese perchè altrimenti gli altri non capiscono

first of all the logs are _incomplete_ because you haven't enabled kodi debugging
it would be useful to know what type of device and model you use

i think your libreelec installation, is not able to check update becouse of a python bad code development in one module
<pre>
2020-01-08 10:52:12.534 T:2680718192   ERROR: Traceback (most recent call last):
                                              File "/home/demetris/S8X/build.LibreELEC-MXIII_Plus.arm-LE9-Kodi_18.5/LibreELEC-settings-171142f0bfe5e0d875618b8b1f016c1355476691/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/updates.py", line 521, in check_updates_v2
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer
</pre>
maybe it's solved with a more update libreelec version?

In the first log there is a lot of this error:
<pre>
2020-01-08 00:02:29.945 T:2577040240  NOTICE: CVideoPlayerAudio::Process - stream stalled
</pre>

I don't know the exact problem that causes this error, 
but it's not a problem of InputStream, InputStream does not process content is only a bridge,
i think can be a network configuration problem,
or your hardware can not handle some type of codecs,
or there is a problem with LibreElec and your hardware

**Comment by robustini** [comment]
@CastagnaIT, I solved using another older build with Kodi 18.2 and the working LibreELEC repo.
