### ISSUE TITLE
Bug in choosing correct stream resolution with "auto" select option

### ISSUE THREAD

**Issue by Linkinsoldier** [peak3d/inputstream.adaptive#38]
Hi,

I am using the [Milhouse builds for Rpi3](https://forum.kodi.tv/showthread.php?tid=298461) and this bug has occured with 703, 707 an 711 (didnt test anything further). I did select the following settings in inpustream adaptive:

Min Bandwith: 0
Max Bandwith: 0
Max Resolution general decoder: Max
Max Resolution secure decoder: 720p (due to RPi3 limitations)
Selection: Auto

With this I started different streams: for TV Series it works pretty great with netflix, skygo and amazon, however movies do have different aspect ratios and I get problems with the selections. 

When I try to stream "Pitch Perfect 2" from Amazon (VOD) using Secure Decoding max 720p i get:
"Auto": 920x520
"Manuel":I get 1920x1040 (which is too much for the Rpi3) - but I can change it to 1280x688 and that works great!

I guess that inputstreams looks for 1280x720 but is only finding 1280x688 and therefore skipps to 920x520, because for tv series (basically every new series since 200x) with 1280x720 everything works great! How can I help further to debug this?

I twould be great to get the 1280x688 with the Auto Option!

Log from Kodi:
https://pastebin.com/PNY4wtBB

Maybe this is connected to this one? title sounds similar, but description does not...
https://github.com/peak3d/inputstream.adaptive/issues/9

**Comment by liberty-developer** [comment]
The reason is HDCP, in the current implementation I assume that there is no HDCP capability and therefore HD streams cannot be played. It seems that this is not true, I'll add an HDCP override button into the settings wich you can activate on your own risk.

**Comment by peak3d** [comment]
Implemented OverrideHDCP option until real GDCP check is implemented.

**Comment by Linkinsoldier** [comment]
Stream select now works for me, thanks!

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
