### ISSUE TITLE
Compile on windows 10?

### ISSUE THREAD

**Issue by Jujudo** [peak3d/inputstream.adaptive#396]
How do I compile this on windows 10?

**Comment by Essam311** [comment]
@CastagnaIT Could you help with that? I too need to know the required software and the steps for compiling inputstream adaptive on windows 10.

**Comment by dagwieers** [comment]
Please collect information in [the Wik](https://github.com/peak3d/inputstream.adaptive/wiki)i so we can maintain it together going forward.

**Comment by Jujudo** [comment]
I solved it!

`git clone -b Leia https://github.com/xbmc/xbmc.git
git clone https://github.com/peak3d/inputstream.adaptive
cd inputstream.adaptive && mkdir build && cd build
cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
`

after all those commands, open and compile ALL_BUILD.vcxproj

**Comment by Essam311** [comment]
@Jujudo Thank you so much, this worked for me with Visual Studio 2019 Community Edition.

**Comment by glennguy** [comment]
@Essam311 It seems the debug version is being built. In my experience it won't work if you share it with others. Try this after the previous steps in @Jujudo 's post (but I think before opening VS and running ALL_BUILD) to get a release build:
(in your inputstream.adaptive/build folder)
```cmake --build . --config Release --target inputstream.adaptive```
To get a zip file:
```
cd inputstream.adaptive-prefix/src/inputstream.adaptive-build
cpack
```

If you are looking to modify code then after building ALL_BUILD, close the VS solution and open the new solution `inputstream.adaptive.sln` in the `inputstream.adaptive-prefix/src/inputstream.adaptive-build` folder. 

For development you can save yourself a lot of hassle by pointing cmake to install the files directly into your Kodi addons folder. Add `-DCMAKE_INSTALL_PREFIX=../../../../AppData/Roaming/Kodi/addons` (depending on where your current working folder is, adjust to suit or even provide an absolute path) to the command in @Jujudo 's post. Then build the INSTALL project in VS after any modifications.

**Comment by Essam311** [comment]
@glennguy Thank you so much, your instructions worked perfectly, and I was able to compile inputstream.adaptive without the need to open Visual Studio 2019, and inputstream.adaptive files are in its regular sizes.

**Comment by Jujudo** [comment]
Awsome, I close this tho 👍

**Comment by Essam311** [comment]
@CastagnaIT Thank you so much for adding how to build inputstream.adaptive on windows to the wiki, I think Visual Studio 2019 need to be added to the prerequisites.

**Comment by CastagnaIT** [comment]
i do not use Visual Studio

**Comment by Essam311** [comment]
@CastagnaIT When I try to use the instructions from the wiki on windows 64bit I get this message.

<img width="456" alt="556" src="https://user-images.githubusercontent.com/59211054/76760000-88bb8480-6795-11ea-91a6-b777dbe801dc.png">

**Comment by Essam311** [comment]
@CastagnaIT I added it, when I tried to compile inputstream.adaptive on a windows without visual studio being installed on it I got this message.

<img width="456" alt="556" src="https://user-images.githubusercontent.com/59211054/76776921-12784b80-67b0-11ea-88e1-4e8803c74a4b.png">

**Comment by peno64** [comment]
I added the compilation instructions in the wiki to compile for rasperry pi
