### ISSUE TITLE
inputstream.adaptive on Odroid C2

### ISSUE THREAD

**Issue by iz8mbw** [peak3d/inputstream.adaptive#4]
Hi.
I'm running Kodi 17 beta 5 (LibreELEC) on Odroid C2 (ARM aarch64).
I would like to install the "inputstream.adaptive" addon to enjoy the YouTube addon with MPEG-DASH but it seem that this addon is not available....

Is it normal that "inputstream.adaptive" add-on is not available for Odroid C2?

Thanks.

**Comment by Raybuntu** [comment]
The addon is included in LE alpha 7.90.009 with Kodi 17 beta 6. Download from the LE website or update.

**Comment by iz8mbw** [comment]
Thanks, it works!
I close it.
