### ISSUE TITLE
OpenDemuxStream - Error creating demuxer for .strm files

### ISSUE THREAD

**Issue by troych** [peak3d/inputstream.adaptive#40]
Hi there,

I've tried creating and playing back a .strm file according to the readme here, but I struggle to make it work. Tried with 2 different mpd Manifests, both didn't work. I'm pretty sure inputstream.adaptive works correctly otherwise, I can, for example, play back netflix content via the netflix addon.

I can make one of the Manifests work with latest VLC nightly, so I know at least the one in the readme provided here should work.

Debug log:  https://pastebin.com/dg1JPWYt
strm File: https://pastebin.com/s3KjMRgL

I'm running:
Kodi 18.0-ALPHA1 Git:20170731
inputstream.adaptive 2.0.5

Any idea where things go wrong for me?

**Comment by peak3d** [comment]
You have to tell kodi to use inputstream.adaptive.
Pls. add at first line in .strm file: 
#KODIPROP:inputstreamaddon=inputstream.adaptive

**Comment by troych** [comment]
Ha, it was that easy indeed, now I feel a little stupid. :) Thanks for the pointer in the right direction, I thought I only need to add one of the #KODIPROP options.
