### ISSUE TITLE
Un-canonical URLs with double slashes not recognized by some streaming servers (error 404)

### ISSUE THREAD

**Issue by basilgello** [peak3d/inputstream.adaptive#408]
Some streaming servers return error 404 if an URL has double slashes in path:

`https://domain.com/path/to/channel/stream.m3u8` is OK but
`https://domain.com/path/to/channel//stream.m3u8` reutrns 404.

To fix this, replace the string with 
https://github.com/peak3d/inputstream.adaptive/blob/Leia/src/main.cpp#L300
with:

` effective_url_.resize(paramPos);`

and append slashes when necessary

@peak3d need your comment about possible breakage of non-HLS parts.

**Comment by peak3d** [comment]
@basilgello pls. provide a sample m3u8 file

**Comment by basilgello** [comment]
Fixed in 2.5.5
