### ISSUE TITLE
Switching frame rate often results in freeze

### ISSUE THREAD

**Issue by maniacgit** [peak3d/inputstream.adaptive#41]
On Nvidia Shield if frame rate switching is enabled this often leads to a freeze or a running video without audio. It happens with different plugins which uses inputsream.adaptive but works with local content.
If trying several times, normally on the 2-3 try, it works and the video is played including audio.
Audio passthrough is enabled for everything if this matters.

In kodi.log the following appears.
`
18:18:14.297 T:138407871568  NOTICE: VideoPlayer: OnResetDisplay received
18:18:15.353 T:138809402448   ERROR: CAESinkAUDIOTRACK::AddPackets write returned error:  -12
18:18:15.353 T:138809402448   ERROR: CActiveAESink::OutputSamples - sink returned error
18:18:15.361 T:138809402448  NOTICE: Trying to open: 192000 samplerate 12 channelMask 13 encoding
18:18:15.364 T:138809402448   ERROR: AESinkAUDIOTRACK - Unable to create AudioTrack
18:18:15.364 T:138809402448  NOTICE: Trying to open: 192000 samplerate 12 channelMask 13 encoding
18:18:15.366 T:138809402448   ERROR: AESinkAUDIOTRACK - Unable to create AudioTrack
18:18:16.647 T:139109667920   ERROR: CDVDVideoCodecAndroidMediaCodec::AddData error(-10000)
`

I already had some similar issue with Nvidia graphic cards using vdpau on Linux. There it was caused by the player wanted to write to the device while the device was in a reset state caused by the framerate switch.

**Comment by troych** [comment]
Are you on a recent (3 Days) 18 Alpha version of Kodi? There was a refreshrate problem with exactly the issue you're describing here. Was fixed with this commit: https://github.com/xbmc/xbmc/commit/e0ce62d3c0a8fe7ae253acd59aa869ceac39f7b0

So may be worth updating Kodi to see if that fixes your problem.

**Comment by maniacgit** [comment]
Yes, I've updated to the most recent nightly before posting the bug report and tried it.

But you are right this looks like the same issue fixed for vdpau. I think something like this might be needed for DVDVideoCodecAndroidMediaCodec also.

**Comment by peak3d** [comment]
@maniacgit can you provide a sample stream wich switches during playback?

B.t.w: inputstream.adaptive for android is only demuxer, the video pipeline is identical to local content.
Is maybe encrypted DRM content played in your example? I don't know how DRM / HDCP behaves if the Monitor switches.

**Comment by maniacgit** [comment]
It was encrypted content which I've used to test it. The frame rate shouldn't change during the stream. But it seems the playback is started, then it recognizes that the stream frame rate doesn't match the current display frame rate and issues the switch. Due to the switch the decoder resets. Since this is already during playback the output surfaces become invalid, therefore the write failed. But it doesn't recover from that.

From your description about the video pipeline I think this has to be handled in Kodi directly.
I've had a fast look into the Kodi source for MediaCodec. The error in DVDVideoCodecAndroidMediaCodec::AddData is from the Android NDK. Kodi tries to queue a input buffer, but this fails with -10000 ( AMEDIA_ERROR_BASE).

**Comment by maniacgit** [comment]
https://pastebin.com/7AmZnyDf

**Comment by maniacgit** [comment]
This is the kodi.log of this try: https://pastebin.com/tJESZZ0f

I've recognized those two virtual functions which are called:
19:13:44.836 T:138407871568  NOTICE: VideoPlayer: OnLostDisplay received
19:13:44.836 T:138407871568  NOTICE: VideoPlayer: OnResetDisplay received

In vdpau those are implemented and releasing and reseting the decoder.
In DVDVideoCodecAndroidMediaCodec they aren't implemented, maybe here a reset of the decoder is also needed for MediaSurface?

**Comment by peak3d** [comment]
Thx, as expected we have HDCP / DRM Errors. Does this stream play if you disable refreshrate switching?

**Comment by peak3d** [comment]
Can you pls provide a full kodi log, debug enabled / video component debugging enabled (pls make sure that only video is checked, thx)?

**Comment by maniacgit** [comment]
Yes, without refreshrate switching it works every time.
With refreshrate switching it works on the 2-3 try, in very rare cases already on the first. It always switches, even on the tries when it's working.

I'll will create the log you've asked for.

**Comment by maniacgit** [comment]
I've created the kodi.log and send it to your mail address from your homepage.

**Comment by peak3d** [comment]
Ok, will look into this issue

**Comment by peak3d** [comment]
can we close this issue @maniacgit ? Fixes were done in kodi core for this....
