### ISSUE TITLE
Media headers not initialized on stream URL parse

### ISSUE THREAD

**Issue by basilgello** [peak3d/inputstream.adaptive#411]
The parsing logic of headers kodiprop assigns the media headers (used to request segments of a HLS playlist):

https://github.com/peak3d/inputstream.adaptive/blob/master/src/main.cpp#L3123

however the URL headers parser:

https://github.com/peak3d/inputstream.adaptive/blob/master/src/main.cpp#L3161

is missing the `medh = manh` causing error 403 on segment downloads.

The proposed fix was tested on self-built 2.4.3 (Leia).

**Comment by peak3d** [comment]
The logic is:

- If mediaHeaders are given: use it for both medh and manh
- If headers are only given in URL (with |), use it for manh
- If both are given, use mediaheaders for medh and use URL headers for manh

-> If I read your request correctly, you simply have to remove your headers from URL and use mediaheaders property instead.

**Comment by basilgello** [comment]
The fix has been added to pvr.iptvsimple version 4.11.7.
