### ISSUE TITLE
Add Support for SupplementalProperty schemeIdUri="urn:scte:dash:utc-time"

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#412]
Hi,

would it be possible to support the below tag in mpd file:

`<SupplementalProperty schemeIdUri="urn:scte:dash:utc-time" value="2020-03-28T23:22:52.396Z"></SupplementalProperty>`

Without support for this, IA calculates the wrong segment number (too far ahead) and can't play some streams (404).

I guess IA needs to use the value from that instead of current unix time and calculate the starting segment from that.

**Comment by matthuisman** [comment]
Also looks like there may be a <UTCTiming element as well...
https://github.com/google/shaka-player/issues/386#issuecomment-227898001

**Comment by matthuisman** [comment]
looking at the browser player (that works)

`<SupplementalProperty schemeIdUri="urn:scte:dash:utc-time" value="2019-10-23T06:32:50.733Z"></SupplementalProperty>
`
```
     <SegmentTemplate timescale="50000" media="index_video_$RepresentationID$_0_$Number$.mp4?m=1585505246" initialization="index_video_$RepresentationID$_0_init.mp4?m=1585505246" startNumber="2314617">
        <SegmentTimeline>
          <S t="698918036973" d="300000" r="299"/>
        </SegmentTimeline>
      </SegmentTemplate>

```
browser gets:  index_video_17_0_2314912.mp4?m=1585505246  which works

**Comment by matthuisman** [comment]
@peak3d 

Could you have a quick look at this?
I suspect it may start being used a lot more.

If it's simple enough to implement, could it be backported for 18?

**Comment by peak3d** [comment]
Hi, to get things right what you want me to do:
- remove publishTime
- replace availabilityStartTime by the new SupplementalProperty if available?

Issue is, that I'm quite sure that there are Manifest implementations which do not work if publishTime / baseTime is not set. Unfortunately there are different players around, IIRC EuroSport or DAZN was quite special -> we need all addon devs for testing if we change this place.

I can do the implementation for Matrix, but backport only after almost all addon devs have tested

**Comment by glennguy** [comment]
I've found some relevant information that will hopefully set us in the right direction

From 4.7.2 in the most recent [DASH IF guidelines](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf)

> If the Media Presentation is dynamic or if the MPD@availabilityStartTime is present.....

> * The MPD should contain at least one UTCTiming element with @schemeIdUri set to one of the following:
>   * `mpeg:dash:utc:http-xsdate:2014`
>   * `mpeg:dash:utc:http-iso:2014`
>   * `mpeg:dash:utc:http-ntp:2014`
>   * `mpeg:dash:utc:ntp:2014`
>   * `mpeg:dash:utc:http-head:2014`
>   * `mpeg:dash:utc:direct:2014`

> * If the MPD does not contain any element UTCTiming then the segments shall be available latest at the announced segment availability time using a globally accurate timing source.

Now the example MPD provided by Matt doesn't contain a UTCTiming element, only the SupplementalProperty element, however it would appear to have the same purpose (Example from an MPD with a UTCTiming element: `<UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2020-04-02T03:31:04.000Z"></UTCTiming>` - doesn't have this issue though...). Considering that it's for AWS we can only imagine in the future it will see a lot of use from content providers so I think it would be wise to allow for either and treat the same.

In the case of no UTCTiming or SupplementalProperty we could use an external timing source as required by leveraging an additional ListItem property similar in working to media_renewal_url, then have the python add-on return UTC in a set format. In the absence of the list item property, fall back to the current implementation.

In addition to solving this issue it will solve many user playback issues arising from incorrect system clocks. An example being an add-on that I develop that only has segments available for 60 seconds has opened my eyes to plenty of devices out there that aren't regularly syncing system clocks to NTP.

@peak3d If this sounds workable to you I can work with @matthuisman to come up with the changes and submit a PR?

**Comment by peak3d** [comment]
This would be cool @matthuisman !! 👍
