### ISSUE TITLE
Shield Tv install error

### ISSUE THREAD

**Issue by n4tur3502** [peak3d/inputstream.adaptive#416]
I have been having issues getting this to install on my nvidia shield tv running kodi 18.6. I have managed to get it to install on my pc using the windows version of kodi 18.6 using the zip i got from the master on the leia release. Is there a different set of files that i need for the Shield to get it updated to 2.4.4?

**Comment by glennguy** [comment]
Try uninstalling IA (make sure it's definitely gone afterwards) then reinstall again from zip

**Comment by dagwieers** [comment]
Beware that Kodi requires a restart after updating or downgrading IA. Otherwise playback will fail silently.

**Comment by n4tur3502** [comment]
I cant seem to remove IA from the Shield version of Kodi. Theres only an option to update. When i try to install from the zip it always fails. And checking for updates via the add on it self states there no updates. right now its on 2.4.3 and its driving me nuts. Is there a way i can use the build instructions to build an android version of the add-on or do i have to build an android version of kodi with version 2.4.4 in it?

**Comment by lhassell** [comment]
I am having the same issue. Stuck on 2.4.5, KODI 18.6. 2015 Shield TV. Most of my apps work, but I'm getting 404 errors from Sling TV and was told it may be this issue.
