### ISSUE TITLE
wrong framerate parsed from mpd

### ISSUE THREAD

**Issue by fayer3** [peak3d/inputstream.adaptive#418]
playing this mpd (https://gist.github.com/fayer3/0ac278507cc319a779767c45d49f7295) with widevine shows the wrong framerate of 48000 in the player info and throws this error in the log: 
`2020-04-13 15:17:14.964 T:15016   ERROR: CVideoPlayerVideo::OpenStream - Invalid framerate 48000, using forced 25fps and just trust timestamps`
the video plays fine, but probably at the wrong framerate
it looks like it parsed the 'audioSamplingRate' as framerate
I'm using Inputstream.adaptive 2.4.4 on leia 18.6
![grafik](https://user-images.githubusercontent.com/8282299/79124106-e85c7e00-7d9b-11ea-8fa5-7d56eef509ce.png)

edit:
upon further inspection it seems the framerates specified in the mpd would be the wrong, even if parsed correctly. The actual framerate should be 23.97.

**Comment by peak3d** [comment]
In general we extract the information about the framerate from init segment if available (what is the case here). A debug log would be fine, or an kodi addon / strm file for reproduction

**Comment by fayer3** [comment]
sorry for the late reply here is a debug log, video the relevant part starts at line 1120
[kodi_debuglog_disneynow.log](https://github.com/peak3d/inputstream.adaptive/files/4754724/kodi_debuglog_disneynow.log)
and here is the addon, needs a video id from disneynow.com and requires an US IP
[plugin.video.disney_now-test.zip](https://github.com/peak3d/inputstream.adaptive/files/4754770/plugin.video.disney_now-test.zip)

**Comment by peak3d** [comment]
I analyzed the video stream "G" (bandwidth="1480429" codecs="avc1.4d001f" frameRate="30" height="594" id="G" scanType="progressive" width="1056") and in the initialization we retrieve 48000 as fps :-(.
I'll change the code that such values are not taken in future, but this means that we start playing the movie with 30fps. 
There are no more information about fps during initialization

**Comment by glennguy** [comment]
I think this is fixed already
