### ISSUE TITLE
HLS WINEVINE (MOVIES ANYWHERE) support?

### ISSUE THREAD

**Issue by 27hectormanuel** [peak3d/inputstream.adaptive#423]
Hi, @peak3d I am creating this issue as guidance on how to create a completely functioning add-on of [Movies Anywhere.](https://moviesanywhere.com/) I am a complete noobie on  the creation of addons. Therefore, I would appreciate support from this great community. 

The movie I am using as test will be "[Missing Link](https://moviesanywhere.com/movie/missing-link-2019)"

Let gets this working! 

Browser I am using: Edge Chromium Browser

Goals:

- **FULL PLAYBACK**
- **PROFILE SWITCHING**
- **LIBRARY INTEGRATION**
- **LOG IN INFORMATION**

Questions: how to begin! 
![Artboard_5_wt](https://user-images.githubusercontent.com/22853711/79499152-80ef3a00-7ff8-11ea-905a-92533bfe0813.jpg)

(US ONLY SEREVICE)

**Comment by 27hectormanuel** [comment]
DATA GATTERED: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:ns2="http://www.w3.org/1999/xlink" xmlns:mspr="urn:microsoft:playready" xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" mediaPresentationDuration="PT1H34M25.701709S" minBufferTime="PT10S"><Period duration="PT1H34M25.701709S"><AdaptationSet id="1" group="1" lang="en" contentType="audio" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" audioSamplingRate="48000" mimeType="audio/mp4" codecs="mp4a.40.5" startWithSAP="1"><AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/><Label lang="en">English Stereo</Label><Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/><Representation id="English Stereo" bandwidth="97000"><BaseURL>sd/audio/en/1567103647490/stereo_aac_96k.mp4</BaseURL><SegmentBase timescale="24000" presentationDuration="135984128" indexRange="660-17695" indexRangeExact="true"><Initialization range="0-659"/></SegmentBase></Representation></AdaptationSet><AdaptationSet id="2" group="2" contentType="video" par="427:240" minBandwidth="165000" maxBandwidth="1980000" minHeight="2147483647" maxHeight="0" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" width="854" height="480" sar="1:1" frameRate="24000/1001" mimeType="video/mp4" codecs="avc1.64001F" startWithSAP="1"><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="78BD13D1-5231-4BBA-B55C-D570F290399D"/><ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95" value="MSPR 2.0"/><ContentProtection schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED"/><Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/><Representation id="video=105872" bandwidth="893000" width="854" height="480" scanType="progressive"><BaseURL>sd/video/en/1567103647490/df7265ba-a2ca-43fc-9e87-9f0d74b5ddc8_1567103647490_900k_sd_video.mp4</BaseURL><SegmentBase timescale="96000" presentationDuration="543907364" indexRange="1535-18558" indexRangeExact="true"><Initialization range="0-1534"/></SegmentBase></Representation><Representation id="video=81704" bandwidth="165000" width="416" height="234" scanType="progressive"><BaseURL>sd/video/en/1567103647490/df7265ba-a2ca-43fc-9e87-9f0d74b5ddc8_1567103647490_160k_sd_video.mp4</BaseURL><SegmentBase timescale="96000" presentationDuration="543907364" indexRange="1534-18557" indexRangeExact="true"><Initialization range="0-1533"/></SegmentBase></Representation><Representation id="video=85448" bandwidth="401000" width="640" height="360" scanType="progressive"><BaseURL>sd/video/en/1567103647490/df7265ba-a2ca-43fc-9e87-9f0d74b5ddc8_1567103647490_400k_sd_video.mp4</BaseURL><SegmentBase timescale="96000" presentationDuration="543907364" indexRange="1535-18558" indexRangeExact="true"><Initialization range="0-1534"/></SegmentBase></Representation><Representation id="video=115656" bandwidth="1381000" width="854" height="480" scanType="progressive"><BaseURL>sd/video/en/1567103647490/df7265ba-a2ca-43fc-9e87-9f0d74b5ddc8_1567103647490_1400k_sd_video.mp4</BaseURL><SegmentBase timescale="96000" presentationDuration="543907364" indexRange="1535-18558" indexRangeExact="true"><Initialization range="0-1534"/></SegmentBase></Representation><Representation id="video=126304" bandwidth="1980000" width="1024" height="576" scanType="progressive"><BaseURL>sd/video/en/1567103647490/df7265ba-a2ca-43fc-9e87-9f0d74b5ddc8_1567103647490_2000k_sd_video.mp4</BaseURL><SegmentBase timescale="96000" presentationDuration="543907364" indexRange="1533-18556" indexRangeExact="true"><Initialization range="0-1532"/></SegmentBase></Representation></AdaptationSet><AdaptationSet id="3" group="3" lang="en" contentType="text" mimeType="text/vtt" startWithSAP="1"><Label lang="en">English Forced Subtitles</Label><Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/><Representation id="3_textstream_eng=0" bandwidth="0"><BaseURL>subtitles/en/1562597051304/forced.vtt</BaseURL></Representation></AdaptationSet><AdaptationSet id="4" group="3" lang="en" contentType="text" mimeType="text/vtt" startWithSAP="1"><Label lang="en">English Subtitles</Label><Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/><Representation id="4_textstream_eng=0" bandwidth="0"><BaseURL>subtitles/en/1562597057857/full.vtt</BaseURL></Representation></AdaptationSet><AdaptationSet id="5" group="3" lang="es-419" contentType="text" mimeType="text/vtt" startWithSAP="1"><Label lang="es-419">Spanish Subtitles</Label><Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/><Representation id="5_textstream_es-419=0" bandwidth="0"><BaseURL>subtitles/es-419/1562597028363/full.vtt</BaseURL></Representation></AdaptationSet></Period></MPD>`

**Comment by 27hectormanuel** [comment]
@matthuisman I would appreciate your help in this project! You have done a great job with the Disney Plus & you're a professional python coder. I am a  total noob...


with an overglanced interpretation of the website code, I believe the playback resolution is based on standard resolution (480p)

**Comment by matthuisman** [comment]
Github issues arnt the place to ask for help building addons. You need to ask in the kodi forums :)

**Comment by 27hectormanuel** [comment]
> Github issues arnt the place to ask for help building addons. You need to ask in the kodi forums :)

Thank you! There's a forum [here](https://forum.kodi.tv/showthread.php?tid=353522&pid=2940917#pid2940917) Either way, please guide me. ;)
