### ISSUE TITLE
There is no mpd file, how to set the video stream url and audio stream url to let it play?

### ISSUE THREAD

**Issue by zhengfan2014** [peak3d/inputstream.adaptive#431]
Video Stream: https: //upos-hz-mirrorakam.akamaized.net/upgcxcode/08/03/173880308/173880308-1-30080.m4s

Audio stream: https: //upos-hz-mirrorakam.akamaized.net/upgcxcode/08/03/173880308/173880308-1-30280.m4s

Any reply is greatly appreciated

**Comment by peak3d** [comment]
inputstream.adaptive is for segmented streams. I think best would be a hls playlist (master and 2 sub m3u8 files) and play it directly in kodi without inputstream.adaptive.
