### ISSUE TITLE
dash subtitles not loaded without contentType

### ISSUE THREAD

**Issue by fayer3** [peak3d/inputstream.adaptive#432]
Subtitles are not selectable in the player, even though they are listed in the mpd as follows:

```
<AdaptationSet group="3" lang="de" mimeType="text/vtt">
  <SegmentTemplate timescale="10000000" media="$RepresentationID$/$Time$.vtt">
    <SegmentTimeline>
      <S t="15882530231240000" d="60000000" r="96"/>
    </SegmentTimeline>
  </SegmentTemplate>
  <Representation id="daserste-de-hd_subtitle_01/vtt" bandwidth="52"/>
</AdaptationSet>
```

this is probably because no contentType is specified and the dashtree parser only checks if the content type is "text" 
https://github.com/peak3d/inputstream.adaptive/blob/36a2cff058c0c3febd9a8c0b2fc7315ed6b5312b/src/parser/DASHTree.cpp#L669-L672

**Comment by peak3d** [comment]
@fayer3 there have been some changes in the last days. You can check if it works for you using Kodi 18.7.1

**Comment by fayer3** [comment]
just tested with Kodi 18.7.1 and latest inputstream commit and it works now
