### ISSUE TITLE
MDP/DASH/DRM with segment return HTTP 404 for the video and audio.

### ISSUE THREAD

**Issue by wwark** [peak3d/inputstream.adaptive#439]
Hi,

I worked for this plugin https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore which using inputstream.adaptive for playing mpd content DRM protected or not.

Since two days, we have experience HTTP 404 while playing this kind of mpd.
[6play_mpd.zip](https://github.com/peak3d/inputstream.adaptive/files/4599316/6play_mpd.zip)
This channel change his mpd format.

You will find below the errror we have:
[kodi_log.zip](https://github.com/peak3d/inputstream.adaptive/files/4599365/kodi_log.zip)
This log is a test with kodi 18.6 and inpustream.adaptive 2.4.4.
> 2020-05-08 14:11:56.677 T:140286583895808   ERROR: AddOnLog: InputStream Adaptive: Download https://live.quortex.bedrock.tech/6play/short/enc/m6/sd/audio-fre-96000/segment_107135.m4s failed with error: 404

We made also the same test with the last nigthly of kodi 19 and inputstream.adaptive 2.5.6. The error HTTP 404 remains.

Thanks for your help.
Do not hesitate if you need more informations.

Wwark

@SylvainCecchetto

**Comment by dagwieers** [comment]
@wwark We have found it helps to test streams against a bunch of manifest validators and players. We have collected a few here: https://github.com/add-ons/best-practices/wiki/Streaming-issues

It can help to find issues with manifests, or confirms that other players have similar issues, or gracefully accept issues instead :-) Feel free to add more resources if you have any.

**Comment by wwark** [comment]
Thank you for those tests player.
I will make some test but I need to get drm key. It is not easy because depends of certain header set and the return of the DRMkey are base64 encoded and the key is on a JSON ....

First point regarding the test from https://conformance.dashif.org/
I have those returns (mdp error log):

> ***Legend: Errors, Warnings, Information ***
>Start XLink resolving
>=====================
>XLink resolving successful
>Start MPD validation
>====================
>MPD validation successful - DASH is valid!
>Start Schematron validation
>===========================
>Schematron validation successful - DASH is valid!
>Start HbbTV-DVB Validation
>===========================
>###'HbbTV check violated: Section E.2.2 - If there is more than one audio AdaptationSet, exactly one shall be labelled with Role@value 'main' ', but found 3 Role@value 'main' in Period 1 

I confirm there is 3 audio stream and all have the role "main".

**Comment by wwark** [comment]
![Screenshot from 2020-05-08 17-47-07](https://user-images.githubusercontent.com/469461/81422974-1000f500-9154-11ea-8cf7-baea39b93120.png)
![Screenshot from 2020-05-08 17-47-41](https://user-images.githubusercontent.com/469461/81422984-12fbe580-9154-11ea-9df9-618c63dfd30d.png)
I don't understand this error I get from the log of each representation.
Does it mean the DRM is not configured ?

**Comment by wwark** [comment]
I tried also this https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html
The DRM url with all headers like the plugin.

I get this error.
![Screenshot from 2020-05-08 18-01-14](https://user-images.githubusercontent.com/469461/81424359-1b552000-9156-11ea-8415-8f54d45030d7.png)

For information, to get the DRM, the format on kodi is:
URL_LICENCE_KEY_LIVE = 'https://lic.drmtoday.com/license-proxy-widevine/cenc/|Content-Type=&User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36&Host=lic.drmtoday.com&Referer=https://www.6play.fr/m6/direct&x-dt-auth-token=%s|R{SSM}|JBlicense'

So I need to set an auth token and get the drm key in the json return by the server.
Do you know if a tool can support it ?

**Comment by dagwieers** [comment]
@wwark No sorry. DRM does complicate things. I do not have experience on how to further troubleshoot this. But if you figure it out, it would be good to document the process for others.

**Comment by peak3d** [comment]
@wwark most probably we calculate the wrong segment number and try to load segments long in the past / in the future. You can verify this by playing the stream in the web browser, and look in network traffic (press F12 in Chrome). You can then compare the segment number (part of the URL) with the numbers IA calculates. They should be not much different if you start the stream nearly at the same time.

**Comment by sy6sy2** [comment]
Hi peak3d, thank you for looking at this issue.

I can confirm what you said. I started the live stream "at same time" on Kodi and on Chrome.

* On chrome: segment_469043
* On Kodi: segment_934858
* Delta ~ 465 815

Second run:

* Chrome: segment_469085
* Kodi: segment_934945
* Delta ~ 465 860

Do you think that IA calculates the wrong segment number?

**Comment by peak3d** [comment]
Yes, what does it need to get something for reproduction?
.strm file? addon?

**Comment by wwark** [comment]
Hi Peak3d,
Thank you !
The stream needs an account. You need to register to 6play (https://www.6play.fr/)
The addon Catch-up-TV-and-More is available in the kodi repo.
The 6play account can be fill to t the settings on our addon.
To test the streamn 'M6 Live TV', you have to go to Live TV -> France -> M6.

Edit : The stream is geolocated to France.

Thanks again.

**Comment by peak3d** [comment]
Can you write me an email (email from this git account)?

**Comment by wwark** [comment]
email sent hope it is good !

**Comment by wwark** [comment]
Thanks a lot for the fix.
Tested on Kodi 19 and Kodi 18 with the last commit on leia branch.
I closed this ticket.
