### ISSUE TITLE
How to send Headers with licence and also with mpd link using #KODIPROP header?

### ISSUE THREAD

**Issue by ghost** [peak3d/inputstream.adaptive#447]
crmid: 89234792
appKey: 2ccce09e59153fc9
versionCode: 323
appId: vod
userId: ty9789
Accept-Encoding: gzip
Connection: Keep-Alive

**Comment by glennguy** [comment]
Try similar to this:
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.stream_headers=crmid=89234792&appId=vod.... etc.
#KODIPROP:inputstream.adaptive.license_key=https://example.com/wvlic|crmid=89234792&appId=vod.... etc.
https://example.com/stream.mpd
```
You might need to call Accept-Encoding AcceptEncoding (without the dash) The dash/hyphen is normally fine, just for this particular header.
Also header values need to be percent encoded i.e space becomes %20 etc.

Turn on debug logging and curl logging to check what's happening if you're not having much luck

**Comment by ghost** [comment]
Thanks brother it worked 🙂

**Comment by ghost** [comment]
hi when i am trying to pass same headers with both licence and mpd its not working now

#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.stream_headers=crmid=89234792&appId=vod.... etc.
#KODIPROP:inputstream.adaptive.license_key=https://example.com/wvlic|crmid=89234792&appId=vod|R{SSM}|
https://example.com/stream.mpd



this one is working but headers only passing through mpd link not with license
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://example.com/wvlic|crmid=89234792&appId=vod|R{SSM}| https://example.com/stream.mpd|crmid=89234792&appId=vod....
