### ISSUE TITLE
Issue with WEBVTT subtitles

### ISSUE THREAD

**Issue by Dis90** [peak3d/inputstream.adaptive#452]
Inputstream adaptive version 2.4.5 seems to support HLS subtitles and subtitles does show in subtitles listing in Kodi using my Dplay addon but nothing shows up in screen. Subtitles are in WEBVTT format. 

Any ideas why subtitles doesn't work?

Kodi.log https://paste.kodi.tv/awosegovid.kodi
Example subtitle https://paste.kodi.tv/felamotoki

**Comment by Dis90** [comment]
Subtitles works in older episodes that are aired before Dplay launch. After that seems to be in different format.

Example working subtitle https://paste.kodi.tv/xomezelugu

**Comment by Dis90** [comment]
So working format is:
```
WEBVTT

1
00:00:20.280 --> 00:00:26.440
TÃ¤ssÃ¤ ohjelmassa autot saavat toisen
tilaisuuden. MinÃ¤ ostan ne...

2
00:00:26.520 --> 00:00:31.320
Ja minÃ¤ kunnostan.
Sitten myymme ne hyvÃ¤llÃ¤ voitolla.
```

And non working is:
```
WEBVTT

00:06.160 --> 00:12.960
Haluan lÃ¶ytÃ¤Ã¤ paikan, jossa on
paljon kultaa tai isoa kultaa.

00:14.400 --> 00:20.840
Parker Schnabelin tavoitteena
on laajentaa reviiriÃ¤Ã¤n Australiaan.
```

Is this Kodi issue or issue with Inputstream Adaptive?

**Comment by redfightggm** [comment]
My problem with HLS WEBVTT subtitles is The subtitles only work at the beginning. After about 2-3 minutes, will not work (Inputstream adaptive version 2.4.5 + kodi Leia)

**Comment by Sopor** [comment]
I didn't know it was supported at all #183. It has never worked in Retrospect.

**Comment by dagwieers** [comment]
Maybe this is related to your problem #456 ?

**Comment by peak3d** [comment]
@Dis90 can you pls. disable all component debug logging and update the log file in first post? Thanx.
beside this you should try (at least for verification) 18.7.1 version, or even better kodi master (after backupping your current kodi leia userdata flder)

**Comment by Dis90** [comment]
New log (also disabled all logging from my addon): https://paste.kodi.tv/arejadakoh.kodi
Tested with latest Leia nightly build.

**Comment by peak3d** [comment]
@Dis90 there is currently no implementation of single - file webvtt subtitles.
It is supported from core code, but must be tagged correctly in HLS parser - I'll try to get it in soon.

**Comment by peak3d** [comment]
@Dis90 it was something different: https://github.com/peak3d/inputstream.adaptive/commit/cc30b2a7dc699d577e1eec094ae873543eb1b485 should fix your issue.

**Comment by peak3d** [comment]
One more commit was finally needed, not sure if I was fast enough for kodi nightly....

**Comment by Dis90** [comment]
Can you backport those changes to Leia? :)

**Comment by peak3d** [comment]
done.

**Comment by Dis90** [comment]
In videos what are longer than 1 hour, last subtitle segment before 1 hour mark starts repeating after 1 hour. Correct segment is also displayed. Problem goes away after seeking video.

**Comment by peak3d** [comment]
@Dis90 does it also appear if you seek to ~ 59mins and then wait for the hour switch?

**Comment by Dis90** [comment]
@peak3d Yes it does.

**Comment by Dis90** [comment]
@peak3d Any updates?

**Comment by Dis90** [comment]
@peak3d do you have time to check this issue?

**Comment by peak3d** [comment]
@Dis90 di I read correctly they provide subs without hours for streams wich are longer than 1 hour?

**Comment by Dis90** [comment]
Yes there's hours. Example subtitle file https://paste.kodi.tv/wohicagica

**Comment by peak3d** [comment]
> In videos what are longer than 1 hour, last subtitle segment before 1 hour mark starts repeating after 1 hour. Correct segment is also displayed. Problem goes away after seeking video.

I don't really understand what you mean. What is "last subtitle segment" and what do you mean with "repeat" ?

Edit: What I see from code is that the last subtitle before 1 hour in the flie you linked will be not read.

**Comment by Dis90** [comment]
What I mean is that this line:
59:59.480 --> 1:00:06.080
Kirjoitan sinulle sekin ja ostan
lipun Dominikaaniseen tasavaltaan.

Shows on screen every time when new subtitle line is displayed.

It's hard to describe. Do you wan't me to record video of the problem?

**Comment by peak3d** [comment]
ah, ok, I was in opinion that it would be simply ignored, ok, I'll look at it

**Comment by peak3d** [comment]
The fix is in Matrix branch, and will be released for 19.x in the next days:
8d9d5d9124233c675b588cbcb4786e632f7049c0

**Comment by peak3d** [comment]
I'll backport for the upcoming 18.9
