### ISSUE TITLE
Subtitles won't work right away on TV4Play when using Retrospect

### ISSUE THREAD

**Issue by Sopor** [peak3d/inputstream.adaptive#458]
When watching videos from TV4Play using Retrospect the subtitles won't work right away. It seems that there are two subtitles, one unknown and one swedish and to get it to work i need to change it from Swedish to Unknown and then back to Swedish.

![image](https://user-images.githubusercontent.com/5789283/83570728-d9d24d80-a526-11ea-96e2-50919ef579e5.png)

![image](https://user-images.githubusercontent.com/5789283/83570742-df2f9800-a526-11ea-91d6-0ebedeea9be9.png)

According to the author of Retrospect it is Inputstream Adaptive that causing it.

**Comment by Sopor** [comment]
In issue #183 it was using webvtt in parts but it was possible to get the webvtt in one file and that is what Retrospect now use on TV4 to get subtitles, but for some reason IA do something wrong and show it as two subtitle files.

Let me know if you need log files and what you need me to debug.

**Comment by dagwieers** [comment]
Maybe this is related to your problem #456 ?

**Comment by peak3d** [comment]
Pls. provide a kodi debug log (after trying the latest kodi Leia or master nightly)

**Comment by Sopor** [comment]
[Kodi 18.7 debug log](https://paste.kodi.tv/joniseredi.kodi)

**Comment by peak3d** [comment]
@Sopor just curious: Are there still 2 sub streams in selection box? From debug log only one (valid) sub stream is found.

**Comment by Sopor** [comment]
Yes, there are two as in the above pictures and i change between them as i describe i have to do to make it work.

**Comment by peak3d** [comment]
@Sopor the version you have used when posting the screenshot seems to not contain the latest changes made in inputstream.adaptive. because of that I asked you to verify with the latest Leia nightly.

```
2020-06-06 04:07:51.554 T:16040   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1001)
2020-06-06 04:07:51.554 T:16040   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1002)
2020-06-06 04:07:51.554 T:16040   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1003)
2020-06-06 04:07:51.554 T:16040   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1001 with codec_id 27
2020-06-06 04:07:51.554 T:16040   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1002 with codec_id 86018
2020-06-06 04:07:51.554 T:16040   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1003 with codec_id 96264
```
But all this retrospect things start to turn getting complcated, either the addon overwrites IA settings or / and most likely pushes also external subs to kodi.

Pls. post these issues in the retrospect addon git, thx!

**Comment by Sopor** [comment]
The Retrospect author told me to report it here. He only send the stream to IA. That was what he told me.

> Pls. provide a kodi debug log (after trying the latest kodi Leia or master nightly)

You told my to use the latest Leia and i did. Latest master is not Leia, that is Matrix.

**Comment by peak3d** [comment]
I don't have any clue what the retrospect addon is doing, and not the time to figure it out, sry:

```
020-06-06 04:07:51.971 T:16040   DEBUG: CUtil::GetExternalStreamDetailsFromFilename - Language = '' / Name = '(External)' / Flag = '0' from
2020-06-06 04:07:51.971 T:16040  NOTICE: Closing stream player 3
2020-06-06 04:07:51.971 T:16040   DEBUG: AddOnLog: InputStream Adaptive: EnableStream(1003: false)
2020-06-06 04:07:51.971 T:16040  NOTICE: Opening stream: 0 source: 1024
2020-06-06 04:07:51.971 T:16040   DEBUG: CDVDOverlayCodecFFmpeg::Open - Unable to find codec 0
2020-06-06 04:07:51.971 T:16040   ERROR: CVideoPlayerSubtitle::OpenStream - Unable to init overlay codec
```

**Comment by basrieter** [comment]
The thing here is that Retrospect sets an external subtitle (retrieved from a different url). The stream also has subtitles in the manifest. The one from the manifest are the "Swedish" ones, the "Unknown" external one, is the one Retrospect sets. 

Both are valid subtitles, but apparently Kodi, or InputStream, has a problem pre-selecting a default one?

**Comment by peak3d** [comment]
external sub is handled after IA setup, the workflow is:

- mpd stream is opend, Video+Audio+Sub are selected correctly from mpd
- External sub is found by kodi -> mpd sub is deactivated, external sub is used instead
- External sub is not working correctly (for reasons I don't know)

Nothing wrong so far. Question is if retrospect really provides a vaild external sub, from log I say NO. Maybe it helps simply deactivating external subs in kodi settings.

**Comment by basrieter** [comment]
Interesting analysis. @Sopor can you post a debug retrospect.log and kodi.log for such a situation. Then we can compare both sides? Because I think it does pass a path to a downloaded subtitle. But let's double check?

**Comment by Sopor** [comment]
@basrieter 
[Kodi debug log](https://paste.kodi.tv/beyizaziti.kodi)
[Retrospect trace log](https://paste.kodi.tv/epeyedehix.kodi)

**Comment by basrieter** [comment]
Ok, I see where this is failing. Somehow an empty string is passed as a subtitle by Retrospect. Odd. Let me figure out where it comes from. Never seen it before, but I did refactor that code a while ago.
