### ISSUE TITLE
"Ignore display resolution" need to be enabled to get 1920x1080 resolution

### ISSUE THREAD

**Issue by Sopor** [peak3d/inputstream.adaptive#459]
When i watch play sites with the add-on Retrospect i only get SD resolution when i watch in Windows but if i run the exact same video on my Vero 4K+ on my TV it is running at 1920x1080.

I have Kodi 18.6 on my Vero and in Windows i have tested Kodi 18.6, 18.7 and 19.0 and they all show SD resolution.

![image](https://user-images.githubusercontent.com/5789283/83574118-199c3380-a52d-11ea-9b0c-6c64defbde07.png)

To get it to work i'm forced to enable `Ignore display resolution` and all other settings are default.

I'm running Windows 10 and 1920x1080@144Hz.

Kodi is running in full screen at 1920x1080.

![image](https://user-images.githubusercontent.com/5789283/83576285-ae089500-a531-11ea-96e1-2f449e900ca1.png)

**Comment by CastagnaIT** [comment]
have you check if the fullhd video streams exists in windows?
by set ISA `Stream selection `to `Manual video`
and when play a video open video settings and check the available streams

**Comment by Sopor** [comment]
After changing `Ignore display resolution` back to disabled it seems to play 1080 now, so i don't know why it play the correct stream now. I still get SD in Kodi 19.0:

![image](https://user-images.githubusercontent.com/5789283/83805422-29905080-a6b0-11ea-93a6-ba74af143a40.png)

If i do the same thing in Kodi 19.0, enable `Ignore display resolution` and then disable it again i get 1080. So it seems to be something that is not working as it should.

I deleted the settings.xml for IA and after rebooting Kodi (i always reboot Kodi after all changes i do to be sure it is working as it should) the video i played was in SD but when i restarted the same video it was now suddenly in 1080. It is very weird. It is very random.

**Comment by dagwieers** [comment]
Did you read this: https://github.com/peak3d/inputstream.adaptive#bandwidth-and-resolution ?
Maybe this mechanism is going wrong due to something specific (a bug?) on your system.

**Comment by CastagnaIT** [comment]
It's a strange symptom, i have two Windows os machine and one with all kodi versions
i never had this problem, so
or there is some wrong setting, then you can try delete kodi with deleting also kodi user data (and reinstall)
or is your hardware specific that cause issue

you could provide a full kodi log with kodi debug enabled after you tried to play a video

**Comment by M2k80** [comment]
maybe try to set minimum bandwith to 2000000000 in inputstream adaptiv settings, normaly that should fix it

**Comment by Sopor** [comment]
Yes, there are many different solutions for it, but they are all work-a-rounds. It should handle this without work-a-rounds. The easiest way is to do as the title says.

**Comment by basrieter** [comment]
> Yes, there are many different solutions for it, but they are all work-a-rounds. It should handle this without work-a-rounds. The easiest way is to do as the title says.

That makes no sense. The whole idea is to not retrieve more data than required. Why fetch 1080p if your resolution is 720p? If you don't want that, disable it via the settings and you are done.

**Comment by dagwieers** [comment]
> I'm running Windows 10 and 1920x1080@144Hz.
>
> Kodi is running in full screen at 1920x1080.

AFAIU he wants 1080p on a 1080p screen 😉

**Comment by dagwieers** [comment]
@Sopor Let met copy&paste the important bits from the [README](https://github.com/peak3d/inputstream.adaptive#bandwidth-and-resolution):

> **Bandwidth and resolution:**
>
> When using inputstream.adaptive the first time, the selection of stream quality / stream resolution is done with a guess of 4MBit/s. This default value will be updated at the time you watch your first movie by measuring the download speed of the media streams.
> Always you start a new video, the average bandwidth of the previous media watched will be taken to calculate the initial stream representation from the set of existing qualities.

4Mbps is not sufficient for 1080p and may also not be sufficient for 720p.

**Comment by peak3d** [comment]
Without kodi debug log file everything is guessing here.

**Comment by Sopor** [comment]
It seems to use many different resolutions according to the log file, but i leave it to the experts :)

What i did was:
1. Started Retrospect.
2. Played an episode of `Falsk identitet` and it was in SD resolution.
3. Stop playback.
4. Played another episode and it was now in 1080 and so was the rest of the episodes i tried to play.

[Here is the log file.](https://paste.kodi.tv/ifayacisob.kodi)

If it only happens once, why did i not get 1080 after my first run? I don't know why it works now...

Is this the file that will remember my bandwidth `bandwidth.bin` after the first run?

**Comment by peak3d** [comment]
AddOnLog: InputStream Adaptive: found inputstream.adaptive.max_bandwidth: 8000000
Please revert your max_bandwith setting (set it to 0) and try again

**Comment by Sopor** [comment]
All settings in IA are at 0 already. I haven't change any settings in inputstream.adaptive.

![image](https://user-images.githubusercontent.com/5789283/83943422-4e91da00-a7fc-11ea-8a71-1ef5e0167511.png)

**Comment by CastagnaIT** [comment]
the forced value of "inputstream.adaptive.max_bandwidth" is set to the played ListItem from the addon used (Retrospect ?) so this invalidate ISA settings...

**Comment by CastagnaIT** [comment]
by the way that addon seems to be forcing the behavior for max_bandwidth
and it is the possible cause of this problem

maybe the addon you use has a setting to be deactivated to avoid forcing a max bandwidth

**Comment by Sopor** [comment]
If i change the settings in Retrospect it will only be worse.

I have tested it several times now and it continues to play 1080 everytime (except the first time and that was done by design). I don't think we should spend more time to try to solve this. If it comes back i can always reopen it.

**Comment by CastagnaIT** [comment]
Retrospect override the max bandwidth so should be disabled:
https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/adaptive.py#L109

**Comment by dagwieers** [comment]
Maybe it would be good practice to indicate in the add-on settings which ones override IA settings to avoid such confusion. Maybe we could add it to the Add-ons best practices.

In the future, using the new settings.xml format, every setting can have a help text. For IA this help text could hint that add-ons could be overriding the IA setting.

**Update:** I added it to the Add-ons wiki [Settings](https://github.com/add-ons/best-practices/wiki/Settings) page, feel free to improve or open a discussion

**Comment by CastagnaIT** [comment]
@dagwieers FYI in integration wiki is specified the behaviour:
https://github.com/peak3d/inputstream.adaptive/wiki/Integration

Edit: i have updated a little wrong info

**Comment by dagwieers** [comment]
@CastagnaIT Maybe for those items (that could be configurable per add-on) we could recommend the settings text to have a consistent setting in add-ons, which includes a text that it overrides Kodi or IA settings?

*I specifically state Kodi here, because in our case the bandwidth limitation also affects Kodi player in our implementation when IA is disabled.*

**Comment by peak3d** [comment]
pls. clarify this first completely in retrospect addon github issue section, thx!

**Comment by dagwieers** [comment]
@peak3d I opened retrospect-addon/plugin.video.retrospect#1385
