### ISSUE TITLE
some HLS streams that do not play

### ISSUE THREAD

**Issue by L2501** [peak3d/inputstream.adaptive#46]
kodi 17 with 2.0.7
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8
http://playertest.longtailvideo.com/adaptive/eleph-audio/playlist.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8

**Comment by peak3d** [comment]
thx, will look at it

**Comment by peak3d** [comment]
The second one is not a m3u8 master playlist this is not supported.
One other of them has a .aac file extension, I have no demuxer for it and TBH no idea how to interpret this file.
The last one is not http accessible

**Comment by L2501** [comment]
does that mean that only HLS streams with variant playlists are playable with this?  streamlink for example has hlsvariant:// and hls:// stream types

**Comment by peak3d** [comment]
This is at least current development state.

inputstream.adaptive is thought for managing multi-bitrate streams (also the main part: switching, is still not implemented).

ffmpeg makes a good job for normal playlists, so I don't see any pressure to have it in inputstream.adaptive.
