### ISSUE TITLE
expat and build problem on windows question

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#464]
Hi @peak3d 
Every time i compile ISA on Windows, the build fails when it try to compile expat-build:

Compile Log: https://paste.kodi.tv/qocugasare.kodi

The only way to workaround this is every time revert this commit before run compile:

[depends] bump expat to 2.2.9 8259b7047718282adcaeaf6279080c7478b68f09

(this on both kodi version leia and matrix)

Can you give me any explanation? Am i missing something?

**Comment by peak3d** [comment]
No, sorry, I use windows, too, but compile ISA completely different

This is my cmake command:

```
cmake -DADDONS_TO_BUILD="inputstream.adaptive" -DADDON_SRC_PREFIX="D:\Dev\kodi-addons" -G "Visual Studio 15" -DCMAKE_INSTALL_PREFIX="D:\Dev\xbmc\build\addons" -DBUILD_DIR="D:\Dev\xbmc\build-addons" -DPACKAGE_ZIP=1 "D:\Dev\xbmc\cmake\addons"
```
This generates an sln for kodi addons, and after you compile first time, it generates a sln for inputstream.adaptive.

Most probably there is already an "old" expat version somewhere on your device, and it is found somehow by cmake (just guessing)

**Comment by CastagnaIT** [comment]
i tried your cmake command but same error
i have analyzed also che file created but i do not found nothing
...i will do the revert again
thanks anyway

**Comment by CastagnaIT** [comment]
Found the problem,
the problem is due to CMake localized with system language,
this cause the check_c_compiler_flag command in the expat/ConfigureChecks.cmake
to failing, and then broken the building

the only solution i found is delete all language packs of visual studio and keep only English language after this the buid works with success. (wiki updated)

I hope there is a better fix than this,
if you want keep your others language packs on visual studio i do not know how to do...

**Comment by glennguy** [comment]
@CastagnaIT are you saying if you install an additional language pack in VS then expat will always fail? i.e can I repro by installing Italian language?

**Comment by CastagnaIT** [comment]
yes so i do not know if check also the system language as reference,
i have italian on my windows 10 system, then i had installed VS with italian pack only,
i think you can reproduce with any non-english languages, try remove VS english pack and keep other language pack

**Comment by CastagnaIT** [comment]
documented on wiki
in any case this should be fixed by expat repo
