### ISSUE TITLE
HLS stream ending with unsupported stream error

### ISSUE THREAD

**Issue by sterd71** [peak3d/inputstream.adaptive#467]
Hi,

I'm trying to play a HLS stream via an addon.

This was working a week ago, but I've recently updated to Kodi 18.7 and it no longer works since the update.

The stream looks like it is going to play as the play icon appears in the corner, but then it terminates and drops me back to the list of items to play.

The addon is setting the stream as follows:
```python
play_item = ListItem(path=stream_url)
play_item.setProperty('inputstreamaddon' , 'inputstreamadaptive')
play_item.setProperty('inputstream.adaptive.manifest_type', 'hls')
play_item.setContentLookup(False)
setResolvedUrl(plugin.handle, True, listitem=play_item)
```
The HLS URL is:
https://eurosport-dlvr-ott.akamaized.net/primary/1/132c559a43e5430c8ea7ba6aef4b012a/start/1591927202/end/1591934401/index.m3u8?hdnts=ip=92.23.184.183~exp=1591970404~acl=/primary/1/132c559a43e5430c8ea7ba6aef4b012a/start/1591927202/end/1591934401/index.m3u8*~hmac=872b92b180a01124418340ae388498f6d4b38fd73792b10e94f326dadcef8fde

The stream is ending with:
`WARNING: OpenStream - Unsupported stream 1001. Stream disabled.`

I've attached my kodi log here:
https://paste.kodi.tv/boyeyizaqe

Inputstream.adaptive version is 2.4.5.

Any suggestions on what to do to get this to work again?

Thanks

**Comment by glennguy** [comment]
Hi @sterd71 
The fix is in the matrix branch but not yet in Leia.
As you're on Ubuntu you'll probably need to build from source if you don't want to wait, here is the commit for Leia with the required changes: https://github.com/peak3d/inputstream.adaptive/commit/ccce8b02815e95c2ecf8a2231fb79b745309bd62

**Comment by sterd71** [comment]
Excellent, thanks I'll give that a try.

**Comment by sterd71** [comment]
Hi,

After an upgrade to Kodi 18.8 this error has re-occurred.

Last time, I compiled inputstream.adaptive from source as advised and that corrected the issue for Kodi 18.7.

I've tried re-compiling from source again, but this time the problem still occurs.

There are also curl errors in the log just before the unsupported stream warning.

These curl errors didn't occur last time so they are new.

I've attached a copy of my log:
https://paste.kodi.tv/vapujahobu

Any help would be appreciated again.

Thanks

**Comment by glennguy** [comment]
Yes the download for the variant playlist is returning http 400 error - that's on your addon's side of things. You need to check the correct headers and such are being sent, compare with how it looks in your browser's Dev tools

**Comment by sterd71** [comment]
Hi,

I'm not sure that is the case.

The URL to play is passed into setResolvedUrl, everything after that is Kodi/inputstream.adaptive and is where the error occurs.

If I disable inputstream.adaptive, Kodi falls back to using ffmpeg, and the stream plays.

I've attached the log from an ffmpeg playback.
 
I can also paste the URL into VLC and it will play from there.

It's only inputstream.adaptive that is having an issue with the URL.

These properties are being set for each list item.  Is there an additional property that needs to be included?

```
item.setMimeType('application/x-mpegURL')
item.setProperty('inputstreamaddon','inputstream.adaptive')
item.setProperty('inputstream.adaptive.manifest_type', 'hls')
```

Thanks

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5040891/kodi.log)

**Comment by glennguy** [comment]
I think we need more info in the log
Could you turn on libcURL debugging in Kodi? After that you should be able to see when using IA vs ffmpeg which headers are being set.
As an example Inputstream.adaptive looks like it sets `Accept-Encoding: gzip` by default, not sure about ffmpeg.

**Comment by sterd71** [comment]
Hi Glenn,

Thanks for coming back to me.

This is the log for inputstream.adaptive:
https://paste.kodi.tv/izajoyerat

This is the log using ffmpeg:
https://paste.kodi.tv/rumixejope

I had a look at development tools like you suggested and couldn't see anything specific on the request that would make it work through a browser.

I can also successfully get a valid response using Postman and that only had the default headers set.

Thanks for your help.

**Comment by glennguy** [comment]
Can you post up your index.m3u8 ? I can get the variant playlists to download by removing the `?aws.manifestfilter=....` but not the main index.m3u8

**Comment by sterd71** [comment]
Hi Glenn,

I'm not sure if I can give you what you want.  There is only one index.m3u8 file and that is passed into setResolvedUrl.

The user is presented with a list of videos to play.  Each video has a unique identifier.

The identifier is used in this URL (698041) to retrieve the playback details of the video:

https://eu3-prod-direct.eurosportplayer.com/playback/v2/videoPlaybackInfo/698041?usePreAuth=true

This returns a JSON response containing URLs for a "dash" stream, a "hls" stream and an "ism" stream:
```yaml
{
  "data": {
    "attributes": {
      "markers": {
        "videoAboutToEnd": 26012000
      },
      "protection": {
        "clearkeyEnabled": true,
        "drmEnabled": false,
        "schemes": {
          "clearkey": {
            "licenseUrl": "https://discovery-eur.conax.cloud/fairplay/clearkey"
          }
        }
      },
      "reportProgressInterval": 60000,
      "sourceSystemId": "eurosport-e14773120c0ch717",
      "streaming": {
        "dash": {
          "url": "https://eurosport-dlvr-ott-vod.akamaized.net/primary/d3205b4da41248c7a4de0c09be0d12a0
/3d090bee39fd4281a3c749e4f7368f29/6f77a3bf97a1419989def8e0886ee06f/index.mpd?aws.manifestfilter=video_codec:h264
&hdnts=ip=85.211.254.200~exp=1597383005~acl=/primary/d3205b4da41248c7a4de0c09be0d12a0
/3d090bee39fd4281a3c749e4f7368f29/6f77a3bf97a1419989def8e0886ee06f
/index.mpd%3Faws.manifestfilter%3Dvideo_codec%3Ah264*~hmac=c377aca510ca6bf4f1a99594bfa4b9ab38499aff8f0576bb161
840fa63bbf06f"
        },
        "hls": {
          "url": "https://eurosport-dlvr-ott-vod.akamaized.net/primary/d3205b4da41248c7a4de0c09be0d12a0
/57c1df6ec52745aabf6358d05908c4aa/983916c99f9e43fbb1df5751dd9c00ff/index.m3u8?aws.manifestfilter=video_codec:h264&
hdnts=ip=85.211.254.200~exp=1597329035~acl=/primary/d3205b4da41248c7a4de0c09be0d12a0
/57c1df6ec52745aabf6358d05908c4aa/983916c99f9e43fbb1df5751dd9c00ff
/index.m3u8%3Faws.manifestfilter%3Dvideo_codec%3Ah264*~hmac=2fa8c119466a538cbf982891afd9a6ab012422b0fd000ed7b
0b53006c764a1cb"
        },
        "mss": {
          "url": "https://eurosport-dlvr-ott-vod.akamaized.net/primary/d3205b4da41248c7a4de0c09be0d12a0
/ca2620443be74b86b5ba8e81aae1e781/ecd02279137e48b98070f0c68c877aaa/index.ism
/Manifest?aws.manifestfilter=video_bitrate:900000-5500000;video_codec:h264&
hdnts=ip=85.211.254.200~exp=1597383005~acl=/primary/d3205b4da41248c7a4de0c09be0d12a0
/ca2620443be74b86b5ba8e81aae1e781/ecd02279137e48b98070f0c68c877aaa/index.ism
/Manifest%3Faws.manifestfilter%3Dvideo_bitrate%3A900000-5500000%3Bvideo_codec%3Ah264*~hmac=15a1e908304e49649
164ffc51a33a9859e4b5a2a0c44034f8bb5c11af30cf113"
        }
      },
      "userInfo": {
        "packages": [
          "Eurosport",
          "Free",
          "Registered"
        ],
        "products": [
          "eurosport-player-all-sports"
        ]
      },
      "viewingHistory": {
        "viewed": false
      }
    },
    "id": "698041",
    "type": "videoPlaybackInfo"
  },
  "meta": {
    "site": {
      "attributes": {
        "brand": "eurosport",
        "websiteHostName": "gb.eurosportplayer.com"
      },
      "id": "gb",
      "type": "site"
    }
  }
}
```


The "hls" URL is then extracted from this response and passed directly into setResolvedUrl.

**Comment by glennguy** [comment]
> The "hls" URL is then extracted from this response

That's exactly the file I need to have a look at as it contains the locations of the variant playlists e.g the one that 400ed from your log `index_3.m3u8`. As it turns out, I can download the index_3.m3u8 from where I am, but the token contained in the index.m3u8 url has already expired by the time I'm viewing your responses (returns HTTP 403).
From there it will be more clear as to what is going wrong.

**Comment by sterd71** [comment]
Hi,

I've sent a message to your email account with how to get the stream.

Thanks

**Comment by sterd71** [comment]
Hi Glenn, I got your email hopefully this is what you are after.

Thanks
Steve
[index.m3u8-response.txt](https://github.com/peak3d/inputstream.adaptive/files/5079023/index.m3u8-response.txt)

**Comment by sterd71** [comment]
Hi Glenn,

Have you had chance to look into the index.m3u8 file yet?

Thanks
Steve

**Comment by glennguy** [comment]
@sterd71 sorry for the delay

Yes I can see that inputstream.adaptive is incorrectly using the ?aws.manifestfilter=.... url params from the master playlist on the variant streams eg. 
`https://eurosport-dlvr-ott.akamaized.net/primary/1/132c559a43e5430c8ea7ba6aef4b012a/start/1596720600/index_3.m3u8?aws.manifestfilter=video_codec:h264&hdnts=ip=88.106.220.99~exp=1596723186~acl=/primary/1/132c559a43e5430c8ea7ba6aef4b012a/start/1596720600/index.m3u8%3Faws.manifestfilter%3Dvideo_codec%3Ah264*~hmac=4b384fe29991a3e291dae5b29773497229f56182902a5fa15ca5e1ebeea8aea7` 
should really just be 
`https://eurosport-dlvr-ott.akamaized.net/primary/1/132c559a43e5430c8ea7ba6aef4b012a/start/1596720600/index_3.m3u8`

@matthuisman has a patch which I believe fixes this, he is testing before resubmitting a PR. Watch this space :)

**Comment by matthuisman** [comment]
actually, its smf007 patch
The PR is here: https://github.com/peak3d/inputstream.adaptive/pull/488

@sterd71 
Try the builds below that have the PR included and see if it fixes your issue

Matrix builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-488/3/artifacts

Leia builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-489/1/artifacts

**Comment by sterd71** [comment]
Great @glennguy and @matthuisman I'll give those builds a try over the weekend and let you know how I get on.

Thanks
Steve

**Comment by sterd71** [comment]
Hi @glennguy & @matthuisman,

I've tried the new patch and it's working great.

Thanks for your help.
Steve
