### ISSUE TITLE
HLS segment http url not joined correctly

### ISSUE THREAD

**Issue by L2501** [peak3d/inputstream.adaptive#47]
https://github.com/peak3d/inputstream.adaptive/blob/a245403d69d616571d5e8eb081b2f9115f890785/src/parser/HLSTree.cpp#L302

url = base_url + line results in invalid urls when the segment paths begin with /

https://example.com/stream/ +  /vod/segment.ts
should result to https://example.com/vod/segment.ts

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/8234217f63a4b137717da11e8981a7a630f2ba9d
