### ISSUE TITLE
Add function: Format HLS4

### ISSUE THREAD

**Issue by VuzzyM** [peak3d/inputstream.adaptive#479]
@peak3d 
Hello.
Add stream/format HLS4 (adaptive streaming) 
Many sites use this format.

**Comment by glennguy** [comment]
@Lontron 
HLS4 does not mean anything.
inputstream.adaptive already supports HLS, please go back to the addon dev.

**Comment by VuzzyM** [comment]
@glennguy HlS4 automatically adjusts the quality to the desired speed internet.

**Comment by glennguy** [comment]
Please look here: https://github.com/peak3d/inputstream.adaptive/blob/Matrix/README.md
HLS is supported.
> automatically adjusts the quality to the desired speed internet.

This is under development but not yet finished.
There is no such thing as "HLS4"
