### ISSUE TITLE
no cathup, but live stream

### ISSUE THREAD

**Issue by Radoorech** [peak3d/inputstream.adaptive#493]
Hello,
I have some problem with cathup. I have a catchup provider which allows to watch catchup for 7 days. It works correctly using ffmpeg in kodi, but it plays as live if using adaptive.
If I enable "use inputstream.adaptive for m3u8 (HLS) streams, than cathup doesn´t work, it still plays live stream. But live stream support timeshift, I can pause stream for 90 minutes or rewind back for 90 minutes.
If I disable "use inputstream.adaptive for m3u8 (HLS) streams, than cathup works great. But live stream doesn´t support timeshift, I can´t pause stream for 90 minutes or rewind back for 90 minutes.
My ott provider support timeshift, I can pause live tv for 90 minutes or rewind back 90 minutes from time, when I started watch live tv.
I tried it with catchup="vod" so my playlist looks

#EXTINF:-1 tvg-id="Channel" tvg-logo="" group-title="" catchup="vod" catchup-days="7" catchup-source="https://archive/Channel/m3u8?starttime={utc}&stoptime={utcend}",Channel
https://live/channel.stream/chunklist.m3u8

Can you please help me with my problem?

Just to mention, that phunkyfish has access to a test stream, so you can use it.

Sorry for my english, hope you understand.

Thanks for your time.

**Comment by glennguy** [comment]
@Radoorech could you provide a pastebin link for your 'chunklist.m3u8' file?
Also full debug log would be great too
Thanks!

**Comment by Radoorech** [comment]
> 
> 
> @Radoorech could you provide a pastebin link for your 'chunklist.m3u8' file?
> Also full debug log would be great too
> Thanks!

Hello glennguy, thanks for your replay.
I have full debug, but what should I do, if I don´t want to everbody see my playlist?
There is full url of live stream and archive url in full debug.
May I send you email or PM?
Many thanks.

**Comment by glennguy** [comment]
Hi @Radoorech sorry for the late reply, yes could you pm me on the Kodi forum - username 'glennguy'
I probably won't be able to access the stream url from where I am so if you could provide that as well.

**Comment by Radoorech** [comment]
Hi @glennguy no problem with late replay, but I´m trying to send you pm on kodi forum, but you have disabled private messaging.
Could you send me pm - username "Franky Doparoma". Thank you very much for your time.

**Comment by glennguy** [comment]
I've got less than 10 posts so no PMs for me atm I guess! I probably should get involved on the forum a little more... Do you have a throwaway email I can reach you at?

**Comment by Radoorech** [comment]
Hi @glennguy, my email: franky.doparoma@gmail.com
