### ISSUE TITLE
Unable to locate addon

### ISSUE THREAD

**Issue by theboy181** [peak3d/inputstream.adaptive#5]
I updated my kodi and I can't seem to find this addon. Youtube had dash greyed out. 

Please help

**Comment by peak3d** [comment]
most probably an version / compatibility issue (sry. for the late response, can we close this one?)

**Comment by theboy181** [comment]
Are you able to telle how to get it working

**Comment by alexmustafa** [comment]
I have the Kodi Krypton 17.1 release candidate installed, and cannot find this addon.

Is it something that should appear in the official kodi repository?

**Comment by peak3d** [comment]
It should be part of the android apk.
But it may have to be enabled (Addons->My Addons->VideoplayerInputstream->inutstream.adaptive)
