### ISSUE TITLE
Add ability to start HLS event playlist from beginning using KODIPROP option

### ISSUE THREAD

**Issue by djbloc** [peak3d/inputstream.adaptive#505]
When playing back a HLS [event playlist](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/event_playlist_construction) where media files are still being added (i.e. the EXT-X_ENDLIST tag has not been set), inputstream.adaptive starts playback about 10 secs from the end of the playlist.

It would be a nice feature to start playback from the beginning without manually seeking back to the beginning. Using .strm files could this be done via #KODIPROP (or similar) option?

**Comment by glennguy** [comment]
@djbloc this should already be possible
`#KODIPROP:inputstream.adaptive.play_timeshift_buffer=true`

**Comment by michaelarnauts** [comment]
Correct. I've recently "discovered" that option by reading the Inputstream Adaptive source. It doesn't seem to be documented somewhere.
