### ISSUE TITLE
Black & white with color artifacts (Netflix)

### ISSUE THREAD

**Issue by haggaie** [peak3d/inputstream.adaptive#509]
Hi,

I've been seeing weird color artifacts watching some videos on Netflix (Star Trek Voyager). The video shows black & white with weird coloring artifacts (see below). Sometimes there's also a green bar on the right side of the screen. 

I noticed that the higher resolution streams show these artifacts, while choosing a lower resolutions play fine. For example the Star Trek Voyager Season 5 Episode 24 has 6 video streams: the 3 streams with the higher resolution (720x480) show these artifacts, and the 3 lower quality streams play fine.

![screenshot000](https://user-images.githubusercontent.com/35070/92208287-8c51dd80-ee93-11ea-9651-b74329b1b61c.png)

My system uses:
* Netflix Addon 1.8.0
* InputStream Adaptive 2.4.5.1
* Kodi 18.7
* LibreELEC 9.2.3 RPi2.arm 
* Raspberry Pi 3 Model B

I would be happy to provide additional information if needed.

**Comment by dagwieers** [comment]
I can confirm this on a Raspberry Pi 4 and LibreELEC v9.2.4. Same behaviour. And playing the same stream using the Android Netflix app does not have this behaviour. There everything looks fine.

cc @CastagnaIT 

PS I also noticed that Netflix has support for subtitle positioning in their Android app, so the subtitles shows close to the character saying it. This is actually quite nice, we are not used to this in Flanders (where almost everything is subtitled by default) but I think I could get used to that ;-)

**Comment by CastagnaIT** [comment]
@haggaie to help to debug you have to provide the full kodi log
by enabling Kodi debug, and also Netflix addon debug (expert settings -> Debug -> Verbose) and then reproduce the issue

it is better that you provide also the manifests,
after played the video, open netflix addon user data folder
an attach here both files (add .txt extension at end of filename):
manifest.json
manifest.mpd

i tried to play E24S5 on my widows 10 but i have only low resolutions
i will try with coreelec

**Comment by haggaie** [comment]
Sure, here are the log and the manifest files: 
* [kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5177668/kodi.log)
* [manifest.json.txt](https://github.com/peak3d/inputstream.adaptive/files/5177669/manifest.json.txt)
* [manifest.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5177670/manifest.mpd.txt)

**Comment by CastagnaIT** [comment]
Tried on Coreelec but here the colors are good
![image](https://user-images.githubusercontent.com/3257156/92301371-9d6a1f80-ef63-11ea-9aca-9ba3eb408a68.png)

**Comment by CastagnaIT** [comment]
i think it is better if you try to open an issue on LibreElec
mainly the video decoding is a task of Kodi, ISA do the decryption

**Comment by haggaie** [comment]
Thanks, I'll try to do that.

EDIT: here's a link to the [LibreELEC issue](https://forum.libreelec.tv/thread/22606-black-and-white-with-color-artifacts-on-netflix-rpi/).

**Comment by jakermx** [comment]
Hello,

I have RPi3 B+ working without isssues

Installed LibreElec9.2.4.RPi2.arm, Added my Codecs Licensense, Setup Network and Interface (Regional), Installed ISA and ISA rtmp then TubeCast and then finally  added CastagnaIT Repository,after that  Installed NF, set user and pass and limit stream to 720p, and I have color on 720x480 streams.

Cheers!

**Comment by jakermx** [comment]
I Remember I had that behavior when I had OMX Player set to default and when change deinterlace methods

**Comment by haggaie** [comment]
Thanks. I think I have OMXPlayer disabled and MMAL enabled. Not sure if that is the default or not. I see the deinterlace method controls as grayed out.

I also updated LibreELEC to 9.2.4. I thought it didn't help at first, but I checked again and now the problem seems to be gone. Perhaps some bad information was cached?

Anyway, thanks a lot everyone for trying to help.
