### ISSUE TITLE
[HLS] Subtitles on Safari but no subtitles on Kodi

### ISSUE THREAD

**Issue by sy6sy2** [peak3d/inputstream.adaptive#512]
Hi,

We have an HLS file (French catch-up TV video), if I open this file directly with Safari I have video, audio and I can also enable subtitles. But by using IA I can not see any subtitle in Kodi.

* Partial log: https://paste.kodi.tv/odesaxeqev.kodi
* ISA build version: Matrix-084ffc1 from Jenkins
* Kodi version: 20200826-8590900278

Thank you.

**Comment by glennguy** [comment]
According to your log the stream is not using inputstream.adaptive, ffmpeg is being used instead.
`2020-09-11 10:00:55.312 T:1230947   ERROR <general>: CInputStreamAddon::Supports - 'inputstreamaddon' has been deprecated, please use #KODIPROP:inputstream=inputstream.adaptive instead` is the best clue I can give atm

**Comment by sy6sy2** [comment]
Oh, I thought that it was only a warning! I will try again. Thank you!

**Comment by sy6sy2** [comment]
Now the video is handled by ISA, but still no subtitle: https://paste.kodi.tv/nivixafiyu.kodi

**Comment by glennguy** [comment]
@sy6sy2 is this issue still current? Could you check to see if it's still broken and if so upload:
* full debug log
* Master m3u8
* video, audio and subtitle m3u8
* if the subtitle m3u8 is a playlist with vtt or similar files, then one or two of those fragments

Thanks!

**Comment by sy6sy2** [comment]
Hi @glennguy,
Sorry for the delay.

It seems that this issue is not present any more! Thank you for the update anyway!
