### ISSUE TITLE
Unable to load widevine shared library widevinecdm.dll

### ISSUE THREAD

**Issue by kokarare1212** [peak3d/inputstream.adaptive#513]
Hi,
I was using an older version of widevine (1.4.8.1008), but when I updated widevine because I got the error "license update not successful (no keys)" (because of the older version?), Widevine.dll (4.*) It couldn't be read and stopped working.
Looking at the binary header of widevinecdm.dll, both the previous version and the new version were x86_64.
OS: Windows10 x86_64

**Comment by kokarare1212** [comment]
solved

**Comment by shentoneco** [comment]
> solved
I'm having the same issue. Could you please share how did you solve the problem?
