### ISSUE TITLE
X-AxDRM-Message

### ISSUE THREAD

**Issue by Zoom-Adr** [peak3d/inputstream.adaptive#514]
#KODIPROP:inputstream.adaptive.license_key=http://drm-widevine-licensing.axtest.net/AcquireLicense|X-AxDRM-Message=eyJ0eX|A{SSM}|

how do i play this type of license X-AxDRM-Message?

**Comment by glennguy** [comment]
`X-AxDRM-Message` looks like a HTTP header, set as any other header
