### ISSUE TITLE
Problems playing Widevine content on macOS, locally built version

### ISSUE THREAD

**Issue by LucasVanDongen** [peak3d/inputstream.adaptive#515]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have cloned from master and followed the steps detailed [here](https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md) to make a build for macOS. Kodi builds and starts fine. I can install all kinds of extensions.

## Expected Behavior

Disney+, Netflix (or other Widevine) content should play

## Actual Behavior

When playing Disney the following happens:

The Player crashes on line 501 of `InputStreamAddon.cpp`:
`  return m_struct.toAddon.open_stream(&m_struct, streamId);`

```
#0	0x00000001b9ac39b6 in VerifyCdmHost_0 ()
#1	0x00000001b9ac393a in VerifyCdmHost_0 ()
#2	0x00000001b9ac3906 in VerifyCdmHost_0 ()
#3	0x00000001b9a9c093 in VerifyCdmHost_0 ()
#4	0x00000001b98df038 in VerifyCdmHost_0 ()
#5	0x00000001b98deffb in VerifyCdmHost_0 ()
#6	0x00000001b98df038 in VerifyCdmHost_0 ()
#7	0x00000001b98deffb in VerifyCdmHost_0 ()
#8	0x00000001b98f1ab5 in VerifyCdmHost_0 ()
#9	0x00000001b98edc91 in VerifyCdmHost_0 ()
#10	0x00000001b98d5506 in 0x1b98d5506 ()
#11	0x00000001b9722ab2 in media::CdmAdapter::CreateSessionAndGenerateRequest(unsigned int, cdm::SessionType, cdm::InitDataType, unsigned char const*, unsigned int) ()
#12	0x00000001b97043d8 in WV_CencSingleSampleDecrypter::WV_CencSingleSampleDecrypter(WV_DRM&, AP4_DataBuffer&, unsigned char const*) ()
#13	0x00000001b97079bd in WV_CencSingleSampleDecrypter::WV_CencSingleSampleDecrypter(WV_DRM&, AP4_DataBuffer&, unsigned char const*) ()
#14	0x00000001b970e550 in WVDecrypter::CreateSingleSampleDecrypter(AP4_DataBuffer&, char const*, unsigned char const*) ()
#15	0x00000001b82f3b9f in Session::InitializeDRM() ()
#16	0x00000001b82f54d4 in Session::PrepareStream(Session::STREAM*, bool&) ()
#17	0x00000001b82f9fff in CInputStreamAdaptive::OpenStream(int) ()
#18	0x00000001b83045fe in kodi::addon::CInstanceInputStream::ADDON_OpenStream(AddonInstance_InputStream const*, int) ()
#19	0x0000000101deae17 in CInputStreamAddon::OpenStream(int) at /Users/lucas/kodi/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp:501
```

The problem is really similar when running Netflix, the Player crashes on line 177 of `InputStreamAddon.cpp`:
`  bool ret = m_struct.toAddon.open(&m_struct, &props);`

## Possible Fix

Did not find a fix

### To Reproduce

1. I've tried to make the whole process repeatable so every time I paste the following in Terminal to get a clean build:
```
cd $HOME
rm -rf kodi
rm -rf kodi-build
git clone https://github.com/xbmc/xbmc kodi
cd $HOME/kodi/tools/depends
./bootstrap
./configure --host=x86_64-apple-darwin
make -j$(getconf _NPROCESSORS_ONLN)
cd $HOME/kodi
make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons
mkdir $HOME/kodi-build
make -C tools/depends/target/cmakebuildsys BUILD_DIR=$HOME/kodi-build GEN=Xcode
```
2. Open Xcode 11.7
3. Build Kodi
4. Install Disney+ or Netflix
5. Load any type of content

### Debuglog

The debuglogs can be found here:
[Netflix](https://paste.kodi.tv/fuhigecoki.kodi)
[Disney +](https://paste.kodi.tv/fowebutewe.kodi)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.15.6 (19G2021)
 - Kodi version: 19.0ALPHA-1 (18.9.701)

**Comment by ksooo** [comment]
Try starting Kodi outside Xcode. This should work. It seems, the widevine guys have built in some debugger trap.

**Comment by LucasVanDongen** [comment]
> Try starting Kodi outside Xcode. This should work. It seems, the widevine guys have built in some debugger trap.

Thanks a lot, that saved me a few hours of banging my head against the wall. So to be able to debug Kodi running Widevine code I need the official debug enabled version of the CDM, or I need to resort to printing to the log if I don't have it? I was particularly interested how Kodi solved some of the issues around Netflix or Disney like the URL's for Netflix that have the range defined in it's path so being able to put some breakpoints would be really helpful. ExoPlayer doesn't play Netflix content out of the box even after converting to regular MPD's etcetera.

**Comment by glennguy** [comment]
There's no easy way around unfortunately. As soon as the widevine cdm detects the debugger it will crash.

However depending on what part of the code you're debugging (what are you wanting to look at btw? Kodi or inputstream.adaptive?) you can get a peek while the video is paused:
1. Start Kodi
2. Open stream from disney+/netflix
3. Pause
4. Attach debugger and set breakpoint
5. Do something to trigger breakpoint
6. ???
7. Profit

If you're looking at inputstream.adaptive code, try setting stream selection in the IA addon settings to manual, then you can use a breakpoint somewhere in OpenStream for eg.
To trigger this just change video streams from the OSD Video Settings

**Comment by LucasVanDongen** [comment]
> what are you wanting to look at btw? Kodi or inputstream.adaptive?

The reason I'm looking into inputstream.adaptive is that it is able to stream Netflix (and Disney+ and whole lot of other formats) while with ExoPlayer it seems I can only play the basic Widevine examples but not play Netflix even when I give it a converted MPD. Since the Netflix add-on doesn't seem to do anything else than talk to the back-end to work as an interface between the Netflix API and Kodi so that leaves inputstream.adaptive as the place where support exists for whatever Netflix needs and ExoPlayer doesn't seem to have. 

For example I notice when I analyze traffic in the browser I see that Netflix puts the range in the URL path rather than (or also?) in the header, this is something I think I need to implement manually in ExoPlayer. Also it seems to struggle to neatly identify the format, it never calls to the license_url for Netflix content while the example streams do.

> As soon as the widevine cdm detects the debugger it will crash.

I expected there was also a "development" version of the Widevine CDM because this document mentions it on page 5: https://usermanual.wiki/Pdf/WidevineModularDRMCDMUserGuideiOS16.729715513/html 
However I don't have the official Google supported CDM yet so I cannot tell how accurate that information (still) is. Also there are some pretty steep limitations to it (especially the fact it only works with license.uat.widevine.com apparently). It's really annoying as I'm completely not interested in Widevine itself but it blocks me from debugging into the code that I am interested in.

> you can get a peek while the video is paused:
> 
> 1. Start Kodi
> 2. Open stream from disney+/netflix
> 3. Pause
> 4. Attach debugger and set breakpoint
> 5. Do something to trigger breakpoint
> 6. ???
> 7. Profit
> 
> If you're looking at inputstream.adaptive code, try setting stream selection in the IA addon settings to manual, then you can use a breakpoint somewhere in OpenStream for eg.
> To trigger this just change video streams from the OSD Video Settings

Thanks again, I just would like to be able to step through a few parts of the code, for example the part where the format gets determined or where the next fragment URL gets built and executed. Pausing the stream seems to be a bit hit or miss as I want to go through specific parts of the code that might or might not have interaction with the Widevine CDM in between. Would [this](https://stackoverflow.com/questions/51618136/can-i-have-an-ios-process-await-a-debugger) be a useful approach to be able to attach the debugger and debug exactly the part of the code I would like to examine running?

**Comment by glennguy** [comment]
> Would this be a useful approach

May as well give it a try, nothing to lose there. You could set a loop at the point after cdm session is initialized and before downloading first segment, not sure if you'll see much before the sample reader wants to decrypt it though.

As far as the iOS SDK goes, I think you have to pay $$$ for access and probably sign NDA so your chances of coming across it will be fairly limited.

AFAIK there's nothing special that IA does that exoplayer can't. There's a small block of code in IA for extracting the frame rate from mp4 specific to netflix but I wouldn't think that would be stopping things.

**Comment by glennguy** [comment]
@LucasVanDongen Happy to close this issue now?

**Comment by LucasVanDongen** [comment]
Regretfully I’m not working on the project I needed it for, so I couldn’t test again.
