### ISSUE TITLE
Add custom headers to redirected location too.

### ISSUE THREAD

**Issue by botallen** [peak3d/inputstream.adaptive#516]
I have setup of local proxy in which i am redirecting local manifest url `http://127.0.0.1:8898/h/1260000025/master.mpd` to original manifest `https://xxxx-i.akamaihd.net/xxxxx/master.mpd?hdnea=xxxx`. 

This url (`https://xxxx-i.akamaihd.net/xxxxx/master.mpd?hdnea=xxxx`) requires specific User-Agent which i am passing as 
```py
play_item.setProperty("inputstream.adaptive.stream_headers", "User-Agent=MY_USER_AGENT")
```

**The Problem is** when i am using `http://127.0.0.1:8898/h/1260000025/master.mpd` link in list item path,  User-Agent is only applying to this url not the forwarded url `https://xxxx-i.akamaihd.net/xxxxx/master.mpd?hdnea=xxxx` and due to this i'm getting 403.

I tested by using direct link as list item path and it's working as intended.
```py
play_item.setPath("https://xxxx-i.akamaihd.net/xxxxx/master.mpd?hdnea=xxxx")
```
Any workaround ? cause i can modify response of proxy.

**Comment by Fireblade89** [comment]
I have the same problem with a different header - (verifyPeer=false). I've think this pass header functionality doesn't work.

**Comment by glennguy** [comment]
@botallen did you figure this one out? Can we close the issue?

**Comment by CastagnaIT** [comment]
we have given enough time to answer its time to close it
