### ISSUE TITLE
How to build for Kodi 18.08 (Leia)  on Ubuntu 20.04

### ISSUE THREAD

**Issue by lonnietc** [peak3d/inputstream.adaptive#517]
Hello,

I am new to Kodi, but have found that I need to install the inputstream.adaptive AddOn to go with my system.

Came across your site, not now I do not know how to build and install the AddOn after grabbing the Leia version in the releases.

Can you please advise?
Thanks in advance

**Comment by michaelarnauts** [comment]
Use the Kodi PPA. No need to compile IA.

**Comment by Vikassm73** [comment]
Assuming that, you have already installed kodi in Ubuntu. To install, you just need to run the following command

sudo apt-get install kodi-inputstream-adaptive

sudo apt-get install kodi-inputstream-rtmp

**Comment by lonnietc** [comment]
Hi All,

Thanks for getting back to me.

It seems that I have it already installed:

lonnie@lonnie-p7-1451:~$ sudo apt-get install kodi-inputstream-adaptive
[sudo] password for lonnie:
Reading package lists... Done
Building dependency tree
Reading state information... Done
kodi-inputstream-adaptive is already the newest version (2.4.5-1~focal).
kodi-inputstream-adaptive set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.

lonnie@lonnie-p7-1451:~$ sudo apt-get install kodi-inputstream-rtmp
Reading package lists... Done
Building dependency tree
Reading state information... Done
kodi-inputstream-rtmp is already the newest version (3.1.1-1~focal).
kodi-inputstream-rtmp set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.

But when I run Kodi 18.08 (Leia)  and start up Pluto and select a channel,
I still get:


[image: image.png]

What is strange is that after I select "OK" then the stream starts up and
displays the as it should.

Any ideas on this?
Thanks

**Comment by Vikassm73** [comment]
In Kodi - Addon - My Addon - All

Check whether Inputstream is enabled or not

**Comment by lonnietc** [comment]
The only Addon that I have the "Inputstream Helper" Addon showing which is
also enabled but not showing any "Inputstream Adaptive" Addon at all
anywhere.

**Comment by lonnietc** [comment]
I seem to have fixed it.

I removed the inputstream.adaptive package from the system, cleaned out the apt cache and then re-installed

sudo apt-get install kodi-inputstream-adaptive

things seem to work now.
Thanks for all of the help

**Comment by dagwieers** [comment]
Unfortunately if you install **inputstream.adaptive**, or when it is updated, you have to restart your system or restart Kodi to pick up the new version. See #454
