### ISSUE TITLE
Widevine stopped working after latest update

### ISSUE THREAD

**Issue by hllizi** [peak3d/inputstream.adaptive#519]
After the recent update of Widevine, it stopped working on my LibreELEC 9.2.1 system with Kodi 18.4 running on a Raspberry Pi 3. The problem concerns both the Netflix addon (where the title of the video to be played shortly flashes in the top right corner but then disappears and nothing further happens) and the Amazon Prime addon (where the title appears together with a loading circle, but soon after vanish and nothing further happens). The logs also seem to suggest that the issue is tied to inputstream adaptive and its interaction with widevine:

[Amazon Prime](https://paste.kodi.tv/azuwuvezam.kodi)
[Netflix](https://paste.kodi.tv/ulobulonaw.kodi)

PS: just updated to LibreELEC 9.2.4, which, as expected, made no difference.

**Comment by hllizi** [comment]
Just found out, somewhat to my embarrassment, that such a feature already exists. Sorry.

**Comment by hllizi** [comment]
It's late, so I decided to close the wrong issue.

**Comment by glennguy** [comment]
`ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)`

inputstream.adaptive isn't responsible for providing or updating the widevinecdm library, it would be better to seek help from either the netflix/amazon add-on devs or inputstreamhelper devs. 
This error could occur for a few reasons, including either permissions for the file aren't correct or it's for the wrong platform/arch

Before opening more issues elsewhere though one thing you could try is deleting this file and allowing inputstreamhelper to try getting the correct version again.

**Comment by hllizi** [comment]
@glennguy Thanks for the info, indeed I thought that keeping track of and installing the newest Widevine version happened quite independently of the addons for individual services and expected it to be related to inputstream adaptive. Regarding your suggestion, I had already tried that, but another automatic download resulted in the same situation again. But in the meantime I have found out that inputstream helper allows for selecting older versions of Widevine, which fixed the problem for now.

**Comment by hllizi** [comment]
Closing this then.

**Comment by dagwieers** [comment]
We identified the issue, fixed it and released InputStream Helper v0.5.1.

As a follow-up we are improving specific logging and intend to review and extend the current ARM HWID list.

### If you are affected by this issue now, follow these steps:
- Go to **Add-ons** » **Program add-ons**
- Start **InputStream Helper**
- Select and click on **Restore Widevine CDM library...**
- Pick any version → stay clear of version **4.10.1679.0 (13310.91.0)**
