### ISSUE TITLE
Seeking in live stream of Zattoo.com (DASH) does not work.

### ISSUE THREAD

**Issue by rbuehlma** [peak3d/inputstream.adaptive#52]
Trying to seek in a live stream results in a freeze of the picture or stopping the stream and returning to the main menu.

**Comment by peak3d** [comment]
Changed interface to IPosTime -> should work now.

**Comment by rbuehlma** [comment]
Yes its, working no with on exception:

Its not possible to seek further than the time I was already watching the stream:

Let's say I pause the stream for 5 minutes and then continue to play. It is then not possible to skip forward even though the stream has 5 minutes left.

This is probably related to the "timeshift-buffer" which does not get filled while no new segments are required. As far as I know, the mpd file should be re-read every few seconds (that interval is also stated in the mpd file itself) to know the current end of the stream.

**Comment by peak3d** [comment]
yes, I'm aware of this topic.
