### ISSUE TITLE
Maximum resolution - please provide more options.

### ISSUE THREAD

**Issue by Harvie** [peak3d/inputstream.adaptive#528]
This menu cannot currently set any maximum resolution limit between 1280p and 4K. But unfortunately hardware limits of my raspi4 seem to be exactly somewhere in between, so i have to choose the resolution manualy every time.

Can you please add following max resolution choices?

1440p, 1620p, 1920p, 2160p, 2540p, 2K (and possibly other sensible values)

![image](https://user-images.githubusercontent.com/276504/95780221-c51f7680-0ccb-11eb-8a3b-cf29f8273809.png)

**Comment by CastagnaIT** [comment]
what are your use cases?

When "ignore display resolution" is turned OFF, ISA limit automatically the max video resolution to the display resolution

this means that you have set a kodi display resolution like 4k? while you play streaming content up to 4K?
why not lower the kodi display resolution?

**Comment by Harvie** [comment]
I have 1280p display, but for example when service provides only 720p, 1440p and 4K streams i have no way to set defaulting to 1440p.

If i obey display resolution, it will play 720p which is not as clear picture as i would like to have. When i set it to ignore display resolution it will default to 4K which can get choppy on my setup...
