### ISSUE TITLE
Project governance

### ISSUE THREAD

**Issue by dagwieers** [peak3d/inputstream.adaptive#529]
I have sent a mail in February to @peak3d with the same topic. My mail back then was to offer help (from the community) to help with documentation, triage and release management (incl. testing). Back then we have had months with lots of fixes but none were released (at least not to our users on Leia) and various community members were active to help out.

In the meantime the Wiki is open to contributors (thanks to all contributors!) and we have had various new releases for Leia, but since July a lot of fixes went unmerged/undiscussed and prior fixes went unreleased. This hampers progress in a critical piece for a lot of important VOD add-ons and an inferior experience for our users.

So I want to open the discussion again (now in public) about this project's governance. We have quite a few active members that could help in triage, merging and release management. A lot of the stakeholders are available for testing out new releases and we could speed up development at a faster pace if we are open to that. I realize that this is not just a matter of trust, it will be a learning process with ups and downs, but with a larger community that can participate more actively.

Possible actions include:
- Select a few active candidates in the community to think about the project's governance
- Create a Slack channel to collaborate more closely on detailed topics
- Moving the add-on to an organization (this enables more people to organize the repository)
- Do better triage so issues and PRs are better managed
- Use milestones for release management
- Work on improving reliability by semi-automated testing

We have seen in other Kodi projects that this can work, no guarantees though :wink: 

cc: @AlwinEsch @glennguy @mediaminister @Rechi @matthuisman @CastagnaIT @phunkyfish @spyderboy92 @smf007 @Maven85

**Comment by CastagnaIT** [comment]
from what I understand peak3d had a break from the project
will probably be able to tell us the future moves :)

it would be nice to use the Projects page for the necessary developments to do
and understand the current development state
but to manage it all you need developers with good knowledge of C++ and some DRM workflow
I personally know very little C++... otherwise i would make some more contribution

**Comment by dagwieers** [comment]
In my original mail I listed the below improvements (not requiring commit access), but I think there is a lot more to address if @peak3d will not be contributing as actively as before.

> - **Improve documentation in the Wiki**
>    - Update the README to reflect the current status
>    - Pointing to the Wiki where relevant
>    - Call out to the community to improve the Wiki
>    - Create an overview of known issues and wanted features
> - **Triage existing issues and feature requests**
>    - Labeling issues correctly
>    - Creating abstract feature requests where they are missing
>    - Tagging existing issues as duplicates where they relate, e.g. adaptive support
>    - Supporting people with issues, and/or escalating to you when needed
>    - Add labels for things we expect the community to implement (so people do not have to wait)
> - **Release management**
>    - Create proper releases based on existing tags
>    - (Possibly add official builds as downloads, for the future)
>    - This could be useful for people tracking releases on GitHub

**Comment by dagwieers** [comment]
Let me also include other stakeholders here.

cc @learningit @Sandmann79 @micahg @emilsvennesson @herrnst @arvvoid @FraserChapman @Lunatixz @basrieter @skipmodea1 @enen92 @MrKrabat @anxdpanic @phate89 @michaelarnauts @flubshi @shycoderX @fayer3 @rbuehlma @rolapp

**Comment by mediaminister** [comment]
My only concern (for now) is that the open PRs are getting reviewed and merged and that we can have a new release in the near future. Some developers made the effort to fix bugs, but it's a pity you can only get these fixes by compiling InputStream Adaptive yourself.

So, I would like to know first if peak3d is able to make a release in the near future. If not, it would be nice if someone else from the community or Team Kodi can get access to the necessary backends to make a new release.

**Comment by Varstahl** [comment]
@CastagnaIT I'm very knowledgeable in C/C++ but not as much for DRM workflow. I see a fruitful partnership ahead waiting to happen :D

Jokes aside, this is really vital to Kodi, and while more devs don't necessarily equate to better codebase, it could help move things forward with features like automatic quality selection coming to mind.

**Comment by CastagnaIT** [comment]
@Varstahl ciao haha :D could be an idea but the DRM topic is very broad i am not a master chef but i can try to help in some way

**Comment by CastagnaIT** [comment]
There is a critical Kodi PR that need some attention:
https://github.com/xbmc/xbmc/pull/18352

I think that this next change to Kodi's interface could cause the inability to use ISA with matrix
should already be merged but seems to be waiting critical

seem only small adjustments but will have to be made

**Comment by peak3d** [comment]
So, I read we want to do some steps forward? Lemme check the PR's :-)

**Comment by peak3d** [comment]
There is one thing I'm right now not quite sure how we proceed: rework branch.
The rework branch, and on top of it adaptive bitrate switching from @spyderboy92 , could lead to issues with the current PR's.

Are there important PR's which affect core (main.cpp / AdaptiveStream.cpp) ?

**Comment by dagwieers** [comment]
Australia has yet to wake up, so anything that is not easy to revert should probably be delayed by 12 hours :wink:

**Comment by CastagnaIT** [comment]
I don't know if this PR could also affect the ISA build:
https://github.com/xbmc/xbmc/pull/18537
maybe it's just for the internal kodi component building

**Comment by smf007** [comment]
Pull https://github.com/peak3d/inputstream.adaptive/pull/488 touches adaptivetree.cpp which the rework branch also touches.  It's rather small, so rebasing on the rework branch should be simple.

There is the question of https://github.com/peak3d/inputstream.adaptive/pull/490 & https://github.com/peak3d/inputstream.adaptive/pull/491 versus https://github.com/peak3d/inputstream.adaptive/pull/508.  If everyone fine with https://github.com/peak3d/inputstream.adaptive/pull/508, then I'll close https://github.com/peak3d/inputstream.adaptive/pull/490 & https://github.com/peak3d/inputstream.adaptive/pull/491 which were the minimal changes to source.

**Comment by glennguy** [comment]
Last time I based the multi period HLS PR on the rework branch there were issues so now that PR is merged, merging rework will likely break it but don't let that stop progress. My vote would be to merge rework and get others to rebase.

**Comment by dagwieers** [comment]
It has been a while, but this issue has not been resolved since.

What can we do to get something moving in this space again?
ISA is too important to Kodi add-on developers and users to have it unmaintained for months.
Even if it means only doing issue triage (closing, duplicates, labels).

**Comment by CastagnaIT** [comment]
the Kodi team is thinking of moving this project to their github
we have to wait some time to have their news

**Comment by matthuisman** [comment]
@dagwieers 
can this issue now be closed?

**Comment by dagwieers** [comment]
I would still like to see more real life testing before release.

But sure, this can be closed.
