### ISSUE TITLE
Change Names of the Streams

### ISSUE THREAD

**Issue by adrianpaniagualeon** [peak3d/inputstream.adaptive#534]
When I create the  .srtm  i add my links and then in the menu appears that URL.

I want to be able to create a .strm file with headers to change the name like "channel-name="channel ABC"

**Comment by glennguy** [comment]
@adrianpaniagualeon inputstream.adaptive does not/cannot tell Kodi what to display in the UI, strm files tell Kodi to use inputstream.adaptive and can tell Kodi what to display.

strm files are effectively m3u8 files, you can add this above your url to change the name displayed: `#EXTINF:0,Stream name goes here`
