### ISSUE TITLE
Cannot play mpd video invalid license challenge 

### ISSUE THREAD

**Issue by sefuns** [peak3d/inputstream.adaptive#539]
Hello @peak3d ,
I am trying to play mpd video but license URL request is returning invalid challenge.
I tried using <laURL>|<headers>|R{SSM}| but its not working, server returns "INVALID_LICENSE_CHALLENGE".
Please take a look at attached EME log
[EME Log.txt](https://pastebin.com/xStZECVQ)

Thank you

**Comment by peak3d** [comment]
@sefuns more interesting in the first step is how the data is send to the server, you can find this in your browsers network log.
