### ISSUE TITLE
Releases for Krypton

### ISSUE THREAD

**Issue by X-dark** [peak3d/inputstream.adaptive#54]
I am packaging this for [Arch Linux](https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive/) but I am a little lost since the 2.x releases to what releases are compatible with Krypton.

I have seen you have made backport in the Krypton branch for 2.0.{6..8} but I do not see the corresponding release archive on the release page.

**Comment by peak3d** [comment]
sry, what exactly are you looking for?

**Comment by X-dark** [comment]
There is two branches Krypton and master, I guess it means master branch is no longer compatible with Krypton.
On the release page, only release from the master branch are downloadable.
Where may I find releases compatibles with Krypton?

**Comment by peak3d** [comment]
Ah, ok, thx! will add releases for krypton there.

**Comment by jansohn** [comment]
@X-dark, I'm currently missing the VideoPlayer Inputstream entry in my Kodi 17.4 installation on Arch. Do I need to install the extra AUR package to enable it? Or should it already be there? Thanks!

**Comment by X-dark** [comment]
@jansohn the linked AUR package above brings the Inputstream addon to Kodi. Currently it does not build because of this aforementioned problem. You should use the -git version.

**Comment by X-dark** [comment]
@peak3d sorry to ping you but any update about this?

**Comment by dagwieers** [comment]
@peak3d Is this still relevant? If not, please close this.

**Comment by X-dark** [comment]
Yes this is no longer relevant.
