### ISSUE TITLE
With Facebook live streams, sound is lost after some seconds

### ISSUE THREAD

**Issue by tanty** [peak3d/inputstream.adaptive#544]
https://forum.kodi.tv/showthread.php?tid=311335

Still reproducible with latest Kodi (Leia)

**Comment by glennguy** [comment]
@tanty is this issue still current? If so could you please post a full debug log? Don't turn on component logging btw.

**Comment by tanty** [comment]
Yes, it's still happening.

Kodi v18.7 from Raspbian Buster repositories (RPi4). inputstream.adaptive addon v2.4.4
[debug-kodi.log](https://github.com/xbmc/inputstream.adaptive/files/6625127/debug-kodi.log)

**Comment by tanty** [comment]
Ugh, just realized that there is v2.4.7 for Leia and Debian has this version for Buster but Raspbian only has v.2.4.4 as the latest version. Not sure how to do to push a newer package there ...

... all in all, I cannot say if the latest version has fixed this. I'll try to figure out.

**Comment by dagwieers** [comment]
@tanty We have a list of contacts on the Wiki at: https://github.com/xbmc/inputstream.adaptive/wiki/Stakeholders#platforms

But the release process currently does not involve contacting them when a new release is ready. We should ask all maintainers to track ISA releases on GitHub. (I think I did ask this in a previous communication)

Raspbian does not seem to be listed. And the releases have not been updated on the Wiki matrix either.

**Update**: I updated the matrix with the most current version.
**Update2**: @tanty I assumed Raspbian was getting updates from Debian, but if that is not the case (or it needs to be acknowledged first) we ought to add a link for Raspbian as well. Feel free to update the Wiki!

**Comment by dagwieers** [comment]
Ok, I add @basilgello as the maintainer for Raspbian now.

**Comment by basilgello** [comment]
I do maintain Debian, not specifically Raspbian, sorry!

**Comment by tanty** [comment]
@peak3d appears as maintainer in the v2.4.4 package I've installed:

```
pi@raspberrypi:~ $ apt show kodi-inputstream-adaptive
Package: kodi-inputstream-adaptive
Version: 2.4.4-1~buster
Priority: extra
Section: libs
Maintainer: peak3d <info@peak3d.de>
Installed-Size: 2,287 kB
Depends: libc6 (>= 2.17), libexpat1 (>= 2.0.1), libgcc1 (>= 1:3.5), libstdc++6 (>= 6)
Conflicts: kodi-inputstream-mpd, kodi-inputstream-smoothstream
Replaces: kodi-inputstream-mpd, kodi-inputstream-smoothstream
Homepage: http://www.peak3d.de
Download-Size: 516 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.raspberrypi.org/debian buster/main armhf Packages
Description: adaptive inputstream addon for Kodi
 DASH/smoothstream inputstream addon for Kodi
```

**Comment by basilgello** [comment]
I'd reach the Raspbian team (https://www.raspbian.org/RaspbianTeam) on IRC or mailing list & kindly asked them to update the package from upstream Debian.

In testing, there is 2.6.14 that I packaged, so there is only update on Raspbian side.

@mpthompson I hope you notice the mention :)

**Comment by CastagnaIT** [comment]
@tanty are you able to test with Kodi 19 Matrix to check if the problem still occurs?
in case it occurs, can you provide valid mpd's for testing? and/or instructions in how get it?

**Comment by CastagnaIT** [comment]
Tested and the issue persist in Kodi 19

I have noticed this
initially the live-video works (with audio) correctly but shows a Kodi GUI time-bar of 20 secs lenght,
at the end of these 20 secs the time lenght in GUI time-bar become completely distorted with negative values (see screenshot)
and then here the audio is broken that could be a side effect of the negative PTS values:
![immagine](https://user-images.githubusercontent.com/3257156/157202598-4aa8e022-2fe7-47c4-8418-bc773b3d0b33.png)
MPD: [FacebookLiveMPD.txt](https://github.com/xbmc/inputstream.adaptive/files/8204377/FacebookLiveMPD.txt)

the problem look like similar to #821 and #832

EDIT:
On Kodi 20 the behaviour is similar but we do not have negative values in the GUI time-bar
after the first 20 secs, the video is stall seem try buffering, anfter that resume without audio.
you can see download errors in log
Kodi20 log: [kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/8204494/kodi.log.txt)

Comparing the ISA audio url seem different to website and VLC:
ISA:
```
https://video-mxp1-1.xx.fbcdn.net/hvideo-ldc-prn/_nc_cat-1/_nc_sr_t-4/v/r_kHjzx6H4hWGk43Zy2mN/_nc_ohc-d7lI6JrSM6IAX_LuV3L/live-dash/dash-abr-ibr-audio/../dash-lp-ld-a/1392275401278663_0-10872111.m4a?ms=m_C&ccb=2-4&sc_t=1
```
VLC:
```
https://video-mxp1-1.xx.fbcdn.net:443/hvideo-ldc-prn/_nc_cat-1/_nc_sr_t-4/v/r_kHjzx6H4hWGk43Zy2mN/_nc_ohc-d7lI6JrSM6IAX_LuV3L/live-dash/dash-lp-qd-a/1392275401278663_0-12704105.m4a?ms=m_C&ccb=2-4&sc_t=1 @0
```
Website:
```
https://video-mxp1-1.xx.fbcdn.net/hvideo-ldc-prn/_nc_cat-1/_nc_sr_t-4/v/rhrse2ewBNmDqh6_3jOjZ/_nc_ohc-vF_zccxZhFgAX_-9EU1/live-dash/ID/dash-lp-ld-a/1392275401278663_0-6085.m4a?ms=m_C&ccb=2-4&sc_t=1&_nc_sc=1&_nc_psid=id-vpuid-f3f7e5bfb86dc6
```

EDIT:
Relative Url dots has not relevance on the problem anyway i fixed on linked PR
From the log seems that try to download a wrong audio segment

another sidenote is that the stereo audio is detected by kodi as 0 channels sounds strange but this is probably a kodi problem

**Comment by CastagnaIT** [comment]
tested more live videos and now on Kodi v20 works correctly

for testing you need to set the property
`inputstream.adaptive.manifest_update_parameter=full`

but i opened a PR to make this property automatic
