### ISSUE TITLE
[Matrix] Latest builds 2.6.3 and 2.6.4 playback are broken and streams properties are broken

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#548]
Install the latest Kodi nightly and 
tried ISA 2.6.3 and 2.6.4 (For Windows) picked from artifacts and also kodi release
with Netflix add-on

The video playback not starts or something starts but the first time only, then next play video will be broken:
log: https://paste.kodi.tv/tezigurapo.kodi

~When video starts there are other problems, the streams properties are all broken, example:~ FIXED
Now (broken):
![image](https://user-images.githubusercontent.com/3257156/97798904-ac4f1480-1c2a-11eb-8d98-fe971bed80a7.png)

Before (working):
![image](https://user-images.githubusercontent.com/3257156/97798953-06e87080-1c2b-11eb-92fd-82f184d2745f.png)

Suggest that the new IA interface have some things to be fixed or depends from the last ISA changes?

**Comment by CastagnaIT** [comment]
Another log: https://paste.kodi.tv/paxedoniri.kodi
this time when the playback is started "successfully"
has took about 15 seconds to start the video

but this time there are some errors:
<pre>
2020-11-02 13:11:27.381 T:23140   ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-11-02 13:11:27.381 T:23140   ERROR <general>: CCurlFile::Open failed with code 0 for https://ipv4-c003-mil001-ix.1.oca.nflxvideo.net/?o=AQP_EC5znsz5aJoAr-OGSfbv4QC_nBwUMVHsIqqBL7vB7RrxOnu9c792k1LhJv9KcQ-hnhssB4vqxaC1KDul-9m2dk69UJDdDHYTayxuSd7CgQrf2AYm9GoToL2HT9YODGOHRcer1p3hYWJDx-uMxaflJyPtXOClSANSgOU&v=5&e=1604362252&t=dbuj8XT9kAM-D1KOPvk2uSqq7no:
                                                   
2020-11-02 13:11:27.381 T:23140   ERROR <general>: AddOnLog: inputstream.adaptive: Unable to select stream!
</pre>

i see that at the end of the url there is a `:` it seems a bit strange to me this

**Comment by fernandoalonzo** [comment]
I'm having a similar problem and am trying to understand what is happening. What I see, after updating to Kodi alpha 3 and ISA 2.6.4, is that the fragment url is not valid:
```
ERROR <general>: AddOnLog: inputstream.adaptive: Download http://p-cdn3-804-cg14-linear-cbd46b77.movetv.com/15804/live/WFLDDT/6529a3f61db311ebb1490025b547120f/video/vid06/fffffff9.m4s failed with error: 404
```
I always get 404 Not Found for Audio and Video streams. Same stream, using the HTML player, generates urls like this:
```
https://p-cdn3-804-cg14-linear-cbd46b77.movetv.com/15804/live/WFLDDT/6529a3f61db311ebb1490025b547120f/video/vid06/00003fbc.m4s
```
This problem only happens when I open live streams; catch-up and VOD work just fine.
Do you think this is related with the issue you described?

**Comment by CastagnaIT** [comment]
I don't know, but I think that one of the problems can be at this line:
https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/main.cpp#L3922
is where the code seems to stuck perhaps the new "reinterpret_cast" introduced fails

**Comment by AlwinEsch** [comment]
The fix request is in and after this addon becomed a new release should it fixed on next downloads.

**Comment by CastagnaIT** [comment]
All fixed on Kodi side thanks to all
