### ISSUE TITLE
Black Screen on Widevivene L1 Device - License server returned failure

### ISSUE THREAD

**Issue by haduvelko** [peak3d/inputstream.adaptive#549]
**Environment**
Disney Plus addon latest version
Operating system version/name: Android Oreo 8.0.0
Device: Philips 65OLED873/12

**Bug:**

Black screen when playing 4K HDR content.

**log:**

2020-11-02 00:08:06.333 T:29838 DEBUG: CurlFile::Open(0x89d55380) http://127.0.0.1:49005/https://global.edge.bamgrid.com/widevine/v1/obtain-license
2020-11-02 00:08:09.993 T:29838 ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-11-02 00:08:09.994 T:29838 ERROR: CCurlFile::Open failed with code 403 for http://127.0.0.1:49005/https://global.edge.bamgrid.com/widevine/v1/obtain-license: 2020-11-02 00:08:09.994 T:29838 ERROR: AddOnLog: InputStream Adaptive: License server returned failure

**Comment by matthuisman** [comment]
Notes: 
Above device is L1 Widevine
Above device Android Disney+ official app works fine
Above works for user when not using secure decoder (therefore lower resolutions)
Same request works on Nvidia shield.
Full log: https://paste.kodi.tv/ofuzogeyet

Ignore the http://127.0.0.1:49005/. This is just the proxy that is used to fix up some hls stuff.
For POST data - the request is passed straight through without any changes.

**Comment by matthuisman** [comment]
@haduvelko 
can you just confirm the below version of the addon also doesnt work.
I just removed the proxy stuff and simplified the headers.
Be great if you could provide a new debug log using the below
[slyguy.disney.plus.zip](https://github.com/peak3d/inputstream.adaptive/files/5485065/slyguy.disney.plus.zip)

**Comment by matthuisman** [comment]
@haduvelko
then after doing the above, make sure SlyGuy common is latest version (0.13.4)
then install the below version of Disney+ and get it to fault.
[slyguy.disney.plus.zip](https://github.com/peak3d/inputstream.adaptive/files/5485164/slyguy.disney.plus.zip)

After its faulted, there will be 2x files in the **userdata/addon_data/script.module.slyguy** directory
Should be named **post-4-in.txt** & **post-4-out.txt**  (the number 4 may be different)
Upload both of those here. 

post-4-in.txt contains the binary data that is being sent from Kodi > Disney
post-4-out.txt contains the binary data received back from Disney

**Comment by haduvelko** [comment]
> @haduvelko
> can you just confirm the below version of the addon also doesnt work.
> I just removed the proxy stuff and simplified the headers.
> Be great if you could provide a new debug log using the below
> [slyguy.disney.plus.zip](https://github.com/peak3d/inputstream.adaptive/files/5485065/slyguy.disney.plus.zip)

I tried this again black screen, here is log filee http://paste.kodi.tv/uxuberigir

I tried second suggestion too but can get it to fault, addon works same like before with black screen (slyguy repository latest version)

**Comment by matthuisman** [comment]
Please follow my 2nd suggestion
https://github.com/peak3d/inputstream.adaptive/issues/549#issuecomment-721478808

**Comment by haduvelko** [comment]
I followed your 2nd suggestion i don't get any fault only black screen and in folder you say i only have post-4-in.txt no out text file.

Here is post-4-in.txt
[post-4-in.txt](https://github.com/peak3d/inputstream.adaptive/files/5489915/post-4-in.txt)

**Comment by matthuisman** [comment]
By fault, I meant the issue happens (black screen). Can you now turn off secure, and confirm playback still works and then upload the two files that creates (should have 2 when it works)

**Comment by haduvelko** [comment]
What you mean by turn off secure?

**Comment by matthuisman** [comment]
In the add-on settings, turn off L1 Secure Device

**Comment by haduvelko** [comment]
Playback still works, like always when L1 is turned off and video is 720p resolution, but now i have two files in and out.
[post-4-in.txt](https://github.com/peak3d/inputstream.adaptive/files/5490006/post-4-in.txt)
[post-4-out.txt](https://github.com/peak3d/inputstream.adaptive/files/5490007/post-4-out.txt)

**Comment by matthuisman** [comment]
interesting, in your WV post data, it has **oem_crypto_security_patch_level 02**
even though device is L1. unless that is a different level..
Also, your log says MaxSecurityLevel: -1
So maybe IA / Kodi aren't detecting the Widevine level correctly?

Maybe @peak3d  has some input.

@peak3d 
With force secure on, this is the data Kodi posts to license server: https://github.com/peak3d/inputstream.adaptive/files/5489915/post-4-in.txt
Results in 403 error and returns **{"errors":[{"code":"downgrade","description":"capability-hd"}]}**

Without force secure, this is the data Kodi posts to license server: https://github.com/peak3d/inputstream.adaptive/files/5490006/post-4-in.txt
and the good response: https://github.com/peak3d/inputstream.adaptive/files/5490007/post-4-out.txt

I'll try get the same data from my Shield so we can compare.

UPDATE:
Did same with Nvidia shield, and I see that does two requests.
The 1st being 2 bytes. So it's doing the VMP stuff.
For some reason, yours isn't doing that.
Even with force secure off - it still does the two requests

**Comment by matthuisman** [comment]
so, recreating his Secure WV request, the server returns
**{"errors":[{"code":"downgrade","description":"capability-hd"}]}**

**Comment by L2501** [comment]
maybe related to 
https://old.reddit.com/r/netflix/comments/jq9wdb/netflix_capped_at_166mbps480p/

**Comment by haduvelko** [comment]
It is not related, because google play apps like netflix and disney plus works in 4k, kodi netflix addon works in 4k too i only have problem with disney plus kodi addon.

Update:

I read all post from reddit and see that my tv use same SOC that is affected MediaTek MT5891 and downgrading L1 to L3 but i don't know how for me in native apps everything works fine, i hope when Philips in future firmware update solve problem with SOC, maybe it will resolve my problem with kodi too.

Update2:

@matthuisman 

Now my native apps can't get 4k L2501 user was right  my TV use SOC that is affected and downgrading Widevine, Philips said that in new firmware update they will fix this problem. So when they update firmware i will update what happening with Disney Plus Kodi Addon and if i get positive result this issue will be closed.

**(Philips TVs using the MT5891-soc can stream again in 1080p resolution. However, streaming in 4k is not yet possible, which is only possible if a vulnerability is resolved with a software update. That update can take several months.)**

**Comment by haduvelko** [comment]
@matthuisman 

After Philips rollout firmware update Disney Plus Kodi addon works in 4K.

This isue can be closed now.

Matthuisman thank you so much for your support, and thanks Arek for reddit post.

**Comment by matthuisman** [comment]
@haduvelko 
Great to hear!
Thanks for letting me know.
