### ISSUE TITLE
DV purple tinting on BRAVIA

### ISSUE THREAD

**Issue by CiNcH83** [peak3d/inputstream.adaptive#557]
DV content on BRAVIA exhibits purple tinting. I have recorded a video, illustrating the ill-effect:

https://www.youtube.com/watch?v=n-sWh-okeBU

When initiating playback of DV content there seems to be some switching back and forth between color profiles. The one chosen then has purple tinting to it. Weird thing is that after playing back DV content in Kodi, also the Netflix app is affected. Looks like Kodi causes some improper DV initialization which is then kept system-wide. Only restarting BRAVIA fixes the Netflix app.

**Comment by glennguy** [comment]
@CiNcH83 I don't know if this would be an issue specifically with IA... have you tried using a DV file from your library or a test file to see if it happens in that case?

**Comment by CiNcH83** [comment]
Not sure whether DV from file is supported by now. Think there has been a PR in that regard. So I will check.

**Comment by CiNcH83** [comment]
OK. Here is some more info...

The problem seems to be with intros at the beginning of a video. Like with Netflix' _Our Planet_. The transission between segments somehow seems to mess with the DV decoder, resulting in the purple tinting, afterwards requiring a reboot of the TV to fix it.

**Comment by CastagnaIT** [comment]
i close the issue since we have no way to investigate or find a fix
however on Kodi nightly (future Kodi v21) has been introduced improvements for HDR/DV
but i am not sure if could fix your problem
