### ISSUE TITLE
[MPD] Wrong segment number calculated

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#560]
Unix timestamp of test:  approx 1606270484

kodi calculated segment: **383716778** (/video6/segment-383716778.m4s)
correct segment: approx **401567613** (/video6/segment-401567613.m4s)

Segments are 4s in length

Difference = 17,850,835 segments = 71,403,340 seconds (826 days)

The UTCTiming in the mpd file is correct to unix timestamp

MPD attached
[manifest8.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5594054/manifest8.mpd.txt)

**Comment by matthuisman** [comment]
if I proxy it and add **17850835** I get the correct live segemtn.
If i add any more it's too far ahead.

**Comment by matthuisman** [comment]
ok, so if I proxy and remove the presentationTimeOffset it calcs the correct segment (well 60 seconds off but thats due to UTCTiming vs publishTime)

Months ago, I had another mpd where the segment was calculate wrong (below is that mpd)
[old_fixed.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5628482/old_fixed.mpd.txt)

That issue was fixed with this commit: https://github.com/peak3d/inputstream.adaptive/commit/dc7b42783d18c65ebcf205a4979a1c9ea6b825e7

That commit introduces parsing presentationTimeOffset which is causing the issue with this mpd.

**Comment by matthuisman** [comment]
possible fix pr here:
https://github.com/peak3d/inputstream.adaptive/pull/564

**Comment by CaptainTK** [comment]
By now most of the BBC's live programmes are affected by this, or a very similar, issue. Streams play fine in VLC, but inputstream.adaptive calculates incorrect (old) segments.

Given the large number of users of plugin.video.iplayerwww it would be highly appreciated if this issue would be addressed as quickly as possible.

**Comment by matthuisman** [comment]
@CaptainTK 
please try this build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-564/7/artifacts

**Comment by CaptainTK** [comment]
A quick test looks good to me, @matthuisman. Great work!
