### ISSUE TITLE
With Coreelec version 9.2.5, CPU usage is unstable

### ISSUE THREAD

**Issue by matthuo333** [peak3d/inputstream.adaptive#561]
The operating environment:
The Device : X96 Max Plus
The SOC : S905X3
OS: CE 9.2.5
Addons: CastagnaIT/plugin.video.netflix 1.10.1
IA : The latest version

The process that occurs:
Step1: Select VP9 decoding on the setting of addons.
Step2: Open the kodi log in Setting-System and display the CPU load percentage.
Step3: Open a movie with a resolution of 1080p or above

At this moment, you will find that the 4 cores of the CPU have uneven load distribution, some cores are 0%, and some are 100+%.
Cause the picture to freeze, drop frames.

I have backed up the video recording under unstable conditions, but because I was identified as a new user by this forum system, I couldn’t upload it.

In addition, if I play the same video on 9.2.2, the CPU will not be unstable

BTW, The staff of the CE team said it might have something to do with IA

**Comment by arthur-liberman** [comment]
The team staff said that the S905X3 is not powerful enough to play Netflix at 1080P.
Reference: https://discourse.coreelec.org/t/the-issue-with-version-9-2-5-cpu-usage-is-unstable/13690
