### ISSUE TITLE
Kodi 19 beta 1 TVOS - inputstream.adaptive missing 

### ISSUE THREAD

**Issue by boldiebold** [peak3d/inputstream.adaptive#562]
Hope I'm right here.
Installed new beta 1 of Kodi 19 on TVOS.

inputstream.adaptive is missing and is not possible to download anywhere.
Do I have compiled it by myself, or is it actually missing in official mirrors 

Thanks
PS: Last snapshot containing it was Alpha 2 in Alpha 3 it was missing, too

**Comment by debennett2** [comment]
Use the latest daily. It works fine

**Comment by boldiebold** [comment]
You have the inputstream.adaptive in the lastest daily? 
I don´t have it . Just inputstream.rtmp in the add-on directory
I need it for my PVR testing

What did you do to get it ?  Just signed the daily from mirrors. Kodi.tv and pushed it via Xcode to the appletv?

**Comment by fuzzard** [comment]
Inputstream.adaptive does not build for tvos. I dont have the details offhand, but one of the files uses macos specific functions that are deprecated on ios/tvos. Just so happens in xcode 11.2 i think, this deprecated function is completely removed, so building with xcode newer than that is not possible.

The exact same issue will be a problem for ios at some point as well.

**Comment by fuzzard** [comment]
https://github.com/peak3d/inputstream.adaptive/pull/568

Should fix building the addon for tvos. Once merged, v19 nightlies should start bundling IA again.

Please note, there is no openly available aarch64 widevine lib, so this does not change the fact that ios/tvos will not playback widevine drm.

**Comment by boldiebold** [comment]
Do you know when we can expect a merge ? Stil not available in Kodi RC

**Comment by fuzzard** [comment]
Peak3d is extremely busy with work, and currently no other team member has commit privs on this repo. Working through that, but no ETA currently

**Comment by phunkyfish** [comment]
Merged and closing issue.
