### ISSUE TITLE
How to get a higher version than 2.4.4 on Retropie-raspi?

### ISSUE THREAD

**Issue by 6heads** [peak3d/inputstream.adaptive#569]
Wanted to use my retropie-raspi to play disney+
I atleast need v2.4.5 to make it work, but unfortunately all I get "apt-get install kodi-inputstream-adaptive" is v2.4.4

I already tried using another repo http://www.deb-multimedia.org/ but then I get another kodi as well and it won't even start. If I force just the installation of the supplied inputstream.adaptive-package I can play videos, but all I see is black.

Do I need to build it myself? If so how?

It's a raspberry 3B+ with Raspbian Buster upgraded to the latest kernel. I wonder why I didn't get 18.9 which seems to be the latest version - I only can install 18.7.

**Comment by matthuisman** [comment]
try _apt-get remove kodi-inputstream-adaptive_
then install this via "Install zip" method in Kodi.
https://f.mjh.nz/ia/2.4.5.1-linux-armv7.zip

**Comment by 6heads** [comment]
> try _apt-get remove kodi-inputstream-adaptive_
> then install this via "Install zip" method in Kodi.
> https://f.mjh.nz/ia/2.4.5.1-linux-armv7.zip

Sound plays, but the video can't be seen (black screen).

**Comment by matthuisman** [comment]
what version Kodi is retropie using?

**Comment by 6heads** [comment]
Are there any logs that could hint me why I get black screen?

**Comment by matthuisman** [comment]
could try provide a full debug log and see if anything there.
Also check your video settings. Should have HW decoding enabled etc.

**Comment by 6heads** [comment]
Pasted my log [here](https://paste.kodi.tv/ozohotifej.kodi)

2020-12-09 10:12:34.690 T:1553653968  NOTICE: Creating InputStream
2020-12-09 10:12:34.691 T:1553653968   ERROR: CVideoPlayer::OpenInputStream - error opening [/var/run/lirc/lircd]
2020-12-09 10:12:34.691 T:1553653968  NOTICE: CVideoPlayer::OnExit()
2020-12-09 10:12:34.691 T:1553653968   DEBUG: Thread VideoPlayer 1553653968 terminating

**Comment by matthuisman** [comment]
Try do
sudo mkdir /var/run/lirc

**Comment by matthuisman** [comment]
Not sure if that's the actual issue.. Where is rest of log? Need to show trying to play something...

**Comment by 6heads** [comment]
I copied the entire log and I started a stream.

I created the suggested directory and did it again: [here](https://paste.kodi.tv/ginaxixipa.kodi)

**Comment by 6heads** [comment]
I used PINN for a dual installation of libreelec and retropie and now it works smoothly. 
I guess retropies sources are just too old.

**Comment by matthuisman** [comment]
@6heads
if you still have the retropie up, could you try go install the Disney+ add-on.
Then go into it's settings > playback and click Install Widevine.
Then reboot, then test :)

**Comment by matthuisman** [comment]
@6heads

found the issue:
https://github.com/RetroPie/RetroPie-Setup/pull/3135
You need to install libnss3 for Widevine to work (retropie is missing that)

**sudo apt-get install libnss3** 

just pushed update to my widevine install code.
it will now try to install libnss3 when installing

**Comment by 6heads** [comment]
> @6heads
> 
> found the issue:
> [RetroPie/RetroPie-Setup#3135](https://github.com/RetroPie/RetroPie-Setup/pull/3135)
> You need to install libnss3 for Widevine to work (retropie is missing that)
> 
> **sudo apt-get install libnss3**
> 
> just pushed update to my widevine install code.
> it will now try to install libnss3 when installing

After reinstalling retropie, upgrading it and installing the provided adaptive-zip I didn't need to install libnss3.
Maybe you could include kodi-inputstream-adaptive as well?
