### ISSUE TITLE
Wvdecrypter "make" error

### ISSUE THREAD

**Issue by AeonNoeA** [peak3d/inputstream.adaptive#57]
Im on a Ubuntu machine and, as per instructions to build the "wvdecrypter" im stuck at make by getting the following error:
Thank you
Error message received
........
[ 14%] Building CXX object libbento4/CMakeFiles/bento4.dir/Core/Ap4OddaAtom.cpp.o
[ 15%] Building CXX object libbento4/CMakeFiles/bento4.dir/Core/Ap4PdinAtom.cpp.o
[ 15%] Building CXX object libbento4/CMakeFiles/bento4.dir/Core/Ap4.cpp.o
In file included from /home/kodi/Downloads/inputstream.adaptive-master/lib/libbento4/Core/Ap4Piff.h:43:0,
                 from /home/kodi/Downloads/inputstream.adaptive-master/lib/libbento4/Core/Ap4.h:300,
                 from /home/kodi/Downloads/inputstream.adaptive-master/lib/libbento4/Core/Ap4.cpp:32:
/home/kodi/Downloads/inputstream.adaptive-master/lib/libbento4/Core/Ap4CommonEncryption.h: In member function âvirtual const char* AP4_CencSingleSampleDecrypter::GetSessionId()â:
/home/kodi/Downloads/inputstream.adaptive-master/lib/libbento4/Core/Ap4CommonEncryption.h:525:49: error: ânullptrâ was not declared in this scope
     virtual const char* GetSessionId() { return nullptr; };
                                                 ^
make[2]: *** [libbento4/CMakeFiles/bento4.dir/Core/Ap4.cpp.o] Error 1
make[1]: *** [libbento4/CMakeFiles/bento4.dir/all] Error 2
make: *** [all] Error 2

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/a1d7d2ef14f8ac853c192e4756d046aedd4b6057
