### ISSUE TITLE
How to get widevine license key drm for mpd

### ISSUE THREAD

**Issue by croszw** [peak3d/inputstream.adaptive#572]
Hey sir i have a question. Can you help me to get this video https://cdn-telkomsel-01.akamaized.net/Content/DASH/Live/channel(2dbe8ad3-8113-46ba-9aea-d218b7970c66)/manifest.mpd so i can put it into my iptv playlist?

I dont know about license server and key 

Some information i get https://lic.drmtoday.com/license-proxy-widevine/cenc/?logRequestId=ec828931bffe1ee68f7cccf47ed036bf&assetId=DASHANIPLUSDRM

**Comment by glennguy** [comment]
@croszw both urls look to be fine on the surface, however github issues aren't really meant for helping users to find stream. You're better off opening a thread in the appropriate Kodi forum.
