### ISSUE TITLE
[MPD] Multiple-period live starting at end of 1st period instead of end of 2nd period

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#574]
with attached mpd, IA will start playback at the end of the 1st period instead of the end (live) of the 2nd period. 

[master.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5683917/master.mpd.txt)
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5691789/kodi.log)

1st period = segments 1 to 891
2nd period = segments 892 to live

You will see from the log, IA starts playing at segment number 888 (end of 1st period)

**Comment by matthuisman** [comment]
seems this may not be possible to fix in IA

A workaround is too set a high resume time (larger than buffer size) in add-on.
As buffer size can change / differ - I just use a large number like 12 * 60 * 60 (12 hours)

Play from Live
```
li.setProperty('ResumeTime', '43200')
li.setProperty('TotalTime', '1')
```

Play from Start
```
li.setProperty('ResumeTime', '1')
li.setProperty('TotalTime', '1')
```

Note: 
some streams audio stops working when using ResumeTime
PR: https://github.com/xbmc/inputstream.adaptive/pull/685 fixes that issue

**Comment by matthuisman** [comment]
@CastagnaIT do you think your big PR would help solve this?
Be nice to be able to remove the seek time hack

There was an attempt here: https://github.com/xbmc/inputstream.adaptive/pull/1176

**Comment by CastagnaIT** [comment]
I haven't changed this part yet i didn't investigate well
i'm wondering if HLS suffers from the same problem

**Comment by CastagnaIT** [comment]
@matthuisman with PR #1518 now period should work as expected
if you can give a feedback
