### ISSUE TITLE
Cannot install zip release on my SPMC

### ISSUE THREAD

**Issue by AnthraxBass** [peak3d/inputstream.adaptive#576]
Hi, guys. 
I'm having trouble installing "InputStream Adaptive" on my SPMC... 
I've tried zip version "2.6.6-Matrix, Nov 21" and "2.5.6-Matrix, Apr 26". 
Please tell me how can I install zip release (not via the repository). 
P.S. My android-box parameters are in the attached screenshot, please take a look. 
![Spmc](https://user-images.githubusercontent.com/3393365/102687641-2cd8cd00-41f9-11eb-8835-f3911c63db33.png)

**Comment by CastagnaIT** [comment]
if you want to use matrix version of InputStreamAdaptive you have to install the new version of Kodi 19 your SPMC is prehistory
