### ISSUE TITLE
plugin unavailable in fedora 33

### ISSUE THREAD

**Issue by Kidlike** [peak3d/inputstream.adaptive#578]
I'm trying to use the Netflix plugin (https://github.com/CastagnaIT/plugin.video.netflix) in Fedora 33 + Kodi 19.

Login works properly, but when trying to start streaming something, I get the error
> **inputstream.adaptive** is missing on your Kodi install. This add-on is required to play this content.

```
$ kodi --version
19.0-BETA2 (18.9.821) Git:20201207-nogitfound Media Center Kodi

$ dnf info kodi
Installed Packages
Name         : kodi
Version      : 19.0
Release      : 0.8.20201207git8cc9e80.fc33
Architecture : x86_64
Size         : 71 M
Source       : kodi-19.0-0.8.20201207git8cc9e80.fc33.src.rpm
Repository   : @System
From repo    : rpmfusion-free-updates
Summary      : Media center
URL          : http://www.kodi.tv/
License      : GPLv2+ and GPLv3+ and LGPLv2+ and BSD and MIT
Description  : Kodi is a free cross-platform media-player jukebox and entertainment hub.
             : Kodi can play a spectrum of of multimedia formats, and featuring playlist,
             : audio visualizations, slideshow, and weather forecast functions, together
             : third-party plugins.
```

**Comment by Kidlike** [comment]
I made this work, by building the plugin myself, following the instructions here: https://github.com/peak3d/inputstream.adaptive/wiki/How-to-build

Of course with some deviations:
- using `19.0b2-Matrix` as branch for cloning xbmc (it's actually a tag and not a branch, but works fine)
- using `Matrix` branch for cloning the inputstream.adaptive repo

---

So, this is probably reported in the wrong place... But I'm a bit lost for who is responsible for shipping this plugin together with Kodi. It's supposed to be included by just installing Kodi, right?
Even if it's not, this plugin is not available in the official addon repository of Kodi.

And then, who is responsible for publishing Kodi itself to the rpmfusion repo?

I'm so confused :smile: 

Anyway... I hope at least this report/solution can help others...

**Comment by glennguy** [comment]
I can't speak on Fedora but for example in Ubuntu inputstream.adaptive is a separate package in the package manager:
` apt install kodi`
` apt install kodi-inputstream-adaptive`

**Comment by Kidlike** [comment]
oooooh... :man_facepalming: 

yes it's indeed there... I was not aware that this addon was supposed to be coming from the package manager...

`dnf install kodi-inputstream-adaptive`

---

Maybe it's worth noting this in the main readme file of this repo?

Because currently it reads:
> this addon is part of the official kodi repository and part of each kodi installation

which is very misleading. At least for me - I thought that it's supposed to come pre-installed.

I would propose something like the following:

---

#### Installation
- Typically this add-on should be available in your package manager as `kodi-inputstream-adaptive`
  - Ubuntu: `apt install kodi-inputstream-adaptive`
  - Fedora: `dnf install kodi-inputstream-adaptive` (from the `rpmfusion` repository)

**Comment by lfarkas** [comment]
but not working:-( it was working with fedora 31 and kodi 18. after i update to fedora 33 and kodi 19 and change to the new netflix plugin (CastagnaIT Repository for KODI 19.x MATRIX - repository.castagnait-1.0.0.zip) now longer works. this means netflix can login and start to play movie but only sound comes and a few noise image. the voice are good. anyone can fix it or find any solution?

**Comment by Kidlike** [comment]
I didn't experience any issues like that.

Maybe check your GPU, drivers etc...

If it's any worth, I'm running with X11 and not Wayland.

**Comment by lfarkas** [comment]
I'm also run with X11. and neither of my 4 fedora 33 run it (different cpu, laptop, media server etc). same affect everywhere.
