### ISSUE TITLE
[Question] how to pass license correctly to EME endpoint?

### ISSUE THREAD

**Issue by shycoderX** [peak3d/inputstream.adaptive#579]
I'm trying to create an addon for TelenetTV but I keep having issues with license request..

Before requesting the license a token is acquired using the **/oesp/v4/BE/nld/web/license/token** endpoint format like so

Request:
`{"contentLocator": "", "deviceId": ""}`
Response:
`{"token":""}
`
with the received token I can fetch the .mpd file 
`wp1-halo01-vxtoken-live-be-prod.tnprod.cdn.dmdsdp.com/dash/vijfhd;**vxttoken=**/manifest.mpd
`

after that has been done, I can see the browser requests a **cert_license_widevine.bin** and after that it requests the license via the **license/eme** endpoint. But.. if I block the request using chrome dev tools for the cert_license_widevine.bin it does something differently, it sends two requests to the license/eme endpoint one with bytes **0x08 0x04** which receives like the widevine certificate I guess? and in the second request it returns the actual license.

The problem is I don't know how to do the magic to make this work in Kodi, I tried doing the first license/eme request using the requests library and base64encoding the response to pass it to **inputstream.adaptive.server_certificate** but that doesn't even seem to do anything? If I send the widevine payload using R{SSM} to the license/eme endpoint I get the following error message
`[{"type":"state","code":"concurrency","reason":"invalid"}]`

Could anyone steer me in the right direction or offer some help in any way? 

**FYI: It seems that the web player uses shaka player**

Probably related to #290

**Comment by glennguy** [comment]
from 290:
>if your service supports playback in web browsers you can check if VMP is required by trying to play it in chrome and vivaldi on windows (unlike chrome there won't be any playback in vivaldi)`

Have you tried this yet?

**Comment by shycoderX** [comment]
> from 290:
> 
> > if your service supports playback in web browsers you can check if VMP is required by trying to play it in chrome and vivaldi on windows (unlike chrome there won't be any playback in vivaldi)`
> 
> Have you tried this yet?

Yes I got the web requests by using Fiddler on the website version of the service. Even tried it on Linux (when widevine is installed at least) it plays the stream.

**EDIT:** Sorry, so if I understand correctly the service only allows certain webbrowsers if VMP is enabled? It doesn't work on vivaldi indeed. It tells me that the browser isn't supported. So is there any way around?

**Comment by shycoderX** [comment]
Ok, never mind my edit above for some reason it **DOES** work now on vivaldi suddenly..

**Comment by matthuisman** [comment]
i just tried vivaldi with hbo max Wonder woman and it works (on windows)
I see the two requests, so I suspect vivaldi now supports VMP

**Comment by shycoderX** [comment]
> i just tried vivaldi with hbo max Wonder woman and it works (on windows)
> I see the two requests, so I suspect vivaldi now supports VMP

How is the browser verified is it in the encrypted payload?

**EDIT:** as the stream also played on ubuntu and the widevine website states "VMP support is NOT available for Linux platforms". does that mean this serivice **DOES NOT** have VMP enabled?

**Comment by glennguy** [comment]
Hard to be sure, there's no public documentation for how providers can configure things on widevine's end. It's possible that VMP is enabled per platform.

**Comment by glennguy** [comment]
@shycoderX how did you end up going with this one? Was it VMP? Can the issue be closed?
