### ISSUE TITLE
Another licence related custom header is required

### ISSUE THREAD

**Issue by gedasm** [peak3d/inputstream.adaptive#58]
**X-AxDRM-Message**

It's for Axinom based Widevine implementations and Kodi internals are blocking it for being set.

So while this, obviously, works:
`#KODIPROP:inputstream.adaptive.license_key=http://drm-widevine-licensing.axtest.net/AcquireLicense|User-Agent=MozillaCustomAgent|A{SSM}|`

this doesn't:
`#KODIPROP:inputstream.adaptive.license_key=http://drm-widevine-licensing.axtest.net/AcquireLicense|X-AxDRM-Message=eyJ0eX|A{SSM}|`

and it **should** in order to obtain the  license  key.

Kodi 17.4 debug log yields:

> DEBUG: CurlFile::ParseAndCorrectUrl() ignoring header option 'X-AxDRM-Message:

**Comment by peak3d** [comment]
It was already fight to get the header filter removed from kodi 18, tbh. I don't want to do the fight for K17 again. Pls. try K18, it should work with it.

**Comment by gedasm** [comment]
Oh, I did not know Kodi 18 supposedly had the filter removed. I'll definetely try it out.

**Comment by gedasm** [comment]
BTW... Would it be possible to modify this input addon and write a little standalone app to output combined stream to stdout? That would allow watching on VLC and other players.

**Comment by peak3d** [comment]
From theory its not rocket science to write an app around it.
I'll NOT do it because we curently request streaming licenses from DRM systems and they are not thought to get written to either stdout  or file.

**Comment by gedasm** [comment]
I understand that... Last question (which probably warrants its own new issue) now. Inputstream fails to even open manifest files when pssh box is missing in mpd file.

I'm dealing with this content provider that has manifests files without pssh fields and it uses init mp4's for that. It's fully working and I even managed to get Google's Shaka player to get the keys from their WV license server. What could be done with Inputstream for Kodi?

**Comment by peak3d** [comment]
Its already implemented and should work.

**Comment by gedasm** [comment]
But it doesn't for some reason. Again, Shaka works fine. And in Kodi debug log I see parseMPD errors.

`<Period duration="PT1H36M16.920S">
<AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="25" par="16:9" lang="und">
<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="__SKIPPED__"/>
<SegmentTemplate timescale="12800" media="dash_$RepresentationID$_$Number$.m4s" startNumber="1" duration="51200" initialization="dash_$RepresentationID$_.mp4"/>
<Representation id="1" mimeType="video/mp4" codecs="avc1.42c015" width="512" height="288" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="390248">
</Representation>
<Representation id="`

As you can see MPD file even has Widevine's ID missing.

And here's excerpt from init mp4:

`..дpssh....љ.рy.SKIPFEWBYTES.ДД.......є.<.W.R.M.H.E.A.D.E.R. .x.m.l.n.s.=.".h.t.t.p.:././.s.c.h.e.m.a.s...m.i.c.r.o.s.o.f.t...c.o.m./.D.R.M./.2.0.0.7./.0.3./.P.l.a.y.R.e.a.d.y.H.e.a.d.e.r.". .v.e.r.s.i.o.n.=.".4...0...0...0.".>.<.D.A.T.A.>.<.P.R.O.T.E.C.T.I.N.F.O.>.<.K.E.Y.L.E.N.>.1.6.<./.K.E.Y.L.E.N.>.<.A.L.G.I.D.>.A.E.S.C.T.R.<./.A.L.G.I.D.>.<./.P.R.O.T.E.C.T.I.N.F.O.>.<.K.I.D.>.e.1.n.c.B.N./.d.k.d.F.e.8.4.O.l.v.L.C.r.V.Q.=.=.<./.K.I.D.>.<./.D.A.T.A.>.<./.W.R.M.H.E.A.D.E.R.>.`

Only PlayReady is visible and no sign of WV. Unless that pssh field is enough to make Shaka work. But then again, the above manifest file fails to be parsed by Inputstream in Kodi.

Any suggestions?

**Comment by peak3d** [comment]
1.) From where do you know that shaka player does not use playready DRM for it?
2.) I can't give support if you provide minmal information. Snippets from something does not help in any way. If we want to go further I'll need the complete mpd manifest file and the complete initialization segment.

**Comment by gedasm** [comment]
1. Because I run it from Firefox and I see being Shaka doing requests to https://drm-widevine-licensing.axprod.net/AcquireLicense in Developer tools. And it's the only license server I have specified for it. I wouldn't know how to request keys from PR :)

2. Can I emal the files to you?

**Comment by gedasm** [comment]
I just sent email with a couple of files attached :)

**Comment by gedasm** [comment]
Thanks to @peak3d everything discussed in this issue has been resolved with latest changes that made it to the Kodi 18 nightly. It can be closed!

**Comment by Zoom-Adr** [comment]
#KODIPROP:inputstream.adaptive.license_key=http://drm-widevine-licensing.axtest.net/AcquireLicense|X-AxDRM-Message=eyJ0eX|A{SSM}|

how do you solve it?
