### ISSUE TITLE
DRM decoding problem

### ISSUE THREAD

**Issue by YMaas** [peak3d/inputstream.adaptive#581]
I am using the retrospect addon with inputstream adaptive addon and have the following issue on a samsung galaxy A40: when playing drm content it looks like the keyframes are not decoded in the right way resulting in screen artifacts while playing please see the attached screen shots:the first seconds are ok and then the following frames are calculated based on the previous frames and the key frames look like there missing/not decoded well or something

![Screenshot_20201230-151147_Kodi](https://user-images.githubusercontent.com/61164604/103356605-8b336480-4ab1-11eb-8a53-ca6bd141e9c0.jpg)
![Screenshot_20201230-151158_Kodi](https://user-images.githubusercontent.com/61164604/103356620-8ec6eb80-4ab1-11eb-9d3e-a6052982a3c2.jpg)

Question: what kind off information do i have to provide so there can be a solution for this problem. If i use other devices android or rpi 4 based there are no issues with this addon and DRM 

Thanks

**Comment by Testato** [comment]
Probably related to #638

It seems that the hw widivine decrypt is active, but it stuttering

**Comment by glennguy** [comment]
@Testato I don't think the issue is related.

@YMaas could you provide a full debug log capturing the issue? You can upload it to paste.kodi.tv or similar and put the link here.

**Comment by Testato** [comment]
The kind of artifact is the same, i mean the second part of my issue.
There is a way for check in realtime the kodi logfile on the phone connected to a pc ?

**Comment by glennguy** [comment]
I just copy the log file over to PC through USB.

**Comment by CastagnaIT** [comment]
@YMaas please can you let us know if with the latest version of Kodi 19 Matrix the problem still occurs?
if it keeps happening, we need also that you attach here the Kodi Debug Log file (https://kodi.wiki/view/Log_file/Easy)
