### ISSUE TITLE
Force hardware decryption on android tv

### ISSUE THREAD

**Issue by lpuglia** [peak3d/inputstream.adaptive#582]
Hello, happy new year! sorry if this is not the right place but I need some clarification about how the decryption process is performed when input stream.adaptive is used.

I just bought a phillips ambilight android tv (it should have an arm cortex 53). Kodi seems to work great in all use cases I have tested so far, the only problem I came across is with encrypted streams (widevine DRM).

In particular I'm experiencing stuttering with this plugin: https://github.com/luivit/plugin.video.rivedila7
Unfortunately there is no android app for this channel, so my only chance is kodi app for android.

As far i can see the stuttering only occurs with live stream (unencrypted on demand streams work just fine). The stuttering gets more visible with the highest resolution (960x540, 1.7 Mbs).
My guess is that decryption is performed in software and the processor is no able to keep up with it (in fact I can see no problem with kodi on a pi4 which has a more beefy processor).

Can you clarify if this is a limitation of the plugin itself, inputstream.adaptive or kodi? Is there any configuration i can modify to force hardware decryption (which the tv is perfectly capable of since netflix app is in 4k)? If it is not possible at the moment is there any plan to implement it?

Thank you in advance for the clarification.

**Comment by Testato** [comment]
Probably related to #638

It seems that the hw widivine decrypt is active, but it stuttering

**Comment by glennguy** [comment]
As far as I know, on Android with secure decoder the decryption and decoding is done in Android's side of things. Kodi never gets to see decrypted data, IA sends Kodi encrypted data and Kodi hands it over to Android to decrypt, decode and display.

Maybe at that resolution it's still using Kodi for decoding the unencrypted data (widevine always does the decrypting)? If you can 
bring up the stream information (press 'o' key when playing, not sure how to do that on TV...) it should indicate if hardware or software decoding is happening.

**Comment by Testato** [comment]
I checked it on a PC with Ubuntu, it isn't a L1 widevine certified device, but by O button Kodi tell that it do HW decoding.
So also on a non L1 device it is possibile Hw widevine decoding ?

When by O button we read (HW) it means Hw decoding and Hw decrypting ?

**Comment by glennguy** [comment]
It means HW *decoding*, using AVC/h264, HEVC/h265 or whichever ***codec***. 

On all platforms supported except Android, libwidevinecdm.so / widevinecdm.dll / libwidevinecdm.dylib is the google supplied library that does the *decryption* - DRM encrypts the file with a secret key. The secret keys are contained within this widevine library, we can't see what they are. Inputstream.adaptive gives widevinecdm some encrypted data, and it returns us decrypted data. 

On Android there is no 'libwidevinecdm.so', widevine is built into Android from Lollipop onwards. The keys are stored somewhere in a hidden partition I believe, and if you root a device the L1 keys become invalidated or destroyed and you're put back to L3.

**Comment by lpuglia** [comment]
hello @glennguy, it has been a while since I was heavily invested in the debugging of this issue, I lost the full debug report (with some effort I can generate them again) but one thing that was very clear on my tv was this:

```
DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /data/app/org.xbmc.kodi-4we2fgtcBZsS1icd7sfk2g==/lib/arm/libssd_wv.so
```

which appears to be the compiled version of:
https://github.com/xbmc/inputstream.adaptive/tree/Matrix/wvdecrypter

am I wrong in saying that the decryption is done in software in this .so library?

**Comment by glennguy** [comment]
Hi @lpuglia 
Yes you are wrong, it is as described above. IA (formerly inputstream.mpd) was conceived with a modular decrypter library - one for widevine and future decrypters could be developed for playready, Marlin etc.
Merely structuring the binaries separately like this doesn't imply that the decryption happens in software.
With some changes everything could be part of libinputstream.adaptive.so

**Comment by lpuglia** [comment]
thanks for the clarification, here is the full log: https://controlc.com/97882668
if it is not enough, could you guide me through the process of obtaining more information?

**Comment by glennguy** [comment]
Hi @lpuglia 
The link no longer works, could you provide a new log?
All it needs is a fresh boot of Kodi, recreate the issue then capture log. Thanks!

**Comment by lpuglia** [comment]
@glennguy can you check again? it works on my side and should be public

**Comment by glennguy** [comment]
Any chance you could post a *full* log? This one is only from when the stream starts.

It is useful to see documented the system, processor etc. that is at the top of the log.

**Comment by Testato** [comment]
I read some info on difference beetween L1 L2 L3 device.
The L1 android device have Hw decoding and Hw decrypting.

Your TV if I remember is L1, so all should be in HW. Same for my Samsung S9+

**Comment by lpuglia** [comment]
@glennguy  here you are: https://controlc.com/9ed46711

**Comment by glennguy** [comment]
I don't think this issue is solvable within inputstream.adaptive.
Yes, avoiding the secure decoder gives good playback. But there are issues similar in other players, see https://github.com/google/ExoPlayer/issues/6348

Exoplayer have done some work to remediate the issue, this [blog write up](https://medium.com/google-exoplayer/improved-rendering-performance-operating-mediacodec-in-asynchronous-mode-and-asynchronous-buffer-3026207850b2) explains pretty well.

I don't imagine the task to be at all trivial to implement similar in Kodi.

At best I can guess that makers of the SOCs powering these Android devices have a line of thinking:
* The TV is 4k and 4K is the future in content
* 4K content will be protected with DRM
* Ensure h265/HEVC can play flawlessly
* h264 used for lower resolution and unprotected streams
* If there's a performance issue then providers like NF can work around it in their apps/content

**Comment by lpuglia** [comment]
just a note on the ExoPlayer thing. Since i was not able to see the stream clearly, back in January I decided to implement a stand alone adroid app to play it, here is the code: https://github.com/lpuglia/ExtTv

I can confirm that on the same device, using last year release (no method `experimental_setMediaCodecOperationMode()`) I can play the stream without stuttering:
https://github.com/lpuglia/ExtTv/blob/master/exttv/src/main/java/com/android/exttv/PlayerActivity.java#L107-L154

**Comment by lpuglia** [comment]
Latest inputstream adaptive version, solved my problem, thanks!
