### ISSUE TITLE
widevine HTTP returned error 500

### ISSUE THREAD

**Issue by KyKyIIIKuH** [peak3d/inputstream.adaptive#587]
Hello.
Sorry if this is not the right place.

There was a 500 error, when playing DRM content.

I will be grateful for your help.

Log file:
[error_play_widevine_cdm.log](https://github.com/peak3d/inputstream.adaptive/files/5789112/error_play_widevine_cdm.log)

**Comment by glennguy** [comment]
Not much that can be done to help from this end except point you in the right direction, I don't believe there is any bug of sorts in inputstream.adaptive causing your 500 error.

You need to compare what is happening in your browser/mobile app vs. kodi and modify [here](https://github.com/KyKyIIIKuH/plugin.video.wakanim/blob/master/resources/lib/streamparams.py#L218) accordingly.

**Comment by KyKyIIIKuH** [comment]
Thanks for the tip

**Comment by chamchenko** [comment]
Hi.
I don't know if I should open a new issue.
In my case I'm getting error 500 unless I force the Content-Type header to be empty (not application/x-www-form-urlencoded)
by adding &Content-Type= in the headers section
my code is here:
[https://github.com/chamchenko/plugin.video.cbsnetwork](url)
