### ISSUE TITLE
Loading of decrypter in Krypton branch is broken

### ISSUE THREAD

**Issue by stbenz** [peak3d/inputstream.adaptive#59]
I think [this commit](https://github.com/peak3d/inputstream.adaptive/commit/3be3da56a092cf21af6046fddf80f4cd334ec2f9) breaks loading of decrypter for Krypton, as the special path translates to /usr/lib/kodi/addons/inputstream.adaptive which doesn't exist, if the addon isn't built in with Kodi (as it is the case in e.g. LibreELEC 8.x). That results in the method returning [here](https://github.com/peak3d/inputstream.adaptive/blob/3be3da56a092cf21af6046fddf80f4cd334ec2f9/src/main.cpp#L1479) and therefore not searching in the second entry of `searchPaths`.

The resolution might be to change that `return` to a `continue`.

**Comment by stbenz** [comment]
It seems that this fix was [already committed](https://github.com/peak3d/inputstream.adaptive/commit/01e390ddbe4552fd4c5fe22332213bae0a4aab76) to the master branch and only has to be merged to the Krypton branch.

**Comment by peak3d** [comment]
It's backported now.
