### ISSUE TITLE
SegmentTemplate, media attribute doesn't support the input formatter %08x

### ISSUE THREAD

**Issue by ckuyehar** [peak3d/inputstream.adaptive#590]
Given the following example:

`<SegmentTemplate timescale="1000" duration="2048" startNumber="34800" initialization="audio/$RepresentationID$/init.mp4" media="audio/$RepresentationID$/$Number**%08x**$.m4s" presentationTimeOffset="71337126"></SegmentTemplate>`

It appears as though inputstream doesn't support the %08x formatter. This is demonstrated by inputstream incorrectly requesting the first segment 34800.m4s. With the use of %08x it is expected that the first segment should be 000087F0.m4s 

87F0 (hex) = 34800 (decimal)

I **think** resolving this issue will also fix another issue @ https://github.com/d21spike/plugin.video.sling/issues/22

**Comment by matthuisman** [comment]
it does support that. 

https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveStream.cpp#L288
It uses sprintf(http://www.cplusplus.com/reference/cstdio/sprintf/)
which supports the same format as printf (http://www.cplusplus.com/reference/cstdio/printf/)

**Comment by matthuisman** [comment]
@ckuyehar @phunkyfish can someone please close this issue.

1) IA does support %08x
2) The real cause of above issue has been found and fixed with PR: https://github.com/xbmc/inputstream.adaptive/pull/564
