### ISSUE TITLE
Same code works with Leia and 2.4.3 and fails with Matrix and 2.6.6

### ISSUE THREAD

**Issue by phate89** [peak3d/inputstream.adaptive#597]
Hi.
I was working on updating my addon to matrix when I encountered a problem with widevine content.
The same code (after fixes for python 3) works well and loads the video with kodi Leia but it fails to play internally in inputstream.adaptive with matrix (it doesn't start at all).
Here's the debug log for v18 (working):
https://paste.kodi.tv/fadutatuxa.kodi
and here's in matrix (not working):
https://paste.kodi.tv/ulirifacoh.kodi
I didn't have to change anything of the video calling to make it work in matrix.

**Comment by glennguy** [comment]
Hopefully a nice simple fix:
`2021-01-31 16:21:40.348 T:23008   ERROR <general>: CInputStreamAddon::Supports - 'inputstreamaddon' has been deprecated, please use '#KODIPROP:inputstream=inputstream.adaptive' instead`

If you are trying to maintain compatibility with both 18 and 19 just put both lines in eg.
```
listitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
listitem.setProperty('inputstream', 'inputstream.adaptive')
```

**Comment by phate89** [comment]
Uh I missed that line.. Thanks it works perfectly!
