### ISSUE TITLE
Débutant perdu !

### ISSUE THREAD

**Issue by KodiMesl** [peak3d/inputstream.adaptive#598]
Bonjour,

Je tente de suivre le tuto présenté mais je bloque, lorsque je rentre la commande suivante :
Clone the ISA master branch git clone --branch master https://github.com/peak3d/inputstream.adaptive.git

Voici le retour :
$ git clone --branch master https://github.com/peak3d/inputstream.adaptive/tree/Leia/inputstream.adaptive
Cloning into 'inputstream.adaptive'...
fatal: repository 'https://github.com/peak3d/inputstream.adaptive/tree/Leia/inputstream.adaptive/' not found

Que dois-je faire ?
Merci de votre aide

**Comment by jlbribeiro** [comment]
[disclaimer: I'm not a contributor/maintainer, just trying to help out]
Bonsoir @KodiMesl,

There are two things going on with your command:
- This repository does not have a `master` branch; judging by the fact you seem to be following instructions, it probably did have one in the past;
- The repository path in your 2nd command (`https://github.com/peak3d/inputstream.adaptive/tree/Leia/inputstream.adaptive`) is incorrect.

I think you probably meant to clone the `Leia` branch of this repository (judging by the path), so I think this should get you what you want:

```
git clone --branch Leia https://github.com/peak3d/inputstream.adaptive
```

If you're already running the `Matrix` version of Kodi, use `--branch Matrix` instead.
 I hope this helps! (and if so, please mark this issue as solved :) )
