### ISSUE TITLE
Initializing stream with unknown KID!

### ISSUE THREAD

**Issue by MPParsley** [peak3d/inputstream.adaptive#599]
I'm seeing this in the logs:
```
2021-02-01 19:57:50.187 T:1763201248 WARNING: AddOnLog: InputStream Adaptive: Initializing stream with unknown KID!
2021-02-01 19:57:51.347 T:1763201248   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2021-02-01 19:57:51.348 T:1763201248   ERROR: CCurlFile::Open failed with code 403 for https://wv-keyos.licensekeyserver.com/:
```

[The manifest](https://stream1-vod.cdn1.sbs.prd.telenet-ops.be/geo/MASTERCHEF_USA/S7/volledigeafleveringen/1014696209196152701075259120250694101469/MASTERCHEF_USA_7_2_F0278565/MASTERCHEF_USA_7_2_F0278565.mpd) doesn't provide a default_KID:
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:dvb="urn:dvb:dash-extensions:2014-1" xmlns:mspr="urn:microsoft:playready" xmlns:scte35="http://www.scte.org/schemas/35/2016" id="MASTERCHEF_USA_7_2_F0278565" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" mediaPresentationDuration="PT2315.541S" minBufferTime="PT10.000S" maxSegmentDuration="PT10.000S">
   <Period id="Period1">
      <AdaptationSet group="1">
         <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
         <ContentProtection schemeIdUri="urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" value="cenc">
            <cenc:pssh>XXX</cenc:pssh>
         </ContentProtection>
         <ContentProtection schemeIdUri="urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" value="MSPR 2.0">
            <cenc:pssh>XXX</cenc:pssh>
            <mspr:pro>XXX</mspr:pro>
         </ContentProtection>
```

Originally reported in https://github.com/add-ons/plugin.video.viervijfzes/issues/67#issuecomment-772279701

**Comment by michaelarnauts** [comment]
@MPParsley I think this is related to this: https://github.com/peak3d/inputstream.adaptive/issues/543#issuecomment-719534565

It should be fixed by this commit: https://github.com/peak3d/inputstream.adaptive/commit/30f3a74595fb6e33d871c5aac0df703a2c9a240c

**Comment by MPParsley** [comment]
Seems to the same as https://github.com/peak3d/inputstream.adaptive/issues/593

This seems to be the underlying issue:
```
2021-02-04 14:34:20.149 T:2604200816   DEBUG: Curl::Debug - TEXT: Connection #0 to host wv-keyos.licensekeyserver.com left intact
2021-02-04 14:34:20.149 T:2604200816   ERROR: CCurlFile::Open failed with code 403 for https://wv-keyos.licensekeyserver.com/:
                                            {"errorcode":371000005,"errormsg":"Widevine license acquisition failed >> Verified media path cannot be verified","errorid":"XXX"}
2021-02-04 14:34:20.149 T:2604200816   ERROR: AddOnLog: InputStream Adaptive: License server returned failure

```

**Comment by CastagnaIT** [comment]
> {"errorcode":371000005,"errormsg":"Widevine license acquisition failed >> Verified media path cannot be verified","errorid":"XXX"}

I could be wrong but I think your problem is due to VMP

in the past i have read of Verified media path on widevine page:
https://www.widevine.com/news
chapter: Browser CDM - Verified Media Path

some other has opened something related https://github.com/peak3d/inputstream.adaptive/issues/405
I think that if your add-on does not provide a certificate to ISA
you should consider trying to add the certificate on ISA listitem property

**Comment by glennguy** [comment]
Duplicate VMP issue
