### ISSUE TITLE
DASH Subtitles Supported?

### ISSUE THREAD

**Issue by guidosarducci** [peak3d/inputstream.adaptive#6]
While looking into BBC DASH streams, I also tried out a test stream they publish here 
[Elephants Dream](http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/). The first MPD includes a video, audio, and text stream, but I noticed Kodi 17b6 doesn't seem to find the subtitle stream.  Is this something that is or will be supported in the Kodi DASH implementation?

**Comment by peak3d** [comment]
Yep, already analyzed them, its a format currently not supported in kodi, but quite easy to implement.
On my TODO List

**Comment by peak3d** [comment]
subtitles implemented (TTML in mp4 / full file)
