### ISSUE TITLE
Please provide instructions for installing this add-on

### ISSUE THREAD

**Issue by JoeIsCool** [peak3d/inputstream.adaptive#611]
inputstream.adaptive is not in the main Kodi repository. It is often in the software repos of a distro, but adding it that way does not work if you are using 18.9 because it has to be built from source.

**Comment by flubshi** [comment]
Inputstream.adaptive should be in kodi main repo, see [here](https://kodi.wiki/view/Add-on:InputStream_Adaptive)

Build instructions can be taken from [wiki](https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build).

**Comment by JoeIsCool** [comment]
It's definitely not in the main Kodi repository. Is it possibly in other repositories?
When I build, I get:
```
`CMake Error at CMakeLists.txt:2 (project):
  Generator
  Unix Makefiles
  does not support toolset specification, but toolset
  host=x64
  was specified.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "../inputstream.adaptive/build/CMakeFiles/CMakeOutput.log"`
```
CMakeOutput.log says:
```
The system is: Linux - 5.8.0-44-generic - x86_64
```

**Comment by wsnipex** [comment]
On Linux, binary addons are not in the official repo, since we have no way to compile them for every combination of distro and hardware architecture. They should be supplied by whoever packages kodi, so refer to your distribution.
If you compile kodi yourself, you also have to compile binary addons.
