### ISSUE TITLE
No sound when timeshifting with IPTV Simple

### ISSUE THREAD

**Issue by BreizhReloaded** [peak3d/inputstream.adaptive#612]
_Following issue [#490](https://github.com/kodi-pvr/pvr.iptvsimple/issues/490) on IPTV Simple_

Hello,

I'm working on [this plugin](https://github.com/BreizhReloaded/plugin.video.orange.fr), redirecting web TV streams to Kodi via IPTV Simple and it works great on most use cases, but I noticed a strange behaviour. 

Steps to reproduce:
- Select channel and play stream
- Pause stream, starting timeshift
- Fast-forward 2x or 4x for a couple of seconds
- Then back to regular playback

When I perform those actions, video is ok, but I don't have any more audio. The only way to get it back is to press stop, and go back to live, losing the content in between. I can share the logs, but I don't see any error. It may come from my implementation, but I don't see where I'm wrong.

Here is a sample of my .m3u8 file:
```
## TF1
#EXTINF:-1 tvg-name="TF1" tvg-id="192" tvg-logo="https://proxymedia.woopic.com/553/p/logos/v2/logos/livetv_tf1/20180417_164011/webTVSquare/logo_150x150.png" tvg-chno="1" group-title="Orange TV France",TF1
plugin://plugin.video.orange.fr/channel/192
```

And the code called when selecting a channel:
```python
stream = Provider().get_stream_info(channel_id)
if not stream:
    dialog('This channel is not part of your current registration.')
    return

is_helper = inputstreamhelper.Helper(stream['manifest_type'], drm=stream['drm'])
if not is_helper.check_inputstream():
    dialog('Cannot load InputStream.')
    return

listitem = xbmcgui.ListItem(path=stream['path'])
listitem.setMimeType(stream['mime_type'])
listitem.setProperty('inputstream', 'inputstream.adaptive')
listitem.setProperty('inputstream.adaptive.manifest_type', stream['manifest_type'])
listitem.setProperty('inputstream.adaptive.license_type', stream['license_type'])
listitem.setProperty('inputstream.adaptive.license_key', stream['license_key'])
xbmcplugin.setResolvedUrl(plugin.handle, True, listitem=listitem)
```

Is a known limitation of InputStream Adaptive used with IPTV Simple?

Thanks!

**Comment by glennguy** [comment]
Will definitely need to see debug logs

**Comment by BreizhReloaded** [comment]
Hello @glennguy!
Here there are. Surprisingly, the steps mentioned above worked that time. I had to reproduce it three times to make the audio drops. It seems to be more stable than I imagined. Let me know if there is any manipulation I can do, I'm trying to find a way to reproduce the bug all the time. As far as I know, once I lose the audio, no way to get it back except getting back to live.
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/6132101/kodi.log)

Edit: from line 4829, there are warnings. 
`WARNING <general>: ActiveAE - large audio sync error: -14395.071045`

**Comment by BreizhReloaded** [comment]
More information: my main install runs on Windows 10 x64, but I was able to reproduce the bug on macOS Catalina too. Going backward makes it 100% of the time

**Comment by glennguy** [comment]
Just a stab in the dark here but can you try adding `listitem.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')` along with the other properties?

If that doesn't fix anything could you also post up the mpd file?

**Comment by BreizhReloaded** [comment]
That did the trick, thank you very much! Couldn't reproduce the bug so far, I'll keep you posted. What does this property do exactly?

By the way, once a a frame as been watched, I can't go backward before it. Is the buffer freed right after? Can I set that behaviour as well?

**Comment by dagwieers** [comment]
And please update the Wiki at: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemanifest_update_parameter

Our documentation could be much better.

**Comment by glennguy** [comment]
@dagwieers will do. First I need to understand a little bit more about how the routines actually differ at this if statement: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1694
I think the general gist is by default new segments are added to the existing list, and on"full" everything is overwritten/recalculated. Not sure though...
