### ISSUE TITLE
Clearkey - eurosport player

### ISSUE THREAD

**Issue by MRLB** [peak3d/inputstream.adaptive#613]
Hello,
Eurosport Player added clearkey to the streams. How can I add this to inputstream?

this is was I get:

protection |  
-- | --
clearkeyEnabled | true
drmEnabled | false
schemes |  
clearkey |  
licenseUrl | "https://discovery-eur.conax.cloud/fairplay/clearkey"
reportProgressInterval | 60000
sourceSystemId | "eurosport-e14981618c9945966ch1"

**Comment by Dis90** [comment]
If it's same as discovery+ you doesn't need to use mpd url and clearkey. drmEnabled is false so you can use hls url to play content. See https://github.com/Dis90/plugin.video.discoveryplus/blob/ea7020ca9b2141e148547e00b285934aa6fb307f/resources/lib/kodihelper.py#L274

As far as I know Inputstream Adaptive doesn't support clearkey.

**Comment by MRLB** [comment]
Thanks :-)
