### ISSUE TITLE
IA 2.4.5-Leia on LE 9.0.2

### ISSUE THREAD

**Issue by Gitta78** [peak3d/inputstream.adaptive#623]
I am trying to install IA 2.4.5-Leia from zip file on LibreElec 9.0.2, and I keep getting the error message

Failed to read '(...)/2.4.5-Leia.zip/inputstream.adaptive-2.4.5-Leia/addon.xml'

I checked my zip file, and it contains addon.xml.in instead of addon.xml, but it's hard to believe that this is the problem. For my hardware (Odroid C2) only LE 9.0.2 is available, no higher version. Does anybody have a suggestion how I can get IA 2.4.5 running on LE 9.0.2? Thanks.

**Comment by matthuisman** [comment]
try this: https://f.mjh.nz/ia/2.4.5.1-linux-armv7.zip

**Comment by Gitta78** [comment]
Yes, this works, thanks a lot.

**Comment by Mark4776** [comment]
I need to do the same but the file is gone, any chance you could share it again?

**Comment by matthuisman** [comment]
Just use the latest 2.4.7

**Comment by Mark4776** [comment]
I tried but it failed to install.

**Comment by matthuisman** [comment]
What hardware? Your running Leia?

**Comment by Mark4776** [comment]
Same as the OP, LibreElec 9.0.2 on an Odroid C2

**Comment by matthuisman** [comment]
oh, i see - libreelec repo no longer pushes newer version of IA for your hardware?

IA 2.4.7 for ARM:
**https://relkai.coreelec.org/ce-9.2/addons/Amlogic/arm/inputstream.adaptive/inputstream.adaptive-2.4.7.1.zip**

**Comment by Mark4776** [comment]
That's got me sorted, thank you very much. I had no idea where to find it.

**Comment by matthuisman** [comment]
no worries.
FYI: that will be the last IA leia build unless any critical bug fixes

**Comment by Mark4776** [comment]
Cool. Figured it was time for a hardware update so have an Odroid C4 on its way.

**Comment by Gitta78** [comment]
I still have some hope that we will get LibreELEC 10 for Odroid C2, which would then also bring the latest versions of IA. It seems that CoreELEC has dumped C2 now.
