### ISSUE TITLE
$Time$ parameter in mpd manifest is not processed

### ISSUE THREAD

**Issue by cache-sk** [peak3d/inputstream.adaptive#629]
Hi again,

our operator, which hates Kodi, hits with new round..

Mpd manifest now contains segment template with $Time$ parameter:

`<SegmentTemplate initialization="$RepresentationID$/init.m4v" media="$RepresentationID$/seg-0000000000-$Number$.m4v?t=$Time$" timescale="1000"  startNumber="00000000">`

Which ends up in several attempts like this in log, before it gives up:

```
DEBUG <general>: AddOnLog: inputstream.adaptive: AdaptiveStream: trying to reload segment ...
DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Origin: https://....'
DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
DEBUG <general>: CurlFile::Open(0x1f2d3e5a8c0) https://..../seg-00000000-00000000.m4v?t=$Time$
ERROR <general>: CCurlFile::FillBuffer - Failed: Stream error in the HTTP/2 framing layer(92)
ERROR <general>: CCurlFile::Open failed with code 0 for https://..../seg-00000000-00000000.m4v?t=$Time$:
- empty line -
```

Note: i have replaced real numbers with "00000000" for safety :)

**Comment by matthuisman** [comment]
please post the full manifest

also, don't replace the numbers. 
and what is correct first segment, correct second segment... 
you can use dev webtools to find that when playing correctly in browser

it's weird using $Number$ and $Time$.
Do the segments still download if you just put any number instead of $Time$ ?

**Comment by cache-sk** [comment]
I have replaced those numbers just here in comment, not modifying manifest in real usage.

Yes, if i change $Time$ to random number, it will download something (tested in browser during playback in original page), but in network log, that value is changing in browser requests, it is not constant.

I don't want to post manifest publicly (if that provider is checking this, maybe can identify me as client and block my yearly paid account), so i have uploaded it to private repo here on github and invite you to it - hope it's ok.

**Comment by matthuisman** [comment]
Can you post what the URLs it should be are... If you use browser and web tools, you should it request each segment. Post a few of these in order please. They can't identify you from that

**Comment by cache-sk** [comment]
Here is 'log' from start of playback for some time.

```
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-v1/init.m4v
https://same_domain_and_path/tracks-a1/init.m4v
https://same_domain_and_path/tracks-v1/seg-1610309906-1218901.m4v?t=7173381228
https://same_domain_and_path/tracks-a1/seg-1610309906-1218901.m4v?t=7173381228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218902.m4v?t=7173387228
https://same_domain_and_path/tracks-a1/seg-1610309906-1218902.m4v?t=7173387228
https://same_domain_and_path/tracks-a1/seg-1610309906-1218903.m4v?t=7173393228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218903.m4v?t=7173393228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218904.m4v?t=7173399228
https://same_domain_and_path/tracks-a1/seg-1610309906-1218904.m4v?t=7173399228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218905.m4v?t=7173405228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218905.m4v?t=7173405228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218906.m4v?t=7173411228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218906.m4v?t=7173411228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218907.m4v?t=7173417228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218907.m4v?t=7173417228
https://same_domain_and_path/tracks-a1/seg-1610309906-1218908.m4v?t=7173423228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218908.m4v?t=7173423228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218909.m4v?t=7173429228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218909.m4v?t=7173429228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218910.m4v?t=7173435228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218910.m4v?t=7173435228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218911.m4v?t=7173441228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218911.m4v?t=7173441228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218912.m4v?t=7173447228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218912.m4v?t=7173447228
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/Manifest.mpd
https://same_domain_and_path/tracks-a1/seg-1610309906-1218913.m4v?t=7173453228
https://same_domain_and_path/tracks-v1/seg-1610309906-1218913.m4v?t=7173453228
```

**Comment by matthuisman** [comment]
looks like IA does support $Time$
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveStream.cpp#L265
but only when $Number$ isn't used....

so a small update to code should allow both to be replaced

**Comment by matthuisman** [comment]
@cache-sk 
please try a Matrix build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-630/1/artifacts

**Comment by vatlach** [comment]
@matthuisman
Super,works OK at Matrix.

**Comment by cache-sk** [comment]
@matthuisman

Win64 and Android aarch64 works! Good job!

**Comment by cache-sk** [comment]
Thanks. I hope it will be backported to Leia as well.
//edit - Already found pull request for that, thanks.

**Comment by cache-sk** [comment]
Hello again.. Leia branch has this fix merged more than month ago, but was not released as new version.. When will be version bumped to 2.4.8?

**Comment by matthuisman** [comment]
@cache-sk 
In the meantime, you can install a build from here: https://github.com/xbmc/inputstream.adaptive/pull/711

**Comment by cache-sk** [comment]
@matthuisman Thanks for reply, will pass that further. There are still users (not me) preffering Leia and they are .. disappointed.. :)

**Comment by matthuisman** [comment]
Which is fine. They may just need to do a bit of stuff manually that's all. A side effect of staying on older release :)

**Comment by matthuisman** [comment]
@cache-sk 
Can you / your users please try the new builds from here: https://github.com/xbmc/inputstream.adaptive/pull/711
That is what should end up being the next Leia release.

**Comment by cache-sk** [comment]
@matthuisman 
Sorry for late reply. Tested on Win64 - working.

**Comment by matthuisman** [comment]
thank you :)
