### ISSUE TITLE
Black Screen on Widevivene L1 Device (Samsung - Android10)

### ISSUE THREAD

**Issue by Testato** [peak3d/inputstream.adaptive#638]
Audio is ok

tested on Kodi19 by Samsung S8 and Samsung s9+ smartphone on Android10 64bit
using last version of LA7 plugin on IA 2.6.13
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip
(the two Live channel si widevine encrypted, it's not Geoblocked, and is free, not need login)

The Samsung is Widevine L1, I attach the info from DRF Info

On cheeper smartphone L3 device the video and audio stream work regularly

I do not know how check the logfile on android, my phone is not rooted

![image](https://user-images.githubusercontent.com/6893841/114268338-db02bf80-9a00-11eb-9e35-6799e7d8d36f.png)

**Comment by glennguy** [comment]
Hi @Testato 

Looking at the mpd there isn't any L1 content in it (720p max resolution)
If you set inputstream.adaptive settings to manual stream selection, can you get a picture on any of the 4 video streams?

@matthuisman has a lot of experience with L1/blank screens with his add-ons, he may know more.

**Comment by Testato** [comment]
Thanks for your tips, manually choosing the video stream only the best one, 1280x720, is blank.
The other three stream, at lower resolution, work regularly.
Do you think is not L1 certification related ?

**Comment by Testato** [comment]
On my LA7 plugin there is also Ondemand programs, some episodes are widevine protected and some not.
I tested that ondemand stream at 1280x720 not Widevine encrypted work regularly. Only the protected 1280x720 is blank and only on L1 certified device.

On an Android L3 phone, or on Ubuntu PC, or on Windows Pc also the 1280x720 protected stream work regularly.

**Comment by matthuisman** [comment]
I'll try on my Shield (L1) when I get time.

you could try force IA to use the L1 secure decoder...
By adding this code
```
listitem.setProperty("inputstream.adaptive.license_key", lic_url)
listitem.setProperty("inputstream.adaptive.license_flags", "force_secure_decoder")
```
Note: This could break non-L1 devices
If that works, you need to have an add-on setting that allows people to Enable L1 Widevine Device.
Then add that above property if that's true.

I need to do this for Disney+

**Comment by Testato** [comment]
ok, it work.
i tested the "force_secure_decoder" property on ubuntu, that it's not L1 device, and it have no problem, so for now i do not create special setting.

A question, Firestick is L1 device, Nvidia Shield is L1 device, why this two devices do not need "force_secure_decoder" instead Samsung need ?

Thanks a lot for your help, i close this issue

**Comment by Testato** [comment]
sorry I reopened this because i see that by "force_secure_decoder" i have many stuttering about every 5 seconds, on Samsung. 

Some other test:
On Samsung s9+ L1 device without force_secure_decoder the video is blank, with force_secure_decoder we have the video but there is stuttering

On a nokia L1 device it's better without force_secure_decoder than with

On Firestick it work with and without force_secure_decoder

On Dodge L3 device it work with and without force_secure_decoder

**Comment by Testato** [comment]
Probably related to https://github.com/xbmc/inputstream.adaptive/issues/638

It seems that the hw widivine decrypt is active, but it stuttering

**Comment by Testato** [comment]
@glennguy @matthuisman 
- why i need force the secure decoder  on Samsung ? On a Firestick it is not needed. Is IA or Kodi that check if the device have hw widevide decoding possibilities ? Maybe it not check correctly ?

**Comment by glennguy** [comment]
> Is IA or Kodi that check if the device have hw widevide decoding possibilities ?

IA has to tell Kodi if we're using a secure decoder or not. IA will attempt to check 

> Maybe it not check correctly ?

Maybe...

What would be extremely useful, again, is some full debug logs for Firestick and Samsung. There are a lot of things logged by IA which may give some pretty good clues about the problem.

**Comment by kszaq** [comment]
I'm observing the same issue on a Huawei device with L1 - unfortunately for some reason Kodi does not save debug info in the log even with debugging turned on.

It looks to me that on (some) L1 devices Widevine cannot pass decrypted data to non-secure decoder. A possible workaround would be to provide an option in IA to always force secure decoder.

Edit: Debug log with debugging enabled (overlay shown on the screen) looks like this: [kodi.log](https://github.com/xbmc/inputstream.adaptive/files/6377605/kodi.log)

**Comment by matthuisman** [comment]
pretty sure IA can detect the Widevine level.
Any harm in forcing secure decoder for all L1 devices?

https://github.com/xbmc/inputstream.adaptive/blob/Matrix/wvdecrypter/wvdecrypter_android_jni.cpp#L588

Oh, does it meant to already be doing that here:
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/wvdecrypter/wvdecrypter_android_jni.cpp#L482
Oh - is that doing it if the media needs L1

**Comment by kszaq** [comment]
It looks like these 3 lines are responsible for switching to non-secure decoder for streams that don't require it:
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/main.cpp#L2490-L2492

Correct me if I'm wrong:
- Removing these lines will result in always using secure decoder on L1 devices as they return `SSD_SECURE_DECODER` in caps: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/wvdecrypter/wvdecrypter_android_jni.cpp#L475-L488
- On non-Android devices caps are evaluated per-stream so current behaviour would stay: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/wvdecrypter/wvdecrypter.cpp#L496-L569

I can check this on Linux and Android devices later today.

**Comment by glennguy** [comment]
@matthuisman did you mention a while ago that HBO or some other provider was using ~~a custom JS function~~ Java code in their Android app to modify their mpds to add `robustness_level`?

I'm just wondering how it must work on providers' official apps. Maybe [this](https://developer.android.com/reference/android/media/MediaDrm#requiresSecureDecoder(java.lang.String)) will help us in the future

**Comment by Testato** [comment]
this is my log on Samsung S9+

without force secure decode by La7 plugin I have only audio, video is blank
with force secure decode the video is present but with stuttering artifact

This logfile is with forced secure decode
https://paste.kodi.tv/ibilatezad.kodi

@kszaq you also have blank viedo and good audio ?
May you try my LA7 plugin where I forced the secure widevine decode ?
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by kszaq** [comment]
@Testato On a Linux device I have video and audio working with HW decoder, Widevine is used only to decrypt.

On Android device I have no video and no audio unless secure decoder is forced.

I have pushed another PR that might fix this, please check https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-662/1/artifacts in a few minutes for an Android build. It would be great if you can test on L1 and L3 device, I only have L1 device.

Edit: #662 fixes the issue on my Android L1 device and does not break a LibreELEC device - meaning that stream with non-secure decoder and secure decoder work correctly, nothing is broken.

**Comment by Testato** [comment]
This logfile is without force secure decode by plugin (so Blank video)
https://paste.kodi.tv/gozolevobi.kodi

**Comment by Testato** [comment]
@kszaq 
I tested your version on L1 device and it work, but with stuttering.

So i think that this is two different problem:
1) the blank screen problem will be solved by the kszaq PR, so the plugin developer not need to manually force the secure decoder
2) the stuttering pixellating problem that appear on some L1 device when use secure decoder is a different problem

**Comment by Testato** [comment]
This logfile is with kszaq PR (so on S9+ L1 means audio and video present, but with stuttering
https://paste.kodi.tv/umicipuyay.kodi

I bet that this second problem is the same of https://github.com/xbmc/inputstream.adaptive/issues/582 and https://github.com/xbmc/inputstream.adaptive/issues/581

**Comment by glennguy** [comment]
@Testato

I'm just noting that in the log your screen refresh rate is 60hz and the content is 25fps - can you have a play with the settings -> player -> video -> sync playback to display.
Also in the same page have a look at the 'processing' section, as the video is 720p Kodi may be set to try and upscale it to your 1440p display.

**Comment by Testato** [comment]
> I'm just noting that in the log your screen refresh rate is 60hz and the content is 25fps - can you have a play with the settings -> player -> video -> sync playback to display.

No difference

> Also in the same page have a look at the 'processing' section, as the video is 720p Kodi may be set to try and upscale it to your 1440p display.

I tried 100% that means HQ scaler disabled, and 0% that means HQ scaler always active, but without difference
