### ISSUE TITLE
Unsupported stream hls 

### ISSUE THREAD

**Issue by DarkAnakin** [peak3d/inputstream.adaptive#64]
Hi, when I use inpustream addon to open some url, I get "OpenStream - Unsupported stream 1. Stream disabled".
 I can open those url when I send it directly to kodi but it take severals seconds to launch while with inpustream addon it is a lot faster.
 So I tried to found out where is the issue but hasn't made much progress.

The streams are protected so there is no easy way to share it.
You can find the donwloaded stream with the key below.

If you need me to make other tests, make me know.

[stream.zip](https://github.com/peak3d/inputstream.adaptive/files/1285922/stream.zip)

**Comment by peak3d** [comment]
In the current implementation only multi-bitrate playlists are supported / expected.
Single playlists should load / play in a compareable speed with ffmpeg (never tried, just a guess)

Its not too much work to get single playlists working, will look at it when the current development step is finished (maybe you have to remember me here again in in a week or so)

**Comment by DarkAnakin** [comment]
The playlist is a multi-bitrate one but I put only the "sub" that I edit to match with the stream and the key requested by inputstream addon. 
Here 2 logs which show what happen.

[logs.zip](https://github.com/peak3d/inputstream.adaptive/files/1287609/logs.zip)

**Comment by peak3d** [comment]
Without the master m3u8 I'm unable to continue.
Can I access the file using a vpn proxy? what country if so?

**Comment by DarkAnakin** [comment]
I have send you an email on the address from your profile.

**Comment by DarkAnakin** [comment]
The issue seems that [ CInputStreamAddon::GetStream(int)](https://github.com/xbmc/xbmc/blob/922a6bb1959befa982f8c37ea3336b018ffe12db/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp#L315) is not called after the stream infos changed.
That make [CVideoPlayerVideo::OpenStream ](https://github.com/xbmc/xbmc/blob/922a6bb1959befa982f8c37ea3336b018ffe12db/xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp#L120)failed because of  hint.extrasize=0.
So what conditions make CInputStreamAddon::GetStream(int) to be called to update the infos because I can found it after hours of search?
