### ISSUE TITLE
Merge Kodi18 IA new version to Kodi-old PPA

### ISSUE THREAD

**Issue by Testato** [peak3d/inputstream.adaptive#642]
do you know that many plugin are not updated for Kodi19, so many people will remain on Kodi18 for some time.
the actual version of IA 2.6.13 solved many problem on many livestream (BBC, LA7, etc)
Will this version be pushed to Kodi18 ?

**Comment by matthuisman** [comment]
Leia 2.4.7 is released and should fix most issues

**Comment by dagwieers** [comment]
Thank you, @glennguy, @matthuisman and @phunkyfish !

**Comment by matthuisman** [comment]
@Testato please close this issue

**Comment by Testato** [comment]
I will test if the update is arrived on Windows, Ubuntu and Android and after i will close it

**Comment by Testato** [comment]
On Ubuntu it's not arrived:

```
ubuntuk@ubuntuk:~$ sudo apt update
All packages are up to date.

ubuntuk@ubuntuk:~$ apt-cache policy kodi-inputstream-adaptive
kodi-inputstream-adaptive:
  Installed: (none)
  Candidate: 2.4.6-1~focal
  Version table:
     2.4.6-1~focal 500
        500 http://ppa.launchpad.net/team-xbmc/kodi-old/ubuntu focal/main amd64 Packages
```

**Comment by matthuisman** [comment]
Oh. It won't go to Ubuntu ppa as that's now moved to kodi 19. 

I'll ask to see if it possible to go into kodi-old ppa

**Comment by CrAcK75** [comment]
the fix did not last long... another issue there is on La7... today, after a few seconds, the playback stop.. into the log there are these errors:
```
ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
ERROR <general>: AddOnLog: inputstream.adaptive: Download https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/Live_1280x720-2385540000.mp4 failed with error: 404
ERROR <general>: AddOnLog: inputstream.adaptive: Download https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/Live_Audio-1168916480.mp4 failed with error: 404
```

**Comment by matthuisman** [comment]
@CrAcK75 
https://github.com/xbmc/inputstream.adaptive/issues/615#issuecomment-818234029

**Comment by CrAcK75** [comment]
> @CrAcK75
> [#615 (comment)](https://github.com/xbmc/inputstream.adaptive/issues/615#issuecomment-818234029)

Thank you

**Comment by Testato** [comment]
Closed as "Ubuntu Teams won't fix" ?

**Comment by phunkyfish** [comment]
Closed as the kodi Ubuntu setup only supports latest stable.

**Comment by Testato** [comment]
And this behaviour is an Ubuntu or a Kodi choise ?

**Comment by phunkyfish** [comment]
It’s the kodi build system for our PPA. It’s only supports current stable and latest.

**Comment by matthuisman** [comment]
@Testato  @anyone_else

I've built a Leia version (current head) for Linux x86_64 as it won't be going into PPA old
https://f.mjh.nz/ia/6742307-linux-x86_64.zip

**Comment by Testato** [comment]
Thanks.
Will this link remains active forever ?

**Comment by matthuisman** [comment]
Until I accidentally delete it. Mirror it yourself to be safe :)

**Comment by Testato** [comment]
Mirrored here :-)
[6742307-linux-x86_64.zip](https://github.com/xbmc/inputstream.adaptive/files/6583867/6742307-linux-x86_64.zip)

on the addon.xml the version is 2.4.7, it is correct ?

**Comment by matthuisman** [comment]
Its the latest commit of Leia repo. 2.4.7 + that other fix
