### ISSUE TITLE
Kodi crashes on DRM protected content

### ISSUE THREAD

**Issue by filigranen** [peak3d/inputstream.adaptive#644]
I originally posted this on the discoveryplus addon issue tracker, but it appears to be related to DRM and widevine, so I'll try reporting it here.

See this issue for original discussion: https://github.com/Dis90/plugin.video.discoveryplus/issues/42

As can be seen there, it crashes on both kodi 18.9 and 19, on Linux, Windows and Android. And only on DRM protected content.

I am trying to watch The Big Bang Theory on Discovery+ using the above addon, and kodi crashes when decoding DRM content. Episode 4 is not protected, episode 5 is.

The files attached are these:

Kodi 18.9 on Linux:

Working log (episode 4): https://paste.kodi.tv/wapuzedaza.kodi
Crashing log (episode 5): https://paste.kodi.tv/urebasedag.kodi
Kodi's own crashlog/debuglog: https://paste.kodi.tv/gidezuqepa.kodi

Kodi 19 on Win 10 64 bit: https://paste.kodi.tv/hukopuyogo.kodi

manifest.mpd from episode that crashes Kodi but works in Chrome: https://paste.kodi.tv/ebejadigad

and Dis90's manifest from finnish discovery+, not TBBT though: https://paste.kodi.tv/udufabiqic 

As Dis90 points out, there is an error in the logs:
```
InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: C53A9877F32C40A3B663C35CDA0AC26A
```

Any ideas on how to solve this?

Like I also say in that issue, the viaplay addon (https://github.com/emilsvennesson/kodi-viaplay) does work, and those are also using inputstream.adaptive and widevine.

Please, point me in the right direction, and if you need me to provide any more logs or files of any kind, let me know!

**Comment by matthuisman** [comment]
Looking at the crash-log - seems the crash may be happening in https://github.com/xbmc/inputstream.adaptive/blob/58c54c7b641f69a862ed2fa5a640b5fa2db9c711/src/common/AdaptiveStream.cpp#L265

think I see the issue
```
  <AdaptationSet group="2" mimeType="text/vtt" contentType="text" lang="sv">
   <SegmentTemplate timescale="90000" media="$RepresentationID$-0?version_hash=93615d8e" presentationTimeOffset="0">
```

**media="$RepresentationID$-0?version_hash=93615d8e"**

I get a segfault when trying the ReplacePlacehoder function with that url.
This is because that function assumes it either has a $Number$ or $Time$
The above url has neither - so you get a segfault when it tries to do the url.replace
```
terminate called after throwing an instance of 'std::out_of_range'                                                                                                                 
  what():  basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 42)                                                                               
Aborted (core dumped)
```

This makes sense as in your log - you can see it get the 1st segment for video and audio and then the crash as it tries for the subtitle

easy fix! ill get you a version to try shortly..

actually, my existing PR https://github.com/xbmc/inputstream.adaptive/pull/630 should have it already fixed as it checks for no matches. What a funny coincidence!

**Comment by matthuisman** [comment]
think I see the fault!!

```
  <AdaptationSet group="2" mimeType="text/vtt" contentType="text" lang="sv">
   <SegmentTemplate timescale="90000" media="$RepresentationID$-0?version_hash=93615d8e" presentationTimeOffset="0">
    <SegmentTimeline>
     <S d="98442000" t="0"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/>
   <Representation id="1112635959" bandwidth="100">
    <BaseURL>1112635959-0.vtt?version_hash=93615d8e</BaseURL>
   </Representation>
  </AdaptationSet>
```

media="$RepresentationID$-0?version_hash=93615d8e"

Notice it has no $Time$
I get a segfault when trying the ReplacePlacehoder
This is because that code assumes it either has a $Time$ or $Number$
There is no check and i get 

```
terminate called after throwing an instance of 'std::out_of_range'                                                                                                                 
  what():  basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 42)                                                                               
Aborted (core dumped)
```

**Comment by matthuisman** [comment]
easy fix! ill get you a version to try shortly

**Comment by matthuisman** [comment]
@filigranen 
please try this build on Windows Matrix:
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-630/3/artifact/cmake/addons/build/zips/inputstream.adaptive+windows-x86_64/inputstream.adaptive-2.6.13.zip

**Comment by filigranen** [comment]
Seems to work! Here's a log with it working, just for completeness: https://paste.kodi.tv/otamabagoq.kodi

Will there be a version for Leia? I have not updated to Matrix yet due to most addons breaking.

**Comment by matthuisman** [comment]
thats great!

Usually Leia wouldn't get any more releases.
However, as this actually causes segfault and crashes Kodi - I have asked if we could backport my PR

**Comment by filigranen** [comment]
Great!
I will apply it here locally in the meantime.
Thanks for the quick fix!

**Comment by matthuisman** [comment]
thank you for the good bug report etc.
This is one of those bugs that could be causing lots of crashes all over the place without ever being found out what the cause is.

**Comment by filigranen** [comment]
Yeah, nasty ones. Had I not tried to watch this it probably wouldn't have made it into the Leia branch, even though you already solved the issue beforehand.

Speaking of Leia, I can confirm it works on there as well, on Linux at least (cannot build on Windows).
Just copied your two changed files and rebuilt the package, no crash now.
So should be a simple backport I suppose. Will use my own package until then. :-)
