### ISSUE TITLE
Widewine multithread

### ISSUE THREAD

**Issue by pipapapipipapa** [peak3d/inputstream.adaptive#646]
Hi all,

I am using Kodi 19 on ARM-based Linux device, LibreELEC. I noticed that when playing DRM 4K stream it can't keep up with decoder. 

It goes like this: buffering - playing 10-15 seconds smoothly - buffering again.
- CPU is at performance governor
- video is 15Mbps H.265
- the video is HW-decoded, so it's not an issue with decoder
- when the video is paused, I can see one CPU core with 100% usage by VideoPlayer thread
- it's not an issue with internet bandwidth, downloading mp4 segment with curl goes >50Mpbs, video plays fine on other device (not Kodi)

I guessed this is because the stream is decrypted on single core by Widevine. My question: is there any way to make Widevine work multithreaded or at least in a separate thread from curl/VideoPlayer?

**Comment by glennguy** [comment]
>I guessed this is because the stream is decrypted on single core by Widevine

I believe that's correct. We are at the mercy of the widevine decrypter's capabilities, see #81 

Maybe testing in a browser on a non-Android platform would confirm that we're restricted to a single core.

**Comment by pipapapipipapa** [comment]
Thank you @glennguy! I didn't notice the previous submission. 

Are the streams decrypted during download or only when they are played? The download is fast but the buffer fills slowly, does this confirm that decryption is done as soon as the segment is downloaded?

**Comment by glennguy** [comment]
Kodi asks for the demux packets from IA in order to keep its internal buffer (8 seconds) full. The segment download is triggered by Kodi asking for more packets. So to answer: kind of yes :)
