### ISSUE TITLE
Add support for suggestedPresentationDelay

### ISSUE THREAD

**Issue by Testato** [peak3d/inputstream.adaptive#647]
_Originally posted by @matthuisman in https://github.com/xbmc/inputstream.adaptive/issues/615#issuecomment-818234029_

> For a start - I see it's using SegmentTemplate now... so you'll need to set manifest_update_param to "full" so it refreshes the MPD
> 
> ```
> if live:
>     #listitem.setLabel(titolo_diretta)
>     listitem.setInfo('video', {'plot': titolo_diretta, 'title': titolo_diretta})
>     listitem.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')
> ```
> 
> i actually have a PR to automatically do this I made last night: https://github.com/xbmc/inputstream.adaptive/pull/645
> 
> Even with the above - it seems to pause with a lot of "Begin WaitForSegment stream 1" so maybe another issue needs looked into
> 
> **Probably best to open a new issue after you have set the above update_parameter.**

**Comment by Testato** [comment]
I tried your tips, yes it is better but sometimes it not work
This is the version of the plugin with 'full' set
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by matthuisman** [comment]
We need full debug log showing when it's not working
and confirmation that it's not just their stream playing up

Also, my above code should also work in Kodi 18
inputstream.adaptive.manifest_update_parameter has been available for long time :)

**Comment by Testato** [comment]
Ok i will.release also a kodi18 version.
Tomorrow i made extensive test.
Thanks

**Comment by Testato** [comment]
I opened the stream at the same time on Chrome and on Kodi, i leave the two togheter opened on Ubuntu.
The problem is no present on the Browser stream.
On Kodi i noticed that often the problem is only at the beginning, if you see the blu bar you see that it go to the end, the little gray buffer reach the end and you receive 
`2021-04-14 14:38:37.003 T:5195     INFO <general>: CVideoPlayerAudio::Process - stream stalled`
after 2 or 3 seconds the blue bar jump a little to the left and the cicle restart.

Sometimes instead the video go blank and in the log appear
`2021-04-14 14:38:49.016 T:5193  WARNING <general>: OutputPicture - timeout waiting for buffer`

Also sometimes there is 
`2021-04-14 14:41:38.171 T:5358    ERROR <general>: CCurlFile::Open failed with code 404 for https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/:
`
https://paste.kodi.tv/qefibeqese.kodi


Maybe it is possible increase some Buffer memory ? Or kodi can ask the .mpd and relative .mp4 in advance ?

**Comment by glennguy** [comment]
I've had a look and found that the manifest isn't refreshing how you would expect.

I made a short python script to download the mpd and print the `t` value in the video SegmentTimeline, looping 10 times with a 3.9 second delay (so roughly 4s loop time, same as duration of a segment).
Here's the values over a ~40 second window:
```
22504320000
22504320000
22504320000
22504320000
22504320000
22504320000
22504320000
22507200000
22507200000
22507200000
```

You'd expect the value to increase 360000 on average for each line. 

I checked over a longer period of time and saw that the mpd is updated around every 30 seconds. You can see this on playback where the 'now' time on the OSD will jump back ~30 seconds every ~30 seconds, whereas on other streams it will usually happen every time a new segment is loaded (IA refreshed mpd every segment). 
Maybe they're trying to save resources on the backend with this by bringing in new segments a small batch at a time? If you get lucky and start a stream just before the mpd content is updated on the backend then you may not have an issue streaming at the live edge, but of course this is still no good for us.

Of note is the `suggestedPresentationDelay="PT32S"` in the `MPD` tag. 

DASH-IF guidlines suggest that we **should** observe this and adjust the effective end of the timeshift window backwards from now by this amount.

If we want to go down this path we would need to find a way to safely remove the last 32s worth of segments from the list of segments. Off the top of my head would be an edge case scenario where we're playing right on the live edge and remove that segment. The video timeline would be easy - just remove 8 from S@r in SegmentTimeline:
```
<SegmentTimeline>
  <S t="22389480000" d="360000" r="59"/>
</SegmentTimeline>
```
Won't work with the audio SementTimeline eg.:
```
<S t="10970847232" d="176128"/>
<S t="10971023360" d="177152"/>
<S t="10971200512" d="176128" r="2"/>
<S t="10971728896" d="177152"/>
<S t="10971906048" d="176128" r="2"/>
<S t="10972434432" d="177152"/>
<S t="10972611584" d="176128" r="1"/>
...
```

**Comment by matthuisman** [comment]
pretty sure IA when sees "r" = 59 literally inserts 59x that segment into the array.
for the audio timeline, when no "r" it means just r="1".
Again, they would all be in the array.

So could be as easy as just removing 8x segments from the end of the array.
Or telling IA to start from 8x segments "back"

Or even easier, just minus 32s from our current clock time?

When we implement the above we should look into making IA only refresh manifest when it gets to it's last or 2nd to last segment.  Instead of refreshing after every segment. Or maybe already does this?
Also, if you rewind - it would stop it refreshing the manifest until it needs the latest segments

**Comment by glennguy** [comment]
>When we implement the above we should look into making IA only refresh manifest when it gets to it's last or 2nd to last segment. Instead of refreshing after every segment. Or maybe already does this?
Also, if you rewind - it would stop it refreshing the manifest until it needs the latest segments

We should be guided by the `minimumUpdatePeriod` attribute. It's possible that BaseURL or other things could change - not for most situations but consider for example if you have a 2 hour timeshift buffer and play from the start there is a lot of chance for a change to happen...

>Or telling IA to start from 8x segments "back"

Definitely an option. AdaptiveStream will always try to start ~12 seconds from the live edge, maybe we could consider having it take a presentation delay into account if available. Still won't stop issues if a user then ff to live edge.

>just minus 32s from our current clock time?

Won't work in this case. Wall clock isn't used in the segment url calculations, just S@t + S@d<sub>r1</sub> + S@d<sub>r2</sub> ...

So maybe the proper solution is to just rip SPD worth of segs from the representation? As long as the algorithm works consistently esp. in the case of uneven segment lengths (audio), don't want to accidentally delete the segment we're playing.

**Comment by Testato** [comment]
on Kodi the MPD is refreshed every 30sec, but on Chrome, if you see by inspection tool, it refresh every 4sec

**Comment by matthuisman** [comment]
curious - if you rewind the live stream 30 secs - does that make it playback better?

**Comment by Testato** [comment]
you mean via Chrome browser ? There is no rewind button, you can only pause and play.
Look yourself
https://www.la7.it/dirette-tv

**Comment by matthuisman** [comment]
no in Kodi.

**Comment by Testato** [comment]
Yes.
If i start the stream on Kodi and immediately rewind on the blu bar, it ask the new .mpd and from now on the blue bar never touch the end, kodi continue to ask the .mpd 30sec in advance.
I think you are found a solution, we will have 30sec delay, but for a stream it can be good, because also the stream from browser is not in sinc with the Air Broadcast

**Comment by matthuisman** [comment]
well, according to the manifest - it's meant to be behind by 32secs...?
Glenn said IA already starts 12 secs behind head.. so we need to start 20 more secs back.
I assume the web stream at present is about 20secs behind Kodi?

If so, you should be able to set ResumeTime on the list item to start 20secs behind head.
If the buffertime is 5mins, you would set ResumeTime to 280 (5x60 - 20)
as resumeTime can't be a negative offset from head. it has to be from the start of the stream

**Comment by Testato** [comment]
yes, Kodi is 20secs in advance on web stream

**Comment by matthuisman** [comment]
@Testato
```
listitem.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')
listitem.setProperty('ResumeTime', '206')
listitem.setProperty('TotalTime', '240')
```
is a temporary fix for now until IA supports suggestedPresentationDelay

Also, if you add ".pvr" to the end of the list item path, it won't try to do the resume stuff for live channels.
eg:
```
   addDirectoryItem_nodup({"mode": "diretta_la7"},liStyle, folder=False, is_live=True)
    ~~
   addDirectoryItem_nodup({"mode": "diretta_la7d"},liStyle, folder=False, is_live=True)


def addDirectoryItem_nodup(parameters, li, title=titolo_global, folder=True, is_live=False):
         ~~
        url = sys.argv[0] + '?' + urllib.urlencode(parameters, 'utf-8') 
        if is_live: url += '&_l=.pvr'
```

Now can you please clean up your 3x open issues
Close blackscreen - that was fixed with force L1. please close.
Old-ppa - looks like that won't happen. please close.
and this PR - could you rename to something like "Add support for suggestedPresentationDelay"

**Comment by matthuisman** [comment]
@glennguy 
> We should be guided by the minimumUpdatePeriod attribute. It's possible that BaseURL or other things could change - not for most situations but consider for example if you have a 2 hour timeshift buffer and play from the start there is a lot of chance for a change to happen...

95% confident IA doesn't update the baseurl etc when refreshing the manifest.
I found this out when I noticed my proxy didn't need to re-write the the refreshed manifest.
I think IA just uses it to grab the latest segmenttimeline and that's it.

What I was meaning is that if we rewind 2 hours and have a segmenttimeline that goes all the way to current time - we shouldn't keep refreshing after every segment. We should just refresh once our number of segments left is a certain number.

**Comment by matthuisman** [comment]
OK, first PR here:
https://github.com/xbmc/inputstream.adaptive/pull/658

@Testato
Please try this build and see if works for you with your plugin:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-658/3/artifacts

Remember to test it **without** my above "ResumeTime" work-around.

**Comment by Testato** [comment]
Yep, now the blu bar never touch the end.
Sometimes when you start the stream it play the video and immediately go back of 30sec, so you see two times the same little frames. But you must try several times. 
For me it is solved, if it is ok also for you you can close this issue

For the Blank screen on L1 device it is true that now on Samsung it is not blank, but it have many stuttering, It is unusable. Do you want close it ?

For the Kodi-old ppa the problem is present, if you want can close it with "Unwanted Fix" notice, or "Ubuntu repo related" notice, but it is correct that you close it not me imho

thanks for your tips on the .pvr

**Comment by glennguy** [comment]
I think I figured out what LA7 must be doing.

They're using cloudfront as cdn for the mpd/segments. The first time you access the mpd you will get an up to date mpd. Then for the next 30 seconds the mpd refreshed get a cache hit from cloudfront and return the same mpd. You can verify this by opening stream on LA7 website in two separate browsers (e.g firefox and chrome) concurrently and as long as they are started slightly offset from eachother they will always have different `t` values in segmentTimeline. Their workaround to make sure the player doesn't get stuck waiting for new segments to appear in the mpd is to use suggestedPresentationDelay.

**Comment by Testato** [comment]
And it is a correct standarzied use of SPD or an hack ?

**Comment by glennguy** [comment]
SPD is meant for cases where *segments* may not yet be available for download.
As explained above, these segments are indeed available and the mpd is being updated for each segment on server side. It's cloudfront's caching that is preventing us from seeing a new mpd after each 4s segment.
Draw your own conclusion if you wish but in my view SPD was not created for this concept. SPD is for where you have an encoder which may lag behind, or lag somewhere else in the pipeline which is intermittent in nature and prevents a guarantee that the segments will be published on time.

**Comment by Testato** [comment]
Ok i understand, but also on browser this mechanism is present (i mean also chrome receive the cached mpd) but it not have problem during play

**Comment by glennguy** [comment]
Browser player for LA7 does not offer ability to seek/FF/RW, only play and pause. Their solution is quite simple - start the stream at least `suggestedPresentationDelay` away from the edge. Problem solved.
Because IA allows seeking through the time shift window our situation becomes much more complex.

**Comment by matthuisman** [comment]
@Testato 
Did you open an issue for the Android stuttering?
I wonder if it does it if you go into Inputstream Adaptive Settings and set Media to "Video"
You won't get Audio - but interested to see if that fixes it

I have seen with HBO Max, EC3 (dolby digital+) audio causes the video to stutter etc
which made me think, maybe there is an issue decoding some audio streams with secure decoder

**Comment by matthuisman** [comment]
@Testato 
could you please test with:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-761/1/artifacts

**Comment by matthuisman** [comment]
@Testato 
please try:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-761/13/artifacts

**Comment by Testato** [comment]
@matthuisman 
Yes it's ok.
But i tried to reproduce the old problem (by removing resumetime/totaltime prom my plugin) and also the stream work regularly, so probably LA7 channel change someting on it's side. 
For this reason my test is not valuable
