### ISSUE TITLE
Audio Stream doesn't change in Live channels with multiple languages

### ISSUE THREAD

**Issue by nikhilk0** [peak3d/inputstream.adaptive#648]
While watching live channels with multiple language audio streams in Discovery+ addon, when toggling audio from one language to another (e.g. English to regional language), instead to switching to that language the audio stops playing and there is no audio.
Current workaround is to toggle the audio stream to your language preference, stop the stream and play it the stream again as kodi remembers your last audio stream.
This issue is only present with live channels. Discovery+ episodes with multiple language audio play fine.
I have mentioned it on discovery+'s repo, but the issue seems to be with ISA.

Tell me if this is legit issue and if you want any debug logs for reference. Thanks

**Comment by matthuisman** [comment]
@glennguy I wonder if this is also fixed with
https://github.com/xbmc/inputstream.adaptive/pull/685

**Comment by nikhilk0** [comment]
Unfortunately, the issue is still there even after this PR.

**Comment by nikhilk0** [comment]
@glennguy @matthuisman I tried again with [this](https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/view/change-requests/job/PR-685/lastSuccessfulBuild/artifact/cmake/addons/build/zips/inputstream.adaptive+windows-x86_64/inputstream.adaptive-2.6.15.zip) build and the audio stream does change. But there is a slight issue.  When I start playing the stream, the video is hung and audio takes 5-10 secs to start playing with video still hung. The video doesn't start playing until I switch the audio to another language.

**Comment by nikhilk0** [comment]
Okay. The latest build of https://github.com/xbmc/inputstream.adaptive/pull/685 has fixed the issue. Thanks for the excellent work @glennguy.

**Comment by glennguy** [comment]
@nikhilk0 my pleasure, thank you so much for testing and reporting back!
