### ISSUE TITLE
How does inputstream adaptive select the starting point in hls playlist

### ISSUE THREAD

**Issue by chamchenko** [peak3d/inputstream.adaptive#664]
Hi,
I'm working on fixing the [nba leaguepass addon](https://github.com/chamchenko/xbmc.plugin.video.nba/tree/dev) 
And I'm encountering an issue with playback.
So in this plugin when selecting a live game user has a choice between "go live" and "start from the beginning"
NBA used to have a time stamped manifest that they return if  a start time and a duration are provided to the api this option does not work any more.
but looking at the playlist that it returns it contains all the segment of the full stream from the beginning of the game so in theory it should be possible to select where the player should start playing

now I will explain what is happening  with inputstream adaptive in this add-on:
by default it starts playing at the end of the playlist.
But for games that starts before midnight GMT
 - it starts at the end if time is before midnight
 - it starts at the beginning if time is after midnight
i did further investigation and the only difference that I see in the playlist is that after midnight there is this block that appears

`#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2021-04-30T00:00:01.059Z
#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,AAAASHBzc2gBAAAA7e+LqXnWSs6jyCfc1R0h7QAAAAECPcxv9t0I0qFBI/WzJ/e2AAAAFAgBEhACPcxv9t0I0qFBI/WzJ/e2",KEYID=0x023DCC6FF6DD08D2A14123F5B327F7B6,KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1"
#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,KEYFORMAT="com.microsoft.playready",KEYFORMATVERSIONS="1",URI="data:text/plain;charset=UTF-16;base64`

So my questions is: does those tag influence the playing start point in inputstream adaptive
Is there any way to force inputstream adaptive to start at the beginning or at the end of the playlist 

[Master playlist](https://paste.kodi.tv/zipegeqoba)
[Video playlist](https://paste.kodi.tv/kokaxugexa)
[Audio playlist](https://paste.kodi.tv/zipegeqoba)

**Comment by glennguy** [comment]
Yes unfortunately it's a hard one to fix.

#EXT-X-DISCONTINUITY tags will divide the playlist into Kodi 'chapters' - you should see the white dot on the OSD timeline (Kodi 19+). There's no way within IA to tell Kodi to start from anything other than chapter 1. In your case it should start roughly 12 seconds before midnight if this tag is placed at midnight i.e the end of chapter 1.

A workaround is to provide a resume time in your addon, then Kodi will seek to the point you want. See here: https://github.com/xbmc/inputstream.adaptive/issues/647#issuecomment-825203536

**Comment by chamchenko** [comment]
Hi @glennguy 
So if understood you. as a work around I should download the playlist myself and estimated the elapsed time using the
segment_duration * number_of_segment as a ResumeTime in order to go live
and use a low value say 1 or 2 as a ResumeTime in order to start from the beginning

I just tested that and playback start at the wanted point, but funny fact I only have video and no audio.
In the log I only see
AddOnLog: inputstream.adaptive: Download for video segment and playlist
the only references for audio is seen once with
`AddOnLog: inputstream.adaptive: Download https://lion-nba-msl.akamaized.net/cmaf/live/2022986/nlds/nba/akmsl/drm/cmaf/wvpr/phi/as/live/nlncp/0022000949-b/br_3000_audio/br_3000_long_fmp4Audio.m3u8 finished
AddOnLog: inputstream.adaptive: Download https://lion-nba-msl.akamaized.net/cmaf/live/2022986/nlds/nba/akmsl/drm/cmaf/wvpr/phi/as/live/nlncp/0022000949-b/br_3000_audio/br_3000_audio-init.mp4 finished, avg speed: 908435.20byte/s, current speed: 30152.00byte/s
the hls playlist of audio and audio-init segment then no audio as if it's disabled
Finding audio codec for: 86018
CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
Creating audio thread
CDVDAudio::Pause - pausing audio stream
CDVDAudio::Resume - resume audio stream`

[Full Log](https://paste.kodi.tv/ketafaqepo.kodi)

**Comment by glennguy** [comment]
This - `AddOnLog: inputstream.adaptive: Begin WaitForSegment stream` indicates that the stream (audio) is waiting for new segments to be placed in the manifest, but interestingly there's no refreshes for the audio m3u8... Maybe you're seeking too far? Try a few minutes earlier and see if that fixes.

**Comment by chamchenko** [comment]
Unfortunately that does not help. 
I don't think that I'm seeking to far as in the progress bar I can  see the remaining time to the end

**Comment by glennguy** [comment]
@chamchenko closing this, I think you're all over it now  :)
