### ISSUE TITLE
6Play via plugin CatchUp TV & More KO

### ISSUE THREAD

**Issue by osmoze06** [peak3d/inputstream.adaptive#672]
Bonjour,

Un problème de DRM empêche le lancement des émissions en Replay du groupe 6Play via le plugin CatchUp TV ans More.

Le version utilisé est Kodi 19.0 Matrix.

Voici le lien vers le ticket avec des logs disponibles :
[Github Issues](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/510) 

Merci pour votre aide,

**Comment by matthuisman** [comment]
English only please on this repo
And also please provide a full debug log and a good description of the issue
And also a copy of the .mpd file it's trying to play

Ok, found a log on your other issue:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6423010/kodi.log

Seems to be a URL calculation issue...

We will need a copy of the https://lbcdn.6cloud.fr/resource/m6web/s/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/static/chromecast_drm_540p_dash_v1.mpd  file to see why it's failing.
This url requires a token - so you will need to download it once you get the latest url from your log.
Please dowload it, paste it somewhere and reply with a link,

**Comment by Arias800** [comment]
Hello,
I retrieve the manifest from the website. I have put the file in an archive to be able to post it on Github directly.
[web_drm_540p_dash_v1.zip](https://github.com/xbmc/inputstream.adaptive/files/6439876/web_drm_540p_dash_v1.zip)

**Comment by matthuisman** [comment]
thanks.

`Download https://lbcdn.6cloud.fr/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2099976.dash failed with error: 404`

So, mpd path is:
`https://lbcdn.6cloud.fr/resource/m6web/s/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/static/chromecast_drm_540p_dash_v1.mpd`

`initialization="/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-$RepresentationID$.dash"`

there is no baseurl, so mpd path is used as baseurl
therefore, `https://lbcdn.6cloud.fr/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2099976.dash`  

seems correct URL to me....
Can you use chromewebtools to see what URL it should be calling...?
Maybe you need to set some cookie or headers that it's looking for?

**Comment by Arias800** [comment]
The mdp path in Chrome is :
```https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/static/web_drm_540p_dash_v1.mpd```

And the url is this :
```https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2100146-10800.dash```

In the headers I have this:
```
:authority: 6play.vod.6cloud.fr
:method: GET
:path: /m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2100146-1800.dash
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
cache-control: no-cache
origin: https://www.6play.fr
pragma: no-cache
referer: https://www.6play.fr/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
```

**Comment by matthuisman** [comment]
that doesn't line up with the mpd you sent me..
Can you upload: https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/static/web_drm_540p_dash_v1.mpd
oh, that downloads for me, nevermind

right, thats using
`media="/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-$RepresentationID$-$Time$.dash`

which would make:
`https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2100146-10800.dash`

which is correct...
have you tried playing: https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/static/web_drm_540p_dash_v1.mpd in Inputstream Adaptive?

**Comment by Arias800** [comment]
Yes, the first one was retrieved with firefox and the rest with Chrome.
Sorry for the mistake.

**Comment by matthuisman** [comment]
have you tried playing: https://6play.vod.6cloud.fr/m6web/output/a/8/4/a849b85662154efd99714945bc05e2a8db4b1b22743d49a09b72171c53e13dcb/static/web_drm_540p_dash_v1.mpd in Inputstream Adaptive?

seems the paths in that are correct and should be calculated correctly

**Comment by matthuisman** [comment]
also
https://6play.vod.6cloud.fr/m6/output/9/7/c/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1.ism/dash/97c44d46e2042a9b00d541a87609ea89ec412bb0d4a4c67ff7a7bc4c5b4b4d58_2863760560ad468bc475bab3901b815b_drm_software_540p_dash_v1-video=2099976.dash
works correctly but same url with lbcdn.6cloud.fr (from the debug log) doesnt - it 404

I suspect maybe they are in the process of changing their DNS or something like that.
Looks like their manifests should be using 6play.vod.6cloud.fr

**I think they just need to use 6play.vod.6cloud.fr instead of lbcdn.6cloud.fr**

 Not an issue in Inputsream Adaptive though. It's working out the urls correctly.
 It's the providers manifests that are wrong / outdated.
 The webplayer is using a correct manifest with correct urls.
 So maybe the add-on just needs to be updated to use the new domain?
 Or a different end-point to fetch the manifest urls?
 
 Please remember to close this issue once you sort that out :)

**Comment by Arias800** [comment]
Ok, thanks.

**Comment by matthuisman** [comment]
One thing I  just thought of is if the manifest is being redirected... I'll check.2moro
UPDATE: No redirect so yeh, seems the manifest is wrong / outdated

**Comment by chamchenko** [comment]
@matthuisman
Yes in the web browser there is a redirection using the location header. I've created a PR that fixes the problem for this plugin by catching the real address of the manifest after the redirection then feeding it to inputstream.
Issue is inputstream adaptive is defaulting to the base url  before the redirection.

**Comment by wwark** [comment]
Thanks @chamchenko !
Thanks @matthuisman to check this part give us some hints.
This ticket can be closed.

**Comment by osmoze06** [comment]
Thank you very much to all ! Everything works again!

**Comment by matthuisman** [comment]
Please reopen as this appears to be an issue in IA. It should be using the final redirected url to calculate the segment urls.

@glennguy I wonder if this is the one quirk we knew about with redirects

**Comment by glennguy** [comment]
Let's look at the DASH-IF docs. I'm pretty sure I remember reading that if we get a redirect from the manifest then we should start using that for the baseurl and/or further refreshes.
There's also the location tag in mpd but that might be slightly different. Not for this issue anyway

**Comment by matthuisman** [comment]
I thought we were already using the final URL to calc base url, domain etc

**Comment by matthuisman** [comment]
@wwark @osmoze06  @Arias800

could you try with IA test build from here:
https://github.com/xbmc/inputstream.adaptive/pull/675#issue-636598550

And of course, try with a version of the add-on without the current work-around (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/515)

**Comment by matthuisman** [comment]
@wwark @osmoze06 @Arias800
anyone tried yet??

**Comment by Arias800** [comment]
Hello,
I was busy this week, so I couldn't test this correction before.
But anyways, I have tried the test build, and It fixes the issues.

**Comment by matthuisman** [comment]
thank you for testing :)

**Comment by wwark** [comment]
sorry, I will test on my side this week-end.
Is this fix will be available also for Kodi 18 ? If it is not the case we will have to keep the other fix on our side.
Thanks again !

**Comment by matthuisman** [comment]
it won't be in Kodi 18, so keep your local fix.
But please still test this fix (without your local fix)
