### ISSUE TITLE
[HLS] TS Byterange fails to play

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#687]
Main manifest: https://pastebin.ubuntu.com/p/npZ8KT95NZ/
Audio / video manifest: https://pastebin.ubuntu.com/p/W6vdwb3PZV/

test strm: https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_ts_byterange/ia.strm

debug log: 
[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/6488904/kodi.log.txt)

sometimes even crashes kodi

**Comment by matthuisman** [comment]
interesting, I've found if the byte range starts at 0, then IA plays it OK

Plays ok:
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_ts_byterange_from_zero/ia.strm
manifest: https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_ts_byterange_from_zero/sub.m3u8

doesnt play:
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_ts_byterange/ia.strm
manifest: https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_ts_byterange/sub.m3u8

**Comment by matthuisman** [comment]
ok, think I found the issue
https://github.com/xbmc/inputstream.adaptive/blob/master/src/common/AdaptiveStream.cpp#L63
if I set that to 0 - it'll play fine.

**Comment by matthuisman** [comment]
ok, i can make it work if I comment out

https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveStream.cpp#L59
and https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveStream.cpp#L213

It seems that check is thinking range_begin_ is referring to a timestamp?
as per here: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveTree.h#L138

So, it's actually just a coincidence that EXT-X-BYTERANGE starting at 0 are working.
As that is setting absolute_position_ to 0 which is what is required

i think both those statements need to be updated to also skip TS or byterange streams..

**Comment by glennguy** [comment]
Yes I think you're completely right. The implementation was the first implementation of fmp4 for hls (separate segment fmp4 didn't happen until disney+) and the init segment is always at 0 anyway:
https://github.com/xbmc/inputstream.adaptive/blob/c08955927f2aabdd1521bcb0ae070ac23b69d504/src/parser/HLSTree.cpp#L698
... seems that TS doesn't like it - `AVContext::configure_ts()` fails in tsDemuxer.cpp. 

> i think both those statements need to be updated to also skip TS or byterange streams..

Only the one instance now in Nexus branch

I think `&& current_rep_->containerType_ != AdaptiveTree::ContainerType::CONTAINERTYPE_TS` being added to the condition check will do the job, just need to test several TS streams to confirm.

**Comment by matthuisman** [comment]
@glennguy awesome - great work!
Let me know if you need anything more from me :)
Was you do a PR, I can test as well

**Comment by glennguy** [comment]
Sure thing, see #831

**Comment by matthuisman** [comment]
fixed with https://github.com/xbmc/inputstream.adaptive/pull/831
