### ISSUE TITLE
2.1.0 friert Player ein 

### ISSUE THREAD

**Issue by quthla** [peak3d/inputstream.adaptive#69]
Kodi Nightly x64 auf Windows kein Problem. Mit der Version von gestern allerdings, mit Adaptive 2.1.0, friert der Player erst ein, wenn man mehrmals hintereinander seekt, GUI läuft aber noch (Uhrzeit verändert sich etc), drückt man auf Stopp, friert die GUI auch ein und kodi hängt sich komplett auf. Zu 100% reproduzierbar. Getestet mit pvr.zattoo. 

Wäre auch gut, würde sich das Manifest, wie im Webplayer, alle 8 Sekunden oder überhaupt aktualisieren, weil man sonst zb keine Werbung überspringen kann, wenn man eine Sendung guckt, die gerade läuft.

**Comment by quthla** [comment]
Kodi Nightly x64 vom 7.9. auf Windows kein Problem sollte es heißen. Version vom 12.9. zeigt beschriebenes Problem.

**Comment by quthla** [comment]
Problem anscheinend auch unter Linux mit Adaptive 2.1.0 bei verschiedenen Leuten unabhängig voneinander

https://www.kodinerds.net/index.php/Thread/49569-Zattoo-PVR-Client/?postID=406726#post406726
https://www.kodinerds.net/index.php/Thread/49569-Zattoo-PVR-Client/?postID=406719#post406719

**Comment by ksooo** [comment]
Have you noticed that everybody else here is communicating in English?

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/commit/c49c8db5a71c1f0dc18d55dd180aac2d68a40b73
