### ISSUE TITLE
Audio causes video stuttering on L1 Android device

### ISSUE THREAD

**Issue by Testato** [peak3d/inputstream.adaptive#693]
@Testato 
Did you open an issue for the Android stuttering?
I wonder if it does it if you go into Inputstream Adaptive Settings and set Media to "Video"
You won't get Audio - but interested to see if that fixes it

I have seen with HBO Max, EC3 (dolby digital+) audio causes the video to stutter etc
which made me think, maybe there is an issue decoding some audio streams with secure decoder

_Originally posted by @matthuisman in https://github.com/xbmc/inputstream.adaptive/issues/647#issuecomment-843703642_

**Comment by matthuisman** [comment]
could you try what I suggested?

go into Inputstream Adaptive Settings and set Media to "Video"
Then try playback. You won't get audio - but see if Video plays better.

Remember to disable the IA securedecoder setting when testing so you are actually using L1

**Comment by Testato** [comment]
@matthuisman 
YEP you are right !

No stuttering on Samsung S9+ 
I will test on Nokia 3.4 also

@lpuglia
May you try on your L1 Philips TV ?

**Comment by matthuisman** [comment]
@glennguy  - we have a clue!

@Testato 
Can you check if the stream has multiple audio tracks?
If so, can you try changing between them during playback and see if that helps.

Can you also provide a copy of the manifest that has issues again...
I want to try to find out what type of audio stream it is. I wonder if it's EC-3 as well....

**Comment by Testato** [comment]
It seems that the stream have only one audio track

![Screenshot_20210519-070404_Kodi](https://user-images.githubusercontent.com/6893841/118759150-c374ed00-b870-11eb-889e-026cf438ec9c.jpg)

For the .mpd may download it yourself ? Sorry I'm on phone now and it is difficult do it.
https://www.la7.it/dirette-tv

Thanks

**Comment by Testato** [comment]
No problem also on Nokia 3.4 L1 device, where the stuttering was much worse than on samsung.
So the problem is definitively the audio stream

**Comment by glennguy** [comment]
@Testato thanks for opening the issue. In future it's best if you can describe the issue yourself rather than quoting someone's request to open an issue (the comment quoted being from an issue created in the exact same way...) It's hard for others to contribute without proper context.

**Comment by glennguy** [comment]
Has anyone seen this thread? https://forum.kodi.tv/showthread.php?tid=361156
Similar sounding issue, audio is the suspected cause.

**Comment by glennguy** [comment]
[mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/6509032/mpd.txt)

Nothing fancy in here, one audio rep `<Representation id="5" bandwidth="96000" audioSamplingRate="44100" codecs="mp4a.40.2"/>` == LC-AAC

**Comment by matthuisman** [comment]
@glennguy 
it could also be that just the extra bandwidth of the audio track is stopping IA from keeping up
but why does the secure decoder affect that?
We can't have Video going via Secure and Audio via Non-secure can we?
Its just a single session used by all

**Comment by matthuisman** [comment]
@Testato 
I doubt this will work, but can you try IA build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-696/1/artifacts
see if audio still causes the stutter

And then try an IA build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-698/1/artifacts

**Comment by matthuisman** [comment]
looks like HBO Max audio streams have quite big issues with audio too.

I've had to add setting to the add-on to disable EC-3 and AC-3.
https://forum.kodi.tv/showthread.php?tid=358484&pid=3038367#pid3038367

"In addition, the CPU occupancy rate was relatively high at that time, reaching 100+%."

On Amazon Fire TV 4k and Google TV (both L1)

**Comment by Testato** [comment]
> @Testato
> I doubt this will work, but can you try IA build from here:
> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-696/1/artifacts
> see if audio still causes the stutter
> 
> And then try an IA build from here:
> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-698/1/artifacts

the link is not active ?

during the stuttering on LA7 stream the cpu on Android do not change, and remain always about 50%

**Comment by Liqianyu** [comment]
@matthuisman 
HBO Max Add-on using E-AC3 Audio is easy to lag and buffer. But switching AAC once may ease it.
Switching back to E-AC3 again at this time will not buffer frequently.

**Comment by matthuisman** [comment]
@Testato  @Liqianyu 
could you guys try the android build from here and see if it makes any difference to pixalation / buffering issues?
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-734/1/artifacts

**Comment by Liqianyu** [comment]
@matthuisman 
I tested this on Shield TV 2019 Kodi 19.1 Nightly. Playing Wonder Woman 1984 via HBO Max Add-on. the audio track still causes constant buffering issues.
However, the problem can be avoided by switching tracks. For example, after starting playback, switch to DD+ 5.1ch, then switch back to DD+ Atmos.

**Comment by Testato** [comment]
@matthuisman this version solve the problem on LA7 Plugin and Samsung S9+

**Comment by lpuglia** [comment]
> @Testato @Liqianyu
> could you guys try the android build from here and see if it makes any difference to pixalation / buffering issues?
> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-734/1/artifacts

Hey @matthuisman , the artifacts seems to be removed, is the PR already built into:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/inc-ver/3/artifacts
?

i tried it this morning but it doesn't seem to solve my problem (https://github.com/xbmc/inputstream.adaptive/issues/582).

**Comment by Testato** [comment]
@lpuglia 
the PR is present on the new IA version 2.6.23
try to update and test it on you TV
