### ISSUE TITLE
.mpd fail only on Linux

### ISSUE THREAD

**Issue by Testato** [peak3d/inputstream.adaptive#695]
In my plugin, RepubblicaItaliana that you can find on Official Kodi Repo, there is a strange problem but only on Linux (tested on Ubuntu 20.04 + Kodi 19.1 + IA 2.6.15).
The plugin have some tv channel in it, all play directly by ffmpeg, but only one is a .mpd link so I use IA only for it.
It is not encripted, it not use widevine.

On Win10 and on Android there is no problem, instead if i play this channel on linux: TV-->TgCom24
1) at the beginning it work but only until the buffer blue bar reach the end, at the end of the bar the play will block.
2) if you press Stop and try to Play again the stream not start

This is the piece of code
```
    titolo = 'TgCom24'
    liStyle = xbmcgui.ListItem(titolo)
    link = 'https://live3.msf.cdn.mediaset.net/Content/dash_d0_clr_vos/live/channel(kf)/manifest.mpd'
    thumb = 'https://www.mimesi.com/wp-content/uploads/2017/11/tgcom24.jpg'
    liStyle.setArt({'thumb': thumb, 'fanart': G.FANART_PATH})
    liStyle.setInfo('video', {})
    liStyle.setProperty('isPlayable', 'true')
    liStyle.setProperty('inputstream', 'inputstream.adaptive')
    liStyle.setProperty('inputstream.adaptive.manifest_type', 'mpd')
    liStyle.setMimeType('application/dash+xml')
    liStyle.setContentLookup(False)
    xbmcplugin.addDirectoryItem(handle=G.PLUGIN_HANDLE, url=link, listitem=liStyle, isFolder=False)
```

This is the manifest.mpd
[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/6509604/manifest.txt)

This is the stream
https://www.tgcom24.mediaset.it/video/

this is the last version of the plugin not loaded yet on kodi repo
[plugin.video.repubblicaitaliana.zip](https://github.com/xbmc/inputstream.adaptive/files/6509523/plugin.video.repubblicaitaliana.zip)

**Comment by matthuisman** [comment]
Only thing I see different in manifest is PT2.0S
Not sure if IA can parse that correctly with the decimal. I'll check

Oh wait, it's working on windows so not that.

**Debug log please**

**Comment by Testato** [comment]
yep, it is ONLY present on Linux

May you confirm that ffmpeg still can't read .mpd ?

This is the log
https://paste.kodi.tv/uvuperedux.kodi

**Comment by matthuisman** [comment]
You could try ffmpeg direct

**Comment by Testato** [comment]
if i must install a plugin i prefer IA :-)

**Comment by matthuisman** [comment]
your issue is

`AddOnLog: inputstream.adaptive: Cannot download https://live3.msf.cdn.mediaset.net/Content/dash_d0_clr_vos/live/channel(kf)/manifest.mpd`

It downloads initially, then fails when trying to refresh the manifest

Also, you can't use?
`https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(kf)/index.m3u8`

**Comment by Testato** [comment]
Maybe, but it is interesting understand if it is an IA bug.
I repeat that the same .mpd work on Android and Windows

**Comment by matthuisman** [comment]
you'll need find why download is failing in Linux.
Can you download the mpd every 2 seconds in the browser on Linux?

Enable component debug logging for CURL.
Then re-do the test and get me a new log.
That will tell us why curl is failing

**Comment by Testato** [comment]
On chrome there is no problem, the .mpd is downloaded very speedy, yes probably every two seconds

**Comment by matthuisman** [comment]
Enable component debug logging for CURL in Kodi
Then re-do the test and get me a new log.
That should tell us why curl is failing

**Comment by Testato** [comment]
https://paste.kodi.tv/anetoticig.kodi

p.s. how you find the .m3u8 link ?
I tried to change the agent to android or ios or ie but Chrome use always the .mpd

**Comment by matthuisman** [comment]
i had googled and found this:
https://salva59s.github.io/m3u/

hmm your log doesn't say much...
It doesn't even get to CURL

Are you able to try with a build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Matrix/67/artifacts

**Comment by glennguy** [comment]
I'm seeing that it's trying for those Bluray structure files in the log, bdmv etc:
`2021-05-20 19:34:52.297 T:18983   DEBUG <general>: Curl::Debug - HEADER_OUT: HEAD /Content/dash_d0_clr_vos/live/channel(kf)/manifest.mpd/BDMV/index.bdmv HTTP/1.1`

**Comment by Testato** [comment]
@matthuisman 
but the build isn't for linux ...
android and windows already work :-)
It's not possible add to the artifact system a .deb ? i think is much usefull a .deb that the various ios, apple etc

**Comment by matthuisman** [comment]
oh right, sorry - i thought it also built for Linux- but i think only does on release for PPA

@glennguy
i think thats actually a new bug in Kodi.. investigating
I get same on this issue too: https://github.com/xbmc/inputstream.adaptive/issues/686

**Comment by Testato** [comment]
i found in my plugin another chanel that not work ONLY on Linux
https://video-ar.radioradicale.it/diretta/padtv2/playlist.m3u8

**Comment by matthuisman** [comment]
is is possible you try Kodi 19.0 ?
i think possibly a bug in 19.1

**Comment by Testato** [comment]
here there isn't linux version:
http://mirrors.kodi.tv/releases/

Where download kodi19.0.deb ?

**Comment by Testato** [comment]
Now that I remember, i updated two days ago from 19.0 to 19.1 in the hope that it solve this problem.
So the bug is present also on Kodi 19.0

**Comment by CastagnaIT** [comment]
I tested on Ubuntu 22.04 by using Kodi v20
the live stream is now played without problems

@glennguy Kodi 19 is EOL, and the branch is broadly diverged,
i suggest to invest our time on Kodi 20/21 and close this, i will leave you a message on slack to discuss

**Comment by CastagnaIT** [comment]
we have just discussed internally and we stop Kodi 19 development
then only thing we can suggest you is to go ahead with Kodi 20
