### ISSUE TITLE
Create tagged release

### ISSUE THREAD

**Issue by candrews** [peak3d/inputstream.adaptive#7]
Can you please create a release tag (looks like it should be "v1.0.6" based on the contents of https://github.com/peak3d/inputstream.adaptive/blob/master/inputstream.adaptive/addon.xml.in )?

That would really help distributions (in my case, Gentoo) package this add-on.

Thanks!

**Comment by peak3d** [comment]
My first git tag is 1.0.6, its the  version before I bumped to 1.0.7

**Comment by candrews** [comment]
Thank you!

Can you please continue to create git tags as your create future releases? :-)

**Comment by peak3d** [comment]
sure, will try to not forget it
