### ISSUE TITLE
Settings doesn't honor 1080p setting

### ISSUE THREAD

**Issue by parkerlreed** [peak3d/inputstream.adaptive#70]
Running Kodi 17.4 and inputstream.adaptive git on a Raspberry Pi Zero W.

In the inputstream.adaptive settings I have the max resolution set as 1080p (as that is the max it can hardware decode). When I have 1080p in settings and play a YouTube video with a 1080p@60 option, it plays the 720p@60 stream. The only way I can play the 1080p@60 is setting the max resolution to "Max" in settings.

**Comment by peak3d** [comment]
can you pls provide a kodi log?

**Comment by parkerlreed** [comment]
I have since lost that install and when I tried on my desktop it loads 1080@60 with the inputstream.adaptive set to 1080p. Will close out. Sorry for not updating sooner.

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
