### ISSUE TITLE
Header information passing problem in matrix

### ISSUE THREAD

**Issue by Vikassm73** [peak3d/inputstream.adaptive#706]
Tty to pass header information

phdr = headers
phdr.update({'x-playback-session-id': 'b3751171afcb441a865c018433ff3534-1622824103229'})
phdr.update({'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'})
play_item.setProperty('inputstream.adaptive.stream_headers', urllib_parse.urlencode(phdr))

But it failed to pass in Matrix. The same code works perfectly in Leia Version.

Complete Debug log

[kodiLog.log](https://github.com/xbmc/inputstream.adaptive/files/6604223/kodiLog.log)

Manifest of above URL

[Temp.txt](https://github.com/xbmc/inputstream.adaptive/files/6604226/Temp.txt)

**Comment by glennguy** [comment]
> play_item.setProperty('inputstream.ffmpegdirect.stream_headers', urllib_parse.urlencode(phdr))

> inputstream.ffmpegdirect

I think this might be your problem?

**Comment by Vikassm73** [comment]
previously I have used inputstream.adaptive but the same error was there. Now noticed that issue was there in the below statement

play_item.setProperty('inputstreamaddon', 'inputstream.adaptive')

After changing inputstreamaddon to  inputstream, it starts working. Thanks
