### ISSUE TITLE
Not processing Cookies

### ISSUE THREAD

**Issue by kyl416** [peak3d/inputstream.adaptive#72]
I'm trying to diagnose an issue involving akamai's streams that have hdnea auth codes. For privacy/security reasons I can't provide the actual URLs, but hopefully you have an idea of what I'm talking about since Akamai's token authentication is in common use.

One provider has akamai HLS urls with an auth code:
```
https://blablabla-i.akamaihd.net/hls/live/xxxxx/name1/name2/index.m3u8?hdnea=randomauthcode
```

In the response header when you fetch that index.m3u8 file there are also a bunch of Set-Cookie values that Akamai expects to continue to be sent with the requests for each variant playlist and the .ts segments within those playlists.
```
Set-Cookie: hdntl=randomvalue1; path=/; domain=blablabla-i.akamaihd.net;
Set-Cookie: removed_hdnts=randomvalue2; path=/; domain=blablabla-i.akamaihd.net;
Set-Cookie: _alid_=randomvalue3; path=/hls/live/xxxxxx/name1/name2/; domain=blablabla-i.akamaihd.net
```

FFmpeg processes these set-cookie values and passes them along when it fetches those individual bitrate variations and ts segments. But it looks like inputstream.adaptive doesn't, so it just results in 403 errors when it attempts to fetch the variant playlists within the index.m3u8 file:
```
ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
ERROR: CCurlFile::Open failed with code 403 for https://blablabla-i.akamaihd.net/hls/live/xxxxx/name1/name2/master4.m3u8|acceptencoding=gzip&seekable=0
```

Yes, I could just use the default ffmpeg system, but the problem is there's no way to specify max bitrates or resolutionjs, which creates problems with slower connections and it tries to use a bitrate or resolution greather than their connection or device can support, or ends up timing out when there's a lot of variant bitates in the playlist and ffmpeg processes all of them before it starts playback.

**Comment by peak3d** [comment]
Ok, I'll look at it

**Comment by glennguy** [comment]
Hi @kyl416 
I faced the exact same issue with akamai. I made a 'dummy' request first and grab the cookies from that to send with the real request.

The addon is [here](https://github.com/xbmc-catchuptv-au/plugin.video.abc_iview) if you want to take a look, and this is the relevant code:
```
def cookies_to_string(cookiejar):
    cookies = []
    for cookie in cookiejar:
        cookies.append('{0}={1}; path={2}; domain={3};'.format(
            cookie.name, cookie.value, cookie.path, cookie.domain))
    return ' '.join(cookies)


def get_stream_url(hn, url):
    utils.log("Fetching stream URL: {0}".format(url))
    with session.Session() as sess:
        sess.headers = {'User-Agent': config.USER_AGENT}
        akamai_auth = get_auth(hn, sess)
        akamai_url = "{0}?hdnea={1}".format(url, akamai_auth)
        request = sess.get(akamai_url)
        cookies = cookies_to_string(request.cookies)
        stream_url = '{0}|User-Agent={1}&Cookie={2}'.format(
            akamai_url, urllib.quote(config.USER_AGENT), urllib.quote(cookies))

    return stream_url
```
Hope this helps!

**Comment by peak3d** [comment]
Can we close the issue? Cookie retrieval was implemented in binary API interface.
