### ISSUE TITLE
Apple TV 4K 2021 Widevine CDM missing(?)

### ISSUE THREAD

**Issue by AntiBigmac** [peak3d/inputstream.adaptive#721]
Is there anyway me to use Netflix addon with Apple TV 4K 2021?

Currently, I have gotten error message that the widevine CDM is not available on this system architecture. 

Any suggetions?

**Comment by matthuisman** [comment]
@AntiBigmac

i think your best asking over here:
https://github.com/emilsvennesson/script.module.inputstreamhelper
that takes care of installing CDM etc.

please close this issue :)

**Comment by AntiBigmac** [comment]
> @AntiBigmac
> 
> 
> 
> i think your best asking over here:
> 
> https://github.com/emilsvennesson/script.module.inputstreamhelper
> 
> that takes care of installing CDM etc.
> 
> 
> 
> please close this issue :)

Thanks. 👍
