### ISSUE TITLE
Unable to resolve: inputstream.adaptive.so.2.0.18 ADDON_GetTypeVersion

### ISSUE THREAD

**Issue by lowang** [peak3d/inputstream.adaptive#73]
Today my Netflix plugin (https://github.com/asciidisco/plugin.video.netflix) stopped playing any videos, when I've checked logs I've got following:
```
21:19:26.050 T:140430518667008  NOTICE: Creating InputStream
21:19:26.097 T:140430518667008 WARNING: Unable to resolve: /inputstream.adaptive.so.2.0.18 ADDON_GetTypeVersion, reason: /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.18: undefined symbol: ADDON_GetTypeVersion
21:19:26.097 T:140430518667008   ERROR: Unable to resolve exports from dll /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.18
```
I've got installed `kodi-inputstream-adaptive 2.0.18-3~trusty` from 
```
deb http://ppa.launchpad.net/team-xbmc/unstable/ubuntu trusty main
deb-src http://ppa.launchpad.net/team-xbmc/unstable/ubuntu trusty main
```
my kodi version is `2:18.0+git20170918.0201-f5bdcb3-0trusty` from http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu/

**Comment by vdrtuxnet** [comment]
Never ever mix unstable addon.debs with nightly kodi.debs, and vice versa, this can't work, because you will trap into unresolvable dependency's, as you already did.

**Comment by lowang** [comment]
Thanks for prompt reply, I was following your suggestion, in order to have netflix  (https://github.com/asciidisco/plugin.video.netflix) addon I need kodi 18 which is only available via `http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu/` 
However when I install `kodi-inputstream-adaptive` from that nightly I'm getting `2.0.17-1~trusty`
Then when I'm starting Kodi I've got following in kodi.log and I cannot enable it:
```
20:23:52.746 T:140060568807488   ERROR: Add-on 'inputstream.adaptive' is not compatible with Kodi
```

but when I mix and use unstable `kodi-inputstream-adaptive` I've got `2.0.18-3~trusty`
but then I've got following:
```
20:38:03.005 T:140202405197888  NOTICE: ADDON: inputstream.adaptive v2.0.18 installed
...
20:40:48.903 T:140200311342848  NOTICE: Creating InputStream
20:40:48.972 T:140200311342848 WARNING: Unable to resolve: /inputstream.adaptive.so.2.0.18 ADDON_GetTypeVersion, reason: /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.18: undefined symbol: ADDON_GetTypeVersion
20:40:48.972 T:140200311342848   ERROR: Unable to resolve exports from dll /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.18
```
same as above happens on kodi `2:18.0+git20170905.0200-3dbac37-0trusty`

Finally I explore my previous versions of kodi in `/var/cache/apt/archives/` and I've got it WORKING!.
Recipe for success was 
- kodi *unstable* `2:18.0+git20170905.0200-3dbac37-0trusty`
- kodi-inputstream-adaptive *xbmc-nightly* `2.0.17-1~trusty`

So my problem is solved for now, we can close this issue - thanks for different versions tip that lead me to solution :)
However I think this discrepancy will backfire.

**Comment by wsnipex** [comment]
I've updated the nightly PPA with the latest version 2.1.4
