### ISSUE TITLE
Memory leak in AP4_Movie::GetPsshAtoms

### ISSUE THREAD

**Issue by babyraging** [peak3d/inputstream.adaptive#730]
Hi there. I've found out a possible memory leak at the line

https://github.com/xbmc/inputstream.adaptive/blob/a675541a5c10e0ff4e0ec2fa7b4c9d8306bcffb8/lib/libbento4/Core/Ap4Movie.cpp#L115

The definition of the property is at the line 
https://github.com/xbmc/inputstream.adaptive/blob/a675541a5c10e0ff4e0ec2fa7b4c9d8306bcffb8/lib/libbento4/Core/Ap4Movie.h#L79

This will actually cause a memory leak since the destructor of `AP4_Array` class will only free the allocated `AP4_PsshAtom*` pointers and not the actual `AP4_PsshAtom`.

A really simple fix could be to change the property definition

```C
AP4_Array<AP4_PsshAtom> m_PsshAtoms;

// and the get method
AP4_Array<AP4_PsshAtom>& GetPsshAtoms()   { return m_PsshAtoms; }
```
remove the new statement

```C
m_PsshAtoms.Append(AP4_PsshAtom(*pssh_item->GetData())); 
// or
m_PsshAtoms.Append(*pssh_item->GetData()); 
```

change where the method is used
https://github.com/xbmc/inputstream.adaptive/blob/a675541a5c10e0ff4e0ec2fa7b4c9d8306bcffb8/src/main.cpp#L2322-L2334

```C
AP4_Array<AP4_PsshAtom>& pssh = movie->GetPsshAtoms();

// and all pssh[i]-> to ppsh[i].
```

What do you think? Are there anything that I'm missing? If the memory leak is legit, should I make a PR?

Thank you.

**Comment by glennguy** [comment]
Hi @babyraging 

I'm wondering if it has been addressed or not upstream https://github.com/axiomatic-systems/Bento4/tree/master/Source/C%2B%2B

The source here is around 4 years or so out of date, I'm not sure exactly but there's been a lot of modifications done here, some are which in commit history but some which predate the initial commit. I'd love to know the hash so we could do a diff...

**Comment by babyraging** [comment]
Hi @glennguy 

Actually, I think `m_PsshAtoms` was added to the code base as a patch for inputstream.adaptive. I've tried to look some old/very old and new releases of bento4, it seems like they haven't ever had `m_PsshAtoms` defined in the `AP4_Movie` class.

I could be wrong tho...
