### ISSUE TITLE
 [Dash] Manifest without mediaPresentationDuration & timeShiftBufferDepth won't play

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#731]
Below won't play 
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2021-07-08T22:35:15Z" publishTime="2021-07-08T22:35:00Z" minimumUpdatePeriod="PT24H" minBufferTime="PT2.048S" suggestedPresentationDelay="PT4.096S" maxSegmentDuration="PT2.048S">
  <ProgramInformation/>
  <Period id="1" start="PT0S">
    <BaseURL serviceLocation="15805-Akamai">https://p-cdn1-805-cg14-linear-cbd46b77.movetv.com/15805/live/COMEDY/0b804a18dfd111ebbc620025b5472112/</BaseURL>
    <AdaptationSet contentType="video" mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
      <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b"/>
      <Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015" value="CC1=eng"/>
      <Accessibility schemeIdUri="urn:scte:dash:cc:cea-708:2015" value="1=lang:eng"/>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate initialization="video/$RepresentationID$/init.mp4" media="video/$RepresentationID$/$Number%08x$.m4s" startNumber="22588" timescale="1000" duration="2048" presentationTimeOffset="46255543"/>
      <Representation id="vid06" bandwidth="5632000" width="1920" height="1080" codecs="avc1.640028" sar="1:1" frameRate="29970/1000" qualityRanking="0"/>
      <Representation id="vid05" bandwidth="4300800" width="1280" height="720" codecs="avc1.640028" sar="1:1" frameRate="29970/1000" qualityRanking="1"/>
      <Representation id="vid04" bandwidth="2867200" width="1280" height="720" codecs="avc1.640028" sar="1:1" frameRate="29970/1000" qualityRanking="2"/>
      <Representation id="vid03" bandwidth="1536000" width="768" height="432" codecs="avc1.4d401f" sar="1:1" frameRate="29970/1000" qualityRanking="3"/>
      <Representation id="vid02" bandwidth="819200" width="768" height="432" codecs="avc1.4d401f" sar="1:1" frameRate="29970/1000" qualityRanking="4"/>
      <Representation id="vid01" bandwidth="319488" width="512" height="288" codecs="avc1.4d401f" sar="1:1" frameRate="29970/1000" qualityRanking="5"/>
    </AdaptationSet>
  </Period>
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2021-07-08T22:38:56.243Z"/>
</MPD>
```

produces the below error
```
AddOnLog: inputstream.adaptive: Build segments from SIDX atom...
AddOnLog: inputstream.adaptive: Unable to create SIDX from IndexRange bytes
AddOnLog: inputstream.adaptive: Unable to select stream!
```
This is because without mediaPresentationDuration  and timeShiftBufferDepth our dash->overallSeconds_ will be 0
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1030

which results in overallSeconds being set to 0 here: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1213
which makes this statement false: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1217

which then makes the eles statement here code execute:
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1285

which sets dash->current_representation_->flags_ |= DASHTree::Representation::SEGMENTBASE;
which breaks playback as we don't have a SEGMENTBASE

My code here fixes it: https://github.com/matthuisman/inputstream.adaptive/commit/e2902c133dc04e71dccde7a8542c48f88325cae3
by removing the check for overallSeconds > 0

However, there is a hack in that code as I noticed Kodi won't playback if countSegs < 6
Which is the same as overallSeconds being 11.
If I hardcode overallSeconds to 11 (gives 6 countSegs) , it'll play
But overallSeconds of 10 (gives 5 countSegs) won't.
This mpd is 2.048s each segment

Maybe it's due to required kodi buffer.
or something in here: https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveStream.cpp#L176

With overallSeconds of 0 we should have 1 segment in current_rep_->segments_.data

**Comment by matthuisman** [comment]
right, further to this - that platform using this uses Shaka Player.
It also allows it to rewind to the start of the current program.

I notice it uses the availabilityStartTime to figure that out...
So maybe it's a dash spec that you use (current_time - availabilityStartTime) to calcuate timeShiftBufferDepth if it's not specified?

**Comment by glennguy** [comment]
> So maybe it's a dash spec that you use (current_time - availabilityStartTime) to calcuate timeShiftBufferDepth if it's not specified?

Exactly:
![image](https://user-images.githubusercontent.com/11909320/127768762-21bbb503-a04b-48fe-91d4-6354f0c2c2ce.png)

**Comment by matthuisman** [comment]
looks like this is causing issues with Sling streams:
https://github.com/d21spike/plugin.video.sling/issues/40#issuecomment-990676307

Notice that sling MPD has no timeShiftBufferDepth 
and also no availabilityStartTime

**Comment by CastagnaIT** [comment]
@matthuisman do you still have this stream available?
can you test with PR #1508 to see what happens?

**Comment by CastagnaIT** [comment]
closed since no replies, if the a problem occurs with last ISA release for kodi 21
feel free to reopen the issue
