### ISSUE TITLE
Loud cracking noise then no sound when seeking DASH

### ISSUE THREAD

**Issue by quthla** [peak3d/inputstream.adaptive#74]
Deadlock seems to be fixed but now when seeking there often is a very loud cracking noise and then there is no more audio at all even when seeking again. You have to completely restart the stream but then it's very common to happen again.

Tested with pvr.zattoo using Inputstream 2.1.2. Had to downgrade to pre 2.1 because no problems there at all.

**Comment by quthla** [comment]
Still exists in nightly from today on RPi3.

**Comment by peak3d** [comment]
These are kodi issues and not inputstream.adaptive. @milhouse already noted in his thread on forum.kodi.tv that core devs are currently working on it.
