### ISSUE TITLE
License URL Error

### ISSUE THREAD

**Issue by spacex97** [peak3d/inputstream.adaptive#755]
Hi Guys
I am using m3u file with widevine license url. I am able to download mpd but getting error in fetching license.
`ERROR: AddOnLog: InputStream Adaptive: 4 '|' separated blocks in licURL expected (req / header / body / response)`
license url format
`#KODIPROP:inputstream.adaptive.license_key=licurl|headers|R{SSM}|`
Pls let me know whats wrong in above format.

**Comment by glennguy** [comment]
Well the template looks fine. If you post the actual line from your m3u8 then we can help

edit: a working example
`#KODIPROP:inputstream.adaptive.license_key=https://proxy.uat.widevine.com/proxy||R{SSM}|`

**Comment by spacex97** [comment]
ok here it is, i have removed some personal information and put xx
`#EXTINF:-1 tvg-id="144" tvg-name="Colors HD" tvg-country="IN" tvg-logo="https://assets.tv.whore.zone/images/j/tEjAMpwRiI.png" tvg-chno="1" group-title="Hindi (JioTV+)",Colors HD
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key="https://tv.media.jio.com/proxy?provider=reliance&content_id=9899990507|crmid=xx&appKey=xx&lbCookie=1&usergroup=xx&versionCode=77&appId=jiovod&jioId=xx&deviceid=xx&devicetype=tv&os=android&idamId=xx&srno=xx&Content-Type=application%2Foctet-stream&subscriberid=xx&channelid=753&playbackToken=xx&ssoToken=xx&User-Agent=JioCinemaFireOS%2F1.0.4.9%20%28Linux%3BAndroid%207.1.2%29%20ExoPlayerLib%2F2.11.1&Accept-Encoding=gzip%2C%20deflate&Content-Length=2120&Host=tv.media.jio.com&Connection=close|R{SSM}|R"
https://jiotv.live.cdn.jio.com/bpk-tv/MTV_Beats_HD_BTS/output/index.mpd|User-Agent=KAIOS`

**Comment by glennguy** [comment]
Using that string you provided works (no `4 '|' separated blocks in licURL expected` message), it 403s of course because of missing headers or geoblock...

Perhaps some of the personal information contained a `|`?

edit: take the quotes (`"`) away, maybe that's your issue

**Comment by spacex97** [comment]
This has been fixed some issues were there with url params and header :D

**Comment by bencooper1** [comment]
Hi @spacex97 ! Could you put your full working code? Thanks!
