### ISSUE TITLE
Dash License Issue

### ISSUE THREAD

**Issue by spacex97** [peak3d/inputstream.adaptive#768]
Hello Guys
I am able to get raw binary license in python script but when same is implemented to kodi I get http 500 error.
I am unable to understand what is causing this.

`#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000542&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNTk5MTYxMzc0NzY0In0.eyJzdWIiOiIxMzExMDczNjI5IiwiaXNlIjp0cnVlLCJqdGkiOiIyZTM5NTg4Ny02ZjcxLTRkY2EtOTVlNC0yYzQwN2RhZTk4NTQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjI3OTA4ODU5LCJuYW1lIjoiS3VtYXJlc2FuIEtOIiwiaWF0IjoxNjI3ODIyNDU5LCJlbnQiOlt7ImVwaWQiOiJTdWJzY3JpcHRpb25fQnJvd3Nlcl9TdHJlYW1pbmciLCJiaWQiOiIxMDAwMDAxMDY1In1dLCJpc3MiOiJUVE4ifQ.yrBGTBHTGzziwMHAumU6W-Xywg-rIxxox1PdBwBsDs4||R{SSM}|`

**Comment by glennguy** [comment]
@spacex97 sorry we never gave any help on this, did you end up solving the issue?
