### ISSUE TITLE
Not able to play video

### ISSUE THREAD

**Issue by drt420** [peak3d/inputstream.adaptive#78]
Hello
i am not able to play video from mpd and following is the logs

`00:08:58.403 T:19256  NOTICE: VideoPlayer: Opening: https://a184avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/1b5c/52f2/a4f0/4ad3-89bf-90c539fa734f/08dfe850-06a7-4f83-a530-04c8e3a40bc7_corrected.mpd
00:08:58.403 T:19256 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
00:08:58.419 T:19256   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
00:08:58.419 T:19256   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
00:08:58.419 T:19092  NOTICE: Creating InputStream
00:08:58.682 T:19092   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://a184avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/1b5c/52f2/a4f0/4ad3-89bf-90c539fa734f/08dfe850-06a7-4f83-a530-04c8e3a40bc7_corrected.mpd)
00:08:58.683 T:19092   ERROR: CVideoPlayer::OpenInputStream - error opening [https://a184avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/1b5c/52f2/a4f0/4ad3-89bf-90c539fa734f/08dfe850-06a7-4f83-a530-04c8e3a40bc7_corrected.mpd]
00:08:58.683 T:19092  NOTICE: CVideoPlayer::OnExit()
00:08:58.683 T:19256   ERROR: Playlist Player: skipping unplayable item: 0, path [https://a184avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/1b5c/52f2/a4f0/4ad3-89bf-90c539fa734f/08dfe850-06a7-4f83-a530-04c8e3a40bc7_corrected.mpd]
00:08:58.685 T:19256  NOTICE: CVideoPlayer::CloseFile()
00:08:58.685 T:19256  NOTICE: VideoPlayer: waiting for threads to exit
00:08:58.685 T:19256  NOTICE: VideoPlayer: finished waiting
00:08:58.685 T:19256  NOTICE: CVideoPlayer::CloseFile()
00:08:58.685 T:19256  NOTICE: VideoPlayer: waiting for threads to exit
00:08:58.685 T:19256  NOTICE: VideoPlayer: finished waiting
`

**Comment by peak3d** [comment]
you have to:

- activate inputstream.adaptive
- create a strm file

#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
[your URL]

and play this file.
Why? You have to tell kodi, that you want to use inputstream.adaptive for playback.
