### ISSUE TITLE
Android (esp. Nvidia Shield) - Seeking causes video freeze

### ISSUE THREAD

**Issue by popy2k14** [peak3d/inputstream.adaptive#785]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying a seek during video playback of the pvr zattoo addon, the video freezes in-place and stays stuck. Sometimes it will skip to correct place, but can be up to a 20+ second delay. Other times the skip doesn't complete and Kodi must be force-closed. Most of the time, audio playback is running but picture freezes.

There is a similar issue here: xbmc/xbmc#19713
and here: https://github.com/rbuehlma/pvr.zattoo/issues/126
(where we already talked about this issue)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Picture should not freeze.

## Actual Behavior

Picture freezes on seeking.

## Possible Fix

no

### To Reproduce

What i have done is:
1. Factory reset shield tv pro 2019
2. Install kodi 19.1
3. Install zattoo pvr addon and set it up
4. enable debug log and exit
5. restart kodi
6. started ORF1 and seeked 1 minute backwards -> picture freezed, audio was running
7. switched to Pro7 and seeked 1 minute backwards -> picture freezed, audio was running

### Debuglog

The debuglog 2.6.15 can be found here: https://paste.kodi.tv/xezuwinewi.kodi
Sadly kodi has'nt updated IA when i made the log.
After that i realised that. Can provide an log with 2.6.23, if needed.
Just let me know.

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9
 - Kodi version: 19.1
 - inputstream.adaptive version: 2.6.15 & newest 2.6.23

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment]
please get a new log with latest Inputstream Adaptive 2.6.23

Also, could you see if either of these IA builds fix the issue
They are suitable for Kodi 19 on Nvidia shield

1) https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-761/13/artifact/cmake/addons/build/zips/inputstream.adaptive+android-aarch64/inputstream.adaptive-2.6.22.zip
or
2) https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-784/1/artifact/cmake/addons/build/zips/inputstream.adaptive+android-aarch64/inputstream.adaptive-2.6.23.zip

**Comment by popy2k14** [comment]
Here are logs with the various versions.
Sadly, non of them fixes the issue.

2.6.23 kodi repo version: https://paste.kodi.tv/ijoxirexib.kodi
PR-761: https://paste.kodi.tv/racedonucu.kodi
PR-784: https://paste.kodi.tv/mujiguhaqe.kodi

I did exactly the same as stated above (rewind 1min) -> picture freezes, audio running.
Can you please look at the logs.

**Comment by Maven85** [comment]
@popy2k14 I have the same problems with my Shield.

With #737 everything is fine again. Can you confirm it?
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-737/5/artifact/cmake/addons/build/zips/inputstream.adaptive+android-aarch64/inputstream.adaptive-2.6.23.zip

**Comment by popy2k14** [comment]
@Maven85 
Thanks for comming back to me here.

Do you had exactly the same issue as me: Rewind on stream causes picture to freeze, but audio keeps playing?

Will try to get my hands on soon and will post my results.

**Comment by Maven85** [comment]
@popy2k14 
> Do you had exactly the same issue as me: Rewind on stream causes picture to freeze, but audio keeps playing?

Yes, that was my problem too.

**Comment by popy2k14** [comment]
@Maven85 
I tried the PR 737 build but that hasn't solved the issue.
Here is the Log: https://paste.kodi.tv/uyihirelul.kodi

**Comment by Maven85** [comment]
@popy2k14 
Okay, it's the same problem, but maybe different causes.
I ran into the problem with Amazon VOD.

**Comment by kontell** [comment]
I've got the issue with seeking backwards during livestreams only. Forwards works fine and both work for on demand content.

It occurs in both Matt's Sky Sport Now addon and the YouTube addon. A workaround for SSN is to toggle the audio setting "Allow passthrough". This doesn't work for YT but changing the video stream does.

The issue is on a Shield Pro, I have an FTV4K with an identical setup that doesn't have the poblem. Attached are logs for both addons with the workaround included.

[SSN_kodi.log](https://github.com/xbmc/inputstream.adaptive/files/7251344/SSN_kodi.log)
[YT_kodi.log](https://github.com/xbmc/inputstream.adaptive/files/7251345/YT_kodi.log)

**Comment by popy2k14** [comment]
Can we provide anything else to help identify and solve the issue?

thx

**Comment by glennguy** [comment]
Hi @popy2k14 
This hasn't been mentioned in any of the linked issues but I found this:
https://github.com/xbmc/xbmc/issues/19436
https://forum.kodi.tv/showthread.php?tid=362500
This is making me think the issue has nothing to do with inputstream.adaptive.

Next steps for you would be to find a video with AAC audio to play locally and see if the seek issue is there.

**Comment by popy2k14** [comment]
Tried several video files with AAC locally, seeking works on all of them.
Also an recording of zattoo downloaded locally -> works, but not with zattoo pvr addon, picture freezes after seeking.

**Comment by phunkyfish** [comment]
@glennguy if the local files play ok does this mean the issue is in adaptive?

**Comment by glennguy** [comment]
Yes it seems so
Sorry @popy2k14 for not following through.
Popy2k14 - are you seeing the same behaviour in the YouTube add-on as another user mentioned above? Would be great if you could check as we can all access YouTube

**Comment by popy2k14** [comment]
@phunkyfish and @glennguy thx for comming back to this issue.

@glennguy yes, i can test youtube addon, maybe today or tomorrow.
Will come back here with the results.

**Comment by popy2k14** [comment]
@glennguy 
Tested youtube addon (man that's a pain to setup) on the shield with 19.3 release.
It runs flawlessly, tested 1080p and 4k both with AAC Audio.
Forward and rewind has no issue, fast and snappy as it should and no freezing picture.

After the testvideos i have played one channel from zattoo, which freezed picture after rewind a few minutes.
Here is the log: https://paste.kodi.tv/ijinaxuhey.kodi

Please note, audio is still running, just picture frozen. When i let it run a few seconds (~30) then one new picture will be shown but also frozen. Before the new picture an kodi "loading" cicrle is shown. Dont know if this helps to identify the issue.

PS.: Just to rule out any network/zattoo issue. The android Zattoo app is running with 1080p streams flawlessly since months. Also when i do my tests, i always shut down kodi after picture freeze and do the same test in the native zattoo app (watching same channel, rewind and see if it works) -> it does work all the time, Also my wife is the best tester for TV -> zattoo native app -> she says, it just works.

**Comment by kontell** [comment]
@popy2k14 can you confirm you were using inpustream with the YouTube addon. As in, "MPEG-DASH" within the YT addon settings was enabled and you tested it with a live stream. Thanks.

**Comment by popy2k14** [comment]
@kontell
On my first test (with the log above) sadly MPEG-DASH was not enabled. Redid my test now with MPEG-DASH enabled with the same Videos.

Same results, Youtube is working with videos.
Also tried live stream in YT but could not rewind at all. But the stream was playing.

I can upload the new log tomorrow, if needed.

**Comment by kontell** [comment]
On demand videos work fine for me in YT as well. 

I think the lack of rewind is because in the MPEG-DASH section of the YT addon settings you need to have "Use for live streams" checked.

**Comment by glennguy** [comment]
Ok, I can see what's happening in the log now. Will investigate properly tonight after work but the video segment that is seeked to is the wrong one (~3 seconds too far)

**Comment by popy2k14** [comment]
I can redo some tests if needed, just come back to me. Nice that you see the zattoo issue in the logs.

If I can help any further, just let me know.

**Comment by popy2k14** [comment]
@glennguy did you found the issue? Please do not hurry, i am not using kodi as my main system currently. But i am also interested in your findings. If i can help in any way (do some more tests, just let me know).

thx a lot

**Comment by glennguy** [comment]
Not yet, I ran out of time last night but will try again tonight

**Comment by popy2k14** [comment]
take your time!

**Comment by glennguy** [comment]
Still havent found time but @popy2k14 are you able to test if this issue is present on Windows? If so regardless of outcome could you provide a debug log? 
There's so much conflicting information in this and the other threads, I suspect there's 2 or more different issues that are being conflated into the one, and I'd like to solve your specific issue first.

**Comment by popy2k14** [comment]
@glennguy 
Done the tests on an Windows 10 21H1 machine + kodi 19.3 + zattoo and all addons up-to-date.

In windows, all is working like it should!

Here are the results:
dash selected in zattoo addon: https://paste.kodi.tv/dibaniveki.kodi
dash widevine  selected in zattoo addon: https://paste.kodi.tv/ifequneniw.kodi

I think you are right, but the title of my issue nails it down to android :-)

Hope you can find the issue in the logs.

**Comment by glennguy** [comment]
I think I'm on the right track, just need more time to put into this. I have a couple more pull requests to make which I'm just about done developing then I can concentrate on this.

What I've found is in here (some lines removed for readability):
```
2021-08-31 20:34:08.078 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: PosTime (10728150)
2021-08-31 20:34:08.354 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10728.2) for Stream:1 continues at 10726.4 (PTS: 1630434771240000)
2021-08-31 20:34:08.461 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10726.4) for Stream:2 continues at 10726.4 (PTS: 1630434771221333)
2021-08-31 20:34:08.576 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10726.4) for Stream:3 continues at 10726.4 (PTS: 1630434771200000)
2021-08-31 20:34:08.814 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10728.2) for Stream:1 continues at 10729.6 (PTS: 1630434774440000)
2021-08-31 20:34:08.911 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10729.6) for Stream:2 continues at 10729.6 (PTS: 1630434774421333)
2021-08-31 20:34:09.029 T:11585    INFO <general>: AddOnLog: inputstream.adaptive: seekTime(10729.6) for Stream:3 continues at 10729.6 (PTS: 1630434774400000)
```

Relevant code:
https://github.com/xbmc/inputstream.adaptive/blob/1d8877960ccf33f423b6d18ee6f9456fc9301fc8/src/main.cpp#L3072-L3110

What's happening in this part is:
* Kodi asks IA to seek to a certain spot
* IA then iterates over the currently enabled streams and asks them to advance to the requested time (i.e move to the correct segment)
* Then seek to the requested time *within* the segment

What stands out to me is that although we're playing 1 * video, 1 * audio, and 1 * subtitle streams, they're all done twice here. Between the 1st and second rounds of seeking we end up with different results, doesn't seem right... Perhaps inbetween (~600ms from first seekTime to 6th) the stream is being read by Kodi and we've advanced into a new segment, or maybe seeking on the spot is causing this. Will need to investigate more.

**Comment by popy2k14** [comment]
Thanks for looking into it.
Sounds reasonable that the wrong seeking time and diff between seeks is part of the issue.
Take your time.

**Comment by glennguy** [comment]
@popy2k14 can you please try the appropriate zip from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-848/1/artifacts

**Comment by kontell** [comment]
Tried the above on Nexus with YouTube and got the same behaviour. Video freezes after skipping back in a live stream and manually changing the video stream jogs it back into life.
[YT_kodi.log](https://github.com/xbmc/inputstream.adaptive/files/7675705/YT_kodi.log)

**Comment by glennguy** [comment]
thanks @kontell 

I think the above zip will help in some situations like the zattoo add-on but not 100% of the time anyway, it will only mask the problem.

I've managed to narrow the issue down some more and am investigating. Thanks to being able to reproduce the cause in the youtube addon I think I'll be able to fix it. The same behaviour can be observed in Windows 10 where the audio and video streams download different segments after seek (misaligned by 1) however Kodi in win 10 doesn't care and plays back fine. Problem is that sometimes on seek they do line up - I can make a change that reverses this situation (most of time lines up) but really we need a 100% fix.

**Comment by popy2k14** [comment]
@glennguy thx for your efforts. i can test the above test build in the evning (~about 6h). Will come back here.

**Comment by popy2k14** [comment]
@glennguy same issue with the above build (like @kontell with youtube addon).

Here is the log : https://paste.kodi.tv/liqacuxudi.kodi

**Comment by glennguy** [comment]
@popy2k14 @kontell 
I hope the latest change resolves this issue for you: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-848/2/artifacts

I'm making a big assumption that the issue it fixes is what you're seeing. In any case the work isn't without use, ISA has been seeking to the wrong audio segment in many cases.

**Comment by popy2k14** [comment]
@glennguy 
Sadly, with the addon build, the issue is the same on the zattoo addon side.
here is the log: https://paste.kodi.tv/ijozikirel.kodi

**Comment by glennguy** [comment]
That's a shame, thanks for your continued patience and testing.

**Comment by glennguy** [comment]
@popy2k14 I don't know if it will help but are you able to get a logcat from your shield for this issue? I say this because of this line in the log `CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)`
If the log can show the exception which caused Kodi to write this line then we may be able to continue progress

**Comment by popy2k14** [comment]
@glennguy no problem. Because of the WAF is curently high without kodi, i have no pressure from this side :-) and can give you logs as you need them.

Have made another test with kodi (switching to three different channels and rewind a few seconds).
Also made a logcat for you.

Kodi log: https://paste.kodi.tv/uxarunamiv.kodi
Logcat from shield (cutted to the runtime of kodi, because otherwise it would be to big): https://paste.kodi.tv/imulakekuv.kodi

Hope you can see something in there.

**Comment by glennguy** [comment]
Nothing that helps in there I'm sorry but I'm reproducing the issue on my Pixel 3 here, so might be a whole of Android thing.
I'll have to figure out an easy way to start debugging on Android.

**Comment by popy2k14** [comment]
Yeah, I also saw nothing intetessting in the logcat.
Are you able to reproduce the issue on your pixel? That would make things a lot easier.

**Comment by glennguy** [comment]
Yes, seeking in YouTube live streams causes a picture freeze, never recovers. Other strange behaviour happens but I'm sure it's all linked to the video freeze.

**Comment by popy2k14** [comment]
Nice that you can reproduce the issue.
If you need anything, just let me know.
Also for testing, i am here.

**Comment by popy2k14** [comment]
@glennguy 
Did you found the root cause of the issue?

Ps.: Again, i DONT want to put any pressure in this, because we dont use kodi anymore. I am just interessted in the technical cause and want to give the kodi community something back :-)

**Comment by glennguy** [comment]
Not yet, I haven't looked at this since last time but plan to again this week.

**Comment by popy2k14** [comment]
ok, thx for the update. Just ping me if i can help.

**Comment by matthuisman** [comment]
This may be worth a try

https://github.com/xbmc/xbmc/issues/19436#issuecomment-1002958894

**Comment by popy2k14** [comment]
Tested the build on my shield tv pro with latest inputstream.adaptive 19.0.1 and test build from above -> same issue after seeking backwards.

**Comment by glennguy** [comment]
@popy2k14 I've spent a lot of my spare time this week on this issue, think I'm getting pretty close. I can say fairly certainly though that the issue isn't with inputstream.adaptive.

One thing I can get you to check for me - does this problem happen for you when watching non-live/VOD streams? I've found it's fine when you start from the beginning, but if you resume then there's issues when seeking.

**Comment by kontell** [comment]
I've got the same behaviour for VOD with Sky Sport Now, skipping back is a problem only when video is resumed.

**Comment by popy2k14** [comment]
@glennguy THANKS A LOT FOR YOUR TIME AND FINDINGS!!!!!
Will do a test with youtube soon.

When i got you right, my tests are:
Starting an video from beginning letting it run for an minute and rewinding should work.
But start an video in the middle (with resume) and then rewind should not work.

Right.

Is it possible to make an test build of kodi nexus or leia for androud arm64?
So i can test that with the "problematic" zattoo addon too.

thx a lot

**Comment by popy2k14** [comment]
@glennguy i can 100% confirm your findings.

Issue pop's up when:

- playing live VOD (zattoo, Youtube, ...) and rewind
- playing NOT live VOD (zattoo, Youtube, ...) and start with "resume" at an position and then reqind

IT does NOT come up when:

- Playing VOD from the beginning and then rewind.

So i think your findings with the missing set variable hopefully solves the issue.

If you can provide android arm64 test builds (nexus or matrix) i can test them.

**Comment by glennguy** [comment]
I've got a Matrix build to try, it won't install over the top of an official build as it's signed with a different key.
https://drive.google.com/file/d/16VfHcj44Krut2Jqu8valkalIlAv8D6LI/view - arm64 btw

**Comment by phunkyfish** [comment]
> I've got a Matrix build to try, it won't install over the top of an official build as it's signed with a different key.
> https://drive.google.com/file/d/16VfHcj44Krut2Jqu8valkalIlAv8D6LI/view - arm64 btw

Or create a PR to get the test builds from Jenkins.

**Comment by popy2k14** [comment]
@glennguy tested your build and it works as it should on zattoo (recordings, live, ...), youtube (live & not live).
I think you found and fixed the issue!

thx a lot

**Comment by popy2k14** [comment]
Fixed with referenced PR's.
Thx again.

**Comment by glennguy** [comment]
@popy2k14 thanks for regularly nudging me on this one and your relentless testing and supply of logs :) and thanks too @kontell -  we got there in the end!

**Comment by popy2k14** [comment]
@glennguy no problem. Nice that you found and solved the issue! It seems it also fixes other open issues (VC1 seeking...) :-)
