### ISSUE TITLE
Unable to play Dash .mpd file

### ISSUE THREAD

**Issue by qutub11** [peak3d/inputstream.adaptive#788]
Dash ".mpd" links are not playing

#m3u

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://mrpw.ptmnc01.verspective.net/?deviceId=ZGFkZmZkZjItYzQ1Mi0zM2RiLTk0OWQtM2M2YmY1YzZjMDNi||R{SSM}|
#EXTINF:-1 group-title="MOVIES" tvg-logo="https://www.dropbox.com/s/pv8jri42pg1bva2/zing.jpg?dl=1", ZING
https://liveanevia.mncnow.id/live/eds/Zing/sa_dash_vmx/Zing.mpd

**Comment by matthuisman** [comment]
https://liveanevia.mncnow.id/live/eds/Zing/sa_dash_vmx/Zing.mpd = 404 not found

that is not an issue with Inputstream Adaptive.

**If you have any future issues, please open a new issue and follow the template.
You must provide debug logs etc or won't get any assistance.**
