### ISSUE TITLE
android + kodi + netflix plugin = something doesn't work

### ISSUE THREAD

**Issue by aintnogeek** [peak3d/inputstream.adaptive#79]
I have problem, that looks like inputstream.adaptive level

ERROR: CDVDVideoCodecAndroidMediaCodec::AddData error(-10000)

So I get black screen and no audio and video, but kodi thinks that video is going fine.

Any directions what should I do?

Here is also full log
[newKodi.log](https://github.com/peak3d/inputstream.adaptive/files/1347529/newKodi.log)

**Comment by anthonws** [comment]
I guess that I have the same issue as you.

I'm using a ASUS Transformer Prime (yes I know, a relique :) ) with Android 7.1 (KitKass ROM), and latest master from Kodi ARM 32-bit.

Netflix plugin works properly but whatever I try to play, there's no image or sound. Although if I touch the screen, Kodi will show me the movie controls (play, stop, etc) and also shows that the timer is counting.

There's some refresh oddities when I touch the screen. I can stop the stream and play another one but it will never show me image or reproduce sound.

I can play Netflix via the official app just fine.

Please advise if you need further logs or tests on my end!

Thank you,
anthonws.
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/1359562/kodi.log)

**Comment by peak3d** [comment]
Netflix requires HDCP for high resolution streams (HD + IIRC)
Pls. try to play lower resolution streams

**Comment by aintnogeek** [comment]
changing resolutions doesn't work... didn't managed to reply and you closed issue.

can you please look in detail about this error there are many users who would be happy to get this working.

**Comment by peak3d** [comment]
You'll find the reason in logcat most probably.
- adb logcat -c
- start video
- adb logcat -d | pastebinit

**Comment by aintnogeek** [comment]
Can throw some link how to do this?.

Do you need fresh kodi log?

**Comment by peak3d** [comment]
if you are connected to your device, the commands above should work.
Pls. refer to adb android documentation and how to use.

**Comment by aintnogeek** [comment]
OK I will check that.

Can you tell which video plugin of kodi also use inputsteam.adaptive, so I could check does It have same error?

**Comment by peak3d** [comment]
amazon (sandmann) / netflix (asciidisco) for example

**Comment by FFY00** [comment]
@peak3d it this working with kodi v17?

**Comment by peak3d** [comment]
@FFY00 no, netflix / amazon only K18
