### ISSUE TITLE
new update of widevine CDM doesn't play DRM streams through KODI - armv7 - enigma 2

### ISSUE THREAD

**Issue by lasmalein** [peak3d/inputstream.adaptive#794]
enigma2 linux-based receivers have the same issue of not being able to play drm protected streams.

 I can't stream content via Kodi and the DAZN addon, as I've seen there is an update of widevine library and it's not compatible with ARM devices. The new library is 4.10.2252.0

disney+ still works fine with the deprecated library

.2252 Widevine CDM doesn't work with armv7  enigma2 receiver

https://paste.kodi.tv/uqoheludum.kodi

**Comment by atvcaptain** [comment]
here now working see my last post : https://www.opena.tv/allgemeine-image-informationen/51181-kodi-18-7-mit-widevine-87.html#post483804

updates soon for all arm models with kodi support

**Comment by lasmalein** [comment]
I have a zgemma h9.2h with openatv 7.0beta. Kodi is 19.1 matrix

How can I apply this patch?

**Comment by lasmalein** [comment]
> here now working see my last post : https://www.opena.tv/allgemeine-image-informationen/51181-kodi-18-7-mit-widevine-87.html#post483804
> 
> updates soon for all arm models with kodi support

Is there a script I can use to patch my image? I have openatv 7.0 beta zgemma h9.2h

**Comment by matthuisman** [comment]
This is not an inputstream adaptive issue.
And it's also a duplicate: https://github.com/xbmc/inputstream.adaptive/issues/678

Please close and follow up with your os
