### ISSUE TITLE
mpd fails to parse with '&' in initialization

### ISSUE THREAD

**Issue by gerion0** [peak3d/inputstream.adaptive#795]
### Describe the bug
I'm currently trying to generate a mpd manifest on my own to combine a video stream and an audio stream.
While doing so, it seems that inputstream.adaptive fails to parse mpd files, if a `&` is contained within the link.

Here is a minimal example. The following file is parsed successfully:
```
<?xml version="1.0"?>
<MPD type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation>
  <Title>blabla</Title>
 </ProgramInformation>

 <Period start="PT0S">
  <AdaptationSet>
   <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
   <ContentComponent id="1" contentType="audio" />
   <SegmentTemplate startNumber="1" initialization="http://localhost/foo.webm?blablub"/>
   <Representation id="blabla" mimeType="audio/webm" codecs="opus">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
Kodi log output:
```
2021-09-11 01:34:07.064 T:12919    INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 1, Type: VOD, Download speed: 0.0000 Bytes/s
```

The following file fails to parse:
```
<?xml version="1.0"?>
<MPD type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation>
  <Title>blabla</Title>
 </ProgramInformation>

 <Period start="PT0S">
  <AdaptationSet>
   <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
   <ContentComponent id="1" contentType="audio" />
   <SegmentTemplate startNumber="1" initialization="http://localhost/foo.webm?bla&blub"/>
   <Representation id="blabla" mimeType="audio/webm" codecs="opus">
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
(The difference is only the `&` within the link.)
Output in the log:
```
2021-09-11 01:33:39.906 T:12748   ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (http://localhost:10010/test.mpd)
```

## Expected Behavior
Links containing `&` should be parsed as well.

## Actual Behavior
Error in parsing.

## Possible Fix
Fix the parsing code?

### To Reproduce

1. Put the above mpd file somewhere on a web server.
2. Feed the link into inputstream.adaptive.

### Debuglog
See above.

### MPD/M3U8s/ISM
Already provided.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: 19.1
 - inputstream.adaptive version: 2.6.23

**Comment by matthuisman** [comment]
**& is a special character in xml ...
Url encode it.**

Please close the issue
Please also try a bit of googling next time :)

**Comment by gerion0** [comment]
Sorry, haven't thought about this. You're right of course. (My googling has always contained the keywords Kodi/inputstream/mpd so it doesn't lead to a result.)
