### ISSUE TITLE
Stops playing after 4 seconds

### ISSUE THREAD

**Issue by dev77-07** [peak3d/inputstream.adaptive#805]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to play a Discovery+ m3u8 file, it plays the first 4 seconds and then stops playing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play entire video

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amutoqaziq.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[Main m3u8 file](https://paste.kodi.tv/ogutopaqeg)
[3840x2160 f.m3u8](https://paste.kodi.tv/xocasawevo)
[Audio a.m3u8](https://paste.kodi.tv/ukafecived)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

If I use ffmpeg on the command line with the main m3u8 file and tell it copy the audio and video, the output file plays fine, so not sure why it's failing through inputstream adaptive in kodi.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 20 nightly
 - inputstream.adaptive version: 20.0.0

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment]
.m4f files = fragmented mp4
which we do support with Dash files (pretty much all dash use it)

we check for supported HLS file extensions here:
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/src/parser/HLSTree.cpp#L481
m4f  isn't there, so it will default to CONTAINERTYPE_INVALID

maybe we just need to treat m4f as mp4...
ill get you a PR to test (for kodi 19 only)

UPDATE:
try a build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-806/1/artifacts

**Comment by glennguy** [comment]
I don't think that will change anything for this situation. Container type would be set to MP4 already because of the init segment


@yeahme49 it would be useful to see an entire log not just a snippet. Also can see that you might be using the up next add-on, please disable or uninstall it. Better yet, see if this happens in a clean installation.

**Comment by dev77-07** [comment]
Here is a new log file https://pastebin.pl/view/a223e4f8 (too large for paste.kodi.tv). Fresh Kodi 19.1 install using the test build of ISA. I also enabled some component-specific logging, not sure if that helps or not.

Had the same issue with the test build, stops after 4 seconds. It's also playing the 640x360 file instead of 4k so I must have something configured wrong in this fresh install of Kodi.

I have an experimental option enabled in Discovery+ that requests H265 video, which allows up to 4k videos. With that option disabled it uses H264 and it works fine, just no 4k option. So the issue doesn't just affect 4k through D+ it's any H265 video though D+.

**Comment by glennguy** [comment]
@yeahme49 thanks for the log.

It's possible beyond my capabilities to solve this one, and there's only so much to find in a log file. If there was a non-DRM publically available stream to test which has the same attributes and reproduces the same problem it would help a lot.

**Comment by dev77-07** [comment]
I was able to pass along an enable DRM parameter which then provides an mpd file instead of m3u8 from discovery+. When trying to play this version, kodi just spins and spins.

Debug log https://paste.kodi.tv/xonisamemi.kodi

I see some Decrypt failed with error: 2. Not sure if that is causing the file to not play or if that error is normal. What does error: 2 mean?

https://paste.kodi.tv/adewujiloc here is what the mpd file looks like

**Comment by CastagnaIT** [comment]
> I have an experimental option enabled in Discovery+ that requests H265 video, which allows up to 4k videos. With that option disabled it uses H264 and it works fine, just no 4k option. So the issue doesn't just affect 4k through D+ it's any H265 video though D+.

from what i know the widevine library for windows not support H265/HEVC streams
you can use it on Android only

**Comment by glennguy** [comment]
Some recent context for this:
https://bitmovin.com/google-adds-hevc-support-chrome/
Note they also mention no HEVC support for DRM yet.
