### ISSUE TITLE
1080 plays choppy

### ISSUE THREAD

**Issue by gregoir3** [peak3d/inputstream.adaptive#81]
When I try to play a netflix vid on my libreelec box, Leia alpha build for s905x, it plays out of sync, choppy and occasionally the sounds quits too. I've tried every setting to make it work somehow but to no avail.
I noticed though (thanks to processor info) that of the 4 cores randomly only 2 hit high loads (up to 100%). I wondered if it was this that made playing 1080p fail.

**Comment by pszafer** [comment]
I have similar issue on Odroid C2 with LibreElec. Kodi v18

**Comment by peak3d** [comment]
This is a question / issue wich has to be discussed with google (libwidevine).
I have not found any way to use more than one core for the decoding stuff in there.
