### ISSUE TITLE
Addon works fine in Windows and does not work in Android

### ISSUE THREAD

**Issue by mtr81** [peak3d/inputstream.adaptive#812]
I wrote simple addon video for Kodi 19.1 to watch online tv CSTAR (content protected DRM)
The problem is that in Windows 10 addon works fine, but in Android (tested in ver 6 and 7) doesn't work. 
Error: license server send response without key. From logs I see that the difference is in content-length sended to license server - in Windows: 3219 bytes, in Android only 803 bytes.

Addon's code:

```
import os
import sys

import urllib
import requests
import xbmc
import xbmcgui
import xbmcplugin
import xbmcaddon
import xbmcvfs
import urllib3
import re
import json
import time
import random
import math
try:
    from urllib.parse import urlencode, quote_plus, quote
except ImportError:
    from urllib import urlencode, quote_plus, quote
    
try:
    import http.cookiejar as cookielib
except ImportError:
    import  cookielib

base_url = sys.argv[0]
addon_handle = int(sys.argv[1])
params = dict(urllib.parse.parse_qsl(sys.argv[2][1:]))
addon = xbmcaddon.Addon(id='plugin.video.canalplus_fr')

mode = addon.getSetting('mode')

def build_url(query):
    return base_url + '?' + urllib.parse.urlencode(query)

def add_item(ch_name, ch_id):
    li=xbmcgui.ListItem(ch_name)
    li.setProperty("IsPlayable", 'true')
    li.setInfo(type='video', infoLabels={'title': ch_name,'sorttitle': ch_name,'plot': ''})
    url_ch = build_url({'mode':'play','channel':ch_id})
    xbmcplugin.addDirectoryItem(handle=addon_handle, url=url_ch, listitem=li, isFolder=False)

channels = [
    ['CSTAR','cstar','']
] 

def channels_gen():
    for ch in channels:
        add_item(ch[0], ch[1])
    xbmcplugin.endOfDirectory(addon_handle)

def PlayStream():
    def rnd():
        return str(hex(math.floor((1+random.random())*9007199254740991)))[4:]
    ts= int(1000*time.time())

    deviceKeyId = str(ts)+'-'+rnd()
    deviceId = deviceKeyId + ':0:' + str(ts+2000)+'-'+rnd()
    sessionId = str(ts+3000)+'-'+rnd()

    #print(deviceId)
    #print(sessionId)

    data={
        "deviceId": deviceId,
        "sessionId": sessionId,
        "vect": "INTERNET",
        "media": "PC",
        "portailId": "vbdTj7eb6aM.",
        "zone": "cpfra",
        "noCache": "false",
        "analytics": "true",
        "trackingPub": "true",
        "anonymousTracking": "true"
    }

    cookies={
        "deviceId": deviceId,
        "sessionId": sessionId
    }

    hdr={
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "pl,en-US;q=0.7,en;q=0.3",
        "Connection": "keep-alive",
        "Content-Length": "227",
        "Content-Type": "application/x-www-form-urlencoded",
        "Host": "pass-api-v2.canal-plus.com",
        "Origin": "https://www.canalplus.com",
        "Referer": "https://www.canalplus.com/",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "cross-site",
        "TE": "trailers",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0"
    }
    
    resp = requests.post('https://pass-api-v2.canal-plus.com/services/apipublique/createToken',data=data,headers=hdr)
    passToken = json.loads(resp.text)['response']['passToken']
    #print(passToken)

    data={
        "ServiceRequest": {
            "InData": {
                "DeviceKeyId": deviceKeyId,
                "PassData": {
                    "Id": 0,
                    "Token": passToken
                },
                "PDSData": {
                    "GroupTypes": "1;2;4"
                },
                "UserKeyId": "_pmofzprqf"
            }
        }
    }

    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    try:
        requests.packages.urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST += 'HIGH:!DH:!aNULL'
    except AttributeError:
        # no pyopenssl support used / needed / available
        pass
    resp = requests.post('https://secure-webtv.canal-plus.com/WebPortal/ottlivetv/api/V4/zones/cpfra/devices/3/apps/1/jobs/InitLiveTV',json=data,headers=hdr)
    liveToken = json.loads(resp.text)['ServiceResponse']['OutData']['LiveToken']
    #print(liveToken)
  
    data_drm=quote('{"ServiceRequest":{"InData":{"ChallengeInfo":"b{SSM}","DeviceKeyId":"'+deviceKeyId+'","EpgId":513,"LiveToken":"'+liveToken+'","Mode":"MKPL","UserKeyId":"_pmofzprqf"}}}')
    #print(data_drm)
  
    url_stream = 'https://dsh-m002.live-lv3.canalplus-cdn.net/live/disk/cstar-hd/dash-fhddvr/cstar-hd.mpd'
   
    import inputstreamhelper
    
    PROTOCOL = 'mpd'
    DRM = 'com.widevine.alpha'
    LICENSE_URL = 'https://secure-webtv.canal-plus.com/WebPortal/ottlivetv/api/V4/zones/cpfra/devices/31/apps/1/jobs/GetLicence'
    is_helper = inputstreamhelper.Helper(PROTOCOL, drm=DRM)
    
    
    if is_helper.check_inputstream():
        play_item = xbmcgui.ListItem(path=url_stream)
        play_item.setInfo(type="Video", infoLabels={"title": ''})
                     
        play_item.setMimeType('application/xml+dash')
        play_item.setContentLookup(False)
        if sys.version_info >= (3,0,0):
            play_item.setProperty('inputstream', is_helper.inputstream_addon)
        else:
            play_item.setProperty('inputstreamaddon', is_helper.inputstream_addon)
        
        play_item.setProperty("IsPlayable", "true")
        play_item.setProperty('inputstream.adaptive.manifest_type', PROTOCOL)
        play_item.setProperty('inputstream.adaptive.license_type', DRM)
        play_item.setProperty('inputstream.adaptive.license_key', LICENSE_URL+'||'+data_drm+'|JBLicenseInfo')        

    xbmcplugin.setResolvedUrl(addon_handle, True, listitem=play_item)


mode = params.get('mode', None)
action = params.get('action', '')

if action=='play':
    PlayStream()
else:

    if not mode:
        channels_gen()

    elif mode == 'play':
        PlayStream()
```
EDIT:
Here is Kodi logs:
- for Android: [https://pastebin.com/Z7Ur6jQd](https://pastebin.com/Z7Ur6jQd)
- for Windows 10: [https://pastebin.com/9wvY02cU](https://pastebin.com/9wvY02cU)

**Comment by glennguy** [comment]
Not really an inputstream.adaptive problem but I'll give some help.
You should be able to see the challenge and response files, they're located in the "profile" / cdm folder (%appdata%\Kodi\cdm by default on Windows, not sure off the top of my head on Android):
![image](https://user-images.githubusercontent.com/11909320/134997342-58cd4003-c600-49b3-b4aa-01d64d55c524.png)

The response file might have some info on why you're not getting keys.

**Comment by mtr81** [comment]
On Android device I have also file .post which includes request data where key "ChallengeInfo" have value "CAQ=".  CHALLENGE file is empty . There are some differences in data INIT files.

**Comment by glennguy** [comment]
CAQ= (\x08\x04) is used by the cdm to get a certificate... my memory is not 100% but it's used on other platforms for VMP. On Windows it will send the CAQ= challenge first to get the certificate back, then send the actual challenge next. This can be seen when using a browser or another player which is VMP certified. Kodi will definitely not do this on non Android platforms.

What you really need to do is hook your android device up to mitmproxy or similar and see what the canal+ android app is doing. Things should become clearer then.

**Comment by mtr81** [comment]
@glennguy thanks for your help
I found that license server need to certificate, so I added to code:

```
import base64
certificate_data = base64.b64encode(requests.get('https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin').content).decode('utf-8')
```
and then in ISA section:
`play_item.setProperty('inputstream.adaptive.server_certificate', certificate_data)`

In this way plugin works on Android device now.

BTW. I will close issue soon, but can you tell me how it's possible that on windows streaming run without certificate data?

**Comment by mtr81** [comment]
Problem solved.

**Comment by glennguy** [comment]
> but can you tell me how it's possible that on windows streaming run without certificate data?

I could be incorrect about these details but Windows/Linux/macOS are limited to L3 (usually 720p), and this doesn't require certificates/signing. The Kodi executable is not signed with google's cert (this is what Verified Media Path is about) unlike Chrome/Firefox/Edge etc. and doesn't try to perform the certificate exchange as the CDM knows it's not signed.

**Comment by ayoubcr5** [comment]
> @glennguy thanks for your help I found that license server need to certificate, so I added to code:
> 
> ```
> import base64
> certificate_data = base64.b64encode(requests.get('https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin').content).decode('utf-8')
> ```
> 
> and then in ISA section: `play_item.setProperty('inputstream.adaptive.server_certificate', certificate_data)`
> 
> In this way plugin works on Android device now.
> 
> BTW. I will close issue soon, but can you tell me how it's possible that on windows streaming run without certificate data?

hey ,
thank you for this one
can you please show me how to do it in php or javascript 
how to get correct license challange from 'https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin'

**Comment by ayoubcr5** [comment]
> Problem solved.
hey ,
thank you for this one
can you please show me how to do it in php or javascript
how to get correct license challange from 'https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin'

**Comment by mkorganashvili** [comment]
> The Kodi executable is not signed with google's c

do you mean, that windows does not need certificate?
