### ISSUE TITLE
[Kodi 20] Video stops after about one minute

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#818]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I start a video with Ntfx add-on the playback stops after about one minute.
Ref. https://github.com/CastagnaIT/plugin.video.netflix/issues/1237

I mentioned the problem here #773, and have now opened an Issue to keep track of the problem

---

Here i report some investigations of @glennguy (answer on first comment):

From looking at the log when the switch occurs this happens in the log `AddOnLog: inputstream.adaptive: WVDecoder initialization returned status 3`

Status 3 is `kInitializationError`

Perhaps this may be related to the new pre init workflow you implemented? Maybe the init data is only making its way through for the initial stream? Just thinking out aloud here, haven't looked into it.

### To Reproduce

1. Install Ntfx and play a video

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ajesoyeyoc.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Last kodi 20 nightly
 - inputstream.adaptive version: self builded form Nexus branch and also last released

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> Perhaps this may be related to the new pre init workflow you implemented? Maybe the init data is only making its way through for the initial stream? Just thinking out aloud here, haven't looked into it.

I can say this, "preinit" should takes place before any other drm initialisation, with single execution only,
i.e. should happens before other operations to start the video, not afterwards (as an example switch stream) is only intended to allow the add-on to download the manifest

when it happen we can find this line:
`DEBUG <general>: AddOnLog: inputstream.adaptive: Session::PreInitializeDRM - Initializing session with KID`
in the log there is only a single line of this, so it continues to be a single execution as it should
the session used for the video stream is different from the one opened/closed by the "preinit"

as confirmation i tried disabling PreInit on Net***x, but the problem still persist
log with preinit disabled: https://paste.kodi.tv/umedaniqom.kodi

**Comment by glennguy** [comment]
The issue I think is around NF using AnnexB/secure path and VideoCodec to pass data to Kodi as that is where the `kInitializationError` message is coming from.

I've come up with issues when using AnnexB with multiple periods. As the transition to a new period begins with the stream change signal, the decoder is reset and a new data is fed into Kodi. However, the content from the period that is ending is still trying to use the decoder. The end result in this scenario is the picture freezes some seconds before the original period ends.

In this case here it's very similar except within the same period. Perhaps though without a new period to keep things going, Kodi sees no more picture data and halts playback?

It's not an issue when VideoCodec is not in use. Unfortunately I know very little of how this works on Kodi's side.

As I don't have a NF sub, can I ask what happens in v19 if you have streams selection set to manual and you change streams?

**Comment by glennguy** [comment]
It may or may not be possible to solve in IA only. My gut feeling at the moment about why it's failing is that widevinecdm doesn't like us calling `InitializeVideoDecoder` when already initialized (would need to deinitialize first but what happens to undecoded content?)

If a quick solution can't be found, then maybe we consider an option to disable stream switching.

**Comment by CastagnaIT** [comment]
Unfortunately, i am unable to help in this
but i can try to ask who could help with kodi devs

> If a quick solution can't be found, then maybe we consider an option to disable stream switching.

I think that in any case it might be a good idea to add this option, in two ways, something like this:
-set it by ListItem (addon choice)
-set it by ISA settings (user choice, but overrided by addon choice)

**Comment by CastagnaIT** [comment]
> As I don't have a NF sub, can I ask what happens in v19 if you have streams selection set to manual and you change streams?

On Kodi 19 when i select another video stream manually, the video image freezes permanently, the sound is regular
https://paste.kodi.tv/ovecihihuz.kodi
(same problem happen on kodi 18)

**Comment by glennguy** [comment]
Hmm same cause, slightly different effects - either way you can't continue watching.

Btw an outstanding issue is that 'manual' stream selection in v20 doesn't stop the automatic switching, however you can see all video streams in the OSD and change manually, just that it will be overridden. Should be just a case of passing in another variable to AdaptiveStream constructor.

Agree that we can have to the options, just that addon should be able to override auto -> manual but not manual -> auto.

**Comment by glennguy** [comment]
My brief analysis is:
In this function here https://github.com/xbmc/inputstream.adaptive/blob/359e8854d258d5a8a1d93cd4025a4654b80e6feb/src/main.cpp#L4014 we refer to the decrypter here https://github.com/xbmc/inputstream.adaptive/blob/359e8854d258d5a8a1d93cd4025a4654b80e6feb/src/main.cpp#L4049-L4050 which is session wide.  If we want this to work it looks like we'll need more than 1. I haven't looked but I wonder if chrome or some other player would show how they handle it.
I've seen an example in Android playing music using the MediaPlayer class, creating a new instance for the next track and swapping them when playback of the next track is due to start - otherwise gapless playback would be impossible. Maybe that approach could work for us?

**Comment by CastagnaIT** [comment]
i have tried limit the bandwidth via software to try emulate different situations with webbrowser video playback but nothing of useful happen lost the buffering only without a real stream switching in realtime, i think the network speed is verified in a different way, also i do not see any widevine reference in the website log, i do not know how i can help
maybe your proposal to use different sessions will work
if there are no other solutions you can try

**Comment by glennguy** [comment]
@CastagnaIT looking at this now. I can get stream switching happening without playback stopping on the parkour widevine test stream. I'm forcing it to use Annex B / Crypto session and the picture freezes but comes back after some seconds. The video decoder initializes properly (returns 0)

I was having a look at the cdm headers and it has this to say about your return code 3:
```
// Returns kInitializationError if |video_decoder_config| is not supported.
// The CDM may still be able to do Decrypt().
```

I'm now thinking that the issue of the stream stopping / return code 3 is not to do with VideoCodec, but maybe the initialisation data that comes back into IA being wrong.

I remember reading somewhere that NF addon generates its own MPDs, and obviously it works fine for the representation that's opened initially... I'm pretty sure the video codec init data all comes from whats parsed from the mpd and then set in `Session::UpdateStream` so maybe something unexpected or wrong is happening here.

**Comment by CastagnaIT** [comment]
Yes you remember correctly, NF addon generate the MPD manually via proxy
this is an example:
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7317857/manifest.mpd.txt)
that has been converted from ntfx manifest:
[manifest.json.txt](https://github.com/xbmc/inputstream.adaptive/files/7317858/manifest.json.txt)

if you need to make some changes or add data you can do so

**Comment by glennguy** [comment]
Hey thanks for the examples.

A couple of observations:
* the representation ids would normally be unique, I think it would only cause issues with live updates (Does NF even have live streams?) but you could try to use `downloadable_id` instead
* The SegmentBase indexRange - it doesn't look right, looking at the source this is being calculated based on the content duration. This attribute is wanting to see the location of the SIDX atom, so should be in the attached example I think `1846-20886`. However, this seems to be corrected for anyway in `parseIndexRange`...

Maybe next steps would be to capture the initData going into `CVideoCodecAdaptive::Open`

**Comment by CastagnaIT** [comment]
thank you i will correct the wrong data

**Comment by CastagnaIT** [comment]
i have tried do the changes, and test it on Kodi 19, but Kodi crash without stacktrace
https://paste.kodi.tv/ufuwapewob.kodi
[manifest.json.txt](https://github.com/xbmc/inputstream.adaptive/files/7327845/manifest.json.txt)
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7327847/manifest.mpd.txt)

**Comment by glennguy** [comment]
I think the problem now becomes narrowed down, something incorrect must be happening in DASHTree.cpp

Stream 1006 is the video stream, that opens fine, correct range is downloaded: `Range: bytes=1846-20886`

Stream 1010 is audio and also opens correctly with the byterange in the manifest: `Range: bytes=861-43309`

~~But then stream 1028 is opened which is the text track according to url, and `Range: bytes=39910-41184` - we should just be downloading the whole vtt file right?~~ - was wrong on this one, the url being downloaded after this log line is for the video stream

As it happens 39910 is in the json as `startByteOffset` for the video tracks.

I can't do without NF access but you could try setting a sleep statement here: https://github.com/xbmc/inputstream.adaptive/blob/17165e4eff776679e94a60add524cdf43446a4b8/src/common/AdaptiveStream.cpp#L705

i.e
```
if (current_rep_->flags_ & AdaptiveTree::Representation::SUBTITLESTREAM)
      std::this_thread::sleep_for(std::chrono::seconds(10));
```
and set a breakpoint straight after. This will allow time to attach the debugger, and you won't cause a crash as long as the code doesn't hit anything that touches the cdm. ~~You can then step through prepareDownload and see why `rangeHeader` is being set for this representation and hopefully work backwards from there.~~ not the issue

**Comment by CastagnaIT** [comment]
please write to me a message on Kodi slack
so i can identify you

**Comment by CastagnaIT** [comment]
Your new changes to the SegmentBase has worked now the playback starts (on Kodi 19)
try recheck if the new mpd data is ok:
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7335672/manifest.mpd.txt)
[manifest.json.txt](https://github.com/xbmc/inputstream.adaptive/files/7335673/manifest.json.txt)
https://paste.kodi.tv/okiyizuniy.kodi

On Kodi 20 still crash as before

**Comment by CastagnaIT** [comment]
Thanks to investigate in this,
i will test the proposed changes in next days to make sure that there are no others problems

**Comment by CastagnaIT** [comment]
No problems in last 2 days, then i close the issue
