### ISSUE TITLE
[Android] Kodi 17 DASH/Widevine playback issue

### ISSUE THREAD

**Issue by glennguy** [peak3d/inputstream.adaptive#82]
Hi @peak3d 

I'm having some difficulty with playback on Kodi 17 in Android. Kodi 18 works perfectly well, in 17 the picture is garbled and with no sound.

[kodi18.log](https://github.com/peak3d/inputstream.adaptive/files/1364222/kodi18.log)
[kodi17.log](https://github.com/peak3d/inputstream.adaptive/files/1364223/kodi17.log)

I've compiled 2.0.18 from the Krypton branch and the issue still persists.

This is a test .strm file that you can test with a VPN exiting in Australia:
```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://wvlic.brightcove.com/proxy/5591550453001|Content-Type=application%2Fx-www-form-urlencoded|A{SSM}|
https://yahoo7pdash-a.akamaihd.net/2376984108001/2376984108001_5591568985001_5591550453001.mpd
```

Here is the mpd:
[2376984108001_5591568985001_5591550453001.txt](https://github.com/peak3d/inputstream.adaptive/files/1364574/2376984108001_5591568985001_5591550453001.txt)

I compiled a debug version and got the challenge/response/init files in case they're helpful:
[files.zip](https://github.com/peak3d/inputstream.adaptive/files/1364575/files.zip)

Let me know if you need any more information.

Thanks for all the great work you do!

**Comment by JinRonin** [comment]
Thats how it is. Android requires kodi 18 for drm playback. A backport is not possible.

**Comment by glennguy** [comment]
@JinRonin I think you're thinking about the situation with Netflix where decrypting AND decoding is required to be done with inputstream.adaptive. The content that I am trying to get working afaik does not require the secure decoder. Asides from that, wvdecrypter_android.cpp is still being maintained in the Krypton branch - if Kodi 17 on Android could not support any form of widevine decryption then I would think this file would not exist in the Krypton branch.

**Comment by JinRonin** [comment]
see:
https://forum.kodi.tv/showthread.php?tid=303609&pid=2561554#pid2561554

**Comment by glennguy** [comment]
I believe the part about backporting not being possible was referring to the huge changes to the inputstream interface that happened in the kodi-agile branch. Did you read my previous post?

**Comment by Displayel** [comment]
can you guys help me how do i update the kodi inputstream addon on my nvidia firetv to the latest one ? when i try to install this one there is an error message..trying on kodi 17.4

**Comment by peak3d** [comment]
pls update your kodi apk. inputstream.adaptive is bundled with kodi

**Comment by glennguy** [comment]
@peak3d is there any comment on the issue re Widevine not decoding
correctly on Kodi 17 on Android?

**Comment by peak3d** [comment]
@glennguy sure, for android decryption there are massive changes to transport encrypted frames into kodi core. This was first done in kodi-agile, which was later merged into k18 development tree.

These changes will never ever be backported, there are thousend lines of code + api changes.
Even if I wanted to backport, the team will never allow.

**Comment by glennguy** [comment]
@peak3d ah ok. I was only confused as I thought that there was some point to having wvdecrypter_android.cpp in the Krypton branch and seeing some of the changes in master still being backported to it recently (for example at https://github.com/peak3d/inputstream.adaptive/commits/Krypton/wvdecrypter/wvdecrypter_android.cpp)

Just to make it clear - the content I'm trying to play doesn't require the secure decoder like Netflix/Amazon, just to decrypt.

**Comment by peak3d** [comment]
For android there is no way to "decrypt only" and pass decrypted frames to kodi.
Android (implementation) allows only one way: pass encrypted frames to kodi and let mediacodec / mediacrypto do the rest. And this is only available in K18 and kodi-agile.

So: no way for drm encrypted content android + K17.x

**Comment by glennguy** [comment]
Perfect, thanks for the detailed explanation :)
