### ISSUE TITLE
[Dash] Tries to play vod from -22:04:40

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#821]
Trying to play the attached manifest and kodi tries to start playback at -22:04:40
If i seek, it'll just then jump to 00:00:00 and start playing.
Also the total time then gets corrected (2nd screenshot)
Or if I set resume from 1 on starting playback.

Seems maybe the total time is being calculated wrong?
Or the manifest is bad?
Maybe there is something we can do to ensure we always play vod from 00:00:00

[starts_at_negative_22_04mins.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7343526/starts_at_negative_22_04mins.mpd.txt)

![screenshot00000](https://user-images.githubusercontent.com/6225961/137263645-883f0eb1-0f31-4d89-a9df-babe45ac1c18.png)
![screenshot00001](https://user-images.githubusercontent.com/6225961/137264221-da708188-b3e3-4e8f-80a5-0dddd3461853.png)

**Comment by CastagnaIT** [comment]
can you say if the problem occurs on Kodi 20?

**Comment by matthuisman** [comment]
this is in the HULU addon. 
I dont think i've got a valid hulu login at present so may not be able to confirm unfortunately.

**Comment by CastagnaIT** [comment]
so for now i close issue
if the problem will be shown in future on Kodi 20 we will see what to do

**Comment by matthuisman** [comment]
Yes. That is fine :) thank you
