### ISSUE TITLE
[Kodi 20] Seek foreward/backward cause image freeze strange behaviours

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#828]
### Describe the bug
Here is a clear and concise description of what the problem is:

I was testing webvtt but the playback of the sample video not works good
so when you seek foreward/backward cause image freeze in apparence is possible that something wrong happen with stream buffering (instead in Kodi 19 is played correctly)

It is not a kodi problem because if on kodi 20 i replace ISA files with the ISA files of Kodi 19 version the playback works without problems

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Open 
[_TestISOWebVTTStream2.strm.txt](https://github.com/xbmc/inputstream.adaptive/files/7360125/_TestISOWebVTTStream2.strm.txt)

2. Seek foreward
3. Seek backward

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/minekaniho.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Latest kodi 20 nightly + Kodi 19
 - inputstream.adaptive version: master branch

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Yep can see here too.

One thing I've noticed is the connection speed on this stream is very unstable, looking at the logs my first suspicion is that ISA wants to finish the download queue before continuing with the task of seeking. Will look properly later today/tonight

**Comment by Mannshoch** [comment]
For the record: https://github.com/xbmc/inputstream.adaptive/pull/30

**Comment by CastagnaIT** [comment]
i close this since now works correctly
