### ISSUE TITLE
clean the dependencies

### ISSUE THREAD

**Issue by remitamine** [peak3d/inputstream.adaptive#83]
i think that some of the dependencies can be limited to certain platforms or removed.
i tested to build(`Krypton` branch as i still use the official archlinux build(17.4)) on linux x64 system without `kodi-platform` and `p8-platform` and the addon works fine(removed `find_package(kodiplatform REQUIRED)` and `find_package(p8-platform REQUIRED)` and related INCLUDE_DIRS and checked that the packages are not installed in the system).
`kodi-platform`: i didn't find it used at all.
`p8-platform`: i see that it's used only for windows in https://github.com/peak3d/inputstream.adaptive/blob/master/src/main.cpp#L42.
i would've sent a PR, but i can't test on other platforms(windows) and architectures(arm).

**Comment by peak3d** [comment]
thx, done

**Comment by remitamine** [comment]
thanks, is it possible to back-port this change to the `Krypton` branch?

**Comment by peak3d** [comment]
Yep, there is some other stuff I'll have to backport today, I'll include this
