### ISSUE TITLE
[Kodi20] Play non-DRM video sometimes freeze or other side effects (100mb lan)

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#830]
### Describe the bug
Here is a clear and concise description of what the problem is:

Mainly happens to me when i use my HTPC on the 100mb Lan,
and i play Netfx non-DRM videos, like the trailers

an example in the ntfx addon with "Dear mother" trailer:
Menu "news and popular" --> "coming next week" -->click on "Dear mother"

There are two different behaviours that happen to me
**case 1)** The video is played, but after some seconds or first minute, the `DEMUX_SPECIALID_STREAMCHANGE` log appears, then the streams are resetted including subtitles streams, that cause kodi to disable the subtitles currently displayed on screen. Here the video is played, but the subtitles are disabled without reason due to `DEMUX_SPECIALID_STREAMCHANGE`.

**case 2)** [of attached logs] The video freeze just after start the playback and `DEMUX_SPECIALID_STREAMCHANGE` log appears in the log, no chance to see the video, only press stop and try again.

BUT if i try play the same trailer on my pc connected to 1gb Lan, all works as expected,
also here suggest something related to the ISA buffering problem,
maybe similar or same issue of #828 but i have opened another Issue because in the other one i have not see the `DEMUX_SPECIALID_STREAMCHANGE` in the log.

the DRM streams works good without problems also on 100mb lan,
with Kodi 19 OFC there are no playback problems

On kodi side this `DEMUX_SPECIALID_STREAMCHANGE` callback should better handled to restore subtitles when this happens (or should be handled in other way), or every time subtitles are suddently disabled, it is not nice that it disables subtitles for no reason, i know this is a known problem, but i underline it to keep note

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Hope in a future stable playback :) and/or a feature to disable adaptive streams switching if it is a long term solution

### To Reproduce

1. ntfx addon
2. Go to menu "news and popular" --> "coming next week" -->"Dear mother" (click on it to play trailer)

### Debuglog

The debuglog can be found here:
log of "Dear mother" trailer:
https://paste.kodi.tv/nuyiboveme.kodi
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7373608/manifest.mpd.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Last in master branch K20 self builded
 - inputstream.adaptive version: Last in Nexus branch self builded

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Thanks @CastagnaIT for all the details

I'm doing my best to simulate a slow connection on my Win 10 box by forcing the network adapter to 10Mbps Half Duplex, seems to work as speedtest on my 100Mbps internet connection gives ~7Mbps now. 

With case 1 I can't reproduce the subtitle issue. I'm using the current ISA Nexus head build and Kodi 20211014-02b20967d0. One small modification is to modify this section here https://github.com/xbmc/inputstream.adaptive/blob/c08955927f2aabdd1521bcb0ae070ac23b69d504/src/main.cpp#L2043-L2057
to always set `bandwidth_` to 300000. The stream will always start at a low resolution to make testing easier. With testing this I would get multiple stream changes within a short time (segments seem to only be a second or two long, at least at the start of the video).

I had noticed previously that with multi-chapter/period content that I'd have to manually re-enable subtitles when a new period would start. To do with default settings maybe?

On case 2 I can't repro either. Do you have a log for that scenario? Are you able to repro on your 1000Mbs machine with the above mentioned change to the network adapter?

Btw is your HTPC box Win 10 as well?

**Comment by CastagnaIT** [comment]
i think these problems are highlighted because i have a very long lan cable like 10/15 metres (mt) because wifi is not stable (due to wide walls and many devices connected in my family) then it is possible that the lan signal is not always constant with the bandwidth

> I had noticed previously that with multi-chapter/period content that I'd have to manually re-enable subtitles when a new period would start. To do with default settings maybe?

i am not sure in what you are referring to...

> On case 2 I can't repro either. Do you have a log for that scenario? Are you able to repro on your 1000Mbs machine with the above mentioned change to the network adapter?

yeah the attached log above is for the "case 2" (HTPC) but the freeze not happens always usually happens the "case 1", i will try to see if i can get a second log with the freeze.

If i force 100mb/lan to my PC i cannot reproduce the problem, i think because is near the router with a short cable,
but,
If i force 10mb/lan to my PC strange things happens with the buffering in the first seconds, the video trailer starts badly seem kodi/ISA they fight to try buffering in an intermittent way, but after about 10 second the buffer starts to stabilise and is played in good way

i have the suspect that "bandwidth.bin" is used as base to start to choose the initial stream bandwidth, also in subsequent video playbacks,
if so, it wrong to store this data and reuse it on next played video,
there is no certainty that that bandwidth is currently available, thus you falsifying the correct initial buffering,
I think that starting buffering always from a low-bandwidth stream is the best way,
i am thinking for example of use with mobile network or also wifi network, or case when the wired network is unstable.

i want to give you some info that i have found a few years ago, which might be of interest to you, concerns the functioning of stream adaptive:

https://www.diva-portal.org/smash/get/diva2:507848/FULLTEXT01.pdfA
(section: design and implementation -> client -> adaptation mechanisms)
Here they talk about also of an "aggresive" way where start playing the video with the lowest quality stream and then increase it as soon as you have the bandwidth data or a kind of.

https://www.cs.princeton.edu/courses/archive/fall16/cos561/papers/NetFlix12.pdf
(section "CDN selection strategy")
talk about in how netfx switch the streams in realtime.

**Comment by glennguy** [comment]
Thanks for those links, they look like very good resources!

> i am not sure in what you are referring to...

Just wondering out aloud if the subtitles disappearing is related to the default setting for whether subtitles are enabled or not.

You're correct about bandwidth.bin
I think there would be good use cases for it though - what about channel surfing IPTV? You might not want every stream to start at 320x180. It could be better to have it as a setting?
We could do as you suggest but there'd need to be some work done with being more aggressive in changing the buffer. On stream start the buffer fills up before checking whether the stream should switch. It's ok with short segment lengths but the services that have 6s lengths can wait up to a minute for the first switch.

**Comment by CastagnaIT** [comment]
> Just wondering out aloud if the subtitles disappearing is related to the default setting for whether subtitles are enabled or not.

in my tests if i remember correctly if subtitles are enabled automatically by kodi setting or manually via GUI while watching and DEMUX_SPECIALID_STREAMCHANGE happen, the subtitles become disabled suddently in any case (so when this happen if you open the GUI you can see the subtitles disabled, then you have to re-enable it, in the log you can see that the subtitle stream has been resetted and the kodi sub-parser have to re-parse again whole subtitles stream again)

i did not go in detail on how all things are handled when DEMUX_SPECIALID_STREAMCHANGE happen, at moment i can only say what i can see. The DEMUX_SPECIALID_STREAMCHANGE implementation on Kodi seem also a bit old and initially for PVR purpose?
maybe some changes are needed, @AlwinEsch has done some changes in this interface in the past maybe can he provide some more info on how works

> You're correct about bandwidth.bin
I think there would be good use cases for it though - what about channel surfing IPTV? You might not want every stream to start at 320x180. It could be better to have it as a setting?

heh good example yes we have to thing a better management
Some time ago i found a document that explained how works the "instant stream playing" but i thing i have not saved the link or i lost it...could be useful in this i will try make a search if i find it again

**Comment by CastagnaIT** [comment]
i close this issue since we have solved differents problems
between DEMUX_SPECIALID_STREAMCHANGE behaviour
drm reinit and netf@x case
