### ISSUE TITLE
[Dash] Live stream 'craziness' due to audio tracks(s)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#832]
Same provider, ESPN and ESPN2.
(slyguy proxy off or on same issue)

ESPN2 - no issues

ESPN will either
start at negative time with audio but no video
or
start at a time above end of stream with audio but no video

With either, if you seek fwd or back - the image will come back but no audio.
Also, if you try to ffwd to live edge - the stream will stop like it think it's the end.

If i set IA to Video only - it correctly starts at live head with no timeline weirdness
If I set IA to Audio only - it correctly starts at live head with no timeline weirdness 

So only issue when using both Video & Audio
Both ESPN and ESPN2 manifests attached as well as screenshots.
they are very similar so hopefully that can help us find the different and narrow down issue

I also had some Hulu live channels that would play at live head OK, but no audio.
The "fix" for those was to make Hulu only return a single audio track.
I suspect that could be related to this.
This issue could be related to https://github.com/xbmc/inputstream.adaptive/issues/821

[espn-2-GOOD.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7385513/espn-2-GOOD.mpd.txt)
[espn-channel-BAD.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7385514/espn-channel-BAD.mpd.txt)
[espn-2-GOOD-less-logging.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7393206/espn-2-GOOD-less-logging.mpd.txt)
[espn-channel-BAD-less-logging.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7393208/espn-channel-BAD-less-logging.mpd.txt)
**(both the above were generated about 2 seconds apart)**

[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/7384853/kodi.log.txt)

![screenshot00002](https://user-images.githubusercontent.com/6225961/138183880-4872052c-bdb3-4819-9567-926b6b36e7a1.png)
![screenshot00003](https://user-images.githubusercontent.com/6225961/138183876-d7ce9913-5f18-425b-8a46-f00d647d6778.png)

**Comment by matthuisman** [comment]
Possibly this is fixed with pr
https://github.com/xbmc/inputstream.adaptive/pull/913

**Comment by CastagnaIT** [comment]
it doesnt happen anymore?

**Comment by matthuisman** [comment]
Have not checked yet. It's not using relative urls so I suspect will still
have issue. I'll try check over next few days

**Comment by matthuisman** [comment]
closing this as that channel now works fine both on kodi 19.4 and 20.
so maybe it was a problem with the manifest and they have fixed
