### ISSUE TITLE
Support for Microsoft playready for clarovideo

### ISSUE THREAD

**Issue by diegofn** [peak3d/inputstream.adaptive#833]
## Bug report

Hello 
I am trying to load the following content
https://latamvosliveclarovideo.akamaized.net/Content/DASH_DASH_FK/Live/Channel(WINPREMIUM)/manifest.mpd

It is blocked for the Kodi agent so I wrote the following code:

```
# Create the listitem
list_item = self.xbmcgui.ListItem(path=media_url + '|User-Agent=' + USER_AGENT)
list_item.setProperty('inputstream.adaptive.license_type', 'com.microsoft.playready')
list_item.setProperty('inputstream.adaptive.server_certificate', server_certificate);
list_item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
list_item.setProperty('inputstream', 'inputstream.adaptive')
list_item.setMimeType('application/dash+xml')
list_item.setContentLookup(False)
```

### Describe the bug
But I don't get the stream, the inputstream for Microsoft playready need the license_key? When we open the URL in my browser web player it doees not request certificate and license.

Thanks for your help

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Open https://www.pirlotv.fr/canal-46.php and check if it works
2. Run the code on Kodi that I put above

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.2
 - inputstream.adaptive version: 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Hi @diegofn 

Playready isn't supported in this addon on platforms other than Android. Windows support is possible in the future but as it stands at the moment, OSX would not be possible. The service should provide a widevine option.
