### ISSUE TITLE
[Windows] Formal Releases

### ISSUE THREAD

**Issue by fruch** [peak3d/inputstream.adaptive#84]
I'm trying to get this pluging for windows kodi version,
and seems the only way is to compile it from source.

I've also see you have appvoer builds for windows, can those you publish those artifacts ?
(doing a setup for installing kodi from source could take me a while...)

**Comment by pinoelefante** [comment]
this plugin is installed with kodi. you don't need to install by your own

**Comment by fruch** [comment]
in which versions?

**Comment by pinoelefante** [comment]
kodi 17.4 and above and kodi 18

**Comment by glennguy** [comment]
@fruch by default it is disabled. Got to addons > my addons >videoplayer inputstream and enable from there.
