### ISSUE TITLE
Kodi 19: mpd subtitles doesn't always work on discovery+

### ISSUE THREAD

**Issue by Dis90** [peak3d/inputstream.adaptive#855]
### Describe the bug

Subtitles on some videos on discovery+ doesn't work properly in Kodi 19.

Here is a clear and concise description of what the problem is:

Every line is displayed as iden1, iden2 and so on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles to display properly.

## Possible Fix

Latest InputStream Adaptive on Kodi 20 on macOS displays subtitles properly. But latest ISA version available on Kodi nightly ppa (20.0.2) has same problem.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Not working: https://paste.kodi.tv/raw/olimogisaw
Working: https://paste.kodi.tv/wamikiyore.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Not Working: [master.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7705843/master.mpd.txt)
Working: [master2.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7705902/master2.mpd.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

<img width="1176" alt="Screenshot" src="https://user-images.githubusercontent.com/1754572/145863724-3f5ba360-8dcb-496c-a95d-ab4419b1e258.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19
 - inputstream.adaptive version: 19.0.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> Latest InputStream Adaptive on Kodi 20 on macOS displays subtitles properly. But latest ISA version available on Kodi nightly ppa (20.0.2) has same problem.

ISA ver 20.0.2 not include the use of the new webvtt parser, then not works
you have to install the 20.0.3 version on both your systems with Kodi 20
or manually build it/install it from Nexus branch

The webvtt parser of ISA used in Kodi 19 is very unstable
i will try to see if i can do something

**Comment by CastagnaIT** [comment]
@Dis90 please do a test, you can download ISA zip test builds from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/3/artifacts/
(for Kodi 19)

**Comment by Dis90** [comment]
Unfortunately no change. Still iden1, iden2... :(

**Comment by CastagnaIT** [comment]
ah my fault i have solved in wrong way...

**Comment by CastagnaIT** [comment]
hi @Dis90 new build please test it: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/9/artifacts
(for Kodi 19)

**Comment by Dis90** [comment]
Tested and now subtitles works. Huge thanks :)

**Comment by dudumaroja** [comment]
> hi @Dis90 new build please test it: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/9/artifacts (for Kodi 19)

where i can find a rpi4 build for testing?

**Comment by CastagnaIT** [comment]
for rpi you have to build ISA yourself to match your device architecture

**Comment by CastagnaIT** [comment]
Fixed by #857
