### ISSUE TITLE
Videos Enter Hyperspeed after Buffer Empties

### ISSUE THREAD

**Issue by david-morris** [peak3d/inputstream.adaptive#863]
### Describe the bug
When the buffer runs empty, the video plays "catch up" and the audio skips.  But that is undesirable behavior.

## Expected Behavior

I would like the video and audio to resume at normal playback speed from where the buffering began.

## Actual Behavior

Once buffering is completed, the video speed runs somewhere around 16x speed until caught up. Meanwhile, the audio skips ahead such that it continues smoothly with the video once caught up.  This has three undesirable effects:

- I do not clearly see the video which is played quickly
- I do not hear the audio which is skipped
- the buffer that was just replenished is now immediately low again.

## Possible Fix

I can see how this could be desirable for live events.  But it probably shouldn't be default, and really should not be default for non-live streams.  It would be nice to have this as a configurable switch.

### To Reproduce

1. Install kodi Youtube addon, enable inputstream adaptive for 4k 60Hz videos
2. Throttle your internet, for example by switching to 2.4ghz wifi on a busy channel
3. Load a big bad 4k@60Hz video that's long enough that you'll run out of buffer

### Debuglog

The debuglog can be found here:
https://pastebin.com/myBsqz2z

### MPD/M3U8s/ISM

https://pastebin.com/N3f8TtSA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `Linux tinkerbell 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux`
 - Kodi version: Matrix 19.3
 - inputstream.adaptive version: arch repos community/kodi-addon-inputstream-adaptive 19.0.0-5

**Comment by matthuisman** [comment]
i see this same behaviour on local media if it buffers over wifi.
Also same behaviour when streaming content that isnt using inputstream adaptive

Therefore I dont think this is an Inputstream Adaptive issue

(You've also not supplied a full debug log)

**Comment by david-morris** [comment]
> Also same behaviour when streaming content that isn't using inputstream adaptive

Good point, I only noticed that after posting.  Inputstream.adaptive was my only way of getting videos which used enough bandwidth to trip over their buffer for a while.

> Therefore I don't think this is an Inputstream Adaptive issue

Yeah, seems like it's likely the video player itself, do you have the ability to move this issue to xbmc/xbmc or should I copy it?

> You've also not supplied a full debug log

Okay.  Is this a matter of logs from before the video being chosen being potentially useful, or the loglevel being too low?  If it's the loglevel, since this is a transient issue, is there any way to set the loglevel without getting the debug HUD?

**Comment by matthuisman** [comment]
you'll need to close this issue and then create a new one on xbmc/xbmc
They will require full debug logs etc

**Comment by david-morris** [comment]
Misfiled, moving to xbmc/xbmc
