### ISSUE TITLE
About release/tags 

### ISSUE THREAD

**Issue by kyrios123** [peak3d/inputstream.adaptive#87]
How come I see the version numbers are bumped (last is 2.0.18) in the code and/or commit messages while the last release/tag is still 2.0.10 ?

I am asking because most Linux distributions uses the release tarballs to build their packages.
Also for some reason, the v2.0.10 fails to build on my machine while the 2.0.18 works just fine.

Thanks!

**Comment by flak3** [comment]
yeah this really doesn't make any sense, would be nice if you could tag it

**Comment by dagwieers** [comment]
@peak3d I see newer tags now so this is probably no longer relevant. Close it?
