### ISSUE TITLE
Nexus - Archlinux - template issues in AdaptiveTree.h

### ISSUE THREAD

**Issue by ilikenwf** [peak3d/inputstream.adaptive#871]
I'm unable to build for Kodi 20 under Archlinux due to this template issue:

```
inputstream.adaptive-20.1.0-Nexus/src/common/AdaptiveTree.h:40:12: error: missing template arguments before ‘(’ token
   40 |   SPINCACHE() :basePos(0) {};
      |            ^
```

**Comment by CastagnaIT** [comment]
i think it is missing the template argument
please apply this diff in your local source code:

```c++
diff --git a/src/common/AdaptiveTree.h b/src/common/AdaptiveTree.h
index a73c668..77e0e5c 100644
--- a/src/common/AdaptiveTree.h
+++ b/src/common/AdaptiveTree.h
@@ -37,7 +37,7 @@ namespace adaptive
 template<typename T>
 struct ATTR_DLL_LOCAL SPINCACHE
 {
-  SPINCACHE() :basePos(0) {};
+  SPINCACHE<T>() : basePos(0){};
 
   size_t basePos;
 
```

recompile and let me know

**Comment by ilikenwf** [comment]
I tried, no such luck. Could it be a verisioning or ABI issue since Arch tends to run bleeding edge versions of packages sometimes? I had to downgrade python already to keep certain plugins from crashing.

```
AdaptiveTree.h:40:18: error: expected ‘}’ before ‘:’ token
   40 |   SPINCACHE<T>() : basePos(0){};
      |                  ^
```

**Comment by ilikenwf** [comment]
Clang gives possibly more useful output:

```
 error: use of variable template 'SPINCACHE' requires template arguments
  SPINCACHE() :basePos(0) {};
```

**Comment by CastagnaIT** [comment]
could be a problem of the compiler version used but i am not so expert on linux
maybe someone else can help you

**Comment by ilikenwf** [comment]
I suspect that I have an old version of the kodi dev libraries. Going to try updating those.

**Comment by ilikenwf** [comment]
Yep, that was it.
