### ISSUE TITLE
Failed to download video segment

### ISSUE THREAD

**Issue by Mariusz89B** [peak3d/inputstream.adaptive#874]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playback stalls after couple minutes of watching stream from https://pilot.wp.pl/tv/ 

Video segment failed to download:
`AddOnLog: inputstream.adaptive: Download failed with error 403: https://stream-cdn-1.videostar.pl/263/smil:premium/segment_7c4f870e2_ctvideo_cfm4s_ridp0va0br2200000_cs7038710595450_mpd.m4s`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normal playback.

## Actual Behavior

Stream stalls.

## Possible Fix

Not entirely sure if I'm missing something out, the license and stream url seems fine as the playback starts.

### To Reproduce

Inputstream settings:
https://github.com/Mariusz89B/script.mtvguide/blob/1141504175cf825640b32410ff5ab79cc7e36687/playService.py#L1119-L1135

Stream url and license:
https://github.com/Mariusz89B/script.mtvguide/blob/1141504175cf825640b32410ff5ab79cc7e36687/wppilotcids.py#L294-L296

JSON response, for stream url and license:
```json
{
   "data":{
      "mux_enabled":false,
      "stream_channel":{
         "url_base":"",
         "channel_name":"Disney Channel",
         "streams":[
            {
               "balance":"50/50",
               "quality":"AUTO",
               "type":"dash@live:abr",
               "url":[
                  "https://stream-cdn-1.videostar.pl/263/smil:premium/manifest.mpd?t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&t5=&device=android_tv&type=premium&ts=9f30babc688838360cf9bf06ae1b9593f0dffc6b45d4b7185050f6c3e6091d3e",
                  "https://stream-cdn-2.videostar.pl/263/smil:premium/manifest.mpd?t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&t5=&device=android_tv&type=premium&ts=9f30babc688838360cf9bf06ae1b9593f0dffc6b45d4b7185050f6c3e6091d3e"
               ]
            },
            {
               "balance":"50/50",
               "quality":"AUTO",
               "type":"hls@live:abr",
               "url":[
                  "https://stream-cdn-1.videostar.pl/263/smil:premium/playlist.m3u8?t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&t5=&device=android_tv&type=premium&ts=359e333efa23a27baf302f263a14d501d01000548437c24dc70072e7503364e3",
                  "https://stream-cdn-2.videostar.pl/263/smil:premium/playlist.m3u8?t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&t5=&device=android_tv&type=premium&ts=359e333efa23a27baf302f263a14d501d01000548437c24dc70072e7503364e3"
               ]
            }
         ],
         "drms":{
            "fairplay":"/api/v1/drm/fairplay?t1=263&t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&ts=0d26627c69479515842738be6ca4bd9bb5f1814569d643c5b1ef7f8093620939",
            "playready":"/api/v1/drm/playready?t1=263&t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&ts=ddc87a8a35cd46a1124e9bb07f5513a8f4536ba157312b8972cdd619803e5015",
            "widevine":"/api/v1/drm/widevine?t1=263&t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&ts=c72b9afa432d787157daa7852682b84f3f0f2d0a185a86de172dc52121ece13e"
         }
      }
   },
   "_meta":"None"
}
```

### Debuglog

The debuglog can be found here:
https://drive.google.com/file/d/1HTxma3Rn7f6cyqWc2wwJj5Xsu4EwyPxL/view?usp=sharing

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://stream-cdn-1.videostar.pl/263/smil:premium/manifest.mpd?t2=I2kwMqctuWSWylxRtTObS8aRREsXSEGn&t3=ec2a102ab36948cc9e303ddce900444c&t5=&device=android_tv&type=premium&ts=9f30babc688838360cf9bf06ae1b9593f0dffc6b45d4b7185050f6c3e6091d3e

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro 21H2 22000.376
 - Kodi version: Kodi (20.0-ALPHA1 (19.90.101) Git:20220102-527ee4b524). Platform: Windows NT x86 64-bit
 - inputstream.adaptive version: 20.1.0

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
Thanks for all the details!
Usually this happens because there's some cookie or other header, or url parameter that changes after a few minutes. Nothing to do with the license in this case.
I'd suggest looking at how the official app for this service behaves for some clues.
The solution for you would involve running a local proxy to modify what's needed, many add-ons have to do this.

**Comment by Mariusz89B** [comment]
@glennguy Thank you for your suggestions, the url in deed changes after couple of minutes.
