### ISSUE TITLE
Could not locate inputstream.adaptive.so.2.1.5

### ISSUE THREAD

**Issue by oyviaase** [peak3d/inputstream.adaptive#88]
I, am unable to play videos from youtube and netflix, the main error message that I get is:

`12:11:25.070 T:140592533206784   DEBUG: ADDON: Dll Initializing - InputStream Adaptive
12:11:25.070 T:140592533206784   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.1.5
12:11:25.070 T:140592533206784   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
12:11:25.070 T:140592533206784   ERROR: CVideoPlayer::OpenInputStream - error opening [https://manifest.googlevideo.com/api/manifest/dash/ip/77.106.147.107/ei/bGj4Wd2AKa7p7gTwo7vYCA/expire/1509473484/key/yt6/itag/0/playback_host/r1---sn
-xpqnp85-vnal.googlevideo.com/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear/initcwndbps/1400000/ipbits/0/signature/A9176D300A0C9DA8537967C9F2110BD3184280E9.43778E4E11EEA44F6040C606604A706081D6BD6E/sparams/as%2Cei%2Cgcr%2Chfr%2Cid%2Cinitcwndbps
%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/id/a5fd6dedcb3d7647/hfr/1/mn/sn-xpqnp85-vnal/mm/31/source/youtube/mv/m/mt/1509451760/ms/au/gcr/no/pl/18/requiressl/yes]`

For the full log se [https://paste.fedoraproject.org/paste/JGyPLHpvRIEUWQ5h8nhLeA](url)

**Comment by peak3d** [comment]
Have you been able to solve the issue? If not, pls. request support from the one building your kodi evvironment.
