### ISSUE TITLE
Won't play .m3u8 with key encrpytions (live channel)

### ISSUE THREAD

**Issue by dav-sap** [peak3d/inputstream.adaptive#89]
Hey, 
I'm developing the NFL game pass international addon and I'm using the inputstream adaptive.
I manage to play the archived games, it works perfectly. 
However when it comes to the live games/channels it won't play, it seems like kodi thinks it's playing cause I can see like a small "play" icon in the top right, and the log keeps posting these:

15:55:19.959 T:10476   DEBUG: CurlFile::Open(14B0A708) https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live//key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_1600/20171107135000.m3u8.key
15:55:20.721 T:10476   ERROR: CCurlFile::Open failed with code 404 for https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live//key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_1600/20171107135000.m3u8.key|Accept-encoding=identity%2c%20gzip%2c%20deflate&Connection=keep-alive&Cookie=hdntl%3dexp%3d1510148978%7eacl%3d%252f%2a%7ehmac%3db91ca34494b0020b784e779ba0a797927edb7b1948145417763ccf5cf9e535f9%3bnlqptid%3dh%3d64131fbe3707862221af61969a7cb316.1510062578206%26hdnea%3dexp%3d1510062638%7eacl%3d%2f%2a%7ehmac%3dA74E59AF5301E17D20F8CE7CB76F6973D76460E280E1F617AED13CEDDB0FBFA7%26nltid%3dnflgp%26nltdt%3d0%26uid%3d1722004&User-Agent=Mozilla%2f5.0%20(Windows%20NT%2010.0%3b%20WOW64%3b%20rv%3a55.0)%20Gecko%2f20100101%20Firefox%2f55.0&acceptencoding=gzip&seekable=0
15:55:20.722 T:10476   DEBUG: AddOnLog: InputStream Adaptive: Download https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live//key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_1600/20171107135000.m3u8.key finished
15:55:23.506 T:10476   DEBUG: AddOnLog: InputStream Adaptive: Download https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/nfltv_hd_1600_20171107135430.ts finished, average download speed: 479875.0000

Maybe it's just trying over and over again.
Anyway this is the error i'm getting (2nd line in that log). I'm sending the correct cookies and everything cause if I change the cookie a bit I get the 403 Forbidden Error, so I conclude the cookies are correct.

This is how I use the input stream:
```
if self.has_inputstream_adaptive and addon.getSetting('use_inputstream_adaptive') == 'true':
            playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
            playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
            playitem.setProperty('inputstream.adaptive.stream_headers', url.split('|')[1])
            playitem.setProperty('inputstream.adaptive.license_key', url)
  playitem.setProperty('IsPlayable', 'true')
  xbmc.Player().play(item=url, listitem=playitem)
```

        
      

Again it works for archive games ( after I added the "setProperty" license_key line), but for live it won't.

Any ideas?

**Comment by glennguy** [comment]
@dav-sap I can't reply to PMs on the Kodi forum, not enough post count!

For clarity here is the excerpt from the m3u8 that was in the PM:
```
the .m3u8 file i'm sending is the master file, looks something lie this:
#EXTM3U
#EXT-X-VERSION:2
#EXT-X-PROGRAM-DATE-TIME:2017-11-07T05:10:40Z
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:14334399
#EXT-X-KEY:METHOD=AES-128,URI="/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171107051000.m3u8.key",IV=0xC750E34848C8961A8DD8E247DE78FB97
#EXTINF:10,
nfltv_hd_4500_20171107051040.ts
#EXTINF:10,
nfltv_hd_4500_20171107051050.ts
#EXTINF:10,
nfltv_hd_4500_20171107051100.ts

etc...
```
You can see that it is appending the URI of the crypt key to the path of the m3u8 file (note the double slash) : ```15:55:19.959 T:10476 DEBUG: CurlFile::Open(14B0A708) https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live//key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_1600/20171107135000.m3u8.key``` whereas it should be appended to the domain only. From what I can see this is implemented in inputstream.adaptive from version 2.0.8 - added in commit 8234217, d7667d3 for Krypton. 

What version of Kodi / inputstream.adaptive are you using to test?

**Comment by dav-sap** [comment]
Using Krypton 17.5, and whatever inputstream adaptive that comes with it, i
think it's 2.0.18. I saw the double slash didn't think much of it.
Should i downgrade my versions?

**Comment by JinRonin** [comment]
If you use inputstream adaptive you have to use the master.m3u8.
As far as i can see (code and post from glenn) you parse the m3u8 master.

The license url is already in the m3u8 file so you just have to send the headers that are beeing required
`playitem.setProperty('inputstream.adaptive.license_key', '|headers'`

**Comment by dav-sap** [comment]
I'm sending the master.. Here's a print from now of my license key and url that i'm playing:
12:21:29.890 T:10868   DEBUG: [plugin.video.nfl.gamepass-0.11.2-dev]: PLAYING: https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/nfltv_hd_pc.m3u8?h=0e60247dedac94eaf6b2f771b860fa07.1510136488576&hdnea=exp=1510136548~acl=/*~hmac=406BED95B2D23EF816152C5925156A800BF884FDEAAE9E1371CB7CC15048C409&nltid=nflgp&nltdt=0&uid=1722004

12:21:29.891 T:10868   DEBUG: [plugin.video.nfl.gamepass-0.11.2-dev]: inputstream.adaptive.license_key: https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/nfltv_hd_pc.m3u8?h=0e60247dedac94eaf6b2f771b860fa07.1510136488576&hdnea=exp=1510136548~acl=/*~hmac=406BED95B2D23EF816152C5925156A800BF884FDEAAE9E1371CB7CC15048C409&nltid=nflgp&nltdt=0&uid=1722004|Connection=keep-alive&Cookie=hdntl%3Dexp%3D1510222889%7Eacl%3D%252f%2A%7Ehmac%3D98c637598528f55ce9da30c5ae1ae4a605c8bf12c500fa2ccfcee9e771baa291%3Bnlqptid%3Dh%3D0e60247dedac94eaf6b2f771b860fa07.1510136488576%26hdnea%3Dexp%3D1510136548%7Eacl%3D%2F%2A%7Ehmac%3D406BED95B2D23EF816152C5925156A800BF884FDEAAE9E1371CB7CC15048C409%26nltid%3Dnflgp%26nltdt%3D0%26uid%3D1722004&Accept-encoding=identity%2C+gzip%2C+deflate&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F61.0.3163.100+Safari%2F537.36

**Comment by dav-sap** [comment]
Problem is the inputstream.adaptive code looks for the last "/" and cuts there, and when I look in the chrome request url for the master .m3u8 file this is the request:

Request URL:https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/nfltv_hd_pc.m3u8?h=7f647299b88b436097e4693f3813d27c.1510139217963&hdnea=exp=1510139277~acl=/*~hmac=DE9C82FE7DD976E52FCECCDBA3D89378EA7A60358DE9448E0522D30A0D81F725&nltid=nflgp&nltdt=0&uid=1722004

So I need to figure out how to send them as parameters to inputstream.adaptive

**Comment by JinRonin** [comment]
Can you please post a full debug log to pastebin with the following setting

`playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
playitem.setProperty('inputstream.adaptive.manifest_type', 'hls') 
playitem.setProperty('inputstream.adaptive.stream_headers', url.split('|')[1])
playitem.setProperty('inputstream.adaptive.license_key', url.split('|')[1])
xbmc.Player().play(item=url, listitem=playitem)`

**Comment by dav-sap** [comment]
https://pastebin.com/index/5JJjHyTR

**Comment by JinRonin** [comment]
yes as pointed out from glennguy the key url is being created wrong. ping @peak3d 

also we have forgot the | in license_key. it should be
`playitem.setProperty('inputstream.adaptive.license_key', '|'+url.split('|')[1]) `

**Comment by peak3d** [comment]
From log inputstream.adaptive uses:

`https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live//key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_3000/20171108111500.m3u8.key|acceptencoding=gzip&seekable=0
`
Is there something wrong with that? Or do you search for a possibility to add headers?

**Comment by JinRonin** [comment]
Yes this is wrong in this case. 
The correct url is:
https://neunlds21.akamaized.net/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171107201000.m3u8.key

So its just 'https://neunlds21.akamaized.net' + key (if its starts with slash)

**Comment by dav-sap** [comment]
it's wrong, because the key end should be added from the base domain, it should look like this:
`https://neunlds21.akamaized.net/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171107201000.m3u8.key`

the string is being split incorrectly because I need to use this url:
`https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/nfltv_hd_pc.m3u8?h=7f647299b88b436097e4693f3813d27c.1510139217963&hdnea=exp=1510139277~acl=/*~hmac=DE9C82FE7DD976E52FCECCDBA3D89378EA7A60358DE9448E0522D30A0D81F725&nltid=nflgp&nltdt=0&uid=1722004`
everything after the `?` is parameters, not headers. is there a way to add them separately. Then the url will be correct

**Comment by peak3d** [comment]
Have you tried K18 + newest inputstream ? I remember that I implemented base-domain, but not sure if it was backported to K17

**Comment by dav-sap** [comment]
I'll give it a try.

**Comment by peak3d** [comment]
From looking into code base_domain_ is in inputstream.adaptive krypton branch, so at least the key request should work

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/blob/Krypton/src/parser/HLSTree.cpp#L400-L404

**Comment by dav-sap** [comment]
the game pass addon is not compatible with k18, all the dependencies are met, but it's not compatible, I can't figure it out. Any other way we can test this?

**Comment by peak3d** [comment]
You can simply create a .strm file with the 

#kodiprop: inputstreamaddon=inputstream.adaptive
#kodiprop: .. repeat for each listitem property you set in addon.
manifest url

and try K18 with playing this .strm file

**Comment by dav-sap** [comment]
but is it cutting the url from the last "/" ? if so that's reason. The base_domain is probably 
`https://neunlds21.akamaized.net/nlds/nfl4/nfltv/as/live/`
instead of `https://neunlds21.akamaized.net`
k18 probably won't make much difference. If i try to change the `.cpp` is it a big deal compiling and building everything?

**Comment by peak3d** [comment]
base_domain is this: https://github.com/peak3d/inputstream.adaptive/blob/Krypton/src/common/AdaptiveTree.cpp#L193-L195

**Comment by dav-sap** [comment]
I see, so the only option is that I'm using an old version? I just installed everything yesterday

**Comment by peak3d** [comment]
Then there could be a whitespace before the / in the URL?
You may have seen that I check for the first character, I'm not 100% sure if I trim everything.

**Comment by glennguy** [comment]
Is there an error in the logic for determining how to construct the key URL from the URI in the manifest?

```
current_pssh_ = map["URI"];
            if (current_pssh_.find("://", 0) == std::string::npos)
              current_pssh_ = base_url + current_pssh_;
            else if (current_pssh_[0] == '/')
current_pssh_ = base_domain_ + current_pssh_;
```

URI - ```URI="/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171107051000.m3u8.key",IV=0xC750E34848C8961A8DD8E247DE78FB97```

A key URI that starts with '/' will never contain '://' - I think the tests need to be performed in reverse order??

**Comment by peak3d** [comment]
No, thats correct, pls. don't look to your case only

There are three cases:

- absolute URL (including ://) (first if)
- relative to base_domain (second if)
- relative to path (default)

**Comment by dav-sap** [comment]
no whitesapces, I checked now. I'll try the k18 version with .strm file. 
I just have no idea how to do it.  I just create a file and add these lines:
```
#kodiprop: inputstreamaddon=inputstream.adaptive
#kodiprop: inputstream.adaptive.manifest_type=hls
```
etc..
?

**Comment by glennguy** [comment]
Sure, but I can't see a case where it would start with / and also contain :// afterwards. Please correct me, but the way I'm reading the code is ' if the URI doesn't contain "://", then append the URI to the base url (path), otherwise if the first character is a / then append the URL to the domain'. With the supplied URI, this will always test true for not containing "://" so we get the relative to path option taken.

**Comment by dav-sap** [comment]
I'm getting an error on my cookies I need and get a link right after all the other operations. I hope it's possible. just a sec

**Comment by peak3d** [comment]
pls. read my edit in my last post, I'll fix the issue

**Comment by dav-sap** [comment]
ok.. Thanks

**Comment by dav-sap** [comment]
@peak3d I saw you fixed the issue. Is there a way to get the 2.1.7 for krypton?

**Comment by peak3d** [comment]
sure, will prepare a backport today

**Comment by peak3d** [comment]
done

**Comment by peak3d** [comment]
Its a binary addon, it has to be compiled.
What OS do you use?

**Comment by peak3d** [comment]
IIRC there are Krypton nightly builds from kodi, so you can pick one tomorrow from kodi mirrors.
For LE you have to wait until someone compiles the addon and provides it. Here you have to ask your LE provider.

If you have finally inputstream.adaptive 2.0.19 you are done.

**Comment by peak3d** [comment]
If you compile native, it is straight forward, cross compiling needs some knowledge about cmake parameters
Make sure to refer to the README.linux and README.ubuntu (if on ubuntu) files in docs folder

**Comment by dav-sap** [comment]
@peak3d It fixed my problem, addon is working :)
Thanks so much! I think I'll try to build it for linux now. I couldn't find the docs folder, can u point me to it?

**Comment by peak3d** [comment]
You need kodi git-cloned to be able to compile binary addons.
Reason is that kodi provides addon-kit (include files) needed for the build.

If you setup a build system, pls. compile both kodi + inputstream.adaptive together,
The docs folder is in xbmc root (https://github.com/xbmc/xbmc/tree/master/docs)

**Comment by dav-sap** [comment]
ok great thanks!
