### ISSUE TITLE
1080p video not recognized (played at 720p)

### ISSUE THREAD

**Issue by axlt2002** [peak3d/inputstream.adaptive#9]
Hi peak3d,

I Am actually using the new version of YouTube add-on (5.3.6) that works with MPEG-DASH thanks to your inputstream.adaptive. I have already posted the following issue in the YouTube add-on thread and the author suggested me to contact you since it seems the issue is related to inputstream. Hope you can give at least a look to it (I didn't find any thread on the Kodi forum, that is why I'm writing here).

The point is simple: even if on YouTube the interested video is available in 1080p resolution, Kodi plays it at 720p. So I'm wondering where I'm making a mistake. These are the relevant settings I'm using:

**_YouTube addo-on_**
Video Quality -> 720p (this one does not have any impact; is an old parameter that is not used in case of MPEG-DASH)
Always ask for the video quality -> Disabled
Use MPEG-DASH -> Enabled

**_InputStream Adaptive_**
Min. Bandwidth -> 11000000
Max. Bandwidth -> 20000000
Max. Resolution -> 1080p
Stream Selection -> Manual (I have tried also "Auto")
Media -> All

The "guilty" video is [this one](https://www.youtube.com/watch?v=7bu6CekekZY) and under Firefox it plays without any issue at 1080p resolution.

In order to help, you can find the log at this [link](http://pastebin.com/Zs5mzvKJ). Please let me know if you need further information.

A more generic question: is there any way to "force" the use of 1080p instead of having the adaptive approach calculation based on the minimum bandwidth (4 Mbit/s as default; 11 Mbit/s in my case)? It would be like in YouTube, where you can choice manually the format.

Thanks for your attention and big effort.

**Comment by peak3d** [comment]
Hi, from log this video is not played using mpeg/dash.
inputstream.adaptive is quite talkative, but there is nothing (except loading on kodi start)

**Comment by axlt2002** [comment]
Hi peak3d,
Thanks a lot for your answer. I'm going to report back to the YouTube add-on developer. In fact it was sounding strange to me that some other videos are played at 4K.
One question on this last point...is there a way to limit the resolution to 1080p? I have set maximum resolution to 1080p, but videos that have 4K available are played at 4K.
Thanks again for your effort in this work!

**Comment by peak3d** [comment]
Seems to be the same issue - if imputstream.adaptive / dash is used for playing the content, the limitation should work (assuming stream selection is "auto" and NOT manual).
Without inputstream.adaptive as player everything could happen (out of my scope)

**Comment by axlt2002** [comment]
Thanks for the clarification; it seems the problem is in my settings. I will try the stream selection on "auto" while playing a 4K video to check if it will be limited to 1080p.
For the "720p issue", please take a look to [this thread.](http://forum.kodi.tv/showthread.php?tid=267160&pid=2508051#pid2508051); may be you can give some hints on that.
Keep in touch!

**Comment by axlt2002** [comment]
Hello,
I had finally some time to make a trial. Well, actually I'm not able to watch this YouTube video zikMbQZe8_k at 1080p. I have tried different settings but in case of "manual" the video is played even at 4K, in case of "auto" it does not go more than 720p. Can you make a try please?
For the "720p issue" reported in the previous posts, is a question of DRM for the 1080p stream option of the same video. See the thread mentioned above.

**Comment by peak3d** [comment]
Have you downloaded the manifest file and looked into it that it supports the 1080p?
The URL of the manifest/mpd file can be found in kodi.log after trying to play.
Can you pls attach this mpd here?

I'm currently very busy in other kodi issues and need your support for this one.

**Comment by axlt2002** [comment]
Hi peak3d!
No worries...thanks for your great work you are doing for Kodi and its users!
I think that I understood why the video is played at 720p maximum. I have just noticed that my PC monitor is not Full HD, therefore inputstream.adaptive does take it into account while "deciding" the stream to be played. Trying on my tablet, that has a 1920x1200 resolution, the video finally played at 1080p.
I think that this implementation choice is for optimize the data flow; does it make sense to download a 1080p video if the screen is only 720p? Well, I think that sometimes this could be the case...A suggestion would be to add an option to inputstream such as "limit the resolution according to the screen one" or something like that.
Thanks for your great effort!

**Comment by peak3d** [comment]
Hi @axlt2002 
I'll do something like how much % screen vs media can differ.
If you type 150% then the movie can be 150% of the screen resolution.

I have currently many open issues, but have noted the requirement.
Means, this will take some time to get it in.

**Comment by pckbls** [comment]
I'm wondering if it would make sense to implement a format filter string similar to the way youtube-dl handles the format selection problem:
https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection

**Comment by peak3d** [comment]
Not really, the example you posted is for streams wich don't support adaptive bitrate switching.

inputstream.adaptive is designed for mpd / ism files wich are thought to do those things best possible automagically.

**Comment by pckbls** [comment]
Ah, I should have been more clear: My thought was to use such a format string to pre-filter the available representations that shall be taken into account by the actual adaptation logic. That way we could for instance:
* limit the maximum video resolution to 1080p while the adaptation logic can still choose between 144p, 240p, 360p, 720p, whatever...
* prefer a specific video codec such as h.264 over vp9 (might be useful for YouTube videos)

**Comment by peak3d** [comment]
- For detailed selection you can use manual stream selection (should only be use for debugging)
- For limiting stream resolution I don't think fixed absolute values ("1080p") is the solution because only a few % of kodi users know what they are doing. A relative value (video can be X % bigger than screen) would fulfill most needs.
- Prio List for codecs would make sense, good idea.

My current implementation sight is to make technical things hidden wherether it is possible.
It is not thought as a kind of mpd analyzer, inputstream.adaptive should run with the best possible result without any manual setting needed (still some work to do for this)

**Comment by koenkooi** [comment]
My use case for 4k video when using 1080p gui is s905* based systems. Running the gui at 4k seems to be too much for the GPU, but 4k decode is fine.
So I would love to have inputstream.adaptive pick a 4k stream and have kodi switch resolution to 4k, just like it does for local media.

**Comment by peak3d** [comment]
@koenkooi Ok, I'll will add an option to ignore display res on start.
Didn't expect that kodi can switch display-res on stream start.

**Comment by Fludizz** [comment]
Can confirm what @vaguerant just said. After updating to LibreELEC 8.95.2, having Inputstream configured to with a resolution set to "1080p" causes all streams to play at 720p. Changing it back to "max" seems to resolve this and streams run at 1080p just fine.

Debug log with setting at "1080p" using Youtube/MPEG-DASH for playback:
https://paste.ubuntu.com/p/HW4yzF82MP/

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259

**Comment by dagwieers** [comment]
@axlt2002 I think we fixed this as part of #259, can you please verify? Or if no longer relevant to you, please close this issue.

**Comment by axlt2002** [comment]
Everything is working as expected now. Thanks a lot!
