### ISSUE TITLE
No Video in Raspberry PI4 Netflix Addon

### ISSUE THREAD

**Issue by venkatmakam** [peak3d/inputstream.adaptive#900]
### Describe the bug
I am using Android Tv  Build (Version 11) from [Konstakang](https://konstakang.com/devices/rpi4/LineageOS18-ATV/). I have installed kodi 19.3 and netflix addon.When i play the video only audio is coming and no video is coming.
Here is a clear and concise description of what the problem is:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV  (version 11)
 - Kodi version: 19.3
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
no debug log provided,
most likely your custom rom does not have licensed Widevine library
