### ISSUE TITLE
Audio doppler effect

### ISSUE THREAD

**Issue by ratcashdev** [peak3d/inputstream.adaptive#906]
### Describe the bug

Noticeable change in audio playback speed - slowdown followed by speedup, followed by slowdown - as if it was played from an old cassette.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Constant audio 'speed', just like it happens in a browser, when playing the same DASH stream.

## Actual Behavior

Playback starts. Wait for some music, because during speech this is hard to notice. During music, after some seconds, the pitch noticeably goes down (frequency drops) and then goes up again as if applying a  'doppler' effect.
Playing the same stream in the browser produces no such effects.

### To Reproduce

1. Open https://c201-node62-cdn.connectmedia.hu/64026/19d3aa1ba2297b490b839118745a3d34/620ec5d7/manifest.mpd?v=5sip:185.29.156.60
2. Listen to the audio and notice the variance in the speed / doppler effect during music
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/omumunudiz.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://paste.kodi.tv/ozokegorij

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjaro Linux 5.16.7
 - Kodi version: 19.3
 - inputstream.adaptive version: 19.0.2

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
I can see in the manifest the frame rate is apparently 14fps, while your screen is refreshing at 59.94
Do you get any different results if you try different combinations with the sync to playback settings in Kodi?

**Comment by ratcashdev** [comment]
Yes, toggling sync ON does seem to have an effect, i.e. there's no pitch shifting.

**Comment by glennguy** [comment]
Thanks for the info

I don't think this is an issue with inputstream.adaptive. I don't think there's a refresh rate on most displays that will play nicely with 13 or 14 fps. Perhaps in the browser it works fine because instead the video is altered/dropped frames?
You could try searching or asking on the forum for advice.
