### ISSUE TITLE
VP9 support

### ISSUE THREAD

**Issue by greystashh** [peak3d/inputstream.adaptive#91]
Have you already tried to integrate vp9 streams into inputstream?

**Comment by peak3d** [comment]
No, I'll most probably need a Bitstreamparser for this.
Have you any example URL for one?

**Comment by greystashh** [comment]
Maybe this might help?

https://github.com/webmproject/libwebm/tree/master/webm_parser

**Comment by Gujal00** [comment]
STRM file for testing. MPD with webm video VP9 codec and webm audio opus codec
`#KODIPROP:inputstreamaddon=inputstream.adaptive`
`#KODIPROP:inputstream.adaptive.manifest_type=mpd`
`#KODIPROP:inputstream.adaptive.stream_headers=Referer=https://h5p2p.peer-stream.com/`
`https://h5p2p.peer-stream.com/chunks/pro7maxx_hq.webm.mpd`

**Comment by peak3d** [comment]
Thx!

**Comment by greystashh** [comment]
Would this be helpful?

http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash

**Comment by anxdpanic** [comment]
@peak3d 
I've had a couple users ask about vp9 in the YouTube add-on since the addition of vp9 for Netflix. 
Is vp9 working in general or currently only w/ Netflix? I tried without luck. 
If you're interested in taking a look I put together a couple test versions of the add-on w/ strm, and a few examples of the manifests/logs/video.

Folder: https://drive.google.com/drive/folders/1c34upeOpQ_dVXmhr48KNyQrdH2g4xyuM
Test version info:  https://drive.google.com/file/d/1Dtko-GJ7Xf6sHglrlNYth_nsfpn7yAfv/view?usp=sharing

**Comment by peak3d** [comment]
@anxdpanic IIRC issue is that the vp9 codec in YT comes in webm container,
Netfilx provides vp9 in mp4 container which is already implemented, webm is still on todo list

**Comment by anxdpanic** [comment]
That makes sense, thank you. I'll keep the test stuff available in case it can be of use in the future

**Comment by dagwieers** [comment]
@peak3d This issue should be titled **Webm container support** instead.

**Comment by peak3d** [comment]
VP9 is implemented IIRC.

**Comment by anxdpanic** [comment]
Yes, implemented and no issues I'm aware of.

**Comment by dagwieers** [comment]
I was referring to:

> @anxdpanic IIRC issue is that the vp9 codec in YT comes in webm container,
Netfilx provides vp9 in mp4 container which is already implemented, webm is still on todo list

**Comment by anxdpanic** [comment]
Yea, webm - vp9 and vp9.2(hdr) streams have been working in YouTube for quite a while.
btw, you can add-on me to the stakeholders for YouTube and Twitch. It's not currently working in Twitch due to the addition of EXT-X-DISCONTINUITY, seen #374 so will test that when I get a chance.

**Comment by dagwieers** [comment]
@andxpanic Thanks for the update. I will update the Wiki (although I think you can also do that now).
