### ISSUE TITLE
French labels too long in settings, settings value not visible

### ISSUE THREAD

**Issue by darodi** [peak3d/inputstream.adaptive#918]
### Describe the bug
Here is a clear and concise description of what the problem is:

French labels are too long in settings, we can't see the selected values next to the label

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

labels not too long, be able to see the selected values in settings

## Actual Behavior

French labels too long in settings, unable to see the selected values

## Possible Fix

shorter labels
I made suggestions in 
https://kodi.weblate.cloud/translate/kodi-add-ons-videoplayer-inputstream/inputstream-adaptive/fr_fr/?q=
but cannot save the modifications

### To Reproduce

1. change regional language to French in Kodi
2. go to inputstream adaptive settings
3. cry because you cannot see the settings values

### Debuglog

The debuglog can be found here: 
**not applicable**

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
**not applicable**

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/4682830/159583808-c0ebacd3-351a-4b9f-922d-98bb98ccf236.png)
![image](https://user-images.githubusercontent.com/4682830/159583905-3e3b5ee8-4412-46fe-903c-48ccc2dc01df.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I changed strings.po locally but would like a fix included in next version

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3
 - inputstream.adaptive version: ?

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
this is a bug in Kodi GUI control, i had already see this bug
please open an Issue on Kodi xbmc repository

**Comment by darodi** [comment]
> this is a bug in Kodi GUI control, i had already see this bug please open an Issue on Kodi xbmc repository

linked to https://github.com/xbmc/xbmc/issues/21184


Also, shorter labels in 
https://kodi.weblate.cloud/translate/kodi-add-ons-videoplayer-inputstream/inputstream-adaptive/fr_fr/?q=
