### ISSUE TITLE
update headers while in play

### ISSUE THREAD

**Issue by dav-sap** [peak3d/inputstream.adaptive#92]
Hey, 
Is there anyway to update headers (Cookies) while the file is playing? I have an issue that after about 20 mins of live stream the stream crashes and in the log I get 403 Forbidden, which is the error I get when the cookies are incorrect, after exiting and opening everything up the stream works again, but it's really not convenient and it makes the whole kodi crash.
I added a service thread that every expiration date of the link(expire in the link, which is 1 minute) I refresh it, but it's obvious and it's kind of stuck and bumpy ( so every minute everything jumps) I can't tell when the 20\30 minutes is it might be even less, the only expire date I have on links is about 1 minute.
If I could just change the headers of the link while they are playing (every `.ts` from now on will use different cookies) it would be great and smooth. my code is this:
 ```
            playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
            playitem.setProperty('inputstream.adaptive.manifest_type', 'hls')
            playitem.setProperty('inputstream.adaptive.stream_headers', url.split('|')[1])
            playitem.setProperty('inputstream.adaptive.license_key', '|' + url.split('|')[1])
            playitem.setProperty('IsPlayable', 'true')
            xbmc.Player().play(item=url, listitem=playitem)
```

Ifi just remove the play it won't do anything right? i need to reach to the inputstream.adaptive playing file and change it.
does that exist? is it possible?

**Comment by JinRonin** [comment]
Actually there is a way to update the license key. 
Where are you getting the 403 response? hls or license?

**Comment by dav-sap** [comment]
I'm not sure, I'll get the error again and post it.

**Comment by dav-sap** [comment]
This is the error I get

```
21:18:10.280 T:140253389842176   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
21:18:10.280 T:140253389842176   ERROR: CCurlFile::Open failed with code 403 for https://neunlds21.akamaized.net/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171115191500.m3u8.key|Accept-encoding=identity%2c%20gzip%2c%20deflate&Connection=keep-alive&Cookie=hdntl%3dexp%3d1510854497%7eacl%3d%252f%2a%7ehmac%3d2b517e3cba10aa0d95dadcf7411e0052b1fcae03eb1c087a3acae9cf15ed80ba%3bnlqptid%3dh%3d2b46251a58301e4abbd99c7b64a03613.1510768096903%26hdnea%3dexp%3d1510768156%7eacl%3d%2f%2a%7ehmac%3dA64F3500A2D1ADE64EBB42DF54452F1AEEE3283BC86922195B470B99983CBA27%26nltid%3dnflgp%26nltdt%3d0%26uid%3d1722004&User-Agent=Mozilla%2f5.0%20(Windows%20NT%2010.0%3b%20Win64%3b%20x64)%20AppleWebKit%2f537.36%20(KHTML%2c%20like%20Gecko)%20Chrome%2f61.0.3163.100%20Safari%2f537.36&acceptencoding=gzip&seekable=0
21:18:10.280 T:140253389842176   DEBUG: AddOnLog: InputStream Adaptive: Download https://neunlds21.akamaized.net/key/nlsk3/nlsk4/hls/securekey?id=21&url=/nlds/nfl4/nfltv/as/live/nfltv_hd_4500/20171115191500.m3u8.key finished

```

nothing else is written.
I think the error comes from the license

**Comment by JinRonin** [comment]
In order to renew the headers you can add a plugin call in the license_key.
Example:
https://github.com/kodinerds/repo/blob/master/plugin.video.eurosportplayer/resources/lib/client.py#L79
There you will have to create a directory item with the new license_key.
https://github.com/kodinerds/repo/blob/master/plugin.video.eurosportplayer/resources/lib/items.py#L71

Note that this only works in Kodi 18

**Comment by dav-sap** [comment]
ok, i'll take a look, Thanks :)

**Comment by dav-sap** [comment]
and this line 
https://github.com/kodinerds/repo/blob/db17c4174102b3ff083efa8f3638c81d4134dd1a/plugin.video.eurosportplayer/resources/lib/items.py#L68
is instead of play for Player?

When I add the directory item it immediately switches to it?

**Comment by JinRonin** [comment]
Ignore that.
If inputstream adaptive fails to get the license key it can call your plugin which has to return the path to the new license key so it can use the new one.
Like this:
https://pastebin.com/MeU6Ptkh

**Comment by dav-sap** [comment]
my `argv` only has `['default.py']`, there is `no argv[1`] or `argv[2]`

**Comment by JinRonin** [comment]
I see. Your addon runs as script and not plugin.
No idea if it will still run when you change it to
`<extension point="xbmc.python.pluginsource" library="default.py">`
in the addon.xml
Sorry but cant help here any further.

**Comment by dav-sap** [comment]
I see.. I'll try, Thanks
