### ISSUE TITLE
inputstream cannot play mpd file

### ISSUE THREAD

**Issue by boxkim14** [peak3d/inputstream.adaptive#922]
Hi,

The Inputstream cannot play following file.
Can you please take a look on this issue when you have time?
Thanks in advance for your help.

hxxps://manifest-viki.viki.io/v1/1192087v/limelight/domain_4/mpd/vtt/viki/baseline/sd/ww/dt2_dt3/manifest.mpd?app=100005a&h_country=ca&h_host=playback-streams-c8f6ddc74-gfkvc&h_request_id=01bfee85c0881ce3522521b8a36cca37%2F9362534543543772187&device_model=vivo+1606&h_data_center=vir-2&h_timestamp=1648357617&tag=mpdhd%3Abaseline%3Aww%3AsourceVIKI%3Ampd%3Acached%3Adt2_dt3&max_res=360p&sig=8b80c88ab80deb0072215f3102e136e070b1a94f

**Comment by glennguy** [comment]
To begin any sort of help we will need a full debug log showing the failed playback.

Is this from an add-on? If so are you the author?

**Comment by boxkim14** [comment]
Thanks @glennguy for your answer.

Please find the log in following url:
https://pastebin.com/gNU8ZJC5

Yes, this is from an add on and I am not the author, but I can modify for testing purpose if needed.

Thanks for your quick answer

**Comment by glennguy** [comment]
Missing license_key property.
Please check the wiki: https://github.com/xbmc/inputstream.adaptive/wiki/Integration

An example (in .strm file format)
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://widevine-proxy.appspot.com/proxy||R{SSM}|
https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd
```

**Comment by boxkim14** [comment]
Thanks for your help @glennguy.

I see the licence key is defined in the code with the Headers:
Note: It was working 2,3 weeks ago.

				item.setProperty('inputstream.adaptive.stream_headers', hea)
				item.setProperty('inputstream.adaptive.license_key', "|" + hea)
			self.__print('Play Input HlS %s' % stream_url)
			item.setPath(stream_url)
			if utils.py3:
				item.setProperty('inputstream', 'inputstream.adaptive')
			else:
				item.setProperty('inputstreamaddon', 'inputstream.adaptive')

			if '.mpd' in stream_url:
				item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
			else:
				item.setProperty('inputstream.adaptive.manifest_type', 'hls')				
				item.setMimeType("application/x-mpegurl")

**Comment by boxkim14** [comment]
I am sorry if I disturb you but any update for this issue? :)
Thanks

**Comment by glennguy** [comment]
`item.setProperty('inputstream.adaptive.license_key', "|" + hea)`
Please check the wiki, in this section: https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivelicense_key

There is no URL in the license key, that is why you are getting the error.
To be clear there is no issue with inputstream.adaptive but the add-on code. You should open an issue with the author.

**Comment by boxkim14** [comment]
Thanks @glennguy to take time to explain how to use the license key.
