### ISSUE TITLE
23.Xp Movies not decoded correctly

### ISSUE THREAD

**Issue by Krautmaster** [peak3d/inputstream.adaptive#93]
My NUC with Kaby Lake is able to run the streams without any issue as far as thy dont offer 23.9XX FPS - which seems to be usual in Amazone prime. 25p as well as 24,000p ran fine. I get hefty blocks (no visible image in general) on other 23.X material. Subtitels are shown correctly.

I can alos disable vaapi, scalers and all, I still get the blocks. Meanwhile all other stuff runs fine on the same libreelec kodi 18 htpc.

**Comment by JinRonin** [comment]
Tried activating adjust display refresh rate?

**Comment by peak3d** [comment]
Pls. report to kodi (trac.kodi.tv) including a debug log file.

**Comment by Krautmaster** [comment]
sure thx
