### ISSUE TITLE
Can't manually specify HLS key URL

### ISSUE THREAD

**Issue by fiplistener** [peak3d/inputstream.adaptive#944]
For some streams the HLS key is protected with headers etc. To work around this I tried to host the key on my local server using
#KODIPROP:inputstream.adaptive.license_key=http://localserver/key
But doing this causes inputstream.adaptive to try to do this
2022-04-21 09:24:54.778 T:11032   ERROR <general>: CCurlFile::Open failed with code 400 for https://keyurl_from_m3u8/key?http://localserver/key

I found some mentions of people trying to do something like this but I can't find any documented way to actually specify a key url that is different from the one in the m3u8 playlist.

**Comment by glennguy** [comment]
That won't work. Add-ons do this by starting a proxy server in python and then the proxy can modify the playlist/headers etc.
For a m3u8 playlist, you'd have to also create a simple helper add-on that could be used.

Call it from the list something like this:
```
#EXTINF:0, some stream
plugin://plugin.video.somepluginhelper/?url=https://example.com/stream.m3u8
```
