### ISSUE TITLE
[HBO] Dolby Atmos stutters

### ISSUE THREAD

**Issue by mkaflowski** [peak3d/inputstream.adaptive#948]
I have a problem with Dolby Atmos. When I use it it stutters. It get some very short mute fragments (and I see on AVR that there is no sound for a moment). When it happening the subtitles disappear for that moment too.
I have tested on Marantz and Denon AVRs and Nvidia Shield 2017 and Pro.
I can deliver video if that helps.

Kodi 19.4

**Comment by glennguy** [comment]
Possibly the same as #757

**Comment by Liqianyu** [comment]
I think this is similar to #757  but a different issue.
It may have something to do with the way HBO Max packages audio.

Kodi 19 Log
INFO <general>: CDVDAudioCodecAndroidMediaCodec Use raw decoder and decode using pt-eac3
INFO <general>: CDVDAudioCodecAndroidMediaCodec Open Android MediaCodec mediacodec
INFO <general>: CAEStreamParser::TrySyncAC3 - E-AC3 stream detected (6 channels, 48000Hz)

Kodi 20 Log
Resetting pause bursts as buffer level was reached! (1)

These logs appear just when there is a problem with the audio.

**Comment by CastagnaIT** [comment]
closed as no log provided no way to determinate the real cause
