### ISSUE TITLE
Nexus/ Compiling for Linux: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by a7ir3za** [peak3d/inputstream.adaptive#949]
⚙️  ~/inputstream.adaptive/build.bin i5 211435 $ uname -a
Linux i5.domain.local 5.16.12 #9 SMP PREEMPT Thu Mar 3 12:39:42 GMT 2022 x86_64 x86_64 x86_64 GNU/Linux

⚙️  ~/inputstream.adaptive/build.bin i5 211952 $ cc --version
cc (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

⚙️  ~/inputstream.adaptive/build.bin i5 211957 $ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Issue:
⚙️  ~/inputstream.adaptive/build.bin i5 212001 $ cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
⚙️  ~/inputstream.adaptive/build.bin i5 212043 $ make
[ 24%] Built target bento4
[ 48%] Built target expat
[ 72%] Built target googletest
[ 75%] Performing forcebuild step for 'inputstream.adaptive'
Force build of inputstream.adaptive
[ 78%] Performing build step for 'inputstream.adaptive'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [inputstream.adaptive-prefix/src/inputstream.adaptive-stamp/inputstream.adaptive-build] Error 2
make[1]: *** [CMakeFiles/inputstream.adaptive.dir/all] Error 2
make: *** [all] Error 2

**Comment by glennguy** [comment]
As I commented on the thread that was necrobumped yesterday:

Please have a read of the wiki page https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build
This may be out of date slightly so adjustments to some commands might be needed.
More up to date but less specific to this add-on instructions are in the Kodi repo: https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md

If you're still having trouble, please start from scratch and instead of just running `make` run `make VERBOSE=1 | tee log.txt` then you can attach the log.txt here.

**Comment by a7ir3za** [comment]
Compiling "in-tree" based on Kodi repo works.

**Comment by CastagnaIT** [comment]
Do you need more help or can we close?

**Comment by a7ir3za** [comment]
So how are you compiling it from within the repo on its own?
If you like to close it's fine as it is possible for me to compile "in-tree".

**Comment by CastagnaIT** [comment]
i have add instruction to build "out of tree" with Ubuntu:
https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build#build-out-of-tree-on-linux-ubuntu
in a similar way should also be done on other linux distributions

**Comment by a7ir3za** [comment]
Looks good.
