### ISSUE TITLE
stream won't change while in play with manual

### ISSUE THREAD

**Issue by dav-sap** [peak3d/inputstream.adaptive#95]
When I change the stream resolution I get a `403 Forbidden error`.
I think it's because I'm using a` license_key` attribute, and maybe it's not used when the switch happens?
I think that because the other times i get the `403 Forbidden Error` is when I don't use a` license_key `attribute
`playitem.setProperty('inputstream.adaptive.license_key', '|' + url.split('|')[1]`

**Comment by peak3d** [comment]
If you enable libCURL component debugging (kodi log settings) you can see every network connection in kodi log.
