### ISSUE TITLE
Only 1 audio stream available for selection in TS files that contain multiple

### ISSUE THREAD

**Issue by Radoorech** [peak3d/inputstream.adaptive#961]
Hello guys,

I use kodi 19.3 on windows 10 and coreelec 19.3, skin Estuary and pvr iptv simple client. My stream looks http://xxxx/live.m3u8, when I play this stream with kodi I have no option to choose audio stream. But if I play the same stream with android apps like TiviMate or with vlc player, I can choose audio stream. Can somebody help me where can be the problem? If need to more details, tell me please.

Thank you very much for your time.

https://imgur.com/a/Y8fBxPA

**Comment by CastagnaIT** [comment]
in order to investigate we need:
- full kodi debug log
- stream manifest

**Comment by Radoorech** [comment]
> in order to investigate we need:
> 
>     * full kodi debug log
> 
>     * stream manifest

Thank you very much for your time, here is the full kodi debug log. I deleted personal data, hope it´s not a problem.

https://paste.kodi.tv/bikorenoka.kodi

Sorry for dumb question, I´m a newbie, but what is stream manifest and how can I get it?

Many thanks in advance.

**Comment by CastagnaIT** [comment]
the manifests are the .m3u8 files
there is an aac audio stream listed but unfurnately no useful info
i could suspect similar problem of #686

you can check in VLC this:
- open "Messages" window from Tools->Messages
- switch to debug
- now play the video

from the VLC log you should find something like `mpeg4audio debug: detected ADTS format`
that could confirm my suspects, not in full, otherwise you should download a chuck of the audio stream and check the file e.g. with mediainfo software

my last investigation i saw that VLC use a mp4 demuxer component that we dont have in Kodi
this could be one of the reasons why the supplied aac type is not readable

**Comment by Radoorech** [comment]
Sorry for delay, here is the manifest, hope this is what you need, many thanks for your help.

https://paste.kodi.tv/zozuqocigo

**Comment by Vikassm73** [comment]
This is not  manifest.
Click link http://xxxx/live.m3u8 in the browser. One m3u8 file will get downloaded. Edit and open that file in notepad. Content inside is manifest.

**Comment by CastagnaIT** [comment]
that link give error page not exists
however seem to be ADTS i think is same issue of Issue linked above

**Comment by Radoorech** [comment]
Hello CastagnaIT and Vikassm73, i opened the stream in browser, edit file in notepad, but there aren´t any details, just this:

#EXTM3U
#EXT-X-ALLOW-CACHE:NO
#EXT-X-STREAM-INF:PROGRAM-ID=5147,BANDWIDTH=6700000,RESOLUTION=1920x1080
/at/hls/media/live5147.m3u8?device=xxx&auth=DVQqJQ5CUlNcUURFV01VRlBfVhleV0tGFlFBEhldQVIIWlNMUl9SXFFXWBlCQ0VURUBXXUBQCApdGFsOBFcD

And vlc.log doesn´t show anything important?

**Comment by CastagnaIT** [comment]
yes say audio ADTS,
currently we already know problems with this format and we dont know a solution

**Comment by Radoorech** [comment]
Ok understand, for now there is no solution for this issue. Just for information, I played with kodi settings and when I disable "use inputstream.adaptive for m3u8 (HLS) streams" in advanced settings of pvr iptv simple client, I can choose audio streams, just missing information about language (if slovak, czech, english,...).

So for now we can close this issue?

https://imgur.com/a/TCKlqV4

**Comment by glennguy** [comment]
If you could find a stream with this issue that a) we could access without geoblocking and b) you would be willing to share with us then we'd be able to help a lot more. Really working in the dark on this one.

**Comment by Radoorech** [comment]
glennguy, is there any way how can I contact you? I can´t share stream url here, because of personal details in stream url? If you live in Europe, I think there will be nou problem with geoblocking, if ouside not sure, sorry.

**Comment by glennguy** [comment]
In this situation we have multiple audio tracks contained in a single TS file (along with video as well).
Not widely seen as users and provider have to use extra bandwidth for streams they're not using.
Will investigate if a solution is easy or not

**Comment by Radoorech** [comment]
Provider made some changes in the stream, so now it works well. So I close the issue.
