### ISSUE TITLE
streams from addon plugin.video.amazon-test cannot be played

### ISSUE THREAD

**Issue by Maven85** [peak3d/inputstream.adaptive#964]
### Describe the bug
Since this [commit](https://github.com/xbmc/inputstream.adaptive/commit/1b9e2d0150bfc7263442c7f285e664592391482b), no streams can be played from the addon plugin.video.amazon-test. Every time you try to play it, you end up back in the overview list.

## Expected Behavior
Normal playback.

## Actual Behavior
Playback does not start.

## Possible Fix
I invested a little time and could identify these lines as the problem:
https://github.com/xbmc/inputstream.adaptive/commit/1b9e2d0150bfc7263442c7f285e664592391482b#diff-43a8b01ff438029416f622d65da103227de144908ecf6426a1e015426623c5a3R728-R731

If I restore the old code (+ helpers.cpp and helpers.h), the playback works

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and Android
 - Kodi version: master nightly
 - inputstream.adaptive version: 20.2.0

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Ronny-nerd** [comment]
I have the same problem with the same operating systems and the Amazon VOD Addon, at least since the new InputStream Adaptive version 20.2.0.

**Comment by CastagnaIT** [comment]
thanks for specified the part of code
seem to be a problem in URLEncode method

**Comment by CastagnaIT** [comment]
please give a feedback
you will find the patched ISAdaptive zips from follow link:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-965/1/artifacts

**Comment by Maven85** [comment]
I can confirm it's working again. Thanks!

**Comment by Ronny-nerd** [comment]
Would also like to thank them for the quick fix.

Thanks
