### ISSUE TITLE
Kodi crashes when playing H.265 streams

### ISSUE THREAD

**Issue by MauriceW67** [peak3d/inputstream.adaptive#969]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when playing H.265 streams since version 20.2.0 of InputStream Adaptive.
This happens with various addons (tried HBO Max and Disney+)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crashing, but playing the stream as it should. This used to work with version 20.1.2.

## Actual Behavior

When starting an H.265 stream (f.e. in the HBO Max addon), Kodi crashes back to the home screen of the Nvidia Shield.

### To Reproduce

1. Start Kodi
2. Open the HBO Max addon
3. Try to play a stream which is H.265 encoded (I used The Flight Attendant Season 2, Episode 1).

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jikiyuqudi.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Not sure how to get a manifest file from the HBO Max addon?

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I also retrieved the logcat from the Nvidia Shield.
The crash is shown starting at 05-08 12:54:45.
Link to logcat:
https://paste.kodi.tv/xisarifaxo.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.0.2 (Android TV 11)
 - Kodi version: kodi-20220507-74574af3-master-22690-arm64-v8a
 - inputstream.adaptive version: Nexus-9b88f0c (https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/114/artifacts)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Ronny-nerd** [comment]
Hardware:
Nvidia Shield TV Pro 2019
LG OLED55B7D

Amazon VOD Addon
Settings
General
If use H.265 video codec = enabled

then Kodi crashes when you start a stream.

**Comment by Ronny-nerd** [comment]
Have the same problem with the PC running Windows 10 and the Amazon VOD addon.

**Comment by CastagnaIT** [comment]
i found a bug, if works is possible that this will fix also dolby vision

Test builds zips here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-970/1/artifacts

**Comment by CastagnaIT** [comment]
@Ronny-nerd i am not aware that hevc widevine works on Windows, but this should fix android case

**Comment by Ronny-nerd** [comment]
Hardware:
Nvidia Shield TV Pro 2019
LG OLED55B7D

Amazon VOD Addon
Settings
General
If use H.265 video codec = enabled

This works again...thanks for the quick fix...CastagnaIT.

Dolby Vision = Not OK

https://github.com/xbmc/inputstream.adaptive/issues/968

Thanks for the info with Windows 10.

**Comment by MauriceW67** [comment]
@CastagnaIT Your fix fixed the H.265 issue that made Kodi crash, so thanks for that.

However, the Dolby Vision issue still persists (tried it in both Netflix and HBO Max).

One other thing I want to mention (if you want me to open a separate issue please let me know):

The option under Expert settings called "Try avoiding the use of secure decoder" is not being saved. When I enable it and restart Kodi, it shows as disabled again. If I understand correctly it would be better to enable this option on an Nvidia Shield or any other  device that has Widevine L1 implemented?

**Comment by CastagnaIT** [comment]
> The option under Expert settings called "Try avoiding the use of secure decoder" is not being saved.

i will check but there is no code that change this setting
more likely is one of your installed python addons force switch off this setting

**Comment by MauriceW67** [comment]
> more likely is one of your installed python addons force switch off this setting

Looks like you are right. I'm doing my tests on a clean install of Kodi with only IS:A, Disney+, Netflix and HBO Max installed.

I kept an eye on the file ".kodi\userdata\addon_data\inputstream.adaptive\settings.xml" while testing and as long as I didn't start any addons, the "NOSECUREDECODER" setting did not change. But after I ran the HBO Max addon, the setting was overwritten.

I was not aware that addons are able to overwrite settings of another addon inside Kodi...

**Comment by matthuisman** [comment]
That was a recent change by me. So users who have a l3 system will have that setting enabled.

If you have l1 (like a shield) you want that setting disabled (the default)

Maybe I should only enable on l3 but don't touch it on l1 so l1 users can enable it for want

Anyway, let's not pollute this thread about this. Open a new issue on slyguy if want to discuss further
