### ISSUE TITLE
Widevine license post body format

### ISSUE THREAD

**Issue by olavopeixoto** [peak3d/inputstream.adaptive#97]
Hi,
I'm implementing a plugin for a service that requires a special format to the post body when requesting widivine license.

The format is as follows:

{
  "token": "private token here...",
  "drm_info": [
    8,
    4
  ],
  "kid": "16880FC4-CD59-6230-9880-B280D0975E6E"
}

How can I achieve this using the license url format on inputstream.adaptive.license_key?

**Comment by peak3d** [comment]
Hi, currently only base64 or raw "drm_info" is supported, but its only a few lines of code to implement decimal numbers. Let me know if this issue is still actual...

**Comment by olavopeixoto** [comment]
Hi, thank you for your reply.
Yes it's still definitely current.
This is a plugin to watch UK TV Player from https://tvplayer.com
The premium channels are DRM and the format is as stated on my first post.
No, I don't have the "kid" value. It is extracted from manifest/media. I do have the token though and it needs to be passed on each DRM request.

The following is a print screen from chrome developer with the DRM request.

![screen shot 2018-03-11 at 22 31 35](https://user-images.githubusercontent.com/7496076/37259275-2d11f4aa-257c-11e8-8fdd-c67bea0677f3.png)

**Comment by emilsvennesson** [comment]
@olavopeixoto @peak3d This looks like the same format that's being used in one of my add-ons (see https://github.com/emilsvennesson/kodi-cmore/blob/master/resources/lib/Widevine.py).

I wrote a small proxy in order to get it to work, but it would have been nice if it was possible to get the challenge in bytearray format as well as a way to retrieve the KID.

**Comment by olavopeixoto** [comment]
@emilsvennesson this is brilliant! Very nice workaround and well coded add-on. Thanks for sharing.

**Comment by peak3d** [comment]
@emilsvennesson @olavopeixoto I'll prepare soemthing for it

**Comment by peak3d** [comment]
I prepared a branch with the changes -> untested
Would be great if someone of you can test / in particular if the order of HEX in kid are ok (there are 2 flavours)

https://github.com/peak3d/inputstream.adaptive/tree/decimal

The placeholders in license_key are D{SSM} and {KID}

**Comment by olavopeixoto** [comment]
Hi! I'm happy to do all tests needed. Just need a help on how to compile it for android. Do you have the binary?

**Comment by olavopeixoto** [comment]
I found one potential issue, not sure if it will cause any problem.
The token that I got has the character '|' in it.

Example: "tvplayer|2018-03-19T18:11:19Z|h8eExQVK3SNTHTVMxLUYRR91rjSgcHwwUG0ZXNOAP6KCXdbXK640bPhWziWSvhDQDQE/tJU4pJJCqxlgNHYiN1V+CCmP6v1zhFZUOT36H5A=|3677146a6dbe1eed99f017711aebf1b8ef1bbdfb"

**Comment by peak3d** [comment]
Yes, this is an issue, can you try to URLencode the token?
If this is not working, I have to implement something for it

**Comment by olavopeixoto** [comment]
I tried with the master version 2.2.5

I got the error: "ERROR: AddOnLog: InputStream Adaptive: 4 '|' separated blocks in licURL expected (req / header / body / response)"


My license_key was:

'https://widevine-proxy.drm.technology/proxy||{"token": "tvplayer|2018-03-19T18:11:19Z|h8eExQVK3SNTHTVMxLUYRR91rjSgcHwwUG0ZXNOAP6KCXdbXK640bPhWziWSvhDQDQE/tJU4pJJCqxlgNHYiN1V+CCmP6v1zhFZUOT36H5A=|3677146a6dbe1eed99f017711aebf1b8ef1bbdfb","drm_info": [D{SSM}],"kid": {KID}}|'

**Comment by olavopeixoto** [comment]
Sorry, missed your last comment.
I tried again url encoding just the token, it didn't work.
Tried one more time url encoding the whole post_body section. Didn't work either.

**Comment by peak3d** [comment]
Beginning with 2.2.7, if the post-body template path starts with %, I'll url_decode this part.
So please try again with 2.2.7 and urlencode the postbody part before sending.

**Comment by olavopeixoto** [comment]
I tried your changes but for some reason Kodi is crashing now after play the stream. I tried both OSX and Android (Shield TV).

license_key: https://widevine-proxy.drm.technology/proxy|Content-Type=application%2Fjson|%7B%22token%22%3A%22tvplayer%7C2018-03-22T21%3A17%3A17Z%7Ch8eExQVK3SNTHTVMxLUYRR91rjSgcHwwUG0ZXNOAP6KCXdbXK640bPhWziWSvhDQDQE%2FtJU4pHQCqxlgNHYiN1V%2BCCmP6v1zhFZUTG36H5A%3D%7C954ed2b5b8430a66e3714df31e08e6ad7d7fd510%22%2C%22drm_info%22%3A%5BD%7BSSM%7D%5D%2C%22kid%22%3A%7BKID%7D%7D|

Relevant log lines:

```
NOTICE: VideoPlayer::OpenFile: https://plus-secondary.tvplayer.com/pocahontas/lifetimehd/bitrate1.isml/Manifest.mpd

NOTICE: Creating InputStream

DEBUG: ADDON: Dll Initializing - InputStream Adaptive

INFO: AddOnLog: InputStream Adaptive: SetVideoResolution (3840 x 2160)

DEBUG: AddOnLog: InputStream Adaptive: Open()

DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_key: [not shown]

DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_type: com.widevine.alpha

DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES

DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_type: mpd

DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.stream_headers: cookie=AWSELB=63316D9B04FDD8FC9F286A83E94C330481D5C56A9391ECC3678AC3EFC096E1D6548791D100EB17A0AF725C1876181600BDA00C06FA1471053D160F2A9A6E0E4FBB82E65852

DEBUG: AddOnLog: InputStream Adaptive: Initial bandwidth: 16285657\

DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions

DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: ------ Window Deinit (DialogBusy.xml) ------
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTION selected: 0
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTIONSECURE selected: 0
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: AddOnLog: InputStream Adaptive: STREAMSELECTION selected: 1
DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /mnt/expand/d1b3d704-4608-498c-9a86-9878e20a5875/app/org.xbmc.kodi-2/lib/arm64/
ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /mnt/expand/d1b3d704-4608-498c-9a86-9878e20a5875/app/org.xbmc.kodi-2/lib/arm64/libssd_wv.so
DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://plus-secondary.tvplayer.com/pocahontas/lifetimehd/bitrate1.isml/Manifest.mpd
DEBUG: AddOnLog: InputStream Adaptive: Download https://plus-secondary.tvplayer.com/pocahontas/lifetimehd/bitrate1.isml/Manifest.mpd finished
INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Download speed: 2035707.1573 Bytes/s
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
21:17:17.435 T:138446832720   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
DEBUG: AddOnLog: InputStream Adaptive: Successful instanciated media_drm: 0x204011ea00, deviceid: unknown, security-level: L1
DEBUG: AddOnLog: InputStream Adaptive: Searching PSSH data in FILE
DEBUG: AddOnLog: InputStream Adaptive: Download https://plus-secondary.tvplayer.com/pocahontas/lifetimehd/bitrate1.isml/dash/bitrate1-audio_track=64000.dash finished, average download speed: 2032764.2457
DEBUG: AddOnLog: InputStream Adaptive: Initializing stream with KID: 16880FC4CD5962309880B280D0975E6E
DEBUG: AddOnLog: InputStream Adaptive: Key request successful
```

This is the last line in the log file:

`DEBUG: AddOnLog: InputStream Adaptive: Key request successful`

Non DRM content is still playing fine as is other DRM content previously working.

**Comment by peak3d** [comment]
can you pls.provide a crashlog? At least in logcat is a backtrace which may help.

**Comment by olavopeixoto** [comment]
FireTV logcat:

[firetv_logcat.txt](https://github.com/peak3d/inputstream.adaptive/files/1839584/firetv_logcat.txt)

**Comment by olavopeixoto** [comment]
Here are the .response files from OSX, I couldn't find them on Android devices.
I'll try to arrange a way for you to reproduce, where are you located? The URL will only work in the UK.
Do you have an email address to share the private details?

[cdm_response.zip](https://github.com/peak3d/inputstream.adaptive/files/1841799/cdm_response.zip)

**Comment by peak3d** [comment]
Please use the one from this git repo: pfau *at* peak3d.de. I have VPN (from germany) so could be possible.

**Comment by olavopeixoto** [comment]
I realised that there is one DRM channel on the free account, so you don't need any subscription in order to test it.

You must, however, create a free account with your email address here:
[https://tvplayer.com/account/create](https://tvplayer.com/account/create)

then you can use my add-on to test the issue here:
[https://github.com/olavopeixoto/plugin.video.tvplayer](https://github.com/olavopeixoto/plugin.video.tvplayer)

In order to properly reproduce the issue, set the following add-on settings:

```
Use InputStream.Adaptive addon = True
Allow DRM Content = True
Use DRM Proxy = False
```
The only DRM channel on the free account is the first "Five" (Usually the 4th item in the list).
For some reason (probably a bug on their side) there will be 2 channel "Five" in the list. The first one should be DRM the other is "open".

**Comment by snake13** [comment]
https://hss-m003-live-aka-canalplus.akamaized.net/live/disk/canalplus-hd/hddvr.isml/manifest

**Comment by peak3d** [comment]
@snake13 pls. do not hijack issue threads, pls. open a separate one

**Comment by peak3d** [comment]
@olavopeixoto there have been changes regarding the crash, is the issue solved now?

**Comment by olavopeixoto** [comment]
Hi @peak3d, I confirm it is working now.
It is working as good as the proxy that I had in place before this fix although It has the same issue that it had with the proxy in place.
The issue now is that the audio is muted for the first 3 or 4 seconds of the start of the streaming.
After these first muted seconds the streaming is perfect with no delays or anything, very smooth.
Should I log this as different issue or should I keep using this ticket?

**Comment by peak3d** [comment]
Pls. reopen / create a new issue thread with the audio delay if we want to continue investigating
