### ISSUE TITLE
drift

### ISSUE THREAD

**Issue by simpledork47** [peak3d/inputstream.adaptive#974]
I'm playing a widevine mpd stream
for about 2 hour an a halff.

pressing stop & play (again)
soccer match : elapsed time drift from 46m (playing time) to 52m (playing time).

kodi is 60hz 1080p display, stream is 1080p 25fps. if that matters
no error were logged in kodi.log (like frameskip or audio sync issues)

 cat /etc/issue.net
Debian GNU/Linux 11

dpkg -l | grep inputstream-adap
ii  kodi-inputstream-adaptive            1:19.0.4-dmo0+deb11u1                   amd64        adaptive inputstream addon for Kodi.

(marillat's one but shouldn't matter)

thank you !

**Comment by basilgello** [comment]
Well, I observe the same issue on 20.2.0 - it looks like if the segment is gone (live TV feed), IA jumps to first segment available.

Wgat's interesting on the same stream, imputstream.ffmpegdirect works fine!

**Comment by CastagnaIT** [comment]
i think that ffmpegdirect store the buffer that we dont have then we rely to what stream provide

**Comment by basilgello** [comment]
> i think that ffmpegdirect store the buffer that we dont have then we rely to what stream provide

Exactly that. But I recall IA also did store buffer no?

**Comment by glennguy** [comment]
I think what @CastagnaIT means is with IA we only ever look at the window of segments provided by the manifest from the last update. Perhaps FFMPEG though (just speculating here) will keep an internal map of all segments seen in manifests past and present?

**Comment by CastagnaIT** [comment]
what i want mean is that ffmpeg keep stream recorded while you watching, then if you pause and play the played stream is not more the live but the stored stream locally

> Exactly that. But I recall IA also did store buffer no?

not same, ISA have a its buffering just to extend kodi buffering

**Comment by glennguy** [comment]
Ah ok thanks

@simpledork47 just to clear up what's happening

1. Watch stream for some period of time
2. Press stop in Kodi
3. Play same stream again - *this I'm unsure of what happens - do you get the option and choose 'resume from' when pressing play?*
4. The position in the stream that starts playing is now different

Besides this there is not enough info in the OP to go off, and no clear way to reproduce.
>  no error were logged in kodi.log (like frameskip or audio sync issues)

A log file to one person says nothing while to another has all the info needed to find and fix a problem. We will never know though if we never see it.

**Comment by basilgello** [comment]
@glennguy I can give you an example stream on Slack that triggers similar jumps. Not mpd though - hls.

**Comment by glennguy** [comment]
That would be great, thanks @basilgello

**Comment by simpledork47** [comment]
> Ah ok thanks
> 
> @simpledork47 just to clear up what's happening
> 
> 1. Watch stream for some period of time
> 2. Press stop in Kodi
> 3. Play same stream again - _this I'm unsure of what happens - do you get the option and choose 'resume from' when pressing play?_

i'm pressing stop and play again, just after.
It was during a soccer/sport game so the 'time playing' displayed within a video was a good indicator.
(and others users here reported similar experience, not an isolated error case)

> 4. The position in the stream that starts playing is now different
> 
> Besides this there is not enough info in the OP to go off, and no clear way to reproduce.

Unfortunately it's a widevine mpd stream so no repro easily :(

> > no error were logged in kodi.log (like frameskip or audio sync issues)
> 
> A log file to one person says nothing while to another has all the info needed to find and fix a problem. We will never know though if we never see it.

Yeah of course.

Sometimes - unrelated to this issue - I'm getting choppy sound and lots of error "ActiveAE - large audio sync error"
=> not what I've seen here.

Do you think modifying refresh rate on kodi would have a (good) impact ?
like setting it to 50HZ , which is close to the 25 fps stream playing ?

**Comment by glennguy** [comment]
@simpledork47 
Perhaps give it a go (changing refresh rate). It would certainly look better!
Also interested to know the current setting for settings -> player -> videos -> sync playback to display

@basilgello with your test stream there's just a 60 second window that's available.
ffmpegdirect has timeshift buffering available which stores the segments in memory or on disk. As @CastagnaIT mentioned we buffer segments but only temporarily so that we can keep Kodi's buffer full if network conditions degrade. Your observations are correct though, when you pause for a long time IA will start with segment 0 of what's available.
On this topic though, Kodi 20 crashes in the same situation, will open a new issue to track

**Comment by simpledork47** [comment]
sync playback to display  'on'
adjust display refresh rate  'off'

**Comment by glennguy** [comment]
Can you try turning sync playback to display off, and turn adjust display refresh rate on (personal preference but I like 'on start/stop')?

If you find you miss the first few seconds of playback due to the refresh rate change you can make it wait: settings -> system ->Display -> Delay after change of refresh rate

**Comment by simpledork47** [comment]
@glennguy 

Today I've tested: 100 minutes of streaming and stop/play
(on a sport event again)

and NO noticeable time drift this time.

So it's fixed by setting sync playback to off.  And 'adjust display rate'

thank you !
