### ISSUE TITLE
Incorrect behaviour when with data interruptions

### ISSUE THREAD

**Issue by glennguy** [peak3d/inputstream.adaptive#976]
details of issue in https://github.com/xbmc/xbmc/issues/20742

IA handles DemuxRead calls appropriately when we reach the live edge of the manifest (sets `WAITFORSEGMENT`) and empty demux packets are returned until this condition changes.

For cases when we're waiting on data, (need to confirm properly) it seems we just make VP wait.

**Comment by glennguy** [comment]
@david-morris @kontell this is behind the issues you opened

**Comment by kontell** [comment]
Well done on narrowing down the issue, let me know if you want any testing done.

**Comment by glennguy** [comment]
Closed with #1008
