### ISSUE TITLE
InputStream Adaptive: Could not open / parse mpdURL

### ISSUE THREAD

**Issue by Jezze83** [peak3d/inputstream.adaptive#98]
Im not sure if this is right place but lets see. Im using latest libreelec and i have a problem with viaplay addon. Sports works fine but movies and series wont. I have latest inputsream adaptive and libreelec running with raspberry pi 3. Here is log file for error message:

https://pastebin.com/zUvMGYVN

**Comment by peak3d** [comment]
Outdated log / pls. use the addon support page (viaplay) at forum.kodi.tv
