### ISSUE TITLE
Can't play, Kodi crashed.

### ISSUE THREAD

**Issue by mbebe** [peak3d/inputstream.adaptive#999]
Can't play this mpd, and can't get log, because KODI crashed when starts playing.
It's a different mpd file than normal.
[manifestvix.txt](https://github.com/xbmc/inputstream.adaptive/files/8837633/manifestvix.txt)

I tried add BaseUrl to Initialization sourceURL and to SegmentURL media and effect is the same.
mpd from vix.com/es-es/canales - need US IP.
Kodi 19, Windows

**Comment by glennguy** [comment]
> and can't get log, because KODI crashed when starts playing.

The log should still exist after Kodi crashes though right? Can you grab it from your device manually?

**Comment by mbebe** [comment]
End of LOG is always in the same time.
[log.txt](https://github.com/xbmc/inputstream.adaptive/files/8837789/log.txt)
Maybe is the same like in: https://github.com/xbmc/inputstream.adaptive/issues/288
My mpd is similar.

**Comment by glennguy** [comment]
Thanks for the log file, it shows that IA is crashing on parsing the mpd file.

Removing this section allows parsing to occur:
```
<SegmentList presentationTimeOffset="19610958" timescale="1000" startNumber="8">
	<SegmentTimeline>
		<S d="6006" t="19652966"/>
		<S d="6006" t="19658972"/>
		<S d="5973" t="19664978"/>
		<S d="6006" t="19670951"/>
		<S d="6006" t="19676957"/>
		<S d="6006" t="19682963"/>
		<S d="6006" t="19688969"/>
		<S d="6006" t="19694975"/>
		<S d="5973" t="19700981"/>
		<S d="6006" t="19706954"/>
		<S d="6006" t="19712960"/>
		<S d="6006" t="19718966"/>
		<S d="6006" t="19724972"/>
		<S d="5972" t="19730978"/>
		<S d="6006" t="19736950"/>
		<S d="2603" t="19742956"/>
	</SegmentTimeline>
</SegmentList>
```

It's very strange - I'm not really sure what this is meant to actually do. Segments should belong to a representation... segment timelines belong to segment templates... almost appears to be bad output from a packager.

I don't have a VPN/US IP to test the actual stream/. Could you try this stream in the reference DASH player here https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html to see if it plays correctly?

**Comment by mbebe** [comment]
At https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html   error occurs - Error Dash.js :32
There are no periods in the MPD nostreamscomposed 


but here - https://developer-tools.jwplayer.com/stream-tester
stream is working correctly.

*edited:
after removing this part 
```
(<SegmentList[^>].*?<\/SegmentList>)  [0]
```


by proxy stream starts.
![hji](https://user-images.githubusercontent.com/30195202/172241116-2e65f5db-9d60-4ddf-840b-1526668e93b8.jpg)

**Comment by glennguy** [comment]
Thanks @mbebe for testing. I'm sure we can get these tags ignored, please keep the issue open for tracking
